python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
Fixes: #12463 
This PR handles any kind of outdated pandas index metadata in `from_arrow` by ignoring it.
=> [REVIEW] Fix `from_arrow` to load a sliced arrow table 

docs/cudf/source/api_docs/dataframe.rst
Removes documentation for `DataFrame.quantiles`, which was deprecated and then removed in #12281. This issue was discovered while building the docs in #12592.
=> Remove DataFrame.quantiles from docs.

java/src/main/native/src/RmmJni.cpp
Fixes a bug introduced here https://github.com/rapidsai/cudf/pull/12632 where the C++ version of the jni call `Rmm.newCudaAsyncMemoryResource` was taking an extra argument (`child`), causing the `threshold` to be set to a random value since the calling code defined the native method has taking 2 longs, not 3.
The above can affect performance if the threshold is set to 0 for example. The async pool will reduce its footprint by releasing memory, which means we need to go back and reallocate. This is how I found it.
I am starting the build process for this, so it's going to take me a bit to test.
=> [JNI] Remove child fom newCudaAsyncMemoryResource

conda/recipes/cudf/meta.yaml, conda/recipes/cudf_kafka/meta.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/libcudf/meta.yaml, conda/recipes/strings_udf/meta.yaml
This PR moves the date string from the version to the build string for conda recipes in this repository.
This is necessary to ensure that the conda packages resulting from PR builds can be installed in the same environment as nightly conda packages, which is useful for testing purposes.
Additionally, this prevents a bug from occurring where the Python builds fail because the date string it computes is different than the one computed by the C++ build, therefore causing the Python build to search for a C++ build artifact that doesn't exist.
xref: https://github.com/rapidsai/rmm/pull/1195
=> Move date to build string in `conda` recipe

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Signed-off-by: Cindy Jiang <cindyj@nvidia.com>
This PR adds [extract, extract_all_record](https://docs.rapids.ai/api/libcudf/nightly/strings_2extract_8hpp.html) related `regex_program` java APIs and unit tests.
Part of work for https://github.com/NVIDIA/spark-rapids/issues/7295.
=> Add `regex_program` strings extract java APIs and tests

.github/workflows/build.yaml, ci/benchmark/build.sh, ci/cpu/build.sh, ci/gpu/build.sh, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/dask-cudf/run_test.sh, dependencies.yaml, python/dask_cudf/setup.py
This PR pins `dask` and `distributed` to `2023.1.1` for `23.02` release.
=> [REVIEW] Pin `dask` and `distributed` for release

ci/test_java.sh, dependencies.yaml
The `latest` CI container was recently updated from CUDA 11.5 to CUDA 11.8. Due to some changes in the image, there are no compilers or `make`. To address this, I added the `build` dependency list to the `test_java` file in `dependencies.yaml`.
=> Add build dependencies to Java tests.

python/cudf/cudf/core/groupby/__init__.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_doctests.py
This PR enables doctests for some GroupBy methods that are not currently tested due to not meeting the inclusion criteria in our doctest class. This includes enabling tests for `GroupBy.apply` with `engine='jit'`. 
came up during https://github.com/rapidsai/cudf/pull/11452
=> Enable doctests for GroupBy methods

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR adds [split_re, rsplit_re, split_record_re, rsplit_record_re](https://docs.rapids.ai/api/libcudf/nightly/split__re_8hpp.html) related `regex_program` java APIs and unit tests.
Part of work for https://github.com/NVIDIA/spark-rapids/issues/7295.
=> Add `regex_program` strings splitting java APIs and tests

cpp/src/io/parquet/page_data.cu
Fixes an issue with a particular arrangement of page data related to lists.  Specifically, it is possible for page `N` to contain "0" rows because the values for the row it is a part of start on page `N-1` and end on page `N+1`.  This was defeating logic in the decode kernel that would erroneously cause these values to be skipped.
Similar to https://github.com/rapidsai/cudf/pull/12488 this is only reproducible with data out in the wild.  In this case, we have a file that we could in theory check in to create a test with, but it is 16 MB so it's fairly large.  Looking for feedback on whether this is too big.
=> Handle parquet list data corner case

python/cudf/setup.py, python/dask_cudf/setup.py
We introduced a change to pin RAPIDS wheel dependencies to the same release version. However, branch 23.04 was created before that last PR was merged, so as of now cudf's 23.4 wheels are installing 23.2 RAPIDS dependencies. This PR updates those pins to the current release.
=> Bump pinned rapids wheel deps to 23.4

java/src/main/java/ai/rapids/cudf/Table.java, java/src/main/native/src/TableJni.cpp
Signed-off-by: Liangcai Li <firestarmanllc@gmail.com>
This PR is exposing the `seed` parameter for the JNI hash partition APIs to support customizing the hash algorithm seed.
The existing tests should cover this change.
=> Allow setting the seed argument for hash partition

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py, python/cudf_kafka/setup.py
This PR adds `dtypes` property to `GroupBy`, this will also fix some upstream dask breaking changes introduced in: https://github.com/dask/dask/pull/9889
Issue was discovered in: https://github.com/rapidsai/cudf/pull/12768#issuecomment-1430650703
=> [REVIEW] Add `GroupBy.dtypes`

cpp/src/io/json/write_json.cu, cpp/tests/io/json_writer.cpp
All-null list is considered as empty list in `join_list_elements`. So, nulls of children are replaced by `narep` before passing to `join_list_elements` API.
Related https://github.com/rapidsai/cudf/issues/12766
=> Fix bug in all-null list due to join_list_elements special handling

python/cudf_kafka/setup.py
The changes to spdlog/fmt packaging in rmm caused an undefined symbol issue in cudf_kafka. To unblock CI in https://github.com/rapidsai/cudf/pull/12783, I simply added fmt to the list of required libraries for the Python package (see https://github.com/rapidsai/cudf/pull/12783/commits/caf7adfb9a89e585bd4d3239c79643328449a242 and [the explanation](https://github.com/rapidsai/cudf/pull/12783#issuecomment-1431997720)). The underlying issue turns out to be that by default usage of fmt results in the dependent assuming that the headers are compiled in not header-only mode. When using CMake to manage the build, fmt relies on use of the appropriate target `fmt::fmt-header-only` to configure the build such that anything using fmt knows to use it in header-only mode, which sets the …
=> Tell cudf_kafka to use header-only fmt

java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java, java/src/test/java/ai/rapids/cudf/ScalarTest.java, java/src/test/java/ai/rapids/cudf/TableTest.java
Fix a small leak of host memory in a java unit test. Also updates some tests that verify that a double free is safe, but don't make it clear from the logs that the double free is expected to be there. This is so we don't have to spend too much time debugging if this double free is expected or not.
=> Fix a leak in a test and clarify some test names

cpp/src/io/parquet/reader_impl_preprocess.cu
When digging through the new chunk writer for parquet pipelined reads, I noticed that the code changed and the read coalescing was no longer happening. Through some checking, I found that tests were issuing multiple smaller reads, specifically a read per rowgroup instead of a single read for multiple rowgroups. With this change, there is a single read per file.
I believe this is an unintentional change and a departure from the previous behavior.
=> Fixing parquet coalescing of reads

python/cudf/cudf/api/types.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/series.py
This PR updates `value_counts` behavior to match `pandas-2.x`, the result name will be `count` (or `proportion` if `normalize=True` is passed), and the index will be named after the original object name. This PR also fixes two dtype APIs that are breaking changes on pandas side.
Here are the pytests that were run locally to test these changes :
```python
(cudfdev) pgali@dt07:/nvme/0/pgali/cudf$ pytest python/cudf/cudf/tests/test_dataframe.py::test_value_counts
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 …
```
=> [REVIEW] Adapt `value_counts` behavior to match `pandas-2.x`

python/cudf/cudf/benchmarks/get_datasets.py
Update datasets download URL to reduce latency and costs
=> Update datasets download URL

ci/test_cpp_memcheck.sh
Removes the `KAFKA_HOST_TEST` from the compute-sanitizer memcheck nighly runs. 
The following error occurs when running this host test.
```
Running compute-sanitizer on KAFKA_HOST_TEST
========= COMPUTE-SANITIZER
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from KafkaDatasourceTest
[ RUN      ] KafkaDatasourceTest.MissingGroupID
[       OK ] KafkaDatasourceTest.MissingGroupID (0 ms)
[ RUN      ] KafkaDatasourceTest.InvalidConfigValues
[       OK ] KafkaDatasourceTest.InvalidConfigValues (0 ms)
[----------] 2 tests from KafkaDatasourceTest (0 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
========= …
```
=> Remove KAFKA_HOST_TEST from compute-sanitizer check

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/tests/test_categorical.py
This PR drops `inplace` parameters in categorical methods, these are also removed as part of pandas-2.0
=> [REVIEW] Drop `inplace` parameter in categorical methods

.pre-commit-config.yaml, docs/cudf/source/user_guide/10min.ipynb, docs/cudf/source/user_guide/cupy-interop.ipynb, docs/cudf/source/user_guide/guide-to-udfs.ipynb, docs/cudf/source/user_guide/missing-data.ipynb
This enables `black` and `isort` linters for ipynb notebooks via [nbqa](https://github.com/nbQA-dev/nbQA). I propose this change to avoid manually linting notebooks like https://github.com/rapidsai/cudf/pull/12595. cc: @galipremsagar
=> Enable nbqa pre-commit hooks for isort and black.

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_rank.py
This PR raises an error when `numeric_only=True` for `rank` if the Series is of non-numeric dtype.
=> [REVIEW] Raise error when `numeric_only=True` for non-numeric Series

docs/cudf/source/api_docs/index_objects.rst, python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_monotonic.py
This PR drops support for `Series.is_monotonic` & `Index.is_monotonic`. Instead, the alternative will be `.is_monotonic_increasing`.
=> [REVIEW] Drop `is_monotonic` from `Series` and `Index`

python/cudf/cudf/__init__.py
Following https://github.com/rapidsai/rmm/pull/1221, RMM allocators now live under the `rmm.allocators` submodule and using old paths causes warnings to be raised. This change updates to the new submodule and prevents such warnings.
=> Update RMM allocators

docs/cudf/source/conf.py
This PR fixes cudf docs build to be compatible with `pydata-sphinx-theme=0.13.0` by adding an empty `icon_links` entry.
=> [REVIEW] Fix docs build to be `pydata-sphinx-theme=0.13.0` compatible

cpp/src/io/parquet/writer_impl.cu
Fixes #12867.
Bug introduced in #12685. A calculation of total bytes in a column was returned in a 32-bit `size_type` rather than 64-bit `size_t` leading to overflow for tables with many millions of rows.
=> Parquet writer column_size() should return a size_t

.github/workflows/pr.yaml, .github/workflows/test.yaml
Nightly wheel tests are failing with this error:
```
+ sh -c 'pytest -v -n 8 ./python/cudf/cudf/tests'
sh: 1: pytest: not found
```
However, pytest is being installed.
The wheel itself is being installed with `python -m pip`, like:
```
python -m pip install --verbose './dist/cudf_cu11-23.4.0.1677647948-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl[test]'
```
Calling `python -m pytest` may resolve this error. For consistency, we should use `python -m` for all executable modules (pip and pytest).
=> Use python -m pytest for nightly wheel tests

python/cudf/cudf/tests/test_df_protocol.py
The most recent versions of cupy now support bool arrays in dlpack (see [the release notes](https://github.com/cupy/cupy/releases/tag/v11.6.0) and [the PR adding the feature](https://github.com/cupy/cupy/pull/7376)). Our DataFrame protocol tests were expecting a failure.
=> Expect cupy to now support bool arrays for dlpack.

cpp/src/io/parquet/parquet_gpu.hpp
Arguments are swapped in declaration (and thus docs as well). Args are passed as required by the definition when `ComputePageSizes` is called.
=> min_rows and num_rows are swapped in ComputePageSizes declaration in Parquet reader

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_series.py, python/cudf/cudf/utils/docutils.py
This PR removes support for `datetime_is_numeric` parameter in `describe`.
=> [REVIEW] Drop `datetime_is_numeric` parameter from `describe`

python/cudf/cudf/core/index.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_multiindex.py
This PR removes `dtype` in `Index & MultiIndex`.`copy`, and `names` in `Index.copy`
=> [REVIEW] Drop `names`, `dtype` in `Index.copy` and `dtype`, `levels`, `codes` in `MultiIndex.copy`

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_monotonic.py
This PR drops `kind` parameter from `Index.get_slice_bound` to match pandas-2.0 API.
=> [REVIEW] Drop `kind` parameter from `Index.get_slice_bound`

conda/recipes/cudf/meta.yaml, conda/recipes/cudf_kafka/meta.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/libcudf/meta.yaml
This PR passes `SCCACHE_S3_USE_SSL` to the conda build environment
`SCCACHE_S3_USE_SSL` has been reported to increase `sccache` performance for S3.
=> Pass `SCCACHE_S3_USE_SSL` to conda builds

cpp/tests/io/text/data_chunk_source_test.cpp, cpp/tests/io/text/multibyte_split_test.cpp
Fixes DATA_CHUNK_SOURCE_TEST gtests source files coded in namespace cudf::test
Fixes MULTIBYTE_SPLIT_TEST gtests source files coded in namespace cudf::test
=> Fix io/text gtests coded in namespace cudf::test

cpp/benchmarks/binaryop/compiled_binaryop.cpp, cpp/benchmarks/groupby/group_rank.cpp, cpp/benchmarks/lists/copying/scatter_lists.cu
Fixes BINARYOP_BENCH, GROUPBY_NVBENCH benchmarks from using namespace cudf directly.
Fixes SCATTER_LISTS_BENCH benchmarks coded in namespace cudf
=> Fix benchmarks coded in namespace cudf and using namespace cudf

cpp/benchmarks/common/generate_input.cu, cpp/tests/copying/gather_struct_tests.cpp, cpp/tests/io/parquet_test.cpp, cpp/tests/lists/explode_tests.cpp, cpp/tests/reductions/tdigest_tests.cu, cpp/tests/sort/sort_test.cpp, cpp/tests/stream_compaction/apply_boolean_mask_tests.cpp, cpp/tests/structs/structs_column_tests.cpp, cpp/tests/transform/row_bit_count_test.cu, cpp/tests/utilities_tests/lists_column_wrapper_tests.cpp
Removing some unneeded usages of `cudf::UNKNOWN_NULL_COUNT` specifically in libcudf gtests source files.
These were found when working on other PRs. 
Reducing the usage like this hopefully will move us closer to not using it at all.
There are few places in the gtest source files where we still use it even though the number of nulls is technically known but these may be fixed by adding and using some new test utilities in a future PR.
=> Fix libcudf gtests to pass null-count=0 for empty validity masks

cpp/src/io/parquet/chunk_dict.cu
Contributes to #11844
This PR migrates parquet encoding to use the experimental `nan_equal` equality check instead of the legacy `equality_compare`.
=> Migrate parquet encoding to use experimental row operators

cpp/src/rolling/detail/rolling_collect_list.cuh
Updated code to use defaulted argument get_current_device_resource() for intermediate allocations in COLLECT_LIST window code
one-line fix.
Fixes https://github.com/rapidsai/cudf/issues/8219
=> Use get_current_device_resource for intermediate allocations in COLLECT_LIST window code

cpp/src/interop/from_arrow.cu
libcudf bitmasks are allocated to a multiple of 64 bytes, in contrast the arrow spec only requires of a column with a null mask that "the validity bitmap must be large enough to have at least 1 bit for each array slot". When the number of rows is not a multiple of 64, the trailing part of the device allocation (which doesn't contribute to actually masking anything) is left uninitialized. While probably benign, this produces errors when running with compute-sanitizer in initcheck mode (since those data are touched and _are_ uninitialized).
To fix this, memset the trailing allocation to zero.
Closes #8873.
=> Ensure all of device bitmask is initialized in from_arrow

python/cudf/cudf/core/algorithms.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/tests/test_series.py
This PR drops support for `na_sentinel` in `factorize` APIs, to match with pandas-2.0
=> [REVIEW] Drop `na_sentinel` from `factorize`

build.sh
This PR moves the `build_ext` step to only happen when `INSTALL_TARGET==''`, thus avoiding the cython build to occur twice when `build.sh` is invoked.
=> [REVIEW] Avoid building cython twice

python/cudf/cudf/core/window/rolling.py, python/cudf/cudf/tests/test_rolling.py
This PR fixes an issue with Series rolling window operations where there is a failure because `Series.set_index` has been dropped in the previous release.
=> [REVIEW] Fix set index error for Series rolling window operations

cpp/src/io/avro/avro.cpp, cpp/src/io/avro/avro.hpp, cpp/src/io/avro/avro_common.hpp, cpp/src/io/avro/avro_gpu.cu, cpp/src/io/avro/avro_gpu.hpp, cpp/src/io/avro/reader_impl.cu, python/cudf/cudf/tests/test_avro_reader_fastavro_integration.py
This includes the date type.  Scaffolding has been put in place to handle the other logical types.  This closes #6482.
=> Implement initial support for avro logical types (#6482)

conda/recipes/libcudf/meta.yaml, cpp/CMakeLists.txt
cudftestutil needs to be statically so that it can support gtest. So to allow this and the preload hooks we have to roll `tests/utilities/default_stream.cpp` into a separate lib.
Will correct downstream issues including: https://github.com/NVIDIA/spark-rapids-jni/issues/1006
=> cudftestutil supports static gtest dependencies

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
Google test is currently being pulled via CPM when our packages are being built instead of using the conda package. This results in gtest (and all its CMake files) being bundled into the cudf package, which interferes with package discovery.
=> Include gtest in build environment.

cpp/include/cudf/detail/reshape.hpp, cpp/include/cudf/io/detail/csv.hpp, cpp/include/cudf/io/detail/tokenize_json.hpp, cpp/include/cudf/lists/detail/combine.hpp, cpp/include/cudf/lists/detail/set_operations.hpp, cpp/src/copying/get_element.cu, cpp/src/filling/fill.cu, cpp/src/filling/sequence.cu, cpp/src/io/csv/durations.hpp, cpp/src/io/json/json_column.cu, cpp/src/lists/set_operations.cu, cpp/tests/io/json_tree.cpp, cpp/tests/io/nested_json_test.cpp
This is the fifth PR in a sequence removing default mr parameters in detail APIs. Contributes to https://github.com/rapidsai/cudf/issues/12944.
=> Remove default detail mrs: part5

python/cudf/cudf/tests/test_setitem.py, python/cudf/cudf/utils/dtypes.py
Since numpy strings are fixed width and use a null byte as an
indicator of the end of the string, there is no way to distinguish
between numpy.str_("abc\x00").item() and numpy.str_("abc").item().
This has consequences for scalar preprocessing we do when constructing
a cudf.Scalar, since that usually goes through
numpy.astype(...).item(). So, when preprocessing as scalar, if we
notice it is a string with trailing null bytes, keep it as is.
Closes #12990.
=> Fix `__setitem__` on string columns when the scalar value ends in a null byte

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/cudf/meta.yaml, dependencies.yaml, python/cudf/pyproject.toml, python/dask_cudf/pyproject.toml
Changes in the upcoming numba 0.57 release will break cudf until we've had time to adapt them, which will not happen in 23.04.
=> Pin numba version

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Adds the JNI API for `stringReplace` using column vector arguments for `targets` and `repls` (to make this consistent with the C++ API). Also adds unit tests for the new API.
Part of the work for https://github.com/NVIDIA/spark-rapids/issues/7907.
=> Add JNI method for strings::replace multi variety

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
Fixes: #12646
This PR fixes an issue with `DataFrame` where broadcasting scalar inputs was order dependent.
=> [REVIEW] Fix `DataFrame` constructor to broadcast scalar inputs properly

python/cudf/cudf/core/groupby/groupby.py
Closes https://github.com/rapidsai/cudf/issues/12986.
=> Fix `GroupBy.apply` doc examples rendering

python/cudf/cudf/_lib/parquet.pyx, python/cudf/cudf/tests/test_parquet.py
`force_nullable_schema` was introduced in https://github.com/rapidsai/cudf/pull/12952, however strangely only after it has been merged to `branch-23.04` we are seeing the following pytest failure occur locally:
```python
(cudfdev) pgali@dt07:/nvme/0/pgali/cudf$ pytest python/dask_cudf/dask_cudf/io/tests/test_parquet.py::test_cudf_list_struct_write
====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.10.9, pytest-7.2.2, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: …
```
=> [REVIEW] Drop `force_nullable_schema` from chunked parquet writer

cpp/tests/utilities/column_utilities.cu
Fixes a bug introduced in #12777 (by me) in `column_utilities.cu` that caused the difference reporting in a failed comparison in a gtest result (i.e. through `CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT` for example) to report the incorrect row.
The logic was changed to improve compile time but incorrectly created indices of only 0s and 1s in the difference vector.
This PR fixes the logic to create the correct indices for the reporting logic.
=> Fix gtest column utility comparator diff reporting

ci/test_cpp_memcheck.sh
The nightly runs of `compute-sanitizer` started failing due to the test script trying to execute some new extra files found in the `$CONDA_PREFIX"/bin/gtests/libcudf/` directory. This change ensures only files ending in `_TEST` are executed by `compute-sanitizer`.
For reference errors are here: https://github.com/rapidsai/cudf/actions/runs/4508267264/jobs/7936800047
Example:
```
Running compute-sanitizer on CTestTestfile.cmake
========= COMPUTE-SANITIZER
========= Error: Target application terminated before first instrumented API call
```
Follow on issue/PR could explore adding a special make option to execute `compute-sanitizer` only on test files.
=> Fix memcheck script to execute only _TEST files found in bin/gtests/libcudf

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
Fixes: #12759 
This PR fixes the above issue by factoring in index names while performing a `groupby` by label name.
=> [REVIEW] Handle index names while performing `groupby`

ci/build_docs.sh
Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> Forward-merge branch-23.04 to branch-23.06

conda/recipes/cudf/meta.yaml, conda/recipes/dask-cudf/meta.yaml
This PR removes the underscore after "cuda" to align with other RAPIDS packages.
=> Remove underscore in build string.

java/ci/README.md, java/pom.xml
Bump up JNI version to 23.06.0-SNAPSHOT
=> Bump up JNI version 23.06.0-SNAPSHOT

cpp/tests/io/json_test.cpp, cpp/tests/reductions/reduction_tests.cpp
Removes some `std::cout` output from some libcudf gtests. These were found while investigating compute-sanitizer test errors.
Also, the `StringReductionTest` gtest was attempting to print an invalid string.
=> Remove console output from some libcudf gtests

python/cudf/cudf/tests/test_parquet.py, python/cudf/cudf/tests/test_reshape.py, python/cudf/cudf/tests/test_stats.py, python/cudf/cudf/tests/test_string.py
This PR contains miscellaneous fixes in pytests. The changes in pytests are due to suttle changes in behaviors from the pandas-2.0 side.
=> [REVIEW] Miscellaneous pytest fixes for pandas-2.0

python/cudf/cudf/_lib/cpp/strings/regex_program.pxd, python/cudf/cudf/_lib/strings/contains.pyx, python/cudf/cudf/_lib/strings/extract.pyx, python/cudf/cudf/_lib/strings/findall.pyx, python/cudf/cudf/_lib/strings/replace_re.pyx, python/cudf/cudf/_lib/strings/split/split.pyx, python/cudf/cudf/tests/test_string.py
Add the `except +` declaration to the `cudf::strings::regex_program::create()` function in the Cython `regex_program.pxd` interface since invalid regex patterns are thrown by this call. This allows the normal Cython exception handling to pass the exception to the Python logic without aborting the process.
Closes #13052
=> Add except declaration in Cython interface for regex_program::create

cpp/tests/utilities/identify_stream_usage.cpp
The identify_stream_usage test uses `strcmp` but not does not include `<cstring>`. This PR fixes that.
The missing include was surfaced by #13064, showing that the test relied on headers in `spdlog` to include `cstring`.
=> Fix tests/identify_stream_usage.cpp

cpp/include/cudf/io/data_sink.hpp
`data_sink.hpp` uses `std::transform` but not does not include <algorithm>. This PR fixes that.
The missing include was surfaced by https://github.com/rapidsai/cudf/pull/13064.
=> Add algorithm include in data_sink.hpp

.github/workflows/pr.yaml, .github/workflows/test.yaml, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/dask-cudf/run_test.sh, dependencies.yaml, python/dask_cudf/pyproject.toml
This PR resolves conflicts in: https://github.com/rapidsai/cudf/pull/13075
=> Resolved automerger from `branch-23.04` to `branch-23.06`

cpp/benchmarks/io/orc/orc_reader_options.cpp, cpp/benchmarks/io/parquet/parquet_reader_options.cpp
Helper function `get_col_names` in the Parquet reader benchmarks throws with nested columns. It should instead just ignore the children columns and return the top-level colum names.
Also renamed the function to better reflect what it does.
=> Fix column selection `read_parquet` benchmarks

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_array_ufunc.py
Pandas 2.0 introduced support for ufuncs when the two columns are indexed. This PR updates the pytests accordingly.
=> [REVIEW] Fix pytests to add coverage for index ufunc support introduced in `pandas-2.0`

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_avro_reader_fastavro_integration.py, python/cudf/cudf/tests/test_datetime.py
=> Raise `NotImplementedError` when attempting to construct cuDF objects from timezone-aware datetimes

cpp/include/cudf/strings/contains.hpp, cpp/include/cudf/strings/extract.hpp, cpp/include/cudf/strings/findall.hpp, cpp/include/cudf/strings/replace_re.hpp, cpp/include/cudf/strings/split/split_re.hpp, cpp/src/strings/contains.cu, cpp/src/strings/extract/extract.cu, cpp/src/strings/extract/extract_all.cu, cpp/src/strings/replace/backref_re.cu, cpp/src/strings/replace/replace_re.cu, cpp/src/strings/search/findall.cu, cpp/src/strings/split/split_re.cu
Removes the libcudf regex APIs that were deprecated in 23.04. All calls to these functions within the repo had already been removed.
Marking this breaking since APIs are being removed.
=> Remove deprecated regex functions from libcudf

cpp/src/io/parquet/page_data.cu
Fixes a minor compile error/warnings for unused variables in the `cpp/src/io/parquet/page_data.cu` source file.
```
cudf/cpp/src/io/parquet/page_data.cu -o CMakeFiles/cudf.dir/src/io/parquet/page_data.cu.o
/cudf/cpp/src/io/parquet/page_data.cu(636): error #177-D: parameter "s" was declared but never referenced
/cudf/cpp/src/io/parquet/page_data.cu(343): error #177-D: parameter "sb" was declared but never referenced
detected during instantiation of "cuda::std::__4::pair<int, int> cudf::io::parquet::gpu::<unnamed>::gpuDecodeDictionaryIndices<sizes_only>(volatile cudf::io::parquet::gpu::<unnamed>::page_state_s *, volatile cudf::io::parquet::gpu::<unnamed>::page_state_buffers_s *, int, int) [with sizes_only=true]" 
(1720): here
/cudf/cpp/src/io/parquet/page_data.cu(527): error #177-D: …
```
=> Fix unused variable error/warning in page_data.cu

build.sh, java/pom.xml
Changes the `GPU_ARCHS` setting in `pom.xml` from `ALL` to `RAPIDS` per recent change in rapidsai/rapids-cmake/pull/397
The Python package build requires CUDA as of the addition of string UDFs, which added compilation of ptx code to the Python build. Therefore CMAKE_CUDA_ARCHITECTURES must be set appropriately even when only the Python package is being built. https://github.com/rapidsai/rapids-cmake/pull/397 requires a nonempty string value to be used if the variable is set at all. This PR updates build.sh to include the appropriate default when only the Python build is requested.
=> Fix GPU_ARCHS setting in Java CMake build and CMAKE_CUDA_ARCHITECTURES in Python package build.

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
Merging the conda-forge curand recipe and building conda-forge packages has caused conda to choose a newer version of curand than what cudf currently supports (we cannot use the version from CUDA 12).
Closes #13126
=> Pin curand version

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
=> Branch 23.06 merge 23.04

cpp/src/io/json/nested_json_gpu.cu
The JSON reader is currently using 32-bit offsets to index into the input's characters to lower memory footprint and for performance reasons. Hence, currently, if an input larger than `UINT_MAX` is read, the parser may return incorrect data. 
This PR adds a check that fails for inputs that could overflow. 
The longer term plan is to make the finite-state transducer stage reentrant and split up inputs larger than `UINT_MAX` into smaller chunks.
=> Adds checks to make sure json reader won't overflow

cpp/src/io/parquet/page_data.cu, cpp/src/io/utilities/column_buffer.cpp, cpp/tests/io/parquet_chunked_reader_test.cpp
Chunked Parquet reader returns columns with incorrect null counts - the counts are cumulative sums that include all previous chunks.
Root cause is that `nesting_decode_cache` is not copied back to `nesting_decode` when `gpuDecodePageData` returns early, so previously computed null counts are only reset in the cache.
With this PR, we use RAII to make sure cached decode info is always copied back in `gpuDecodePageData`.
Also fixed `column_buffer::empty_like` to return zero null count and empty null mask.
=> Fix `null_count` of columns returned by `chunked_parquet_reader`

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/series.py, python/cudf/cudf/testing/_utils.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_series.py
Fixes: #12999, #13056
This PR fixes the `Series` and `DataFrame` constructors to validate the `data` & `index` lengths. This also contains fixes where `index` was being ignored in certain cases.
=> [REVIEW] Fix `Series` and `DataFrame` constructors to validate index lengths

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/tests/test_array_ufunc.py, python/cudf/cudf/tests/test_dataframe.py
This PR enables `numeric_only` for row-wise ops to be on parity with pandas-2.0.
=> [REVIEW] Enable `numeric_only` for row-wise ops

cpp/src/io/orc/orc.cpp, cpp/src/io/orc/orc.hpp
Replaced `std::make_tuple` with `std::tuple` constructor
Removed `std::make_field_reader`, calling `field_reader` constructor directly now.
=> Use CTAD instead of functions in ProtobufReader

cpp/include/cudf/detail/copy.hpp, cpp/src/column/column.cu, cpp/src/copying/get_element.cu, cpp/src/copying/slice.cu, cpp/src/groupby/sort/sort_helper.cu, cpp/src/interop/from_arrow.cu, cpp/src/stream_compaction/unique.cu, cpp/tests/transform/mask_to_bools_test.cpp, cpp/tests/utilities/column_utilities.cu
Calculates the null-count in the `cudf::detail::slice()` function. This requires adding a stream parameter to the function and updating the callers to pass the stream. Also moved the function definition to the `slice.cu` file since there are only two possible values for the template parameter.
Labeling this with non-breaking since it is a detail function.
Contributes to: https://github.com/rapidsai/cudf/issues/11968
=> Compute null-count in cudf::detail::slice

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_groupby.py
This PR deprecates `pad` and `backfill` methods in favor of `ffill` and `bfill` methods.
Pandas recently deprecated these:
https://github.com/pandas-dev/pandas/pull/51221
https://github.com/pandas-dev/pandas/pull/45076
=> [REVIEW] Deprecate `pad` and `backfill` methods

python/cudf/cudf/core/dataframe.py
This PR updates `DataFrame.__getitem__` to be able to work with pandas-2.0. For which, we conditionally pass `dtype` to `pandas.Series` constructor so that we don't get a warning in `<2.0` versions.
This PR also fixes 76 pytests:
```
= 907 failed, 86353 passed, 2034 skipped, 992 xfailed, 165 xpassed in 504.93s (0:08:24) =
```
on `pandas_2.0_feature_branch`:
```
= 983 failed, 86277 passed, 2034 skipped, 992 xfailed, 165 xpassed in 515.47s (0:08:35) =
```
=> [REVIEW] Fix `DataFrame.__getitem__` to work with `pandas-2.0`

cpp/tests/stream_compaction/distinct_tests.cpp, cpp/tests/stream_compaction/unique_tests.cpp
Fixes some build errors occuring after https://github.com/rapidsai/cudf/pull/13133 was merged. Looks like a couple files may have gotten mismerged perhaps. This should unblock several current PRs.
=> Fix a few clang-format style check errors

cpp/src/io/avro/avro.cpp, cpp/src/io/avro/avro.hpp, cpp/src/io/avro/avro_common.hpp, cpp/src/io/avro/avro_gpu.cu, cpp/src/io/avro/avro_gpu.hpp, cpp/src/io/avro/reader_impl.cu, python/cudf/cudf/tests/test_avro_reader_fastavro_integration.py
This PR fixes the avro reader (`cudf.read_avro()`) such that it honors the values passed to the `skip_rows` and `num_rows` parameters.  In implementing this new logic, we also revamp the reader's ability to handle multi-block avro files, which we also test extensively with a new `test_avro_reader_multiblock()` test that features some 1300 permutations of various block size combinations.
Closes #6529.
=> Fix read_avro() skip_rows and num_rows.

docs/cudf/source/api_docs/groupby.rst, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
This PR drops support for `pad` and `backfill` in `GroupBy`.
This PR:
```
= 881 failed, 86383 passed, 2034 skipped, 956 xfailed, 165 xpassed in 522.05s (0:08:42) =
```
```
= 911 failed, 86389 passed, 2034 skipped, 956 xfailed, 165 xpassed in 521.12s (0:08:41) =
```
=> [REVIEW] Drop support for `pad` and `backfill` in `GroupBy`

python/cudf/cudf/api/types.py, python/cudf/cudf/tests/test_api_types.py
With `pandas-2.0`, `pd.api.types.is_string_dtype(obj)` is going to perform a data-introspection to determine the true dtype of the underlying data. This path won't work for gpu objects, hence this PR adds special handling for GPU objects before we hit `pd.api.types.is_string_dtype(obj)` API.
This PR fixes 56 pytests:
```
= 927 failed, 86333 passed, 2034 skipped, 992 xfailed, 165 xpassed in 506.69s (0:08:26) =
```
```
= 983 failed, 86277 passed, 2034 skipped, 992 xfailed, 165 xpassed in 557.07s (0:09:17) =
```
=> [REVIEW] Fix `is_string_dtype` to adapt to `pandas-2.0` changes

python/cudf/cudf/tests/test_dataframe.py
This PR adds pytest handling for wanring incase of `pad` and `backfill`.
=> [REVIEW] Handle pandas warnings for `pad` and `backfill`

python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/tests/test_datetime.py
This PR fixes some of the `to_datetime` related pytests and also raises error while constructing a time-zone un-aware type to datetime types.
This PR fixes 62 pytests:
```
= 745 failed, 87877 passed, 2044 skipped, 956 xfailed, 165 xpassed in 492.06s (0:08:12) =
```
```
= 807 failed, 87819 passed, 2044 skipped, 956 xfailed, 165 xpassed in 488.43s (0:08:08) =
```
=> [REVIEW] Fix datetime pytests & raise errors for timezone un-aware typecasting

cpp/include/cudf/lists/detail/scatter.cuh, cpp/tests/column/column_test.cu, cpp/tests/column/column_view_shallow_test.cpp, cpp/tests/groupby/rank_scan_tests.cpp, cpp/tests/reductions/rank_tests.cpp, cpp/tests/rolling/grouped_rolling_range_test.cpp, cpp/tests/transform/nans_to_null_test.cpp
Fix calls to the `column::set_null_mask()` function to always pass the null-count value in gtests source files.
Contributes to: https://github.com/rapidsai/cudf/issues/11968
=> Fix gtests to always pass null-count to set_null_mask calls

python/cudf/cudf/tests/test_dataframe.py
https://github.com/rapidsai/cudf/pull/12890 dropped support for `datetime_is_numeric` from `describe` API. This PR cleans-up a remaining pytest that was using this parameter.
This PR fixes 20 pytests:
```
= 464 failed, 88182 passed, 2044 skipped, 932 xfailed, 165 xpassed in 440.68s (0:07:20) =
```
```
= 484 failed, 88162 passed, 2044 skipped, 932 xfailed, 165 xpassed in 457.87s (0:07:37) =
```
=> [REVIEW] Fix `DataFrame.describe` pytests

python/cudf/cudf/_lib/transform.pyx, python/cudf/cudf/core/reshape.py, python/cudf/cudf/tests/test_onehot.py
This PR changes the default dtype for `get_dummies` to `bool` from `uint8` to match pandas-2.0: https://github.com/pandas-dev/pandas/pull/48022
=> [REVIEW] Change default `dtype` for `get_dummies` to `bool`

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/reshape.py, python/cudf/cudf/tests/test_reshape.py
This PR updates parameter ordering in `DataFrame.pivot` to match pandas-2.0.
This PR fixes 7 related pytests:
```
= 477 failed, 88169 passed, 2044 skipped, 932 xfailed, 165 xpassed in 438.55s (0:07:18) =
```
```
= 484 failed, 88162 passed, 2044 skipped, 932 xfailed, 165 xpassed in 457.87s (0:07:37) =
```
=> [REVIEW] Update parameter ordering in `DataFrame.pivot`

java/src/main/java/ai/rapids/cudf/Table.java, java/src/main/java/ai/rapids/cudf/WindowOptions.java, java/src/main/native/src/TableJni.cpp, java/src/test/java/ai/rapids/cudf/TableTest.java
This commit adds back-end JNI changes to support explicit range-extents for ranged window functions. The change is analogous to the addition of `cudf::range_window_bounds::extent_type`, in `libcudf`. This change will allow for `STRING` order-by columns for range window functions. It is required because without it, it would be impossible to differentiate between `UNBOUNDED` and `CURRENT ROW` for a window function over a `STRING` order-by column.
=> JNI changes for range-extents in window functions.

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, dependencies.yaml
Since rapids-cmake will now pull GTest 1.13, update cudf recipes so we don't get two versions of GTest installed.
=> Update cudf recipes to use GTest version to >=1.13

build.sh, java/ci/build-in-docker.sh
As part of https://github.com/rapidsai/cudf/pull/13071 changes were made to add tests that will fail unless assertions are off for those tests. This PR adds `ColumnViewNonEmptyNullsTest` to the list of skipped tests
=> Skip Non-Empty nulls tests for the nightly build just like we skip CuFileTest and CudaFatalTest

cpp/cmake/thirdparty/patches/nvbench_global_setup.diff
Fixes a build warning encountered by @nvdbaranec.
=> Add [[maybe_unused]] to nvbench environment.

cpp/benchmarks/io/parquet/parquet_reader_input.cpp
Adds a benchmark for the chunked parquet reader.
=> Add chunked reader benchmark

python/cudf/cudf/tests/test_stats.py
https://github.com/rapidsai/cudf/pull/12847 introduced support for `numeric_only`, this PR cleans up a `kurt` related pytest that was relying on the old behavior.
This PR fixes 18 pytests :
```
= 413 failed, 88257 passed, 2044 skipped, 932 xfailed, 165 xpassed in 463.03s (0:07:43) =
```
```
= 431 failed, 88221 passed, 2044 skipped, 932 xfailed, 165 xpassed in 456.25s (0:07:36) =
```
=> Fix `kurtosis` pytests to support `numeric_only` parameter

cpp/src/io/comp/nvcomp_adapter.cpp
Adds a mutex to guard the use of the memoization map for the status of nvCOMP features.
=> Make `is_decompression_disabled` and `is_compression_disabled` thread-safe

cpp/include/cudf/detail/contiguous_split.hpp, cpp/src/copying/pack.cpp
This PR introduces a helper class `metadata_builder` within the `cudf::detail` namespace, that allows `pack` and `contiguous_split` to create metadata for a packed buffer without having access to metadata internals (e.g. `serialized_column`).
The class makes it possible for callers to build metadata independent of the current implementations in `pack`, that are relying on `column_view`s being defined (actual valid cuDF columns). The chunked pack work will use this class to create metadata without needing to create a `column_view` in the first place, since it doesn't have a valid base pointer for the columns to be instantiated.
=> Add metadata_builder helper class

conda/recipes/cudf/meta.yaml, conda/recipes/cudf_kafka/meta.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/libcudf/meta.yaml
This change passes through the value of `SCCACHE_S3_NO_CREDENTIALS` to our `conda` builds, enabling devs to utilize the `sccache` cache that's populated by CI when they are reproducing build issues locally as per [these](https://docs.rapids.ai/resources/reproducing-ci/) instructions.
=> Enable sccache hits from local builds

python/cudf/cudf/testing/dataset_generator.py
Starting `mimesis=9.0.0`, the `generate_string` function has become private:
```python
In [1]: import mimesis
In [2]: mimesis.__version__
Out[2]: '9.0.0'
In [3]: mimesis.random.random.generate_string
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 mimesis.random.random.generate_string
AttributeError: 'Random' object has no attribute 'generate_string'
In [4]: mimesis.random.random._generate_string
Out[4]: <bound method Random._generate_string of <mimesis.random.Random object at 0x555992f65a20>>
```
This PR replaces all uses of the function with a homespun one. Note that the implementation is about as fast (perhaps identical?)
```python
In [6]: %timeit …
```
=> Roll our own generate_string() because mimesis' has gone away

cpp/src/io/parquet/writer_impl.cu
Fix some unused variables/parameters warnings introduced by https://github.com/rapidsai/cudf/pull/13076.
My old nvcc 11.5 compiler found these. Removing some of these found functions that could be removed as well.
Some variables/parameters are now declared with `[[maybe_unused]]`
```
/cudf/cpp/src/io/parquet/writer_impl.cu(575): error #177-D: variable "data_col_type" was declared but never referenced
/cudf/cpp/src/io/parquet/writer_impl.cu(906): error #177-D: parameter "stream" was declared but never referenced
/cudf/cpp/src/io/parquet/writer_impl.cu(908): error #177-D: variable "col" was declared but never referenced
/cudf/cpp/src/io/parquet/writer_impl.cu(1290): error #177-D: parameter "max_page_uncomp_data_size" was declared but never referenced …
```
=> Fix unused variables/parameters in parquet/writer_impl.cu

java/src/main/java/ai/rapids/cudf/ColumnVector.java, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This adds an event handler for `ColumnVector` to be invoked when `.close()` is invoked.
I also made `getRefCount` public since it is useful for debugging and I couldn't think of a good reason to keep this hidden.
This event handler is used to keep track of what columns are spillable at a time and is part of https://github.com/NVIDIA/spark-rapids/issues/7672.
=> Add an event handler for ColumnVector.close

python/cudf/cudf/core/column/string.py, python/cudf/cudf/tests/test_string.py
Closes https://github.com/rapidsai/cudf/issues/13253
=> Support the case=False argument to str.contains

cpp/cmake/thirdparty/patches/nvbench_override.json, cpp/include/cudf_test/iterator_utilities.hpp, cpp/include/cudf_test/type_lists.hpp, cpp/src/io/json/json_column.cu, cpp/src/io/json/nested_json_gpu.cu, cpp/tests/io/json_test.cpp, cpp/tests/scalar/scalar_test.cpp
Corrects compilation issues found by gcc 12 and the new warnings it provides.
Three major classes of issues was found:
- incorrect lambda captures of the wrong container for the iterators being used
- incorrect implicit conversions
- warnings generated by using std::transform and std::initializer_lists
=> Support gcc 12 as the C++ compiler

.pre-commit-config.yaml, python/cudf/cudf/_lib/column.pyi, python/cudf/cudf/core/buffer/buffer.py, python/cudf/cudf/core/buffer/spill_manager.py, python/cudf/cudf/core/buffer/spillable_buffer.py, python/cudf/cudf/core/buffer/utils.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/decimal.py, python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/column/lists.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/column/numerical_base.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/core/column/struct.py, python/cudf/cudf/core/column/timedelta.py, python/cudf/cudf/core/column_accessor.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/core/single_column_frame.py
Bring us up to date with the current mypy release. Big diff, mostly due to the no-implicit-optional rule that mypy now enforces (see commit message of 040f5773c37d89cdbc0baf57fa70a4b3dcab4fc9 for details). That commit is automated so probably best to review commit-by-commit for the substantive changes.
- Closes #13336
=> Update mypy to 1.3

cpp/benchmarks/copying/contiguous_split.cu, cpp/include/cudf/detail/contiguous_split.hpp, cpp/src/copying/contiguous_split.cu, cpp/src/copying/pack.cpp
This fixes a performance issue in `contiguous_split` that is due to `pack_metadata` not being implemented by an efficient way. In particular, the output bytes are copied from the internal buffer to the output buffer byte-by-byte, through `std::back_inserter`:
```
std::copy(metadata_begin,
metadata_begin + (metadata.size() * sizeof(detail::serialized_column)),
std::back_inserter(metadata_bytes));
```
This was probably optimized somehow by the compiler, but recent refactors made some changes to the code and probably prevent such optimization.
Latest cudf commit:
```
----------------------------------------------------------------------------------------------------------------------------------------------------
ContiguousSplit/6Gb512ColsNoValidity/6442450944/512/256/0/iterations:8/manual_ti …
```
=> Fix  `contiguous_split` performance

python/cudf/cudf/_lib/column.pyi, python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/buffer/buffer.py, python/cudf/cudf/core/buffer/cow_buffer.py, python/cudf/cudf/core/buffer/spillable_buffer.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/core/column/struct.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/core/tools/datetimes.py
With #13336, we can use the PEP674 `Self` type.
=> Expunge most uses of `TypeVar(bound="Foo")`

cpp/src/binaryop/binaryop.cpp, cpp/src/copying/copy_range.cu, cpp/src/filling/fill.cu, cpp/tests/copying/purge_nonempty_nulls_tests.cpp
Fixes a few more places where the null count was not being set in a libcudf function before returning a column. A couple of places were setting the null count value into the mutable-view object. So the value was calculated correctly but not set into the actual column object.
Reference: https://github.com/rapidsai/cudf/issues/11968
=> Fix some libcudf functions to set the null count on returning columns

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnViewNonEmptyNullsTest.java
When setting the validity buffer in `mergeAndSetValidity` method, we check to see two things 
1. Purge any non-empty nulls that may have arise due to setting values to null which were previously non-null
2. If we override the existing null values in the validity buffer then throw an IllegalStateException.
=> [Java] Purge non-empty nulls when setting validity 

cpp/src/io/parquet/page_data.cu
Fixed unused parameters warning/error in the `parquet/page_data.cu`:
```
/cudf/cpp/src/io/parquet/page_data.cu(171): error #177-D: parameter "is_decode_step" was declared but never referenced
detected during:
instantiation of "__nv_bool cudf::io::parquet::gpu::<unnamed>::setupLocalPageInfo(cudf::io::parquet::gpu::<unnamed>::page_state_s *, const cudf::io::parquet::gpu::PageInfo *, cudf::device_span<const cudf::io::parquet::gpu::ColumnChunkDesc, 18446744073709551615UL>, size_t, size_t, __nv_bool, cudf::io::parquet::gpu::rle_stream<level_t> *) [with level_t=uint8_t]" 
(1825): here
instantiation of "void cudf::io::parquet::gpu::<unnamed>::gpuComputePageSizes<lvl_buf_size,level_t>(cudf::io::parquet::gpu::PageInfo *, cudf::device_span<const cudf::io::parquet::gpu::ColumnChunkDesc, …
```
=> Fix unused parameter warning/error in parquet/page_data.cu

java/src/main/native/src/CudfJni.cpp
This is a simple fix for a JNI method that doesn't have the right parameter list. It didn't trigger any bug because the mismatched (redundant) parameter is not used, and Java calls this method through function name lookup without knowing its signature.
=> Fix JNI method with mismatched parameter list

java/src/main/java/ai/rapids/cudf/Table.java, java/src/main/java/ai/rapids/cudf/TableWriter.java, java/src/main/native/src/CudfJni.cpp, java/src/main/native/src/TableJni.cpp, java/src/test/java/ai/rapids/cudf/TableTest.java
This adds JNI to expose compression statistics for ORC and Parquet writer, which was implemented in https://github.com/rapidsai/cudf/pull/13294.
For doing so, `TableWriter` has been changed from an interface into an abstract class. Related derived writer classes are also updated accordingly.
Closes https://github.com/rapidsai/cudf/issues/13252.
=> Add JNI for ORC/Parquet writer compression statistics

python/cudf/cudf/tests/test_dataframe_copy.py
This modernizes a few copy tests that came up during conversation at https://github.com/rapidsai/cudf/pull/13337/files#r1197942788
=> Remove numba JIT kernel usage from dataframe copy tests

cpp/src/copying/contiguous_split.cu
This PR introduced some unused arguments that are causing compilation errors in nvcc 11.5 https://github.com/rapidsai/cudf/issues/13180. Taking care of that here.
@davidwendt found these in his local nvcc 11.5 build
=> Fix unused argument errors in nvcc 11.5

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py, python/dask_cudf/dask_cudf/tests/test_groupby.py
Scan-based groupbys are massaged back into pandas (original dataframe)
order by a post-processing step. Previously, this did the wrong thing
if the grouping key contained null (or nan) keys. In this situation
dropna=True will cause libcudf to produce an output table that is
smaller than the input frame. To mimic pandas we need to expand this
output to the original frame size, inserting nulls in the missing rows
and reordering correctly.
Furthermore, the previous reordering code had an out-of-bounds memory
access when there were null keys, since we were asking to group a
column of the same length as the result, but the grouping object expects
columns of length of the original input (which is larger with
dropna=True and null keys).
To fix these issues, compute the reordering on a column of …
=> Correctly reorder and reindex scan groupbys with null keys

java/src/main/java/ai/rapids/cudf/ColumnVector.java, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Putting this up as an optimization for ColumnVector.EventHandler. 
As it stands today, code in the spark-rapids plugin that wants to use this is having to java objects that encapsulate state about the columns around reference counting and what represents the bag of `ColumnVector`s that are spillable at any given time. If we pass the `ColumnVector` instance in the event handler, one of these objects can be removed, and we can simplify the implementation in the plugin. I am putting this up as draft while my local tests pass, but I think it should be fairly straightforward.
=> [JNI] Pass this ColumnVector to the onClosed event handler

cpp/benchmarks/CMakeLists.txt, cpp/benchmarks/stream_compaction/stable_distinct.cpp, cpp/include/cudf/detail/stream_compaction.hpp, cpp/include/cudf/stream_compaction.hpp, cpp/src/stream_compaction/stable_distinct.cu, cpp/tests/CMakeLists.txt, cpp/tests/stream_compaction/distinct_tests.cpp, cpp/tests/stream_compaction/stable_distinct_tests.cpp
This PR supersedes part of #11656.
It adds a public API for `cudf::stable_distinct`, mirroring that of `cudf::distinct` but preserving the order of the input table. The `stable_distinct` implementation was refactored to use `apply_boolean_mask`, which reduces the number of kernels needed. I also added tests/benchmarks for `cudf::stable_distinct`.
I split out the C++ changes from #11656 because that PR size was getting too large. Also these C++ changes are non-breaking, but the Python changes are breaking (and depend on these C++ changes), so separating into a new PR seemed like a good idea.
=> Add cudf::stable_distinct public API, tests, and benchmarks.

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
=> Fix groupby head/tail for empty dataframe

conda/recipes/cudf/meta.yaml
This PR drops two dependencies from the cudf conda recipe.
- `numba` is only a `run` dependency and should not be listed in `host`.
- `fastavro` is only a test dependency. It is listed in `dependencies.yaml` but does not need to be listed in `meta.yaml` as a run dependency. This is already listed as a testing dependency in `pyproject.toml`.
=> Drop extraneous dependencies from cudf conda recipe.

conda/recipes/cudf/meta.yaml, cpp/benchmarks/CMakeLists.txt, cpp/benchmarks/stream_compaction/stable_distinct.cpp, cpp/include/cudf/detail/stream_compaction.hpp, cpp/include/cudf/stream_compaction.hpp, cpp/src/io/utilities/data_sink.cpp, cpp/src/io/utilities/datasource.cpp, cpp/src/stream_compaction/stable_distinct.cu, cpp/tests/CMakeLists.txt, cpp/tests/stream_compaction/distinct_tests.cpp, cpp/tests/stream_compaction/stable_distinct_tests.cpp, java/src/main/java/ai/rapids/cudf/ColumnVector.java, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java, python/cudf/cudf/_lib/cpp/stream_compaction.pxd, python/cudf/cudf/_lib/stream_compaction.pyx, python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/reshape.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/indexes/test_interval.py, python/cudf/cudf/tests/test_array_function.py, python/cudf/cudf/tests/test_groupby.py, python/cudf/cudf/tests/test_onehot.py, python/cudf/cudf/tests/test_string.py, python/dask_cudf/dask_cudf/tests/test_groupby.py
Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> Forward-merge branch-23.06 to branch-23.08

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_csv.py
Pandas-2.0 moved to a very strict & consistent date format inference, we should plan to move similarly but meanwhile for the pytest to pass, we will need to pass `date_format='mixed'`.
This PR also fixes a miscellaneous issue with `MultiIndex.copy` docstring.
=> [REVIEW] Fix csv reader pytest to pass `date_format='mixed'`

python/cudf/cudf/core/column/string.py, python/cudf/cudf/tests/test_text.py
Closes https://github.com/rapidsai/cudf/issues/13399
=> Fix tokenize with non-space delimiter

python/cudf/cudf/core/groupby/groupby.py
In pandas-2.0 `groupby.nth` behavior has changed: https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#dataframegroupby-nth-and-seriesgroupby-nth-now-behave-as-filtrations
This PR enables preserving the callers index in the end result and returns grouping columns as part of the result.
This PR fixes all 12 pytests in `python/cudf/cudf/tests/test_groupby.py::test_groupby_nth`
=> Preserve Index and grouped columns in `Groupby.nth`

cpp/src/io/orc/stripe_enc.cu, cpp/tests/io/orc_test.cpp
Issue #13460
Fixes the bug in `gpuCompactOrcDataStreams` where stream pointer would not get updated for empty row groups.
=> Fix writing of ORC files with empty rowgroups

cpp/benchmarks/io/parquet/parquet_reader_input.cpp
Currently, chunked Parquet reader benchmark creates the chunked reader object once and reuses it for all iterations.
After the first iteration the source is fully read so each subsequent iteration returns a single, empty, chunk. 
This PR fixes the use of the chunked reader object.
The creation of the object is included in the benchmark timing.
=> Fix chunked Parquet reader benchmark

cpp/include/cudf/detail/utilities/cuda.cuh
Since shared memory declarations have a lifetime tied to the
block they are executed on (and not the function scope), we must
sync the block before returning the result to ensure that there
are no RAW/WAR-conflicts between successive invocations of
single_lane_block_sum_reduce within a kernel. Previously, it was
possible for the i+1th call to conflict with the ith call in a
loop.
- Closes #13485.
=> Ensure `single_lane_block_sum_reduce` is safe to call in a loop

cpp/include/cudf/detail/null_mask.cuh
Fixes the valid count calculation in the `offset_bitmask_binop` kernel when the mask may contain slack bits. The slack bits must be accounted for in the final bitmask word to correctly compute the valid count.
Closes #13479
=> Fix valid count computation in offset_bitmask_binop kernel

python/cudf/cudf/core/join/join.py, python/cudf/cudf/tests/test_joining.py
This PR raises an error when a merge is being performed between data consisting of different levels.
=> Enforce merge validation deprecation for unequal levels

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_index.py
This PR enables `sort=True` for `union`, `difference`, and `intersection` APIs in `Index`. 
This also fixes 1 pytest failure and adds 77 pytests:
On `Index_sort_2.0`:
```
= 230 failed, 95836 passed, 2045 skipped, 768 xfailed, 308 xpassed in 438.88s (0:07:18) =
```
```
= 231 failed, 95767 passed, 2045 skipped, 764 xfailed, 300 xpassed in 432.59s (0:07:12) =
```
xref: https://github.com/pandas-dev/pandas/issues/25151
=> Enable `sort=True` for `Index.union`, `Index.difference` and `Index.intersection`

python/cudf/cudf/core/window/rolling.py, python/cudf/cudf/tests/test_rolling.py
This PR drops a special handling for `Rolling.count` where we always default to `min_periods=0`, this is an inconsistency that pandas-2.0 resolves in: https://github.com/pandas-dev/pandas/pull/48839
This PR fixes 2 pytest failures:
```
= 229 failed, 95769 passed, 2045 skipped, 764 xfailed, 300 xpassed in 458.04s (0:07:38) =
```
```
= 231 failed, 95767 passed, 2045 skipped, 764 xfailed, 300 xpassed in 457.58s (0:07:37) =
```
=> Drop special handling of `min_periods` for `Rolling.count`

python/cudf/cudf/tests/test_json.py
This PR fixes 3 json reader pytests:
This PR:
```
= 228 failed, 95770 passed, 2045 skipped, 764 xfailed, 300 xpassed in 473.29s (0:07:53) =
```
```
= 231 failed, 95767 passed, 2045 skipped, 764 xfailed, 300 xpassed in 445.90s (0:07:25) =
```
=> Fix JSON reader pytests

cpp/include/cudf_test/column_wrapper.hpp, cpp/tests/utilities/column_utilities.cu
For the purpose of verifying that streams are properly forwarded through all libcudf APIs, libcudf tests will be rewritten to use `cudf::test::get_default_stream()` (introduced in #12089) instead of `cudf::get_default_stream()`. By default, these are identical, so this change is typically a no-op, but when using the preload library features added in #12089 we will be able to use a custom (non CUDA-default) stream in tests and verify that it is the only stream used. This PR contains a subset of changes needed to existing test functionality without making any changes to libcudf public APIs. These changes are extracted from #12090.
Contributes to #11943.
=> Use test default stream

build.sh
`python setup.py` has been deprecated for years and will eventually be removed. It has numerous issues, most significant of which is that it is incompatible with many modern build systems that support only PEP 517-based builds.
This is a breaking change for build.sh users who do not install. Modern builders no longer support running entirely in place. They do support editable installs, however, so `pip install -e` remains an option for which support could be added later.
=> Change build.sh to use pip install instead of setup.py

python/cudf/cudf/tests/test_dataframe.py
This PR xfails a condition that is failing due to a pandas bug: https://github.com/pandas-dev/pandas/issues/53497
=> Fix `DataFrame.mode` pytest

cpp/tests/CMakeLists.txt
The preload lib is already being specified in the CI testing environment via bash, so this change has no short-term effect. The long-term solution is being worked on in #13513.
=> Remove preload lib from CMake for now

ci/build_docs.sh
The `s3` destination prefix for `dask-cudf` incorrectly included "dask_cudf" instead of "dask-cudf". The PR fixes this.
=> s3 folder naming fix

conda/environments/all_cuda-118_arch-x86_64.yaml, dependencies.yaml
This PR adds a libcufile dependency specification, only for x86_64 (the package is not available on ARM). This aligns with the conda recipe specification, previously updated in #13231.
=> Add libcufile to dependencies.yaml.

cpp/src/io/json/json_column.cu, cpp/src/io/json/nested_json.hpp
Issue: JSON reader null mask size was alloted bigger than expected size (4x bigger).
This change creates null mask with right size.
=> Fix the null mask size in json reader

cpp/tests/utilities/identify_stream_usage.cpp
This PR changes the error message from stream testing to identify that it's being raised by a cudf test utility. I didn't recognize the error text at first, and assumed it was an error from CUDA or nvbench.
=> Clarify source of error message in stream testing.

python/cudf/cudf/io/parquet.py, python/cudf/cudf/tests/test_parquet.py, python/cudf/cudf/utils/ioutils.py
This PR deprecates `string_to_categorical` because of the ambiguous naming to the end users and no real use for this parameter at this point. Pandas or pyarrow don't have this parameter, it was exclusive to `cudf`.
=> Deprecate `strings_to_categorical` in `cudf.read_parquet`

cpp/include/cudf/strings/detail/strip.cuh, cpp/src/strings/strip.cu, cpp/tests/strings/strip_tests.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Fixes `cudf::strings::strip` logic when all the input strings are empty or all null. The logic was incorrectly incorrectly empty strings as null rows when producing the output column.
Also added a gtest for this special case.
Closes #13529
=> Fix cudf::strings::strip for all-empty input column

cpp/src/dictionary/detail/concatenate.cu
Fixes memcheck error found by the cudf nightly memcheck in `cudf::dictionary::detail::concatenate`
```
========= COMPUTE-SANITIZER
Note: Google Test filter = DictionaryConcatTest.StringsKeys
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from DictionaryConcatTest
[ RUN      ] DictionaryConcatTest.StringsKeys
========= Invalid __global__ write of size 4 bytes
=========     at 0x420 in void thrust::cuda_cub::core::_kernel_agent<thrust::cuda_cub::__parallel_for::ParallelForAgent<thrust::cuda_cub::for_each_f<thrust::zip_iterator<thrust::tuple<thrust::transform_iterator<cudf::dictionary::detail::concatenate(cudf::host_span<const cudf::column_view, (unsigned long)18446744073709551615>, rmm::cuda_stream_view, …
```
=> Fix out-of-bounds memory write in cudf::dictionary::detail::concatenate

CONTRIBUTING.md, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/cudf/conda_build_config.yaml, conda/recipes/cudf_kafka/conda_build_config.yaml, conda/recipes/cudf_kafka/meta.yaml, conda/recipes/libcudf/conda_build_config.yaml, cpp/CMakeLists.txt, cpp/examples/basic/CMakeLists.txt, cpp/examples/strings/CMakeLists.txt, cpp/libcudf_kafka/CMakeLists.txt, dependencies.yaml, java/src/main/native/CMakeLists.txt, python/cudf/CMakeLists.txt, python/cudf/pyproject.toml, python/cudf/udf_cpp/CMakeLists.txt
Updates minimum required CMake version to 3.26.4. This will allow us to take advantage of a variety of new features in the last three minor releases, particularly with respect to better CUDA and Python support. See https://github.com/rapidsai/rapids-cmake/issues/315 for more information.
=> Update to CMake 3.26.4

cpp/src/join/join_common_utils.hpp, cpp/src/text/subword/load_merges_file.cu
This PR gets rid of the use of the deprecated `cuco::pair_type` alias. `cuco::pair` is all what we need.
=> Get rid of `cuco::pair_type` aliases

python/cudf/cudf/testing/testing.py, python/dask_cudf/dask_cudf/backends.py, python/dask_cudf/dask_cudf/core.py, python/dask_cudf/dask_cudf/io/tests/test_parquet.py, python/dask_cudf/dask_cudf/tests/test_accessor.py, python/dask_cudf/dask_cudf/tests/test_core.py, python/dask_cudf/dask_cudf/tests/test_reductions.py
This PR fixes all `dask_cudf` side failures that happen due to `pandas-2.0` upgrade. The fixes are trivial to be broken down into separate PRs. 
This PR fixes 56 pytest failures:
```
== 1100 passed, 13 skipped, 8 xfailed, 5 xpassed, 114 warnings in 57.10s ==
```
```
== 56 failed, 1044 passed, 13 skipped, 8 xfailed, 5 xpassed, 114 warnings in 73.73s (0:01:13) ==
```
=> Fix `dask_cudf` pytest failures for `pandas-2.0` upgrade

python/dask_cudf/dask_cudf/backends.py, python/dask_cudf/dask_cudf/tests/test_dispatch.py
Registers the necessary cudf-specific logic for the dispatch functions introduced in https://github.com/dask/dask/pull/10312. These dispatch functions are necessary to enable "p2p" shuffling with a cudf backend (see: https://github.com/dask/distributed/pull/7743)
=> Add dispatch for `cudf.Dataframe` to/from `pyarrow.Table` conversion

cpp/include/cudf/hashing.hpp, cpp/src/hash/hashing.cu, cpp/tests/CMakeLists.txt, cpp/tests/hashing/hash_test.cpp, cpp/tests/streams/hash_test.cpp
This PR adds a stream parameter to `cudf::hash`, allowing callers to request execution on a stream other than cudf's default stream.
=> Add stream parameter to hashing APIs 

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/java/ai/rapids/cudf/Table.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/main/native/src/TableJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java, java/src/test/java/ai/rapids/cudf/TableTest.java
This adds in java bindings for cudf::distinct_count for both table and column APIs.
=> Add java bindings for distinct count

cpp/src/reductions/all.cu, cpp/src/reductions/any.cu, cpp/tests/reductions/reduction_tests.cpp
The nightly tests found memcheck errors in `REDUCTION_TEST` for **any/all** aggregation types on **dictionary** columns.
The error is caused by the internal `atomicOr()` function which reads the target value as 32-bit even if the type is bool (8-bit).
The fix works around this limitation by using `atomicOr()` on a 32-bit device scalar and then converting that to a bool scalar on return.
All other tests in `REDUCTION_TEST` now pass memcheck successfully.
Closes #13572
=> Fix memcheck errors found in REDUCTION_TEST

cpp/include/cudf/scalar/scalar.hpp, cpp/src/scalar/scalar.cpp
Adds an exception to the `cudf::string_scalar` constructor if the input `std::string` size exceeds the maximum `cudf::size_type`.
=> Add exception to string_scalar if input string exceeds size_type

docs/cudf/source/api_docs/general_functions.rst
This PR adds documentation for `cudf.from_dataframe`, `cudf.date_range`, and `cudf.interval_range`. These are exposed in the top-level API of the `cudf` module but lacked docstrings.
=> Update docs for top-level API.

cpp/src/stream_compaction/distinct_count.cu, cpp/tests/stream_compaction/distinct_count_tests.cpp
If nulls should compare equal then we want to filter out rows for which all column entries are invalid (bitmask not set). If any column is not nullable, then bitmask_or returns an empty bitmask buffer (and a null count of zero) indicating that the returned bitmask is fully valid. When passed as a predicate to insert_if we get a null pointer dereference.
To avoid this, only run predicated insertion if the null count returned from bitmask_or is positive (which guarantees that the validity bitmask exists). This also avoids running predicated insertion when the predicate is always true.
Closes #13576.
=> Handle nullptr return value from bitmask_or in distinct_count

cpp/src/interop/from_arrow.cu
The nightly tests found a memcheck error in `INTEROP_TEST` for `cudf::from_arrow` when the arrow bitmask is not padded to `bitmask_type` size. This causes a global memory read error when calling the `cudf::detail::mask_to_bools` function which expects the mask to be properly padded.
This fixes the device allocation size used when copying the arrow bool data to a temporary `rmm::device_buffer` which is used when calling `cudf::detail::mask_to_bools`.
All other tests in `INTEROP_TEST` now pass memcheck successfully.
Closes #13568
=> Fix memcheck error found in INTEROP_TEST

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_joining.py
This PR removes materialization of certain `RangeIndex.join` combinations by falling back to pandas because it's not expensive to do so and also fixes an issue around mismatching index names while performing a join.
=> Bring parity with pandas in Index.join

cpp/src/strings/search/find.cu
Fixes a memcheck error found in `STRINGS_TEST` where an `atomicOr` was used on a boolean device scalar. The workaround uses a `cub::WarpReduce` to compute the result in the warp-per-string kernel.
Reference #13574
=> Fix memcheck error found in STRINGS_TEST 

python/dask_cudf/dask_cudf/io/parquet.py
Preemptive fix for incoming dask PR: https://github.com/dask/dask/pull/10353
Adds handling for the case that the array of known hive-partitioning keys is empty. This will happen when we **don't** want to convert a hive-partitioned column into a categorical column.
=> Preemptive fix for hive-partitioning change in dask

python/cudf/cudf/core/_internals/timezones.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/indexes/datetime/test_time_specific.py, python/cudf/cudf/tests/series/test_datetimelike.py
Closes https://github.com/rapidsai/cudf/issues/13601
=> Fix `localize(None)` for timezone-naive columns

cpp/include/cudf/contiguous_split.hpp, cpp/include/cudf/detail/nvtx/nvtx3.hpp, cpp/include/cudf/io/parquet.hpp, cpp/include/cudf/rolling/range_window_bounds.hpp, cpp/include/cudf/types.hpp, cpp/include/cudf_test/column_wrapper.hpp, cpp/include/cudf_test/cudf_gtest.hpp, cpp/src/copying/contiguous_split.cu, cpp/src/datetime/timezone.cpp, cpp/src/text/subword/wordpiece_tokenizer.cu
Removes the repeated words in doxygen text in libcudf.
Similar to #13561, fixed repeated words.
https://github.com/rapidsai/cudf/pull/13561#issuecomment-1592147377
=> Fix repeated words in doxygen text

cpp/benchmarks/string/like.cpp, cpp/src/strings/like.cu
Minimizes character counting in the kernel logic for `cudf::strings::like` to improve overall performance especially for longer strings.
The nvbench benchmark is updated to include measurements for various strings sizes.
Reference #13048
=> Performance improvement for cudf::strings::like 

cpp/src/rolling/grouped_rolling.cu, cpp/tests/rolling/grouped_rolling_range_test.cpp
This commit fixes the window range calculations for floating-point order by columns.
Window range calculations involve comparing the `delta` value (preceding/following) with the current row value, and capping `current_row - delta` at `numeric_limits::min()`.
It turns out that for `float`/`double` values, `numeric_limits::min()` returns `FLT_MIN` which is the lowest positive finite float value. This causes the erstwhile logic to produce incorrect results when the order-by column contains negative float values.
The fix involves replacing `numeric_limits::min()` with `numeric_limits::lowest()` which returns the true min float value.
Reference:
1. https://en.cppreference.com/w/cpp/types/numeric_limits/min
=> Fix floating point window range extents.

README.md, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/cudf/meta.yaml, conda/recipes/cudf_kafka/meta.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
This PR changes CUDA 11 packaging to rely on `cuda-version` pinnings to constrain the installed version of `cudatoolkit`.
Resolves #13613. Resolves #13607.
=> Use cuda-version to constrain cudatoolkit.

cpp/src/strings/split/split_re.cu
Fixes compile warning found in `cpp/src/strings/split/split_re.cu` for unused declared variable
```
/cudf/cpp/src/strings/split/split_re.cu(83): error #177-D: structured binding "end_pos" was declared but never referenced
```
=> Fix compile warning for unused variable in split_re.cu

dependencies.yaml
cupy is now available via PyPI with ARM builds. This means we can delete some outdated logic in `dependencies.yaml`.
=> Clean up cupy in dependencies.yaml.

cpp/src/io/orc/reader_impl.cu
Fixes memcheck regression in ORC reader uncompressed logic. The regression was introduced in #13396.
The original fix is copied from #13586 
The error was caught by the nightly build here: https://github.com/rapidsai/cudf/actions/runs/5409203449/jobs/9829059618
=> Fix memcheck error in ORC reader call to cudf::io::copy_uncompressed_kernel

cpp/src/copying/purge_nonempty_nulls.cu, cpp/tests/copying/purge_nonempty_nulls_tests.cpp
This fixes `has_nonempty_nulls` that always access the column offsets without considering the starting offset. As such, it may give wrong answer if the input column is sliced.
Closes https://github.com/rapidsai/cudf/issues/13638.
=> Fix `has_nonempty_nulls` ignoring column offset

conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml
The CUDA 12 developer conda environment contains `cubinlinker` and `ptxcompiler`. These are unneeded and make the environment unsolvable, because they depend on `cudatoolkit`.
=> Fix CUDA 12 conda environment to remove cubinlinker and ptxcompiler.

java/src/main/java/ai/rapids/cudf/ColumnView.java
This PR addresses a case where an AssertionError will cause a double-free corruption. This was missed as part of https://github.com/rapidsai/cudf/pull/13597
=> [Java] Avoid double-free corruption in case of an Exception while creating a ColumnView

cpp/src/text/utilities/tokenize_ops.cuh
Fixes memcheck error found by the nightly build in the nvtext `characters_tokenizer` utility function.
```
[ RUN      ] TextNgramsTokenizeTest.Tokenize
========= Invalid __global__ read of size 1 bytes
=========     at 0x2360 in void cub::CUB_101702_610_860_NS::DeviceScanKernel<cub::CUB_101702_610_860_NS::DeviceScanPolicy<int>::Policy600, thrust::cuda_cub::transform_input_iterator_t<int, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, nvtext::detail::strings_tokenizer>, int *, cub::CUB_101702_610_860_NS::ScanTileState<int, (bool)1>, thrust::plus<int>, cub::CUB_101702_610_860_NS::NullType, int>(T2, T3, T4, int, T5, T6, T7)
=========     by thread (5,0,0) in block (0,0,0)
=========     Address 0x7f67a0200a65 is out of bounds
=========     and …
```
=> Fix memcheck error found in nvtext tokenize functions

python/cudf/cudf/_lib/cpp/sorting.pxd, python/cudf/cudf/_lib/sort.pyx, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/groupby/groupby.py
As preparation for addressing parts of #13557, this just exposes the existing sort-by and stable-sort-by routines from libcudf.
=> Expose stable versions of libcudf sort routines

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_multiindex.py
#13657 attempted to provide pandas-compatible ordering to the return value from multiindex-based `loc`-indexing. However, one must sort by keys corresponding to both the left and right gather maps of the join, rather than just the right gather map, to ensure that  correct ordering is maintained.
=> Fix multiindex loc ordering in pandas-compat mode

conda/recipes/cudf/meta.yaml
Ensure `cuda-nvcc-impl` is pulled in by `cudf` CUDA 12 packages alongside `numba` for CUDA support.
=> Add `cuda-nvcc-impl` to `cudf` for `numba` CUDA 12

python/cudf/cudf/core/dataframe.py
This PR:
- Adds a pandas compatibility note to the DataFrame.query docstring that indicates query only supports a subset of the canonical dtypes (e.g., not strings). A user ran into this and mentioned it would be nice to document it.
=> Add pandas compatibility note to DataFrame.query docstring

cpp/benchmarks/common/generate_input.cu
Currently the data generator only takes the element (leaf) size into account when estimating the size of a row in a list column.
This estimate can be lower by an order of magnitude for tall lists (many levels with few elements per row).
This PR expands the row size estimate to also include the offsets size.
A small impact on existing benchmarks with list types is expected because of reduced row count for a given data size.
=> Data generator - include offsets in the size estimate of list elments

cpp/include/cudf/table/experimental/row_operators.cuh, cpp/tests/sort/sort_nested_types_tests.cpp
This fixes a bug showing up in spark-rapids (https://github.com/NVIDIA/spark-rapids/issues/8702) when the lexicographic comparator encounters a corner case with an input table having:
* At least two structs-of-lists columns followed by at least one more column, and
* All elements of the first structs-of-lists column are all null.
This bug is due to a short circuit in the lexicographic comparator that forgets to keep track of the number of processed lists columns during early exit.
=> Fix a corner case of list lexicographic comparator

docs/cudf/source/developer_guide/contributing_guide.md, python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/algorithms.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/decimal.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/join/join.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/core/reshape.py, python/cudf/cudf/core/series.py, python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/io/orc.py, python/cudf/cudf/tests/test_binops.py, python/cudf/cudf/tests/test_reductions.py, python/cudf/cudf/tests/test_series.py, python/cudf/cudf/utils/ioutils.py
Fixes: https://github.com/rapidsai/cudf/issues/13619
This PR enforces deprecation warnings and adds comments around the existing deprecation warnings that shouldn't be dropped right now.
=> Enforce deprecations and add clarifications around existing deprecations

cpp/include/cudf/io/data_sink.hpp, cpp/include/cudf/io/datasource.hpp, cpp/include/doxygen_groups.h
Adds the `cudf::io::datasource` source (header) to the doxygen IO Data Sources group/modules:
https://docs.rapids.ai/api/libcudf/stable/group__io__datasources.html
Found while working #13698 
Also created a Data Sinks group and added the `cudf::io::data_sink` source to it.
=> Fix doxygen groups for io data sources and sinks

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml
I ran into an issue with `clang-format` not being able to run due to the version of identify I had installed.
```
$ pre-commit 
An error has occurred: InvalidManifestError: 
==> At Hook(id='clang-format')
==> At key: types_or
==> At index 9
=====> Type tag 'textproto' is not recognized.  Try upgrading identify and pre-commit?
```
This led me to find out that `pre-commit` only requires version 1, but we require a newer version to work with `clang-format`. We don't specify that version anywhere, so I tracked down the minimum requirement and added it in our `dependencies.yaml` and ran `pre-commit` to update the conda environment files.
I verified that version [2.5.19](https://github.com/pre-commit/identify/blob/v2.5.19/identify/extensions.py#L226) did not have textproto, but …
=> Adding identify minimum version requirement

cpp/src/io/orc/dict_enc.cu, cpp/tests/io/orc_test.cpp
ORC writer incorrectly counts characters in sliced string columns, ignoring the slice offset. This potentially leads to under-allocated stripes and errors.
This PR fixes the char counting kernel to take the string column offset into account.
=> Fix character counting when writing sliced tables into ORC

python/cudf/cudf/_lib/cpp/io/parquet.pxd, python/cudf/cudf/_lib/parquet.pyx, python/cudf/cudf/io/parquet.py, python/cudf/cudf/tests/test_parquet.py, python/cudf/cudf/utils/ioutils.py, python/dask_cudf/dask_cudf/io/parquet.py, python/dask_cudf/dask_cudf/io/tests/test_parquet.py
This PR enforces previously deprecated code until `23.08` in `23.10`. This PR removes `strings_to_categorical` parameter support in `read_parquet`.
=> Enforce deprecations in `23.10`

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, ci/build_wheel_cudf.sh, ci/build_wheel_dask_cudf.sh, ci/test_wheel_cudf.sh, ci/test_wheel_dask_cudf.sh
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> Forward-merge branch-23.08 to branch-23.10

cpp/src/io/orc/dict_enc.cu, cpp/tests/io/orc_test.cpp
Closes #13742
Fixes an OOB access in `rowgroup_char_counts_kernel` when the input column has no rows. This can happen with string columns with a parent list column.
=> Fix writing of ORC files with empty child string columns

python/cudf/cudf/tests/text/test_text_methods.py
The random string generation was using a minimum length of 1 rather than the ngram size. While both the reference implementation and the libcudf code were robust to that case, they return different extreme values (0 vs 1) for those. Since testing that edge case isn't really in scope for this particular test, I've modified the generator to only generate strings whose length is at least the requested ngram size.
Resolves #13748
=> Don't test strings shorter than the requested ngram size

conda/recipes/custreamz/meta.yaml
In #12922, we missed adding a `cuda{{ cuda_major }}_` to the `custreamz` build tag. This PR fixes that.
=> Add CUDA version to custreamz build string.

python/cudf/cudf/_lib/column.pyx, python/cudf/cudf/_lib/concat.pyx, python/cudf/cudf/_lib/copying.pyx, python/cudf/cudf/_lib/cpp/libcpp/memory.pxd, python/cudf/cudf/_lib/expressions.pyx, python/cudf/cudf/_lib/join.pyx, python/cudf/cudf/_lib/null_mask.pyx, python/cudf/cudf/_lib/parquet.pyx, python/cudf_kafka/cudf_kafka/_lib/kafka.pyx
`make_unique` in Cython's libcpp headers is not annotated with `except +`. As a consequence, if the constructor throws, we do not catch it in Python. To work around this (see cython/cython#5560 for details), provide our own implementation.
Due to the way assignments occur to temporaries, we need to now explicitly wrap all calls to `make_unique` in `move`, but that is arguably preferable to not being able to catch exceptions, and will not be necessary once we move to Cython 3.
- Closes #13743
=> Provide our own Cython declaration for make_unique

conda/recipes/cudf_kafka/meta.yaml, conda/recipes/libcudf/meta.yaml
In #12922, we missed adding a `cuda{{ cuda_major }}_` to the `cudf-kafka` and `libcudf-example` build strings. This PR fixes that.
=> Add CUDA version to cudf_kafka and libcudf-example build strings.

python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_series.py
Checking for boolean values in a range results in incorrect behavior:
```python
In [1]: True in range(0, 0)
Out[1]: False
In [3]: True in range(0, 2)
Out[3]: True
```
This results in the following bug:
```python
In [23]: s = cudf.Series([True, False])
In [24]: s[0]
Out[24]: True
In [25]: type(s[0])
Out[25]: numpy.bool_
In [26]: True in s
Out[26]: True
In [26]: True in s.to_pandas()
Out[26]: False
```
This PR fixes this issue by properly checking if an integer is passed to the `RangeIndex. __contains__`
=> Fix contains(`in`) method for `Series`

python/cudf/cudf/core/frame.py, python/cudf/cudf/tests/test_unaops.py
Negative unary op on boolean series is resulting in conversion to `int` type:
```python
In [2]: s = cudf.Series([True, False])
In [3]: s
Out[3]: 
0     True
1    False
dtype: bool
In [4]: -s
Out[4]: 
0   -1
1    0
dtype: int8
In [5]: -s.to_pandas()
Out[5]: 
0    False
1     True
dtype: bool
```
The PR fixes the above issue by returning inversion of the boolean column instead of multiplying with `-1`.
=> Fix negative unary operation for boolean type

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_dataframe.py
This PR fixes various cases in binary operations where columns are of certain dtypes and the binary operations on those dataframes and series don't yield correct results, correct resulting column types, or have missing columns altogether. 
This PR also introduces ensuring column ordering to match pandas binary ops column ordering when pandas compatibility mode is enabled.
=> Fix binary operation column ordering and missing column issues

cpp/cmake/thirdparty/get_arrow.cmake
Arrow 12.0 uses the vendored CMake target `arrow::xsimd` instead of the global target name of `xsimd`. We need to use the new name so that libcudf can be used from the build directory by other projects.
Found by issue: https://github.com/NVIDIA/spark-rapids-jni/issues/1306
=> Update get_arrow to arrows 12 CMake target name of arrow::xsimd

ci/test_wheel_dask_cudf.sh, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/dask-cudf/run_test.sh, dependencies.yaml, python/dask_cudf/pyproject.toml
This PR pins `dask` & `distributed` to `2023.7.1` version for `23.08` release.
=> Pin `dask` and `distributed` for `23.08` release

cpp/src/lists/contains.cu
This PR is to prepare for https://github.com/rapidsai/cudf/pull/13672 which uses experimental comparators for both nested and non-nested types.
`lists::contains` currently has two APIs that support:
1. `cudf::scalar`
2. `cudf::column_view`
Both APIs currently need to call `cudf::type_dispatcher`. However, by converting `cudf::scalar` to a `cudf::column_view` by materializing all rows, we cut down the number of dispatches to half.
Compile times:
Before this PR: [12:07](https://downloads.rapids.ai/ci/cudf/pull-request/13788/0498f7d/cuda11_x86_64.ninja_log.html)
After this PR: [5:46](https://downloads.rapids.ai/ci/cudf/pull-request/13805/7664a98/cuda11_x86_64.ninja_log.html)
=> Reduce `lists::contains` dispatches for scalars

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
In `cudf`, we currently have a hang in this scenario:
```python
In [2]:     class A:
...:         def __getitem__(self, key):
...:             return 1
...: 
In [3]: cudf.DataFrame([A()])
```
This PR introduces additional checks before letting the list-like inputs pass onto `itertools` for transposing.
=> Fix unbounded sequence issue in `DataFrame` constructor

cpp/src/io/parquet/page_enc.cu, cpp/tests/io/parquet_test.cpp
#12685 introduced a bug in page calculation. If the `max_page_size_rows` parameter is set smaller than the page fragment size, the writer will produce a spurious empty page. This PR fixes this by only checking the fragment size if there are already rows in the page, and then returns the old check for number of rows exceeding the page limit.
Interestingly, libcudf can read these files with empty pages just fine, but parquet-mr cannot.
=> Fix for Parquet writer when requested pages per row is smaller than fragment size

cpp/src/lists/contains.cu
=> Update `lists::contains` to experimental row comparator

cpp/tests/copying/concatenate_tests.cpp, cpp/tests/copying/split_tests.cpp, cpp/tests/groupby/tdigest_tests.cu, cpp/tests/interop/from_arrow_test.cpp, cpp/tests/interop/to_arrow_test.cpp, cpp/tests/io/arrow_io_source_test.cpp, cpp/tests/io/csv_test.cpp, cpp/tests/io/json_test.cpp, cpp/tests/io/parquet_test.cpp, cpp/tests/transform/row_bit_count_test.cu, cpp/tests/transpose/transpose_test.cpp
`CUDF_EXPECTS` should be used to report internal errors in libcudf. Google test framework has macros that should be used to report failures. The `ASSERT_` macros replace `CUDF_EXPECTS` as they exit the current function (not by throwing as `CUDF_EXPECTS`, but the effect is very similar).
This PR replaces the erroneous use of CUDF_EXPECTS with ASSERT_XYZ macros in unit tests.
=> Avoid use of CUDF_EXPECTS in libcudf unit tests outside of helper functions with return values

cpp/tests/io/arrow_io_source_test.cpp
Previously I didn't realize that the `ARROW_S3` define was provided to consumers via `arrow/util/config.h`. We can remove the dlopen hack and just guard the entire S3 logic.
=> No need to dlsym EnsureS3Finalized we can call it directly

python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/timedelta.py, python/cudf/cudf/tests/test_datetime.py, python/cudf/cudf/tests/test_scalar.py, python/cudf/cudf/tests/test_timedelta.py, python/cudf/cudf/utils/dtypes.py
Fixes: #13825 This PR raises an error when a time-zone-aware scalar is passed to binops or cudf scalar construction.
=> Raise error when trying to construct time-zone aware timestamps

cpp/src/io/utilities/file_io_utilities.cpp
Factories that instantiate `cufile_input_impl`/`cufile_output_impl` objects did not return the created objects, and instead always returned `nullptr`.
This PR fixes this bug, which made the "GDS" and "OFF" cuFile use policies effectively the same.
The default policy value, "KVIKIO", should be unaffected.
=> Fix cuFile I/O factories

python/cudf/cudf/api/types.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_datetime.py
Fixes: #13834 
This PR raises `NotImplementedError` for more types of data that are timezone-aware passed to `as_column`.
=> Raise error for more cases when `timezone-aware` data is passed to `as_column`

python/cudf/cudf/_lib/scalar.pyx, python/cudf/cudf/tests/test_timedelta.py
Fixes: #13851 
This PR fixes a mistake in `_get_np_scalar_from_timedelta64`, which has to return `cudf.NA` instead of `None`.
=> Fix an issue with fetching `NA` from a `TimedeltaColumn`

cpp/src/io/fst/agent_dfa.cuh
https://github.com/rapidsai/cudf/pull/13344 introduced a performance regression to the FST benchmarks that showed as much as a 35% performance degradation. 
It seems that, after the refactor in the above PR, compiler optimization heuristics are deciding differently on loop unrolling in the part of the FST that's writing out transduced symbols. 
As a fix, we are enforcing to not unroll that loop.
=> Fixes a performance regression in FST 

cpp/src/io/parquet/page_decode.cuh
This PR fixes a typo in the parquet page decoding doc and adds a missing doc.
=> Fix typo in parquet/page_decode.cuh

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_index.py
This PR raises an error when a `cudf` column/series/Index is being constructed using a pandas Index that has a `freq` set. This error is raised only in pandas-compatibility mode, because we will have to switch to `cudf.date_range` everywhere in the code base and examples, and `cudf.date_range` still isn't at a full feature parity with `pd.date_range`.
=> Disable construction of Index when `freq` is set in pandas-compatibility mode

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_multiindex.py
Fixes: #13863 
This PR fixes the return type of `MultiIndex.levels` to return `Index` objects.
=> Fix return type of `MultiIndex.levels`

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_series.py
This PR disables type-casting to `object` dtype for non-string columns. It's a no-op for string columns. We disable this only in pandas-compatibility mode since the usage of `np.dtype("O")` is wide-spread and not quite possible to remove it's support entirely at this point.
=> Raise error when `astype(object)` is called in pandas compatibility mode

python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/timedelta.py, python/cudf/cudf/tests/test_datetime.py, python/cudf/cudf/tests/test_timedelta.py
Resolves: #13876 
This PR brings parity with pandas `datetime` & `timedelta` comparison operations by filling the null locations of results with `True`/`False` according to the binary operation.
**Note: This is only enabled in pandas-compatibility mode.**
=> Bring parity with pandas for `datetime` & `timedelta` comparison operations

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_index.py
Fixes: #13861 
This PR fixes an issue in `MulitIndex.isin` where, previously we calculated partial matches. With this PR we will only return `True` for complete matches.
=> Check for the presence of all values in `MultiIndex.isin`

java/src/test/java/ai/rapids/cudf/CudaTest.java, java/src/test/java/ai/rapids/cudf/RmmTest.java, java/src/test/java/ai/rapids/cudf/TableTest.java, java/src/test/java/ai/rapids/cudf/UnsafeMemoryAccessorTest.java
Contributes to https://github.com/NVIDIA/spark-rapids-jni/issues/1221.
In PR https://github.com/NVIDIA/spark-rapids-jni/pull/1321, we are going to enable the Compute Sanitizer in memcheck mode to help detect some possible kernel errors in the JNI unit tests. But not all the tests are suitable to run with the Compute Sanitizer. This PR is to add these exclusions.
=> Exclude some tests from running with the compute sanitizer

cpp/src/text/generate_ngrams.cu
Fixes performance regression when generating character ngrams. The regression was introduced as part of refactoring common code when adding the `nvtext::hash_character_ngrams` function (Reference #13654). Defactoring the code fixed the regression. Overall, these functions only share about 6 lines of code in common so the defactoring is expected to require minimal maintenance.
The defactoring involves re-instating the original kernel code logic for `nvtext::generate_character_ngrams`.
=> Fix nvtext::generate_character_ngrams performance regression for longer strings 

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_dataframe.py
Continuation to https://github.com/rapidsai/cudf/pull/13768/, In #13768 we prevented construction of mixed types in `Index` & `Series`. This PR implements the same for `DataFrame`.
=> Raise error when trying to construct a `DataFrame` with mixed types

python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/tests/test_datetime.py
In https://github.com/rapidsai/cudf/pull/13857/, we disabled the construction of `DatetimeIndex` & `TimedeltaIndex` when their pandas counter-parts have `freq` set. However, when `freq` is passed to `date_range`, the expectation and pandas-behavior is to return a `DateTimeIndex` with `freq` set. This isn't possible with cudf currently, hence disabled the construction of `DatetimeIndex` in this case.
=> Disable creation of `DatetimeIndex` when `freq` is passed to `cudf.date_range`

python/cudf/cudf/_lib/json.pyx, python/cudf/cudf/tests/test_json.py
Fixes  #13800
The children metadata of list column was not constructed in Cython code. This is fixed by constructing all children columns metadata for list column.
=> Fix List's missing children metadata in JSON writer

python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_index.py
This PR returns `pd.Timestamp` & `pd.Timdelta` respectively for `DatetimeIndex` & `TimedeltaIndex` `__getitem__` in pandas-compatibility mode.
=> Return `Timestamp` & `Timedelta` for fetching scalars in `DatetimeIndex` & `TimedeltaIndex`

cpp/src/io/parquet/page_enc.cu, cpp/src/io/parquet/parquet_gpu.hpp, cpp/src/io/parquet/writer_impl.cu
While working on #13707 it was noticed that RLE encoding of booleans had been implemented and then disabled (see [this comment](https://github.com/rapidsai/cudf/pull/13707#discussion_r1275194215) for details). This PR re-enables RLE encoding for booleans, but only when V2 headers are being used.
Part of #13501.
=> Enable RLE boolean encoding for v2 Parquet files

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml
Fixes the CUDA 12 `cuda-nvtx-dev` package name. This issue was found by @davidwendt and I verified that this fixes it.
=> Use cuda-nvtx-dev CUDA 12 package.

cpp/src/io/csv/reader_impl.cu, python/cudf/cudf/tests/test_csv.py
We currently detect the BOM mark at the start of the file and then decompress the data, if compressed. This leads to a problem with compressed files that have a BOM mark, as we are trying to detect the mark in the compressed data.
This PR moves the BOM detection until after decompression. Also cleaned up the surrounding code slightly.
=> Correctly detect the BOM mark in `read_csv` with compressed input

java/src/test/java/ai/rapids/cudf/ReductionTest.java
Relates to NVIDIA/spark-rapids-jni#1349.  The Java ReductionTest unit tests are failing when run under CUDA 12's compute-sanitizer but pass when run with the CUDA 11 version.  To unblock CI, marking the affected tests to be run without the sanitizer in the interim while this is being investigated.
=> Add noSanitizer tag to Java reduction tests failing with sanitizer in CUDA 12

cpp/src/io/avro/reader_impl.cu, cpp/src/io/csv/reader_impl.cu, cpp/src/io/json/json_column.cu, cpp/src/io/json/legacy/reader_impl.cu, cpp/src/io/json/nested_json_gpu.cu, cpp/src/io/orc/reader_impl.cu, cpp/src/io/orc/writer_impl.cu, cpp/src/io/parquet/compact_protocol_writer.cpp, cpp/src/io/parquet/reader_impl.cpp, cpp/src/io/parquet/writer_impl.cu, cpp/src/io/utilities/column_buffer.cpp, cpp/src/io/utilities/hostdevice_vector.hpp
Adds `empty()` to `hostdevice_vector`.
Check `empty()` instead of checking the column/buffer/vector `size()`.
=> Use `empty()` instead of `size()` where possible

cpp/src/io/avro/avro_gpu.cu, cpp/src/io/csv/csv_gpu.hpp, cpp/src/io/fst/logical_stack.cuh, cpp/src/io/json/json_column.cu, cpp/src/io/json/nested_json_gpu.cu, cpp/src/io/parquet/parquet_gpu.hpp, cpp/src/io/parquet/predicate_pushdown.cpp, cpp/src/io/parquet/reader_impl.cpp, cpp/src/io/parquet/reader_impl_helpers.cpp, cpp/src/io/parquet/reader_impl_helpers.hpp, cpp/src/io/parquet/reader_impl_preprocess.cu
`cudf::get_default_stream()` is used as the default stream when calling `detail` APIs. From this point, the stream passed to this `detail` implementation should be propagated and used consistently. The exceptions are the parts of the implementation that use a separate stream pool.
All in all, libcudf code should not use `cudf::get_default_stream()` outside of dispatching the detail APIs. This PR removes most of such uses in cuIO.
One notable exception is `datasource::host_read`, as it simply does not have a stream parameter (and adding it would be a breaking change).
Also removed comments that mention default stream value that no longer exists.
=> Remove the internal use of the cudf's default stream in cuIO

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py
Fixes: #13900 
This PR fixes an issue with `reindex` API, where `name` of the index being reindexed upon was lost. This PR fixes it to match pandas by using the new index name if it exists or preserving the old name.
=> Preserve index `name` in `reindex`

python/cudf/cudf/_lib/column.pxd, python/cudf/cudf/_lib/column.pyx, python/cudf/cudf/_lib/copying.pyx, python/cudf/cudf/_lib/pylibcudf/column.pxd, python/cudf/cudf/_lib/pylibcudf/column.pyx, python/cudf/cudf/_lib/pylibcudf/gpumemoryview.pxd, python/cudf/cudf/_lib/pylibcudf/table.pxd, python/cudf/cudf/_lib/pylibcudf/table.pyx, python/cudf/cudf/_lib/types.pxd, python/cudf/cudf/_lib/types.pyx, python/cudf/cudf/_lib/utils.pxd, python/cudf/cudf/_lib/utils.pyx
In the short term, cudf internals will be the primary client of pylibcudf, and in the intermediate term cudf internals will likely remain the most exhaustive test of pylibcudf's API. While pylibcudf is designed to be used as either a Python or a Cython library, Python usage is expected to be the much more common entry point. Therefore, it would be best for cudf to use pylibcudf solely as a Python library. This is also useful because it would theoretically allow us to turn cudf into a pure Python library, or at least something much closer to it. In the long run we will likely want to leverage pylibcudf's Cython to accelerate parts of cudf, but that isn't something we should aim for the in the first pass. Switching to pure Python mode is also important because of certain limitations with …
=> Ensure cudf internals use pylibcudf in pure Python mode

python/cudf/cudf/core/frame.py, python/cudf/cudf/tests/test_indexing.py, python/cudf/cudf/tests/test_search.py
Fixes: #13902 
This PR fixes a type-casting issue with `searchsorted` where typecast was done to the `values` dtype instead of inspecting both input and values columns and converting them to common dtypes.
=> Fix handling of typecasting in `searchsorted`

ci/test_wheel_dask_cudf.sh, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/dask-cudf/run_test.sh, dependencies.yaml, python/dask_cudf/pyproject.toml
This PR unpins `dask` and `distributed` to use nightly builds for `23.10` development.
=> Unpin `dask` and `distributed` for `23.10` development

python/cudf/cudf/core/column_accessor.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_indexing.py
Fixes: #13864 
This PR fixes an issue with `loc` indexer where some special handling needs to be done when `columns` is of type `MultiIndex`.
=> Fix an issue with `loc` when column names is `MultiIndex`

cpp/benchmarks/stream_compaction/apply_boolean_mask.cpp
Due to missing parentheses in APPLY_BOOLEAN_MASK benchmark, the number of written bytes were not multiplied by the number of iterations of this benchmark.
=> Fixed processed bytes calculation in APPLY_BOOLEAN_MASK benchmark.

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/resample.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_groupby.py, python/cudf/cudf/tests/test_serialize.py
This PR fixes multiple issues with groupby where the consequent operations on a groupby object always return incorrect results due to an inplace modification that happens in the `Groupby` constructor. To fix this, take a copy of the `by` argument whenever it is an (internal) `_Grouping` object.
- Closes #13923
- Closes #13390
=> Fix construction of `Grouping` objects

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/java/ai/rapids/cudf/DefaultHostMemoryAllocator.java, java/src/main/java/ai/rapids/cudf/HostMemoryAllocator.java, java/src/main/java/ai/rapids/cudf/JCudfSerialization.java, java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java, java/src/main/java/ai/rapids/cudf/Table.java, java/src/main/java/ai/rapids/cudf/nvcomp/BatchedLZ4Compressor.java, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java, java/src/test/java/ai/rapids/cudf/ColumnViewNonEmptyNullsTest.java, java/src/test/java/ai/rapids/cudf/CuFileTest.java, java/src/test/java/ai/rapids/cudf/GatherMapTest.java, java/src/test/java/ai/rapids/cudf/MemoryBufferTest.java, java/src/test/java/ai/rapids/cudf/TableTest.java, java/src/test/java/ai/rapids/cudf/nvcomp/NvcompTest.java
Creates an interface to intercept calls to HostMemoryBuffer.allocate
Fixes NVIDIA/spark-rapids#8884
Signed-off-by: Gera Shegalov <gera@apache.org>
=> Add HostMemoryAllocator interface

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_series.py
closes #13945 
This PR contains changes that raises an error message exactly matching pandas for `nsmallest` and `nlargest`.
=> Raise error for string types in `nsmallest` and `nlargest`

cpp/benchmarks/binaryop/compiled_binaryop.cpp
To add `bytes_per_second`, a call to `.SetBytesProcessed()` with the number of written and read bytes is added to the benchmark.
=> Add `bytes_per_second` to compiled binaryop benchmark

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/tests/test_categorical.py
closes #13947 
This PR fixes the setting of categories in the appropriate order when a dtype with the same categories but of mismatching order is passed.
=> Fix setting of categories order when `dtype` is passed to a `CategoricalColumn`

python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_series.py
Partially addresses #8175
This PR makes changes to `Series.unique`, where a cupy array is returned to match `pd.Series.unique` where a numpy array is returned.
=> Add pandas compatible output to `Series.unique`

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_interval.py
closes #13953 
This PR fixes an issue with `Column.unique` where the type-metadata wasn't being preserved in the end before returning the unique values. This lead to `IntervalColumn` being returned as a `StructColumn`.
=> Fix type metadata issue preservation with `Column.unique`

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
Closes https://github.com/rapidsai/cudf/issues/13897
=> Handle `as_index` in `GroupBy.apply`

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_multiindex.py
closes #13961 
The absence of `MultiIndex.to_numpy` resulted in calling of `Frame.to_numpy` that returns a numpy array without any tuples, this PR adds `MultiIndex.to_numpy` so that a numpy array of tuples is returned.
=> Fix `MultiIndex.to_numpy` to return numpy array with tuples

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_interval.py
closes #13952 
This PR fixes an issue with `IntervalColumn` construction where we can utilize the existing type inference to create a pandas Series and then construct an `IntervalColumn` out of it since pyarrow is unable to read this kind of input correctly.
=> Handle `Interval` scalars when passed in list-like inputs to `cudf.Index`

cpp/src/partitioning/partitioning.cu
This PR uses `cudf::thread_index_type` to avoid overflows.
=> Use `thread_index_type` in `partitioning.cu`

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_factorize.py
closes #13979 
This PR restores column type metadata for `dropna` call, absense of this restoration was causing an issue with the `CategoricalColumn.dropna` that was necessary for `factorize` API.
=> Restore column type metadata with `dropna` to fix `factorize` API

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
closes #13974 
This PR re-calculates the `CategoricalIndex`'s `categories` order to match the order in which the grouping has been done for the `CategoricalColumn`. This fix is being done only when pandas-compatibility mode is enabled.
=> Fix `CategoricalIndex` ordering in `Groupby.agg` when pandas-compatibility mode is enabled

python/cudf/cudf/core/algorithms.py, python/cudf/cudf/tests/test_factorize.py
closes #13981 
This PR enables parity with pandas `factorize` API by returning `codes` with `int64` dtype only in pandas-compatibility mode. When the pandas-compatibility mode is turned off, `cudf` will calculate the appropriate dtype that needs to be returned to save memory usage.
=> Enable `codes` dtype parity in pandas-compatibility mode for `factorize` API

cpp/src/strings/attributes.cu, cpp/src/strings/convert/convert_urls.cu
Adds `cudf::thread_index_type` usage when calculating the thread index in custom kernels in `src/strings/attributes.cu` and `src/strings/convert/convert_urls.cu`
=> Use cudf::thread_index_type in strings custom kernels

cpp/include/cudf/concatenate.hpp, cpp/include/cudf_test/column_wrapper.hpp, cpp/src/copying/concatenate.cu, cpp/tests/CMakeLists.txt, cpp/tests/streams/concatenate_test.cpp
=> Expose streams in public concatenate APIs

java/src/main/java/ai/rapids/cudf/Table.java, java/src/main/native/include/jni_utils.hpp, java/src/main/native/src/ContiguousTableJni.cpp, java/src/main/native/src/CudfJni.cpp, java/src/main/native/src/RmmJni.cpp, java/src/main/native/src/TableJni.cpp, java/src/main/native/src/cudf_jni_apis.hpp, java/src/main/native/src/jni_writer_data_sink.hpp
Fixes #13940 
Contributes to NVIDIA/spark-rapids#8889
- Pass an explicit host memory allocator to  `jni::allocate_host_buffer`
- Consistently check for errors from NewGlobalRef
- Consistently guard against DelteteGlobalRef on a null
=> Use HostMemoryAllocator in jni::allocate_host_buffer

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/tests/test_index.py
closes #13985
This PR fixes issues with `Index.difference` and `Index.intersection` API where the name selection was incorrect and `NA` values handling wasn't happening in these two APIs.
=> Fix `name` selection in `Index.difference` and `Index.intersection`

cpp/benchmarks/copying/copy_if_else.cpp
Adds `bytes_per_second` to the `COPY_IF_ELSE_BENCH` benchmark.
=> Add `bytes_per_second` to copy_if_else benchmark

cpp/benchmarks/hashing/partition.cpp
Adds `bytes_per_second` to the `PARTITION_BENCH` benchmark.
=> Add `bytes_per_second` to hash_partition benchmark

cpp/tests/utilities/column_utilities.cu, cpp/tests/utilities_tests/column_utilities_tests.cpp
Adds escaped `\\t` to the `cudf::test::to_string()` output.
Found this while working on #13891 where the output included tabs but was shown as a various number of spaces in the console when using `cudf::test::print()`.
Also added `\\b` for good measure as well as a gtest for all the supported escape sequences.
=> Add tab as literal to cudf::test::to_string output

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_multiindex.py
closes #13992 
This PR fixes the construction of an empty `MultiIndex` from `pandas` to `cudf` was causing an error in pandas-compatibility mode, null-array is one such case where it is _okay_ to cast to any type because there is no data in it. Hence we pass `str` dtype to `astype`, whenever we encounter an `object` dtype.
=> Fix an issue where casting null-array to `object` dtype will result in a failure

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_multiindex.py
closes #14008 
This PR ensures `MultiIndex.difference` returns `cudf.MultiIndex`.
=> Fix return type of `MultiIndex.difference`

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_interval.py
closes #14004 
This PR raises an error when an `IntervalIndex` contains a timezone-aware sub-type so that we don't go into infinite recursion.
=> Raise an error when timezone subtypes are encountered in `pd.IntervalDtype`

cpp/benchmarks/hashing/hash.cpp
In the past, the HASING_NVBENCH benchmark treated the `nulls` parameter as a boolean. Any value other than 0.0 resulted in a null probability of 1.0.
Now, the `nulls` parameter directly determines the null probability. For instance, a value of 0.1 will generate 10% of the data as null. Moreover, setting nulls to 0.0 produces data without a null bitmask.
Additionally, `bytes_per_second` are added to the benchmark.
=> Enable fractional null probability for hashing benchmark

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
We were previously obtaining zlib transitively through our cmake dependency, but since the 3.27.4 conda package, this dependency no longer exists. Therefore we must depend on zlib ourselves.
- Closes #14021
=> Explicitly depend on zlib in conda recipes

cpp/include/cudf/strings/split/split.hpp, cpp/src/strings/split/split.cu, cpp/src/strings/split/split_record.cu
Adds a `stream` parameter to the libcudf `cudf:strings::split(), cudf:strings::rsplit(), cudf:strings::split_record(), cudf:strings::rsplit_record()` APIs.
Change needed for work in #13891
=> Add stream parameter to public cudf::strings::split APIs

python/cudf/cudf/core/column/numerical_base.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_quantiles.py
closes #14002 
This PR changes the behavior of the `quantile` API by preserving the return type of scalar `interpolation` is either one of `"lower", "higher", "nearest"`.
=> Preserve types of scalar being returned when possible in `quantile`

cpp/include/cudf/contiguous_split.hpp
Fix for a typo in a docstring for `contiguous_split`.
=> Fix typo in docstring: metadata.

cpp/include/cudf/detail/utilities/cuda.cuh, cpp/include/cudf/detail/valid_if.cuh, cpp/src/bitmask/null_mask.cu, cpp/src/copying/scatter.cu, cpp/src/partitioning/partitioning.cu, cpp/src/replace/nulls.cu, cpp/src/rolling/jit/kernel.cu, cpp/src/transform/compute_column.cu
This PR adds `grid_1d::grid_stride()` and uses it in a handful of kernels. Follow-up to #13910, which added a `grid_1d::global_thread_id()`. We'll need to do a later PR that catches any missing instances where this should be used, since there are a large number of PRs in flight touching thread indexing code in various files. See #10368.
=> Use grid_stride for stride computations.

java/src/main/java/ai/rapids/cudf/HostMemoryReservation.java, java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
This adds in an API to java to reserve pinned memory. It is very much like allocating it, but provides a way to guarantee up front that there is enough memory for multiple allocations to succeed.
=> Added pinned pool reservation API for java

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/io/csv.py, python/cudf/cudf/io/json.py
Frame._dtypes maps column names to dtypes, however, it is a property that is computed on-demand. Consequently, a seemingly innocuous dict lookup is actually O(N). When used in a loop over columns, this makes an O(N) loop into an O(N^2) one.
This mostly bites on IO when reading data with many thousands of columns. To fix this, manually move access of Frame._dtypes outside of any loop over columns.
A more systematic way might be to make this a cached property, but the cache invalidation is rather hard to reason about.
- Closes https://github.com/rapidsai/cudf/issues/14005
=> Remove quadratic runtime due to accessing Frame._dtypes in loop

cpp/src/io/json/write_json.cu, cpp/tests/copying/gather_str_tests.cpp, cpp/tests/reshape/interleave_columns_tests.cpp, cpp/tests/strings/array_tests.cpp, cpp/tests/strings/attrs_tests.cpp, cpp/tests/strings/booleans_tests.cpp, cpp/tests/strings/case_tests.cpp, cpp/tests/strings/combine/concatenate_tests.cpp, cpp/tests/strings/combine/join_strings_tests.cpp, cpp/tests/strings/concatenate_tests.cpp, cpp/tests/strings/datetime_tests.cpp, cpp/tests/strings/durations_tests.cpp, cpp/tests/strings/fill_tests.cpp, cpp/tests/strings/find_multiple_tests.cpp, cpp/tests/strings/find_tests.cpp, cpp/tests/strings/integers_tests.cpp, cpp/tests/strings/ipv4_tests.cpp, cpp/tests/strings/pad_tests.cpp, cpp/tests/strings/replace_tests.cpp, cpp/tests/strings/reverse_tests.cpp, cpp/tests/strings/slice_tests.cpp, cpp/tests/strings/split_tests.cpp, cpp/tests/strings/strip_tests.cpp, cpp/tests/strings/translate_tests.cpp, cpp/tests/strings/urls_tests.cpp, cpp/tests/text/ngrams_tests.cpp
Replaces places where the `cudf::column_view(type,size,...)` constructor was used to create an empty view with a call to `cudf::make_column_view(type)->view()`.
This helps minimize the dependency on calling the constructors directly as part of the work needed for #13733 which may require an update to the `column_view` classes and its constructor(s).
Most of the changes occur in strings gtests source files.
No functionality or behavior has changed.
=> Use cudf::make_empty_column instead of column_view constructor

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_datetime.py, python/cudf/cudf/tests/test_interval.py
Currently `cudf.from_pandas` with a pandas Categorical with datetimetz type will drop the timezone information (due to pyarrow)
```python
In [5]: import pandas as pd
In [6]: ci = pd.CategoricalIndex(pd.date_range("2016-01-01 01:01:00", periods=5, freq="D").tz_localize("UTC"))
In [7]: ci
Out[7]: 
CategoricalIndex(['2016-01-01 01:01:00+00:00', '2016-01-02 01:01:00+00:00',
'2016-01-03 01:01:00+00:00', '2016-01-04 01:01:00+00:00',
'2016-01-05 01:01:00+00:00'],
categories=[2016-01-01 01:01:00+00:00, 2016-01-02 01:01:00+00:00, 2016-01-03 01:01:00+00:00, 2016-01-04 01:01:00+00:00, 2016-01-05 01:01:00+00:00], ordered=False, dtype='category')
In [8]: ci_cudf = cudf.from_pandas(ci)
In [10]: ci_cudf
Out[10]: 
CategoricalIndex(['2016-01-01 01:01:00', '2016-01-02 01:01:00',
'2016-01-03 01:01:00', …
```
=> Raise NotImplementedError for Categoricals with timezones

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_multiindex.py
Previously, the `sort_remaining` argument to `sort_index` was ignored. Passing `sort_remaining=False` would raise a `NotImplementedError`. Moreover, for a multiindex, `sort_remaining=True` was not handled correctly: if not all levels were requested as sorted, `sort_index` would behave as if `sort_remaining=False` had been passed.
To fix this case, construct the sort order based on first the provided levels and, if `sort_remaining=True`, the left-over levels (in index order).
To facilitate this, refactor the internal `_get_columns_by_label` function to always return a `Frame`-like object (previously, if we had a `Frame` we would get back a `ColumnAccessor`, and it was only for `IndexedFrame` and above that we'd get something of `Self`-like type back). This meant that calling …
=> Implement `sort_remaining` for `sort_index`

python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/tests/test_datetime.py
Avoids timezone information from being dropped in `to_datetime` when the z directive is provided
```python
In [2]: fmt = '%Y-%m-%d %H:%M:%S %Z'
...: dates = ['2010-01-01 12:00:00 UTC', '2010-01-01 12:00:00 UTC']
In [3]: cudf.to_datetime(dates, format=fmt)
Out[3]: DatetimeIndex(['2010-01-01 12:00:00', '2010-01-01 12:00:00'], dtype='datetime64[ns]')
```
=> Raise NotImplementedError for to_datetime with z format

cpp/include/cudf/search.hpp, cpp/src/search/contains_column.cu, cpp/src/search/contains_scalar.cu, cpp/src/search/search_ordered.cu, cpp/tests/CMakeLists.txt, cpp/tests/streams/search_test.cpp
=> Expose streams in public search APIs

python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/tests/test_datetime.py
Avoids the following incorrect behavior
```python
In [7]: cudf.to_datetime([True])
Out[7]: GenericIndex([True], dtype='bool')
In [1]: import pandas
In [2]: pandas.to_datetime([True])
TypeError: <class 'bool'> is not convertible to datetime
```
=> Raise TypeError for any non-parseable argument in to_datetime

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_multiindex.py
Fixes #14035 
This PR raises an error for `MultiIndex.to_series` because we cannot store `tuple` type columns in `cudf`.
=> Raise `NotImplementedError` for `MultiIndex.to_series`

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/decimal.py, python/cudf/cudf/tests/test_index.py
Fixes: #14041 
This PR fixes `fillna` that will preserve the type-metadata for `IntervalColumn`.
=> Fix `IntervalIndex.union` to preserve type-metadata

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_parquet.py, python/cudf/cudf/tests/test_series.py
Fixes #14038 
This PR introduces changes that raise an error when a column of `object` dtype is being constructed when the data is not string or bools.
=> Raise `MixedTypeError` when a column of mixed-dtype is being constructed

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_index.py
Fixes #14046 
This PR fixes empty string column construction that arises due to a corner-case in the way pyarrow constructs arrays.
=> Fix empty string column construction

ci/build_cpp.sh, ci/build_python.sh
Since Conda 23.7.3, the plugin mechanism changed, and mambabuild broke.
Since, with `boa` installed, `conda mambabuild` uses the `libmamba` solver, switch to that.
The general handling of subcommands with `mamba` was partially fixed in mamba-org/mamba#2732, but `mamba build` does not currently work due to mamba-org/mamba#2821.
- Closes #14068
=> Use `conda mambabuild` rather than `mamba mambabuild`

python/cudf/cudf/core/index.py, python/cudf/cudf/core/series.py, python/cudf/cudf/testing/_utils.py, python/cudf/cudf/tests/test_binops.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_series.py
Fixes: #14076 
This PR resolves renaming `Series` and `Index` by assigning `no_default` to internal API default parameters.
=> Fix renaming `Series` and `Index`

dependencies.yaml
Some platforms (such as aarch64 + CUDA 12) don't have a matching matrix entry for nvcomp. This PR adds a fallback matrix entry so it is possible to attempt local development on aarch64 with CUDA 12.
=> Add fallback matrix for nvcomp.

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_duplicates.py
Currently allows odd behavior like
```python
In [4]: df = cudf.DataFrame({"a": [1, 2, 1, 3]})
In [6]: df.drop_duplicates(ignore_index="True")
Out[6]: 
a
0  1
1  2
2  3
```
=> Validate ignore_index type in drop_duplicates

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_series.py
Fixes: #14083 
This PR fixes builtin function `round` call on `DataFrame` & `Series` to work by implementing `__round__` method.
=> Add support for `__round__` in `Series` and `DataFrame`

cpp/include/cudf_test/base_fixture.hpp
=> Only use memory resources that haven't been freed

python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/tests/test_stats.py
Fixes: #14090 
This PR allows passing `numeric_only=True` for reduction operation on numerical columns.
=> Allow `numeric_only=True` for reduction operations on numeric types

python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_series.py, python/dask_cudf/dask_cudf/core.py
Fixes: #14089 
This PR drops `kwargs` from `Series.count` method signature.
=> Drop `kwargs` from `Series.count`

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
Fixes: #14096 
This PR enables nested dict initialization support in `DataFrame` constructor.
=> Add support for nested dict in `DataFrame` constructor

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
Fixes: #14094 
This PR raises an error when an iterates of `DataFrame`'s is detected in `DataFrame` constructor.
=> Restrict iterables of `DataFrame`'s as input to `DataFrame` constructor

python/cudf/cudf/_lib/cpp/reduce.pxd
This Cython modules contains some cimports from higher-level modules than it should, which introduces the possibility for circular import issues. Also it contains an unused import of DeviceScalar that can cause similar issues.
=> Avoid circular cimports in _lib/cpp/reduce.pxd

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
This PR implements `GroupBy.value_counts`, matching the [pandas equivalent](https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.DataFrameGroupBy.value_counts.html) method.
Tests currently ignore the returned Series/DataFrame's name, as this was [added to pandas in v2.0.0](https://github.com/pandas-dev/pandas/commit/bec92a43feb0057f06f4f9b9db26c1a09232b1c0). This can be removed if tests are against `pandas>=2.0.0`.
Closes #12789
=> Implement `GroupBy.value_counts` to match pandas API

python/cudf/cudf/core/frame.py, python/cudf/cudf/tests/test_dataframe.py
Fixes the following
```python
In [32]: cudf.DataFrame(index=range(10)).values
Out[32]: array([], shape=(0, 0), dtype=float64)
```
=> Fix DataFrame.values with no columns but index

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
closes #14132
This PR removes the re-sorting of dataframe columns when initialized by a series list.
=> Don't sort columns for DataFrame init from list of Series

python/cudf/cudf/core/column/column.py
The main culprit is in the way the codes returned from _label_encoding were being ordered. We were generating an int64 column for the order, gathering through the left gather map, and then argsorting, before using that ordering as a gather map for the codes.
We note that gather(y, with=argsort(x)) is equivalent to sort_by_key(y, with=x) so use that instead (avoiding an unnecessary gather). Furthermore we also note that gather([0..n), with=x) is just equivalent to x, so we can avoid a gather too.
This reduces the peak memory footprint of categorifying a random column of 500_000_000 int32 values where there are 100 unique values from 24.75 GiB to 11.67 GiB.
```python
import cudf
import cupy as cp
K = 100
N = 500_000_000
rng = cp.random._generator.RandomState()
column = …
```
=> Reduce memory usage of as_categorical_column

cpp/src/io/orc/dict_enc.cu
Fixes memcheck error found during the nightly builds found in gtest `OrcWriterNumericTypeTest/0.SingleColumn`
```
========= COMPUTE-SANITIZER
Note: Google Test filter = OrcWriterNumericTypeTest/0.SingleColumn
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from OrcWriterNumericTypeTest/0, where TypeParam = signed char
[ RUN      ] OrcWriterNumericTypeTest/0.SingleColumn
========= Program hit cudaErrorInvalidConfiguration (error 9) due to "invalid configuration argument" on CUDA API call to cudaLaunchKernel.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x480aa6]
=========                in /usr/lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:cudaLaunchKernel …
```
=> Fix kernel launch error for cudf::io::orc::gpu::rowgroup_char_counts_kernel

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
Pin conda packages to `aws-sdk-cpp<1.11`. The recent upgrade in version `1.11.*` has caused several issues with cleaning up (more details on changes can be read in [this link](https://github.com/aws/aws-sdk-cpp#version-111-is-now-available)), leading to Distributed and Dask-CUDA processes to segfault. The stack for one of those crashes looks like the following:
```
(gdb) bt
#0  0x00007f5125359a0c in Aws::Utils::Logging::s_aws_logger_redirect_get_log_level(aws_logger*, unsigned int) () from /opt/conda/envs/dask/lib/python3.9/site-packages/pyarrow/../../.././libaws-cpp-sdk-core.so
#1  0x00007f5124968f83 in aws_event_loop_thread () from /opt/conda/envs/dask/lib/python3.9/site-packages/pyarrow/../../../././libaws-c-io.so.1.0.0
#2  0x00007f5124ad9359 in thread_fn () from …
```
=> Pin to `aws-sdk-cpp<1.11`

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, conda/recipes/libcudf/meta.yaml, dependencies.yaml
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> Forward-merge branch-23.10 to branch-23.12

.github/ops-bot.yaml
This check occasionally hangs for `cudf` for unknown reasons.
Upon checking the application logs, the GitHub API seems to be returning responses that aren't helpful in troubleshooting the problem.
Therefore, it's probably best to just remove the check to avoid confusion.
[skip ci]
=> Disable `Recently Updated` Check

cpp/src/io/utilities/data_casting.cu
Workaround for illegal instruction error in sm90 for warp instrinsics with non `0xffffffff` mask
Removed the mask, and used ~0u (`0xffffffff`) as MASK because
- all threads in warp has correct data on error since is_within_bounds==true thread update error.
- init_state is not required at last iteration only where MASK is not ~0u.
Fixes #14183
=> Workaround for illegal instruction error in sm90 for warp instrinsics with mask

python/cudf/cudf/core/join/join.py
If we drop the gather maps as soon as we are done with them, we have a little more headroom for joins that are close to hitting the device memory limit.
=> Marginally reduce memory footprint of joins

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/java/ai/rapids/cudf/DType.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR adds a method to ColumnView class to allow for conversion from Integers to hex
closes #14081
=> [Java] Add JNI bindings for `integers_to_hex`

ci/test_wheel_dask_cudf.sh, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/custreamz/meta.yaml, conda/recipes/dask-cudf/meta.yaml, conda/recipes/dask-cudf/run_test.sh, dependencies.yaml, python/dask_cudf/pyproject.toml
This PR pins `dask` and `distributed` to `2023.9.2` for `23.10` release.
=> Pin `dask` and `distributed` for `23.10` release

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, dependencies.yaml
This PR builds conda packages using CUDA 12 on ARM.
This work is targeting 23.12 and depends on https://github.com/rapidsai/rmm/pull/1330.
Closes #14128.
=> cuDF: Build CUDA 12.0 ARM conda packages.

cpp/src/round/round.cu, cpp/tests/round/round_tests.cpp
Fixes a bug where floating-point values were used in decimal128 rounding, giving wrong results.
Closes https://github.com/rapidsai/cudf/issues/14210.
=> Fix inaccuracy in decimal128 rounding.

cpp/src/strings/replace/replace.cu, cpp/tests/strings/replace_tests.cpp
Fixes bug that can occur when replacing all occurrences in a string using a multi-byte UTF-8 target when the target matches sequentially in the same string -- some characters were missed.
Specialized gtest is also added.
Found while working on #13891
=> Fix strings replace for adjacent, identical multi-byte UTF-8 character targets

cpp/include/cudf/detail/utilities/pinned_host_vector.hpp
Fixes #14165
The deallocate function is called by the `pinned_host_vector`. Throwing from destructors is bad since they can't be caught, and generally get converted into runtime sig aborts.
=> cudf::detail::pinned_allocator doesn't throw from `deallocate`

cpp/include/cudf/strings/padding.hpp, cpp/include/cudf/strings/slice.hpp, cpp/include/cudf/strings/strip.hpp, cpp/include/cudf/strings/wrap.hpp, cpp/src/strings/padding.cu, cpp/src/strings/slice.cu, cpp/src/strings/strip.cu, cpp/src/strings/wrap.cu, cpp/tests/CMakeLists.txt, cpp/tests/streams/strings/strings_tests.cpp
Add stream parameter to public APIs:
- `cudf::strings::strip()`
- `cudf::strings::slice_strings()`
- `cudf::strings::pad()`
- `cudf::strings::zfill()`
- `cudf::strings::wrap()`
Also cleaned up some of the doxygen comments and added stream-tests.
Reference #13744
=> Expose stream parameter in public strings APIs

cpp/src/io/json/nested_json_gpu.cu, cpp/tests/io/json_test.cpp, cpp/tests/io/nested_json_test.cpp
Closes https://github.com/rapidsai/cudf/issues/14227. Adapts the behaviour of the JSON finite-state transducer (FST) when `recover_with_nulls` is `true` to be more strict and reject lines that contain incomplete JSON objects (aka records) or JSON arrays (aka lists).
=> Fixes behaviour for incomplete lines when `recover_with_nulls` is enabled

python/cudf/cudf/_fuzz_testing/csv.py, python/cudf/cudf/_fuzz_testing/json.py, python/cudf/cudf/_lib/column.pyx, python/cudf/cudf/_lib/csv.pyx, python/cudf/cudf/_lib/groupby.pyx, python/cudf/cudf/_lib/json.pyx, python/cudf/cudf/_lib/utils.pyx, python/cudf/cudf/api/types.py, python/cudf/cudf/core/_internals/where.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/dtypes.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/reshape.py, python/cudf/cudf/core/tools/numeric.py, python/cudf/cudf/testing/testing.py, python/cudf/cudf/tests/test_api_types.py, python/cudf/cudf/tests/test_column.py, python/cudf/cudf/tests/test_concat.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/utils/dtypes.py, python/dask_cudf/dask_cudf/backends.py, python/dask_cudf/dask_cudf/sorting.py
This PR deprecates `is_categorical_dtype` to match https://github.com/pandas-dev/pandas/pull/52527 which was introduced in `pandas-2.x`. This PR internalizes the public API since this is a needed utility in our code base.
This PR:
```
= 23835 failed, 5698 passed, 1613 skipped, 288 xfailed, 423 errors in 1976.84s (0:32:56) =
```
```
= 24297 failed, 5115 passed, 1613 skipped, 288 xfailed, 480 errors in 1980.46s (0:33:00) =
```
=> Deprecate `is_categorical_dtype`

python/cudf/cudf/_lib/column.pyx, python/cudf/cudf/_lib/groupby.pyx, python/cudf/cudf/api/types.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/dtypes.py, python/cudf/cudf/core/index.py, python/cudf/cudf/testing/testing.py
This PR deprecates `is_datetime64tz_dtype` and `is_interval_dtype` to have parity with pandas-2.x: https://github.com/pandas-dev/pandas/pull/52607, alternatively this PR internalizes these utilities.
This PR:
```
= 1584 failed, 98570 passed, 2069 skipped, 776 xfailed, 312 xpassed, 20 errors in 737.24s (0:12:17) =
```
```
= 23835 failed, 5698 passed, 1613 skipped, 288 xfailed, 423 errors in 1976.84s (0:32:56) =
```
=> Deprecate `is_datetime64tz_dtype` and `is_interval_dtype`

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/resample.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_groupby.py, python/cudf/cudf/tests/test_replace.py
This PR deprecates `method` parameter in all public `fillna` APIs to match pandas: https://github.com/pandas-dev/pandas/pull/53496/
This PR:
```
= 1056 failed, 99098 passed, 2069 skipped, 776 xfailed, 312 xpassed, 20 errors in 670.87s (0:11:10) =
```
```
= 1584 failed, 98570 passed, 2069 skipped, 776 xfailed, 312 xpassed, 20 errors in 737.24s (0:12:17) =
```
=> Deprecate `method` in `fillna` API

cpp/cmake/thirdparty/get_arrow.cmake, cpp/cmake/thirdparty/get_cufile.cmake, cpp/cmake/thirdparty/get_gtest.cmake, cpp/cmake/thirdparty/get_kvikio.cmake, cpp/cmake/thirdparty/get_libcudacxx.cmake, cpp/cmake/thirdparty/get_spdlog.cmake, cpp/cmake/thirdparty/get_thrust.cmake
Update to use non deprecated signatures for `rapids_export` functions
=> Update rapids-cmake functions to non-deprecated signatures

cpp/src/text/edit_distance.cu
Fixes a bug in `nvtext::edit_distance_matrix` where the internal offsets vector is initialized to 0. 
This error was introduced in #13912 
The bug was found while working on a different PR which re-ordered the nvtext gtests execution causing device memory to be reused from the rmm pool in a different way.
=> Fix memset error in nvtext::edit_distance_matrix

cpp/include/cudf/lists/extract.hpp, cpp/include/cudf/lists/filling.hpp, cpp/include/cudf/lists/gather.hpp, cpp/include/cudf/lists/reverse.hpp, cpp/include/cudf/lists/sorting.hpp, cpp/include/cudf/lists/stream_compaction.hpp, cpp/src/lists/copying/segmented_gather.cu, cpp/src/lists/extract.cu, cpp/src/lists/reverse.cu, cpp/src/lists/segmented_sort.cu, cpp/src/lists/sequences.cu, cpp/src/lists/stream_compaction/apply_boolean_mask.cu, cpp/src/lists/stream_compaction/distinct.cu, cpp/tests/groupby/histogram_tests.cpp, cpp/tests/streams/lists_test.cpp
This PR introduces the stream parameter to the List Sorting and Filtering APIs.
Sorting and Filtering (`extract.hpp`, `filling.hpp`, `gather.hpp`, `reverse.hpp`, `sorting.hpp`, `stream_compaction.hpp`)
```
extract_list_element - index
extract_list_element - indices
segmented_gather
sequences - without steps
sequences - with steps
reverse
sort_lists
stable_sort_lists
apply_boolean_mask
distinct
```
Reference [13744](https://github.com/rapidsai/cudf/issues/13744)
=> Add stream parameter to List Sort and Filter APIs

python/cudf/cudf/core/buffer/spill_manager.py, python/cudf/cudf/core/buffer/spillable_buffer.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/core/series.py, python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/core/udf/groupby_utils.py, python/cudf/cudf/core/udf/utils.py, python/cudf/cudf/io/csv.py, python/cudf/cudf/io/parquet.py, python/cudf/cudf/io/text.py, python/cudf/cudf/utils/nvtx_annotation.py, python/cudf/cudf/utils/utils.py, python/dask_cudf/dask_cudf/backends.py, python/dask_cudf/dask_cudf/core.py, python/dask_cudf/dask_cudf/groupby.py, python/dask_cudf/dask_cudf/sorting.py
In nsys traces, it is useful to be able to see when memory allocations are provoking cudf-managed spilling. Do this by adding appropriate nvtx annotations.
To enable this, we must move the nvtx decorators to a separate file avoiding circular imports.
=> Add nvtx annotations to spilling-based data movement

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, ci/release/update-version.sh
Update `shared-action-workflows` references to `shared-actions` following the work to rename the `rapidsai/shared-action-workflows` to `rapidsai/shared-workflows`.
This is a backport fix as these changes had [originally been implemented](https://github.com/rapidsai/cudf/pull/14289) for `23.12`. The backport is necessary for a `branch-23.10` hotfix.
=> Update `shared-action-workflows` references (backport from `23.12` to `23.10`)

cpp/src/io/parquet/page_enc.cu
=> test is_valid before reading column data

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, cpp/tests/io/orc_test.cpp, dependencies.yaml, docs/cudf/source/conf.py, docs/dask_cudf/source/conf.py, python/cudf/cudf/_fuzz_testing/orc.py, python/cudf/cudf/_fuzz_testing/utils.py, python/cudf/cudf/tests/test_orc.py, python/cudf/pyproject.toml
This PR removes dependency on `pyorc` in `cudf` altogether by using drop-in replacements found in `pandas` & `pyarrow`.
=> Drop `pyorc` dependency and use `pandas`/`pyarrow` instead

ci/test_wheel_dask_cudf.sh, python/dask_cudf/dask_cudf/io/tests/test_parquet.py
We are not currently running any IO tests for `dask_cudf` in CI. This PR should correct this. It also modifies a test that *would* be failing due to https://github.com/rapidsai/cudf/issues/14326
=> Run IO tests for Dask-cuDF

cpp/src/io/parquet/reader_impl_preprocess.cu
Closes https://github.com/rapidsai/cudf/issues/14311
The host access becomes an issue when pageable memory is used for host side of `hostdevice_vector`.
This PR fixes the device lambda to use the device pointer instead.
=> Fix host buffer access from device function in the Parquet reader

ci/test_python_other.sh
@rjzamora recently identified and fixed(https://github.com/rapidsai/cudf/pull/14327/) an issue where `dask_cudf/io` pytests weren't being run in ci, however, this was fixed for wheels pytests. This PR fixes the same issue in `conda` pytests.
=> Enable `dask_cudf/io` pytests in CI

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml, python/cudf/pyproject.toml
As of fastavro 1.9.0 (released on October 27) [the recommend method for snappy decompression is via the cramjam package](https://github.com/fastavro/fastavro/blob/62ea68fe22e11ff5ff5dc86dfe942c7d51d7c157/ChangeLog#L3). We need to install it [to avoid getting deprecation warnings involving python-snappy usage](https://github.com/fastavro/fastavro/issues/722).
=> Add cramjam

.github/workflows/build.yaml
#14339 added the ability to build cudf wheels against a newer manylinux, but those jobs were not added to the build matrix, only the PR matrix, so the newer ABI wheels aren't currently being published.
=> Add the new manylinux builds to the build job

python/cudf/cudf/tests/test_stats.py
This PR fixes a pytest typo that pytest framework somehow conveniently ignores and continues to execute.
=> Fix a pytest typo in `test_kurt_skew_error`

.github/workflows/build.yaml, .github/workflows/pr.yaml, ci/build_docs.sh
Reverts build changes from #14376.
Merge _after_ docs deployment completes.
=> Revert changes to docs build scripts.

cpp/CMakeLists.txt, cpp/include/cudf/strings/detail/scan.hpp, cpp/include/cudf/structs/detail/scan.hpp, cpp/src/reductions/scan/scan_inclusive.cu, cpp/src/strings/scan/scan_inclusive.cu, cpp/src/structs/scan/scan_inclusive.cu
Splits out the `strings` and `struct` specializations in `scan_inclusive.cu` into separate source files to improve compile time.
Each specialization is unique code with limited aggregation types.
No functional changes. Just code moved around.
Found while working on #14234
=> Split up scan_inclusive.cu to improve its compile time

cpp/cmake/thirdparty/patches/nvbench_override.json
Port https://github.com/NVIDIA/nvbench/pull/148 to cudf so that nvbench benchmarks work now that we always use a static version of nvbench.
=> Ensure nvbench initializes nvml context when built statically

conda/recipes/custreamz/meta.yaml
#14407 added a dask dependency to custreamz, but it added too tight of a pinning by requiring the exact same version. This is not valid because rapids-dask-dependency won't release a new version corresponding to each new cudf release, so pinning to the exact same version up to the alpha creates an unsatisfiable constraint.
=> Fix dask dependency in custreamz

.github/workflows/test.yaml
This PR fixes a nightly test failure due to an extraneous `needs:` entry in `test.yaml`.
```
Invalid workflow file: .github/workflows/test.yaml#L100
The workflow is not valid. .github/workflows/test.yaml (Line: 100, Col: 12): Job 'unit-tests-cudf-pandas' depends on unknown job 'wheel-build-cudf'.
```
=> Remove needs: wheel-build-cudf.

.github/workflows/test.yaml, ci/release/update-version.sh, cpp/examples/README.md, cpp/examples/basic/CMakeLists.txt, cpp/examples/build.sh, cpp/examples/fetch_dependencies.cmake, cpp/examples/nested_types/CMakeLists.txt, cpp/examples/nested_types/deduplication.cpp, cpp/examples/nested_types/example.json, cpp/examples/strings/CMakeLists.txt
Forward-merge triggered by push to `branch-23.12` that creates a PR to keep `branch-24.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> Forward-merge branch-23.12 to branch-24.02

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_series.py, python/dask_cudf/dask_cudf/backends.py
Bacport of #14400 
Fixes: #14398 
This PR raises an error in `reindex` API when reindexing is performed on a non-unique index column.
Authors:
- GALI PREM SAGAR (https://github.com/galipremsagar)
Approvers:
- Matthew Roeschke (https://github.com/mroeschke)
- Lawrence Mitchell (https://github.com/wence-)
URL: https://github.com/rapidsai/cudf/pull/14400
=> Raise error in `reindex` when `index` is not unique

cpp/src/io/json/write_json.cu
Added the true/false string scalars to `column_to_strings_fn` so they are created once, instead of creating new scalars for each boolean column (using default stream).
=> JSON writer: avoid default stream use in `string_scalar` constructors

docs/cudf/source/user_guide/data-types.md
cuDF CI is failing to build docs due to an ambiguous reference `io`. This PR makes that reference unambiguous.
```
/__w/cudf/cudf/docs/cudf/source/user_guide/data-types.md:139: WARNING: Multiple matches found for 'io': pandas:std:label:io, pyarrow:std:label:io, python:py:module:io [myst.iref_ambiguous]
```
I used this output to help me find the object inventory that lists this.
```bash
python -m sphinx.ext.intersphinx https://docs.rapids.ai/api/cudf/stable/objects.inv
```
I also looked at the MyST docs on external references. https://mystmd.org/guide/external-references
=> Fix io reference in docs.

cpp/src/io/parquet/decode_preprocess.cu, cpp/src/io/parquet/page_data.cu, cpp/src/io/parquet/page_decode.cuh, cpp/src/io/parquet/page_enc.cu, cpp/src/io/parquet/page_string_decode.cu
`volatile` should no be required in our code, unless there are compiler or synchronization issues.
This PR removes the use in Parquet reader and writer.
=> Remove the use of `volatile` in Parquet

cpp/include/nvtext/edit_distance.hpp, cpp/include/nvtext/stemmer.hpp, cpp/src/text/edit_distance.cu, cpp/src/text/stemmer.cu, cpp/tests/CMakeLists.txt, cpp/tests/streams/text/edit_distance_test.cpp, cpp/tests/streams/text/stemmer_test.cpp
Add stream parameter to public APIs:
- `nvtext::is_letter()`
- `nvtext::porter_stemmer_measure`
- `nvtext::edit_distance()` 
- `nvtext::edit_distance_matrix()`
Also cleaned up some of the doxygen comments and added stream gtests.
Reference #13744
=> Expose stream parameter in public nvtext APIs

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/groupby/test_agg.py
A count aggregation should always return an int64 column, even if the grouped dataframe is empty. Previously we did not do this because the short-circuiting for empty inputs was hit before handling the count case. Fix this by reordering the conditions.
- Closes https://github.com/rapidsai/cudf/issues/14200
=> Correct dtype of count aggregations on empty dataframes

cpp/tests/reductions/rank_tests.cpp
Removes a non-empty null entry from a test strings column utility in `rank_tests.cpp`.
Behavior with unsanitized nulls in at best UB and should not be included in unit tests.
=> Remove unsanitized null from input strings column in rank_tests.cpp

cpp/tests/ast/transform_tests.cpp
This PR addresses the issue at #14409. I would like to propose the addition of unit tests that involve scenarios like having 100 or 1000 elements in a tree, reaching 100 levels of depth, with diferent data types and similar stress tests. The purpose of these tests is to conduct comprehensive testing and stress the Abstract Syntax Tree (AST), ultimately aiding in the identification and resolution of any potential issues.
By introducing these pathological tests, we aim to ensure the robustness and reliability of our codebase. These tests can help us uncover edge cases and performance bottlenecks that might otherwise go unnoticed.
=> Introduce Comprehensive Pathological Unit Tests for Issue #14409

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/decimal.py, python/cudf/cudf/core/column/numerical_base.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_search.py
Previously a number of algorithms on Columns first converted to a single column frame and called a frame-based algorithm (which calls directly into libcudf using the column we first thought of). This is unnecessary since we already have the column to hand when calling the same algorithm at the column level. Moreover, in many cases where the algorithm is a user-facing API, the frame-based approach does more work (for example conversions and dtype matching).
By removing this round trip we reduce some (unnecessary) overhead, and also make the memory footprint and behaviour of column-based methods more transparent.
- Closes #13565
=> Expunge as_frame conversions in Column algorithms 

cpp/include/cudf/ast/expressions.hpp, cpp/include/cudf/column/column_device_view.cuh, cpp/include/cudf/dictionary/update_keys.hpp, cpp/include/cudf/io/types.hpp, cpp/include/cudf/lists/lists_column_view.hpp, cpp/include/cudf/strings/strings_column_view.hpp, cpp/include/cudf/structs/structs_column_view.hpp, cpp/include/cudf/utilities/default_stream.hpp, cpp/include/cudf/utilities/span.hpp, cpp/include/doxygen_groups.h
This PR fixes some errors in the doxygen docs and adds groups for some items that were previously missing altogether.
=> Some doxygen improvements

python/cudf/cudf/pandas/__main__.py, python/cudf/cudf_pandas_tests/data/profile_basic.py, python/cudf/cudf_pandas_tests/test_profiler.py
Fixes: #14512 
This PR fixes a function name typo in `cudf.pandas` profiler.
=> Fix function name typo in `cudf.pandas` profiler

cpp/src/io/csv/reader_impl.cu, cpp/tests/streams/io/csv_test.cpp
String scalars, used to replace double quotes, are implicitly created from `std::string`s, using the default stream. In addition, these scalars are created for each string column.
This PR changes how these objects are created to avoid redundant H2D copies and the use of the default stream.
=> Fix default stream use in the CSV reader

java/src/main/java/ai/rapids/cudf/DefaultHostMemoryAllocator.java
spark-rapids requires the ability to set DefaultHostMemoryAllocator
Contributes to NVIDIA/spark-rapids#9862
=> Make DefaultHostMemoryAllocator settable

cpp/include/nvtext/byte_pair_encoding.hpp, cpp/src/text/bpe/load_merge_pairs.cu
Remove deprecated `nvtext::load_merge_pairs_file` since it is not needed -- in favor `nvtext::load_merge_pairs` which accepts a strings column. Callers can use cuIO functions to load the file into a column.
=> Remove deprecated nvtext::load_merge_pairs_file

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/multiindex.py
Previously, isin was implemented using an inner join between the column we are searching (the haystack) and the values we are searching for (the needles). This had a large memory footprint when there were repeated needles (since that blows up the cardinality of the merge).
To fix this, note that we don't need to do a merge at all, since libcudf provides a primitive (contains) to search for many needles in a haystack. The only thing we must bear in mind is that left.isin(right) is asking for the locations in left that match an entry in right, whereas contains(haystack, needles) provides a bool mask that selects needles that are in the haystack. To get the behaviour we want, we therefore need to do contains(right, left) and treat the values to search for as the haystack.
As well as having a …
=> Improve memory footprint of isin by using contains

cpp/src/io/statistics/statistics.cuh
Removed the use of volatile, not required now that it's not used in ORC or Parquet.
Small template simplification.
=> Small clean up in `io::statistics`

cpp/doxygen/Doxyfile, cpp/include/cudf/io/text/byte_range_info.hpp, cpp/include/cudf_test/column_utilities.hpp, cpp/include/cudf_test/column_wrapper.hpp
Doxygen-generated XML is parsed by Breathe, so this is a prerequisite for #13846.
=> Enable doxygen XML generation and fix issues

python/cudf/cudf/core/column/column.py
This PR replaces usages of `PandasArray` with `NumpyExtensionArray` to not have warnings during runtime.
```
= 15895 failed, 61649 passed, 1840 skipped, 735 xfailed, 312 xpassed, 371 errors in 4361.35s (1:12:41) =
```
On this PR:
```
= 923 failed, 100684 passed, 2071 skipped, 786 xfailed, 312 xpassed, 20 errors in 1216.98s (0:20:16) =
```
=> Replace `PandasArray` with `NumpyExtensionArray`

python/cudf/cudf/core/column_accessor.py
This PR fixes a copy creation in `ColumnAccessor` by properly passing the `rangeindex` and `label_dtype` to it's newly constructed object.
=> Fix copy creation of a `ColumnAccessor`

python/cudf/cudf/tests/test_parquet.py, python/cudf/cudf/tests/test_udf_masked_ops.py
This PR removes `nullable=True` in two pytests as we error when `nullable` is passed when there is decimal / list / struct data.
=> Fix `to_pandas` calls in pytests

python/cudf/cudf/api/types.py, python/cudf/cudf/tests/test_api_types.py
This PR adds back `cudf.api.types.is_categorical` that was missing due to a bad merge.
=> Add missing `is_categorical_dtype` to `cudf.api.types` namespace

python/cudf/cudf/core/_base_index.py
This PR fixes result names for `Index.difference` in some early exit scenarios.
=> Fix result name in `Index.difference`

cpp/include/cudf/table/table_view.hpp, cpp/src/table/table_view.cpp
Moves some `inline` functions from the `table_view.hpp` to the `table_view.cpp` to help reduce dependency bloat.
Also reference #14531: I'd like to minimize changes to the highly inclusive `table_view.hpp`.
Closes #14431
=> Move non-templated inline function definitions from table_view.hpp to table_view.cpp

python/cudf/cudf/core/series.py
This PR fixes the return type of `Series.value_counts` to return `int64`, correcting a typo that was `int34`.
=> Fix typo in `Series.value_counts`

cpp/src/io/parquet/page_string_decode.cu
Fixes an issue detected in Spark where string data was being corrupted due to an incorrect page size calculation.
Closes #14560
=> Fix data corruption when skipping rows

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_multiindex.py
This PR enforces deprecations of `Index.to_frame` and updates pytests related to this API.
=> Enforce `Index.to_frame` deprecations

docs/cudf/source/user_guide/api_docs/dataframe.rst, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_applymap.py, python/cudf/cudf/tests/test_parquet.py
Pandas 2.1.0 deprecated `DataFrame.applymap`, This PR deprecated `applymap` and introduces `map` to be used as the new alternative API.
=> Deprecate `DataFrame.applymap` and use `map` instead

cpp/tests/io/json_tree.cpp
Changes the `NJP_DEBUG_DUMP` environment variable used in `json_tree.cpp` gtest source to a local `#define` compile-time definition instead. This preserves the rather complex code for debugging json parsing without requiring building it otherwise.
This is part of larger work to refactor and document env vars in the libcudf code.
=> Change json gtest environment variable to compile-time definition

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, conda/recipes/libcudf/conda_build_config.yaml, dependencies.yaml
This fixes some memcheck errors found by the libcudf nightly builds as documented here: #14440
=> Upgrade to nvCOMP 3.0.5

cpp/src/io/parquet/page_delta_decode.cu, cpp/src/text/jaccard.cu
Found some invalid return statements when compiling cudf with a newer gcc.
=> Correct invalid or missing return types

cpp/include/cudf_test/file_utilities.hpp
Removes the `WORKSPACE` env var check from the `cudf_test` `temp_directory` class. This env var is not being used. This is part of a larger effort to consolidate and document libcudf env vars.
=> Remove WORKSPACE env var from cudf_test temp_directory class

cpp/src/dictionary/decode.cu, cpp/tests/dictionary/slice_test.cpp
Fixes `cudf::dictionary::decode` logic to produced sanitized null entries for compound column types.
Reference: #14559 -- fixes many of the errors found here concerning dictionary column gtests.
=> Fix unsanitized nulls produced by libcudf dictionary decode

cpp/src/reductions/segmented/simple.cuh
Fixes the string specialization logic in `cudf::segmented_reduce` to not produce unsanitized null entries. The functor used to build a gather map for argmin/argmax was corrected to handle include/exclude nulls correctly.
Reference: #14559
=> Fix unsanitized nulls from strings segmented-reduce

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py
Fixes the following behavior
```python
In [2]: import pandas as pd
In [3]: df = cudf.DataFrame([1], columns=cudf.Index([1], name="foo"))
In [4]: df
Out[4]: 
foo  1
0    1
In [5]: df = df.reindex(index=[0, 1])
In [6]: df
Out[6]: 
1  <-- foo missing
0     1
1  <NA>
```
=> Fix DataFrame.reindex removing column name

cpp/src/quantiles/tdigest/tdigest_aggregation.cu
This removes `cuda::proclaim_return_type` from a device lambda because that lambda is going to be nested inside another device lambda, which is in turn enclosed by `cuda::proclaim_return_type`. 
This PR is to fix a compile issue that we encountered:
```
/usr/local/cuda/include/cuda/std/detail/libcxx/include/__functional/invoke.h(402): error: 
calling a __device__ function("cudf::tdigest::detail::_NV_ANON_NAMESPACE::build_output_column(int,   
::std::unique_ptr<   ::cudf::column,     ::std::default_delete<   ::cudf::column> >  &&,     ::std::unique_ptr<   ::cudf::column,     ::std::default_delete<   ::cudf::column> >  &&,     ::std::unique_ptr<   ::cudf::column,     ::std::default_delete<   ::cudf::column> >  &&,     ::std::unique_ptr<   ::cudf::column,     ::std::default_delete< …
```
=> Remove `cuda::proclaim_return_type` from nested lambda

cpp/tests/copying/copy_if_else_nested_tests.cpp, cpp/tests/copying/purge_nonempty_nulls_tests.cpp
Removes unsanitized rows from input data in gtests for COPYING_TEST.
This fixes some errors found in #14559
=> Remove unsanitized input test data from copy gtests

cpp/include/cudf/detail/stream_compaction.hpp, cpp/include/cudf/stream_compaction.hpp, cpp/src/stream_compaction/distinct.cu, cpp/src/stream_compaction/stable_distinct.cu, python/cudf/cudf/_lib/cpp/stream_compaction.pxd, python/cudf/cudf/_lib/stream_compaction.pyx, python/cudf/cudf/core/indexed_frame.py
To obtain the duplicate rows in a dataframe we previously performed a drop-duplicates with a carrier column of row indices and then set entries in a boolean column to False for those row indices that remained. Furthermore, we were performing an unnecessary merge after the drop-duplicates call to obtain the row indices.
Note that the carrier column provides exactly the information that is computed internally in `libcudf` by `cudf::detail::get_distinct_indices` (called as part of `cudf::distinct`). We therefore promote `get_distinct_indices` to a public function (as `cudf::distinct_indices`) and replace the (unnecessary) merge plus `iloc`-based setting of the result with a call to `libcudf.copying.scatter`.
This provides a reasonable speedup (around 1.5x) for `duplicated()` on `Series`, and …
=> Implement `IndexedFrame.duplicated` with `distinct_indices` + `scatter`

.gitignore
Adds `cpp/doxygen/xml` to `.gitignore`. This directory is created with a docs build.
=> Add cpp/doxygen/xml to .gitignore

python/cudf/cudf/_lib/cpp/hash.pxd, python/cudf/cudf/_lib/hash.pyx, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py
This PR refactors the Python code for `IndexedFrame.hash_values` to use the newer named C++ functions from `cudf::hashing::*`. I also added bindings for xxhash64 and updated some tests.
Needed for #14391.
=> Refactor IndexedFrame.hash_values to use cudf::hashing functions, add xxhash64 to cudf Python.

cpp/src/json/json_path.cu
Removes unsanitized rows from output result of `cudf::get_json_object` which may occur when querying an array path `$[*]` does not find any matches in the target string. In this case, a single `'['` remains in the output buffer (per row) though the row is marked as a null entry.
This fixes the `JsonPathTests.GetJsonObjectInvalidQuery` error found in https://github.com/rapidsai/cudf/pull/14559
=> Remove non-empty nulls in cudf::get_json_object

python/cudf/cudf/api/types.py
PyTorch tensors advertise that they support the number API, and hence answer "True" to the question pd.api.types.is_scalar(torch_tensor). This trips up some of our data ingest, since in as_index we check if the input is a scalar (and raise) before handing off to as_column. To handle this, if we get True back from pandas' is_scalar call, additionally check that the object has an empty shape attribute (if it exists).
See also:
- https://github.com/pytorch/pytorch/issues/99646
- https://github.com/pandas-dev/pandas/issues/52701
=> Add (implicit) handling for torch tensors in is_scalar

python/cudf/cudf/core/dtypes.py
This PR fixes the docstring in `CategoricalDtype` where the repr has added a new field (`categories_dtype`).
This PR fixes 2 doctest failures.
=> Fix docstring in `CategoricalDtype`

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py
This PR fixes sorting of a MultiIndex by removing an existing hard-coded `na_position` value that was based on `ascending` flag, essentially ignoring the user-passed parameter.
```
= 501 failed, 101106 passed, 2071 skipped, 786 xfailed, 312 xpassed, 20 errors in 1234.91s (0:20:34) =
```
This PR:
```
= 405 failed, 101034 passed, 2071 skipped, 954 xfailed, 312 xpassed, 20 errors in 1124.69s (0:18:44) =
```
=> Fix `DataFrame.sort_index` when a index is a `MultiIndex`

python/cudf/cudf/_lib/string_casting.pyx, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/decimal.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/single_column_frame.py, python/cudf/cudf/tests/test_column.py, python/cudf/cudf/tests/test_string.py
Remove unnecessary "inference" on `[]` in as_column. Additionally fixed a bug in `arange` and `istimestamp` to return an int and bool type respectively for empty inputs for consistency with non-empty inputs
=> Use column_empty over as_column([])

cpp/include/cudf/contiguous_split.hpp, cpp/include/cudf/fixed_point/fixed_point.hpp, cpp/include/cudf/io/orc_metadata.hpp, cpp/include/cudf/io/orc_types.hpp, cpp/include/cudf/io/parquet_metadata.hpp, cpp/include/cudf/io/types.hpp, cpp/include/cudf/rolling/range_window_bounds.hpp, cpp/include/cudf/strings/split/split.hpp, cpp/include/cudf/tdigest/tdigest_column_view.hpp, cpp/include/cudf/utilities/span.hpp, cpp/include/doxygen_groups.h
This PR fixes a few errors and typos in C++ docs, adds some members to groups that previously weren't in one, and adds documentation for a few undocumented enums.
=> More doxygen fixes

cpp/cmake/thirdparty/patches/nvbench_override.json
We can drop a patch from nvbench for nvml support now that it has been upstreamed and dropped from rapids-cmake. https://github.com/rapidsai/rapids-cmake/pull/488
=> Drop nvbench patch for nvml.

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/column/lists.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/core/column/struct.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/dtypes.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/series.py, python/cudf/cudf/core/tools/numeric.py, python/cudf/cudf/testing/testing.py, python/cudf/cudf/utils/dtypes.py
Internally IMO we should prefer `isinstance` over `is_*_dtype` when we know the input is a dtype instance in order to be stricter/faster that the `is_*_dtype` checks
=> Use isinstance over is_foo_dtype internally

python/cudf/cudf/_lib/copying.pyx, python/cudf/cudf/_lib/pylibcudf/column.pxd, python/cudf/cudf/_lib/pylibcudf/column.pyx, python/cudf/cudf/_lib/pylibcudf/copying.pxd, python/cudf/cudf/_lib/pylibcudf/copying.pyx, python/cudf/cudf/_lib/pylibcudf/table.pxd, python/cudf/cudf/_lib/pylibcudf/table.pyx, python/cudf/cudf/_lib/scalar.pxd, python/cudf/cudf/_lib/scalar.pyx
This PR implements the remaining parts of libcudf's copying APIs in pylibcudf, updating cuDF Python to use those as a backend. The cudf copying Cython module is now largely just a set of pylibcudf calls. This represents the general transition that we hope to make, and eventually once all of cudf looks like this we can refactor its internal data structures to be built directly around pylibcudf objects we can remove these thin translation layers.
This PR also implements a few core utility functions required for translating between pylibcudf and libcudf objects, namely for:
- Generating pylibcudf Columns from libcudf column_views (instead of owning `column`s)
- Creating libcudf mutable_column_view objects from pylibcudf.Columns
- Producing cudf DeviceScalar objects from pylibcudf Scalars.
=> Implement remaining copying APIs in pylibcudf along with required helper functions

python/cudf/cudf/core/dataframe.py
This PR preserves original column ordering in `DataFrame.stack`
```
= 328 failed, 101111 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1113.40s (0:18:33) =
```
This PR:
```
= 316 failed, 101123 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1123.65s (0:18:43) =
```
=> Preserve column ordering in `DataFrame.stack`

python/cudf/cudf/core/column/column.py
Implemented @wence- 's suggestion in https://github.com/rapidsai/cudf/pull/14636#discussion_r1427766142
=> Consolidate memoryview handling in as_column

dependencies.yaml
Our notebook tests will currently fail to run because CUDA 12.1 is now available on conda-forge. We need to constrain the testing environment (we already do this for non-notebook testing environments).
=> Constrain CUDA in notebook testing to prevent CUDA 12.1 usage until we have pynvjitlink

python/cudf/cudf/tests/test_array_ufunc.py, python/cudf/cudf/tests/test_dataframe.py
This PR ignores ufunc runtime warnings that show up in `eval` API and setitem deprecation warnings.
```
= 260 failed, 101179 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1104.58s (0:18:24) =
```
This PR:
```
= 211 failed, 101228 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1095.49s (0:18:15) =
```
=> Filter ufunc related warnings in pytests

python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_csv.py, python/cudf/cudf/tests/test_indexing.py
This PR deprecates positional access in `Series.__getitem__` when a label-based index is present.
xref: https://github.com/pandas-dev/pandas/pull/53201
```
= 260 failed, 101179 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1104.58s (0:18:24) =
```
This PR:
```
= 248 failed, 101190 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1105.78s (0:18:25) =
```
=> Deprecate positional access for label based indexes in `Series.__getitem__`

cpp/tests/copying/get_value_tests.cpp, cpp/tests/copying/segmented_gather_list_tests.cpp, cpp/tests/copying/split_tests.cpp, cpp/tests/utilities/column_utilities.cu
This PR removes an extra code path used for checking the equality of the null count when verifying if columns are equivalent (not equal). The purpose of this code path was to verify a specific definition of equivalence for columns containing unsanitized nulls, i.e. by ignoring the stored null count and directly verifying the validity of the underlying null mask. This is no longer necessary because we required sanitized null masks to be output from all libcudf APIs now (see the "libcudf expects nested types to have sanitized null masks" section in the [developer guide](https://docs.rapids.ai/api/libcudf/stable/developer_guide)), and this requirement will be enforced with the merge of #14559.
=> Simplify null count checking in column equality comparator

cpp/cmake/thirdparty/get_cccl.cmake
Previously we searched for the rapids-cmake version of CCCL first which isn't desired as it doesn't have the patches CUDF ( and consumers ) require.
=> Ensure libcudf searches for our patched version of CCCL first

cpp/cmake/thirdparty/get_cccl.cmake, fetch_rapids.cmake
We need to unconditionally export the CCCL path because the condition can no longer be evaluated since the export is happening before the call to `rapids_cpm_cccl` as of #14655. Since cudf should in practice always be getting its own local copy of CCCL, it should be safe to have this export unconditionally; we will never use an externally provided copy of CCCL.
=> Unconditionally export the CCCL path

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_interpolate.py
This PR:
```
```
This PR:
```
= 187 failed, 101252 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1090.48s (0:18:10) =
```
=> Deprecate `method` in `interpolate` and calculation on `object` dtype

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_multiindex.py
This PR adds validation to `name` inputs in `MultiIndex.to_frame` API.
```
```
This PR:
```
= 180 failed, 101247 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1025.07s (0:17:05) =
```
=> Add more validation to `MultiIndex.to_frame`

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/join/_join_helpers.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/core/reshape.py, python/cudf/cudf/core/series.py, python/cudf/cudf/io/parquet.py, python/cudf/cudf/tests/test_concat.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_index.py
This PR deprecates ignoring `empty` objects for dtype calculation in `concat`.
```
```
This PR:
```
= 179 failed, 101260 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1225.23s (0:20:25) =
```
=> Deprecate ignoring empty objects in `concat`

python/cudf/cudf/core/index.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_indexing.py, python/cudf/cudf/tests/test_setitem.py
This PR deprecates the setting of a value that is not of same dtype as that of a column.
```
```
This PR:
```
= 176 failed, 101263 passed, 2091 skipped, 954 xfailed, 312 xpassed in 1096.08s (0:18:16) =
```
=> Deprecate setting of incompatible dtypes to an existing column

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/tests/test_datetime.py, python/cudf/cudf/tests/test_joining.py, python/cudf/cudf/tests/test_orc.py, python/cudf/cudf/tests/test_parquet.py
This PR fixes all `datetime` related pytests by properly handling their assertions with bug-fixes made in pandas-2.x and filtering newly introduced warnings where not necessary to propagate to the end-user.
```
```
This PR:
```
= 161 failed, 101280 passed, 2091 skipped, 952 xfailed, 312 xpassed in 1106.29s (0:18:26) =
```
=> Fix `datetime` related assertions and warnings in pytests

python/cudf/cudf/tests/test_stats.py
This PR fixes calculation of `cond` variable in `test_corr1d` which will include more cases for warnings. This change fixes, 9 pytest failures.
=> Fix pytest condition to include more warning scenarios

python/cudf/cudf/core/_base_index.py
This PR sorts results in `Index.difference` & `union` in the early exit scenarios similar to: https://github.com/pandas-dev/pandas/pull/51346/
```
= 110 failed, 101331 passed, 2091 skipped, 952 xfailed, 312 xpassed in 1064.30s (0:17:44) =
```
This PR:
```
= 87 failed, 101354 passed, 2091 skipped, 952 xfailed, 312 xpassed in 1004.34s (0:16:44) =
```
=> Sort `Index.difference` & `union` results for early exit scenarios

python/cudf/cudf/tests/test_index.py
This PR adds warning assertions that were missed in https://github.com/rapidsai/cudf/pull/14672
```
= 110 failed, 101331 passed, 2091 skipped, 952 xfailed, 312 xpassed in 1064.30s (0:17:44) =
```
This PR:
```
= 105 failed, 101336 passed, 2091 skipped, 952 xfailed, 312 xpassed in 1068.90s (0:17:48) =
```
=> Handle missing warning assertions for `concat` pytests

python/cudf/cudf/tests/test_dataframe.py
This PR fixes a typo in `isinstance` check, thus fixing 6 pytest failures.
=> Fix a typo error in `where` pytest

.pre-commit-config.yaml, dependencies.yaml
This PR updates `dependencies.yaml` so that generic CUDA 12.* dependencies can be specified with a glob, like `cuda: "12.*"`. This feature requires `rapids-dependency-file-generator>=1.8.0`, so the pre-commit hook has been updated.
I have not yet added support for a specific CUDA version like 12.1 or 12.2. That can be done separately.
=> Update dependencies.yaml to support CUDA 12.*.

CONTRIBUTING.md, README.md, cpp/src/io/comp/nvcomp_adapter.cpp, cpp/tests/io/comp/decomp_test.cpp, python/cudf/cudf/utils/gpu_utils.py, python/custreamz/README.md
=> Drop Pascal GPU support.

cpp/include/cudf/io/detail/orc.hpp, cpp/include/cudf/io/orc.hpp, cpp/src/io/functions.cpp, cpp/src/io/orc/reader_impl.cu, cpp/src/io/orc/reader_impl.hpp, cpp/src/io/orc/writer_impl.cu, cpp/src/io/orc/writer_impl.hpp
This PR simply changes the (sub) namespace `io::detail::orc` namespace into `io::orc::detail`. From now, the implementation of ORC reader and writer will be part of the `detail` namespace under the `io::orc` namespace.
=> Change `io::detail::orc` namespace into `io::orc::detail`

python/dask_cudf/dask_cudf/core.py, python/dask_cudf/dask_cudf/groupby.py, python/dask_cudf/dask_cudf/sorting.py, python/dask_cudf/dask_cudf/tests/test_core.py, python/dask_cudf/dask_cudf/tests/test_distributed.py, python/dask_cudf/dask_cudf/tests/test_groupby.py, python/dask_cudf/dask_cudf/tests/test_sort.py
https://github.com/dask/dask/pull/10738 has deprecated the `shuffle` kwarg in favor of `shuffle_method` which now raises a `FutureWarning`. This change transitions to the new kwarg.
=> Update to Dask's `shuffle_method` kwarg

pyproject.toml, python/cudf/cudf_pandas_tests/test_cudf_pandas.py
Nightly jobs have been [failing](https://github.com/rapidsai/cudf/actions/runs/7382855293/job/20083184931) with a numba segfault.
This appears to be a longstanding issue with numba on aarch64 fixed by https://github.com/numba/llvmlite/pull/1009. Technically, the issue exists already in our tests, but it appears that changes from numba 0.58 make the conditions for the issue to occur much more likely, hence the failures occurring after removing the numba 0.58 version constraint recently. The issue should be fixed in numba 0.59.
For now however we should skip things so that nightlies can be fixed.
=> Skip numba test that fails on ARM

cpp/src/io/parquet/page_decode.cuh
=> Potential fix for peformance regression in #14415

cpp/src/strings/filling/fill.cu
Refactors the `cudf::strings::detail::fill()` function to use `make_strings_children`. 
This refactors some duplicated logic and will help to enable large strings support.
=> Use make_strings_children for fill() specialization logic

cpp/src/strings/search/find.cu, cpp/tests/strings/find_tests.cpp
Fixes bug in `cudf::strings::contains` where the target matches the end of the string. This only occurred in the long strings special kernel logic for contains.
Also added additional gtests for long and short strings and for related functions find/rfind.
Closes #14710
=> Fix strings::contains matching end of string target

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml, python/cudf/cudf/testing/dataset_generator.py, python/cudf/cudf/tests/test_parquet.py, python/cudf/pyproject.toml
Looks like this is used to generate random ages/cities/countries. As generically cudf should work with arbitrary ints/strings, I don't think it's critical that the test data has real world meaning
=> Remove mimesis as a testing dependency

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/decimal.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/core/column/timedelta.py, python/cudf/cudf/tests/test_timedelta.py
Aligns the definitions of `Columns.fillna` among all subclasses. `dtype` looks to only needed in certain instances to cast the fill value so can do that separately. A `fill_nan` can be avoided with its single usage in a `can_cast` routine by checking for nan first
=> Ensure column.fillna signatures are consistent

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_categorical.py, python/cudf/cudf/tests/test_orc.py, python/cudf/cudf/utils/dtypes.py
* `valid_count` can be composed of `null_count` or where checked `has_nulls`
* `contains_na_entries` is redundant with `has_nulls`
* Better typing in `searchsorted`
=> Remove unneeded methods in Column

python/cudf/cudf/core/_internals/where.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/testing/testing.py
Just promotes more explicitness when using dtype checking functions
=> Explicitly pass .dtype into is_foo_dtype functions

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_series.py
Similar to https://github.com/rapidsai/cudf/pull/14687, nan was not being interpreted as null when `nan_as_null=True`
=> Fix nan_as_null not being respected when passing arrow object

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_series.py
Previously, passing a `dtype=` argument to the constructors was ignored when passing arrow array objects
=> Fix constructing Series/Index from arrow array and dtype

python/cudf/cudf/core/column/categorical.py
The removal of `valid_count` on columns in #14730 had one logic bug, fixed here.
=> Fix logic bug introduced in #14730

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml, python/cudf/pyproject.toml
Appears in the pytest-cases 3.8.2, there's a requirement that automatically finding `cases` must be in a file named `test_*`, when historically looks like we use `bench_*` 
https://github.com/smarie/python-pytest-cases/pull/320/files
=> Pin pytest-cases<3.8.2

python/dask_cudf/dask_cudf/core.py, python/dask_cudf/dask_cudf/groupby.py, python/dask_cudf/dask_cudf/sorting.py, python/dask_cudf/dask_cudf/tests/test_groupby.py
It seems that https://github.com/rapidsai/cudf/pull/14708 was a bit too aggressive in updating the `shuffle` kwarg to `shuffle_method`, and [gpu-CI is currently failing](https://github.com/dask/dask/issues/10809) in dask/dask.
This PR aligns dask-cudf with `dask.dataframe` by warning the user when the `shuffle` argument is used (rather than raising an error). I definitely don't think it makes sense for RAPIDS to be **more** strict than dask/dask about this argument.
This also fixes a bug in `groupby.aggregate()` (where we were still using `shuffle=`)
=> Revise ``shuffle`` deprecation to align with dask/dask

python/cudf/cudf/core/udf/utils.py, python/cudf/cudf/utils/_numba.py, python/cudf/udf_cpp/CMakeLists.txt
The behavior of editable installs changed when we transitioned to scikit-build-core, and it affects where the ptx files created during the build can be discovered. Editable installs no longer place built files directly alongside source files. Instead, Python's import machinery is leveraged to add built files to the search path. Since ptx files are not Python files, the loader logic isn't relevant, but we now need to ensure that we always search for the ptx files alongside built artifacts (namely Cython compiled modules) rather than Python source files. I'm guessing that nobody has encountered this yet due to preexisting build artifacts in their source directories.
=> Fix ptx file discovery in editable installs

docs/cudf/source/conf.py
In my initial pass through enabling Breathe I tried to leave a minimal footprint of external modification to the generated files. In this particular case it looks like the problematic attributes can appear in more places than I originally observed. I never observed this behavior in that PR, but I don't know if these now appear due to something that merged after #13846 or something else changing in the environment (e.g. a Sphinx or doxygen behavior etc). Nonetheless, blanket wiping these is the simpler and safer option. The docs build successfully locally with this change.
=> Remove unparseable attributes from all nodes

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-120_arch-x86_64.yaml, dependencies.yaml, python/cudf/benchmarks/API/bench_dataframe.py, python/cudf/benchmarks/API/bench_functions.py, python/cudf/benchmarks/API/cases_dataframe.py, python/cudf/benchmarks/API/cases_functions.py, python/cudf/pyproject.toml
Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> Forward-merge branch-24.02 to branch-24.04

python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_datetime.py
Additionally adds some typing and remove validation done by `cudf.dtype` and add a unit test to ensure numpy dtype objects are accepted in the constructor
=> Clean up `DatetimeIndex.__init__` constructor

ci/build_docs.sh
A new release of `pydata_sphinx_theme` [from last night](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.15.2) includes https://github.com/pydata/pydata-sphinx-theme/pull/1642, which marks the theme as unsafe for parallel writing.
=> Disable parallel build

python/cudf/cudf/core/index.py
Aligns the constructor closer to `DatetimeIndex.__init__`: https://github.com/rapidsai/cudf/pull/14774
=> Clean up `TimedeltaIndex.__init__` constructor

.github/workflows/pr.yaml
Fix the repo name for `shared-workflows`
=> Fix shared-workflows repo name

conda/recipes/libcudf/build.sh
The `-DNVBench_ENABLE_CUPTI=OFF` flag is no longer needed because of https://github.com/rapidsai/rapids-cmake/pull/504. NVBench CUPTI support is now disabled by default.
=> Remove -DNVBench_ENABLE_CUPTI=OFF.

ci/release/update-version.sh, dependencies.yaml
Fix `update-version.sh` to include pip `cu` suffixed dependencies
=> Fix 24.04 versions

python/cudf/cudf/_lib/parquet.pyx
This PR preserves types of empty column index objects whose metadata is already present in the parquet file.
This PR:
```
= 107 failed, 101869 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1265.57s (0:21:05) =
```
```
= 111 failed, 101865 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1292.26s (0:21:32) =
```
=> Preserve empty index types in parquet reader

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
This PR documents the libcudf preference for "east const." Follow-up from #13491, #13492, #13493, #13494.
=> Add developer guideline to use east const.

cpp/CMakeLists.txt, cpp/cmake/Modules/JitifyPreprocessKernels.cmake, cpp/tests/CMakeLists.txt
This PR uses rapids-cmake to handle per-target CMake linking to cudart.
Replaces #13543 and #11641.
=> Use `rapids_cuda_set_runtime` to determine cuda runtime usage by target

cpp/examples/strings/custom_optimized.cu
Follow-up PR to #14771.
I noticed the strings example code still had a deprecated function call:
```
-- Build files have been written to: /opt/conda/conda-bld/work/cpp/examples/strings/build
[1/8] Building CXX object CMakeFiles/libcudf_apis.dir/libcudf_apis.cpp.o
[2/8] Linking CXX executable libcudf_apis
[3/8] Building CUDA object CMakeFiles/custom_prealloc.dir/custom_prealloc.cu.o
[4/8] Building CUDA object CMakeFiles/custom_with_malloc.dir/custom_with_malloc.cu.o
[5/8] Linking CUDA executable custom_prealloc
[6/8] Linking CUDA executable custom_with_malloc
[7/8] Building CUDA object CMakeFiles/custom_optimized.dir/custom_optimized.cu.o
/opt/conda/conda-bld/work/cpp/examples/strings/custom_optimized.cu: In function 'std::unique_ptr<cudf::column> redact_strings(const cudf::column_view&, …
```
=> Fix calls to deprecated strings factory API in examples.

cpp/include/cudf_test/stream_checking_resource_adaptor.hpp, java/src/main/native/src/RmmJni.cpp
Part of rapidsai/rmm#1388. This removes now-optional and soon-to-be deprecated functions from cuDF's custom device_memory_resource implementations:
* `supports_get_mem_info()`
* `do_get_mem_info()`
=> Remove get_mem_info functions from custom memory resources

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
This PR fixes `DataFrame.agg` API where the actual dataframe was being casted to incorrect dtype (object dtype) and then the operations were being performed. This PR adds strict checks at two places.
This PR:
```
= 95 failed, 101829 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1479.83s (0:24:39) =
```
```
= 111 failed, 101865 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1265.57s (0:21:05) =
```
=> Fix `Dataframe.agg` to not return incorrect dtypes

python/cudf/cudf/tests/test_reductions.py
This PR validates the warnings generated by certain reduction ops.
=> Catch warnings in reduction pytest

python/cudf/cudf/tests/test_groupby.py
This PR catches `RuntimeWarning`'s in jit groupby pytests.
This PR:
```
= 61 failed, 101866 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1446.19s (0:24:06) =
```
```
= 91 failed, 101836 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1348.36s (0:22:28) =
```
=> Catch groupby jit apply warnings

python/cudf/cudf/tests/test_stats.py
This PR fixes all the remaining one-off reduction pytest failures.
This PR: 
```
= 54 failed, 101872 passed, 2091 skipped, 977 xfailed, 312 xpassed in 1432.99s (0:23:52) =
```
```
= 61 failed, 101866 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1446.19s (0:24:06) =
```
=> Fix all reduction pytest failures

.github/workflows/pr.yaml, .github/workflows/test.yaml, ci/release/update-version.sh, docs/dask_cudf/source/conf.py
Fixes some merge issues with outdated versions from #14768. I also made a minor tweak to `update-version.sh` that double-quotes some outputs to make pre-commit happier.
=> Update conda-cpp-post-build-checks to branch-24.04.

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
Closes https://github.com/rapidsai/cudf/issues/14862
This PR fixes the errors in https://github.com/rapidsai/cudf/issues/14862 by ensuring we match the pandas return type when doing grouped count, size, idxmax, idxmin.
=> Fix empty groupby return types

python/cudf/cudf/core/dataframe.py
closes #14866
@galipremsagar it appears the linked failing test in the issue `test_reductions_axis_none_warning` expected `FutureWarning` from these calls. Should they be expected for kurt/skew too?
=> Support kurt/skew(axis=None) for multi columns/low row count

python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_joining.py, python/cudf/cudf/tests/test_series.py, python/dask_cudf/dask_cudf/backends.py
This PR fixes miscellaneous corner cases in pytests
This PR:
```
= 27 failed, 101895 passed, 2091 skipped, 979 xfailed, 312 xpassed in 1360.28s (0:22:40) =
```
```
= 52 failed, 101872 passed, 2091 skipped, 977 xfailed, 312 xpassed in 1188.72s (0:19:48) =
```
=> Fix miscellaneous failures in pytests

python/cudf/cudf/_lib/cpp/types.pxd, python/cudf/cudf/_lib/lists.pyx, python/cudf/cudf/_lib/stream_compaction.pyx
This change is a necessary prerequisite for adding other APIs to pylibcudf that need these types.
=> Move all core types to using enum class in Cython

python/cudf/cudf/core/dataframe.py
This PR preserves `columns` dtype in `DataFrame` constructor.
This PR:
```
= 52 failed, 101872 passed, 2091 skipped, 977 xfailed, 312 xpassed in 1188.72s (0:19:48) =
```
```
= 61 failed, 101866 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1446.19s (0:24:06) =
```
=> Preserve columns `dtype` in dataframe constructor

cpp/src/io/parquet/reader_impl_chunking.cu
Fixes  https://github.com/rapidsai/cudf/issues/14883
The core issue was that the output chunking code was expecting all columns to have terminating pages that end in the same row count.  Previously this was the case because we always processed entire row groups.  But now with the subrowgroup reader, we can split on page boundaries that cause a jagged max row index for different columns.  Example:
```
0       100             200
Col A     [-----------][--------------]      300
Col B     [-----------][----------------------]
```
The input chunking would have computed a max row index of 200 for the subpass.  But when computing the _output_ chunks, there was code that would have tried finding where row 300 was in column A, resulting in an out-of-bounds read.
The fix is simply to cap the max …
=> Fixed an issue with output chunking computation stemming from input chunking.

python/cudf/cudf/tests/test_array_function.py, python/cudf/cudf/tests/test_array_ufunc.py, python/cudf/cudf/tests/test_parquet.py
* `np.product` call I think will be redundant with the existing params, `np.var` call adjusted to what was tested before
* `matmul` failure existed upstream in pandas
* Snuck in a clean up files leftover by a parquet test (found these leftover when running the test suite locally)
=> Fix some pytests

python/cudf/cudf/_lib/utils.pyx
This PR enables writing of non-string columns in parquet writer only in pandas-compatibility mode.
This PR:
```
= 8 failed, 102249 passed, 2090 skipped, 976 xfailed, 312 xpassed in 1363.59s (0:22:43) =
```
```
= 9 failed, 102247 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1336.47s (0:22:16) =
```
=> Parquet Writer: Write `non-string` columns pandas-compatibility mode only

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_replace.py
This PR:
This PR:
```
= 8 failed, 102249 passed, 2090 skipped, 976 xfailed, 312 xpassed in 1359.84s (0:22:39) =
```
```
= 9 failed, 102247 passed, 2091 skipped, 976 xfailed, 312 xpassed in 1336.47s (0:22:16) =
```
=> Deprecate `method` in `replace` and warn for a specific combination of `value` and `to_replace`

python/cudf/cudf/core/indexed_frame.py
[The last commit](https://github.com/rapidsai/cudf/pull/14900/commits/b61b39d0ebd33113d4070ceae24adf8c58a46ddf) on #14900 introduced an invalid usage of set membership checks where the values could be dictionaries (which are not hashable and therefore cannot be searched in sets). This PR reverts that change.
=> Fix incorrect set usage

python/dask_cudf/dask_cudf/io/tests/test_csv.py, python/dask_cudf/dask_cudf/io/tests/test_json.py, python/dask_cudf/dask_cudf/io/tests/test_parquet.py, python/dask_cudf/dask_cudf/tests/test_accessor.py, python/dask_cudf/dask_cudf/tests/test_core.py, python/dask_cudf/dask_cudf/tests/test_groupby.py, python/dask_cudf/dask_cudf/tests/test_reductions.py
`dask` is natively converting all `object` types to `arrow[string]` types if proper pyarrow dependency is detected. This is being done in `assert_eq` API. We will need a change in `cudf` and `dask` upstream to be able to support this kind of conversion. I'm coming up with a solution in `24.04` dev cycle, but in the interest of shipping pandas-2.x I'm feeling confident to disable this auto-conversion by setting the `dataframe.convert-string` dask config to `False` where necessary.
=> Prevent converting strings to arrow strings in `dask_cudf` pytests

cpp/tests/CMakeLists.txt, cpp/tests/table/row_operator_tests_utilities.cu, cpp/tests/table/row_operator_tests_utilities.hpp, cpp/tests/table/row_operator_tests_utilities2.cu
Splitting up `row_operator_tests_utilities.cu` works around a nvcc segfault when building with Debug.
The segfault is found to occur on at least 11.8 and 12.0. 
```
Building CUDA object tests/CMakeFiles/TABLE_TEST.dir/table/row_operator_tests_utilities.cu.o
FAILED: tests/CMakeFiles/TABLE_TEST.dir/table/row_operator_tests_utilities.cu.o 
/usr/local/bin/nvcc -forward-unknown-to-host-compiler -DFMT_HEADER_ONLY=1 -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DSPDLOG_FMT_EXTERNAL -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -I/cudf/cpp -I/cudf/cpp/src -I/cudf/cpp/build/_deps/dlpack-src/include -I/cudf/cpp/build/_deps/jitify-src -I/cudf/cpp/include -I/cudf/cpp/build/include …
```
=> Fix debug build by splitting row_operator_tests_utilities.cu

python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_timedelta.py
This removes xpassing tests from the test output.
=> Remove strict=False from xfail marks

cpp/include/cudf/detail/aggregation/aggregation.hpp, cpp/tests/groupby/sum_tests.cpp
This pull request reverses the modifications made to the sum/product aggregation target type, ensuring it always produces int64. The changes implemented by  PR [14679](https://github.com/rapidsai/cudf/pull/14679) which led to degraded performance when the aggregation column had an unsigned type, are reverted. Additional details can be found in the issue [14886](https://github.com/rapidsai/cudf/issues/14886).
=> Revert sum/product aggregation to always produce `int64_t` type

cpp/src/strings/copying/copying.cu
Replace hardcoded offset types with offsetalator in `cudf::strings::detail::copy_slice`.
=> Use offsetalator in cudf::strings::copy_slice

python/custreamz/custreamz/tests/test_dataframes.py
This PR passes types to empty dataframe construction because reductions were being performed on `float64` types and now empty column default type is `object`.
=> Fix `custreamz` pytests to test on `float64` types

python/cudf/cudf/core/_compat.py, python/cudf/cudf/tests/test_concat.py, python/cudf/cudf/tests/test_csv.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_datetime.py, python/cudf/cudf/tests/test_groupby.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_replace.py, python/cudf/cudf/tests/test_series.py
Removes pandas 1.3, 1.4 checks in unit tests
=> Remove pandas 1.3, 1.4 checks

python/custreamz/custreamz/tests/test_dataframes.py
This PR passes types to empty dataframe construction because reductions were being performed on float64 types and now empty column default type is object.
=> Fix custreamz pytests to test on float64 types

python/cudf/cudf/api/extensions/accessor.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/datasets.py, python/cudf/cudf/tests/test_concat.py, python/cudf/cudf/tests/test_custom_accessor.py, python/cudf/cudf/tests/test_datasets.py, python/dask_cudf/dask_cudf/sorting.py, python/dask_cudf/dask_cudf/tests/test_accessor.py, python/dask_cudf/dask_cudf/tests/test_core.py, python/dask_cudf/dask_cudf/tests/test_delayed_io.py, python/dask_cudf/dask_cudf/tests/test_join.py, python/dask_cudf/dask_cudf/tests/test_reductions.py
Discussed offline, replacing this legacy import style without aliasing
=> Replace legacy cudf and dask_cudf imports as (d)gd

docs/cudf/source/cudf_pandas/benchmarks.md, docs/cudf/source/cudf_pandas/faq.md
This PR updates the cudf.pandas docs to reflect cudf using pandas 2.
=> Update cudf.pandas FAQ.

codecov.yml
This PR makes the codecov status always pass ✔️ so that it doesn't distract from actual CI failures in the commit CI summary.
https://docs.codecov.com/docs/commit-status#informational
cc: @davidwendt @mroeschke
=> Make codecov only informational (always pass).

docs/cudf/source/user_guide/api_docs/pylibcudf/aggregation.rst, docs/cudf/source/user_guide/api_docs/pylibcudf/groupby.rst, docs/cudf/source/user_guide/api_docs/pylibcudf/index.rst, python/cudf/cudf/_lib/aggregation.pyx, python/cudf/cudf/_lib/cpp/CMakeLists.txt, python/cudf/cudf/_lib/cpp/aggregation.pxd, python/cudf/cudf/_lib/cpp/groupby.pxd, python/cudf/cudf/_lib/cpp/replace.pxd, python/cudf/cudf/_lib/pylibcudf/CMakeLists.txt, python/cudf/cudf/_lib/pylibcudf/__init__.pxd, python/cudf/cudf/_lib/pylibcudf/__init__.py, python/cudf/cudf/_lib/pylibcudf/aggregation.pxd, python/cudf/cudf/_lib/pylibcudf/aggregation.pyx, python/cudf/cudf/_lib/pylibcudf/copying.pyx, python/cudf/cudf/_lib/pylibcudf/groupby.pxd, python/cudf/cudf/_lib/pylibcudf/groupby.pyx, python/cudf/cudf/_lib/pylibcudf/types.pxd, python/cudf/cudf/_lib/pylibcudf/types.pyx, python/cudf/cudf/_lib/pylibcudf/utils.pxd, python/cudf/cudf/_lib/pylibcudf/utils.pyx
This PR implements groupby in pylibcudf along with the minimal set of aggregation logic to support groupby. To limit its scope, this PR does not include other aggregation logic for e.g. non-groupby reductions and scans. Due to the large scale of what's already in this PR, I have also omitted the changes required to leverage pylibcudf in the current cudf Cython code from this PR. That will be done in a follow-up. This PR's diff is misleadingly large, a large chunk of it is adding documentation and function declarations that shouldn't impose too heavy a cognitive load in review.
=> Implement groupby in pylibcudf

cpp/include/cudf/column/column_factories.hpp, cpp/include/cudf/strings/strings_column_view.hpp, cpp/src/strings/strings_column_factories.cu, cpp/src/strings/strings_column_view.cpp
Removes the functions deprecated in 24.02 in #14202.
=> Remove deprecated strings functions

python/cudf/cudf/tests/test_spilling.py
This PR updates spilling tests to limit the scope of all environment and cudf option modifications to the scope of the test to avoid interfering with other tests. This PR also temporary skips a test that is not currently safe to run in an environment where other tests may already have modified related global state (the rmm default memory resource).
=> unset `CUDF_SPILL` after a pytest

cpp/include/cudf_test/column_wrapper.hpp
Replace struct_column_wrapper with structs_column_wrapper in example given in documentation of `structs_column_wrapper`
=> [DOC] Update typo in docs example of structs_column_wrapper

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/dtypes.py, python/dask_cudf/dask_cudf/backends.py
This is more explicit than the methods which may allow array objects where we don't want to
=> Replace _is_datetime64tz/interval_dtype with isinstance

python/cudf/cudf/_lib/aggregation.pxd, python/cudf/cudf/_lib/aggregation.pyx, python/cudf/cudf/_lib/groupby.pyx, python/cudf/cudf/_lib/pylibcudf/aggregation.pyx, python/cudf/cudf/_lib/pylibcudf/groupby.pxd, python/cudf/cudf/_lib/pylibcudf/groupby.pyx
This PR builds on #14945 to use pylibcudf's groupby in cudf's internals. It should not be merged until after that PR.
=> Rewrite cudf internals using pylibcudf groupby

docs/cudf/source/developer_guide/pylibcudf.md, python/cudf/cudf/_lib/copying.pyx, python/cudf/cudf/_lib/pylibcudf/binaryop.pxd, python/cudf/cudf/_lib/pylibcudf/binaryop.pyx, python/cudf/cudf/_lib/pylibcudf/copying.pxd, python/cudf/cudf/_lib/pylibcudf/copying.pyx
This change makes the pylibcudf API more convenient and a more faithful reproduction of the underlying libcudf APIs that offer overloaded signatures. In cases like binary ops where we were previously using runtime instance checks, this change also removes unnecessary runtime overhead if the calling code is Cython since in those cases the types at the call site are known at compile time.
=> Use fused types for overloaded function signatures

ci/check_style.sh, cpp/examples/fetch_dependencies.cmake, cpp/libcudf_kafka/CMakeLists.txt, fetch_rapids.cmake, java/src/main/native/CMakeLists.txt, python/cudf/CMakeLists.txt, python/cudf_kafka/CMakeLists.txt
`branch-24.04` was opened without updating the copyrights on a few files. This fixes those missing copyright updates, which keep getting updated by our pre-commit hooks for me locally.
=> Update copyrights for 24.04.

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/groupby/test_agg.py
Closes https://github.com/rapidsai/cudf/issues/14957
Calling `SeriesGroupBy.aggregate` is currently directed to `GroupBy.agg` instead of `SeriesGroupBy.agg`. This means that `SeriesGroupBy.aggregate` currently produces a `DataFrame` in many cases that it *should* produce a `Series`. This PR corrects the underlying problem.
=> Direct ``SeriesGroupBy.aggregate`` to ``SeriesGroupBy.agg``

python/cudf/cudf/core/index.py, python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/tests/indexes/test_interval.py
This PR deprecates non-integer `periods` in `date_range` and `interval_range` to match pandas-2.2 deprecations.
=> Deprecate non-integer `periods` in `date_range` and `interval_range`

docs/cudf/source/user_guide/api_docs/pylibcudf/index.rst, docs/cudf/source/user_guide/api_docs/pylibcudf/join.rst, python/cudf/cudf/_lib/cpp/join.pxd, python/cudf/cudf/_lib/join.pyx, python/cudf/cudf/_lib/pylibcudf/CMakeLists.txt, python/cudf/cudf/_lib/pylibcudf/__init__.pxd, python/cudf/cudf/_lib/pylibcudf/__init__.py, python/cudf/cudf/_lib/pylibcudf/groupby.pyx, python/cudf/cudf/_lib/pylibcudf/join.pxd, python/cudf/cudf/_lib/pylibcudf/join.pyx
=> Implement joins in pylibcudf

cpp/src/io/orc/writer_impl.cu, cpp/tests/io/orc_test.cpp
Closes #14932
ORC writer uses uncompressed stream sizes when allocating the bounce buffer. This can lead to issues when all uncompressed streams are larger than the GDS threshold, but compressed size is not. In this scenario, the bounce buffer is not allocated, and writing the compressed stream through the bounce buffer causes a crash.
This PR moves the computation of the bounce buffer size until after compression, so it works with correct stream sizes.
=> Fix the bounce buffer size in ORC writer

python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/tests/test_dataframe.py
This PR fixes `DataFrame.sort_index` to properly ignore indexes for all values of `axis`. This is fixed in pandas-2.2, hence xfailing the tests with a version check.
=> Fix `DataFrame.sort_index` to respect `ignore_index` on all axis

python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
Deprecated in pandas 2.2 https://github.com/pandas-dev/pandas/pull/55719
=> Deprecate groupby fillna

python/cudf/cudf/_fuzz_testing/utils.py, python/cudf/cudf/io/hdf.py, python/cudf/cudf/tests/test_hdf.py
This only really affected `to_hdf`
=> Ensure to_* IO methods respect pandas 2.2 keyword only deprecation

python/cudf/cudf/core/index.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/core/tools/numeric.py, python/cudf/cudf/tests/test_datetime.py, python/cudf/cudf/tests/test_numerical.py
For comparison:
https://github.com/pandas-dev/pandas/pull/55856
https://github.com/pandas-dev/pandas/pull/55895
https://github.com/pandas-dev/pandas/issues/55499
The `errors="ignore"` parameter is the only one that is implemented so just added a test for that deprecation
=> Deprecate parameters similar to pandas 2.2

python/cudf/cudf/_lib/groupby.pyx, python/cudf/cudf/_lib/pylibcudf/groupby.pxd, python/cudf/cudf/_lib/pylibcudf/groupby.pyx, python/cudf/cudf/core/groupby/groupby.py, python/cudf/cudf/tests/test_groupby.py
A small bug in our previous implementation leads to a segfault when calling `.get_groups()` with no `values`. Thankfully, the cuDF Python API always calls this function with a value, but it's possible `pylibcudf` consumers will not.
=> Fix handling of values=None in pylibcudf GroupBy.get_groups

cpp/include/cudf/detail/sequence.hpp
A small fix avoiding the detail sequence header including itself.
=> Clean up detail sequence header inclusion

python/cudf/cudf/core/column/column.py, python/cudf/cudf/tests/test_datetime.py
Similar to the where pandas inputs that are tz-aware raise a `NotImplementedError`
=> Raise for pyarrow array that is tz-aware

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/tests/test_replace.py
Matches pandas 2.2 behavior: https://github.com/pandas-dev/pandas/pull/56385
=> Deprecate replace with categorical columns

python/cudf/cudf/tests/test_api_types.py
Fixed in pandas 2.2: https://github.com/pandas-dev/pandas/issues/54661
=> Fix is_string_dtype test for pandas 2.2

cpp/src/strings/reverse.cu
Updates `cudf::strings::reverse` to use the offsetalator instead of hardcoded int32 type for offsets column data.
=> Use offsetalator in cudf::strings::reverse

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/reshape.py, python/cudf/cudf/tests/test_reshape.py
This PR introduces `future_stack` to `stack` API. This also means deprecating `dropna`.
=> Add `future_stack` to `DataFrame.stack`

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/tests/test_index.py
This PR removes duplicate values in two short-circuit code-paths of `Index.difference` which is already fixed in `pandas-2.2`
=> Fix `Index.difference` to handle duplicate values when one of the inputs is empty

java/src/main/java/ai/rapids/cudf/ColumnView.java, java/src/main/java/ai/rapids/cudf/GetJsonObjectOptions.java, java/src/main/native/src/ColumnViewJni.cpp, java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Resolves [10219](https://github.com/NVIDIA/spark-rapids/issues/10219)
This PR introduces a new class named `GetJsonObjectOptions` that holds the configurations to control the behavior of the underlying `cudf::get_json_object` function. It incorporates this new class into the `getJSONObject` JAVA API as an additional argument but also keeps the previous API to maintain backwards compatibility.  It also includes a test case, `testGetJSONObjectWithSingleQuotes`, validating the behavior of `getJSONObject` when single quotes are enabled.
=> Introduce `GetJsonObjectOptions` in `getJSONObject` Java API

conda/recipes/cudf/meta.yaml
I think unpinning `numba` in the conda recipe was just missed in #14616.
I discovered this issue [trying to build the `24.02` release](https://github.com/rapidsai/cudf/actions/runs/7878153691/job/21496377912#step:7:1674).
PRs & nightly builds are working because the `rapidsai-nightly` channel has an older version of `pynvjitlink` that supported `numba>=0.57` whereas the `rapidsai` channel only has the latest version which pins to `numba>=0.58`.
=> [HOTFIX] Unpin numba<0.58

cpp/include/cudf/detail/utilities/algorithm.cuh
Found while working on large strings where copy-if is called. In places where `copy_if_safe` utility is called the non-stencil overload calls the stencil-ed function by forwarding the `first` iterator as the `stencil` parameter. This works logically because both values will return the same result. Unfortunately, this can be a performance issue if the iterator is complex/slow transform iterator since it would be called twice (an inlined twice). Changing the non-stencil version to call `thrust::copy_if` directly fixes the potential issue.
=> Change copy_if_safe to call thrust instead of the overload function

python/cudf/cudf/io/csv.py, python/cudf/cudf/tests/test_csv.py
Toward pandas 2.2 compat: Deprecated in pandas in https://github.com/pandas-dev/pandas/pull/56557
=> Deprecate delim_whitespace in read_csv for pandas 2.2

cpp/src/reshape/interleave_columns.cu
Updates `cudf::interleave_columns()` to use the new `make_offsets_child_column` utility and the offsetalator to build the output strings column.
=> Use offsetalator in cudf::interleave_columns()

cpp/cmake/Modules/JitifyPreprocessKernels.cmake
Developers expect that 'cleaning' a build directory will remove all forms of cached files ( objects, libraries, jit cache, etc ). To ensure that happens consistenly we also need to remove the jitify cache objects for cudf.
=> Requesting a clean build directory also clears Jitify cache

python/cudf/cudf/tests/test_indexing.py
Chained indexing raises a `FutureWarning` in pandas 2.2. Since this test doesn't look to specifically test that, refactoring the test to avoid that
=> Avoid chained indexing in test_indexing for pandas 2.2

python/cudf/cudf/core/reshape.py, python/cudf/cudf/tests/test_concat.py
Fixed in pandas by https://github.com/pandas-dev/pandas/pull/56365
=> Align concat Series name behavior in pandas 2.2

python/cudf/cudf/tests/test_groupby.py
This case for some reason doesn't raise a FutureWarning in pandas in 2.2 while it does in pandas 2.1. It's likely a won't-fix so adding a condition
=> Add condition for test_groupby_nulls_basic in pandas 2.2

python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/tests/test_binops.py
2 tests needed to be adjusted due to pandas changes in behaviors in https://github.com/pandas-dev/pandas/issues/57447 and https://github.com/pandas-dev/pandas/issues/57448
=> Adjust test_binops for pandas 2.2

python/cudf/cudf/tests/test_joining.py
As described in https://pandas.pydata.org/docs/dev/whatsnew/v2.2.0.html#merge-and-dataframe-join-now-consistently-follow-documented-sort-behavior
=> Adjust test_joining for pandas 2.2

python/cudf/cudf/tests/test_resampling.py
I think this got unintentionally fixed in pandas 2.2, but `pandas.testing.assert_series_equal` will be strict about checking a Series's Index's dtype for date-likes. Since pandas always returns `ns` in resample and cudf tries to match the resolution frequency (IMO the better behavior), need to specify `check_index=False` in pandas 2.2
=> Fix test_resample index dtype checking for pandas 2.2

python/cudf/cudf/tests/test_applymap.py
There were regressions in the `map` methods on the pandas side that is causing some of these applymap tests to fail on pandas 2.2
=> Add xfailures for test_applymap for pandas 2.2

python/cudf/cudf/tests/test_datetime.py
pandas 2.2 is stricter about converting from date string to datetime type if the resolution would lead to loss of precision. This affects `test_datetime_infer_format` where an `astype` is done, so adjusting the test such that the `astypes` don't lead to loss of precision.
=> Adjust test_datetime_infer_format for pandas 2.2

python/cudf/cudf/core/tools/datetimes.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_series.py
Matching https://github.com/pandas-dev/pandas/pull/56427
=> Deprecate datelike isin casting strings to dates to match pandas 2.2

python/cudf/cudf/tests/test_setitem.py
`test_setitem_dataframe_series_inplace` failed with pandas 2.2 because it exhibits a chained indexing behavior that raised a `FutureWarning` in pandas 2.2 and will raise in 3.0. I refactored the test to test cudf copy on write to exhibit the 3.0 behavior, but it still seems to allow this chained indexing behavior, so xfailed it for now.
=> Change chained replace inplace test to COW test for pandas 2.2

cpp/src/copying/purge_nonempty_nulls.cu
Updates `cudf::detail::has_nonempty_null_rows` to use the offsetalator instead of hardcoded integer type.
=> Use offsetalator in cudf::detail::has_nonempty_null_rows

python/cudf/cudf/core/multiindex.py, python/cudf/cudf/tests/test_groupby.py
closes #15087
closes #11259
(The typing annotation is incorrect, but I guess there needs to be a check somewhere to make `_copy_type_metadata` stricter)
=> Fix Series.groupby.shift with a MultiIndex

python/cudf/cudf/utils/gpu_utils.py
RAPIDS 24.02 dropped support for Pascal GPUs. When using an unsupported GPU, the behavior of cudf is undefined and sometimes produces results that appear valid (and empty) but conceal CUDA kernel launch errors. This PR changes the behavior to error on import if unsupported GPUs are detected.
=> Raise an error on import for unsupported GPUs.

cpp/src/strings/extract/extract_all.cu, cpp/src/strings/search/findall.cu
Fixes `cudf::strings::extract_all()` to use `cudf::detail::make_offsets_child_column` so it properly computes the output-size and checks for overflow when building offsets for a lists column.
Also undo some changes from #14745 that incorrectly called `cudf::strings::detail::make_offsets_child_column` to create offsets for a lists column.
=> Use appropriate make_offsets_child_column for building lists columns

cpp/include/cudf/rolling/range_window_bounds.hpp
Fixes #15131.
The `const` on the `_extent` member of `range_window_bounds` is superfluous. It provides no additional protection to `range_window_bounds`'s invariants, and prevents the class from being copy assignable.
This change removes the `const`, thus making `range_window_bounds` copy-assignable, and more readily usable from Cython.
=> Remove `const` from `range_window_bounds::_extent`.

cpp/examples/strings/custom_prealloc.cu, cpp/src/transform/row_conversion.cu, cpp/tests/io/json_type_cast_test.cu
Removes calls to `cudf::strings_column_view::offsets_begin()` since the result cannot have a hardcoded integer type.
The goal is to deprecate this member function in this release. Follow on changes may be required to further enable large strings support to these functions.
=> Remove calls to strings_column_view::offsets_begin()

.github/ops-bot.yaml, cpp/include/cudf/fixed_point/fixed_point.hpp, cpp/include/cudf/round.hpp, cpp/tests/strings/fixed_point_tests.cpp
Compile-time ipow() computation with array lookup.  Results in up to 8% speed improvement for decimal64 -> double conversions.  Improvement is negligible for other conversions but is not worse.  New benchmark test will be in a separate PR.  Fix fixed_point -> string conversion test. Also fix rounding comments. Closes #9346
=> Compile-time ipow computation with array lookup

python/cudf/cudf/core/frame.py
There are  currently [CI failures](https://github.com/rapidsai/cudf/actions/runs/8089269486/job/22105880070?pr=15181#step:7:1050) that seem to be caused by non-deterministic `dict` normalization in `Frame.__dask_tokenize__`. This PR avoids normalizing that dictionary.
=> Avoid dict normalization in ``__dask_tokenize__``

python/cudf/cudf/_lib/pylibcudf/column.pyx
This PR enables creation of pylibcudf columns from scalar values.
=> Enable creation of columns from scalar

cpp/include/cudf_test/column_utilities.hpp, cpp/tests/utilities/column_utilities.cu
The `cudf::test::to_host` function is updated to handle int32 and int64 offset types for strings columns when copying data to host memory. This function is used with `cudf::test::print()` as well.
Also moved the function from the header `column_utilities.hpp` to the `column_utilities.cu` file.
And moved the specialization for of `to_host` for fixed-point types from the header to `.cu` as well.
=> Fix cudf::test::to_host to handle both offset types for strings columns

cpp/include/cudf/table/row_operators.cuh
Simple change removes the `cudf/sorting.hpp` include from `row_operators.cuh`.
Found this while waiting for recompiles to finish.
Changes to `sorting.hpp` seemed to cause more recompiling than expected. 
Also took the opportunity to change the `include <limits>` to `include <cuda/limits>`
=> Fix includes for row_operators.cuh

python/cudf/cudf/core/column/interval.py, python/cudf/cudf/core/column/lists.py, python/cudf/cudf/tests/test_series.py
I think there will be a mypy error on main soon as https://github.com/rapidsai/cudf/pull/15182 and https://github.com/rapidsai/cudf/pull/15155 were merge in close succession (my fault for not rebasing first)
Also address a review I forgot in https://github.com/rapidsai/cudf/pull/15182/files#r1507154770
cc @galipremsagar
=> Add ListColumns.to_pandas(arrow_type=)

java/src/test/java/ai/rapids/cudf/TableTest.java
This is a follow on from https://github.com/rapidsai/cudf/pull/15210. We bring back the test and fix it so it copies from the right buffer this time. I also set the original column to have some values and nulls, to make sure we are checking something interesting.
=> Fix testchunkedPackTwoPasses to copy from the bounce buffer

cpp/benchmarks/string/case.cpp, cpp/include/cudf/strings/strings_column_view.hpp, cpp/src/strings/strings_column_view.cpp
Changes the `cudf::strings_column_view::chars_size()` function to return `int64_t` instead of `size_type`
=> Change strings_column_view::char_size to return int64

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md, cpp/src/io/parquet/error.hpp
Follow up to #15063 to add new guidance for quoting includes of internal headers from `src` paths. Also covers clang-format include grouping. 
Also fixes a single include that was added with `<>` recently that should be `""`. #15063 updated all includes to match the guidance in this PR (changing a lot of `<>` to `""` for includes from `src/...`.
=> Update `developer_guide.md` with new guidance on quoted internal includes

python/cudf/cudf/utils/_numba.py
This PR updates the mapping from PTX version to toolkit versions to cover CUDA 12.4.
=> Add CUDA 12.4 to supported PTX versions

cpp/include/cudf/strings/detail/utilities.hpp, cpp/src/strings/utilities.cu
Removes the `cudf::strings::detail::create_chars_child_column` utility. This is not longer needed or used.
Removing it helps prevent inadvertently using it to wrap chars data with a cudf column.
=> Remove create_chars_child_column utility

java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java, java/src/main/java/ai/rapids/cudf/Rmm.java, java/src/main/native/src/RmmJni.cpp, java/src/test/java/ai/rapids/cudf/PinnedMemoryPoolTest.java
Following https://github.com/rapidsai/cudf/pull/15079, we add a way to share the pinned pool in JNI with cuIO via the new method added by @nvdbaranec `set_host_memory_resource`.
=> Use JNI pinned pool resource with cuIO

ci/build_docs.sh, python/cudf/cudf/core/column/column.py
Currently there are some network issues affecting docs builds. To prevent this from causing complete CI blockage, we can temporarily allow errors in the docs build. This will allow us to monitor the network status and re-enable the docs builds when the network issues are resolved.
=> Temporarily disable docs errors.

ci/build_docs.sh
This reverts part of commit c794ce4968b69e0cffc97b3db9496a1cdeab78bc. This PR can be merged after the docs.rapids.ai issues are resolved. cc: @raydouglass @AyodeAwe
PR #15265 unblocked CI for cudf by disabling errors in the docs. However, it also included the diff from #15261 so that CI would pass. This reverts the docs build changes but leaves in the changes from #15261.
=> Revert "Temporarily disable docs errors. (#15265)"

cpp/CMakeLists.txt
When building as static libraries, CMake tries to export the PRIVATE nvtx3-cpp dependency due to how it handles static library exports. Since nvtx3-cpp is a header-only library, and since cudf's public headers don't depend on it, make it BUILD_LOCAL_INTERFACE to avoid exporting the nvtx3-cpp dependency.
Issue: https://github.com/rapidsai/cudf/issues/15270
=> Make linking of nvtx3-cpp BUILD_LOCAL_INTERFACE

cpp/include/cudf/fixed_point/fixed_point.hpp
The addition of an array of integers in this function placed too much register pressure on our code base. This function is used by the fixed_point constructor and cast operators, so it potentially affects every kernel.  Too many unrelated kernels were impacted and suffered performance degradations to justify this change.  This reverts the algorithm introduced in #15110 to what it was previously, with some very minor tweaks.
=> Roll back ipow changes due to register pressure.

python/cudf/cudf/pandas/scripts/run-pandas-tests.sh
This PR adds `timeout` for the pytest command so that we can release the GPU resources if we detect a hang. Total suite usually takes 21 mins, I added 30 mins as the timeout.
=> Add timeout for `cudf.pandas` pandas tests

python/cudf/cudf/tests/test_groupby.py
This was required by #15109, but removed by the changes in #15145 and the merge order was such that they weren't tested against each other.
=> Reintroduce PANDAS_GE_220 import

ci/build_docs.sh
Prompted by https://github.com/rapidsai/cudf/pull/15101#issuecomment-1995325920
=> Fix Doxygen upload directory

python/cudf/cudf/tests/test_parquet.py
xref https://github.com/rapidsai/cudf/issues/15295
Hoping to make this test easier to debug if the input data is deterministic
=> Make test_read_parquet_partitioned_filtered data deterministic

cpp/src/io/comp/gpuinflate.cu
Issue #15216
Avoids an OOB read; the read was not causing bugs as the read data was never used.
Addresses the memcheck part of #15216
=> Fix OOB read in `inflate_kernel`

cpp/tests/error/error_handling_test.cu
Fixes errors reported by `gtests/ERROR_TEST` when run with a Debug build. Both errors occur due to invalid stream usage.
```
[ RUN      ] DebugAssert.cudf_assert_true
libcudf was not built with stacktrace support.
unknown file: Failure
C++ exception with description "cudf_identify_stream_usage found unexpected stream!" thrown in the test body.
[ RUN      ] DebugAssertDeathTest.cudf_assert_false
libcudf was not built with stacktrace support.
/cudf/cpp/tests/error/error_handling_test.cu:112: Failure
Death test: call_kernel()
Result: threw an exception.
Error msg:
[  DEATH   ] 
[  DEATH   ] /cudf/cpp/tests/error/error_handling_test.cu:112:: Caught std::exception-derived exception escaping the death test statement. Exception message: cudf_identify_stream_usage found unexpected stream!
``` …
=> Fix gtests/ERROR_TEST errors when run in Debug

cpp/src/io/utilities/datasource.cpp
Closes https://github.com/rapidsai/cudf/issues/14140
Added a no-op CUDA call before creating a `kvikio::FileHandle` to avoid the error in `cuFileDriverOpen`.
=> Work around a cuFile error when running CSV tests with memcheck

.github/workflows/pr.yaml, .github/workflows/test.yaml
This PR updates the script inputs in the relevant workflows from `build_script` and `test_script` to `script`. 
Depends on https://github.com/rapidsai/shared-workflows/pull/191
=> Update script input name

python/cudf/cudf/_lib/CMakeLists.txt, python/cudf/cudf/_lib/column.pyx, python/cudf/cudf/_lib/datetime.pyx, python/cudf/cudf/_lib/interop.pyx, python/cudf/cudf/_lib/nvtext/CMakeLists.txt, python/cudf/cudf/_lib/pylibcudf/CMakeLists.txt, python/cudf/cudf/_lib/pylibcudf/__init__.pxd, python/cudf/cudf/_lib/pylibcudf/column.pyx, python/cudf/cudf/_lib/pylibcudf/interop.pxd, python/cudf/cudf/_lib/pylibcudf/interop.pyx, python/cudf/cudf/_lib/pylibcudf/scalar.pxd, python/cudf/cudf/_lib/pylibcudf/scalar.pyx, python/cudf/cudf/_lib/pylibcudf/table.pxd, python/cudf/cudf/_lib/pylibcudf/table.pyx, python/cudf/cudf/_lib/pylibcudf/types.pxd, python/cudf/cudf/_lib/scalar.pxd, python/cudf/cudf/_lib/scalar.pyx, python/cudf/cudf/_lib/strings/CMakeLists.txt, python/cudf/cudf/_lib/strings/convert/CMakeLists.txt, python/cudf/cudf/_lib/strings/split/CMakeLists.txt
Resolves #15310. Contributes to #15193
In addition, this PR adds pylibcudf.Column<-->pyarrow.Array interconversion as a benefit
=> Restructure pylibcudf/arrow interop facilities

cpp/include/cudf/contiguous_split.hpp, cpp/include/cudf/copying.hpp, cpp/include/cudf/detail/null_mask.cuh, cpp/src/copying/contiguous_split.cu, cpp/src/copying/copy.cu, cpp/src/copying/copy_range.cu, cpp/src/copying/gather.cu, cpp/src/copying/get_element.cu, cpp/src/copying/scatter.cu, cpp/src/copying/shift.cu, cpp/src/copying/slice.cu, cpp/src/copying/split.cpp, cpp/tests/bitmask/bitmask_tests.cpp, cpp/tests/copying/copy_range_tests.cpp, cpp/tests/copying/copy_tests.cpp, cpp/tests/copying/get_value_tests.cpp, cpp/tests/copying/scatter_tests.cpp, cpp/tests/copying/shift_tests.cpp, cpp/tests/copying/slice_tests.cpp, cpp/tests/copying/split_tests.cpp
This PR also introduces `std::out_of_range` to cudf's code base in cases where it is appropriate.
Contributes to #12885 
Resolves #15315 
Contributes to #15162
=> Change exceptions thrown by copying APIs

ci/test_python_other.sh, ci/test_wheel_dask_cudf.sh
Sets `DASK_DATAFRAME__QUERY_PLANNING` explicitly in tests to avoid duplicate testing of dask-expr once dask version is unpinned.
=> Avoid duplicate dask-cudf testing

python/dask_cudf/dask_cudf/expr/__init__.py
During some offline debugging with @bdice and @divyegala, we discovered that some cuml tests are somehow failing after `dask_expr` is imported - Even if `dask_expr` is not actually being used. I'd like to figure out exactly what is causing that problem, but the first thing we can/should do is avoid the import altogether when the "query-planning" config is set to `False`.
=> Avoid importing dask-expr if "query-planning" config is `False`

ci/build_docs.sh
Fixes CI blocked by dask-expr.
xref:
- https://github.com/rapidsai/cudf/pull/14805
- https://github.com/rapidsai/rapids-dask-dependency/pull/33
=> Disable dask-expr in docs builds.

cpp/src/io/parquet/page_string_decode.cu, python/dask_cudf/dask_cudf/expr/__init__.py
Manual forward merge from 24.04 to 24.06. This PR should not be squashed.
=> Forward-merge branch-24.04 to branch-24.06

java/src/main/java/ai/rapids/cudf/ColumnVector.java, java/src/main/java/ai/rapids/cudf/HostColumnVector.java, java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
Closes https://github.com/rapidsai/cudf/issues/15350. This PR changes the order of the callback `MemoryBuffer.onClosed` to happen after our `MemoryCleaner` finishes. This is done so that we can accurately, and safely, reflect the state of the memory resource (be it device or host). This PR is needed to address a bug found in spark-rapids here: https://github.com/NVIDIA/spark-rapids/issues/10585.
=> [BUG][JNI] Trigger MemoryBuffer.onClosed after memory is freed

python/cudf/cudf/_lib/utils.pyx, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/dataframe/test_io_serialization.py, python/cudf/cudf/tests/test_parquet.py
When materializing range indices we were not previously creating the correct metadata. So do that.
While here, tidy up a few corner cases around creating range indices when constructing empty data frames.
- Closes #12243 
- Closes #14159
=> Fix arrow-based round trip of empty dataframes

python/cudf/udf_cpp/CMakeLists.txt
This PR updates the `udf_cpp` target to use `rapids_cpm_cccl`. The previous `rapids_cpm_libcudacxx` has been deprecated.
=> Update udf_cpp to use rapids_cpm_cccl.

docs/cudf/source/conf.py
Fixes a docs build error since `DLManagedTensor` cannot be resolved from the dlpack documentation.
=> Ignore DLManagedTensor in the docs build

cpp/src/io/parquet/decode_fixed.cu, cpp/src/io/parquet/decode_preprocess.cu, cpp/src/io/parquet/page_data.cu, cpp/src/io/parquet/page_data.cuh, cpp/src/io/parquet/page_decode.cuh, cpp/src/io/parquet/page_hdr.cu, cpp/src/io/parquet/page_string_decode.cu, cpp/src/io/parquet/parquet_gpu.hpp, cpp/src/io/parquet/reader_impl.cpp, cpp/src/io/parquet/reader_impl_chunking.cu, cpp/src/io/parquet/reader_impl_helpers.cpp, cpp/src/io/parquet/reader_impl_preprocess.cu
Closes #15224. Now use logical type exclusively in the reader rather than the deprecated converted type.
=> Use logical types in Parquet reader

ci/build_docs.sh, ci/check_style.sh, ci/test_cpp_common.sh, ci/test_java.sh, ci/test_notebooks.sh, ci/test_python_common.sh
conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.
=> Use `conda env create --yes` instead of `--force`

python/dask_cudf/dask_cudf/backends.py, python/dask_cudf/dask_cudf/io/tests/test_json.py, python/dask_cudf/dask_cudf/io/tests/test_parquet.py, python/dask_cudf/dask_cudf/io/tests/test_s3.py, python/dask_cudf/dask_cudf/tests/utils.py
Addresses parts of https://github.com/rapidsai/cudf/issues/15027 (json and s3 testing).
=> Enable ``dask_cudf`` json and s3 tests with query-planning on

cpp/src/io/json/nested_json_gpu.cu, cpp/tests/io/json_test.cpp
PR adds a missing synchronization before the FST destructor of the FST used for cleaning excess characters following the first valid record on a JSON line.
The problem is that the FST's destructor could otherwise free memory that is yet to be used by the still running FST instance.
Closes https://github.com/rapidsai/cudf/issues/15409
=> Fixes potential race in JSON parser when parsing JSON lines format and when recovering from invalid lines

.pre-commit-config.yaml, cpp/include/cudf/io/detail/parquet.hpp, cpp/src/copying/contiguous_split.cu, cpp/src/io/orc/aggregate_orc_metadata.cpp, pyproject.toml, python/cudf/benchmarks/common/config.py, python/cudf/cudf/_fuzz_testing/utils.py, python/cudf/cudf/core/buffer/buffer.py, python/cudf/cudf/core/buffer/spillable_buffer.py, python/cudf/cudf/core/column/__init__.py, python/cudf/cudf/core/column/methods.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/io/parquet.py, python/cudf/cudf/pandas/scripts/analyze-test-failures.py, python/cudf/cudf/pandas/scripts/summarize-test-results.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_monotonic.py, python/cudf/cudf/tests/test_multiindex.py, python/cudf/cudf/utils/docutils.py, python/cudf/cudf/utils/dtypes.py
xref https://github.com/rapidsai/cudf/pull/15345#discussion_r1532379047
Before pursuing migrating isort to ruff, bumping ruff to the latest version
=> Bump ruff and codespell pre-commit checks

.github/workflows/pr.yaml, .github/workflows/test.yaml, ci/configure_cpp_static.sh, cpp/cmake/thirdparty/get_nanoarrow.cmake, cpp/cmake/thirdparty/patches/nanoarrow_cmake.diff, dependencies.yaml
Resolves #15275
Resolves #15434
=> Test static builds in CI and fix nanoarrow configure

cpp/cmake/Modules/JitifyPreprocessKernels.cmake
The `JitifyPreprocessKernels.cmake` module now handles when `CUDAToolkit_INCLUDE_DIRS` has multiple values correctly, allowing for compilation with splayed CUDA Toolkit installs.
=> Allow jit compilation when using a splayed CUDA toolkit

cpp/include/cudf/detail/normalizing_iterator.cuh
Fixes the `cudf::detail::base_normalator::integer_sizeof_fn` dispatch function to support only integers. Also remove the `constexpr` since the non-integer path can throw an exception.
=> Fix base_normalator::integer_sizeof_fn integer dispatch

cpp/tests/interop/nanoarrow_utils.hpp, cpp/tests/interop/to_arrow_device_test.cpp
Fixes debug build failures resulting from changes from #15047. Here are some of the errors reported by the compiler:
```
Building CXX object tests/CMakeFiles/INTEROP_TEST.dir/interop/to_arrow_device_test.cpp.o
FAILED: tests/CMakeFiles/INTEROP_TEST.dir/interop/to_arrow_device_test.cpp.o 
/usr/local/bin/g++ -DFMT_HEADER_ONLY=1 -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DNANOARROW_DEBUG -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DSPDLOG_FMT_EXTERNAL -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_DISABLE_ABI_NAMESPACE -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_IGNORE_ABI_NAMESPACE_ERROR -I/cudf/cpp -I/cudf/cpp/src -I/cudf/cpp/build/_deps/dlpack-src/include -I/cudf/cpp/build/_deps/jitify-src -I/cudf/cpp/include -I/cudf/cpp/build/include …
```
=> Fix debug build errors from to_arrow_device_test.cpp

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/dtypes.py, python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_categorical.py
A rehash of https://github.com/rapidsai/cudf/pull/14979
The `CategoricalDtype.ordered` behavior matches `pandas.CategoricalDtype.ordered` behavior.
Also combines `as_ordered` and `as_unordred` into 1 method, and avoids to `as_index` casts that are already performed elsewhere
=> Avoid .ordered and .categories from being settable in CategoricalColumn and CategoricalDtype

python/cudf/cudf/_lib/pylibcudf/types.pyx
If we pass a scale parameter to cudf::data_type, the type_id must name a decimal type. This is asserted in debug mode.
Without this change, one cannot use the cython wrappers when build with CMAKE_BUILD_TYPE=Debug.
=> Only use data_type constructor with scale for decimal types

cpp/src/io/parquet/page_enc.cu
Fixes https://github.com/rapidsai/cudf/issues/15473
The issue is that in some cases, for example where we have all nulls, we can fail to update the size of the page output buffer, resulting in a missing byte expected by some readers.   Specifically, we poke the value of dict_bits into the output buffer here:
https://github.com/rapidsai/cudf/blob/6319ab708f2dff9fd7a62a5c77fd3b387bde1bb8/cpp/src/io/parquet/page_enc.cu#L1892
But, if we have no leaf values (for example, because everything in the page is null) `s->cur` never gets updated here, because we never enter the containing loop.
https://github.com/rapidsai/cudf/blob/6319ab708f2dff9fd7a62a5c77fd3b387bde1bb8/cpp/src/io/parquet/page_enc.cu#L1948
The fix is to just always update `s->cur` after this if-else block …
=> Fixed page data truncation in parquet writer under certain conditions.

cpp/cmake/thirdparty/get_nanoarrow.cmake, cpp/cmake/thirdparty/patches/nanoarrow_override.json
The usage of `PATCH_COMMAND` with `rapids_cpm_find` isn't capturable by `+rapids_cpm_generate_pinned_versions`. So we use a nanoarrow json override file to hold the patch we need applied and the custom SHA1 to check out.
=> nanoarrow uses package override for proper pinned versions generation

python/cudf/cudf/core/frame.py, python/cudf/cudf/core/indexed_frame.py
Extended view of the diff
Found a couple of others whilst looking into https://github.com/rapidsai/cudf/issues/15487
=> rm-dup-doc in frame.py

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/single_column_frame.py
It appears these properties do not map to public APIs, and for better state management, these `@property`s are better left not settable.
=> Make some private class properties not settable

ci/configure_cpp_static.sh
The new `configure_cpp_static.sh` script added in https://github.com/rapidsai/cudf/pull/15437 is calling `rapids-configure-conda-channels`. However, it is doing so on a `ci-wheel` image, which fails. This is causing CI issues and needs to be removed.
=> Remove conda channel setup from wheel CI image script.

.github/workflows/test.yaml
The `static-configure` CI job had an erroneous dependency on `checks`. That job exists for PRs but not nightly tests, and caused nightly failures.
=> Remove checks dependency from static-configure test job.

python/cudf/cudf/pandas/scripts/run-pandas-tests.sh
If these test actually crash pytest workers, will add to `TEST_THAT_CRASH_PYTEST_WORKERS`
=> Enable more ignored pandas unit tests for cudf.pandas

cpp/benchmarks/CMakeLists.txt
This renames a benchmark executable for `JSON_READER_OPTION` to indicate that it is an NVBench executable. This naming pattern is significant for our automated benchmarking tools.
=> Rename JSON_READER_OPTION to JSON_READER_OPTION_NVBENCH.

cpp/include/cudf/io/json.hpp
This PR deprecates the option for using the legacy JSON reader, so it can be removed in the next RAPIDS release.
This work follows up on a task from https://github.com/rapidsai/cudf/issues/15537
=> Deprecate legacy JSON reader options.

cpp/src/io/json/read_json.cu, cpp/tests/io/json_test.cpp, cpp/tests/streams/io/json_test.cpp
Fixes deprecation warnings caused by changes in #15558 
Most are in the `json_test.cpp` and appear like this
```
[150+7+50=206] Building CXX object tests/CMakeFiles/JSON_TEST.dir/io/json_test.cpp.o
/cudf/cpp/tests/io/json_test.cpp: In member function 'virtual void JsonReaderParamTest_BasicJsonLines_Test::TestBody()':
/cudf/cpp/tests/io/json_test.cpp:320:14: warning: 'cudf::io::json_reader_options_builder& cudf::io::json_reader_options_builder::legacy(bool)' is deprecated [-Wdeprecated-declarations]
317 |     cudf::io::json_reader_options::builder(cudf::io::source_info{data.data(), data.size()})
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
318 |       .dtypes(std::vector<data_type>{dtype<int32_t>(), dtype<double>()})
| …
```
=> Fix deprecation warnings for json legacy reader

cpp/src/strings/regex/utilities.cuh, cpp/src/strings/replace/backref_re.cuh, cpp/src/strings/replace/replace_re.cu
Updates the `replace_re()` and `replace_with_backrefs()` internal logic to support large strings.
These functions use a regex-specific version of make-strings-children.
Depends on #15363
=> Large strings support in regex replace APIs

cpp/tests/io/json_test.cpp, cpp/tests/io/nested_json_test.cpp
This PR renames the "experimental" JSON reader tests. These are now production grade and not experimental.
This task is tracked in https://github.com/rapidsai/cudf/issues/15537.
=> Rename experimental JSON tests.

python/cudf/cudf/pandas/fast_slow_proxy.py, python/cudf/cudf_pandas_tests/test_cudf_pandas.py
closes #15548
`_replace_closurevars` creates a new function by replacing objects with their fast versions. When creating the new function, it populates `globals` from the result of `inspect.getclosurevars`, but it don't think it comprehensively returns _all_ the globals accessible to the function (`function.__globals__`)
To minimize the change, the "fast globals" are still sourced from `inspect.getclosurevars`, and those update the `old_function.__globals__` when creating a new function.
=> Allow apply udf to reference global modules in cudf.pandas

python/cudf/cudf/tests/pytest.ini
cupy 13.1 added a warning about the jitify cache warming up that we must silence in our test suite for it to pass.
=> Ignore new cupy warning

dependencies.yaml
Fixes dependency issue with nightly builds running 11.4.3 cpp tests requiring the compute-sanitizer tool.
Closes #15571
=> Add cuda-sanitizer-api dependency for test-cpp matrix 11.4

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
Noticed that step was hardcoded to `1` when it should reflect `RangeIndex.step`
=> Preserve RangeIndex.step in to_arrow/from_arrow

ci/run_cudf_examples.sh, dependencies.yaml
Undoes changes in 15573 since `compute-sanitizer` is not available in the CI test environment with CUDA 11.4.
This disables the example scripts for tests with CUDA < 11.6 only to unblock the nightly builds.
=> Disable compute-sanitizer usage in CI tests with CUDA<11.6

cpp/benchmarks/string/contains.cpp, cpp/benchmarks/string/count.cpp, cpp/src/strings/regex/regex.inl
Improves performance of `cudf::strings::count_re` when pattern starts with a literal character.
Although this is a specific use case, the regex code has special logic to help speed up the search in this case.
Since the pattern indicates the target must contain this character as the start of the matching sequence, it first does a normal find for the character before continuing matching the remaining pattern. The `find()` function can be inefficient for long strings since it is character based and must resolve the character's byte-position by counting from the beginning of the string. For a function like `count_re()` all occurrences are matched within a target meaning longer target strings can incur expensive counting.
The solution included here is to introduce a more efficient …
=> Improve performance for cudf::strings::count_re

cpp/tests/interop/from_arrow_device_test.cpp, cpp/tests/interop/nanoarrow_utils.hpp, cpp/tests/interop/to_arrow_device_test.cpp
Fixes debug build errors introduced by #15458 
These warnings show up in a debug build where warnings become errors.
Some of the errors:
```
/cudf/cpp/tests/interop/from_arrow_device_test.cpp:103:27: error: ignoring return value of 'ArrowErrorCode cudfArrowSchemaSetTypeStruct(ArrowSchema*, int64_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
103 |   ArrowSchemaSetTypeStruct(input_schema.get(), 1);
/cudf/cpp/tests/interop/from_arrow_device_test.cpp:105:29: error: ignoring return value of 'ArrowErrorCode cudfArrowSchemaSetTypeDateTime(ArrowSchema*, ArrowType, ArrowTimeUnit, const char*)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
105 |   ArrowSchemaSetTypeDateTime(
/cudf/cpp/tests/interop/from_arrow_device_test.cpp:107:21: error: ignoring …
```
=> Fix debug warnings/errors in from_arrow_device_test.cpp

cpp/src/strings/char_types/char_types.cu, cpp/src/strings/filter_chars.cu, cpp/src/strings/replace/multi.cu, cpp/src/strings/replace/replace.cu, cpp/src/strings/replace/replace_slice.cu, cpp/src/strings/translate.cu
Updates strings replace functions to use the new experimental `make_strings_children` which supports building large strings.
Reference #15579
=> Use experimental make_strings_children for strings replace/filter/translate

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-122_arch-x86_64.yaml, conda/recipes/cudf/meta.yaml, dependencies.yaml, python/cudf/cudf/tests/pytest.ini, python/cudf/pyproject.toml
Backport of https://github.com/rapidsai/cudf/pull/15506 to cuDF 24.04.
Also backports #15574 to ignore a warning from newer cupy releases.
=> Backport: Relax protobuf lower bound to 3.20. (#15506)

cpp/benchmarks/json/json.cu, cpp/src/io/csv/writer_impl.cu, cpp/src/io/json/write_json.cu
Updates the JSON and CSV writer functions to use the new experimental make_strings_children.
Also included is an update to the JSON_BENCH benchmark for get_json_object.
Reference https://github.com/rapidsai/cudf/issues/15579
=> Use experimental make_strings_children for json/csv writers

cpp/cmake/thirdparty/get_nvbench.cmake, cpp/cmake/thirdparty/patches/nvbench_override.json
The override is no longer necessary as rapids-cmake now uses the same version that was set by the override.
Refs rapidsai/rapids-cmake#584, #15492
- [N/a] New or existing tests cover these changes.
- [N/a] The documentation is up to date with these changes.
=> Remove NVBench SHA override.

cpp/src/io/parquet/page_decode.cuh
Fixes an operator precedence problem with a bitwise `&` that was not detected because it was accidentally correct. `PAGEINFO_FLAGS_DICTIONARY` has a value of '1', so `PAGEINFO_FLAGS_DICTIONARY != 0` evaluates to '1', and that ANDed with the page flags evaluates `true` when the bit is set.
=> Fix operator precedence problem in Parquet reader

cpp/src/io/comp/cpu_unbz2.cpp, cpp/src/io/parquet/reader_impl_helpers.cpp
I'm compiling cuDF as a part of another application and ran into errors from `-Werror=type-limits`. There are a few comparisons between unsigned types like `value < 0`, which is never true. This PR removes those impossible code paths.
=> Fix -Werror=type-limits.

cpp/src/strings/copying/shift.cu
Fixes the `cudf::strings::detail::shift()` function to use the correct `make_offsets_child_column` function to support large strings.
=> Fix make_offsets_child_column usage in cudf::strings::detail::shift

cpp/src/hash/md5_hash.cu, cpp/src/hash/sha_hash.cuh
Updates the hash functions for md5 and sha to support creating large strings results.
=> Large strings support in MD5 and SHA hashers

cpp/src/strings/convert/convert_booleans.cu, cpp/src/strings/convert/convert_datetime.cu, cpp/src/strings/convert/convert_durations.cu, cpp/src/strings/convert/convert_fixed_point.cu, cpp/src/strings/convert/convert_floats.cu, cpp/src/strings/convert/convert_hex.cu, cpp/src/strings/convert/convert_integers.cu, cpp/src/strings/convert/convert_ipv4.cu
Updates strings convert functions to use the new experimental `make_strings_children` which supports building large strings.
Reference https://github.com/rapidsai/cudf/issues/15579
=> Use experimental make_strings_children for strings convert

cpp/src/io/json/nested_json.hpp, cpp/src/io/json/read_json.cu, cpp/tests/io/nested_json_test.cpp
This PR addresses a task from #15537 to remove the `host_parse_nested_json` code path and corresponding tests. See discussion in https://github.com/rapidsai/cudf/pull/15568#issuecomment-2067024223.
=> Remove host_parse_nested_json.

.pre-commit-config.yaml, python/cudf/cudf/core/column/column.py, python/cudf/cudf/pandas/fast_slow_proxy.py
The only really substantive change is to update mypy, which will be required for some type annotations in the cudf-polars work.
=> Upgrade pre commit hooks

.github/workflows/pr.yaml, ci/cudf_pandas_scripts/pandas-tests/diff.sh
An `s3` fetch api seems to be returning incorrectly ordered output, this PR fixes the issue.
=> Fix CI s3 api command to fetch latest results

python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/tests/test_categorical.py
Fixes: #15666 
This PR validates values passed to `fillna` even if there are no null values in a categorical column.
Forks from #14534
=> Allow `fillna` to validate for `CategoricalColumn.fillna`

python/cudf/cudf/pandas/_wrappers/pandas.py, python/cudf/cudf_pandas_tests/test_cudf_pandas.py
Fixes: #15678 
This PR adds a proxy type for `NumpyExtensionArray`
Forks out from #14534
=> Add `NumpyExtensionArray` proxy type in `cudf.pandas`

python/cudf/cudf/tests/test_parquet.py
test_parquet.py currently takes around 55s to run on an RTXA6000 system. A large portion of that run time is in two tests of the Parquet DELTA_LENGTH_BYTE_ARRAY and DELTA_BYTE_ARRAY encodings. These tests are parameterized with varying row counts to test certain encoding edge cases, but the final two row counts (10,000, 50,000) are unnecessarily large to provide adequate test coverage. This PR reduces the number of row counts (some were redundant) and decreases the maximum row count to 1,000.  This drops the execution time to just under 26s on the same system.
This PR also corrects an oversight from #15239. DELTA_BYTE_ARRAY encoding should have been added to the tests at that time.
=> Rework some python tests of Parquet delta encodings

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/index.py, python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_dataframe.py, python/cudf/cudf/tests/test_index.py, python/cudf/cudf/tests/test_series.py
Fixes: #15679 
This PR switches the default of `nan_as_null` to be `False` if pandas compatibility mode is turned on.
Forked from #14534
=> Make `nan_as_null` behavior consistent across all APIs

cpp/benchmarks/io/json/json_reader_option.cpp
This PR cleans up the JSON reader options benchmark by reducing the number of runtime configurations from 162 to 20. 
Reasoning behind the splitting of the benchmark -
1. The `normalize_single_quotes` and `normalize_whitespace` are pre-processing options and do not impact each other - the runtimes of the FSTs are additive.
2. The performance of raw input ingestion (`row_selection::ALL` and `row_selection::BYTE_RANGE`) is independent of the token generation and tree algorithms.
=> Reducing runtime of JSON reader options benchmark

python/cudf/cudf/core/column/column.py, python/cudf/cudf/core/column/numerical_base.py
* Some typing
* Moved a single use helper function inline
* Some dtype checking simplification
=> Misc Column cleanups

cpp/benchmarks/CMakeLists.txt, cpp/benchmarks/json/json.cu
Moves google-benchmark for `cudf::get_json_object` to nvbench.
Also removes randomness from device code to help ensure consistent results if the test input data generator logic is changed.
Updating the `detail::make_strings_children` function produced different input data so the performance results could not be compared. Removing the device code randomness helps keep the input data consistent.
=> Rework get_json_object benchmark to use nvbench

.github/CODEOWNERS
This PR overhauls how `ops-codeowners` reviews are handled.
`ops-codeowners` is replaced by `ci-codeowners` & `packaging-codeowners`. The coverage of files is expanded as well.
Additionally, the process will change: reviews will be assigned to a member of the teams instead of a manual request to `ops-codeowners`.
=> Overhaul ops-codeowners coverage

python/cudf/cudf/core/index.py, python/cudf/cudf/tests/test_index.py
Fixes: #15713 
This PR properly calls `search_sorted` to arrive at correct results for indexes that are of decreasing order.
=> Fix `get_loc` to properly fetch results from an index that is in decreasing order

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/tests/test_dataframe.py
Fixes: #15716 
This PR makes changes to `.loc` by preserving the original type at the end of the operation.
=> Return same type as the original index for `.loc` operations

python/cudf/cudf/core/column_accessor.py, python/cudf/cudf/tests/test_column_accessor.py
https://github.com/rapidsai/cudf/pull/14758 may have propagated a caching invalidation bug of the number of rows in a `ColumnAccessor`
Previously the number of rows was cached and cleared only if an operation caused the `ColumnAccessor` to have no more columns.
However, if the `ColumnAccessor` was empty and operation added new columns, the cached number of rows should have also been cleared.
=> Fix ColumnAccessor caching of nrows if empty previously

ci/configure_cpp_static.sh, cpp/cmake/thirdparty/get_arrow.cmake
Correct the CMake logic in arrow so that we can properly build cudf + arrow statically
Fixes https://github.com/rapidsai/cudf/issues/15714
=> Correct static builds + static arrow

python/cudf/cudf/core/column/column.py
closes #8796
I left a `TODO` in `as_column` to validate earlier that `arbitrary` is an iterable or sequence like if it wasn't a recognized array like (e.g. numpy array, pandas object, etc). Additionally, ensure we materialize iterators since there are some checks that would exhaust the object
=> Validate and materialize iterators earlier in as_column

cpp/CMakeLists.txt, cpp/benchmarks/binaryop/compiled_binaryop.cpp, cpp/include/cudf/binaryop.hpp, cpp/src/binaryop/binaryop.cpp, cpp/src/binaryop/compiled/NullNotEquals.cu, cpp/src/binaryop/compiled/binary_ops.cu, cpp/src/binaryop/compiled/binary_ops.cuh, cpp/src/binaryop/compiled/binary_ops.hpp, cpp/src/binaryop/compiled/operation.cuh, cpp/src/binaryop/compiled/struct_binary_ops.cuh, cpp/src/binaryop/compiled/util.cpp, cpp/tests/binaryop/binop-compiled-test.cpp, cpp/tests/binaryop/util/operation.h, java/src/main/java/ai/rapids/cudf/BinaryOp.java, java/src/main/java/ai/rapids/cudf/BinaryOperable.java, python/cudf/cudf/_lib/binaryop.pyx, python/cudf/cudf/_lib/pylibcudf/libcudf/binaryop.pxd, python/cudf/cudf/core/column/categorical.py, python/cudf/cudf/core/column/datetime.py, python/cudf/cudf/core/column/numerical.py, python/cudf/cudf/core/column/string.py, python/cudf/cudf/core/column/timedelta.py
Fill out the table of null-aware comparison binops by also supporting a new NULL_NOT_EQUALS. This is the negation of NULL_EQUALS but implemented in a single pass, rather than binop(NULL_EQUALS) followed by uop(NEGATE).
=> Implement null-aware NOT_EQUALS binop

cpp/tests/io/parquet_chunked_reader_test.cu
Reduces the runtime for the `ParquetChunkedReaderInputLimitTest.List` and `ParquetChunkedReaderInputLimitTest.Mixed` which together are 1/3 the total time for `PARQUET_TEST`.
These two tests produce multi-GB test files that are not strictly necessary for testing the chunked reader since the chunk sizes are controllable. The changes here reduce the runtime for these 2 tests by about 1/3 the original runtime.
=> Reduce runtime for ParquetChunkedReaderInputLimitTest gtests

cpp/src/strings/split/split.cuh, cpp/src/strings/split/split_re.cu, cpp/tests/column/factories_test.cpp, cpp/tests/copying/concatenate_tests.cpp, cpp/tests/strings/array_tests.cpp, cpp/tests/strings/factories_test.cu, cpp/tests/strings/repeat_strings_tests.cpp
Fixes offsets type for list column returned by `cudf::strings::split_record` and `cudf::strings::split_record_re` when large-strings enabled. The list column offsets type must be INT32. The code was changed to use the appropriate `make_offsets_child_column` utility function.
Also added some `is_large_strings_enabled()` checks to check-overflow gtests.
This allows all current gtests to pass when the large-strings support environment variable is set.
=> Fix split-record result list column offset type

python/cudf/cudf/core/reshape.py, python/cudf/cudf/tests/test_reshape.py
closes #15758
Also fixes an inconsistency with pandas where `var_name` data was always a `Categorical` unlike pandas
=> Fix id_vars and value_vars not accepting string scalars in melt

python/cudf/cudf/core/column/numerical.py, python/dask_cudf/dask_cudf/tests/test_core.py
Fixes: #15768 
There is a possibility that a host array can have `object` type but contain all values of a homogeneous type, this still cannot be supported by column constructors because `cudf` doesn't have a true `object` types, hence this PR introduces a workaround for this problem in `isin` API.
=> Handle mixed-like homogeneous types in `isin`

conda/recipes/libcudf/meta.yaml, dependencies.yaml
Fix `libarrow` runtime dependency which is currently broken due to the release of `libarrow=16.1.0`:
```python
$ python -c "import cudf"
File "<string>", line 1, in <module>
File "/opt/conda/envs/rapids/lib/python3.10/site-packages/cudf/__init__.py", line 9, in <module>
_setup_numba()
File "/opt/conda/envs/rapids/lib/python3.10/site-packages/cudf/utils/_numba.py", line 124, in _setup_numba
_get_cc_60_ptx_file()
File "/opt/conda/envs/rapids/lib/python3.10/site-packages/cudf/utils/_numba.py", line 16, in _get_cc_60_ptx_file
from cudf._lib import strings_udf
File "/opt/conda/envs/rapids/lib/python3.10/site-packages/cudf/_lib/__init__.py", line 4, in <module>
from . import (
ImportError: libarrow.so.1600: cannot open shared object file: No such file or …
```
=> Limit runtime dependency to `libarrow>=16.0.0,<16.1.0a0`

python/cudf/cudf/pandas/_wrappers/pandas.py, python/cudf/cudf_pandas_tests/test_cudf_pandas.py
Only `pandas-2.1.0+` has support for `NumpyExtensionArray` and any version below that only have support for `PandasArray`. This PR make `cudf.pandas` back-ward compatible in that aspect.
=> Add support for `PandasArray` for `pandas<2.1.0`

cpp/include/cudf/io/detail/parquet.hpp, cpp/include/cudf/io/parquet.hpp, cpp/src/io/functions.cpp, cpp/src/io/parquet/reader.cpp, cpp/src/io/parquet/reader_impl.cpp, cpp/src/io/parquet/reader_impl.hpp, cpp/src/io/parquet/reader_impl_chunking.cu, cpp/src/io/parquet/reader_impl_preprocess.cu
This PR does the following:
1. It enables the support for filtered I/O in chunked parquet reader.
2. It simplifies the use of `parquet_reader_options` in `parquet::readers` by taking and saving the options at reader construction for later use instead of passing around `options` as arguments from `read()`, `has_next()` and `chunked_read()` to `prepare_data()`, `read_chunk_internal()` and several other internal APIs.
=> Support filtered I/O in `chunked_parquet_reader` and simplify the use of `parquet_reader_options`

python/cudf/cudf/core/_base_index.py, python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/multiindex.py, python/cudf/cudf/core/single_column_frame.py
xref https://github.com/rapidsai/cudf/issues/11648
Essentially refactors `Frame._to_array` to short circuit some checks for a `Frame` with 1 column or `ndim == 1` 
```python
In [2]: s = cudf.Series(range(10000))
In [3]: %timeit s.to_cupy()
252 µs ± 3.47 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)  # PR
419 µs ± 2.21 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)  # branch 24.06
```
I needed to add `Frame.ndim` which will raise a `NotImplementedError` (until Frame actually becomes an ABC)
=> Improve performance of Series.to_numpy/to_cupy

python/dask_cudf/dask_cudf/expr/_collection.py, python/dask_cudf/dask_cudf/expr/_expr.py, python/dask_cudf/dask_cudf/tests/test_sort.py
Follow up to https://github.com/rapidsai/cudf/pull/15788
Adds a temporary workaround for sorting on categorical columns in 24.06: We convert only the partitioning column to pandas to calculate divisions.
This is related to https://github.com/rapidsai/cudf/issues/11795, but I don't want to "close" that issue until `RepartitionQuantiles` works with cudf-backed data.
=> Add temporary dask-cudf workaround for categorical sorting

cpp/benchmarks/fixture/nvbench_fixture.hpp
Previously, the benchmarks used a non-pooled pinned memory allocator by default, and exposed an option to use an internally-declared pooled pinned allocator.  Now that we have a pooled pinned allocator enabled in cuIO itself, this PR switches to using that as the new default for the benchmarks.
=> Switch cuIO benchmarks to use pinned-pool host allocations by default.

cpp/include/cudf/io/memory_resource.hpp, cpp/src/io/utilities/config_utils.cpp, java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java, java/src/main/java/ai/rapids/cudf/Rmm.java, java/src/main/native/src/RmmJni.cpp
Closes https://github.com/rapidsai/cudf/issues/15814
This adds a boolean return value from `cudf::io::config_host_memory_resource` to allow the caller to handle the case where the memory resource has already been configured in the past. Before this the function would throw, forcing callers to try/catch.
=> Return boolean from config_host_memory_resource instead of throwing

cpp/CMakeLists.txt, cpp/benchmarks/CMakeLists.txt, cpp/cmake/thirdparty/get_nvtx.cmake, cpp/tests/CMakeLists.txt, java/src/main/native/CMakeLists.txt
We need to use the `rapids_cpm_nvtx3` so that the nvtx3 targets, and setup are consistent across rmm and cudf. If we don't we get errors around incorrect exports when building statically or link errors when building shared.
=> Use rapids_cpm_nvtx3 to get same nvtx3 target state as rmm

python/cudf/cudf/core/series.py, python/cudf/cudf/tests/test_series.py
Aligns these behaviors
```python
In [1]: import pandas as pd
In [3]: ser1 = pd.Series(range(3), index=list("Abc"))
In [4]: ser2 = pd.Series(ser1)
In [5]: ser1.index is ser2.index
Out[5]: True
In [6]: import cudf
In [7]: ser1 = cudf.Series(range(3), index=list("Abc"))
In [8]: ser2 = cudf.Series(ser1)
In [9]: ser1.index is ser2.index
Out[9]: False
```
=> Ensure cudf.Series(cudf.Series(...)) creates a reference to the same index

docs/cudf/source/libcudf_docs/api_docs/io_readers.rst, docs/cudf/source/libcudf_docs/api_docs/strings_convert.rst
Fixes documentation for IO readers and strings_convert.
=> Fix docs for IO readers and strings_convert

python/cudf/cudf/core/dataframe.py, python/cudf/cudf/core/frame.py, python/cudf/cudf/core/indexed_frame.py, python/cudf/cudf/core/multiindex.py
Also ensures any calls to `_num_rows` uses the cached version
=> Use ColumnAccessor row and column length attributes more consistently

ci/build_docs.sh, docs/cudf/source/libcudf_docs/api_docs/io_readers.rst, docs/cudf/source/libcudf_docs/api_docs/strings_convert.rst
Reverts rapidsai/cudf#15842
The files the original PR added documentation for appear to contain some text that is problematic for the Sphinx parser to extract from doxygen. My best guess is that it's something in a table, since parsing doxygen tables via Breathe is something I know can be tricky. We didn't catch this issue because [we currently only build the text docs in nightly builds, not PRs](https://github.com/rapidsai/cudf/blob/branch-24.08/ci/build_docs.sh#L49), and this issue only arises in those text builds. We can revisit adding these docs in 24.08. For the sake of correctness, I have added back building text docs in PRs in this PR (see #14856 for context on the removal).
=> Revert "Fix docs for IO readers and strings_convert"

cpp/benchmarks/join/distinct_join.cu, cpp/benchmarks/join/join.cu, cpp/benchmarks/join/join_common.hpp, cpp/benchmarks/join/mixed_join.cu
This a followup of #15644.
It fixes the lhs/rhs input bug in the hash join and distinct join benchmarks.
=> Refactor join benchmarks to target public APIs with the default stream

cpp/src/lists/interleave_columns.cu
Fixes the `compute_string_sizes_and_interleave_lists_fn` functor to use `column_device_view::element<string_view>()` method to access string row contents instead of using the strings offsets. This removes the need to add specific offsetalator logic to the logic.
=> Update interleave lists column for large strings

python/cudf/cudf/core/buffer/buffer.py, python/cudf/cudf/core/buffer/spillable_buffer.py, python/cudf/cudf/tests/test_hash_vocab.py, python/cudf/cudf/tests/test_numerical.py, python/cudf/cudf/tests/test_replace.py, python/cudf/cudf/tests/test_sorting.py, python/cudf/cudf/utils/hash_vocab_utils.py
I have a branch that works, but some changes may need a bit of thought to get right, so splitting out the simpler half.
(N.B. the only bigger chunk that is remaining is to make sure that `uint_series > -1` keeps working at least as well as before)
In either case, these are changes that:
* Avoid `copy=False` in `np.array()`
* Are necessary due to NumPy rejecting e.g. `uint8(-1)` now (only changed this where it is test-only)
* Are necessary due to NumPy preserving the scalar dtype things fail later (the hashing code and using `float(float32)` to avoid overflow.
* Sorting change is the same, using `int8(-1)` gives effectively the old promotion (to float) rather than erroring to not implicit go to float based on the value.
The main noise, is that I parametrized that one test since it seemed …
=> Simple NumPy 2 fixes that are clearly no behavior change

python/cudf/cudf/core/frame.py, python/cudf/cudf/tests/test_dataframe.py
The current logic for converting arrow dictionary arrays to cudf doesn't properly uniquify categories across chunks of chunked arrays. This PR implements the simplest fix by having arrow combine chunks when this case is encountered.
Resolves #6828
=> Fix categorical conversion from chunked arrow arrays

cpp/src/text/vocabulary_tokenize.cu
Updates the `token_counts_fn` kernel in the `nvtext::tokenize_with_vocabulary` to use the offsetalator instead of hardcoded `size_type` for accessing strings offsets.
=> Use offsetalator in nvtext::tokenize_with_vocabulary

cpp/src/strings/replace/multi.cu
Replaces `thrust::count_if` with raw kernel counter to handle large strings (int64 offsets) and > 2GB strings columns.
=> Fix multi-replace target count logic for large strings

cpp/src/io/orc/dict_enc.cu
Replaces hardcoded `size_type` for accessing strings offsets data with the offsetalator to compute the number of characters in a group in `cudf::io::orc::gpu::rowgroup_char_counts_kernel`
=> Use offsetalator in orc rowgroup_char_counts_kernel
