rapidsai/cudf

cpp/benchmarks/string/url_decode.cu

Fixes the logic for generating URLs in the url-decoder benchmark to use the offsetalator instead of hardcoding `size_type`.
This will allow benchmarking with large strings column in the future.

Fix url-decode benchmark to use offsetalator

---

cpp/benchmarks/string/replace.cpp
cpp/include/cudf/strings/detail/replace.hpp
cpp/include/cudf/strings/replace.hpp
cpp/src/strings/replace/multi.cu
cpp/tests/json/json_tests.cpp
cpp/tests/streams/strings/replace_test.cpp
cpp/tests/strings/replace_tests.cpp
java/src/main/native/src/ColumnViewJni.cpp
python/cudf/cudf/_lib/pylibcudf/libcudf/strings/replace.pxd
python/cudf/cudf/_lib/strings/replace.pyx

Renames the multi-target overload of `cudf::strings::replace()` to `cudf::strings::replace_multiple()`.
This helps with some Cython issues involving fused types and overloaded functions with the same number of arguments.
Reference: https://github.com/rapidsai/cudf/issues/15855#issuecomment-2129980298
This change deprecates the old name to be removed in a future release.
Also added some additional error unit tests.
Closes #15855

Rename strings multiple target replace API

---

cpp/src/strings/copying/shift.cu

Replaces hardcoded `size_type` used for offset values in the `shift_chars_fn` functor with offsetalator.
Follow on to #15630

Use offsetalator in strings shift functor

---

python/cudf/cudf/pylibcudf_tests/common/utils.py
python/cudf/cudf/pylibcudf_tests/test_copying.py
python/cudf/cudf/pylibcudf_tests/test_reshape.py
python/cudf/cudf/pylibcudf_tests/test_string_capitalize.py

Swap the order of result,expected to expected, result for assert_table_eq too
Fix a few places where result,expected was swapped for assert_column_eq

Clean up pylibcudf test assertations

---

docs/cudf/source/cudf_pandas/how-it-works.md
docs/cudf/source/user_guide/api_docs/options.rst
docs/cudf/source/user_guide/options.md

Recently I have answered a few user questions about how to use cudf options for display. We were missing documentation that explained that display options are inherited from pandas. I also found a broken link in the docs. This PR fixes both of those doc-related issues.

Improve options docs

---

.github/labeler.yml

This PR leverages some of the new labels we have for organizing our issues and removes labels that aren't really used at the moment. If reviewers feel strongly I can keep the ci label, but AFAICT that doesn't really get used for anything at the moment and we'll benefit more from leveraging future labels to help direct tasks to the build/infra team vs cudf devs.

Update Python labels and remove unnecessary ones

---

cpp/src/io/utilities/column_buffer.cpp
cpp/src/reshape/byte_cast.cu

Fixes a couple places where strings columns are converted to lists column as binary -- chars are represented as INT8.
Since lists columns only support `size_type` offsets type, this change will throw an error if the size of the chars exceeds max `size_type` values.

Add overflow check when converting large strings to lists columns

---

python/cudf/cudf/_lib/pylibcudf/interop.pyx
python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/utils/dtypes.py
python/cudf_polars/pyproject.toml
python/cudf_polars/tests/__init__.py
python/cudf_polars/tests/expressions/__init__.py
python/cudf_polars/tests/expressions/test_agg.py
python/cudf_polars/tests/expressions/test_distinct.py
python/cudf_polars/tests/test_scan.py

The polars schema tells us the dtype for any literals, but previously we were relying on pyarrow inference. Add pylibcudf to pyarrow datatype conversion utilities and use the resulting datatypes explicitly.

Ensure literals have correct dtype

---

docs/cudf/source/developer_guide/cudf_pandas.md
docs/cudf/source/developer_guide/index.md

This PR provides documentation for cudf.pandas in the Developer Guide. It will describe the fast-slow proxy wrapping scheme as well as document the `CUDF_PANDAS_DEBUGGING` environment variable created in PR #15837 for issue #14975.

DOC: Add documentation for cudf.pandas in the Developer Guide

---

cpp/tests/CMakeLists.txt

Allows cudf to be built with `BUILD_SHARED_LIBS=OFF`, `CUDA_STATIC_RUNTIME=ON` and tests enabled

Allow tests to be built when stream util is disabled

---

python/cudf_polars/cudf_polars/containers/__init__.py
python/cudf_polars/cudf_polars/containers/column.py
python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/testing/asserts.py
python/cudf_polars/cudf_polars/utils/dtypes.py
python/cudf_polars/cudf_polars/utils/sorting.py
python/cudf_polars/docs/overview.md
python/cudf_polars/tests/expressions/test_agg.py
python/cudf_polars/tests/test_select.py
python/cudf_polars/tests/test_union.py

Simplify name tracking in expression evaluation by only requiring names for columns when putting them in to a `DataFrame`. At the same time, this allows us to have one place where we broadcast-expand `Scalar`s to the size of the `DataFrame`, so we can expunge tracking them in the `DataFrame` itself.
Additionally, adapt to minor changes on the polars side in terms of translating the DSL: we no longer need to handle CSE expressions specially, and sorting by multiple keys takes a list of `descending` flags, rather than a single bool as previously.

Introduce `NamedColumn` concept in cudf-polars

---

docs/cudf/source/cudf_pandas/usage.md

We need to arrange that cudf.pandas.install() is run on the workers, this requires that we programmatically install the metapath loader in our script. Unfortunately, passing an initializer function to the pool startup is not sufficient if any part of the script transitively loads pandas at the top level.
- Closes #15246

Document how to use cudf.pandas in tandem with multiprocessing

---

.pre-commit-config.yaml
python/cudf_polars/cudf_polars/__init__.py
python/cudf_polars/cudf_polars/callback.py
python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/testing/asserts.py
python/cudf_polars/cudf_polars/typing/__init__.py
python/cudf_polars/pyproject.toml

We can check this with:
pyright --verifytypes cudf_polars --ignoreexternal
Which reports a "type completeness" score of around 94%. This will
improve once pylibcudf gets type stubs.

Add more complete type annotations in polars interpreter

---

cpp/src/io/utilities/data_casting.cu
cpp/tests/io/json_test.cpp

Updates the `cudf::io::json::detail::parse_string` function to use the offsetalator for building a strings column instead of `size_type` pointers. The output row sizes are computed in the first pass through the kernels and then converted to offsets. The offsets are wrapped with an offsetalator on the 2nd pass to locate each individual rows' output position in the chars data.

Use offsetalator in cudf::io::json::detail::parse_string

---

ci/build_docs.sh
docs/cudf/source/libcudf_docs/api_docs/io_readers.rst
docs/cudf/source/libcudf_docs/api_docs/strings_convert.rst

This reverts commit 2b031e06a7fe18eec462db445eea1c596b93a9f1.
We got the go ahead to remove the text docs from @taureandyernv.

Reland "Fix docs for IO readers and strings_convert" (#15872)"

---

python/cudf/cudf/pandas/_wrappers/common.py
python/cudf/cudf/pandas/_wrappers/numpy.py

Add __array_interface__ to cudf.pandas numpy.ndarray proxy

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/index.py
python/cudf/cudf/tests/series/test_datetimelike.py
python/cudf/cudf/tests/test_datetime.py
python/dask_cudf/dask_cudf/io/tests/test_parquet.py

closes #13611
(This technically does not support pandas objects have interval types that are timezone aware)
@rjzamora let me know if the test I adapted from your PR in https://github.com/rapidsai/cudf/pull/15929 is adequate

Support timezone aware pandas inputs in cudf

---

conda/recipes/libcudf/build.sh

The libcudf conda package is not specifying to build for all supported architectures and is instead letting build.sh fall back to NATIVE. However, because the default behavior of rapids-cmake is to build SASS for all supported architectures if NATIVE is specified but no local architecture is detected, we're still ending up with all of the RAPIDS architectures having SASS built for them. The problem is that we are failing to build PTX for the latest version, which would be produced if we used RAPIDS instead of NATIVE. This PR should resolve that issue.

Explicitly build for all GPU architectures

---

python/cudf/cudf/api/types.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/single_column_frame.py

Also removes an extra copy from `.flatten()` when calling `.values` or `.values_host`

Add typing to single_column_frame

---

python/cudf/cudf/pylibcudf_tests/test_copying.py
python/cudf/cudf/pylibcudf_tests/test_quantiles.py
python/cudf/cudf/pylibcudf_tests/test_reshape.py
python/cudf/cudf/pylibcudf_tests/test_string_capitalize.py
python/cudf/cudf/pylibcudf_tests/test_string_contains.py
python/cudf/cudf/pylibcudf_tests/test_string_find.py

Condense all pa_foo/plc_foo data fixtures into just foo, as recommended by
https://github.com/rapidsai/cudf/pull/15839#discussion_r1626769872.

Condense pylibcudf data fixtures

---

cpp/src/io/text/multibyte_split.cu

Replaces int32 type used for building offsets in `cudf::io::text::multibyte_split()` to use the offsetalator instead.
This allows creating large strings columns from input text files.

Support large strings in cudf::io::text::multibyte_split

---

python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/cudf_polars/testing/asserts.py
python/cudf_polars/cudf_polars/typing/__init__.py
python/cudf_polars/tests/test_slice.py

Polars wraps negative starts and then clamps both the resulting start
and length to [0, num_rows), so we should do that.
Add tests of this behaviour as well.

Add test coverage for slicing with "out of bounds" negative indices

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/expressions/test_gather.py

Pylibcudf calls the datatype accessor type(). Add tests to cover this case, and raising on out of bounds accesses.

Fix typo bug in gather implementation

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_union.py

Arguably this should be determined during query optimization by polars, but for now it is raised late during compute, so we must validate on our side.

Add test that diagonal concat with mismatching schemas raises

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/expressions/test_stringfunction.py

Additionally, assert that we raise during translation for an unhandled function.

Add tests of implemented StringFunctions

---

python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/tests/expressions/test_len.py

Fix bug (and report a polars issue) for the case that the dataframe is empty, and therefore we cannot ask a column for its length.

Add coverage selecting len from a dataframe (number of rows)

---

python/cudf/cudf/pandas/__init__.py

This PR addresses review comments made by @bdice here: https://github.com/rapidsai/cudf/pull/15628#pullrequestreview-2116067037

Refactor rmm usage in `cudf.pandas`

---

cpp/src/utilities/pinned_memory.cpp

This PR fixes a pool size alignment bug.

Fix the pool size alignment issue

---

.pre-commit-config.yaml
cpp/benchmarks/io/orc/orc_reader_multithreaded.cpp
cpp/tests/interop/from_arrow_test.cpp

The clang-tidy changes in #15894 introduce a new exclude regex list to the pre-commit clang-format hook. However, it was a single character too long, ending with a |. Consequently, the exclude regex matched the empty string, and hence excluded every C++ file.
Fix this, and apply formatting changes to the files that were modified in the interim and were not clang-format compatible.

Fix exclude regex in pre-commit clang-format hook

---

cpp/src/interop/to_arrow.cu

When converting an empty string view to arrow, we don't bother with copies from device, but rather create the arrow arrays directly. The offset buffer is therefore a singleton int32 array with zero in it.
Previously, the initialization of this array was incorrect, since mutable_data() returns a uint8_t pointer, and so setting the single element could leave 24 of the 32 bits uninitialized.
Fix this by using memset instead to zero out the full buffer.

Fix initialization error in to_arrow for empty string views

---

.github/workflows/pr_issue_status_automation.yml

This PR adds another condition to when we should run the automation work. PRs aren't always in the cuDF Python project so when this is the case we should skip the job rather than attempting to run it and have it throw an error.

Project automation update: skip if not in project

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/expressions/test_booleanfunction.py

Add tests covering BooleanFunction implementations.

Fix implemention of any, all, and isbetween

---

cpp/src/strings/case.cu
cpp/src/strings/replace/multi.cu
cpp/src/strings/split/split.cuh
cpp/src/text/tokenize.cu

in a few places, `thread_scope_block` is used even where there threads from multiple blocks update the same location. This PR changes these to `thread_scope_device` to avoid UB with sufficiently large inputs.
Have not ran benchmarks to evaluate the impact.

Fix `atomic_ref` scope when multiple blocks are updating the same output

---

cpp/benchmarks/join/conditional_join.cu

The current **JOIN_NVBENCH** uses three table sizes `1000, 100'000, 10'000'000` for all the **join** benchmarks.
But, **coditional** **joins** perform **X * Y** operations, and the large table size explodes the bench runtime. Hence we need to benchmark on smaller tables only.
This PR reduces **nvbench configurations** from **36** to **16** by using only two smaller table sizes `1000, 100'000` which lowers the overall benchmark runtime significantly.

Reduce conditional_join nvbench configurations

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/index.py
python/cudf/cudf/tests/test_index.py

1. Changed `Index.rename(inplace=False)` to shallow copy which matches pandas behavior. Let me know if there's a reason why we should deep copy here.
2. Made `RangeIndex.unique` return a shallow copy like pandas.
3. Made `Index.dropna` with no NA's shallow copy like pandas.

Reduce deep copies in Index ops

---

python/cudf_polars/tests/expressions/test_numeric_binops.py

Coverage of binops where one or both operands are a scalar

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/testing/asserts.py
python/cudf_polars/docs/overview.md
python/cudf_polars/tests/test_dataframescan.py
python/cudf_polars/tests/test_scan.py
python/cudf_polars/tests/testing/__init__.py
python/cudf_polars/tests/testing/test_asserts.py

Also assert that unsupported file scan operations raise.

Add basic tests of dataframe scan

---

cpp/src/io/text/byte_range_info.cpp

Fixes over allocated memory for range vector in `cudf::io::text::create_byte_range_infos_consecutive`

Fix memory size in create_byte_range_infos_consecutive

---

python/cudf_polars/tests/expressions/test_filter.py
python/cudf_polars/tests/test_filter.py

Note that expression filter with literals does not work because broadcasting is not implemented. It is also the case that the result could be computed without broadcasting in the case of scalars with some data introspection, but we do not do that here.

Add coverage for both expression and dataframe filter

---

python/cudf_polars/cudf_polars/utils/dtypes.py
python/cudf_polars/cudf_polars/utils/sorting.py
python/cudf_polars/pyproject.toml
python/cudf_polars/tests/expressions/test_datetime_basic.py
python/cudf_polars/tests/utils/test_dtypes.py
python/cudf_polars/tests/utils/test_sorting.py

The datetime conversion tests just test that we can round-trip correctly for now.

Add full coverage of utility functions

---

cpp/src/io/parquet/writer_impl.cu

The number of rows per fragment will be off by a factor of 4 for FIXED_LEN_BYTE_ARRAY columns. This results in many more fragments than are necessary to achieve user requested page size limits. This PR shifts where the determination of whether a column has fixed-width data to a location where knowledge of the schema can be used.

Account for FIXED_LEN_BYTE_ARRAY when calculating fragment sizes in Parquet writer

---

python/cudf/cudf/utils/_ptxcompiler.py

In some user environments, calling a subprocess may produce output that confuses the version parsing machinery inside `_ptxcompiler`. Since the affected functions are vendored from the real `ptxcompiler` package for the purposes of using them with CUDA 12, this fix will only these situations for CUDA 12+.
Closes https://github.com/rapidsai/cudf/issues/16016.

More safely parse CUDA versions when subprocess output is contaminated

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/expressions/test_rolling.py
python/cudf_polars/tests/test_groupby.py

Just raise for the rolling expressions for now since we have yet to implement them.

Extend coverage of groupby and rolling window nodes

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_dataframe.py

Before `ColumnAccessor.names` was modified with new column labels without the `ColumnAccessor._data` dict keys being modified. This could hide a subtle bug if one later uses `ColumnAccessor._data.keys()` to access column labels instead of `ColumnAccessor.names`

Prevent bad ColumnAccessor state after .sort_index(axis=1, ignore_index=True)

---

cpp/benchmarks/io/text/multibyte_split.cpp
cpp/src/io/text/data_chunk_source_factories.cpp

Changes the `cudf::io::text::multibyte_split()` function to use `std::ifstream::seekg()` to skip bytes instead of `std::ifstream::ignore()` for a file input source.
The `seekg()` function is significantly faster for large files.
Also fixed the multibyte-split benchmark to correctly access the chars buffer after generating an input strings column.

Improve multibyte-split byte-range performance

---

python/cudf/cudf/_lib/pylibcudf/join.pxd
python/cudf/cudf/_lib/pylibcudf/join.pyx
python/cudf/cudf/_lib/pylibcudf/libcudf/join.pxd
python/cudf/cudf/pylibcudf_tests/test_join.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_join.py

libcudf supports cross joins, but until now this wasn't exposed to python. Do that in pylibcudf and implement the evaluation rule in cudf-polars.

Expose and then implement support for cross joins in cudf-polars

---

docs/cudf/source/user_guide/api_docs/pylibcudf/index.rst
docs/cudf/source/user_guide/api_docs/pylibcudf/interop.rst
python/cudf/cudf/_lib/pylibcudf/table.pyx
python/cudf/cudf/pylibcudf_tests/test_table.py

There was a bug where Table.num_rows raised when we had 0 columns instead of returning 0.
I also added interop to the docs since that was missing.

Fix pylibcudf Table.num_rows for 0 columns case and add interop to docs

---

.github/workflows/pr.yaml
ci/test_cudf_polars.sh
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/typing/__init__.py
python/cudf_polars/tests/expressions/test_agg.py
python/cudf_polars/tests/expressions/test_booleanfunction.py
python/cudf_polars/tests/expressions/test_rolling.py
python/cudf_polars/tests/expressions/test_stringfunction.py
python/cudf_polars/tests/test_groupby.py
python/cudf_polars/tests/test_join.py
python/cudf_polars/tests/test_mapfunction.py
python/cudf_polars/tests/test_python_scan.py
python/cudf_polars/tests/test_union.py

They changed the semantics of join keys when those keys are expressions to more closely match SQL.
Dtype inference is also tighter, so update tests to adapt to those changes, and some other small deprecation warnings.
Finish the final missing coverage piece and turn on testing in CI (failing if we don't hit 100% coverage as well).

Adapt to polars upstream changes and turn on CI testing

---

python/cudf/cudf/core/multiindex.py
python/cudf/cudf/tests/test_repr.py

Additionally, this allows simplification in `MultiIndex.__repr__` which avoids a shallow copy and also caught a bug where `NaT` was not supposed to be quoted

Ensure MultiIndex.to_frame deep copies columns

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/expressions/test_booleanfunction.py

The missing nodes were `is_in`, `not` (both easy), `is_finite` and `is_infinite` (obtained by translating to `contains` calls).
While here, remove the implementation of `IsBetween` and just translate to an expression with binary operations. This removes the need for special-casing scalar arguments to `IsBetween` and reproducing the code for binop evaluation.

Finish implementation of cudf-polars boolean function handlers

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/expressions/test_when_then.py

A straightforward evaluation using `copy_if_else`.

Implement Ternary copy_if_else

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/algorithms.py
python/cudf/cudf/core/cut.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_dataframe.py

The `cudf.Index` constructor will shallow copy a `cudf.Index` input. Sometimes, we just need to make sure an input is a `cudf.Index`, so created `ensure_index` (pandas has something similar) so we don't shallow copy these inputs unnecessarily

Add ensure_index to not unnecessarily shallow copy cudf.Index

---

cpp/include/cudf/binaryop.hpp
cpp/src/binaryop/compiled/binary_ops.cuh
cpp/src/binaryop/compiled/util.cpp
cpp/tests/binaryop/binop-compiled-fixed_point-test.cpp

Some of the binary operators in cuDF don't work between fixed_point and floating-point numbers after [this earlier PR](https://github.com/rapidsai/cudf/pull/15438) removed the ability to construct and implicitly cast fixed_point numbers from floating point numbers. This PR restores that functionality by detecting and performing the necessary explicit casts, and adds tests for the supported operators. 
Note that the `binary_op_has_common_type` code is modeled after `has_common_type` found in traits.hpp. 
This closes [issue 16090](https://github.com/rapidsai/cudf/issues/16090)

Make binary operators work between fixed-point and floating args

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/utils/dtypes.py
python/cudf_polars/tests/expressions/test_literal.py
python/cudf_polars/tests/test_dataframescan.py

A query plan can contain a "literal" polars Series. Often, for example, when calling a contains-like function. To translate these, introduce a new `LiteralColumn` node to capture the concept and add an evaluation rule (converting from arrow).
Since list-dtype Series need the same casting treatment as in dataframe scan case, factor the casting out into a utility, and take the opportunity to handled casting of nested lists correctly.

Implement handlers for series literal in cudf-polars

---

cpp/cmake/thirdparty/get_cucollections.cmake
cpp/cmake/thirdparty/patches/cuco_noexcept.diff
cpp/cmake/thirdparty/patches/cuco_override.json

[cuco previously marked a number of methods as noexcept that can in fact throw exceptions](https://github.com/nvidia/cuCollections/issues/510). This causes problems for cudf functions that call these methods. The issue [was fixed in cuco upstream](https://github.com/NVIDIA/cuCollections/pull/511), but we cannot easily update to the latest commit of cuco, especially in a patch fix for 24.06. This PR instead adds a rapids-cmake patch for the cuco clone to address this issue. The patch may be removed once we update to a commit of cuco that contains the necessary fix.
Resolves #16059

Add patch for incorrect cuco noexcept clauses

---

cpp/src/join/conditional_join.cu
cpp/tests/join/conditional_join_tests.cu

Backports #16094 to 24.06 for inclusion in a hotfix release.

Backport: Fix segfault in conditional join (#16094)

---

cpp/include/cudf/ast/detail/operators.hpp

Backporting #16038 for a patch release.

Backport #16038 to 24.06

---

.pre-commit-config.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-122_arch-x86_64.yaml
dependencies.yaml

With the deployment of rapids-build-backend, we need to make sure our dependencies have alpha specs.

Use verify-alpha-spec hook

---

cpp/tests/ast/transform_tests.cpp

Backporting #16045 for a patch release.

Backport #16045 to 24.06

---

cpp/include/cudf/table/experimental/row_operators.cuh
cpp/include/cudf/table/table_view.hpp
cpp/src/table/table_view.cpp
cpp/tests/table/experimental_row_operator_tests.cu
cpp/tests/table/row_operator_tests_utilities.cu
cpp/tests/table/row_operator_tests_utilities2.cu

The `has_nested_columns` functionality is used in numerous tests. It looks like it should be part of our stable public API.

Promote has_nested_columns to cudf public API

---

.pre-commit-config.yaml

Because `verify-alpha-spec` potentially modifies `dependencies.yaml`, we want to run DFG after it. This should have been included in #16144 but was forgotten.

Run DFG after verify-alpha-spec

---

cpp/src/join/mixed_join.cu
cpp/src/join/mixed_join_semi.cu

This PR fixes a few places where certain code paths for mixed joins are not using the user-provided memory resource.

Use provided memory resource for allocating mixed join results.

---

cpp/tests/interop/from_arrow_stream_test.cpp

Fixes a debug build error reporting an unused return value in `from_arrow_stream_test.cpp`
```
g++ -DFMT_HEADER_ONLY=1 -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DNANOARROW_DEBUG -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DSPDLOG_FMT_EXTERNAL -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_DISABLE_ABI_NAMESPACE -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_IGNORE_ABI_NAMESPACE_ERROR -I/cudf/cpp -I/cudf/cpp/src -I/cudf/cpp/build/_deps/dlpack-src/include -I/cudf/cpp/build/_deps/jitify-src -I/cudf/cpp/include -I/cudf/cpp/build/include -I/cudf/cpp/build/_deps/cccl-src/thrust/thrust/cmake/../.. -I/cudf/cpp/build/_deps/cccl-src/libcudacxx/lib/cmake/libcudacxx/../../../include -I/cudf/cpp/build/_deps/cccl-src/cub/cub/cmake/../.. -I/cudf/cpp/build/_deps/nanoarrow-src/src …
```

Fix unused-return-value debug build error in from_arrow_stream_test.cpp

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/common/benchmark_utilities.cpp
cpp/benchmarks/common/benchmark_utilities.hpp
cpp/benchmarks/common/nvbench_utilities.cpp
cpp/benchmarks/common/nvbench_utilities.hpp
cpp/benchmarks/common/table_utilities.cpp
cpp/benchmarks/common/table_utilities.hpp
cpp/benchmarks/reduction/anyall.cpp
cpp/benchmarks/reduction/dictionary.cpp
cpp/benchmarks/reduction/minmax.cpp
cpp/benchmarks/reduction/rank.cpp
cpp/benchmarks/reduction/reduce.cpp
cpp/benchmarks/reduction/scan.cpp
cpp/benchmarks/reduction/scan_structs.cpp

This PR addresses https://github.com/rapidsai/cudf/issues/13735 for reduction benchmarks. There are 3 new utils added.
- `int64_t estimate_size(cudf::table_view)` returns a size estimate for the given table. https://github.com/rapidsai/cudf/pull/13984 was a previous attempt to add a similar utility, but this implementation uses `cudf::row_bit_count()` as suggested in https://github.com/rapidsai/cudf/pull/13984#issuecomment-2189916570 instead of manually estimating the size.
- `void set_items_processed(State& state, int64_t items_processed_per_iteration)` is a thin wrapper of `State.SetItemsProcessed()`. This wrapper takes `items_processed_per_iteration` as a parameter instead of `total_items_processed`. This could be useful to avoid repeating `State.iterations() * …

Add throughput metrics for REDUCTION_BENCH/REDUCTION_NVBENCH benchmarks

---

ci/run_cudf_polars_pytests.sh
ci/test_cudf_polars.sh

Adds environment-agnostic `ci/run_cudf_polars_pytest.sh` script, similar to the scripts added in https://github.com/rapidsai/cudf/pull/14992.

Add environment-agnostic `ci/run_cudf_polars_pytest.sh`

---

python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/test_groupby.py

Polars default dtypes for some aggregations, particularly count, don't match ours, so insert casts.

Cast count aggs to correct dtype in translation

---

python/cudf_polars/cudf_polars/callback.py
python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_union.py

These catch a few more edge cases.

Some small fixes in cudf-polars

---

python/cudf/cudf/core/column/lists.py
python/cudf/cudf/tests/test_list.py

The offset column of a nested empty list column may be empty as discussed in https://github.com/rapidsai/cudf/issues/16164. `ListColumn.memory_usage` assumed that this column was non-empty
Unblocks https://github.com/rapidsai/cuspatial/pull/1400

Fix `memory_usage` when calculating nested list column

---

python/cudf/cudf/_lib/pylibcudf/libcudf/lists/reverse.pxd
python/cudf/cudf/_lib/pylibcudf/lists.pxd
python/cudf/cudf/_lib/pylibcudf/lists.pyx
python/cudf/cudf/pylibcudf_tests/test_lists.py

Migrate lists/modifying to pylibcudf

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/expressions/test_datetime_basic.py
python/cudf_polars/tests/expressions/test_round.py
python/cudf_polars/tests/expressions/test_unique.py
python/cudf_polars/tests/test_groupby.py

Implement translation for some unary functions and a single datetime extraction

---

cpp/include/cudf/strings/replace.hpp
cpp/src/strings/replace/multi.cu
cpp/tests/strings/replace_tests.cpp

Fixes logic in `cudf::strings::replace_multiple` to ignore empty targets correctly in the `replace_multi_fn` functor.
Also updated the doxygen and added a gtest for this case.

Fix cudf::strings::replace_multiple hang on empty target

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-122_arch-x86_64.yaml
conda/recipes/cudf/conda_build_config.yaml
conda/recipes/cudf_kafka/conda_build_config.yaml
conda/recipes/libcudf/conda_build_config.yaml
dependencies.yaml
python/cudf/pyproject.toml
python/cudf_kafka/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/80
Adds constraints to avoid pulling in CMake 3.30.0, for the reasons described in that issue.

skip CMake 3.30.0

---

cpp/CMakeLists.txt

We must define `CUDA_API_PER_THREAD_DEFAULT_STREAM` for the stream hook lib, since `cudaLaunchKernel` in CUDA 12.4+ is now a macro that expands to a different function when it's not defined.

Define PTDS for the stream hook libs

---

cpp/src/interop/to_arrow.cu

Add single offset to an empty ListArray in cudf::to_arrow

---

cpp/cmake/thirdparty/patches/cccl_override.json

While upgrading CCCL, we ran into a test failure in cuSpatial. We added a patch to revert some changes from CCCL but the root cause was a bug in cuSpatial. I have fixed that bug here: https://github.com/rapidsai/cuspatial/pull/1402
Once that PR is merged, we can remove this CCCL patch.
See also:
- rapids-cmake patch removal: https://github.com/rapidsai/rapids-cmake/pull/640
- Original rapids-cmake patch: https://github.com/rapidsai/rapids-cmake/pull/511
- CCCL epic to remove RAPIDS patches: https://github.com/NVIDIA/cccl/issues/1939

Remove CCCL patch for PR 211.

---

python/cudf/cudf/_lib/csv.pyx
python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/test_scan.py

Previously we were just relying on the default cudf read_csv options which doesn't do the right thing if the user has configured things.
Now that polars passes through the information to us, we can handle things properly, and raise for unsupported cases.
While here, update to new polars release and adapt tests to bug fixes that have been made upstream.

Handler csv reader options in cudf-polars

---

cpp/src/io/parquet/decode_fixed.cu

Dictionary support for this particular flavor of kernel was being compiled in. Harmless, but caused an unneeded increase in shared memory usage.  This PR disables it.

Disable dict support for split-page kernel in the parquet reader.

---

cpp/include/cudf/io/csv.hpp
cpp/include/cudf/io/detail/csv.hpp
cpp/include/cudf/io/detail/json.hpp
cpp/include/cudf/io/json.hpp
cpp/src/io/csv/writer_impl.cu
cpp/src/io/functions.cpp
cpp/src/io/json/write_json.cu
cpp/tests/io/json_test.cpp
cpp/tests/io/json_writer.cpp

Remove `mr` param from `write_csv` and `write_json`

---

python/cudf/cudf/pandas/_wrappers/pandas.py
python/cudf/cudf/pandas/fast_slow_proxy.py
python/cudf/cudf_pandas_tests/test_cudf_pandas.py

Add custom name setter and getter for proxy objects in `cudf.pandas`

---

cpp/include/cudf_test/column_wrapper.hpp
cpp/tests/io/orc_test.cpp
cpp/tests/io/parquet_v2_test.cpp
cpp/tests/reshape/interleave_columns_tests.cpp
cpp/tests/streams/io/csv_test.cpp
cpp/tests/streams/io/orc_test.cpp
cpp/tests/streams/io/parquet_test.cpp

The `cudf::test::fixed_width_column_wrapper` supports all fixed-width type including fixed-point types. However, there is no mechanism to specify the fixed-point scale value which is common for the entire column and stored in the column's type.
This fixes the case by throwing an error if a non-zero scale is specified for the input values in a fixed-point `fixed_width_column_wrapper` instance. 
Also fixed several tests that incorrectly specified a non-zero scale. 
Closes #16092

Allow only scale=0 fixed-point values in fixed_width_column_wrapper

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/tools/datetimes.py

`Column.as_string/datetime/timedelta_column` had a `format` argument that was not used for columns that weren't these types or didn't require conversion to these types.
This PR introduces a `strftime` and `strptime` on the column that will handle this `format` argument.

Add Column.strftime/strptime instead of overloading `as_string/datetime/timedelta_column`

---

cpp/include/cudf/detail/unary.hpp
cpp/include/cudf/unary.hpp
cpp/src/unary/cast_ops.cu
python/cudf/cudf/_lib/pylibcudf/libcudf/unary.pxd
python/cudf/cudf/_lib/pylibcudf/unary.pxd
python/cudf/cudf/_lib/pylibcudf/unary.pyx
python/cudf/cudf/pylibcudf_tests/test_unary.py

In cudf-polars we need to check if a cast between two datatypes is supported (and fallback, or generate different code if not).
Let's ask libcudf to be the source of truth for when a cast is supported.

Expose reflection to check if casting between two types is supported

---

python/cudf/cudf/pylibcudf_tests/common/utils.py
python/cudf/cudf/pylibcudf_tests/conftest.py
python/cudf/cudf/pylibcudf_tests/io/test_json.py

Don't just use random integers for every data type.
Decided not to use hypothesis since I don't think there's a good way to re-use the table across calls
(and I would like to keep the runtime of pylibcudf tests down).

Improve the test data for pylibcudf I/O tests

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/df_protocol.py

xref https://github.com/rapidsai/cudf/issues/16238
Mainly direct users to use `from_pandas` instead of `from_dataframe` if the user has a `pandas.DataFrame`

Add docstring for from_dataframe

---

cpp/tests/lists/contains_tests.cpp

Changes the `cpp/tests/lists/contains_test.cpp` to use `cudf::slice` instead of `cudf::detail::slice()`

Update contains_tests.cpp to use public cudf::slice

---

cpp/include/cudf/detail/distinct_hash_join.cuh
cpp/src/search/contains_table.cu
cpp/src/text/bpe/byte_pair_encoding.cuh
cpp/src/text/vocabulary_tokenize.cu

This is a follow-up of #15938. It removes the temporary workaround no longer needed after the cuco version bump.

Remove temporary functor overloads required by cuco version bump

---

python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/tests/test_binops.py
python/cudf/cudf/tests/test_doctests.py
python/cudf/cudf/tests/test_dtypes.py

Splitting out the non API changes from gh-15897, the Scalar API change is required for the tests to pass with NumPy 2, but almost all changes should be relatively straight forward here on their own.
(I will add inline comments.)
---
This PR does not fix integer comparisons, there are currently no tests that run into these.
xref: https://github.com/rapidsai/build-planning/issues/38

MAINT: Adapt to NumPy 2 promotion changes

---

python/cudf/cudf/_fuzz_testing/utils.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/scalar.py
python/cudf/cudf/core/tools/numeric.py
python/cudf/cudf/tests/test_binops.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_list.py
python/cudf/cudf/tests/test_scalar.py
python/cudf/cudf/utils/dtypes.py

It appears this was called when we already had a dtype object so can instead just simply check the .kind attribute

Replace is_datetime/timedelta_dtype checks with .kind checks

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/cut.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/tests/test_datetime.py

There are some cupy usages that don't seem _strictly_ necessary (generating starting data, array type conversion) in some APIs. IMO we should prefer using CPU data/the existing data structure/Column ops over cupy when possible
closes https://github.com/rapidsai/cudf/issues/12133

Type & reduce cupy usage

---

cpp/src/interop/to_arrow.cu

An empty list column need not have empty children, it just needs to have zero length. In this case, the offsets array will have zero length, and we need to create a temporary buffer.
Now that this branch runs, fix two errors in the construction of the arrow array:
1. The element type, if there are children, should be taken from the child array;
2. If the child arrays are empty, we must make an empty null array, rather than passing a null pointer as the values array, otherwise we hit a segfault inside arrow.
The previous fix in #16201 correctly handled the empty children case (except for point two), but not the first case, which we do here.
Since we we're previously going down this code path (child_arrays was never empty), we never hit the latent segfault from point two.

Fix logic in to_arrow for empty list column

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/utils/versions.py
python/cudf_polars/tests/test_scan.py

We decided we would attempt to support a range of versions back to 1.0. We'll test with oldest and newest versions we support. To facilitate, introduce some versioning constants.

Introduce version file so we can conditionally handle things in tests

---

python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/io/parquet.py
python/cudf/cudf/options.py
python/cudf/cudf/tests/test_json.py
python/cudf/cudf/tests/test_parquet.py

This PR disables low memory readers by default in `cudf.pandas` and instead gives a provision to enable them with dedicated options.

Introduce dedicated options for low memory readers

---

.devcontainer/cuda12.2-conda/devcontainer.json
.devcontainer/cuda12.2-pip/devcontainer.json
.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml
CONTRIBUTING.md
README.md
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml

This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.
Contributes to https://github.com/rapidsai/build-planning/issues/73

Build and test with CUDA 12.5.1

---

python/cudf_polars/tests/test_groupby.py

Fix tests for polars 1.2

---

cpp/scripts/sort_ninja_log.py

Removes xml support from the `sort_ninja_log.py` utility. The xml support was experimental for possible use with Jenkins reporting that never materialized.
This script is used in build.sh generally when running local builds.

Remove xml from sort_ninja_log.py utility

---

cpp/include/cudf/detail/utilities/cuda.cuh

Updates the `cudf::detail::grid_1d` to use `thread_index_type` instead of `int` and `size_type` for the number threads and blocks.
This has become important for launching kernels with more threads than max `size_type` total bytes for warp-per-row and thread-per-byte algorithms.

Update cudf::detail::grid_1d to use thread_index_type

---

cpp/include/cudf/fixed_point/fixed_point.hpp
cpp/include/cudf/fixed_point/floating_conversion.hpp

The decimal <--> floating conversion PR reduced the performance of some of the AST and BINARYOP kernels due to register pressure.  This removes the switches that are the primary source of the register pressure, falling back to the old ipow() method for 64bit and 128bit integers.

Remove decimal/floating 64/128bit switches due to register pressure

---

cpp/src/strings/split/split.cuh
cpp/tests/strings/split_tests.cpp

Fixes `cudf::strings::split_record` handling of an all empty strings column. This caused a kernel launch with no threads eventually reporting a CUDA error. A new gtest was added to check this condition and includes tests for `rsplit_record` as well.
Closes #16284

Fix split_record for all empty strings column

---

conda/recipes/cudf/meta.yaml
dependencies.yaml

Part of issue: https://github.com/rapidsai/build-planning/issues/82
Drop `{{ pin_compatible('numpy', max_pin='x') }}` as it is no longer needed. `numpy` has its own `run_exports`, which constraints `numpy` to an API compatible version. More details in issue: https://github.com/orgs/rapidsai/projects/132
So `cudf` now uses that in its recipe builds. Also update `requirements/run` to set the `numpy` lower bound to `1.23` as required by us.
Lastly add todo comments for NumPy 2 update lines.

Drop `{{ pin_compatible('numpy', max_pin='x') }}`

---

python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/utils/dtypes.py

There were a couple of dedicated functions in `python/cudf/cudf/utils/dtypes.py` specific to `.where` that could be subsumed by `Column.can_cast_safely`.
The minor downside is that we need to cast where's argument to a Column first, but IMO it's probably OK given the deduplication

Use Column.can_cast_safely instead of some ad-hoc dtype functions in .where

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_groupby.py

To do this, we just need to collect the appropriate aggregation information, and broadcast literals to the correct size.

Support Literals in groupby-agg

---

.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml

After updating everything to CUDA 12.5.1, use `shared-workflows@branch-24.08` again.
Contributes to https://github.com/rapidsai/build-planning/issues/73

Use workflow branch 24.08 again

---

python/cudf/cudf/_lib/pylibcudf/join.pyx
python/cudf/cudf/_lib/pylibcudf/libcudf/utilities/type_dispatcher.pxd
python/cudf/cudf/_lib/pylibcudf/types.pyx
python/cudf/cudf/_lib/types.pyx
python/cudf_polars/cudf_polars/containers/column.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_join.py

Unlike all other joins, polars provides an ordering guarantee for left joins. By default libcudf does not, so we need to order the gather maps in this case.
While here, because it requires another hard-coding of `int32` for something that should be `size_type`, expose `type_to_id` in cython and plumb it through.

Preserve order in left join for cudf-polars

---

python/cudf/cudf/_lib/reduce.pyx
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/numerical_base.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/tests/test_reductions.py

In terms of pandas alignment, this argument doesn't exist in reduction ops. Additionally, the same result can be easily achieved by calling `astype` after the operation, and it appears libcudf does not support any arbitrary casting to an output type.

Deprecate dtype= parameter in reduction methods

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/series.py

In pandas, this argument was deprecated in pandas 1.x and removed in pandas 2.x. xref https://github.com/pandas-dev/pandas/pull/33218
Looks like in cudf this argument was never implemented, so to align with pandas, I think it should be OK to just remove this argument

Remove squeeze argument from groupby

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/index.py
python/cudf/cudf/utils/dtypes.py

* Replace `min_scalar_type` with `min_signed_type` (the former just called the latter)
* Replace `numeric_normalize_types` with `find_common_dtype` followed by a column `astype`
* Removed `_NUMPY_SCTYPES` with just hardcoding the integer/floating types or using `np.integer`/`np.floating`

Clean unneeded/redudant dtype utils

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/series.py

I have a script that did some signature comparisons between `pandas.DataFrame` and `cudf.DataFrame` API and it appears some signatures have changed between the pandas 1.x and 2.x release. The API changes in this PR are mostly adding implementations or adding missing keyword argument (although they might not be implemented). The APIs affected are:
* `__init__`
* `__array__`
* `__arrow_c_stream__`
* `to_dict`
* `where`
* `add_prefix`
* `join`
* `apply`
* `to_records`
* `from_records`
* `unstack`
* `pct_change`
* `sort_values`
Marking as breaking as I ensured some added keywords are in the same positions as pandas and therefore might break users who are using purely positional arguments.

Align more DataFrame APIs with pandas

---

python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/join/_join_helpers.py
python/cudf/cudf/core/series.py
python/cudf/cudf/testing/testing.py
python/cudf/cudf/utils/dtypes.py

* `is_scalar` also handles cudf.Scalars which should be handled internally
* `issubdtype` can largely be replaced by checking the `.kind` attribute on the dtype

Replace np.isscalar/issubdtype checks with is_scalar/.kind checks

---

pyproject.toml
python/cudf/cudf/core/resample.py

Additionally breaks up the prior, single-line of `select` rules that are enabled.

Mark cudf._typing as a typing module in ruff

---

cpp/include/cudf/dictionary/dictionary_factories.hpp
cpp/src/dictionary/dictionary_factories.cu
cpp/tests/streams/dictionary_test.cpp

Add `stream` param to dictionary column factory functions. Partially solves #13744

Add missing `stream` param to dictionary factory APIs

---

cpp/include/cudf/lists/explode.hpp
cpp/include/cudf/lists/set_operations.hpp
cpp/src/lists/explode.cu
cpp/tests/streams/lists_test.cpp

Add `stream` param to list `explode*` APIs. Partially fixes https://github.com/rapidsai/cudf/issues/13744

Add `stream` param to list explode APIs

---

python/cudf/cudf/core/dataframe.py

This PR fixes docstring of `DataFrame.apply`

Fix docstring of `DataFrame.apply`

---

cpp/include/cudf/utilities/prefetch.hpp
cpp/src/column/column_view.cpp
cpp/src/utilities/prefetch.cpp

This PR addresses a comment requesting a rename of `PrefetchConfig` to `prefetch_config`.
See: https://github.com/rapidsai/cudf/pull/16020#discussion_r1686284151

Rename PrefetchConfig to prefetch_config.

---

cpp/src/io/parquet/reader.cpp
cpp/tests/io/parquet_chunked_reader_test.cu

This PR must merge in cudf 24.08 to avoid unhandled expections.
Gracefully CUDF_FAIL in chunked parquet reader when `skip_rows>0` which may result in runtime exceptions like segfaults or an infinite loop. See #16186 for more information.

Gracefully CUDF_FAIL when `skip_rows > 0` in Chunked Parquet reader

---

cpp/benchmarks/common/generate_input.cu
cpp/include/cudf/detail/gather.cuh
cpp/src/io/fst/agent_dfa.cuh
cpp/src/reductions/minmax.cu
java/src/main/native/src/aggregation128_utils.cu

`cub::If` has been deprecated and should not be used. There is a better alternative in `cuda::std::conditional_t`
`thrust::{binary, unary}_function` has been deprecated and does not serve a purpose similar to the removed `std::{binary, unary}_function`
Rather than relying on the type aliases one should use the `std::invoke` machinery

Fix some issues with deprecated / removed cccl facilities

---

cpp/include/cudf/interop.hpp
cpp/src/interop/to_arrow.cu
cpp/tests/interop/from_arrow_test.cpp
cpp/tests/interop/to_arrow_test.cpp
cpp/tests/streams/interop_test.cpp

In https://github.com/rapidsai/cudf/pull/16297, we deprecated the use of `to_arrow` in favour of `to_arrow_host` and `to_arrow_device`. However, the scalar detail overload of `to_arrow` used the public table overload. So we get a warning when compiling internal libcudf code. Fix this by using the detail API, and fix a bug along the way where we were not passing through the arrow memory resource.

Make C++ compilation warning free after #16297

---

python/custreamz/pyproject.toml

Noticed this warning in logs from #16183 
> _/python3.10/site-packages/setuptools/config/pyprojecttoml.py:70: _ToolsTypoInMetadata: Ignoring [tools.setuptools] in pyproject.toml, did you mean [tool.setuptools]?_
This fixes that.
Intentionally targeting this at 24.10.
This misconfiguration has been in `custreamz` since the 23.04 release ([git blame link](https://github.com/rapidsai/cudf/blame/e6d412cba7c23df7ee500c28257ed9281cea49b9/python/custreamz/pyproject.toml#L60)).
I think the only effect might be that some test files are included in wheels when we don't want to.
I don't think the fix for it needs to be rushed into 24.08.
I searched across RAPIDS in case this was copied from somewhere else... don't see any other instances of this typo that need to be fixed.

fix [tool.setuptools] reference in custreamz config

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/expressions/test_numeric_binops.py
python/cudf_polars/tests/expressions/test_stringfunction.py

Fixes a bug where numeric <-> string casts are not being properly rejected at the cudf-polars level.

Require fixed width types for casting in `cudf-polars`

---

cpp/cmake/thirdparty/get_thread_pool.cmake

cudf does not currently export any headers that depend on bs_thread_pool, and having it as a dependency is currently causing problems for consumers. Avoid exporting it since it's not needed.

Don't export bs_thread_pool

---

python/cudf/cudf/pandas/_wrappers/pandas.py

`ArrowStringArrayNumpySemantics` was newly added in 2.1: https://github.com/pandas-dev/pandas/blob/2.1.x/pandas/core/arrays/string_arrow.py#L488, so putting the proxy wrapper behind a version check for pandas 2.0.x compat
```ipython
In [1]: %load_ext cudf.pandas
In [2]: import pandas as pd
In [3]: pd.__version__
Out[3]: '2.0.0'
```

Gate ArrowStringArrayNumpySemantics cudf.pandas proxy behind version check

---

cpp/tests/CMakeLists.txt

The `STREAM_INTEROP_TEST` code was commented out in #16379 so the `compute-sanitizer` returns an error for this test in the nightly cpp-memcheck tests. https://github.com/rapidsai/cudf/actions/runs/10107041505/job/27950193878#step:9:62177
This PR comments out the empty test so it is not built. The test will be re-enabled in a future release when the deprecated functions are replaced.

Fix nightly memcheck error for empty STREAM_INTEROP_TEST

---

python/cudf/cudf/core/dtypes.py

`NumpyEADtype` is a 2.1.0+ change, this PR handles the missing attribute error in pandas-2.0

Fix a `pandas-2.0` missing attribute error

---

docs/cudf/source/user_guide/api_docs/groupby.rst
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/resample.py
python/cudf/cudf/tests/test_groupby.py

The following breaking APIs are affected:
* `apply`
* `transform`
* `describe`
The rest of the APIs are non-breaking and generally will raise a `NotImplementedError`

Align groupby APIs with pandas 2.x

---

cpp/include/cudf/detail/reshape.hpp
cpp/include/cudf/reshape.hpp
cpp/src/reshape/byte_cast.cu
cpp/src/reshape/interleave_columns.cu
cpp/src/reshape/tile.cu
cpp/tests/CMakeLists.txt
cpp/tests/streams/reshape_test.cpp

Adds `stream` parameter to reshape APIs:
- `cudf::interleave_columns`
- `cudf::tile`
- `cudf::byte_cast`
Found while working #15983

Add stream parameter to reshape APIs

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/window/ewm.py
python/cudf/cudf/core/window/rolling.py
python/cudf/cudf/tests/test_dropna.py

The API changes in this PR are mostly adding implementations or adding missing keyword argument (although they might not be implemented). The APIs affected are:
* `DataFrame.insert`
* `DataFrame.melt`
* `DataFrame.merge`
* `DataFrame.quantile`
* `DataFrame.cov`
* `DataFrame.corr`
* `DataFrame.median`
* `DataFrame.rolling`
* `DataFrame.resample`
* `DataFrame.dropna`
* `MultiIndex.from_tuple`
* `MultiIndex.from_frame`
* `MultiIndex.from_product`

Align misc DataFrame and MultiIndex methods with pandas 2.x

---

.github/workflows/pr_issue_status_automation.yml

Fixes some lingering references to `branch-24.08` in the `pr_issue_status_automation` CI workflow.
This was missed when new branches were cut because that file ends in `.yml` and `update-version.sh` was only modifying files ending in `.yaml`. The corresponding `update-version.sh` changes were made in #16183 and are already on 24.10 thanks to forward mergers.
https://github.com/rapidsai/cudf/blob/dc05a01f3fc0742c5fbbddd86a0f2007bfdc2050/ci/release/update-version.sh#L78
I checked like this, and don't see any other missed references:
```shell
git grep -E '24\.8|24\.08|0\.39'
```

update some branch references in GitHub Actions configs

---

cpp/include/cudf/utilities/prefetch.hpp
cpp/src/utilities/prefetch.cpp

This adds muti-thread support for `prefetch_config` getter and setter functions. This avoid the issue that the config map is corrupted in multi-thread environments.
Closes https://github.com/rapidsai/cudf/issues/16426.

Support thread-safe for `prefetch_config::get` and `prefetch_config::set`

---

cpp/benchmarks/fixture/benchmark_fixture.hpp
cpp/include/cudf_test/stream_checking_resource_adaptor.hpp
cpp/include/cudf_test/testing_main.hpp
java/src/main/native/src/RmmJni.cpp

This PR uses RMM memory resource adaptor constructors instead of factory functions. With CTAD, we do not need the factory and can use the constructor directly. The factory will be deprecated in https://github.com/rapidsai/rmm/pull/1626.

Use RMM adaptor constructors instead of factories.

---

python/cudf/cudf/tests/test_s3.py
python/dask_cudf/dask_cudf/io/parquet.py
python/dask_cudf/dask_cudf/io/tests/test_s3.py

Important follow-up to https://github.com/rapidsai/cudf/pull/16132
Without this PR, using `dask_cudf.read_parquet("s3://...", ...)` will result in loud deprecation warnings after `compute`/`persist` is called. This is because dask will always pass `NativeFile` objects down to cudf.
My fault for missing this earlier!

[Bug] Remove loud `NativeFile` deprecation noise for `read_parquet` from S3

---

docs/cudf/source/cudf_pandas/how-it-works.md

This PR adds user facing docs for rmm memory modes and prefetching.

Add about rmm modes in `cudf.pandas` docs

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/java/ai/rapids/cudf/HostColumnVector.java
java/src/main/java/ai/rapids/cudf/HostColumnVectorCore.java
java/src/main/java/ai/rapids/cudf/JCudfSerialization.java

Adds Java methods to ColumnView to allow copying of column data to host memory asynchronously.  This can be used to avoid many unnecessary stream synchronization when copying many columns to the host.

Add Java APIs to copy column data to host asynchronously

---

cpp/src/column/column_view.cpp
cpp/src/utilities/prefetch.cpp
python/cudf/cudf/pandas/__init__.py
python/cudf/cudf/pandas/__main__.py

This PR enables `cudf.pandas` managed memory prefetching in `cudf.pandas.install()`, to ensure that prefetching is enabled for all methods of enabling `cudf.pandas`.
I also fixed a bug in libcudf's prefetching logic, where it tried to compute the number of characters in a strings column view even if the string column view's data is `nullptr`. This errors, so we must avoid the `chars_size()` call and stop the prefetch attempt early.

Enable prefetching in cudf.pandas.install()

---

ci/run_cudf_memcheck_ctests.sh
cpp/tests/error/error_handling_test.cu
cpp/tests/identify_stream_usage/test_default_stream_identification.cu

Removes the checking for specific gtests in the `run_cudf_memcheck_ctests.sh` script. Each of those tests can check the `LIBCUDF_MEMCHECK_ENABLED` environment variable themselves.
This simplifies the script logic and may help with replacing this with ctest logic in the future.

Remove checking for specific tests in memcheck script

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/libcudf/conda_build_config.yaml
conda/recipes/libcudf/meta.yaml
dependencies.yaml

Without `flatbuffers` being added to the conda environment `libcudf` is being built in is causing the following build failures:
```
In file included from /nvme/0/pgali/cudf/cpp/src/io/parquet/arrow_schema_writer.cpp:26:
/nvme/0/pgali/cudf/cpp/src/io/parquet/ipc/Message_generated.h:6:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory
6 | #include <flatbuffers/flatbuffers.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Add `flatbuffers` to `libcudf` build

---

cpp/src/io/parquet/compact_protocol_reader.cpp

Fixes internal parquet_field_list subclass constructors capturing invalid this pointer when passing objects to std::make_tuple. The std::make_tuple usage creates a parameter object that is constructed, moved, and destroyed. The this pointer is captured during constructor call. The move constructor is called which creates its own separate this pointer (all member data is moved/copied appropriately). The original this pointer is invalidated by the following destructor. The lambda that was captured in the constructor no longer contains a valid this value in the final moved object.
This PR removes the dependency on the this pointer in the lambda and captures the vector reference instead which is preserved correctly in the object move. The ctor, move, dtor pattern occurs because of how …

Fix parquet_field_list read_func lambda capture invalid this pointer

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/libcudf/conda_build_config.yaml
conda/recipes/libcudf/meta.yaml
cpp/src/io/parquet/compact_protocol_reader.cpp
dependencies.yaml

Reference #16447 
Conflict file was dependencies.yaml.

Fix merge conflict for auto merge 16447

---

python/cudf/benchmarks/API/bench_dataframe.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/dataframe.py

https://github.com/rapidsai/cudf/pull/16277 removed a universal cast to a `cupy.array` in `_from_array`. Although the typing suggested this method should only accept `np.ndarray` or `cupy.ndarray`, this method is called on any object implementing the `__cuda_array_inferface__` or `__array_interface__` (e.g. `numba.DeviceArray`) which caused a performance regression in cuspatial https://github.com/rapidsai/cuspatial/issues/1413
closes #16434
```python
In [1]: import cupy, numba.cuda
In [2]: import cudf
In [3]: cupy_array = cupy.ones((10_000, 100))
In [4]: %timeit cudf.DataFrame(cupy_array)
3.88 ms ± 52 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [5]: %timeit cudf.DataFrame(numba.cuda.to_device(cupy_array))
3.99 ms ± 35.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops …
```

Ensure objects with __interface__ are converted to cupy/numpy arrays

---

python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/index.py

When we need to construct a column with a specific type, we do not need to go through the indirection of `build_column`, which matches a column subclass to a passed type, and instead construct directly from the class instead

Use explicit construction of column subclass instead of `build_column` when type is known

---

cpp/src/stream_compaction/distinct.cu

This PR fixes a small typo in the C++ code.

Fix typo in dispatch_row_equal.

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/test_scan.py

Adapts to IR changes in polars 1.4 and handles nrows/skiprows a little more correctly.

Adapt to IR changes in polars 1.4

---

cpp/include/cudf/io/text/multibyte_split.hpp
cpp/src/io/text/multibyte_split.cu

Removes overloaded `cudf::io::text::multibyte_split` API deprecated in 24.08 and is no longer needed.

Remove a deprecated multibyte_split API

---

cpp/include/cudf/io/detail/json.hpp
cpp/src/io/json/json_normalization.cu
cpp/src/io/json/read_json.cu
cpp/tests/io/json/json_quote_normalization_test.cpp
cpp/tests/io/json/json_whitespace_normalization_test.cu

This change updates json normalization calls (quote and whitespace normalization) to take owning buffer of device_buffer as input rather than device_uvector. It makes it easy to hand over a string_column's char buffer to normalization calls.

Update json normalization to take device_buffer

---

python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_sorting.py

Allow DataFrame.sort_values(by=) to select an index level

---

python/cudf/cudf/core/index.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/tests/test_datetime.py

xref https://github.com/rapidsai/cudf/issues/16507
`date_range` generates its dates via `range`, and the end of this range was calculated via `math.ceil((end - start) / freq)`. If `(end - start) / freq` did not produce a remainder, `math.ceil` would not correctly increment this value by `1` to capture the last date.
Instead, this PR uses `math.floor((end - start) / freq) + 1` to always ensure the last date is captured

Fix `date_range(start, end, freq)` when end-start is divisible by freq

---

python/cudf/cudf/core/multiindex.py
python/cudf/cudf/tests/test_multiindex.py

xref https://github.com/rapidsai/cudf/issues/16507

Preserve array name in MultiIndex.from_arrays

---

python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/tests/test_indexing.py

xref https://github.com/rapidsai/cudf/issues/16507
I would say this was a bug before because we would silently return a new DataFrame with just `len(set(column_labels))` when selecting by column. Now this operation raises since duplicate column labels are generally not supported.

Disallow indexing by selecting duplicate labels

---

java/src/main/java/ai/rapids/cudf/Table.java

Recently some JSON parsing was updated so lists could be returned as strings. This updates the java code so that when cleaning up the results to match the desired schema that it can handle corner cases associated with lists and structs properly.
Tests are covered in the Spark plugin, but I am happy to add some here if we really want to validate that part of this.

Update the java code to properly deal with lists being returned as strings

---

cpp/include/cudf/io/text/byte_range_info.hpp
cpp/src/io/text/byte_range_info.cpp
cpp/src/io/text/multibyte_split.cu

Adds `const` declarations to appropriate member functions in class `cudf::io::text::byte_range_info` and moves the ctor implementation to .cpp file.
This helps with using the `byte_range_info` objects in `const` variables and inside of `const` functions.
Found while working on #15983

Rework cudf::io::text::byte_range_info class member functions

---

.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml

This PR removes hardcoded Python versions from CI workflows. It is a prerequisite for dropping Python 3.9. See https://github.com/rapidsai/build-planning/issues/88.

Remove hardcoded versions from workflows.

---

cpp/src/strings/contains.cu
cpp/src/strings/count_matches.cu
cpp/src/strings/count_matches.hpp
cpp/src/strings/extract/extract_all.cu
cpp/src/strings/search/findall.cu
cpp/src/strings/split/split_re.cu

Removes `output_size` parameter from `cudf::strings::detail::count_matches` utility since the output size should equal the input size from the first parameter. This also removes an unnecessary `assert()` call. The parameter became unnecessary as part of the large strings work.

Remove unneeded output size parameter from internal count_matches utility

---

ci/cudf_pandas_scripts/pandas-tests/diff.sh

python 3.9 support was recently dropped in rapids, hence changing the python version to 3.10

Switch python version to `3.10` in `cudf.pandas` pandas test scripts

---

python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_series.py

xref https://github.com/rapidsai/cudf/issues/16507
Raising a `NotImplementedError` gives a chance for this work in `cudf.pandas`

Raise NotImplementedError for Series.rename that's not a scalar

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_replace.py

Since `cudf.Index` is list-like, passing this to `.replace` should act like replacing a list of values with a corresponding list of values.
Discovered while working on https://github.com/rapidsai/cuml/pull/6019

Fix `.replace(Index, Index)` raising a TypeError

---

python/dask_cudf/dask_cudf/backends.py

Namely:
* Avoiding `cudf.core` imports by checking public column `.dtype`s
* Using more straightforward cudf APIs to construct meta objects

Use more idomatic cudf APIs in dask_cudf meta generation

---

python/cudf/cudf/_lib/column.pyx
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/numerical_base.py

This PR makes `NumericalBaseColumn.__init__` and its subclasses strict putting restrictions on `data`, `dtype`, `size` and `children` so these columns cannot be constructed into to an invalid state. It also aligns the signature with the base class.
xref https://github.com/rapidsai/cudf/issues/16469

Make NumericalColumn.__init__ strict

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/timedelta.py

This PR makes Datetime/TimedeltaColumn.__init__ and its subclasses strict putting restrictions on data, dtype, size and children so these columns cannot be constructed into to an invalid state. It also aligns the signature with the base class.
xref https://github.com/rapidsai/cudf/issues/16469

Make Timedelta/DatetimeColumn.__init__ strict

---

python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/index.py

https://github.com/rapidsai/cudf/pull/16457 requires `NumericalColumn` to be constructed with `size`. It appears another PR got in after this PR was created so there are currently a few usages where `size` isn't passed in.

Ensure size is always passed to NumericalColumn

---

python/cudf/cudf/pandas/_wrappers/numpy.py

NumPy hid the `flagsobj` type into the `_core` module.  It may make sense for NumPy to put it somewhere less "private", but I think it is fine to consider this semi-private.
However, we need to avoid the deprecation warning (oddly, found in the cuml test suite, and not here).

MAINT: Adapt to numpy hiding flagsobject away

---

dependencies.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/33
Follow-up to #16299
This proposes some simplifications to `dependencies.yaml`. It's not intended to change any behavior.
* more use of YAML anchors for requirements that are intended to be identical to each other
* eliminating the `pylibcudf_build_dep` dependency group that was introduced in #16299, in favor of just tracking the `pylibcudf` build dependency alongside `cudf`'s `rmm` build dependency in the existing `build_python_cudf` group
- *(sorry I'd missed that in the review on #16299)*
I found myself starting to make similar changes in the PR breaking up these packages into more (splitting out a `libcudf` in #15483) and thought they'd be better as a standalone PR.

make more use of YAML anchors in dependencies.yaml

---

cpp/include/cudf/io/types.hpp
python/pylibcudf/pylibcudf/libcudf/io/types.pxd

The C++ I/O types were previously not specifying a base type despite the fact that the Cython code was relying on the base being an int32. This has apparently never bitten us before, but in theory this could go very wrong since it leaves the underlying type up to the compiler and if the C++ binary used something other than an int32 that would result in an ABI incompatibility with the Python build that would produce spurious results.
While fixing this, I also noticed that the Cython contained a number of erroneous (likely outdated) declarations. Since Cython extern declarations are simply an indicate to Cython of how to resolve a function call _if_ it appears in compiled Cython code, these were not causing any build failures because these were all unused APIs, so I removed them from the …

Fix C++ and Cython io types

---

cpp/include/cudf/io/json.hpp

This PR fixes a use after move in json header.
The fix simply shifts the attributes to access the object value before moving it.
Closes https://github.com/rapidsai/cudf/issues/16608

bug-fix: cudf/io/json.hpp use after move

---

cpp/include/cudf/ast/detail/expression_evaluator.cuh

This PR follows up on a request from @davidwendt in https://github.com/rapidsai/cudf/pull/15091#discussion_r1722183142.

Remove thrust::optional from expression evaluator

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/expressions/test_agg.py
python/cudf_polars/tests/testing/test_asserts.py

contributes to #16478
This implements "cum_min", "cum_max", "cum_prod", "cum_sum"
"cum_count" is not implemented for now, since there's no exact libcudf match (I imagine the non-grouped case is also not used that much but haven't checked).
I suppose we could implement it by creating a column of 1s and copying the null mask over, and doing a cum_sum on that.
Let me know if you want to try that.

Implement scan-based whole-frame aggregations for cudf-polars

---

ci/test_wheel_cudf_polars.sh

Removes unnecessary installation of `cudf` wheels in wheel testing for `cudf_polars`.
`cudf_polars` doesn't depend on `cudf`, and neither do its tests. However, right now it's downloading `cudf` during it's wheel tests. I mistakenly introduced that in #16575.
This introduced a race condition that could lead to CI failures whenever the `cudf` wheels aren't published yet by the time the `cudf_polars` tests. Because the `cudf_polars` wheel tests (rightly) do not wait for `cudf` wheels to be available:
https://github.com/rapidsai/cudf/blob/555734dee7a8fb10f50c8609a8e4fb2c025e6305/.github/workflows/pr.yaml#L154-L155
https://github.com/rapidsai/cudf/blob/555734dee7a8fb10f50c8609a8e4fb2c025e6305/.github/workflows/pr.yaml#L145-L146
Noticed this in #16611
```text
[rapids-download-from-s3] …
```

do not install cudf in cudf_polars wheel tests

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml

Proposes some additional cleanup in `dependencies.yaml`, for things I noticed while working through #15483.
* standardizes the naming of keys in the `files:` section for build dependencies
- *`py_build_{project}` = dependencies for the `[build-system]` table*
- *`py_rapids_build_{project}` = dependencies for the `[tool.rapids-build-backend]` table*
- *this is how it was done over most of the other repos in https://github.com/rapidsai/build-planning/issues/31, it was just missed because `cudf` was one of the first repos to add `rapids-build-backend`*
* removes the dependency on building `streamz` from latest source on GitHub
- *`custreamz` conda packages and wheels depend on packages for those, not this git dependency*
- https://github.com/rapidsai/cudf/blob/2f7d35435db2b5ed9ead96cf43e2a710 …

remove streamz git dependency, standardize build dependency names, consolidate some dependency lists

---

python/cudf_polars/cudf_polars/dsl/ir.py

The "invalid" placeholder column does not work with the experimental prefetching setup.

Use a key column rather than a placeholder for count agg

---

java/src/main/native/src/TableJni.cpp

This fixes an issue in JNI C++ code. In particular, during a function call, the two passing parameters are evaluated using an index value, but that index is modified during evaluating one of the parameters, leading to out-of-bound access when evaluating the other.

Fix function parameters with common dependency modified during their evaluation

---

docs/cudf/source/developer_guide/pylibcudf.md

This PR updates the pylibcudf dev guide with some more recent recommendations.

DOC: Refresh pylibcudf guide

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_groupby.py

Implement order preserving groupby in cudf-polars

---

cpp/src/rolling/jit/operation.hpp

I noticed from https://github.com/rapidsai/cudf/pull/16590#discussion_r1725842333 that there was one other file where `#pragma once` was not at the top. This PR fixes that.

Move pragma once in rolling/jit/operation.hpp.

---

cpp/cmake/thirdparty/get_gtest.cmake

This reverts commit ac42bc870a65d807784cae63e25b9e9ca788eb23.
We need to revert #16546 as it broke the gtest builds for cudf. Therefore gtests that actually fail wouldn't properly report an error but silently continue and report as passed.

Revert "Hide all gtest symbols in cudftestutil (#16546)"

---

cpp/benchmarks/groupby/group_max.cpp

This PR fixes a minor bug where the `num_aggregations` axis was missed when working on #16154.

Add the missing `num_aggregations` axis for `groupby_max_cardinality`

---

.github/workflows/build.yaml

Follow-up to #15483.
Contributes to https://github.com/rapidsai/build-planning/issues/33
Wheel publishing for `libcudf` is failing like this:
```text
Error:  File "./dist/*.whl" does not exist
```
([build link](https://github.com/rapidsai/cudf/actions/runs/10528569930/job/29176811683))
Because the `package-type` was not set to `cpp` in the `wheels-publish` CI workflow, and that workflow defaults to `python`. ([shared-workflows code link](https://github.com/rapidsai/shared-workflows/blob/157e9824e6e2181fca9aa5c4bea4defd4cc322b0/.github/workflows/wheels-publish.yaml#L23-L26)).
This fixes that, and makes that choice explicit for all wheel publishing jobs.
References for this `package-type` argument:
* https://github.com/rapidsai/shared-workflows/pull/209
* …

fix libcudf wheel publishing, make package-type explicit in wheel publishing

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_series.py

Preserve Series name in duplicated method.

---

cpp/CMakeLists.txt

This PR removes CMake code enabling the CUDA language if the testing component was requested.
Closes #16614

bug-fix: Don't enable the CUDA language if testing was requested when finding cudf

---

python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/tests/containers/test_dataframe.py

polars.from_arrow renames empty column names (see https://github.com/pola-rs/polars/issues/11632). This causes problems when round-tripping specially crafted dataframes. Avoid the problem by constructing the table with fake names and then renaming.

Correctly export empty column names in DataFrame.to_polars

---

cpp/benchmarks/reduction/minmax.cpp
cpp/benchmarks/reduction/reduce.cpp

Uses the `NVBENCH_DECLARE_TYPE_STRINGS` feature to produce readable type names in the nvbench output.
Example previous output for `cudf::timestamp_ms` would appear like this:
```
| cuda::std::__4::chrono::time_point<cuda::std::__4::chrono::system_clock, cuda::std::__4::chrono::duration<long, cuda::std::__4::ratio<1l, 1000l> > > | 100000 |  23840x | 25.138 us | 21.98% | 20.979 us |  9.54% | 4.767G |  38.134 GB/s |  4.38% |
```
Adding the nvbench name feature changes this to:
```
| cudf::timestamp_ms | 100000 |  24752x | 24.387 us | 21.58% | 20.208 us | 3.79% | 4.948G |  39.588 GB/s |  4.55% |
```

Use non-mangled type names in nvbench output

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/string/slice.cpp

Moves google-benchmark  for `cudf::strings::slice_strings` to nvbench.
This is to help measure performance improvements in follow on work for strings-slice.

Rework strings::slice benchmark to use nvbench

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_indexing.py

Discovered in https://github.com/rapidsai/cudf/pull/16652, `DataFrame.iloc/loc.__setitem__` with a non-cupy type e.g. `"category"` failed because the indexing path unconditionally tries to `cupy.asarray` the value to be set which only accepts types recognized by cupy.
We can skip this `asarray` if we have a numpy/pandas/cudf object

Fix loc/iloc.__setitem__[:, loc] with non cupy types

---

pyproject.toml
python/cudf/cudf/_typing.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/dtypes.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/udf/utils.py
python/cudf/cudf/io/parquet.py
python/cudf/cudf/options.py
python/cudf/cudf/pandas/fast_slow_proxy.py
python/cudf/cudf/utils/ioutils.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/typing/__init__.py
python/cudf_polars/pyproject.toml
python/dask_cudf/dask_cudf/io/json.py

Follow-up to #16637.
Once this project's minimum support Python version was bumped up to Python 3.10, `ruff` started raising this error from `pyupgrade`:
```text
Import from `collections.abc` instead: `Callable`
```
* ruff docs: https://docs.astral.sh/ruff/rules/deprecated-import/
* `typing` docs saying that `typing.Callable` is deprecated starting in Python 3.9 https://docs.python.org/3/library/typing.html#typing.Callable
* context: https://github.com/rapidsai/cudf/pull/16637#discussion_r1727482177
This proposes accepting that suggestion, so that `cudf` won't be broken whenever `Callable` is removed from the `typing` module.
Some of the imports added in this PR are put into `if TYPE_CHECKING` blocks because of this other error from `ruff`:
```text
TCH003 Move standard library import …
```

switch from typing.Callable to collections.abc.Callable

---

python/pylibcudf/pylibcudf/libcudf/interop.pxd

Replaces a single `device_memory_resource*` in pylibcudf Cython inline C++ function with `rmm::device_async_resource_ref` to help smooth RMM refactoring effort.

Replace raw device_memory_resource pointer in pylibcudf Cython

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/expressions/test_agg.py

Support `pl.Expr.quantile` in cudf-polars.

Support quantile in cudf_polars

---

python/cudf/cudf/core/column/__init__.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/index.py

To match pandas implementation, `interval_range` dispatches to `IntervalIndex.from_breaks` which allows some code deduplication. This also allows us to remove `column_empty_same_mask` which (luckily) I didn't find any usage across RAPIDS

Have interval_range use IntervalIndex.from_breaks, remove column_empty_same_mask

---

cpp/tests/error/error_handling_test.cu

Disables the `gtests/ERROR_TEST` when run under `compute-sanitizer` for memcheck. The `compute-sanitizer` started hanging on some of these tests. There is no value in running memcheck on any of the tests in `ERROR_TEST`

Disable gtests/ERROR_TEST during compute-sanitizer memcheck test

---

python/cudf/cudf/core/index.py
python/cudf/cudf/core/series.py

* Add more type annotations to `index.py`
* More consistently use `Index._from_column` where appropriate
* Remove single used `Index._indices_of` in favor of just accessing the `Column._indicies_of` method

Add type annotations to Index classes, utilize _from_column more

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/tests/test_series.py

In pandas 2.0, `to_frame(name=None)` allowed the resulting column name to be `None` https://github.com/pandas-dev/pandas/pull/45523
Looks like based on the current default of `cudf.Series.to_frame`, this behavior was not reflected.
Additionally, created a `SingleColumnFrame._to_frame` to more easily share the logic between `Series.to_frame` and `Index.to_frame`

Fix Series.to_frame(name=None) setting a None name

---

python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/tests/test_groupby.py

Since the full-frame `Agg` handler for first and last doesn't construct a request (because we can do it without a `from_scalar` call), we didn't handle these in a groupby context. Fortunately it is easy to add.

Implement handlers for first/last in groupby

---

.github/workflows/pr.yaml

`get-pr-info.outputs.base.sha` does not actually give the merge base, but merely the tip of the target branch. Calculate the merge base and pass it to the `changed-files` step.

Use merge base when calculating changed files

---

.github/workflows/build.yaml
.github/workflows/pr.yaml

Follow-up to #16650 and #15483.
`libcudf` wheels are identical (same content, same filename) across Python versions, but due to an oversight in the PRs linked above, we're currently building nightlies of them once per Python version supported by RAPIDS 😭 
You can see this on recent runs of the `build` workflow:
([build link](https://github.com/rapidsai/cudf/actions/runs/10627299703/job/29460218854))
This PR fixes that by applying the same matrix filter to `libcudf` nightly build jobs as is currently applied to PR jobs:
https://github.com/rapidsai/cudf/blob/5e420ff63ba2997a37bf5dfbfaa73c5f05225f9d/.github/workflows/pr.yaml#L195-L200

remove some unnecessary libcudf nightly builds

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/main/native/src/ColumnViewJni.cu
java/src/main/native/src/ColumnViewJni.hpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This depends on https://github.com/NVIDIA/spark-rapids/pull/11399
Essentially ifElse is faster than this API and this API is not safe to use generically.
https://github.com/NVIDIA/spark-rapids/issues/11397#issuecomment-2310570124
So I am removing it after replacing all calls to it with calls to `ifElse/cudf::copy_if_else`

Remove java ColumnView.copyWithBooleanColumnAsValidity

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/tests/test_scan.py

Although it is possible to construct an `EMPTY` column in libcudf, we can't do anything with it (even export it to arrow). This is the case even if the emptiness is part of a nested type. Previously we were not sufficiently diligent at noticing this case when translating polars queries, and would fail (with `abort`) at runtime in some cases.
Fix this by checking the unique set of dtypes in the schema of each query node and raising if any such dtype would be `EMPTY`.

No support for producing dataframes with Empty columns

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_groupby_dynamic.py

We are not yet exposing the actual information that the groupby is dynamic, but this catches a bunch of cases.

Partially reject dynamic groupby

---

python/cudf/cudf/_lib/text.pyx
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py
python/cudf/cudf/io/text.py

This modifies cases where `_from_column` provided the same logic or where 1 column was produced so `._from_column` was valid to use

Use Series._from_column more consistently to avoid validation

---

python/cudf_polars/cudf_polars/containers/column.py
python/cudf_polars/cudf_polars/dsl/expr.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/utils/dtypes.py
python/cudf_polars/tests/test_mapfunction.py

Add support for unpivoting a DataFrame. We raise for cases where the concatenation of the value columns produces a cast that is not supported by standard fixed-width unary casting.

Implement unpivot in cudf-polars

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_scan.py

Reject two more edge cases that we do not support.
We could easily support the case where the parquet read just needs to read the metadata, but it is low priority, so have not done so here.

Small scan-handler fixes

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py

This field renaming was due to a recent refactor in (as-yet-unreleased) polars 1.7.
Perhaps a safer option is that we hard-pin the release to 1.6.

Polars 1.7 will change a minor thing in the IR, adapt to that

---

.github/workflows/pr.yaml
ci/run_cudf_polars_polars_tests.sh
ci/test_cudf_polars_polars_tests.sh
ci/test_wheel_cudf_polars.sh
python/cudf_polars/cudf_polars/testing/plugin.py
python/cudf_polars/pyproject.toml

We implement a small pytest plugin that defaults the polars engine to GPU (by monkeypatching `LazyFrame.collect`, yet another reason to have a global default somehow).
As well as this, we collate all the known failures and classify them.

Run polars test suite (defaulting to GPU) in CI

---

ci/cudf_pandas_scripts/run_tests.sh

#16745 added support for Python 3.12 in this project.
When that was merged, nightly `unit-tests-cudf-pandas` jobs on Python 3.12 started failing, with errors from compiling `pandas`: ([build link](https://github.com/rapidsai/cudf/actions/runs/10733915866/job/29768130164))
That's only happening because we're running `pip install pandas==2.1` in those jobs, which matches exactly `pandas==2.1.0`, which does not have Python 3.12 wheels on PyPI (https://pypi.org/project/pandas/2.1.0/#files).
```text
Collecting pandas==2.1
Downloading pandas-2.1.0.tar.gz (4.3 MB)
```
`pandas==2.1.1` DOES have Python 3.12 wheels on PyPI (https://pypi.org/project/pandas/2.1.1/#files).
To fix those jobs, this proposes allowing the patch version of `pandas` installed in those CI jobs to float:
* before: `pip …

allow pandas patch version to float in cudf-pandas unit tests

---

python/cudf/cudf/_lib/csv.pyx
python/cudf/cudf/tests/test_csv.py

closes https://github.com/rapidsai/cudf/issues/16766
If the cudf `read_csv` behavior of always returning string column labels is long standing behavior, we can match the pandas behavior of returning integer column labels in `mode.pandas_compatible`

Allow read_csv(header=None) to return int column labels in `mode.pandas_compatible`

---

cpp/include/cudf/io/nvcomp_adapter.hpp
cpp/src/io/comp/nvcomp_adapter.cpp
cpp/src/io/comp/nvcomp_adapter.hpp
cpp/src/io/orc/writer_impl.cu
cpp/src/io/parquet/writer_impl_helpers.cpp
cpp/tests/io/comp/decomp_test.cpp

This PR removes the adapter code that allow running with older nvCOMP versions.
Feature status checking has been significantly simplified, and compile-time checks for newer compression types have been removed.
Also removed the fallback to the old version of get_temp_size, since we are now guaranteed to have access to the extended version.

Simplify the nvCOMP adapter

---

docs/cudf/source/user_guide/api_docs/pylibcudf/index.rst
docs/cudf/source/user_guide/api_docs/pylibcudf/labeling.rst

Follow up to https://github.com/rapidsai/cudf/pull/16761, I forgot to add the doc pages for the labeling pylibcudf APIs

Add labeling pylibcudf doc pages

---

cpp/benchmarks/hashing/hash.cpp

Fixes the `sha512` output for nvbench for `GlobalMem BW`.
Previously:
```
|    65536 |     0 | sha512 |   1216x | 417.898 us |  1.40% | 412.669 us | 0.61% |     24.139 GB/s |           3.14% |
| 16777216 |     0 | sha512 |     11x |  71.392 ms |  0.03% |  71.387 ms | 0.03% | 258404.649 PB/s | 33642233417.78% |
|    65536 |   0.1 | sha512 |   1184x | 433.031 us |  1.58% | 427.815 us | 1.01% |     22.919 GB/s |           2.98% |
| 16777216 |   0.1 | sha512 |     11x |  73.457 ms |  0.03% |  73.452 ms | 0.03% | 251140.174 PB/s | 32696456458.71% |
```
Fixed integer overflow calculation:
```
|    65536 |     0 | sha512 |   1200x | 423.838 us |  1.42% | 418.561 us | 0.66% |  23.799 GB/s |  3.10% |
| 16777216 |     0 | sha512 |     11x |  72.773 ms |  0.11% |  72.767 ms | 0.11% |  35.041 GB/s | …
```

Fix nvbench output for sha512

---

cpp/include/cudf/detail/tdigest/tdigest.hpp
cpp/include/cudf_test/tdigest_utilities.cuh
cpp/src/quantiles/tdigest/tdigest.cu
cpp/src/quantiles/tdigest/tdigest_aggregation.cu
cpp/tests/groupby/tdigest_tests.cu
cpp/tests/quantiles/percentile_approx_test.cpp

This PR reverts #16675, which has introduced another bug. Our nightly CI pipeline is failing because of this bug (https://github.com/NVIDIA/spark-rapids/issues/11463). I can reproduce the bug within a libcudf unit test. I will make another PR to fix both the original issue and the new bug.

Revert "Fix empty cluster handling in tdigest merge (#16675)"

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java

Exposes ColumnVector's fromViewWithContiguousAllocation method so code outside of cudf that builds contiguous table views can expose those columns in Java.

Java: Make ColumnVector.fromViewWithContiguousAllocation public

---

java/src/main/java/ai/rapids/cudf/ParquetWriterOptions.java
java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

Adds the ability to set the max # rows per row group and max # bytes per row group for parquet files.

Add ability to set parquet row group max #rows and #bytes in java

---

dependencies.yaml

Uses cupy 12.2.0 as oldest dependency pinning on ARM to ensure CUDA 12 support.
This will fix nightly CI failures that look like:
```
LibMambaUnsatisfiableError: Encountered problems while solving:
- package cupy-12.0.0-py311h308989c_2 requires python_abi 3.11.* *_cp311, but none of the providers can be installed
Could not solve for environment specs
The following packages are incompatible
├─ cuda-version 12.2**  is installable and it requires
│  └─ cudatoolkit 12.2|12.2.* , which can be installed;
├─ cupy 12.0.0  is installable with the potential options
│  ├─ cupy 12.0.0 would require
│  │  └─ cudatoolkit >=11.2,<12 , which conflicts with any installable versions previously reported;
...
```

Use cupy 12.2.0 as oldest dependency pinning on CUDA 12 ARM

---

cpp/benchmarks/io/parquet/parquet_reader_multithread.cpp

Closes #16758
This PR adds an `io_type` axis to the benchmarks in `PARQUET_MULTITHREAD_READER_NVBENCH` with `PINNED_BUFFER` as default value. More description at #16758.

Add io_type axis with default `PINNED_BUFFER` to nvbench PQ multithreaded reader

---

.github/workflows/pr.yaml

There are two implementations of the same action; one in [rapidsai/shared-actions](https://github.com/rapidsai/shared-actions/tree/main/get-pr-info) and [the other](https://github.com/nv-gha-runners/get-pr-info) in the nv-gha-runners org. This PR switches to the implementation in the nv-gha-runners group in order to keep a single source of truth.
Tested in https://github.com/rapidsai/cudf/actions/runs/10906617425/job/30268277178?pr=16819#step:4:5

use get-pr-info from nv-gha-runners

---

.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml

All RAPIDS libraries have been updated with Python 3.12 support, so Python 3.12 changes
have been merged into `branch-24.10` of `shared-workflows`: https://github.com/rapidsai/shared-workflows/pull/213
This updates GitHub Actions configs here to that branch.

Use CI workflow branch 'branch-24.10' again

---

cpp/benchmarks/CMakeLists.txt

Renames the NDS-H benchmark binaries with 0 prefixes for better lexicographical sorting

Rename the NDS-H benchmark binaries

---

cpp/include/cudf/detail/aggregation/aggregation.hpp

This PR fixes several documentation issues uncovered while working on #16619. There are no actual code changes.

Improve aggregation documentation

---

docs/cudf/source/user_guide/api_docs/pylibcudf/strings/index.rst
docs/cudf/source/user_guide/api_docs/pylibcudf/strings/repeat.rst
python/cudf/cudf/_lib/strings/repeat.pyx
python/pylibcudf/pylibcudf/libcudf/strings/repeat.pxd
python/pylibcudf/pylibcudf/strings/CMakeLists.txt
python/pylibcudf/pylibcudf/strings/__init__.py
python/pylibcudf/pylibcudf/strings/repeat.pxd
python/pylibcudf/pylibcudf/strings/repeat.pyx
python/pylibcudf/pylibcudf/tests/test_string_repeat.py

Add string.repeats API to pylibcudf

---

python/cudf/cudf/_lib/strings/contains.pyx
python/pylibcudf/pylibcudf/libcudf/strings/contains.pxd
python/pylibcudf/pylibcudf/strings/contains.pxd
python/pylibcudf/pylibcudf/strings/contains.pyx
python/pylibcudf/pylibcudf/tests/test_string_contains.py

Add string.contains APIs to pylibcudf

---

python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/reshape.py

`MultiIndex._poplevel`, which backs `MultiIndex.droplevel`, operates by dropping a given level inplace. There 2 places where `._poplevel` is called, and both usages makes a shallow copy of the data first, presumably to work around side effects of this inplace behavior.
This PR remove the `MultiIndex._poplevel` implementation and just implements dropping level like behavior by just returning a new object.

Remove `MultiIndex._poplevel` inplace implementation.

---

cpp/src/utilities/stream_pool.cpp

The NVbench application `PARQUET_READER_NVBENCH` in libcudf currently crashes with the segmentation fault. To reproduce:
```
./PARQUET_READER_NVBENCH -d 0 -b 1 --run-once -a io_type=FILEPATH -a compression_type=SNAPPY -a cardinality=0 -a run_length=1
```
The root cause is that some (1) `thread_local`  objects on the main thread in `libcudf` and (2) `static` objects in `kvikio` are destroyed after `cudaDeviceReset()` in NVbench and upon program termination. These objects should simply be leaked, since their destructors making CUDA calls upon program termination constitutes UB in CUDA.
This simple PR is the cuDF side of the fix. The other part is done here https://github.com/rapidsai/kvikio/pull/462.
closes #13229

Intentionally leak thread_local CUDA resources to avoid crash (part 1)

---

cpp/src/join/join_common_utils.hpp
cpp/src/join/mixed_join_common_utils.cuh
cpp/src/join/mixed_join_kernels_semi.cu
cpp/src/join/mixed_join_kernels_semi.cuh
cpp/src/join/mixed_join_semi.cu
cpp/tests/join/mixed_join_tests.cu

Reverting rapidsai/cudf#16230 as this PR leads to https://github.com/rapidsai/cudf/issues/16852.

Revert "Refactor mixed_semi_join using cuco::static_set"

---

cpp/benchmarks/common/ndsh_data_generator/table_helpers.cpp
cpp/benchmarks/ndsh/utilities.cpp
cpp/examples/parquet_io/parquet_io.cpp
cpp/include/cudf/join.hpp
cpp/src/join/conditional_join.cu
cpp/src/join/conditional_join.hpp
cpp/src/join/cross_join.cu
cpp/src/join/join.cu
cpp/src/join/mixed_join.cu
cpp/src/join/mixed_join_semi.cu
cpp/src/join/semi_join.cu
cpp/tests/CMakeLists.txt
cpp/tests/join/join_tests.cpp
cpp/tests/join/semi_anti_join_tests.cpp
cpp/tests/streams/join_test.cpp

Adds stream ordering to the public join APIs:
- `inner_join`
- `left_join`
- `full_join`
- `left_semi_join`
- `left_anti_join`
- `cross_join`
- `conditional_inner_join`
- `conditional_left_join`
- `conditional_full_join`
- `conditional_left_semi_join`
- `conditional_left_anti_join`
- `mixed_inner_join`
- `mixed_left_join`
- `mixed_full_join`
- `mixed_left_semi_join`
- `mixed_left_anti_join`
- `mixed_inner_join_size`
- `mixed_left_join_size`
- `conditional_inner_join_size`
- `conditional_left_join_size`
- `conditional_left_semi_join_size`
- `conditional_left_anti_join_size`
closes #16792 
follows up https://github.com/rapidsai/cudf/issues/13744

Exposed stream-ordering to join API

---

.github/labeler.yml

The labeler was not updated for the move of pylibcudf to a separate package.

Update labeler for pylibcudf

---

cpp/include/cudf/datetime.hpp
cpp/include/cudf/detail/datetime.hpp
cpp/include/cudf/detail/timezone.hpp
cpp/include/cudf/timezone.hpp
cpp/src/datetime/datetime_ops.cu
cpp/src/datetime/timezone.cpp
cpp/tests/CMakeLists.txt
cpp/tests/streams/datetime_test.cpp

This merge request exposes stream-ordering to the public-facing datetime APIs.
- `extract_year`
- `extract_month`
- `extract_day`
- `extract_weekday`
- `extract_hour`
- `extract_minute`
- `extract_second`
- `extract_millisecond_fraction`
- `extract_microsecond_fraction`
- `extract_nanosecond_fraction`
- `last_day_of_month`
- `day_of_year`
- `add_calendrical_months`
- `is_leap_year`
- `days_in_month`
- `extract_quarter`
- `ceil_datetimes`
- `floor_datetimes`
- `round_datetimes`
Follows-up https://github.com/rapidsai/cudf/issues/13744
Closes https://github.com/rapidsai/cudf/issues/16775

Exposed stream-ordering to datetime API

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
docs/cudf/source/cudf_polars/index.rst

This PR improves the docs by reducing the size of the Polars heading (too many words) and tightening up the writing of the docs page.

Improve Polars docs

---

python/cudf/cudf/tests/pytest.ini

This PR ignores numba warnings that are showing up in arm runners: https://github.com/numba/numba/issues/6589#issuecomment-748595076

Ignore numba warning specific to ARM runners

---

java/src/main/java/ai/rapids/cudf/JSONOptions.java
java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

This is a back-port of #16867 to 24.10.

Add in support for setting delim when parsing JSON through java (#16867)

---

build.sh

This CMake option was removed by #15483.

Remove unnecessary flag from build.sh

---

python/dask_cudf/dask_cudf/expr/_collection.py
python/dask_cudf/dask_cudf/expr/_expr.py
python/dask_cudf/dask_cudf/tests/test_core.py

See https://github.com/rapidsai/cudf/issues/16895
Closes https://github.com/rapidsai/cudf/issues/16892
Dask-expr uses `rename_axis`, which is not supported by cudf yet. This is a temporary workaround until #16895 is resolved.

Add dask-cudf workaround for missing `rename_axis` support in cudf

---

.github/workflows/pr.yaml
ci/release/update-version.sh
ci/test_cudf_polars_polars_tests.sh
docs/dask_cudf/source/best_practices.rst

Fixes forward merge into 24.12. Some 24.10 references were left behind.

Fix 24.10 to 24.12 forward merge

---

python/cudf/cudf/_lib/aggregation.pyx
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

closes https://github.com/rapidsai/cudf/issues/16861

Respect groupby.nunique(dropna=False)

---

docs/dask_cudf/source/best_practices.rst
docs/dask_cudf/source/conf.py
docs/dask_cudf/source/index.rst

More follow-up fixes to the recent Dask-cuDF documentation additions.

Fix links in Dask cuDF documentation

---

cpp/src/strings/search/findall.cu
cpp/tests/strings/findall_tests.cpp

Fixes `cudf::strings::findall` error when passed an empty input column.
Also adds a gtest for empty input and for all-rows do not match case.

Fix cudf::strings::findall error with empty input

---

cpp/tests/copying/copy_tests.cpp
cpp/tests/filling/sequence_tests.cpp
cpp/tests/groupby/collect_list_tests.cpp
cpp/tests/interop/dlpack_test.cpp
cpp/tests/io/orc_test.cpp
cpp/tests/io/parquet_chunked_writer_test.cpp
cpp/tests/io/parquet_common.cpp
cpp/tests/io/parquet_misc_test.cpp
cpp/tests/io/parquet_reader_test.cpp
cpp/tests/io/parquet_v2_test.cpp
cpp/tests/io/parquet_writer_test.cpp
cpp/tests/json/json_tests.cpp
cpp/tests/reductions/reduction_tests.cpp
cpp/tests/reductions/scan_tests.cpp
cpp/tests/rolling/nth_element_test.cpp
cpp/tests/streams/transform_test.cpp
cpp/tests/strings/chars_types_tests.cpp
cpp/tests/strings/contains_tests.cpp
cpp/tests/strings/durations_tests.cpp
cpp/tests/strings/extract_tests.cpp
cpp/tests/strings/findall_tests.cpp
cpp/tests/transform/integration/unary_transform_test.cpp

Subset of improvements to the code base proposed by the latest version of clang-tidy.
**Note to reviewers**: The changeset looks deceptively large. Almost all of the change are really just switching from raw C-style arrays to C++ std::arrays.

clang-tidy fixes part 3

---

cpp/src/datetime/timezone.cpp
cpp/src/dictionary/dictionary_column_view.cpp
cpp/src/interop/dlpack.cpp
cpp/src/io/avro/avro.cpp
cpp/src/io/avro/avro.hpp
cpp/src/io/comp/uncomp.cpp
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/jit/parser.cpp
cpp/src/strings/regex/regcomp.cpp
cpp/src/utilities/stream_pool.cpp

Subset of improvements to the code base proposed by the latest version of clang-tidy.

clang-tidy fixes part 2

---

cpp/tests/large_strings/json_tests.cu

Fixes the `unsetenv` to use `LIBCUDF_JSON_BATCH_SIZE`

Fix JsonLargeReaderTest.MultiBatch use of LIBCUDF_JSON_BATCH_SIZE env var

---

cpp/.clang-tidy
cpp/include/cudf/io/parquet.hpp
cpp/include/cudf_test/type_list_utilities.hpp
cpp/src/io/functions.cpp
cpp/src/io/utilities/output_builder.cuh
cpp/tests/ast/transform_tests.cpp
cpp/tests/binaryop/util/operation.h
cpp/tests/groupby/mean_tests.cpp
cpp/tests/io/json/json_test.cpp
cpp/tests/io/parquet_common.hpp
cpp/tests/io/text/multibyte_split_test.cpp

With the last few clang-tidy PRs merged, clang-tidy now completes successfully enough that autofixes work again. This is the result of an autofix pass.

Apply clang-tidy autofixes

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_groupby.py

When we are requested to maintain order in groupby aggregations we must post-process the result by computing a permutation between the wanted order (of the input keys) and the order returned by the groupby aggregation. To do this, we can perform a join between the two unique key tables. Previously, we assumed that the gather map returned in this join for the left (wanted order) table was the identity. However, this is not guaranteed, in addition to computing the match between the wanted key order and the key order we have, we must also apply the permutation between the left gather map order and the identity.
- Closes #16893

Fix order-preservation in cudf-polars groupby

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/groupby/test_ordering_pandas_compat.py

When sort=False is requested in groupby aggregations and pandas compatibility mode is enabled, we are on the hook to produce the grouped aggregation result in an order which matches the input key order. We previously nearly did this, but the reordering relied on the (incorrect) assumption that when joining two tables with a left join, the resulting gather map for the left table is the identity. This is not the case.
To fix this, we must permute the right (result) table gather map by the ordering that makes the left map the identity (AKA, sort by key with the left map as keys) before permuting the result.
While here, replace the (bounds-checking) IndexedFrame.take call with usage of the internal (non-bounds-checking) _gather method. This avoids a redundant reduction over the indices, since …

Fix order-preservation in pandas-compat unsorted groupby

---

docs/cudf/source/user_guide/api_docs/pylibcudf/strings/index.rst
docs/cudf/source/user_guide/api_docs/pylibcudf/strings/split.rst
python/cudf/cudf/_lib/strings/split/partition.pyx
python/cudf/cudf/_lib/strings/split/split.pyx
python/cudf/cudf/core/column/string.py
python/pylibcudf/pylibcudf/libcudf/strings/split/partition.pxd
python/pylibcudf/pylibcudf/libcudf/strings/split/split.pxd
python/pylibcudf/pylibcudf/strings/__init__.pxd
python/pylibcudf/pylibcudf/strings/__init__.py
python/pylibcudf/pylibcudf/strings/split/CMakeLists.txt
python/pylibcudf/pylibcudf/strings/split/__init__.pxd
python/pylibcudf/pylibcudf/strings/split/__init__.py
python/pylibcudf/pylibcudf/strings/split/partition.pxd
python/pylibcudf/pylibcudf/strings/split/partition.pyx
python/pylibcudf/pylibcudf/strings/split/split.pxd
python/pylibcudf/pylibcudf/strings/split/split.pyx
python/pylibcudf/pylibcudf/tests/test_string_split_partition.py
python/pylibcudf/pylibcudf/tests/test_string_split_split.py

Includes `split/split.pxd` and `split/partition.pxd`

Add string.split APIs to pylibcudf

---

python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/tests/series/test_datetimelike.py

closes https://github.com/rapidsai/cudf/issues/16973
Also matches astype from tz-naive to tz-aware type like pandas

Fix astype from tz-aware type to tz-aware type

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_reshape.py

closes https://github.com/rapidsai/cudf/issues/16972

Allow melt(var_name=) to be a falsy label

---

cpp/include/cudf/detail/utilities/logger.hpp
cpp/include/cudf/utilities/logger.hpp
cpp/src/utilities/logger.cpp
cpp/tests/utilities_tests/logger_tests.cpp

This PR removes support for accessing cudf's underlying spdlog logger directly.
Contributes to https://github.com/rapidsai/build-planning/issues/104

Deprecate support for directly accessing logger

---

python/cudf/cudf/_lib/string_casting.pyx
python/pylibcudf/pylibcudf/libcudf/strings/convert/convert_durations.pxd
python/pylibcudf/pylibcudf/strings/convert/convert_durations.pxd
python/pylibcudf/pylibcudf/strings/convert/convert_durations.pyx
python/pylibcudf/pylibcudf/tests/test_string_convert.py
python/pylibcudf/pylibcudf/tests/test_string_convert_durations.py

Since the implementation already existed:
* Added docstrings
* Like https://github.com/rapidsai/cudf/pull/16971, made the `format` parameter accept `str` instead
* Aligned parameter names closer to pylibcudf
* Added missing `move`s
* Moved `convert_duration` tests to `test_string_convert_duration.py` and added a new test for `from_durations`

Add docstrings and test for strings.convert_durations APIs for pylibcudf

---

python/cudf/cudf/_lib/string_casting.pyx

This PR removes an unused unused import in cudf which was causing errors in doc builds.

Remove unused import

---

.github/workflows/pr_issue_status_automation.yml

This PR adds two new jobs to the project automations. One to extract the version number from the branch name, and one to set the project `Release` field to the version found.

Add release tracking to project automation scripts

---

java/ci/build-in-docker.sh

the same issue as https://github.com/NVIDIA/spark-rapids-jni/issues/2475 due to https://github.com/rapidsai/kvikio/pull/464
Port the fix from https://github.com/NVIDIA/spark-rapids-jni/pull/2476, verified locally

Disable kvikio remote I/O to avoid openssl dependencies in JNI build

---

cpp/src/io/parquet/compact_protocol_reader.cpp
cpp/src/io/parquet/parquet.hpp
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/predicate_pushdown.cpp
cpp/src/io/parquet/reader_impl.cpp
cpp/src/io/parquet/reader_impl_chunking.cu
cpp/src/io/parquet/reader_impl_helpers.cpp
cpp/src/io/parquet/writer_impl.cu
cpp/tests/io/parquet_common.cpp
cpp/tests/io/parquet_common.hpp

cuda::std::optional shouldn't be used for host types such as `std::vector` as it requires the constructors of the `T` types to be host+device.

Use std::optional for host types

---

ci/build_docs.sh
ci/test_cpp_common.sh
ci/test_java.sh
ci/test_notebooks.sh
ci/test_python_common.sh
ci/test_python_other.sh

Follow-up to #17013
Changes relative to that PR:
* switches to pinning CI conda installs to the output of `rapids-version` (`{major}.{minor}.{patch}`) instead of `rapids-version-major-minor` (`{major}.{minor}`), to get a bit more protection in the presence of hotfix releases
* restores some exporting of variables needed for docs builds
I made some mistakes in https://github.com/rapidsai/cudf/pull/17013#discussion_r1792317422. Missed that this project's Doxygen setup is expecting to find `RAPIDS_VERSION` and `RAPIDS_VERSION_MAJOR_MINOR` defined in the environment.
https://github.com/rapidsai/cudf/blob/7173b52fce25937bb69e22a083a5de4655078fa1/cpp/doxygen/Doxyfile#L41
https://github.com/rapidsai/cudf/blob/7173b52fce25937bb69e22a083a5de4655078fa1/cpp/doxygen/Doxyfile#L2229

make conda installs in CI stricter (part 2)

---

cpp/src/io/parquet/chunk_dict.cu
cpp/src/join/mixed_join_kernels_semi.cu
cpp/src/join/mixed_join_semi.cu

This PR replaces the deprecated cuco APIs with the new ones, ensuring the code is up to date with the latest API changes.

Replace deprecated cuco APIs with updated versions

---

python/custreamz/README.md

This PR corrects a typo in the `python/custreamz/README.md` file by changing the uppercase `'CSV'` to lowercase `'csv'`. This change aligns the documentation with the `message_format` options defined in `python/custreamz/custreamz/kafka.py`, ensuring consistency across the codebase.

docs: change 'CSV' to 'csv' in python/custreamz/README.md to match kafka.py

---

cpp/src/io/orc/reader_impl_chunking.cu

This fixes a bug in ORC reader when `device_read_async` is called while the destination device buffers are not ready to write in. In detail, this bug is because `device_read_async` does not use the user-provided stream but its own generated stream for data copying. As such, the copying ops could happen before the destination device buffers are being allocated, causing data corruption.
This bug only shows up in certain conditions, and also hard to reproduce. It occurs when copying buffers with small sizes (below `gds_threshold`) and most likely to show up with setting `rmm_mode=async`.

Fix ORC reader when using `device_read_async` while the destination device buffers are not ready

---

cpp/src/interop/to_arrow_host.cu

It is unclear whether the performance gains here are entirely from huge pages themselves or whether invoking madvise with huge pages is primarily serving to trigger an eager population of the pages (huge or not). We attempted to provide alternate flags to `madvise` like `MADV_WILLNEED` and that was not sufficient to recover performance, so either huge pages themselves are doing something special or specifying huge pages is causing `madvise` to trigger a page migration that no other flag does. In any case, this change returns us to the performance before the switch to the C data interface, and this code is lifted straight out of our old implementation so I am comfortable making use of it and knowing that it is not problematic. We should explore further optimizations in this direction, …

Reenable huge pages for arrow host copying

---

python/custreamz/custreamz/kafka.py

Updated the `poll` method in `kafka.py` to use `self.ck_consumer.poll(timeout)` instead of `self.ck.poll(timeout)`. This change ensures consistency with the `__init__` method where `self.ck_consumer` is initialized.

bug fix: use `self.ck_consumer` in `poll` method of kafka.py to align with `__init__`

---

cpp/include/cudf/io/datasource.hpp
cpp/src/io/functions.cpp
cpp/src/io/utilities/datasource.cpp

On Grace Hopper, file I/O takes a special path that calls `cudaHostRegister` to circumvent a performance issue. Recent benchmark shows that this workaround is no longer necessary . This PR is making a clean-up.

Remove the additional host register calls initially intended for performance improvement on Grace Hopper

---

cpp/src/io/utilities/file_io_utilities.cpp

When `LIBCUDF_CUFILE_POLICY` is set to `GDS` or `ALWAYS`, cuDF uses an internal implementation to call the cuFile API and harness the GDS feature. Recent tests with these two settings were unsuccessful due to program crash. Specifically, for the `PARQUET_READER_NVBENCH`'s `parquet_read_io_compression` benchmark:
- GDS write randomly crashed with segmentation fault (SIGSEGV).
- GDS read randomly crashed with bus error (SIGBUS).
- At the time of crash, stack frame is randomly corrupted.
The root cause is the use of dangling reference, which occurs when a variable is captured by reference by nested lambdas. This PR performs a hotfix that turns out to be a 1-char change.

Fix the GDS read/write segfault/bus error when the cuFile policy is set to GDS or ALWAYS

---

cpp/include/cudf/utilities/span.hpp
cpp/src/io/utilities/hostdevice_vector.hpp

Errors reported here: https://github.com/rapidsai/cudf/actions/runs/11398977412/job/31716929242
Just adding `[[nodiscard]]` to a few member functions.

Fix clang-tidy violations for span.hpp and hostdevice_vector.hpp

---

cpp/tests/io/parquet_reader_test.cpp

This PR disables Parquet reader's wide lists table gtest by default as it takes several minutes to complete with memcheck. See the discussion on PR #17059 (this [comment](https://github.com/rapidsai/cudf/pull/17059#discussion_r1805342332)) for more context.

Disable the Parquet reader's wide lists tables GTest by default

---

python/dask_cudf/pyproject.toml

This PR ignores loud dask warnings about legacy dask dataframe implementation is going to be soon removed: https://github.com/dask/dask/pull/11437
Note: We only see this error for `DASK_DATAFRAME__QUERY_PLANNING=False` cases, `DASK_DATAFRAME__QUERY_PLANNING=True` are passing fine.

Ignore loud dask warnings about legacy dataframe implementation

---

cpp/include/cudf/detail/iterator.cuh
cpp/include/cudf/detail/utilities/batched_memset.hpp
cpp/include/cudf/strings/detail/strings_children.cuh
cpp/src/io/parquet/page_data.cu
cpp/src/io/parquet/reader_impl_preprocess.cu
cpp/tests/io/orc_chunked_reader_test.cu

This PR adds a compile time check to enforce that the `start` argument to `cudf::detail::counting_transform_iterator`, which is used to determine the type of `counting_iterator`, is of a type that fits in `int32_t` (aka `size_type`). The PR also modifies the instances of `counting_transform_iterator` that need to work with `counting_iterators` of type > `int32_t` to manually created `counting_transform_iterators` using thrust.
More context in this [comment](https://github.com/rapidsai/cudf/pull/17059/files#r1803925659).

Add compile time check to ensure the `counting_iterator` type in `counting_transform_iterator` fits in `size_type`

---

cpp/include/cudf/io/config_utils.hpp
cpp/src/io/utilities/config_utils.cpp
cpp/src/io/utilities/data_sink.cpp
cpp/src/io/utilities/datasource.cpp

Recent benchmarks have shown that setting the environment variable `KVIKIO_NTHREADS=8` in cuDF usually leads to optimal I/O performance. This PR internally sets the default KvikIO thread pool size to 8. The env `KVIKIO_NTHREADS` will still be honored if users explicitly set it.
Fixes #16718

Set the default number of threads in KvikIO thread pool to 8

---

cpp/include/cudf/detail/unary.hpp

Closes #17117
Related to #12086
This PR replaces the synchronous execution policy with an asynchronous one to eliminate unnecessary synchronization.

Use async execution policy for true_if

---

docs/cudf/source/conf.py

This is an improvement PR that uses the full name of `rmm.DeviceBuffer` in the sphinx config file. Its a follow-up to this [comment](https://github.com/rapidsai/cudf/pull/16913#discussion_r1792283249).

Use the full ref name of `rmm.DeviceBuffer` in the sphinx config file

---

cpp/src/quantiles/tdigest/tdigest_aggregation.cu

Removes unused variable that contains host copy of the group_offsets data.
This host variable appears to have been made obsolete by a combination of #16897 and #16780
Found while working on #17149

Remove unused variable in internal merge_tdigests utility

---

python/cudf/cudf/_lib/copying.pyx
python/cudf/cudf/_lib/lists.pyx
python/cudf/cudf/core/column/lists.py

This PR moves `segmented_gather` out of the copying module and into the lists module. And it uses the pylibcudf `segmented_gather` implementation in cudf python.

Move `segmented_gather` function from the copying module to the lists module

---

cpp/benchmarks/CMakeLists.txt
cpp/include/nvtext/minhash.hpp
cpp/tests/CMakeLists.txt

Deprecates the current nvtext minhash functions some of which will be replaced in #16756 with a different signature. The others will no longer be used and removed in future release. The existing gtests and benchmarks will be retained for rework in the future release as well.

Deprecate current libcudf nvtext minhash functions

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/text/ngrams.cpp

Moves the `nvtext::generate_ngrams` and `nvtext::generate_character_ngrams` benchmarks from google-bench to nvbench.
Target parameters are exposed to help with profiling.

Move nvtext ngrams benchmarks to nvbench

---

cpp/CMakeLists.txt
cpp/src/groupby/hash/compute_mapping_indices.cu
cpp/src/groupby/hash/compute_mapping_indices.cuh
cpp/src/groupby/hash/compute_mapping_indices.hpp
cpp/src/groupby/hash/compute_mapping_indices_null.cu

This work is part of splitting the original bulk shared memory groupby PR https://github.com/rapidsai/cudf/pull/16619.
This PR introduces the `compute_mapping_indices` API, which is used by the shared memory groupby. libcudf will opt for the shared memory code path when the aggregation request is compatible with shared memory, i.e. there is enough shared memory space and no dictionary aggregation requests. Aggregating with shared memory involves two steps. The first step, introduced in this PR, calculates the offset for each input key within the shared memory aggregation storage, as well as the offset when merging the shared memory results into global memory.

Add compute_mapping_indices used by shared memory groupby

---

java/src/main/java/ai/rapids/cudf/DType.java
java/src/main/java/ai/rapids/cudf/Schema.java

In Spark, the `DecimalType` has a specific number of digits to represent the numbers. However, when creating a data Schema, only type and name of the column are stored, thus we lose that precision information. As such, it would be difficult to reconstruct the original decimal types from cudf's `Schema` instance.
This PR adds a `precision` member variable to the `Schema` class in cudf Java, allowing it to store the precision number of the original decimal column.
Partially contributes to https://github.com/NVIDIA/spark-rapids/issues/11560.

Support storing `precision` of decimal types in `Schema` class

---

java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java

This is the first patch in a series of patches that should make it so that all java host memory allocations go through the DefaultHostMemoryAllocator unless another allocator is explicitly provided. 
This is to make it simpler to track/control host memory usage.

Add in new java API for raw host memory allocation

---

cpp/benchmarks/ast/transform.cpp
cpp/benchmarks/binaryop/binaryop.cpp
cpp/benchmarks/binaryop/compiled_binaryop.cpp

This merge request unifies the parameter names of the AST and BINARYOP benchmark suites and makes it easier to perform parameter sweeps and compare the outputs of both benchmarks.

Unified binary_ops and ast benchmarks parameter names

---

.github/workflows/auto-assign.yml

The Auto Assign GHA workflow fails with this [error](https://github.com/rapidsai/cudf/actions/runs/11580081781). This PR fixes this error.
xref #16969

[BUG] Replace `repo_token` with `github_token` in Auto Assign PR GHA

---

cpp/include/nvtext/tokenize.hpp
docs/cudf/source/user_guide/api_docs/pylibcudf/nvtext/index.rst
docs/cudf/source/user_guide/api_docs/pylibcudf/nvtext/tokenize.rst
python/cudf/cudf/_lib/nvtext/tokenize.pyx
python/cudf/cudf/core/tokenize_vocabulary.py
python/pylibcudf/pylibcudf/nvtext/CMakeLists.txt
python/pylibcudf/pylibcudf/nvtext/__init__.pxd
python/pylibcudf/pylibcudf/nvtext/__init__.py
python/pylibcudf/pylibcudf/nvtext/tokenize.pxd
python/pylibcudf/pylibcudf/nvtext/tokenize.pyx
python/pylibcudf/pylibcudf/tests/test_nvtext_tokenize.py

Migrate NVText Tokenizing APIs to pylibcudf

---

docs/cudf/source/user_guide/api_docs/pylibcudf/strings/findall.rst
docs/cudf/source/user_guide/api_docs/pylibcudf/table.rst
python/pylibcudf/pylibcudf/binaryop.pyx
python/pylibcudf/pylibcudf/filling.pyx
python/pylibcudf/pylibcudf/strings/__init__.py
python/pylibcudf/pylibcudf/strings/regex_program.pyx
python/pylibcudf/pylibcudf/strings/replace.pyx
python/pylibcudf/pylibcudf/types.pyx

* Fixed/modified some title headers
* Fixed/added pylibcudf section docstrings

Fix some documentation rendering for pylibcudf

---

cpp/tests/reductions/list_rank_test.cpp
cpp/tests/reductions/rank_tests.cpp
cpp/tests/reductions/reduction_tests.cpp
cpp/tests/reductions/scan_tests.cpp

Input strings column containing unsanitized nulls may result in undefined behavior.
This PR fixes the input data to not include string characters in null rows in gtests for `REDUCTION_TESTS`.

Remove unsanitized nulls from input strings columns in reduction gtests

---

java/src/main/java/ai/rapids/cudf/Schema.java

When calling `Schema.Builder.build()`, the value `topLevelPrecision` should be passed into the constructor of the `Schema` class. However, it was forgotten.

Fix `Schema.Builder` does not propagate precision value to `Builder` instance

---

cpp/include/cudf/fixed_point/detail/floating_conversion.hpp
cpp/include/cudf/unary.hpp
cpp/include/doxygen_groups.h

Moves the 'cudf/fixed_point/floating_conversion.hpp' to `cudf/fixed_point/detail/` subdirectory since it only contains declarations and definition in the `detail` namespace.
It had previously been its own module. https://docs.rapids.ai/api/libcudf/stable/modules.html

Move detail header floating_conversion.hpp to detail subdirectory

---

python/cudf/cudf/core/tokenize_vocabulary.py
python/pylibcudf/pylibcudf/nvtext/tokenize.pxd
python/pylibcudf/pylibcudf/nvtext/tokenize.pyx
python/pylibcudf/pylibcudf/tests/test_nvtext_tokenize.py

This PR follow up #17100 to address the last review here https://github.com/rapidsai/cudf/pull/17100#pullrequestreview-2406700961

Remove `nvtext::load_vocabulary` from pylibcudf

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/tests/test_binops.py

closes #17087
For binops, cudf tries to convert a 0D numpy array to a numpy scalar via `.dtype.type(value)`, but `.dtype.type` requires other parameters if its a `numpy.datetime64` or `numpy.timedelta64`. Indexing via `[()]` will perform this conversion correctly.

Fix binop with LHS numpy datetimelike scalar

---

cpp/include/cudf/io/datasource.hpp
cpp/src/io/utilities/file_io_utilities.cpp
cpp/src/io/utilities/file_io_utilities.hpp

This PR makes small improvements for the I/O code. Specifically,
- Place type constraint on a template class to allow only for rvalue argument. In addition, replace `std::move` with `std::forward` to make the code more *apparently* consistent with the convention, i.e. use `std::move()` on the rvalue references, and `std::forward` on the forwarding references (Effective modern C++ item 25).
- Alleviate (but not completely resolve) an existing cuFile driver close issue by removing the explicit driver close call. See #17121 
- Minor typo fix (`struct` &#8594; `class`).

Minor I/O code quality improvements

---

cpp/include/cudf/io/config_utils.hpp
cpp/src/io/utilities/config_utils.cpp
cpp/src/io/utilities/data_sink.cpp
cpp/src/io/utilities/datasource.cpp
docs/cudf/source/user_guide/io/io.md

This PR adjusts the default KvikIO parameters in light of recent discussions.
- Set KvikIO compatibility mode to ON (previously unspecified). This is to avoid the overhead of KvikIO validating the cuFile library when most of the time clients are not using cuFile/GDS.
- Set KvikIO thread pool size to 4 (previous 8). See the reason below.
In addition, this PR updates the documentation on `LIBCUDF_CUFILE_POLICY`.
---
It is reported that Dask-cuDF on a 8-GPU node with Lustre file system has major performance regression when the KvikIO thread pool size is 8.
|KVIKIO_NTHREADS| 8 | 4 | 2 | 1 |
|----------------------------|---|----|---|----------|
|Dask-cuDF time [s]| 16 | 3.9 | 4.0 | 4.3 |
|cuDF time [s]| 3.4 | 3.4 | 3.8 | 4.9 |
Additional benchmark on Grace Hopper …

Change default KvikIO parameters in cuDF: set the thread pool size to 4, and compatibility mode to ON

---

cpp/benchmarks/io/parquet/parquet_reader_multithread.cpp

Added an axis that controls the number of times each thread reads its input. Running with a higher number of iterations should better show how work from different threads pipelines. 
The new axis, "num_iterations", is added to all multi-threaded Parquet reader benchmarks.

Add `num_iterations` axis to the multi-threaded Parquet benchmarks

---

python/cudf/cudf/_lib/csv.pyx
python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/_lib/orc.pyx
python/cudf/cudf/_lib/parquet.pyx
python/pylibcudf/pylibcudf/io/types.pyx

If we consider the `pylibcudf.libcudf` namespace to eventually be more "private", this PR replaces that usage, specifically when accessing enums, with their public counterparts

Use more pylibcudf.io.types enums in cudf._libs

---

cpp/cmake/thirdparty/get_kvikio.cmake

The case-sensitive name KvikIO is will throw off `find_package` searches, particularly after https://github.com/rapidsai/devcontainers/pull/414 make the usage consistent in devcontainers.

Search for kvikio with lowercase

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cudf/meta.yaml
conda/recipes/pylibcudf/meta.yaml
dependencies.yaml
python/cudf/pyproject.toml
python/pylibcudf/pyproject.toml

Follow-up to #17253
Contributes to https://github.com/rapidsai/build-planning/issues/116
That PR used `!=` requirements to skip a particular version of `cuda-python` that `cudf` and `pylibcudf` were incompatible with. A newer version of `cuda-python` (12.6.2 for CUDA 12, 11.8.5 for CUDA 11) was just released, and it also causes some build issues for RAPIDS libraries: https://github.com/rapidsai/cuvs/pull/445#issuecomment-2461146449
To unblock CI across RAPIDS, this proposes **temporarily** switching to ceilings on the `cuda-python` dependency here.

Put a ceiling on cuda-python

---

python/cudf/cudf/_lib/strings/convert/convert_integers.pyx

Use `pylibcudf.strings.convert.convert_integers.is_integer` in cudf python

---

python/cudf/cudf/_lib/sort.pyx

Use pylibcudf.search APIs in cudf python

---

cpp/tests/io/json/json_test.cpp

Fixes call to `data_type{}` ctor in `json_test.cpp`. The 2-parameter ctor is for fixed-point-types only and will assert in a debug build if used incorrectly: https://github.com/rapidsai/cudf/blob/2db58d58b4a986c2c6fad457f291afb1609fd458/cpp/include/cudf/types.hpp#L277-L280
Partial stack trace from a gdb run
```
#5  0x000077b1530bc71b in __assert_fail_base (fmt=0x77b153271130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
assertion=0x58c3e4baaa98 "id == type_id::DECIMAL32 || id == type_id::DECIMAL64 || id == type_id::DECIMAL128",
file=0x58c3e4baaa70 "/cudf/cpp/include/cudf/types.hpp", line=279, function=<optimized out>) at ./assert/assert.c:92
#6  0x000077b1530cde96 in __GI___assert_fail (
assertion=0x58c3e4baaa98 "id == type_id::DECIMAL32 || id == type_id::DECIMAL64 || id == …
```

Fix data_type ctor call in JSON_TEST

---

python/cudf/cudf/_lib/datetime.pyx

Plumb pylibcudf datetime APIs through cudf python

---

java/src/main/java/ai/rapids/cudf/ContiguousTable.java
java/src/main/java/ai/rapids/cudf/DeviceMemoryBufferView.java

Make constructor of DeviceMemoryBufferView and ContiguousTable public.

Make constructor of DeviceMemoryBufferView  public

---

python/cudf/cudf/_lib/quantiles.pyx
python/cudf/cudf/_lib/types.pxd
python/cudf/cudf/_lib/types.pyx
python/cudf/cudf/core/frame.py

Shouldn't need to use the "private" `pylibcudf.libcudf` types anymore now that the Python side enums are exposed

Use pylibcudf enums in cudf Python quantile

---

python/cudf/cudf/_lib/groupby.pyx
python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/_lib/lists.pyx

Similar to https://github.com/rapidsai/cudf/pull/17287. Also remove a `plc` naming shadowing

Use more pylibcudf Python enums in cudf._lib

---

cpp/include/cudf/transpose.hpp
cpp/src/transpose/transpose.cu
cpp/tests/CMakeLists.txt
cpp/tests/streams/transpose_test.cpp

Adds stream parameter to `cudf::transpose`.
Verifies correct stream forwarding with stream gtests.
Reference: https://github.com/rapidsai/cudf/issues/13744

Expose stream-ordering in public transpose API

---

cpp/cmake/thirdparty/get_flatbuffers.cmake
cpp/cmake/thirdparty/get_nanoarrow.cmake

This change helps shrink RAPIDS wheels. It should not affect Spark builds since those use the build directory of cudf and statically link in those components to its final binary.

Exclude nanoarrow and flatbuffers from installation

---

cpp/tests/ast/transform_tests.cpp

The ast operation takes references to the expressions. The expression was being copied to a lambda scope and destroyed at the end, leading to a dangling reference.
New code should use the ast tree for constructing complicated expression trees as it handles lifetime management.
Closes https://github.com/rapidsai/cudf/issues/17274

Fixed lifetime issue in ast transform tests

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/cpp_linters.sh
cpp/CMakeLists.txt
dependencies.yaml

This PR adds Polars tests to our nightly runs now that [we no longer only fail conditional on certain files changing in PRs](https://github.com/rapidsai/cudf/pull/17299). This PR also updates the IWYU jobs to use [the version released three days ago, which supports clang 19 like we need](https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.23). It also fixes a couple of errors in the CMake for how we were setting compile flags for IWYU.
Closes #16383

Update CI jobs to include Polars in nightlies and improve IWYU

---

python/cudf/cudf/_lib/copying.pyx
python/cudf/cudf/_lib/groupby.pyx
python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/_lib/lists.pyx
python/pylibcudf/pylibcudf/io/types.pyx

* Removed `ctypedef const scalar constscalar` usage
* Use `dtype_to_pylibcudf_type` where appropriate
* Use pylibcudf enums instead of `pylibcudf.libcudf` types

Clean up misc, unneeded pylibcudf.libcudf in cudf._lib

---

cpp/cmake/thirdparty/get_flatbuffers.cmake
cpp/cmake/thirdparty/get_nanoarrow.cmake

Had an issue crop up in spark-rapids-jni where we statically link arrow and the build started to fail due to change #17308.

Do not exclude nanoarrow and flatbuffers from installation if statically linked

---

.pre-commit-config.yaml
cpp/CMakeLists.txt
cpp/cmake/Modules/FindCUDAToolkit.cmake
java/src/main/native/CMakeLists.txt

The reference in JNI was missed in #17298. Replace it with `FindCUDAToolkit`.
Also backport `FindCUDAToolkit` from CMake 3.31 to get https://gitlab.kitware.com/cmake/cmake/-/commit/b38a8e77cb3c8401b3022a68f07a4fd77b290524.
Also add an option to statically link `cuFile`.

Remove another reference to `FindcuFile`

---

.github/workflows/pr.yaml
ci/build_cpp.sh

This is a prototype implementation of https://github.com/rapidsai/build-infra/issues/139
The work that this builds on:
* https://github.com/rapidsai/gha-tools/pull/118, which adds a shell wrapper that automatically creates spans for the commands that it wraps. It also uses the `opentelemetry-instrument` command to set up monkeypatching for supported Python libraries, if the command is python-based
* https://github.com/rapidsai/shared-workflows/tree/add-telemetry, which installs the gha-tools work from above and sets necessary environment variables. This is only done for the conda-cpp-build.yaml shared workflow at the time of submitting this PR.
The goal of this PR is to observe telemetry data sent from a GitHub Actions build triggered by this PR as a proof of concept. Once it all works, …

add telemetry setup to test

---

java/ci/Dockerfile.rocky

Updates cmake to 3.28.6 in the JNI Dockerfile used to build the cudf jar.  This helps avoid a bug in older cmake where FindCUDAToolkit can fail to find cufile libraries.

Update cmake to 3.28.6 in JNI Dockerfile

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/string/translate.cpp

Moves `cpp/benchmarks/string/translate.cpp` implementation from google-bench to nvbench.
This is benchmark for the `cudf::strings::translate` API.

Move strings translate benchmarks to nvbench

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/run_cudf_polars_polars_tests.sh

This PR ensures that we have nightly coverage of more of the CUDA/Python/arch versions that we claim to support for dask-cudf and cudf-polars wheels.
In addition, this PR ensures that we do not attempt to run the dbgen executable in the Polars repository on systems with too old of a glibc to support running them.

Test the full matrix for polars and dask wheels on nightlies

---

python/cudf/cudf/_lib/CMakeLists.txt
python/cudf/cudf/_lib/__init__.py
python/cudf/cudf/_lib/column.pyi
python/cudf/cudf/_lib/utils.pxd
python/cudf/cudf/_lib/utils.pyx
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/numerical_base.py
python/cudf/cudf/core/frame.py

Contributes to https://github.com/rapidsai/cudf/issues/17317

Remove cudf._lib.quantiles in favor of inlining pylibcudf

---

cpp/src/io/utilities/config_utils.cpp
cpp/src/io/utilities/data_sink.cpp
cpp/src/io/utilities/datasource.cpp

This PR adapts cuDF to a breaking API change in KvikIO (https://github.com/rapidsai/kvikio/pull/547) introduced recently, which adds the `AUTO` compatibility mode to file I/O.
This PR causes no behavioral changes in cuDF: If the environment variable `KVIKIO_COMPAT_MODE` is left unset, cuDF by default still enables the compatibility mode in KvikIO. This is the same with the previous behavior (https://github.com/rapidsai/cudf/pull/17185).

Adapt to KvikIO API change in the compatibility mode

---

cpp/src/binaryop/jit/kernel.cu

Follow on to #17354 to prevent overflow in jit kernel binary-ops.
This uses the `thread_index_type` directly since the `detail/utilities/cuda.cuh` cannot be included in the jit'd kernel source.

Use thread_index_type in binary-ops jit kernel.cu

---

cpp/src/join/join_common_utils.hpp

This PR eliminates unused type aliases in join details.

Remove unused type aliases

---

cpp/examples/basic/CMakeLists.txt
cpp/examples/billion_rows/CMakeLists.txt
cpp/examples/interop/CMakeLists.txt
cpp/examples/nested_types/CMakeLists.txt
cpp/examples/parquet_io/CMakeLists.txt
cpp/examples/strings/CMakeLists.txt

The examples currently have no build type set by default so they wind up with debug code in them.

Set build type for all examples

---

cpp/src/replace/nans.cu
cpp/tests/streams/replace_test.cpp

Adds stream parameter to
```
cudf::normalize_nans_and_zeros
```
Reference: https://github.com/rapidsai/cudf/issues/13744

Expose stream-ordering in replace API

---

.github/workflows/pr.yaml

The contents of the `.devcontainer/` directory don't affect any of the artifacts produced from this repo. This proposes skipping most CI on PRs that only make changes in that directory.

skip most CI on devcontainer-only changes

---

python/custreamz/custreamz/tests/test_dataframes.py

Temporarily skip tests failing due to an upstream dask change.

Temporarily skip tests due to dask/distributed#8953

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml
python/cudf/cudf/tests/test_cuda_array_interface.py
python/cudf/cudf_pandas_tests/third_party_integration_tests/dependencies.yaml

This PR updates our PyTorch lower bound to 2.4.0 to get the bugfix from https://github.com/pytorch/pytorch/pull/121458.
Also, this PR drops CUDA 11 tests because conda-forge no longer produces CUDA 11 builds of PyTorch. This was causing a failure on Hopper GPUs because the last available CUDA 11 builds from conda-forge do not include sm90 support.

Update PyTorch to >=2.4.0 to get fix for CUDA array interface bug, and drop CUDA 11 PyTorch tests.

---

python/custreamz/custreamz/tests/test_dataframes.py

Reverts rapidsai/cudf#17472
The new dask nightly has resolved https://github.com/dask/distributed/issues/8953

Revert "Temporarily skip tests due to dask/distributed#8953"

---

cpp/src/io/csv/csv_gpu.cu

Use a global array instead of a shared memory array in the `gather_row_offsets_gpu` kernel.
Impact on the kernel performance is less than 5%, and this kernel takes very little portion of the total read_csv execution time - impact on the performance is negligible.
Also modified functions that take this array to take a `device_span` instead on a plain pointer.

Workaround for a misaligned access in `read_csv` on some CUDA versions

---

.github/workflows/test.yaml

Removes the third-party integration tests for the 24.12 nightly CI. We need to do this to unblock CI. These tests have not been running properly, and we just noticed that. There are more than a few failures so we will have to resolve this in the next release. Future work is tracked in #17490.

Turn off cudf.pandas 3rd party integrations tests for 24.12

---

cpp/src/io/comp/nvcomp_adapter.cpp

Adds `[[maybe_unused]]` to the `compression_type_name` function to prevent the warning/error.
Error/warning introduced in #17431
Closes #17510

Fix libcudf compile error when logging is disabled

---

cpp/cmake/thirdparty/patches/thrust_disable_64bit_dispatching.diff

This fixes the patch we use for Thrust to always get a 32-bit offset type. The net effect of this patch is that we are behaving as if `THRUST_FORCE_32_BIT_OFFSET_TYPE` is set. This replaces a previous patch which I mistakenly did not update between CCCL 2.6.x testing and 2.7.0-rc2 testing.
In the future we hope to configure this with CMake and drop the patches, but that will require us to use features from https://github.com/NVIDIA/cccl/pull/2844 (which is not available in 2.7.0-rc2).

Force Thrust to use 32-bit offset type.

---

python/cudf/cudf/_lib/strings_udf.pyx
python/cudf/cudf/_lib/utils.pyx

Apart of #15162. In a follow-up PR we'll deprecate the cudf python column APIs and others that are used outside cudf.

Replaces uses of `cudf._lib.Column.from_unique_ptr` with `pylibcudf.Column.from_libcudf`

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cudf/meta.yaml
conda/recipes/pylibcudf/meta.yaml
dependencies.yaml
python/cudf/pyproject.toml
python/pylibcudf/pyproject.toml

We require a newer cuda-python lower bound for new features and to use the new layout.
This will fix a number of errors observed when the runtime version of cuda-python is older than the version used to build packages using Cython features from cuda-python.
See https://github.com/rapidsai/build-planning/issues/117#issuecomment-2524250915 for details.

Update cuda-python lower bounds to 12.6.2 / 11.8.5

---

cpp/src/strings/search/find.cu

Replaces the `cub::WarpReduce` usage in `cudf::strings::contains` with cooperative-groups `any()`.
The change is only for the `contains_warp_parallel` kernel which is used for wider strings.
Using cooperative-groups generates more efficient code for the same results and gives an additional 11-14% performance improvement.

Use cooperative-groups instead of cub warp-reduce for strings contains

---

java/src/main/native/src/RmmJni.cpp

This is a follow up from https://github.com/rapidsai/cudf/pull/17526, where fabric handles can be enabled from RMM. That PR also sets the memory access protection flag (`cudaMemPoolSetAccess`), but I have learned that this second flag is not needed from the owner device. In fact, it causes confusion because the owning device fails to call this function with some of the flags (access none).  `cudaMemPoolSetAccess` is meant to only be called from peer processes that have imported the pool's handle. In our case, UCX handles this from the peer's side and it does not need to be anywhere in RMM or cuDF.
Sorry for the noise. I'd like to get this fix in, and then I am going to fix RMM by removing that API.

[JNI] remove rmm argument to set rw access for fabric handles

---

python/cudf/cudf/_lib/parquet.pyx

Follow up to #17506. This PR removes an unused buffer class.

Remove unused `BufferArrayFromVector`

---

python/cudf/cudf/_lib/CMakeLists.txt

Due to 2 of my cudf._lib refactoring PRs going in which then impacted formatting of `cudf/_lib/CMakeLists.txt`

Fix CMake format in cudf/_lib/CMakeLists.txt

---

cpp/CMakeLists.txt

#17307 broke builds that use the rapids-cmake pinned dependencies feature since no version was specified for the rapids_logger dependency.  This adds a version string equal to the git tag so the dependency has a stated version.

Specify a version for rapids_logger dependency

---

java/src/main/java/ai/rapids/cudf/Scalar.java

This exposes the constructor and `getScalarHandle()` method in `Scalar.java` to the public, allowing them to be called from the outside. Without access to these methods, it was very inconvenient. Workaround has been implemented ([spark-rapids-jni/CudfAccessor.java](https://github.com/NVIDIA/spark-rapids-jni/blob/5231d4d82603d488b95ea259874a26f9f4354005/src/main/java/ai/rapids/cudf/CudfAccessor.java#L21)) to overcome this but it is better to have the issue addressed from the root.
Partially contributes to https://github.com/NVIDIA/spark-rapids-jni/issues/1307.

Expose Scalar's constructor and `Scalar#getScalarHandle()` to public

---

cpp/src/io/orc/writer_impl.cu

This PR replaces a set of per-column, per-rowgroup D2D memcopies with a single call to the `batched_memcpy_async` utility. Should improve performance when writing wide tables.

Use batched memcpy when writing ORC statistics

---

python/cudf/cudf/core/column/numerical_base.py
python/cudf/cudf/tests/test_quantiles.py

From an offline conversation, fixes the follow discrepancy between cudf and pandas
```python
In [2]: import numpy as np
In [3]: ser = cudf.Series([np.nan, np.nan, 0.9], nan_as_null=False)
In [4]: ser
Out[4]: 
0    NaN
1    NaN
2    0.9
dtype: float64
In [5]: ser.quantile(0.9)
Out[5]: np.float64(nan)
In [6]: import pandas as pd
In [7]: ser = pd.Series([np.nan, np.nan, 0.9])
In [8]: ser.quantile(0.9)
Out[8]: np.float64(0.9)
```

Ignore NaN correctly in .quantile

---

cpp/include/cudf/column/column_device_view.cuh
cpp/include/cudf/strings/string_view.hpp
cpp/src/strings/regex/regex.cuh
cpp/src/strings/regex/regex.inl

Clang-tidy does not like `[[nodiscard]]` after `__device__` and I don't like red squigly lines.

Use `[[nodiscard]]` attribute before `__device__`

---

python/dask_cudf/dask_cudf/backends.py
python/dask_cudf/dask_cudf/io/csv.py
python/dask_cudf/dask_cudf/io/tests/test_csv.py

Recent changes in dask and dask-expr have broken `dask_cudf.read_csv` (https://github.com/dask/dask-expr/pull/1178, https://github.com/dask/dask/pull/11603). Fortunately, the breaking changes help us avoid legacy CSV code in the long run.

Fix ``dask_cudf.read_csv``

---

python/cudf/cudf/io/avro.py
python/pylibcudf/pylibcudf/io/avro.pxd
python/pylibcudf/pylibcudf/io/avro.pyi
python/pylibcudf/pylibcudf/io/avro.pyx
python/pylibcudf/pylibcudf/tests/io/test_avro.py

Add Avro Reader options classes to pylibcudf

---

cpp/CMakeLists.txt

This PR has two fixes:
- Since we're pinning to a commit, a shallow clone will start failing as soon as HEAD gets bumped on the main branch (which will happen next when cuml/raft logging features are merged). We need to stop using shallow clones.
- The CMake code for setting the default logging levels was setting the wrong macro name.

A couple of fixes in rapids-logger usage

---

cpp/tests/streams/replace_test.cpp

Fixes memcheck error found in nightly build checks in the STREAM_REPLACE_TEST's `ReplaceTest.NormalizeNansAndZerosMutable` gtest. The mutable-view passed to the `cudf::normalize_nans_and_zeros` API was pointing to invalidated data.
The following line created the invalid view
```
cudf::mutable_column_view mutable_view = cudf::column(input, cudf::test::get_default_stream());
```
The temporary `cudf::column` is destroyed once the `mutable_view` is created so this view would now point to a freed column. The view must be created from a non-temporary column and also must be non-temporary itself so that it is not implicitly converted to a `column_view`.
Error introduced by #17436

Fix memcheck error in ReplaceTest.NormalizeNansAndZerosMutable gtest

---

cpp/include/cudf/detail/aggregation/aggregation.cuh
cpp/src/aggregation/aggregation.cu
cpp/src/groupby/hash/compute_aggregations.cuh
cpp/src/groupby/hash/compute_global_memory_aggs.cu
cpp/src/groupby/hash/compute_global_memory_aggs.cuh
cpp/src/groupby/hash/compute_global_memory_aggs.hpp
cpp/src/groupby/hash/compute_global_memory_aggs_null.cu
cpp/src/groupby/hash/create_sparse_results_table.cu
cpp/src/groupby/hash/create_sparse_results_table.hpp
cpp/src/groupby/hash/flatten_single_pass_aggs.cpp
cpp/src/groupby/hash/flatten_single_pass_aggs.hpp
cpp/src/groupby/hash/hash_compound_agg_finalizer.cu
cpp/src/groupby/sort/group_scan_util.cuh

Return a `cudf::detail::host_vector` from `flatten_single_pass_aggs` because this vector is eventually copied to the device and we might want to use pinned memory.

Use `host_vector` in `flatten_single_pass_aggs`

---

cpp/src/groupby/hash/compute_groupby.cu
cpp/src/groupby/hash/compute_mapping_indices.cuh
cpp/src/groupby/hash/helpers.cuh
cpp/src/io/orc/dict_enc.cu
cpp/src/io/orc/orc_gpu.hpp
cpp/src/io/parquet/chunk_dict.cu
cpp/src/io/parquet/parquet_gpu.cuh
cpp/src/io/parquet/writer_impl.cu

Recently, cuco refined the term "window" as "bucket," as the latter more accurately represents a contiguous memory space containing one or more hash table slots. This PR implements the necessary changes to replace "window" with "bucket" in all relevant use cases.

Replace the outdated cuco window concept with buckets

---

cpp/include/cudf/hashing/detail/murmurhash3_x86_32.cuh

Changes the return types for the `MurmurHash3_x86_32` specialization functions to match the declarations in the struct.
Hoping to fix some intellisense squiggles.

Fix return types for MurmurHash3_x86_32 template specializations

---

cpp/src/io/parquet/predicate_pushdown.cpp

This PR simplifies the StatsAST expression transformer in Parquet reader's predicate pushdown using `ast::tree` from (https://github.com/rapidsai/cudf/pull/17156). 
This PR is a follow up to @bdice's comment at https://github.com/rapidsai/cudf/pull/17289#discussion_r1876966752. Similar changes for the `BloomfilterAST` expression converter have been incorporated in the PR https://github.com/rapidsai/cudf/pull/17289.
Related to https://github.com/rapidsai/cudf/issues/17164

Simplify expression transformer in Parquet predicate pushdown with `ast::tree`

---

cpp/src/join/mixed_join_size_kernel.cuh
cpp/src/json/json_path.cu

Fixes possible integer overflow condition when the number of rows is near max int32 in `compute_mixed_join_output_size` kernel function.
Reference #10368

Fix possible int overflow in compute_mixed_join_output_size

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

Fixes: #17648 
This adds support for `Groupby.cumprod` which has been missing in current code.

Add support for `Groupby.cumprod`

---

python/cudf_polars/cudf_polars/dsl/expressions/aggregation.py
python/cudf_polars/tests/test_groupby.py

closes https://github.com/rapidsai/cudf/issues/17667

Fix groupby.len with null values in cudf.polars

---

python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_timedelta.py

Fixes: #16802 
This PR implements `.dt.total_seconds`

Implement `.dt.total_seconds`

---

docs/cudf/source/cudf_pandas/faq.md
docs/cudf/source/cudf_pandas/usage.md

Adds a cross-link to the cudf.pandas profiler docs. This cross-linking would have helped answer a user question about how to profile.

Cross-link cudf.pandas profiler documentation.

---

cpp/src/io/comp/nvcomp_adapter.cpp
cpp/src/io/csv/reader_impl.cu
cpp/src/io/fst/agent_dfa.cuh
cpp/src/io/parquet/writer_impl.cu
cpp/src/io/utilities/data_sink.cpp
cpp/src/io/utilities/datasource.cpp
cpp/src/io/utilities/getenv_or.hpp
cpp/src/utilities/host_memory.cpp
cpp/src/utilities/stream_pool.cpp

Replace fmt-style `{}` syntax with `printf`-style `%xyz` format strings, because the fmt-style does not work with recent logger changes.

Fix formatting in logging

---

.github/CODEOWNERS
python/libcudf/CMakeLists.txt

Nothing in `libcudf`'s CMake should need a Python interpreter or linking to Python components. This proposes removing the `find(Python)` there, to simplify that build:
https://github.com/rapidsai/cudf/blob/955b1f4566abccf920a022dc78a1e654acf0de16/python/libcudf/CMakeLists.txt#L37-L38

remove find_package(Python) in libcudf build

---

python/cudf_polars/cudf_polars/dsl/expressions/aggregation.py
python/cudf_polars/tests/expressions/test_agg.py

closes #17681
(We have a similar carve-out in cudf classic due to `sum([]) == 0` in Python)

Fix cudf.polars sum of empty not equalling zero

---

java/src/main/java/ai/rapids/cudf/ParquetChunkedReader.java
java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/CMakeLists.txt
java/src/main/native/include/multi_host_buffer_source.hpp
java/src/main/native/src/ChunkedReaderJni.cpp
java/src/main/native/src/TableJni.cpp
java/src/main/native/src/multi_host_buffer_source.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

Adds a custom cuio datasource that can provide file data via multiple host memory buffers.  This allows data that arrives from multiple threads in multiple buffers to be read directly rather than requiring the buffers to be concatenated into a single host memory buffer before reading.

Java Parquet reads via multiple host buffers

---

cpp/scripts/sort_ninja_log.py

Truncates filenames that appear as multiple `placehold_placedhold_...` in the Build Metrics Report.
Example show here: https://downloads.rapids.ai/ci/cudf/pull-request/17669/0710ad6/cuda12_x86_64.ninja_log.html (requires VPN).

Fix build metrics report format with long placehold filenames

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

Use `ci-conda:latest` tags for all jobs. All jobs should now support `ci-conda:latest`, and older pinnings are probably not necessary anymore.

Use latest ci-conda images

---

cpp/src/io/parquet/decode_fixed.cu

This fixes a bug in the parquet list reader, where if a row had a list so long that it spanned a whole page, we would skip reading the page entirely.

Fix parquet reader list bug

---

java/src/main/java/ai/rapids/cudf/HostUDFWrapper.java

This adds the requirement to implement `AutoCloseable`  to the classes derived from `HostUDFWrapper`, forcing them to delete the native UDF instance upon class destruction. Doing so will fix the memory leak issue when the native UDF instance never being destroyed.

Require to implement `AutoCloseable` for the classes derived from `HostUDFWrapper`

---

cpp/src/io/utilities/config_utils.cpp

KvikIO has just introduced slightly breaking code changes (https://github.com/rapidsai/kvikio/pull/581) where the utility function `getenv_or` is moved out of the `detail` namespace and becomes part of the public API. This PR adapts cuDF for this change.
This PR has been tested locally using the abovementioned KvikIO branch.

Update kvikio call due to upstream changes

---

python/cudf/cudf/core/multiindex.py

Follow up to https://github.com/rapidsai/cudf/pull/17644
This PR changes `MultiIndex` to delay computing `self._level` and `self._codes` via factorization of `self._column` until needed by certain methods. Before, for state consistency, those attributes were always eagerly computed. As discussed offline the performance benefit of not eagerly computing those attributes is more desirable.
```python
import cudf
df_train = cudf.datasets.randomdata(nrows=50_000_000, dtypes={"label": int, "weekday": int, "cat_2": int, "brand": int})
target = "label"
col = ['weekday', 'cat_2', 'brand']
df_gb= df_train[col + [target]].groupby(col)
%%time
df_gb.agg(['mean', 'count'])
CPU times: user 144 ms, sys: 23.9 ms, total: 168 ms
Wall time: 166 ms
_     ._   __/__   _ _  _  _ _/_   Recorded: 12:12:46 …
```

Delay setting MultiIndex.level/codes until needed

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cudf/meta.yaml
dependencies.yaml
python/cudf/pyproject.toml
python/dask_cudf/pyproject.toml

This PR unblock `cudf` CI from recent failures: https://github.com/rapidsai/cudf/actions/runs/12881355939/job/35911797186 introduced by latest release of `numba-0.61.0`

Add `numba` pinning to `cudf` repo

---

.pre-commit-config.yaml

This PR adds configuration for pre-commit.ci.
See https://github.com/rapidsai/build-planning/issues/124 for the motivation.

Enable pre-commit.ci

---

ci/run_cudf_memcheck_ctests.sh

Uses the `GTEST_BRIEF=1` environment variable to reduce the output of the memcheck script.
This should help find errors more quickly in the nightly memcheck build output.
Example output where 1 test fails in the entire `STRINGS_TEST`
```
$ export GTEST_BRIEF=1
$ gtests/STRINGS_TEST 
/cudf/cpp/tests/utilities/column_utilities.cu:566: Failure
Failed
first difference: lhs[12] = 50089, rhs[12] = 500890
Google Test trace:
/cudf/cpp/tests/strings/attrs_tests.cpp:45:  <--  line of failure
[  FAILED  ] StringsAttributesTest.CodePoints (13 ms)
[==========] 488 tests from 53 test suites ran. (697 ms total)
[  PASSED  ] 487 tests.
```
It reports only on failing tests.

Reduce libcudf memcheck tests output

---

cpp/tests/io/orc_test.cpp

The following ORC_TEST tests were intended to be disabed:
```
OrcWriterTest.DISABLE_Over65kColumns
OrcReaderTest.DISABLE_Over65kStripes
OrcReaderTest.DISABLE_Over65kRowGroups
```
Unfortunately they are missing the end `D` and so were not actually disabled. This caused the memcheck nightly build to fail.
Changing `DISABLE_` to `DISABLED_` properly disables the tests.

Disable intended disabled ORC tests

---

python/cudf/cudf/core/column/string.py
python/cudf/cudf/tests/test_string.py

closes https://github.com/rapidsai/cudf/issues/17745
closes https://github.com/rapidsai/cudf/issues/17748
closes https://github.com/rapidsai/cudf/issues/17749
closes https://github.com/rapidsai/cudf/issues/17751

Fix various `.str` methods for pandas compatability

---

cpp/examples/basic/CMakeLists.txt
cpp/examples/billion_rows/CMakeLists.txt
cpp/examples/interop/CMakeLists.txt
cpp/examples/nested_types/CMakeLists.txt
cpp/examples/parquet_io/CMakeLists.txt
cpp/examples/strings/CMakeLists.txt

init_architectures sets this for us and invoking set_architectures before the project call produces the wrong result.

Remove incorrect calls to set architectures

---

.github/workflows/build.yaml
.pre-commit-config.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/136
For nightly builds, some `wheel-build-{project}` jobs currently wait to start until some other `wheel-publish-{dependency}` jobs complete. This is unnecessary... `wheel-build-{dependency}` jobs will upload packages to S3, which is where `wheel-build-{project}` jobs will download them from.
This proposes changing that such that all nightly `wheel-build-*` jobs depend only other `wheel-build-*` jobs. This should decrease the end-to-end time it takes for all wheels to be built and published on nightly / branch builds.
Also updates `pre-commit` config to the latest `rapids-dependency-file-generator` version.

increase parallelism in nightly builds

---

cpp/src/io/parquet/decode_fixed.cu
cpp/src/io/parquet/page_delta_decode.cu

Fixes #17838. Related to #17702
This PR fixes a possible OOB in parquet string decoder when writing initial offset for nested large string cols. Existing tests should have been throwing segfaults in decoder kernels but somehow weren't. The decoder was producing correct results even without this change as the initial offsets are written from the first decoded ColumnChunk of each input column.

Fix possible OOB mem access in Parquet decoder

---

docs/cudf/source/cudf_pandas/index.rst

I changed the link to the cudf-pandas notebook in the docs from the secured link to the new public one
Closes #17845

Update cudf.pandas colab link in docs

---

python/cudf/cudf/pandas/_wrappers/pandas.py
python/cudf/cudf_pandas_tests/test_cudf_pandas.py

Follow up #17629 to make `_Series_dtype` a property. Should fix the nightly integration tests https://github.com/rapidsai/cudf/actions/runs/13026631397/job/36336775867#step:10:28786

Make `_Series_dtype` method a property

---

.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

This PR points the shared workflow branches back to the default 25.02 branches.
xref: https://github.com/rapidsai/build-planning/issues/139

Revert CUDA 12.8 shared workflow branch changes

---

ci/cudf_pandas_scripts/third-party-integration/test.sh

This PR fixes this nightly CI failure: https://github.com/rapidsai/cudf/actions/runs/13067745114/job/36478210419#step:10:16 in the cudf.pandas 3rd-party integration tests.

Remove extra local var declaration from cudf.pandas 3rd-party integration shell script

---

cpp/include/cudf/io/orc_metadata.hpp
cpp/src/io/functions.cpp
cpp/src/io/orc/dict_enc.cu
cpp/src/io/orc/orc.cpp
cpp/src/io/orc/orc.hpp
cpp/src/io/orc/orc_field_reader.hpp
cpp/src/io/orc/orc_field_writer.hpp
cpp/src/io/orc/orc_gpu.hpp
cpp/src/io/orc/reader_impl_chunking.cu
cpp/src/io/orc/reader_impl_chunking.hpp
cpp/src/io/orc/reader_impl_decode.cu
cpp/src/io/orc/reader_impl_helpers.cpp
cpp/src/io/orc/reader_impl_helpers.hpp
cpp/src/io/orc/stats_enc.cu
cpp/src/io/orc/stripe_data.cu
cpp/src/io/orc/stripe_enc.cu
cpp/src/io/orc/stripe_init.cu
cpp/src/io/orc/writer_impl.cu
cpp/src/io/orc/writer_impl.hpp

Moving forward with removal of the (redundant) `gpu` namespace in cuIO.
Also moved the entire ORC implementation to `cudf::io::orc::detail`, leaving only the implementation of the public API in `cudf::io::orc`.
Also removed a few unused headers, or moved them to be included in the right files.

Remove `orc::gpu` namespace

---

python/cudf/cudf/pandas/_wrappers/numpy.py
python/cudf/cudf_pandas_tests/test_cudf_pandas.py

`data` attribute of numpy should be marked private as it actually points to the underlying memory and it will be distinct for a cupy array.

Fix `numpy` data access by making attribute private

---

cpp/include/cudf/io/orc_metadata.hpp
cpp/src/io/functions.cpp
cpp/src/io/orc/aggregate_orc_metadata.cpp
cpp/src/io/orc/orc.cpp
cpp/src/io/orc/orc.hpp
cpp/src/io/orc/orc_field_reader.hpp
cpp/src/io/orc/orc_field_writer.hpp
cpp/src/io/orc/orc_gpu.hpp
cpp/src/io/orc/reader_impl_chunking.cu
cpp/src/io/orc/reader_impl_chunking.hpp
cpp/src/io/orc/reader_impl_decode.cu
cpp/src/io/orc/stripe_data.cu
cpp/src/io/orc/stripe_enc.cu
cpp/src/io/orc/stripe_init.cu
cpp/src/io/orc/writer_impl.cu
cpp/src/io/orc/writer_impl.hpp

Some older code in the ORC reader/writer uses PascalCase, which is not used in the rest of libcudf. This PR renames such functions and types to align the style with the rest of the code base.
The types that are based on the ORC specs are kept as PascalCase to make it easy to identify such types.

Rename PascalCase functions and types to to snake_case to improve consistency

---

python/cudf/cudf/core/join/join.py
python/cudf/cudf/tests/test_joining.py

closes https://github.com/rapidsai/cudf/issues/17902

Raise NotImplementedError if `.merge(suffixes=)` introduces duplicate labels

---

ci/run_pylibcudf_pytests.sh
ci/test_python_common.sh
ci/test_python_cudf.sh
python/pylibcudf/.coveragerc

This is a small change adding a script to run pylibcudf tests, like we have for other Python libraries in this repository.

Add script to run pylibcudf tests

---

conda/recipes/cudf/meta.yaml
conda/recipes/pylibcudf/meta.yaml

Currently pylibcudf does not export a dependency on libcudf at all, which is incorrect.

Add missing pin

---

ci/build_wheel.sh
ci/build_wheel_libcudf.sh
ci/configure_cpp_static.sh
ci/test_cudf_polars_polars_tests.sh
ci/test_wheel_cudf.sh
ci/test_wheel_cudf_polars.sh
ci/test_wheel_dask_cudf.sh

Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```

Use `rapids-pip-retry` in CI jobs that might need retries

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

closes https://github.com/rapidsai/cudf/issues/17880
Needed similar handing as the `rolling` case in https://github.com/rapidsai/cudf/pull/17822

Fix groupby scans with int and NA data in mode.pandas_compatible

---

cpp/include/cudf/column/column_device_view.cuh
cpp/src/copying/pack.cpp

With the upcoming CCCL release we moved some includes around and it seems that we relied on transitively including `<functional>` in some files.
Fix that and include all the headers used in at least those two files

Add missing standard includes

---

cpp/include/nvtext/minhash.hpp
cpp/src/text/minhash.cu

Removes `nvtext::minhash_permuted` and `nvtext::minhash64_permuted` APIs deprecated in the previous release.

Remove deprecated nvtext::minhash_permuted APIs

---

.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

This completes the migration to NVKS runners now that all libraries have been tested and https://github.com/rapidsai/shared-workflows/pull/273 has been merged.
xref: https://github.com/rapidsai/build-infra/issues/184

Use shared-workflows branch-25.04

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_rank.py

closes https://github.com/rapidsai/cudf/issues/17948

Fix DataFrame/Series.rank for int and null data in mode.pandas_compatible

---

python/cudf/cudf_pandas_tests/third_party_integration_tests/tests/test_ibis.py

ibis has removed their pandas backend in version 10.0.0. In their release notes,
> pandas: The pandas backend is removed. Note that pandas DataFrames are STILL VALID INPUTS AND OUTPUTS and will remain so for the foreseeable future. Please use one of the other local backends like DuckDB, Polars, or DataFusion to perform operations directly on pandas DataFrames.
This PR removes the pandas backend from the integration tests. And asserts that the inputs and outputs to ibis APIs are proxy objects.

Remove pandas backend from `cudf.pandas` - ibis integration tests

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

xref https://github.com/rapidsai/cudf/issues/17649
For `cudf.pandas`, we will dispatch to pandas instead of silently dropping the duplicate column

Raise NotImplementedError for groupby.agg if duplicate columns would be created

---

python/cudf/cudf_pandas_tests/third_party_integration_tests/dependencies.yaml
python/cudf/cudf_pandas_tests/third_party_integration_tests/tests/test_ibis.py

Follows up #17972. This PR is intended to get 25.02 nightly CI passing, which has been failing for few days.

Pin `ibis` version in the cudf.pandas integration tests <10.0.0

---

cpp/benchmarks/common/generate_input.cu
cpp/benchmarks/groupby/group_max_multithreaded.cpp
cpp/benchmarks/join/join_common.hpp
cpp/include/cudf/detail/utilities/cast_functor.cuh
cpp/include/cudf/reduction/detail/reduction_operators.cuh
cpp/include/cudf_test/column_wrapper.hpp
cpp/src/groupby/sort/group_merge_m2.cu
cpp/src/groupby/sort/group_scan_util.cuh
cpp/src/groupby/sort/group_single_pass_reduction_util.cuh
cpp/src/groupby/sort/sort_helper.cu
cpp/src/io/json/json_normalization.cu
cpp/src/join/hash_join.cu
cpp/src/join/join_utils.cu
cpp/src/lists/combine/concatenate_list_elements.cu
cpp/src/lists/interleave_columns.cu
cpp/src/reductions/scan/scan_inclusive.cu
cpp/src/sort/rank.cu
cpp/src/stream_compaction/unique.cu
cpp/src/strings/search/contains_multiple.cu
cpp/tests/iterator/iterator_tests.cuh
cpp/tests/iterator/value_iterator_test_transform.cu
cpp/tests/rolling/collect_ops_test.cpp
cpp/tests/stream_compaction/apply_boolean_mask_tests.cpp
cpp/tests/transform/row_bit_count_test.cu
cpp/tests/utilities/column_utilities.cu

This PR removes the usage of the deprecated `thrust::identity` and replaces it with `cuda::std::identity` where applicable. In cases where `thrust::identity` was used as a type conversion callable and `cuda::std::identity` is not suitable, it uses a new utility called `cast_fn` in the `detail` namespace.

Get rid of the deprecated `thrust::identity`

---

cpp/include/cudf/utilities/span.hpp

Closes https://github.com/rapidsai/cudf/issues/17949
Closes https://github.com/rapidsai/cudf/issues/17960
Derived span classes use `size_type` for the index type in their `operator[]` implementations. The intent was to use `base::size_type`, but the type actually resolves to `cudf::size_type`, which is `int32_t`, and does not allow access past `int32_t::max`.
This PR fixes the type used by explicitly using `typename base::size_type`. Also added static_asserts to make sure the type has the right size for element indexing.

Fix the index type in the indexing operator of the span types

---

cpp/src/groupby/hash/compute_aggregations.cuh
cpp/src/groupby/hash/compute_shared_memory_aggs.cu
cpp/src/groupby/hash/compute_shared_memory_aggs.hpp
cpp/src/groupby/hash/shared_memory_aggregator.cuh

Replace https://github.com/rapidsai/cudf/pull/17976
This fixes the race check failures in shared memory groupby and resolves https://github.com/NVIDIA/spark-rapids/issues/11835.

Fix race check failures in shared memory groupby

---

python/dask_cudf/dask_cudf/_expr/__init__.py
python/dask_cudf/dask_cudf/_expr/collection.py

Moves the import of get_collection_type. It's been available from `dask.dataframe` since at least `dask>=2024.12.1`
xref https://github.com/dask/dask/pull/11689 and the CI failure at https://github.com/rapidsai/cudf/actions/runs/13286927884/job/37100164792?pr=17929

Compatibility with Dask `main`

---

python/cudf/cudf_pandas_tests/third_party_integration_tests/tests/test_ibis.py

Follows up #17972 to fix one more failing ibis test. The PR ensures the ibis test is deterministic by returning the aggregation in sorted order.

Fix failing ibis test

---

cpp/src/io/utilities/data_sink.cpp
cpp/src/io/utilities/datasource.cpp

KvikIO has just introduced a breaking change (https://github.com/rapidsai/kvikio/pull/608) where the compatibility mode handling is delegated to `CompatModeManager`. This PR updates the way cuDF queries the compatibility mode to avoid build errors.

Fix the build error due to KvikIO update

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/_internals/timezones.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/join/join.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/resample.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/subword_tokenizer.py
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/core/tools/numeric.py
python/cudf/cudf/core/window/ewm.py
python/cudf/cudf/core/window/rolling.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_datetime.py
python/cudf/cudf/tests/test_string_udfs.py
python/cudf/cudf/utils/utils.py

Broken off from https://github.com/rapidsai/cudf/pull/17978
This passes more dtype objects to `Column.astype` but does not _ensure_ that a dtype object is passes unlike in https://github.com/rapidsai/cudf/pull/17978
Also it appears we avoid surfacing from warnings from pandas within our tests.

Pass dtype objects to Column.astype

---

.github/workflows/spark-rapids-jni.yaml

spark-rapids-jni is going to drop support for the 12.2.0 CI image, 
this change is to switch image version to cuda12.8.0 one https://hub.docker.com/r/rapidsai/ci-spark-rapids-jni/tags

Update spark-rapids-jni CI image version to cuda12.8.0

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/dtypes.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/join/_join_helpers.py
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/tests/test_dataframe.py

Broken off from https://github.com/rapidsai/cudf/pull/17978

Pass more dtype objects to `astype` calls

---

cpp/src/io/parquet/reader_impl_preprocess.cu
cpp/tests/io/parquet_chunked_reader_test.cu

Fixes  https://github.com/rapidsai/cudf/issues/18043
An incorrect computation in the subpass generation code would come to the conclusion that there weren't enough rows to decode for list columns under certain circumstances.  
This PR fixes the issue and I did a little bit of variable naming cleanup around the area.  Ultimately the true source of the bug was poorly named variables causing them to be used incorrectly.
Edit: I've disabled various checks in the chunked reader tests that expect specific chunk counts being returned from chunking operations.  Changes to decompression temporary memory usage can make this unreliable.  We will need a smarter solution down the road.

Fix 'Unexpected short subpass' exception in parquet chunked reader.

---

python/dask_cudf/dask_cudf/_expr/__init__.py
python/dask_cudf/dask_cudf/_expr/expr.py

The upstream [test_gpu_loc dask test is failing](https://github.com/rapidsai/dask-upstream-testing/actions/runs/13419658348/job/37489003426), and the culprit seems to be https://github.com/dask/dask/pull/11745
I don't see anything "wrong" with the changes in that PR. However, the divisions assertion is now sensitive to the fact that an  element of divisions can end up being a 0-dimensional cupy arrays for GPU-backed data. The `test_gpu_loc` feels like a pretty strange corner case to me. So, this PR proposes a temporary fix in dask-cudf.

Fix upstream dask `loc` test

---

cpp/src/copying/concatenate.cu

`cudaMemcpyAsync` can return a `cudaError_t` value which should be checked for runtime errors. 
We should preserve the behavior of `thrust::copy` which got replaced with the `cudaMemcpyAsync` call in #17584. The driver may do the right thing and infer the source and destination pointer location instead of using the `cudaMemcpyKind`, but this still leads to weird circumstances where the copy type in code is DtoD while the actual copy at runtime is HtoD

Fix memcopy direction for concatenate

---

cpp/src/io/fst/dispatch_dfa.cuh

I accidentally used `CCCL_VERSION_MAJOR`, which is used in our cmake scripts

Use the right version macro `CCCL_MAJOR_VERSION`

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_reshape.py

Additionally, refactors `melt` to avoid Series/DataFrame constructors by operating on columns and passing the result to `_from_data`
```python
In [1]: import numpy as np, cudf
In [2]: df = cudf.DataFrame(np.ones((1000, 1000)))
In [3]: %timeit df.melt(id_vars=range(50, 300))   # this PR
1.35 s ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [3]: %timeit df.melt(id_vars=range(50, 300))  # branch-25.04
24.8 s ± 47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Support melt(ignore_index=False)

---

python/cudf/CMakeLists.txt
python/cudf_kafka/CMakeLists.txt
python/pylibcudf/CMakeLists.txt

The `cython_lib_dir` was removed as part of the switch to publishing a libcudf wheel.

Remove unused var

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_spilling.py

closes https://github.com/rapidsai/cudf/issues/18088
Before the old Cython bindings of `columns_split` spill locked the conversion from libcudf to a cudf Python column. When I replaced these bindings, this spill locking was removed during the refactor.
I'm spot checking that other APIs are not affected. If so I can open PRs for those

Fix scatter_by_map with spilling enabled

---

python/cudf_polars/tests/test_scan.py

The current implementation of `test_scan_csv_multi` does not work if the compute task is run on distinct worker processes (because it changes directory in lieu of using a proper file path).

Fix `test_scan_csv_multi` cudf-polars test

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_reductions.py

xref https://github.com/rapidsai/cudf/pull/16313
Deprecated in 24.08

Enforce deprecation of dtype parameter in sum/product

---

cpp/tests/rolling/offset_row_window_test.cpp

Fixes #18079.
This commit fixes the failures reported in #18079, where the use of static column vector objects in the tests causes the use of a CUDA runtime context before it's been initialized, causing the tests to fail with:
```
parallel_for failed: cudaErrorInvalidResourceHandle: invalid resource handle
```
The solution is to switch the static column vectors to runtime, as a member of the test utility class `rolling_runner`.

Remove static column vectors from window function tests.

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_reshape.py

closes https://github.com/rapidsai/cudf/issues/12410
closes https://github.com/rapidsai/cudf/issues/12409
The fix just mirrors the pandas logic.

Allow pivot_table to accept single label index and column arguments

---

docs/cudf/source/conf.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/dtypes.py
python/cudf/cudf/core/scalar.py

Broken off (the non-breaking parts) from https://github.com/rapidsai/cudf/pull/18035/ as that PR will probably not move forward since it would require a pyarrow minimum version bump to 19

Simplify DecimalDtype and DecimalColumn operations

---

.github/workflows/build.yaml

We use `cpu16` for PR jobs that build libcudf (conda and wheels). We also need to use `cpu16` for the corresponding jobs in `build.yaml`.

Use cpu16 for build CI jobs

---

cpp/benchmarks/common/random_distribution_factory.cuh
cpp/src/column/column_device_view.cu
cpp/src/io/functions.cpp
cpp/src/io/json/host_tree_algorithms.cu
cpp/src/io/json/read_json.cu
cpp/src/io/orc/aggregate_orc_metadata.cpp
cpp/src/io/orc/writer_impl.cu
cpp/src/io/parquet/reader_impl_chunking.cu
cpp/src/io/parquet/writer_impl.cu
cpp/src/lists/dremel.cu
cpp/src/strings/regex/regex.cuh
cpp/src/strings/replace/multi_re.cu
cpp/src/table/row_operators.cu
cpp/src/text/bpe/load_merge_pairs.cu
cpp/tests/groupby/tdigest_tests.cu
cpp/tests/io/metadata_utilities.cpp
cpp/tests/io/parquet_writer_test.cpp
cpp/tests/reductions/scan_tests.cpp

There are some files that use `std::function` and it seems they were relying on transitive includes from CCCL headers because building cudf fails with CCCL 2.8, which is the next CCCL release in line for rapids

Add include for `<functional>`

---

python/cudf/cudf/core/df_protocol.py
python/cudf/cudf/core/subword_tokenizer.py
python/cudf/cudf/tests/test_dlpack.py

This PR adapts cudf's dlpack tests for compatibility with cupy 13.4, which was just released yesterday on PyPI and containers https://github.com/cupy/cupy/pull/8722 that breaks the legacy toDlpack functionality.

Use protocol for dlpack instead of deprecated function

---

cpp/src/io/utilities/config_utils.cpp

KvikIO has changed the function names of the config setters to improve clarity (https://github.com/rapidsai/kvikio/pull/644). This PR updates the setter calls in cuDF accordingly.

Update calls to KvikIO's config setter

---

.github/workflows/pr.yaml
cpp/src/io/orc/writer_impl.cu
cpp/src/utilities/host_memory.cpp
cpp/tests/CMakeLists.txt

Closes #18059
To avoid estimating the maximum compressed size for each actual block in the file, ORC writer uses the estimate for the (uncompressed) block size limit, which defaults to 256KB. However, when we write many small blocks, this compressed block size estimate is much larger than what is needed, leading to high memory use for wide/short tables.
This PR adds logic to take the actual block size into account, and to use the size of the actual largest block in the file, not the largest possible block. This changes the memory usage by orders of magnitude in some tests.

Reduce memory use when writing tables with very short columns to ORC

---

ci/run_cudf_polars_pytests.sh

This test is failing in multiple places right now, such as [this run](https://github.com/rapidsai/cudf/actions/runs/13595690128/job/38014725800) on https://github.com/rapidsai/cudf/pull/18133 and [this run](https://github.com/rapidsai/cudf/actions/runs/13636334843/job/38118996773?pr=18136) on https://github.com/rapidsai/cudf/pull/18136. Let's skip it until we can debug why so that we unblock other CI.

Skip failing test

---

cpp/include/cudf/strings/string_view.cuh

Slight optimization improvement sets the character count in the `cudf::string_view` produced by `cudf::string_view::substr` when the number of output characters is known. This can save redundant character counting in downstream usage of the new string.

Optimization improvement for substr in cudf::string_view

---

python/cudf/cudf/core/column/methods.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/udf/groupby_utils.py
python/cudf/cudf/utils/utils.py

Noticed while working on https://github.com/rapidsai/cudf/pull/18141.
Also made some imports more specific to make it easier to see what we need

Remove some unnecessary module imports

---

python/cudf/cudf/api/types.py
python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/join/_join_helpers.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/scalar.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/core/tools/numeric.py
python/cudf/cudf/core/window/ewm.py
python/cudf/cudf/io/dlpack.py
python/cudf/cudf/testing/testing.py
python/cudf/cudf/utils/dtypes.py
python/cudf/cudf/utils/utils.py

Avoids using potentially more expensive dtype checking utilities referenced in https://github.com/rapidsai/cudf/issues/12494
`is_string_dtype` -> `== CUDF_STRING_DTYPE`
`is_decimal_dtype` -> `isinstance`
`is_numeric_dtype` -> (new) `is_dtype_obj_numeric`
```python
In [1]: import numpy as np
In [2]: from cudf.api.types import is_numeric_dtype
In [3]: from cudf.utils.dtypes import is_dtype_obj_numeric
In [4]: dtype = np.dtype(np.int64)
In [5]: %timeit is_dtype_obj_numeric(dtype)
211 ns ± 2.26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [6]: %timeit is_numeric_dtype(dtype)
1.14 μs ± 2.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
Also standardizes some imports from `cudf.api.types`

Use more, cheaper dtype checking utilities in cudf Python

---

cpp/examples/interop/interop.cpp
python/pylibcudf/pylibcudf/libcudf/filling.pxd

Found this misspelled word while working on other things.

Minor typo fix in filling.pxd

---

conda/recipes/libcudf/recipe.yaml

With the transition to rapids-logger libcudf no longer has a direct dependency on fmt. However, the benchmarks still have a transitive dependency via nvbench. Interestingly, the google benchmarks also seem to have a dependency there and I have not uncovered why yet. With the merge of https://github.com/rapidsai/rapids-cmake/pull/790, builds using rapids-cmake no longer require a patched version of fmt anywhere, which is resulting in benchmark builds picking up fmt from the environment. This results in overlinking issues for the benchmarks binaries, and if the check is disabled the binaries fail at runtime since fmt will not be present in the runtime environment. This PR temporarily patches this issue by adding the dependency until we can figure out how we want to deal with it going …

Add fmt to the test/benchmarks env

---

ci/run_cudf_polars_pytests.sh

This PR skips a flaky test for the experimental dask engine for polars. An example failure is https://github.com/rapidsai/cudf/actions/runs/13705493794/job/38331727822?pr=18175

Skip flaky multi GPU test

---

cpp/include/cudf/ast/detail/operators.hpp

This drops the final use of `thrust::optional` in cuDF

More minor fixes for CCCL

---

build.sh

`build.sh` provides incorrect descriptions of the default behavior. This fixes it.

Fix build.sh docs for default behavior

---

conda/recipes/libcudf/recipe.yaml
rapids_config.cmake

This reverts #18173. Now that https://github.com/rapidsai/rapids-cmake/pull/792 is in we should be set to properly avoid libfmt linkage.

Drop unnecessary fmt dep

---

python/cudf/cudf/core/join/join.py
python/cudf/cudf/tests/test_joining.py

closes https://github.com/rapidsai/cudf/issues/18153
This fix a bit more conservative than what was initially done in https://github.com/rapidsai/cudf/pull/17739. 
Before, we were modifying the `_using_left_index/_using_right_index` attributes which affects other merge operations besides setting the result index. Now, this PR scopes a specific attribute to determine when to set a `RangeIndex` in the result

Fix merge(how=left, left_on=, right_index=True, sort=True)

---

conda/recipes/libcudf/recipe.yaml

Similar to #18161, this PR ignores some run-exports that are too tight.
I caught this bug in #18183.

Ignore run exports of libcufile.

---

docs/cudf/source/pylibcudf/api_docs/contiguous_split.rst
docs/cudf/source/pylibcudf/api_docs/index.rst

This module was missing from the API docs.

Added pylibcudf.contiguous_split to API docs

---

ci/build_cpp.sh

This fixes an issue where local reproductions of CI fail with the following error:
```
╭─ Finding outputs from recipe
│ Loading variant config file: "/cudf/conda/recipes/libcudf/conda_build_config.yaml"
│
╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe
Error:
× failed to render Jinja expression: invalid operation: Environment variable RAPIDS_ARTIFACTS_DIR not found (in <string>:1)
╭─[conda/recipes/libcudf/recipe.yaml:45:31]
44 │         PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
45 │         RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR") }}
·                               ───────────────────┬──────────────────
·                                                  ╰── invalid operation: Environment variable RAPIDS_ARTIFACTS_DIR not found
46 │ …
```

Ensure RAPIDS_ARTIFACTS_DIR is set for build metrics reports.

---

conda/recipes/cudf/recipe.yaml

`cudatoolkit` was version constrained to >=11.8 because of an inherited run
export, causing older versions to be installed on CI runs (see
https://github.com/rapidsai/cudf/actions/runs/13714799167/job/38378393950)
This removes that constraint.

fix(rattler): add `cudatoolkit` ignore run export to `cudf`

---

python/cudf/cudf/tests/test_array_ufunc.py
python/cudf/cudf/tests/test_unaops.py

Updating the xfail condition in https://github.com/rapidsai/cudf/pull/18128 to capture that this behavior will be fixed in cupy 14 (https://github.com/cupy/cupy/issues/9018#issuecomment-2705550983) so we can avoid failures here when cupy 14 is released

Update Numpy <2.1 unpinning xfail condition

---

.github/workflows/pr.yaml

Bumps the nightly check limit while we investigate/fix cuDF CI failures

Bump nightly check limit

---

conda/recipes/pylibcudf/recipe.yaml

As observed in
https://github.com/rapidsai/cudf/actions/runs/13759152380/job/38471497911, the
amd64, cuda 11.4 environment isn't running against the packages built in the
previous nightly `build` step.
Adding one more missing run export to undo the unintentional pin to `cudatoolkit>=11.8` in `pylibcudf`

Add missing `cudatoolkit` run_export ignore to `pylibcudf`

---

.github/workflows/pr.yaml
cpp/src/text/bpe/load_merge_pairs.cu
cpp/src/text/subword/load_hash_file.cu

This works around CI failures on ARM build machines where single space literal character array is not working properly.
Minimal example of failures found
```
auto input = std::string("string with spaces");
auto space = std::string(" ");
auto sview = std::string_view(" ");
auto schar = " ";
input.find(' ') works
input.find(" ") fails
input.find(space) works
input.find(sview) fails
input.find(schar) fails
```

Workaround for ARM compiler issue with single space literal string

---

conda/recipes/cudf/recipe.yaml
conda/recipes/pylibcudf/recipe.yaml

The `cudatoolkit` export is inherited from the cuda compilers
metapackage, so ignoring `from_package` won't catch it.

Ignore `cudatoolkit` run exports by name, not package

---

ci/build_cpp.sh

Fix for #18192. The environment variables `RAPIDS_ARTIFACTS_DIR` is now exported, so that `rattler-build` can see it.
I verified this works for local reproductions of CI builds.

Export RAPIDS_ARTIFACTS_DIR.

---

cpp/cmake/Modules/JitifyPreprocessKernels.cmake

This fixes our jitify preprocessing commands to use include directories from the libcudacxx (CCCL) target that cuDF is using, rather than falling back to the CUDA Toolkit version.
This was removed earlier in commit 38616feaf04fcc1c410b1f1454c7a97bd0873ca5, perhaps by accident, but went unnoticed because the bundled CUDA Toolkit libcudacxx was sufficient.

Use CCCL::libcudacxx include directories in Jitify preprocessing.

---

ci/cudf_pandas_scripts/run_tests.sh

Follow up of #16930 [comment](https://github.com/rapidsai/cudf/pull/16930#discussion_r1989879989).

Explain why we disable parallelism for profiler tests to avoid pytest-cov issue

---

python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/tests/test_datetime.py

Fixes: #17740 
This PR fixes max time resolution of datetime binops with `datetime` scalars.

Fix `datetime64` vs `datetime` binops max resolution

---

ci/test_narwhals.sh

Skips the tests for now so that nightly CI passes. We need to investigate the tests we skip to see which ones can be fixed. Tracking Issue for that work is in https://github.com/rapidsai/cudf/issues/18248

Skip Narwhals cross join tests for cudf.pandas CI run

---

conda/recipes/cudf_kafka/recipe.yaml

I missed this `ignore_run_export` in the previous round of fixes, but it is still constraining cuda 11.x environments:
https://github.com/rapidsai/cudf/actions/runs/13804299839/job/38612724166#step:9:5077
Maybe this is the last one of these.

Fix `cudf_kafka` run export for `cudatoolkit`

---

ci/run_cudf_polars_pytests.sh
python/cudf_polars/tests/experimental/test_dataframescan.py
python/cudf_polars/tests/experimental/test_groupby.py
python/cudf_polars/tests/experimental/test_join.py

This fixes a few experimental cudf-polars tests (due to https://github.com/rapidsai/cudf/issues/18228), and reduces the scope of distributed tests to the `tests/experimental` directory.

Fix experimental cudf-polars tests

---

.github/workflows/pr.yaml
conda/recipes/libcudf/recipe.yaml

This PR disables part of rattler-build's process for making packages relocatable ([see the conda-build docs](https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html)) because it was resulting in an unsafe modification to libcudf binaries. A much longer writeup is in #18251.
Fixes #18251

Disable conda prefix patching to avoid mangling binaries

---

docs/cudf/source/user_guide/api_docs/index.rst
docs/cudf/source/user_guide/api_docs/wordpiece_tokenizer.rst

Add `WordPieceVocabulary` and `tokenize` to the cudf docs.

[DOC] Add wordpiece tokenizer to cudf documentation

---

python/cudf_polars/cudf_polars/testing/plugin.py

We can reevaluate adding it back once we depend on a version of polars with pola-rs/polars/pull/21721.

Skip failing polars test test_general_prefiltering

---

ci/cudf_pandas_scripts/run_tests.sh

Makes some of the failing nightly cudf.pandas tests pass. Eg. https://github.com/rapidsai/cudf/actions/runs/13824856866/job/38681644861. For now we exclude them from a parallel run, but we have an open issue to root cause the reason why they can't be run in parallel.

Filter all cudf.pandas profiler tests from running in parallel

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #18242 
This PR fixes two issues in `DataFrame.loc`:
1. Inplace modification of the original dataframe.
2. Returning series instead of dataframe for a specific combination of `loc` inputs.

Fix `Dataframe.loc` to not modify the actual dataframe

---

ci/test_narwhals.sh
python/cudf/cudf/core/join/join.py
python/cudf/cudf/tests/test_joining.py

Contributes to #18248. This PR fixes failures in narwhals pytest suite by fixing `cross` join in `cudf` to properly suffix columns and factor in extra columns.

Fix `cross` join with extra columns

---

cpp/src/io/comp/comp.cpp
cpp/src/io/json/read_json.cu
cpp/src/utilities/stream_pool.cpp

When `get_streams` requests more streams than there are in the pool, the pool returns existing streams in round-robin order. We originally included this warning because the behavior might be surprising to the caller. However, this warning just clutters the logs when we don't add extra logic to make sure we don't ask for more streams than available.
Removing the warning and cleaning up call sites.

Remove warning in the stream pool when asking for more streams than available

---

python/cudf_polars/cudf_polars/experimental/base.py
python/cudf_polars/cudf_polars/experimental/groupby.py
python/cudf_polars/cudf_polars/experimental/join.py
python/cudf_polars/cudf_polars/experimental/parallel.py
python/cudf_polars/cudf_polars/experimental/shuffle.py

In the dask-graph, use the splat operator instead of list arguments everywhere. The splat operator is used in most places already, only a few functions are missing.
This makes it easier to transform the dask-graph after its creation, which will be useful for prototyping.

dask-polars: use splat everywhere.

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/experimental/groupby.py
python/cudf_polars/cudf_polars/experimental/join.py
python/cudf_polars/cudf_polars/experimental/shuffle.py
python/cudf_polars/cudf_polars/utils/config.py
python/cudf_polars/tests/experimental/test_join.py
python/cudf_polars/tests/experimental/test_shuffle.py

**NOTE**: This is intended to be the precursor for #18231
this PR adds the `"broadcast_join_limit"` config option, and revises configuration handling in `Join`, `GroupBy`, and `Shuffle`.

Add and revise experimental cudf-polars config options

---

ci/test_narwhals.sh

closes https://github.com/rapidsai/cudf/issues/18248
With each test skipped, linked to an issue or comment that describes the rational. 
I think we can close out the parent issue as the follow ups have individual issues to track.

Split Narwhals cudf.pandas tests failures into to fix and to skip

---

python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/tests/test_column_from_device.py

Follow up to #15615. The cuda array interface [specification](https://numba.readthedocs.io/en/stable/cuda/cuda_array_interface.html) for a device array with `strides=None` is a C-contiguous layout.
Contributes to #15132

Make a pylibcudf Column from a device array object with `strides=None`

---

ci/test_narwhals.sh
python/cudf/cudf/testing/narwhals_test_plugin.py

The narwhals tests are failing due to a new Narwhals release (1.31) and polars release (1.25). The majority of the failures are in the polars pytest run. They will be fixed in #18132 which will update our polars version pinning to 1.25. 
The remaining tests which fail during the cudf and cudf.pandas pytest runs are skipped/xfailed in this PR. They fail because duckdb is not installed as a test dependency in Narwhals. Is it missing somewhere in https://github.com/narwhals-dev/narwhals/blob/main/pyproject.toml?
CC @MarcoGorelli

xfail narwhals sqlframe tests

---

cpp/include/cudf/rolling.hpp
cpp/src/rolling/grouped_rolling.cu

The new API for aggregating multiple columns in a single `grouped_range_rolling_window` call has some issues when trying to use it from cython.
To avoid rewriting a public API between 25.04 and 25.06, let's just remove it, leaving only the detail API for now.

Remove unused `group_range_rolling_window` API

---

cpp/include/cudf/ast/detail/expression_evaluator.cuh
cpp/tests/join/mixed_join_tests.cu

Fixes https://github.com/rapidsai/cudf/issues/18321
cast is unary operator in AST and Right index is defaulted to zero. This error passing the index to `resolve_input`.

Fix index of right table in unary operators in AST, in Joins

---

cpp/include/cudf/ast/detail/expression_evaluator.cuh
cpp/tests/join/mixed_join_tests.cu

Backport of #18333 to 25.04. This bug fix will be needed for Velox-cuDF to use the stable 25.04 release.

Backport: Fix index of right table in unary operators in AST, in Joins

---

cpp/src/lists/sequences.cu

Closes https://github.com/rapidsai/cudf/issues/18100
This PR simplifies the code for `sequences` by introducing `make_offsets_child_column`, which also reduces the runtime of `sequences`.
I generated `starts` and `sizes` for `num_rows`, where all `start` values are 1 and all `size` values are 5.
Here is the result of the benchmark:

Optimize `sequences` by introducing `make_offsets_child_column`

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
conda/recipes/custreamz/recipe.yaml
conda/recipes/libcudf/conda_build_config.yaml
dependencies.yaml
python/custreamz/pyproject.toml

There appears to be a conda solve conflict between `cuspatial` & `custreamz`/`libcudf_kafka`.
I think it ultimately stems from `lz4-c` pinnings. `cuspatial`'s dependencies require `lz4-c >=1.10.0,<1.11.0a0`, but `libcudf_kafka`'s `librdkafka >=2.5.0,<2.6.0a0` requires `lz4-c >=1.9.3,<1.10.0a0`.
Bumping `librdkafka` to `>=2.8.0` should resolve this conflict.

Bump librdkafka to 2.8.0

---

docs/cudf/source/cudf_pandas/usage.md

Adding a note about restarting the kernel when needed in the cudf pandas usage docs
xref: https://github.com/rapidsai/rapids.ai/pull/437#issuecomment-2744449620

Add restart kernel note in cudf pandas docs

---

python/cudf_polars/cudf_polars/testing/plugin.py

Warnings are treated as errors, so we're skipping the tests for now.

Skip polars tests that fail with pydantic deprecation warnings

---

python/dask_cudf/dask_cudf/_expr/collection.py
python/dask_cudf/dask_cudf/tests/test_core.py

Aligns with recent task-spec changes in Dask. The ideal fix is probably in [create_array_collection](https://github.com/dask/dask/blob/4399aef0bfcba1a57d15cce458d6464fb7c0af2b/dask/array/_array_expr/_backends.py#L23), where the output `Array` object is **not** created with `meta` (needed for cupy-backed arrays).

Update Dask array-conversion handling

---

dependencies.yaml

Closes https://github.com/rapidsai/cudf/issues/18391
This PR sets the cmake version range in `test_java` to be [3.30.4, 4.0.0), allowing us to side step the issue linked due to the java native build needing to build thrift.
I am not 100% sure about this change, as I don't think I have a way to test this locally.

Pin cmake in test_java to be less than 4.0.0

---

ci/test_narwhals.sh

In cuDF, we test Narwhals in CI using three separate test calls:
1. cudf-classic
2. cudf-polars (the Polars GPU executor)
3. cudf.pandas
We test against a "stable" branch of Narwhals, which is only updated when Narwhals makes a new release.
However, because Narwhals releases more frequently than cuDF, this branch isn't truly stable and often 
causes our CI to fail after a new Narwhals release.
The tests below [fail](https://github.com/rapidsai/cudf/actions/runs/14190187843/job/39752908239) during the cudf-polars pytest run when using cuDF release 25.04, which supports Polars 
versions 1.24 to 1.25 (inclusive). The failures occur with Polars 1.24 and Narwhals 1.33, but they pass with 
Polars 1.24 + Narwhals 1.32 and also with Polars 1.26 + Narwhals 1.33. 
I'm temporarily skipping these …

Skip failing Narwhals rolling groupy tests

---

cpp/cmake/thirdparty/get_zstd.cmake

zstd [warns](https://github.com/facebook/zstd/blob/0c3345d6ec207c5207cb2b9bd50a32a0c709228b/build/cmake/lib/CMakeLists.txt#L156) (but behaves as expected) if `BUILD_SHARED_LIBS` conflicts with the zstd-specific CMake options. This change silences that warning.

Silence warning by setting BUILD_SHARED_LIBS

---

python/pylibcudf/pylibcudf/column.pxd
python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/io/avro.pyx
python/pylibcudf/pylibcudf/io/csv.pyx
python/pylibcudf/pylibcudf/io/json.pyx
python/pylibcudf/pylibcudf/io/orc.pyx
python/pylibcudf/pylibcudf/io/parquet.pxd
python/pylibcudf/pylibcudf/io/parquet.pyx
python/pylibcudf/pylibcudf/io/types.pxd
python/pylibcudf/pylibcudf/io/types.pyx
python/pylibcudf/pylibcudf/scalar.pyx
python/pylibcudf/pylibcudf/table.pxd
python/pylibcudf/pylibcudf/table.pyx

When we take ownership of a table/column from libcudf we construct an rmm DeviceBuffer via a DeviceBuffer's from_unique_ptr. This latter takes a stream argument, defaulting to the default stream (the per thread default stream if RMM was compiled with PTDS enabled). If RMM determines that the stream we're taking ownership on is the default stream, it syncs the stream.
In the newly stream-aware IO routines, by not providing the user's stream when taking ownership of data from libcudf, we incur more stream syncs than necessary. To avoid this, plumb through the explicit user stream when taking ownership.
- Closes #18356

Pass stream through when taking ownership from libcudf

---

cpp/src/io/comp/comp.cpp
cpp/src/io/comp/comp.hpp
cpp/src/io/comp/io_uncomp.hpp
cpp/src/io/comp/uncomp.cpp
cpp/src/io/json/write_json.cu
cpp/src/io/orc/aggregate_orc_metadata.cpp
cpp/src/io/orc/orc.cpp
cpp/src/io/orc/orc.hpp
cpp/tests/io/comp/comp_test.cpp
cpp/tests/io/json/json_chunked_reader.cu
cpp/tests/io/json/json_test.cpp
cpp/tests/large_strings/json_tests.cu

Host decompression and compression have race conditions mostly because of the incorrect assumption that the pinned buffers are deallocated in stream-ordered way. However, this is only the case of the allocations in the pinned pool. Vectors allocated when the pool is full are deallocated immediately in the destructor, so we can't assume stream ordering at the end of the scope.
Fixed several race conditions in host compression and decompression:
1. Use `cuda_memcpy` instead of `cuda_memcpy_async` at the end of host decompression AND compression because, without synchronization, the host buffer with results can be deallocated before the copy is performed.
2. Use `make_pinned_vector_sync` instead of `make_pinned_vector_async` when creating the decompression output buffer because the buffer is …

Fix synchronization issues in host compression and decompression

---

dependencies.yaml
python/cudf/cudf/tests/test_parquet.py

We observed nightly failures due to a bad conda solve that fetched outdated cudf-related packages. The root cause is that due to https://github.com/rapidsai/cudf/pull/18370, `cudf_kafka`'s dependency tree requires a newer `lz4-c` than what we can get from `pyarrow==14.*`. Therefore, we must bump the "oldest" pinning we test for `pyarrow` to `pyarrow==15.*` in order to have a compatible `lz4-c` library.

Use pyarrow 15 in oldest dependency CI jobs

---

python/cudf_polars/cudf_polars/dsl/ir.py

This is a backport of https://github.com/rapidsai/cudf/pull/18351 to fix flaky tests in the cudf.polars experimental module.

Backport: Deterministic hashing for DataFrameScan nodes in cudf-polars multi-partition executor (#18351)

---

python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/gpumemoryview.pxd
python/pylibcudf/pylibcudf/gpumemoryview.pyx

Closes #18324. `Py_ssize_t` is signed and typically used for indexing based on this [stack overflow dicussion](https://stackoverflow.com/questions/20987390/cython-why-when-is-it-preferable-to-use-py-ssize-t-for-indexing). I think we simplify the ptr type by switching it to `uintptr_t` instead.

Switch the ptr type in gpumemoryview from Py_ssize_t to uintptr_t

---

python/pylibcudf/pylibcudf/interop.pyx
python/pylibcudf/pylibcudf/libcudf/interop.pxd

When releasing nanoarrow schemas and arrays in pylibcudf interop we allocate the space for the struct with new, but previously deallocated it with free. This is technically incorrect: data allocated with new should be deallocated with delete. To fix this, introduce a few more inlined C++ functions that take the place of the calls to free.

Use delete not free to release data allocated with new

---

cpp/include/nvtext/normalize.hpp
cpp/tests/streams/text/replace_test.cpp
cpp/tests/text/normalize_tests.cpp

Deprecates the old `nvtext::normalize_characters` API which accepts a column and to-lower bool parameter.
```
std::unique_ptr<cudf::column> normalize_characters(
cudf::strings_column_view const& input,
bool do_lower_case,
rmm::cuda_stream_view stream ,
rmm::device_async_resource_ref mr);
```
This has been replaced with the `nvtext::character_normalizer` APIs:
```
std::unique_ptr<cudf::column> normalize_characters(
cudf::strings_column_view const& input,
character_normalizer const& normalizer, // created using nvtext::create_character_normalizer
rmm::cuda_stream_view stream,
rmm::device_async_resource_ref mr );
```
Associated gtests have also been removed to prevent warnings as errors.

Deprecate old nvtext::normalize_characters

---

python/pylibcudf/pylibcudf/scalar.pyi
python/pylibcudf/pylibcudf/scalar.pyx
python/pylibcudf/pylibcudf/tests/test_scalar.py

Adds an optional dtype argument to `Scalar.from_any`.

Add optional dtype argument to `Scalar.from_any`

---

python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/cudf_polars/dsl/expressions/string.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/utils/dtypes.py

Now that libcudf can ingest arrow string_view columns, we don't need to convert on the host side.

Allow polars arrow conversion to produce string_view

---

python/pylibcudf/pylibcudf/column.pyx

Contributes to #15132. Follow up to #18311.

Remove numpy requirement when converting 2d cuda array interface objects to pylibcudf Columns

---

ci/build_python.sh
ci/build_wheel.sh

In PR #18198, we created a standalone file `python/cudf/cudf/VERSION` that is not a symlink to `VERSION`. This was meant to fix issues with editable installations. However, because of this, we also need to write out the alpha version information to `python/cudf/cudf/VERSION` at build time. This PR fixes that.

Fix alpha versions of cudf package.

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/typing/__init__.py
python/cudf_polars/tests/test_cache.py

Previously we held on to evaluated `Cache` nodes for the lifetime of the query evaluation. This is more memory pressure than necessary. To fix this, track the number of times we see the node and drop the cached value once we see it for the last time.
So that the same thing occurs in the partitioned executor, implement specialised hashing and equality for cache nodes: their key is guaranteed to be unique by polars within a query, so that is sufficient for the hash key.
- Closes #17363

Refcount-based dropping of cached evaluations in cudf-polars executor

---

CONTRIBUTING.md

- No code change
- Only typo fix in `CONTRIBUTING.md`: the build type is `tests` instead of `test`

[DOC] Fix typo in CONTRIBUTING.md on build type tests

---

python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/tests/test_dataframe.py

After https://github.com/rapidsai/cudf/pull/18306, we are maintaining a non-`None` `ColumnAccessor.label_dtype` (i.e. `DataFrame.columns.dtype`) attribute more often; however, now we need to be more careful to set this attribute to `None` if we add a new column label that isn't the same type.
cuml is experiencing some test failures because of this.

Ensure DataFrame column label operations reset label_dtype

---

cmake/RAPIDS.cmake
cmake/rapids_config.cmake
cpp/CMakeLists.txt
cpp/libcudf_kafka/CMakeLists.txt
java/src/main/native/CMakeLists.txt
python/cudf/CMakeLists.txt
python/cudf_kafka/CMakeLists.txt
python/libcudf/CMakeLists.txt
python/pylibcudf/CMakeLists.txt

This works around a problem where GitHub is rejecting requests to the `githubusercontent.com` CDN. We vendor the contents of `RAPIDS.cmake` from `rapidsai/rapids-cmake` to avoid a network call.
xref: https://github.com/rapidsai/rapids-cmake/pull/809
xref: https://github.com/rapidsai/build-infra/issues/206

Vendor RAPIDS.cmake

---

cpp/src/io/json/read_json.cu
cpp/src/io/utilities/datasource.cpp

Generally, for a function `g(X x, Y y)` that is called in such a way `g(f(u), h(u))`. The order of evaluation is unspecified on two aspects:
- The order of `f(u)` and `h(u)` is unspecified.
- The order of `x` and `y` initialization is unspecified.
As a result, function call `g(f(v), std::move(v))` has unspecified (not undefined) behaviors: although `std::move(v)` is only a cast to xvalue that does not affect `v` itself, the order of `X x(f(v))` and `Y y(std::move(v))` is still unspecified. If the latter is evaluated first, then a moved-from `v` will be passed to `f(v)` with which to initialize `x`.
This PR fixes a few places where this potential issue exists.
References: https://eel.is/c++draft/expr#call-7

Fix unspecified behavior involving move semantics and order of evaluation

---

python/cudf_polars/cudf_polars/experimental/shuffle.py
python/cudf_polars/tests/experimental/test_rapidsmpf.py

The experimental `rapidsmp` module has been renamed to `rapidsmpf`.

Rename rapidsmp to rapidsmpf

---

python/libcudf/pyproject.toml

I saw libcudf wheel builds fail in https://github.com/rapidsai/cudf/pull/18235 because the wheel was exceeding the size limit. We recently got a size limit increase, which was needed to support more GPU architectures. This bumps the limit up.

Increase wheel size limit.

---

cpp/examples/set_cuda_architecture.cmake

Fixes one of the cpp examples cmake to use the rapids_config.cmake
Reference #18473

Fix cpp examples cmake to use the rapids_config.cmake

---

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
cpp/include/cudf/detail/indexalator.cuh
cpp/src/copying/concatenate.cu
cpp/src/dictionary/detail/concatenate.cu
cpp/src/dictionary/set_keys.cu
cpp/src/io/comp/comp.cu
cpp/src/io/json/column_tree_construction.cu
cpp/src/io/orc/writer_impl.cu
cpp/src/io/parquet/page_data.cu
cpp/src/io/parquet/page_enc.cu
cpp/src/io/parquet/page_string_decode.cu
cpp/src/io/parquet/reader_impl_chunking.cu
cpp/src/io/parquet/reader_impl_preprocess.cu
cpp/src/labeling/label_bins.cu
cpp/src/sort/common_sort_impl.cuh
cpp/src/sort/sort_column_impl.cuh
cpp/src/strings/attributes.cu
cpp/src/strings/convert/convert_durations.cu
cpp/src/strings/copying/concatenate.cu
cpp/src/strings/search/contains_multiple.cu
cpp/src/text/edit_distance.cu
cpp/src/text/normalize.cu
cpp/src/text/subword/subword_tokenize.cu
cpp/src/text/subword/wordpiece_tokenizer.cu
cpp/tests/reductions/host_udf_example_tests.cu

They are aliases to the libcu++ ones and we want to get rid of them

Replace thrust functors with libcu++ ones

---

python/pylibcudf/pylibcudf/column.pxd
python/pylibcudf/pylibcudf/column.pyx

closes https://github.com/rapidsai/cudf/issues/18495. I assume this is properly tested as I made `Column.from_libcudf` dispatch to this new method.
Additionally, follows up on https://github.com/rapidsai/cudf/pull/18367 by passing `stream` to mask and children construction.

Add pylibcudf.Column.from_rmm_buffer

---

python/cudf/cudf/utils/ioutils.py

This PR reduces memory pressure in pandas metadata generation by materializing a `0` sized index rather than full range-index.

Optimize pandas metadata generation to reduce memory pressure

---

ci/run_cudf_polars_pytests.sh
python/cudf_polars/cudf_polars/callback.py
python/cudf_polars/cudf_polars/experimental/dask_serialize.py
python/cudf_polars/cudf_polars/experimental/groupby.py
python/cudf_polars/cudf_polars/experimental/io.py
python/cudf_polars/cudf_polars/experimental/join.py
python/cudf_polars/cudf_polars/experimental/parallel.py
python/cudf_polars/cudf_polars/experimental/shuffle.py
python/cudf_polars/cudf_polars/experimental/utils.py
python/cudf_polars/cudf_polars/testing/asserts.py
python/cudf_polars/cudf_polars/utils/config.py
python/cudf_polars/tests/conftest.py
python/cudf_polars/tests/experimental/test_dataframescan.py
python/cudf_polars/tests/experimental/test_groupby.py
python/cudf_polars/tests/experimental/test_join.py
python/cudf_polars/tests/experimental/test_parallel.py
python/cudf_polars/tests/experimental/test_rapidsmpf.py
python/cudf_polars/tests/experimental/test_scan.py
python/cudf_polars/tests/experimental/test_select.py
python/cudf_polars/tests/experimental/test_shuffle.py
python/cudf_polars/tests/test_executors.py

Closes https://github.com/rapidsai/cudf/issues/18348
- Renames the cudf-polars executors (currently `"pylibcudf"` and `"dask-experimental"`) to `"in-memory"` and `"streaming"`.
- The new terms are consistent with the engine options available for cpu-polars.
- Adds a `"scheduler"` configuration option to enable distributed execution when the `"streaming"` executor is active.
- The new options are `"synchronous"` and `"distributed"`, for now. It will be easy to add a `"threads"` option in a follow-up PR (to take advantage of both UVM and PTDS on a single GPU)
- We no longer import dask/distributed and look for a distributed client unless the `"distributed"` option is configured.
```python
import polars as pl
import polars as pl
q = pl.scan_parquet("/parquet/directory").group_by("y").sum() …
```

Rename cudf-polars executors

---

python/cudf/cudf_pandas_tests/test_main.py

Not sure if this test is running in CI, but `print()` doesn't have an `out=` keyword argument:
```shell
$ python
Python 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print("hello", out=sys.stderr)
File "<stdin>", line 1, in <module>
TypeError: 'out' is an invalid keyword argument for print()
>>> print("hello", file=sys.stderr)
hello
```

Fix `print()` keyword argument in cudf pandas test

---

python/cudf/cudf/core/index.py
python/cudf/cudf/tests/test_index.py

pandas exposes `Categorical.from_codes` as a fastpath to constructing categorical data without factorization. While cuDF doesn't have a pandas analogue for `Categorical`, I think this is still worth adding to `CategoricalIndex.from_codes` to provide a fastpath.
Additionally, this API will help cugraph avoid using private columns APIs

Add CategoricalIndex.from_codes

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/struct.py
python/cudf/cudf/core/scalar.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_indexing.py
python/cudf/cudf/tests/test_scalar.py
python/cudf/cudf/utils/dtypes.py

`to_cudf_compatible_scalar` was largely used as a utility function for `cudf.Scalar` and `Series.__setitem__`.
The use for the function in `Series.__setitem__` is largely unneeded in as logic can be pushed to `Column._cast_setitem_value`. Therefore, `to_cudf_compatible_scalar` can be moved along side `cudf.Scalar`, which is now deprecated, and both can be removed once the deprecation is enforced.

Remove need for to_cudf_compatible_scalar

---

conda/recipes/libcudf/recipe.yaml

Without this setting the kafka builds fail to find cudf and instead rebuild it.

Add back cudf root

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

Broken off from https://github.com/rapidsai/cudf/pull/18541/files, adjusting some groupby test (including a doctest) to be more order agnostic as an expected difference between cudf and pandas and happened to fail with an cuCollections update

Adjust cudf Python groupby test for cuCollections update

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java
java/src/main/native/src/ColumnVectorJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Add Sha1 JNI.  We want to add this functionality for Spark Rapids. Would help for https://github.com/NVIDIA/spark-rapids/issues/7035

[JNI] Expose row-wise sha1 api

---

python/cudf/cudf_pandas_tests/third_party_integration_tests/tests/test_cuml.py

Skips cuml integration tests that may fail (eg. https://github.com/rapidsai/cudf/actions/runs/14607488227/job/40980050789?pr=18554) during execution. We will let a cuml developer follow-up and potentially unskip these tests or move them to cuml.
CC @csadorf, @vyasr

Skip cuml third-party integration tests that may segfault

---

cpp/src/groupby/sort/group_merge_m2.cu
cpp/tests/groupby/merge_m2_tests.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

This fixes an overflow issue for the `MERGE_M2` groupby aggregation that has been reported in https://github.com/NVIDIA/spark-rapids/issues/12468. In particular, the current implementation of this aggregation requires the `count` input to be a column of type `INT32`, which cannot handle groups with sizes larger than `INT_MAX` (2B rows). To fix that, `count` type is changed to a wider type, which can be either `INT64` or `FLOAT64`.
This is also a breaking change and requires the downstream applications (Spark-Rapids) to change the corresponding data structure.

Fix overflow for `MERGE_M2` groupby aggregation

---

python/cudf_polars/cudf_polars/dsl/expressions/string.py
python/cudf_polars/cudf_polars/experimental/shuffle.py
python/pylibcudf/pylibcudf/libcudf/scalar/scalar_factories.pxd
python/pylibcudf/pylibcudf/scalar.pyx
python/pylibcudf/pylibcudf/tests/test_scalar.py

Contributes to https://github.com/rapidsai/cudf/issues/18534
Should help unblock the failure in https://github.com/rapidsai/cudf/pull/18554

Support `plc.Scalar.from_py(None)` and `plc.Scalar.from_py(int, float type)`

---

cpp/cmake/thirdparty/get_kvikio.cmake
cpp/src/io/utilities/datasource.cpp

https://github.com/rapidsai/kvikio/pull/700 fixed a bug in S3 endpoint constructor. This PR updates cuDF accordingly.

Update KvikIO S3 endpoint usage

---

python/cudf_polars/tests/test_window_functions.py

This PR adds unit tests for window functions in cudf-polars using both `over` and `rolling`. These tests will `xfail` at the moment, but the intention would be that as we add window function support to cudf-polars these tests can serve as acceptance criteria to make sure we support a wide range of aggregate functions.

Add xfail window function tests for cudf_polars

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_dataframe.py

Namely when `index=True`, the index memory usage should be the first element not the last.
Also adds more type annotations to `memory_usage` signatures

Fix `DataFrame.memory_usage` output order

---

cpp/src/strings/split/split_record.cu

Improves the performance of `cudf::strings::split_record()` when specifying whitespace-split delimiter.
The change includes computing token counts into an intermediate buffer before computing offsets.
Result is up to a 2x performance improvement especially for longer strings.

Improve performance of strings split-record on whitespace

---

cpp/CMakeLists.txt
java/src/main/native/CMakeLists.txt

This exports the compiler flags and definitions that are configured by libcudf, so the downstream applications can retrieve and use them directly. 
This is useful for the applications that heavily depend on libcudf and try to maintain a similar CMake build system as libcudf, such as `spark-rapids-jni`. They typically have to generate the same set of flags/definitions similar to what libcudf uses and have to periodically update their flags/definitions to sync with libcudf.

Export cudf compiler flags and definitions

---

cpp/include/nvtext/wordpiece_tokenize.hpp
cpp/src/text/wordpiece_tokenize.cu
cpp/tests/text/subword_tests.cpp

Adds a missing error check for the `nvtext::wordpiece_tokenize` for an invalid argument value. Also fixes the doxygen and removes some commented out code.

Add gtest error check for nvtext::wordpiece_tokenize

---

java/src/main/native/src/ColumnViewJni.cu

This fixes a deprecated warning in Java JNI code.
Closes https://github.com/rapidsai/cudf/issues/18652.

Fix compile warnings in Java JNI

---

.github/workflows/pr.yaml
.github/workflows/test.yaml

This PR disables `arm64` tests to unblock CI.

Disable `arm64` python tests

---

cpp/benchmarks/io/cuio_common.cpp

CCCL's RAPIDS CI is failing due to what looks like a missing include when attempting C++20 compilation.

Add missing header

---

ci/build_wheel_cudf.sh
ci/build_wheel_libcudf.sh
ci/build_wheel_pylibcudf.sh

librmm will ship a shared library component in 25.06 (xref: https://github.com/rapidsai/rmm/issues/1779). This PR updates `auditwheel` calls to exclude `librmm.so`.

Exclude librmm.so from auditwheel

---

cpp/tests/strings/split_tests.cpp
docs/cudf/source/conf.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/dtypes.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/single_column_frame.py

Additionally simplifies `ListDtype` to "privately" hold a dtype object instead of a pyarrow object

Annotate and simplify `from_arrow`

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/single_column_frame.py

Additionally adds some type annotations to methods of `Frame`

Prune methods from Frame that are specific to subclasses

---

cpp/src/column/column_view.cpp

Currently we print a notice when prefetching is enabled and we try to use a type that cannot be safely prefetched (essentially any nested type). We should not be printing unconditionally. Logging is more appropriate.

Switch from printing to logging

---

python/cudf/benchmarks/API/bench_index.py
python/cudf/cudf/tests/test_repr.py

This PR fully resolves #18665 by moving the test to benchmarks and only verifying the correctness result on a smaller subset of values in the regular pytest suites.

Move `test_large_unique_categories_repr` to benchmarks

---

python/cudf_polars/cudf_polars/experimental/shuffle.py

Teeing up this "fix" for the proposed change in https://github.com/rapidsai/rapidsmpf/pull/256
Once that PR is merged, we will want to get this in asap to keep `rapidsmpf` shuffling from breaking. We can update `Sort` in a follow-up PR.

Revise `DaskIntegration` protocol to align with `rapidsmpf`

---

python/cudf_polars/cudf_polars/experimental/join.py
python/cudf_polars/tests/experimental/test_join.py

Adds very basic `ConditianalJoin` support. Simple reduces the smaller table to 1 partition in all cases. Further variations can be added in follow-up work.

Support `ConditianalJoin` via broadcasting in cudf-polars streaming engine

---

python/cudf_polars/cudf_polars/dsl/utils/groupby.py
python/cudf_polars/tests/experimental/test_groupby.py

This fixes a bug where a group_by with no aggregations raised a ValueError.
```python
df.group_by("col").agg()
```
The fix uses `Distinct`, which is equivalent to a groupby with no aggregations. `Distinct` was previously not supported by the multi-partition executor, so that's implemented here as well.
Closes https://github.com/rapidsai/cudf/issues/18276

Handle empty aggregations in multi-partition cudf.polars group_by

---

cpp/examples/billion_rows/CMakeLists.txt
cpp/examples/parquet_io/CMakeLists.txt
cpp/examples/strings/CMakeLists.txt

Cherry-picking and squashing Bradley's commits: https://github.com/rapidsai/cudf/commit/35b78d8832be98ab2756cac4f8a223706116828d & https://github.com/rapidsai/cudf/commit/c5741194ba5d23c5965612e2a399aadae0ddf497
As part of CUDA 12.9 bringup, we found that cuDF is linking to the legacy `nvToolsExt` library, which is dropped in that CUDA release. However cuDF no longer uses the legacy `nvToolsExt` library since upgrading to NVTX 3.
In the rest of the code, we use the `nvtx3::nvtx3-cpp` target. So this replaces the few `nvToolsExt` usages with the new/preferred target.

Link to `nvtx3::nvtx3-cpp` instead of `nvToolsExt`

---

python/pylibcudf/pylibcudf/column.pyx

The calculation of the size in bytes for the CUDA Array Interface for pylibcudf Column objects produced from a column_view and an arbitrary owner previously ran the risk of overflow because the arithmetic was performed on int32 types but that is actually the maximum size in number of elements, not bytes. Since the CAI is a Python object, we can do the arithmetic with pure Python (infinite precision) integers to avoid this problem. In the process of fixing this bug, this PR also does some minor cleanup of the various cases handled in the size calculation.
Resolves #18598

Fix overflow case and clean up some logic

---

python/pylibcudf/pylibcudf/column.pyx

The `_Ravelled` object was orginally added in https://github.com/rapidsai/cudf/pull/18311 to avoid cupy dependence (ie `cp.asarray(obj).ravel()`). But we dont need to ravel the object because it must be C-contiguous already. Addresses https://github.com/rapidsai/cudf/pull/18744#issuecomment-2873769554

Remove unecessary _Ravelled class

---

cpp/include/cudf/strings/strings_column_view.hpp
cpp/src/strings/strings_column_view.cpp

`chars_size` can throw (since `get_offset_value` might throw), conversely `chars_begin` doesn't throw.

Fix noexcept annotations on strings_column_view

---

cpp/include/cudf/strings/strings_column_view.hpp
python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/gpumemoryview.pyx
python/pylibcudf/pylibcudf/libcudf/strings/strings_column_view.pxd
python/pylibcudf/pylibcudf/libcudf/types.pxd
python/pylibcudf/pylibcudf/types.pxd
python/pylibcudf/pylibcudf/types.pyx

Although the number of _rows_ in a `column_view` cannot exceed `size_type`, the number of _bytes_ surely can. So fix that.
This fixes multi-GPU errors we are seeing in rapidsmpf when communicating buffers.

Fix integer overflows in pylibcudf `from_column_view_of_arbitrary`

---

python/pylibcudf/pylibcudf/scalar.pyx
python/pylibcudf/pylibcudf/tests/test_scalar.py

I noticed that the factory methods have some paths by which the scalar will be initialized with a None dtype. Although such scalars are technically in an invalid state, many if not most operations work anyway since the underlying C++ scalar is properly typed and its type is what is used for most operations when testing.

Ensure scalar dtype is always set in from_py

---

cpp/src/io/avro/reader_impl.cu

Based on the specs at https://avro.apache.org/docs/1.11.1/specification/
In Avro files with Snappy compression, blocks contain a CRC32 checksum after the compressed data. The reader did not take this into account when setting up the decompression inputs, leading to errors with HW decompression (other implementations ignore the unused bytes).
This PR adjusts the size of the compressed block to exclude the checksum.

Fix reading of Snappy compressed Avro files

---

conda/recipes/cudf-polars/recipe.yaml
conda/recipes/cudf/recipe.yaml
conda/recipes/cudf_kafka/recipe.yaml
conda/recipes/custreamz/recipe.yaml
conda/recipes/dask-cudf/recipe.yaml
conda/recipes/libcudf/recipe.yaml
conda/recipes/pylibcudf/recipe.yaml

This quotes `head_rev` to ensure that commits with leading zeros in the git SHA include those zeros in the output package name.
xref: https://github.com/rapidsai/build-planning/issues/176

Quote head_rev in conda recipes

---

conda/environments/all_cuda-118_arch-aarch64.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
conda/recipes/cudf/recipe.yaml
dependencies.yaml
python/cudf/pyproject.toml
python/dask_cudf/pyproject.toml

This PR updates the lower bound for `numba-cuda` to `0.11.0`.

Require `numba-cuda>=0.11.0`

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/sort/rank.cpp
cpp/benchmarks/sort/sort.cpp
cpp/benchmarks/sort/sort_strings.cpp

Changing the sort benchmarks to use nvbench to better check performance impact of future code changes to libcudf sort APIs.

Change cudf::sort googlebench benchmarks to nvbench

---

cpp/src/sort/sort_column_impl.cuh
cpp/src/text/edit_distance.cu

Using the `cuda::std` functions instead of `thrust` whenever possible.

Change calls to thrust::swap to cuda::std::swap

---

python/cudf/cudf/tests/test_avro_reader_fastavro_integration.py
python/cudf/cudf/tests/test_csv.py
python/cudf/cudf/tests/test_orc.py
python/cudf/cudf/tests/test_parquet.py

Towards https://github.com/rapidsai/cudf/issues/10001
Before
```
============================= slowest 30 durations =============================
25.62s call     cudf/tests/test_no_cuinit.py::test_cudf_import_no_cuinit
25.29s call     cudf/tests/test_no_cuinit.py::test_cudf_create_series_cuinit
4.00s call     cudf/tests/test_parquet.py::test_parquet_reader_basic[gzip-10-columns3-cudf]
3.97s call     cudf/tests/test_replace.py::test_replace_multiple_rows
3.87s call     cudf/tests/test_json.py::test_chunked_json_reader
3.81s call     cudf/tests/test_parquet.py::test_delta_binary[int16-False-2]
3.69s call     cudf/tests/test_orc.py::test_chunked_orc_writer[TestOrcFile.demo-12-zlib.orc-columns1-None]
3.67s call     cudf/tests/test_csv.py::test_csv_reader_numeric_data[5-float64]
3.49s call …
```

Reduce more data sizes of Python tests

---

.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml
README.md

This PR reverts shared-workflows branches to `branch-25.06` and ensures builds use CUDA 12.8.
CUDA 12.9 will be used in the test matrix but not for builds in RAPIDS 25.06. See https://github.com/rapidsai/build-planning/issues/173#issuecomment-2882179838 for more information.

Finish CUDA 12.9 migration and use branch-25.06 workflows

---

cpp/src/io/parquet/reader_impl_preprocess.cu
cpp/src/io/utilities/column_buffer.cpp
cpp/tests/io/parquet_chunked_reader_test.cu
python/cudf/cudf/tests/test_parquet.py

This PR handles a potential `int32_t` overflow error when Parquet reader attempts to read more than 2 billion rows in one subpass.

Throw a descriptive exception in Parquet reader when trying to read files with more than two billion rows

---

python/cudf/cudf/io/hdf.py

https://github.com/rapidsai/cudf/pull/18829 made changes to `cudf.from_pandas` call to `DataFrame.from_pandas` and hdf reader can read series objects too. So reverting this change.

Call the correct `from_pandas` in `hdf` reader

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
python/cudf/cudf_pandas_tests/third_party_integration_tests/dependencies.yaml

Catboost supports NumPy 2.0 now. This PR also pins the python version to 3.12 because TensorFlow does not support python 3.13 (I was not able to pin python version to 3.12 in just the TensorFlow environment).

Update NumPy dependency in cudf.pandas-catboost integration test

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_dataframe.py

Forks off of: https://github.com/rapidsai/cudf/pull/18832/
xref: https://github.com/rapidsai/cudf/pull/18832#discussion_r2096186843

Fix Dataframe `getitem` when `MultiIndex` columns exist

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/temporal_base.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/tests/test_binops.py

closes https://github.com/rapidsai/cudf/issues/18860
This was returning `bool` because `ColumnBase._binaryop` might have returned `NotImplemented` for both operands and therefore `is/is not` was being used for equality.
My fix ensures this returns a broadcasted result when this was done in a public cuDF object, but a more rigorous solution would be to change `_binaryop` to ensure all subclasses returned this broadcasted result.

Ensure __eq__/__ne__ between Columns in public objects don't return bool

---

python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py

Add a required CLI argument to allow enabling RMM async memory when creating a `LocalCUDACluster` for PDS-H benchmarking.

Add CLI argument to enable RMM async memory resource in PDS-H

---

cpp/benchmarks/string/case.cpp
cpp/benchmarks/string/char_types.cpp
cpp/benchmarks/string/combine.cpp
cpp/benchmarks/string/contains.cpp
cpp/benchmarks/string/convert_datetime.cpp
cpp/benchmarks/string/convert_durations.cpp
cpp/benchmarks/string/convert_fixed_point.cpp
cpp/benchmarks/string/convert_numerics.cpp
cpp/benchmarks/string/copy.cpp
cpp/benchmarks/string/copy_if_else.cpp
cpp/benchmarks/string/copy_range.cpp
cpp/benchmarks/string/count.cpp
cpp/benchmarks/string/extract.cpp
cpp/benchmarks/string/factory.cpp
cpp/benchmarks/string/filter.cpp
cpp/benchmarks/string/find.cpp
cpp/benchmarks/string/find_multiple.cpp
cpp/benchmarks/string/join_strings.cpp
cpp/benchmarks/string/lengths.cpp
cpp/benchmarks/string/like.cpp
cpp/benchmarks/string/repeat_strings.cpp
cpp/benchmarks/string/replace.cpp
cpp/benchmarks/string/replace_re.cpp
cpp/benchmarks/string/reverse.cpp
cpp/benchmarks/string/slice.cpp
cpp/benchmarks/string/split.cpp
cpp/benchmarks/string/split_re.cpp
cpp/benchmarks/string/translate.cpp
cpp/benchmarks/string/url_decode.cu

Fixes the strings benchmarks to use `alloc_size()` member function instead of `chars_size()` which did not account for reading the offsets or the bitmask.
Reference #13735

Update strings benchmarks to use alloc_size column/table function

---

python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py

Add a required CLI argument to allow enabling RapidsMPF's OOM protection when creating a LocalCUDACluster for PDS-H benchmarking.
Additionally add `rapidsmpf_oom_protection` and `rmm_async` (the latter was missed in https://github.com/rapidsai/cudf/pull/18899) to the `RunConfig` class to store whether those features were enabled or not.

Add CLI argument to enable OOM protection in PDS-H

---

python/custreamz/custreamz/tests/test_dataframes.py

This fixes the issue @mroeschke spotted in https://github.com/rapidsai/cudf/pull/18887#discussion_r2098349135, where this fixture wasn't actually being used.

Ensure gc fixture is used in custreamz test

---

docs/cudf/source/cudf_polars/engine_options.md

PR to add basic usage of streaming / distributed options for cudf-polars:
xref:  [StreamingExecutor](https://github.com/rapidsai/cudf/blob/branch-25.06/python/cudf_polars/cudf_polars/utils/config.py#L148) / [usage in pdsh](https://github.com/rapidsai/cudf/blob/96b0f94549cf8ac94d8681d789c3491126f08e40/python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py#L1205-L1208)

Docs for streaming executor options

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_onehot.py

This was deprecated in 24.10 https://github.com/rapidsai/cudf/pull/16565

Remove deprecated get_dummies(cats=, ...)

---

python/cudf/cudf/core/groupby/groupby.py
python/dask_cudf/dask_cudf/_expr/groupby.py
python/dask_cudf/dask_cudf/tests/test_groupby.py

Deprecated in 24.06: https://github.com/rapidsai/cudf/pull/15808

Remove deprecated groupby.collect

---

cpp/tests/io/orc_chunked_reader_test.cu

Removed fragile checks in ORC tests that can fail when (de)compression changes.

Remove test checks that depend on the compression engine

---

ci/test_cudf_polars_polars_tests.sh

The latest release of deltalake (>=1.0.0) introduces changes that are incompatible with the current version of polars supported by cudf. So this PR updates Polars' requirements-dev.txt to pin deltalake to <1.0.0.
Example of the failures we are seeing: https://github.com/rapidsai/cudf/actions/runs/15308055134/job/43067933487?pr=18916

Pin deltalake to <1.0.0

---

python/cudf/cudf/pandas/scripts/conftest-patch.py

This possibly got fixed when https://github.com/rapidsai/cudf/pull/18979 was merged, but these tests were not marked as xpassing in that PR

Mark pandas unit test test_eval_no_support_column_name as xpassing

---

python/cudf_polars/cudf_polars/dsl/ir.py

Follows up https://github.com/rapidsai/cudf/pull/18130. This PR removes the workaround that manually sliced off `skip_rows` from chunked Parquet reads by instead using built-in `set_skip_rows` API.

Remove skip_rows workaround for chunked Parquet reader in cudf-polars

---

cpp/src/rolling/detail/rolling.cuh
cpp/src/rolling/detail/rolling.hpp

For rolling mean, the aggregation is computed by summing valid values in the window and then dividing by the count in the store operation.
For duration types, the output type is also a duration (i.e. has an integer representation), and so the division of the sum of the window by the count is an integer division. Integer division by zero is undefined behaviour so we must avoid it. If the compiler just emits the division as is we might get a runtime trap, however, a sufficiently smart compiler might deduce that, since count is initialized to zero and then only incremented in the loop over the window bounds, and division by zero is undefined, that the loop between start_index and end_index must execute at least once (with a valid input value).
To avoid this, only store the output (also …

Avoid undefined behaviour in rolling_store_output_functor

---

python/cudf_polars/cudf_polars/experimental/groupby.py
python/cudf_polars/tests/experimental/test_groupby.py

The streaming cudf-polars engine is missing the pre-shuffling step needed to guarantee correct results for `group_by(...).n_unique()`. This PR fixes the problem and adds test coverage.

Fix bug in ``group_by().n_unique()`` in streaming cudf-polars

---

cpp/benchmarks/sort/sort.cpp

Adds `float` and `timestamp_ms` to the libcudf sort benchmark.

Add benchmarks for sorting float and timestamp

---

CONTRIBUTING.md
README.md

This PR updates the README to remove pip installation instructions for CUDA 11 and revises the CUDA and driver requirements to reflect CUDA 12.

Update README and CONTRIBUTING to reflect new CUDA requirements

---

conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
conda/recipes/cudf/recipe.yaml
dependencies.yaml
python/cudf/cudf/__init__.py
python/cudf/cudf/tests/test_mvc.py
python/cudf/cudf/utils/_numba.py
python/cudf/pyproject.toml
python/dask_cudf/pyproject.toml

Bumps to numba-cuda `>=0.14.0,<0.15.0` in order to get pynvjitlink enabled by default (if available): https://github.com/NVIDIA/numba-cuda/pull/263
Because cudf has a hard dependency on `pynvjitlink`, this means we always get `pynvjitlink` and do not need additional setup at import time.
Release notes for numba-cuda 0.14.0: https://github.com/NVIDIA/numba-cuda/pull/286

Use numba-cuda >=0.14.0,<0.15.0 to get pynvjitlink by default.

---

python/cudf_polars/cudf_polars/experimental/io.py

This removes the temporary workaround added in https://github.com/rapidsai/cudf/pull/19071, disabling predicate pushdown in cudf-polars with the streaming executor, which is unnecessary now that https://github.com/rapidsai/cudf/pull/19082 is merged. I've kept the test added in #19071.
Closes https://github.com/rapidsai/cudf/issues/19086

Reenable predicate pushdown in streaming cudf-polars

---

cpp/src/interop/from_arrow_host.cu
cpp/src/interop/from_arrow_host_strings.cu
cpp/tests/interop/from_arrow_host_test.cpp

Fixes the bitmask check in `cudf::from_arrow_host` for sliced input containing an ArrowStringView type.
Closes #19159

Fix bitmask in from_arrow_host for sliced stringview type

---

python/pylibcudf/pylibcudf/utils.pyx

#19051 enables using CUDA's per-thread stream at runtime using an environment variable. pylibcudf will get this for free when calling libcudf functions without a stream, but since we want every API to ultimately pass streams to libcudf we need to mirror the same default stream selection behavior in pylibcudf.

Make pylibcudf default stream choice consistent with libcudf

---

python/cudf_polars/cudf_polars/experimental/groupby.py
python/cudf_polars/tests/experimental/test_groupby.py

This fixes the `group_by(...).mean()` with the experimental executor when there are missing values. We were using the length of the column, rather than the number of non-NA elements.
Closes https://github.com/rapidsai/cudf/issues/19151

Fixed group_by mean with missing values and multiple partitions

---

python/cudf_polars/cudf_polars/dsl/expressions/rolling.py
python/cudf_polars/cudf_polars/dsl/translate.py
python/cudf_polars/cudf_polars/experimental/parallel.py
python/cudf_polars/tests/experimental/test_rolling.py

Closes https://github.com/rapidsai/cudf/issues/19150
(Although, we can probably do a bit more work to avoid fallback for some non-pointwise expressions)
We were not validating that the items in `HStack.columns` were all "pointwise" before lowering to partitionwise logic. This adds the possibility for single-partition fallback.

Add fallback to ``HStack`` lowering in cudf-polars

---

python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py
python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py

Updates `cudf_polars/experimental/benchmarks/pdsh.py` to record the scale factor (and use it in q11).
Some notes:
1. The user may now specify `--root` and `--scale` instead of specifying `--path`.
- The implied dataset directory is then: `f"{root}/scale-{scale}"`
2. If `--path` is specified, the `--root` argument is ignored (because the user has already defined the full path for us).
3. If `--scale` is **not** specified, we use the length of the `supplier` table to infer the scale factor.
This is **not** a "breaking" change, because neither `--root` nor `--scale` are required if `--path` is specified.

Record scale factor in experimental PDS-H benchmark

---

ci/test_wheel_cudf_polars.sh

This updates our coverage reporting to be a bit more useful in CI. Currently, we print out the coverage of each module in `cudf_polars`. See https://github.com/rapidsai/cudf/actions/runs/15679773613/job/44171842342?pr=19135#step:11:465 for an example.
This changes it to use `term-missing:skip-covered` output format, which will differ by
1. Not printinging the status of completely covered modules (making it easier to find the offending modules)
2. Print the lines missing coverage (making it easier to find the offending lines)
Now, failing output will look something like this:
```
Name                                         Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------
cudf_polars/experimental/dask_registers.py      89      2 …
```

Update coverage reporting for cudf-polars

---

python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py
python/cudf_polars/cudf_polars/experimental/io.py
python/cudf_polars/tests/expressions/test_numeric_unaryops.py
python/cudf_polars/tests/test_groupby.py

Along with https://github.com/rapidsai/cudf/pull/19219, this PR removes our usages of NumPy in cudf_polars which is used for testing and multi-gpu utils. Since Polars does not depend on NumPy, neither should cudf_polars

Remove NumPy usage in cudf_polars

---

cpp/include/cudf/column/column_device_view_base.cuh
cpp/include/cudf/detail/null_mask.cuh
cpp/src/bitmask/null_mask.cu
cpp/src/io/orc/stripe_enc.cu
cpp/src/io/orc/stripe_init.cu
cpp/src/io/orc/writer_impl.cu

Moves the `get_mask_offset_word` utility from `column_device_view_base.cuh` to `null_mask.cuh`
The function had no interdependencies with `column_device_view` and vice versa and operates only on a `bitmask_type` array.

Move get_mask_offset_word utility to null_mask.cuh

---

python/cudf_polars/cudf_polars/dsl/expressions/string.py
python/cudf_polars/tests/expressions/test_stringfunction.py

closes https://github.com/rapidsai/cudf/issues/18998
closes https://github.com/rapidsai/cudf/issues/18999
closes https://github.com/rapidsai/cudf/issues/19000

Support Expr.str.json_path_match/len_bytes/len_chars in cudf_polars

---

python/cudf_polars/cudf_polars/dsl/traversal.py

As noted in
https://github.com/rapidsai/cudf/pull/19135/files/e4cefacbcdabc39a50d9fa84f55eb4bee682a14c..5529066b5c8a89ccaabe8f04947162e5a5ef3083#r2181080547, the type parameter for the `state` parameter of `make_recursive` can be `StateT_co` like in `CachingVisitor`.

Fixed type annotation for 'state' in make_recursive

---

cpp/include/cudf/column/column_device_view.cuh
cpp/include/cudf/column/column_device_view_base.cuh

Fixes the doxygen for the `cudf::column_device_view::element()` to correctly claim a copy of the element is returned.
Closes #19291

Fix cudf::column_device_view::element() doxygen

---

dependencies.yaml
python/cudf/cudf/core/_compat.py

This PR adds support for `pandas-2.3.1` in `cudf`

Add support for `pandas-2.3.1`

---

python/cudf/cudf/_lib/strings_udf.pyx
python/cudf/cudf/core/udf/utils.py

* Removed unused `get_cuda_build_version`
* Removed dependence on `cudf.core`
* Reorganized some imports

Clean up cudf._lib.strings_udf.pyx

---

cpp/src/reductions/std.cu
cpp/src/reductions/var.cu
cpp/tests/reductions/reduction_tests.cpp

Enables the variance and standard-deviation aggregations in `cudf::reduce` in a libcudf debug build.
The nvcc compile bugs have been fixed and the code compiles and tests pass.

Re-enable std/var reductions for libcudf debug builds

---

cpp/src/reductions/segmented/all.cu
cpp/src/reductions/segmented/any.cu
cpp/src/reductions/segmented/max.cu
cpp/src/reductions/segmented/min.cu
cpp/src/reductions/segmented/product.cu
cpp/src/reductions/segmented/sum.cu

Fixes the `cpp/src/reductions/segmented` source files to include to correct `segmented_reduction_functions.hpp` header.
This will help match the declarations and definitions correctly and compile only necessary files when changing the header.
Found while working  on `cudf::reduce` PRs.

Fix includes for segmented-reduce source files

---

python/pylibcudf/tests/common/utils.py
python/pylibcudf/tests/conftest.py
python/pylibcudf/tests/test_utils.py

This changes our test-only assert_column_eq utility to provide a better error message when running under pytest.
After we've detected that two columns are not equal, we'll cast the columns to either python lists (for nested dtypes like lists or structs) or numpy arrays.
We then use NumPy's or python's usual assertion machiner to compare.
Some examples:
**Numeric values** (using NumPy)
```pytb
python/pylibcudf/tests/test_utils.py:34: in test_assert_column_eq_ok_raises
assert_column_eq(column, pa.array(right))
python/pylibcudf/tests/common/utils.py:195: in assert_column_eq
np.testing.assert_array_equal(left, right)
E   AssertionError: 
E   Arrays are not equal
E   
E   Mismatched elements: 1 / 3 (33.3%)
E   Max absolute difference among violations: 1
E   Max relative difference among …
```

Improve error message for `assert_column_eq` in pylibcudf tests

---

cpp/tests/io/parquet_common.cpp
cpp/tests/io/parquet_experimental_reader_test.cpp
cpp/tests/io/parquet_v2_test.cpp

Changes the sprintf usage to snprintf to prevent stack-overflow error in parquet gtests.

Replace sprintf with snprintf in libcudf parquet tests

---

.clang-format
.github/workflows/pr.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/197
* removes references to `cuspatial` in `.clang-format`
* updates `changed-files` configuration, so future PRs that only touch `.clang-format` do not trigger a full run of all CI
Looked for references like this:
```shell
git grep -i -E 'cuproj|cuspatial'
```

remove cuspatial references, avoid triggering tests on clang-format config changes

---

cpp/include/cudf/detail/device_scalar.hpp
cpp/include/cudf/fixed_point/fixed_point.hpp
cpp/include/cudf/utilities/bit.hpp
python/cudf/cudf_pandas_tests/test_cudf_pandas.py

Issue #19381
Remove workarounds specific to CUDA 11 since we don't support it any more.

Remove CUDA 11 Workarounds

---

python/cudf/cudf/tests/test_testing.py
python/cudf/cudf/tests/test_timedelta.py
python/cudf/cudf/tests/test_transform.py
python/cudf/cudf/tests/test_unaops.py
python/cudf/cudf/tests/test_unique.py

Towards https://github.com/rapidsai/cudf/issues/9999
* Use more pytest fixtures
* Avoid GPU objects in `pytest.mark.parametrize`

More pytest fixtures and avoid GPU params in cuDF classic tests

---

cpp/src/io/parquet/reader_impl_chunking_utils.cu
cpp/src/io/parquet/reader_impl_chunking_utils.cuh

This is to workaround an issue with `cub::DeviceMergeSort` in CCCL (https://github.com/NVIDIA/cccl/issues/5297), which is called by `thrust::sort`. By explicitly calling to `cub::DeviceRadixSort`, we can avoid the crash issue reported in https://github.com/NVIDIA/spark-rapids/issues/12949.

Switch from `thrust::sort` to `cub::DeviceRadixSort` in Parquet chunked reader

---

ci/cudf_pandas_scripts/pandas-tests/run.sh
python/cudf/cudf/pandas/scripts/run-pandas-tests.sh

When running `run-pandas-tests.sh` to debug pandas unit tests, it seems like setting `breakpoint()`s does not drop into pdb (seems to hang) due to the `timeout` command. Additionally, I think we're more concerned about timeouts when running in CI than locally, so moving this `timeout` command to the CI script instead.

Move timeout in cudf.pandas pandas unit tests script to ci script

---

dependencies.yaml

This is a slight simplification on https://github.com/rapidsai/cudf/pull/19529/ by having clang versions specified in only one place and splitting out include-what-you-use.

Simplify clang dependency spec

---

python/pylibcudf/pylibcudf/io/parquet.pxd
python/pylibcudf/pylibcudf/io/parquet.pyx

Exposes `filter` and `columns` options so we can use chaining style when building the options object before passing them to the reader.

Expose `filter` and `columns` parquet reader builder options to python

---

python/cudf/cudf/testing/_utils.py
python/cudf/cudf/tests/test_cuda_array_interface.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_dlpack.py
python/cudf/cudf/tests/test_udf_masked_ops.py
python/cudf/cudf_pandas_tests/test_disable_pandas_accelerator.py
python/dask_cudf/dask_cudf/tests/test_accessor.py

Working to have less places where we define "testing utilities" e.g. `conftest.py` vs `testing/*.py`

Clean testing/_utils.py

---

cpp/libcudf_kafka/CMakeLists.txt
cpp/libcudf_kafka/tests/CMakeLists.txt
python/cudf_kafka/CMakeLists.txt

Continuation of #19065, hopefully the last one.
Discovered that the kafka components are not compiled using C++20, unlike the rest of libcudf/cuDF.

Compile `libcudf_kafka` and `cudf_kafka` with C++20

---

cpp/include/cudf/strings/convert/convert_datetime.hpp
cpp/src/strings/convert/convert_datetime.cu
cpp/tests/strings/datetime_tests.cpp

Converts generic `cudf::logic_error` exceptions to more appropriate `std::invalid_argument` exceptions and adds additional gtests for those cases. Also update the doxygen as appropriate.

Additional gtests error checks for string/timestamp convert libcudf APIs

---

java/src/main/native/src/CudaJni.cpp

CUDA13 doesn't support get compute mode from cudaDeviceProp.computeMode.
It's changed to use  cudaDeviceGetAttribute.
Use macro CUDART_VERSION > 13000 to detect building on cuda13
And keep the original code for cuda12 in else part.
close #19644

Use cudaDeviceGetAttribute to get ComputeMode for CUDA13

---

python/cudf_polars/tests/test_config.py

Skips the test: `test_cudf_polars_enable_disable_managed_memory` if managed memory is not supported.

Skip managed memory test if managed memory not supported in cudf-polars

---

python/cudf_polars/cudf_polars/experimental/benchmarks/pdsds.py
python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py
python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py

Contributes to #19200. Unlike PDS-H, which scales linearly with row counts, PDS-DS tables scale nonlinearly, so we cannot infer the scale factor from a single table’s row count.
In the future, we can relax this requirement by maintaining a map of scale factors to expected row counts for PDS-DS tables.

Require `--scale` for PDS-DS benchmarks (due to nonlinear scaling)

---

cpp/tests/join/distinct_join_tests.cpp
cpp/tests/join/join_tests.cpp

This PR re-enables previously disabled join tests following the recent cuco version bump, along with the necessary fixes.

Re-enable Disabled Join Tests

---

cpp/src/jit/cache.cpp
cpp/src/jit/cache.hpp

This MR removes the excessive copies of the programdata, which was being copied on every kernel launch. The program data contains compressed un-compiled C++ code of CUDF's headers, which is very large.
This impacts both small and large columns/tables.
Follows-up https://github.com/rapidsai/cudf/issues/19625

[FEA] Remove excessive copies of JITIFY's ProgramData during JIT kernel launch

---

cpp/src/strings/attributes.cu
cpp/src/strings/case.cu
cpp/src/strings/like.cu
cpp/src/strings/search/find.cu
cpp/src/text/vocabulary_tokenize.cu
cpp/src/text/wordpiece_tokenize.cu

Fixed int overflow for `size * warp_size` calculation for the number of threads given to `grid1d` utility in several strings and nvtext functions.

Fix integer overflow in warp-per-row grid calculation

---

java/src/main/java/ai/rapids/cudf/Cuda.java
java/src/main/native/src/CudaJni.cpp
java/src/test/java/ai/rapids/cudf/CudaTest.java

Contributes to https://github.com/NVIDIA/spark-rapids/issues/12982
Different GPU should generate different UUID sequences.
I plan to use GPU card UUID to participate in the calculation of initial seed, so post this PR to expose the Gpu UUID.
The seed will be calculated on Java side, the following informations will parqicipate in the intial seed:
- Gpu card UUID
- Current timestamp
- Java process ID
- Java process start time
- an static incremental sequence ID on Java side.
......
Maybe more to make sure no same UUID sequences are generated.

Add Java JNI interface to get Gpu UUID

---

python/cudf/cudf/pandas/scripts/conftest-patch.py

We have two new failures in the pandas test suite that I started seeing yesterday. I strongly suspect that these are due to [the new xarray release](https://pypi.org/project/xarray/). Adding to the xfail list for now to unblock our CI.

Add new xfails for xarray release

---

conda/recipes/pylibcudf/recipe.yaml

This is a follow-up to #19657 to remove hard pyarrow and numpy requirements from the pylibcudf conda recipe.

Move to pyarrow and numpy to run_constrained

---

python/cudf/cudf/pandas/scripts/run-pandas-tests.sh
python/cudf/cudf_pandas_tests/test_cudf_pandas.py

cuDF now requires numba>=0.60. We can remove these workarounds for bugs in earlier numba versions.

Remove outdated numba workarounds

---

python/cudf_polars/cudf_polars/containers/dataframe.py
python/cudf_polars/cudf_polars/containers/datatype.py
python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/cudf_polars/testing/plugin.py
python/cudf_polars/tests/expressions/test_literal.py
python/cudf_polars/tests/test_groupby.py
python/cudf_polars/tests/test_scan.py
python/cudf_polars/tests/test_select.py
python/pylibcudf/pylibcudf/scalar.pyx
python/pylibcudf/tests/test_interop.py

Reverts rapidsai/cudf#19589
Currently CI is failing as the original PR did not sync with the HEAD of `branch-25.10` to catch presumably, new groupby tests that are failing.
Reverting to unblock CI for now and going to reopen this PR once I can investigate why those tests are failing.

Revert "Support decimal columns in cudf_polars"

---

cpp/cmake/Modules/JitifyPreprocessKernels.cmake

Fixes a warning from jitify compile with NVRTC when including C++ stdlib stdint.h or cstdint.
```
cuda/std/cstdint(105): warning #47-D: incompatible redefinition of macro "INTPTR_MIN" (declared at line 16 of stdint.h)
^
cuda/std/cstdint(106): warning #47-D: incompatible redefinition of macro "INTPTR_MAX" (declared at line 18 of stdint.h)
^
cuda/std/cstdint(107): warning #47-D: incompatible redefinition of macro "UINTPTR_MAX" (declared at line 20 of stdint.h)
^
cuda/std/cstdint(109): warning #47-D: incompatible redefinition of macro "INTMAX_MIN" (declared at line 17 of stdint.h)
^
cuda/std/cstdint(110): warning #47-D: incompatible redefinition of macro "INTMAX_MAX" (declared at line 19 of stdint.h)
^
cuda/std/cstdint(111): warning #47-D: incompatible redefinition of macro "UINTMAX_MAX" …
```

Suppress NVRTC warning from stdint.h

---

cpp/include/cudf/sorting.hpp

Updates the doxygen for `cudf::rank` to illustrate how the null-policy, null-order, and order parameter combinations behave for a given input.
Closes #19772

Add examples of null handling to doxygen for cudf::rank

---

cpp/tests/utilities/identify_stream_usage.cpp

The kernel launch and memcpyasync API have changed and we need updates to work properly.

Update identify_stream_usage CUDA runtime hooks to CUDA 13

---

python/cudf_polars/cudf_polars/testing/plugin.py

We return decimals with `precision=38`, polars returns `precision=None`. This is an expected mismatch, so xfail the test.

xfail polars `decimal(precision=None)` test

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/interval.py

Precursor of https://github.com/rapidsai/cudf/issues/18726 towards consistently constructing a cuDF column with a pylibcudf Column

Construct cuDF classic Decimal32/64Columns from RMM buffers

---

cpp/include/cudf/detail/join/hash_join.cuh
cpp/include/cudf/join/hash_join.hpp
cpp/include/cudf/join/join.hpp
cpp/include/cudf/join/sort_merge_join.hpp
cpp/src/join/hash_join.cu
cpp/src/join/sort_merge_join.cu
cpp/tests/join/join_tests.cpp

Related to #18677
This PR moves the strong types `join_match_context` and `join_partition_context` out of the `sort_merge_join` class into the public interface, allowing them to be reused in `hash_join`. It also introduces `*_join_match_context` APIs to `hash_join`, enabling per-row match data retrieval to better distribute cuDF workloads for downstream libraries like Spark.
Follow-up work, such as adding partition context retrieval, will be handled in a separate PR to keep the review process simpler.

Add join `*_match_context` APIs to hash join

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/cut.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/index.py
python/cudf/cudf/io/parquet.py

Precursor to https://github.com/rapidsai/cudf/issues/18726. We'll want to minimize direct construction of cuDF classic column via their attributes and instead use a pylibcudf in the future

Avoid CategoricalColumn constructors in cuDF classic

---

python/pylibcudf/tests/conftest.py

As pylibcudf is working to enable stream-ordered APIs and we add tests accordingly, those tests will all be running on non-default streams. Since we create those streams using rmm's APIs, by default they will be non-blocking streams that do not synchronize with the default stream. For such tests to be valid, any fixtures used in those tests must synchronize the streams used to create those fixtures before the tests queue up any work on the new streams (either synchronize the stream or enqueue an event on that stream for the test stream to wait on, but the latter is more complicated and probably unnecessary). Doing so ensures valid data since the host thread will block on the first synchronization, which will occur before any work is queued on the new stream that could use data on the old …

Make sure conftest fixture data is valid on exit

---

.github/workflows/build.yaml
.github/workflows/pandas-tests.yaml
.github/workflows/pr.yaml
.github/workflows/pr_issue_status_automation.yml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/208
Now that https://github.com/rapidsai/shared-workflows/pull/413 is merged, this converts all GitHub Actions references from `@cuda13.0` back to `branch-25.10`.
This is safe to admin-merge because the change is a no-op... configs on those 2 branches are identical.

Use branch-25.10 again

---

.github/workflows/pr.yaml

Until https://github.com/dmlc/xgboost/issues/11648 and https://github.com/rapidsai/xgboost-feedstock/issues/100 are resolved we need to run the integration tests on CUDA 12 so that we can still test xgboost.

Pin to CUDA 12 image for integration tests

---

python/cudf/cudf/utils/applyutils.py
python/cudf/cudf/utils/queryutils.py

xref https://github.com/rapidsai/cudf/pull/19855#discussion_r2323540719

Use cupy array instead of numba device array as inputs to jit routines

---

.github/workflows/test.yaml

Nightly companion to https://github.com/rapidsai/cudf/pull/19903/

Also use the CUDA 12 container for nightlies

---

python/cudf/cudf/_lib/strings_udf.pyx
python/pylibcudf/pylibcudf/column.pxd
python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/column_factories.pxd
python/pylibcudf/pylibcudf/column_factories.pyi
python/pylibcudf/pylibcudf/column_factories.pyx

This change ensures that we never create an rmm buffer that is not tied to the stream provided via an API.
Contributes to #15163

Make stream a required parameter for from_libcudf methods

---

python/cudf_polars/tests/test_scan.py

It appears this test actually makes a network request to Hugging Face via Polars which can fail if Hugging Face rate limits us e.g. https://github.com/rapidsai/cudf/actions/runs/17837593656/job/50721165949?pr=19996#step:11:2692 
In the future, this test should probably mock the network call as to also be polite to HF.

xfail(strict=False) test_scan_hf_url_raises due to rate limiting

---

python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/table.pyx
python/pylibcudf/tests/test_interop.py

When we ingest data via the Arrow C Data Interface in Python and produce our own data structures, these data structures will use rmm's current device resource to allocate memory. If that resource goes out of scope later, there is currently no link to keep them alive. This issue is the same reason that rmm's DeviceBuffer class in Python [stores the current mr](https://github.com/rapidsai/rmm/blob/de85ed361daa9868df15f62aff257e0cef291843/python/rmm/rmm/pylibrmm/device_buffer.pyx#L94). Now that our Arrow interop code no longer creates those DeviceBuffers, we need similar protections here. With this fix there is still some small potential for issues due to #14229, but that will be fixed soon enough with the work on #15170.

Keep mr alive along with arrow tables and columns

---

python/cudf_polars/cudf_polars/dsl/ir.py
python/cudf_polars/tests/test_scan.py

Follow up to https://github.com/rapidsai/cudf/pull/20027
Discussed offline, this test isn't useful at the moment and eventually another version will be written once scanning CSV over remote IO is supported.

Remove test_scan_hf_url_raises

---

python/cudf_polars/cudf_polars/experimental/parallel.py
python/cudf_polars/tests/experimental/test_filter.py

While experimenting with the new [StatsPlanningOptions](https://github.com/rapidsai/cudf/blob/5faa1db15728fa588d8e87cf0dcdb228dcc5ab45/python/cudf_polars/cudf_polars/utils/config.py#L294), I discovered a pre-existing bug in `lower_ir_node.register(Filter)`. We are failing to check for non-pointwise expressions in `Filter.mask` before treating the `Filter` operation as "pointwise".
This PR "fixes" the bug by falling back to a single partition. For 25.12, we can probably add multi-partition support to non-pointwise filters (if necessary).

Fix multi-partition `Filter` bug

---

cpp/include/cudf/column/column_view.hpp
cpp/include/cudf/detail/utilities/cuda_memcpy.hpp
cpp/include/cudf/detail/utilities/host_vector.hpp
cpp/include/cudf/utilities/span.hpp
cpp/src/groupby/hash/flatten_single_pass_aggs.hpp
cpp/src/io/csv/csv_gpu.hpp

Replaces the `cudf::host_span(cudf::detail::host_vector)` constructor with `cudf::host_span` cast operator method on `cudf::detail::host_vector`. This means changes to `cudf::detail::host_vector` requires minimal compile dependencies.
The `cudf::detail::host_vector` is only currently used in 44 places in 21 files while the `cudf::host_span` is used in 1191 places in 189 files. So changes to `host_vector` required recompiling most of libcudf. Switching the dependency means changes to `host_vector` will have less impact on an incremental build.

Switch host_vector and host_span dependency

---

python/cudf_polars/tests/experimental/conftest.py

This fixes the slowdown we observed recently in the cudf-polars distributed tests (e.g. https://github.com/rapidsai/cudf/actions/runs/18088209118/job/51465191815?pr=20130#step:11:2848, which took 2+ hours). c82f0fceeda changed how we set up the dask cluster, and inadvertently changed the scope of the fixture. We want it to run once at the start of the test sesssion, not per function.

Fix slowdown in cudf-polars distributed tests

---

python/cudf/cudf/pandas/__init__.py

Fixes cudf.pandas portion of https://github.com/rapidsai/rmm/issues/2060.
We should not prime the async MR by default.

Disable async MR priming in cudf.pandas

---

python/pylibcudf/pylibcudf/column.pxd
python/pylibcudf/pylibcudf/column.pyi
python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/column_factories.pxd
python/pylibcudf/pylibcudf/column_factories.pyi
python/pylibcudf/pylibcudf/column_factories.pyx
python/pylibcudf/pylibcudf/contiguous_split.pxd
python/pylibcudf/pylibcudf/contiguous_split.pyx
python/pylibcudf/pylibcudf/libcudf/column/column_factories.pxd
python/pylibcudf/pylibcudf/libcudf/contiguous_split.pxd
python/pylibcudf/pylibcudf/libcudf/reduce.pxd
python/pylibcudf/pylibcudf/reduce.pxd
python/pylibcudf/pylibcudf/reduce.pyi
python/pylibcudf/pylibcudf/reduce.pyx
python/pylibcudf/pylibcudf/strings/convert/convert_durations.pyx
python/pylibcudf/pylibcudf/strings/split/split.pyx

Add memory resources to reduce, column, column_factories, and contiguous_split

---

python/pylibcudf/pylibcudf/io/avro.pxd
python/pylibcudf/pylibcudf/io/avro.pyi
python/pylibcudf/pylibcudf/io/avro.pyx
python/pylibcudf/pylibcudf/io/csv.pxd
python/pylibcudf/pylibcudf/io/csv.pyi
python/pylibcudf/pylibcudf/io/csv.pyx
python/pylibcudf/pylibcudf/io/json.pxd
python/pylibcudf/pylibcudf/io/json.pyi
python/pylibcudf/pylibcudf/io/json.pyx
python/pylibcudf/pylibcudf/io/orc.pxd
python/pylibcudf/pylibcudf/io/orc.pyi
python/pylibcudf/pylibcudf/io/orc.pyx
python/pylibcudf/pylibcudf/io/parquet.pxd
python/pylibcudf/pylibcudf/io/parquet.pyi
python/pylibcudf/pylibcudf/io/parquet.pyx
python/pylibcudf/pylibcudf/io/text.pxd
python/pylibcudf/pylibcudf/io/text.pyi
python/pylibcudf/pylibcudf/io/text.pyx
python/pylibcudf/pylibcudf/io/timezone.pxd
python/pylibcudf/pylibcudf/io/timezone.pyx
python/pylibcudf/pylibcudf/libcudf/io/avro.pxd
python/pylibcudf/pylibcudf/libcudf/io/csv.pxd
python/pylibcudf/pylibcudf/libcudf/io/json.pxd
python/pylibcudf/pylibcudf/libcudf/io/orc.pxd
python/pylibcudf/pylibcudf/libcudf/io/parquet.pxd
python/pylibcudf/pylibcudf/libcudf/io/text.pxd

Add memory resources to I/O modules

---

python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py

The PDS-H queries don't obey `--rmm-async` unless using the distributed scheduler. This adds a note to the docs.
Perhaps we should solve this differently, so that `--rmm-async` actually works for all schedulers?
A workaround is setting `POLARS_GPU_ENABLE_CUDA_MANAGED_MEMORY=0`.

Add note that --rmm-async only affects distributed scheduler.

---

.github/workflows/pr.yaml
.github/workflows/test.yaml

Until we can get a proper fix for #20159 / #20160, this PR disables `conda-java-tests`.
PRs will still run the job but it is not required to merge. Nightly tests will skip the job completely.

Temporarily disable conda-java-tests

---

cpp/tests/io/parquet_common.cpp
cpp/tests/io/parquet_misc_test.cpp

Related to #14750 (CC: @vuule)
This PR reduces the execution time for parquet dictionary tests by using a step of 3 for the cardinality range as well as using a host buffer (instead of a file) to read/write parquet data

Reduce execution times for parquet dictionary tests

---

cpp/src/io/parquet/experimental/hybrid_scan_helpers.cpp

This PR adds a check to ensure that only the column chunks that have only dictionary encoded pages participate in dictionary-page based row group filtering in the new parquet reader.
Note that we can't GTest the PR as cuDF's parquet writer decides and uses single encoding type for data pages of a column chunk. Also note that this is a preemptive fix and we hadn't yet come across a test with the hybrid scan reader.

Skip filtering Parquet row groups with dictionaries if there are non-dict encoded pages

---

python/cudf/cudf/_lib/strings_udf.pyx
python/pylibcudf/pylibcudf/column.pxd
python/pylibcudf/pylibcudf/column.pyx
python/pylibcudf/pylibcudf/contiguous_split.pxd
python/pylibcudf/pylibcudf/contiguous_split.pyx
python/pylibcudf/pylibcudf/io/types.pxd
python/pylibcudf/pylibcudf/io/types.pyx
python/pylibcudf/pylibcudf/table.pxd
python/pylibcudf/pylibcudf/table.pyx

Require passing memory resources to from_libcudf methods

---

cpp/src/io/parquet/experimental/hybrid_scan_helpers.cpp
cpp/src/io/parquet/reader_impl.cpp
cpp/src/io/parquet/reader_impl_helpers.cpp
cpp/src/io/parquet/reader_impl_helpers.hpp
python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py

Two changes that significantly speed up `read_parquet_metadata`:
1. Skip parsing page indexes because they are not used in `read_parquet_metadata`.
2. Avoid accidental copies of the `metadata` object, which can have **many** dynamic allocations.
Measured PDS-H total time reduction from 54s to 33s.

Remove unnecessary work from `read_parquet_metadata`

---

ci/test_cudf_polars_polars_tests.sh

pydantic made a release today, and pyiceberg was relying on [non-documented](https://docs.pydantic.dev/latest/api/pydantic_core_schema/#pydantic_core.core_schema.ValidationInfo) functionality that was removed
```python
AttributeError: 'pydantic_core._pydantic_core.ValidationInfo' object has no attribute 'current_schema_id'
```
So I think it's sufficient just to pin pydantic in our cudf_polars polars test job

Pin pydantic<2.12 in ci/test_cudf_polars_polars_tests.sh
