- pygdf/_gdf.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/tests/test_binops.py
- pygdf/tests/test_unaops.py
- pygdf/tests/utils.py
Depends on https://github.com/gpuopenanalytics/libgdf/pull/18
> Add support of operations on masked series

- conda_environments/builddocs_py35.yml
- conda_environments/notebook_py35.yml
- conda_environments/testing_py35.yml
- pygdf/_gdf.py
- pygdf/categorical.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/formatting.py
- pygdf/numerical.py
- pygdf/series_impl.py
- pygdf/tests/test_binops.py
- pygdf/tests/test_categorical.py
- pygdf/tests/test_dataframe.py
- pygdf/utils.py
Based upon #18
Partially addresses #7 
This mainly adds support for categorical.  A lot of refactoring has to be done to handle categorical Series properly.  Index is added to support selection, a common operation for categorical.
Importing of categorical columns is not yet supported.
> Add Categorical and various improvments

- pygdf/dataframe.py
- pygdf/tests/test_numpy_interop.py
Based on #20 
Closes #5  
Conversion function b/w numpy recarray and structured array
> Add to_records and from_records

- pygdf/_gdf.py
- pygdf/dataframe.py
- pygdf/numerical.py
- pygdf/series_impl.py
This uses the libgdf reduction code from: https://github.com/gpuopenanalytics/libgdf/pull/21
> Convert stats implementation to use libgdf

- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
- pygdf/utils.py
Previous impl and tests were incorrect in the interpretation of the `.loc` feature.
> Fix .loc and df[index] indexing

- pygdf/_gdf.py
- pygdf/cudautils.py
- pygdf/tests/test_query.py
Depends on https://github.com/numba/numba/pull/2434
> Fix handling of empty gpu buffer

- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
> Fix showing wrong last column for truncated display

- pygdf/categorical.py
- pygdf/dataframe.py
- pygdf/index.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_categorical.py
- pygdf/tests/test_joining.py
Fixes:
* to_pandas
* sort_index
* take
* join
on categoricals
> Fixes various operations on categoricals

- pygdf/__init__.py
- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
- Add `dtypes` property to dataframes
- Support attribute access instead of getitem for column access
- Support tab completion for column attributes
- Add `DataFrame` and `Series` to top-level namespace
> A few niceties

- travisci/upload-anaconda.sh
> Fix travisci upload file not found

- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_categorical.py
- pygdf/tests/test_stats.py
- Add `Series.sum`
- Fix bug in `astype` where mask was dropped
- Fix bugs in reductions where `mask` was ignored
- Add tests for masked reductions, consolidate reduction tests
> Reduction fixes

- pygdf/_gdf.py
- pygdf/cudautils.py
- pygdf/series.py
- pygdf/series_impl.py
- pygdf/utils.py
> Improve performance related to slow bitmask operation

- pygdf/_gdf.py
- pygdf/column.py
- pygdf/cudautils.py
- pygdf/grouper.py
- pygdf/index.py
- pygdf/numerical.py
- pygdf/tests/test_binops.py
- pygdf/tests/test_dataframe.py
- pygdf/tests/test_groupby.py
- pygdf/tests/test_unaops.py
- pygdf/tests/utils.py
These are bugs/missing-feature encountered when writing a new demo.  Each commit corresponding to one bug-fix/feature-addition.
> Fixing various bugs and missing features

- pygdf/column.py
- pygdf/gpuarrow.py
Fix bug due to incorrect round down.
> Fix incorrect mask size calculation in parsing arrow serialized data

- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
> Improve as_gpu_matrix() error messsage

- conda_environments/testing_py35.yml
> Update libgdf dependency for issue #59

- pygdf/categorical.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_binops.py
- pygdf/tests/test_categorical.py
- binops now promote operands to a common type
- incompatible binops now raises properly
> Fix binop operands promotion and error handling

- pygdf/categorical.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_binops.py
> Add scalar broadcasting to binary operations

- pygdf/_gdf.py
- pygdf/tests/test_groupby.py
and add more test for groupby.
The bug affects groupby for keylevel > 2.
> Fix segsort dtype mismatch bug

- conda_environments/builddocs_py35.yml
- conda_environments/testing_py35.yml
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/grouper.py
- pygdf/index.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_groupby.py
Also added docstring to groupby APIs
> Add support for iterating groups and getting grouped df 

- pygdf/numerical.py
Due to recent changes to cudautils.find_segments.
> Fix unique_k

- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_factorize.py
- pygdf/tests/test_label_encode.py
- pygdf/tests/test_sparse_df.py
- pygdf/tests/test_stats.py
And improvements to .label_encoding
> Series.factorize

- pygdf/column.py
- pygdf/dataframe.py
- pygdf/index.py
- pygdf/series.py
- pygdf/tests/test_dataframe.py
- pygdf/tests/test_index.py
- pygdf/tests/test_onehot.py
- pygdf/tests/test_pandas_interop.py
~~~Work in progress~~~
* fix from_pandas for non-default index
* fix Index comparison
* implement .take
> Various fixes and enhancements to implement dask_gdf shuffling

- docs/source/api.rst
- pygdf/dataframe.py
- pygdf/groupby.py
> Rename Grouper to Groupby to match pandas API

- pygdf/applyutils.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/docutils.py
- pygdf/groupby.py
- pygdf/index.py
- pygdf/tests/test_cuda_apply.py
- pygdf/tests/test_dataframe.py
- pygdf/tests/test_groupby.py
Implements
* `groupby.apply` for basic pandas-like .apply on the groups.
* `groupby.apply_grouped` for transforming each group with user provided GPU function.
* `dataframe.apply_rows` for row-wise transform with a GPU function.
* `dataframe.apply_chunks` for chunk-wise transform with a GPU function.  This is the underlying function for `groupby.apply_grouped`.
> groupby apply and new dataframe.apply_*()

- pygdf/groupby.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_groupby.py
Adds the following groupby aggregation functions:
* var
* sum
* sum_of_squares
> Add more groupby aggregation functions

- pygdf/buffer.py
- pygdf/categorical.py
- pygdf/column.py
- pygdf/dataframe.py
- pygdf/gpu_ipc_broker.py
- pygdf/groupby.py
- pygdf/index.py
- pygdf/numerical.py
- pygdf/serialize.py
- pygdf/series.py
- pygdf/tests/test_serialize.py
* Have known issues with CUDA IPC transfer over two devices w/o device peer access ability (e.g. PCIe over different IOH, non NVLink connected).
> Custom distributed serialization for CUDA IPC transfer

- pygdf/_gdf.py
- pygdf/dataframe.py
- pygdf/formatting.py
- pygdf/groupby.py
- pygdf/index.py
- pygdf/multi.py
- pygdf/numerical.py
- pygdf/tests/test_categorical.py
Contains various performance fixes and issues dealing with empty dataframe
> Various perf fix

- pygdf/_gdf.py
- pygdf/applyutils.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/groupby.py
- pygdf/index.py
- pygdf/numerical.py
* Mostly improvements to groupby
* Add cache_key in apply_rows to avoid recompilation
> Groupby Performance enhancements

- docs/source/developer.rst
- docs/source/index.rst
- notes on code organization
- notes on things that should go into libgdf
> Add Developer doc

- pygdf/cudautils.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_stats.py
Extending unique() functionality to unique_count() and value_count() in pygdf code, needed for some current usage scenarios.
Functionality similar to pandas or clickhouse functions, in pygdf.
Will port whole functionality to libgdf later.
> Extending unique to unique_count and value_count functions to numerical.py and series.py

- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
- pygdf/tests/test_serialize.py
> Fix errors revealed in dask_gdf groupby test

- Dockerfile
- README.md
Saves a few mb of disk space and makes the build more configurable
> Removed extra apt packages, added build-args for Python, GCC, G++ versions

- pygdf/column.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/index.py
- pygdf/tests/test_multi.py
The issue is revealed in dask_gdf.merge.
> Fix an issue with concating empty frames

- pygdf/_gdf.py
- pygdf/buffer.py
- pygdf/column.py
- pygdf/columnops.py
- pygdf/datetime.py
- pygdf/index.py
- pygdf/series.py
- pygdf/tests/test_datetime.py
just started, but wanted to open it asap and i'll add to it today
> [REVIEW] datetime support

- pygdf/buffer.py
- pygdf/categorical.py
- pygdf/numerical.py
- pygdf/series.py
Fix for issues:
- https://github.com/gpuopenanalytics/pygdf/issues/144
- https://github.com/gpuopenanalytics/pygdf/issues/145
Also categorical columns had no implementation of value_counts (unlike numerical). No active issue filled for that.
> Fixes for github issues 144, 145 and lack of categorical value_counts

- .travis.yml
- travisci/upload-anaconda.sh
> [REVIEW] Fix TravisCI build errors

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Borrowed from [Numba](https://github.com/numba/numba/tree/master/.github) these templates will help to communicate the process used by the GoAi team to the larger community.
> [REVIEW] Adding templates for Issues and Pull Requests

- pygdf/dataframe.py
- pygdf/formatting.py
- pygdf/tests/test_dataframe.py
Solution to issue 166: https://github.com/gpuopenanalytics/pygdf/issues/166
> [REVIEW] Changes to allow numeric column names

- conda-recipes/pygdf/meta.yaml
- conda-recipes/pygdf/run_test.py
- pygdf/serialize.py
- setup.py
- travisci/build_pygdf.sh
> [REVIEW] Fix distributed dependency and add testing to conda recipe

- pygdf/_gdf.py
- pygdf/categorical.py
- pygdf/dataframe.py
- pygdf/index.py
- pygdf/numerical.py
- pygdf/tests/test_joining.py
Updates to pygdf to support changes in libgdf PRs:
https://github.com/gpuopenanalytics/libgdf/pull/99
https://github.com/gpuopenanalytics/libgdf/pull/100
> [REVIEW] Update to support hash join, gdf_context and new libgdf api

- README.md
Conda installation instruction needed changes with pygdf version.
> [REVIEW] Update README.md

- pygdf/_gdf.py
Binding modifications to accomodate API changes in fea-ext-join-gdf-col branch of libgdf: 
```
gdf_error gdf_inner_join(int num_cols, gdf_column **leftcol, gdf_column **rightcol, gdf_join_result_type **out_result, gdf_context *ctxt);
```
New API:
```
gdf_error gdf_inner_join(int num_cols, gdf_column **leftcol, gdf_column **rightcol,gdf_column *left_result, gdf_column *right_result,gdf_context *join_context);
```
libgdf PR: gpuopenanalytics/libgdf#116
> [REVIEW] Python bindings for the join output API changes

- pygdf/dataframe.py
- Remove return variable from `_sanitize_columns`.
- Remove nested call of `_sanitize_values` within `_sanitize_columns` for memory efficiency 
- w.r.t issue #230
> [Review] Remove multiple series creation during sanitize columns, resolves issue 230

- pygdf/cudautils.py
- pygdf/tests/test_dataframe.py
…put array is empty.
Updated astype to return an empty array of the desired type if the input array is empty.
> [REVIEW] Fixes astype for empty inputs

- pygdf/dataframe.py
- pygdf/index.py
- pygdf/tests/test_dataframe.py
- pygdf/tests/test_index.py
Needed for dask_gdf meta calculations.
> [REVIEW] Allow for running concat against empty dataframes

- pygdf/utils.py
Need to not call the numba kernel if the array is size 0.
> [REVIEW] Handle condition where column is empty for binary ops

- pygdf/_gdf.py
- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
Based on https://github.com/gpuopenanalytics/libgdf/pull/123
> [REVIEW] Add binding to libgdf gdf_hash_partition

- pygdf/cudautils.py
- pygdf/tests/test_categorical.py
Added checks for mask handling functions to prevent from running a 0 size kernel.
> [REVIEW] Handle 0 length category columns

- pygdf/_gdf.py
- pygdf/column.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/tests/test_dataframe.py
Based on https://github.com/gpuopenanalytics/libgdf/pull/142
> [REVIEW] Add validity mask support to DataFrame.partition_by_hash

- pygdf/libgdf_groupby.py
- pygdf/tests/test_groupby.py
Eliminate sorting on single aggreagator and update groupby tests.
> [REVIEW] Eliminate sorting on single aggregator and update groupby tests

- pygdf/dataframe.py
Fixes https://github.com/gpuopenanalytics/pygdf/issues/219
> [REVIEW]  Add docstring for merge function: Fixes #219

- pygdf/_gdf.py
- pygdf/categorical.py
- pygdf/columnops.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/datetime.py
- pygdf/index.py
- pygdf/numerical.py
- pygdf/series.py
- pygdf/tests/test_dataframe.py
Note: This doesn't support chunked arrays yet as I don't think we'd want to load each chunk into GPU memory and then do a concat afterwards.
> [REVIEW] Add to/from PyArrow functions and use PyArrow more heavily for data ingestion

- pygdf/_gdf.py
- pygdf/columnops.py
- pygdf/dataframe.py
- pygdf/tests/test_joining.py
Changed join and merge in dataframe to use new libgdf join API: 
https://github.com/gpuopenanalytics/libgdf/pull/135
New join builds the full dataframe in libgdf/C++ instead of only calculating indices in libgdf, providing a big speedup. 
Note: tests need to be rerun after libgdf PR 135 merge.
> [REVIEW] Change dataframe to call new join api

- pygdf/_gdf.py
Bindings for functions in https://github.com/gpuopenanalytics/libgdf/pull/157
> [WIP] Add bindings to gdf_nvtx_range_push and gdf_nvtx_range_pop.

- pygdf/_gdf.py
- pygdf/dataframe.py
- pygdf/tests/test_joining.py
Changed `dataframe.py` and `_gdf.py` to use new libgdf API that was merged last night. There is one minor discrepancy with pandas (weird) outer categories so skipping the test for the time being to be able to update pygdf-master to get it back to working state.
> [WIP] Changed outer joins to use new libgdf outer join API

- .gitignore
- cudf/dataframe.py
- cudf/formatting.py
- cudf/tests/test_dataframe.py
This PR fix the existing bug in printing empty dataframe as mentioned in [issue](https://github.com/rapidsai/cudf/issues/206).   
There are code changes in three files:
-  **cudf/dataframe.py** 
- **cudf/formatting.py** 
- **cudf/tests/test_dataframe.py**: unit tests are written in it.
**Issues:** First, in `to_string()` method of `cudf/dataframe.py`, `ncols` is not being calculated correctly and second, in same method, it is trying to get the last element of an empty list.
Let me know, what all things are needed more.
> [REVIEW] - Fix #206: resolved bug in printing empty dataframe

- cudf/buffer.py
- cudf/cudautils.py
- cudf/datetime.py
- cudf/numerical.py
- cudf/tests/test_dataframe.py
- cudf/tests/test_datetime.py
Add support for typecasting to/from datetime dtype.
> [REVIEW] Datetime Typecasting and fix empty column test

- libgdf/doc/RAPIDS_Memory_Manager.md
This documentation depends on PR #321 and should be merged after it.
> [REVIEW] DOC Add RMM documentation. 

- libgdf/src/io/csv/type_conversion.cuh
Super simple fix to a previous fix for negative values in read_csv
> [REVIEW] fixed for negative values in read_csv

- cudf/dataframe.py
- cudf/series.py
- docs/source/developer.rst
Adapted from a [prior pr](https://github.com/rapidsai/cudf/pull/289) closed for getting too out of synch with master.
This should have fewer conflicts
> [REVIEW] Doc cleanup & examples mostly for DataFrame methods

- cudf/tests/test_csvreader.py
- libgdf/src/io/csv/type_conversion.cuh
> [REVIEW] Fixed negative float

- libgdf/include/gdf/cffi/functions.h
- libgdf/src/join/joining.cu
- libgdf/src/quantiles.cu
- libgdf/src/scan.cu
- libgdf/src/segmented_sorting.cu
- libgdf/src/sorting.cu
- libgdf/src/sqls_ops.cu
- libgdf/src/streamcompactionops.cu
- libgdf/src/tests/groupby/groupby-test.cu
- libgdf/src/tests/groupby/test_parameters.cuh
- libgdf/src/tests/join/join-tests.cu
- libgdf/src/tests/join/valid_vectors.h
- libgdf/src/tests/quantiles/quant_tester.cu
In algorithms that do not support valid masks, GDF_VALIDITY_UNSUPPORTED
is now thrown if the valid pointer is not null and the null_count is not
0 for the columns involved.
> [REVIEW] Fix validity check for columns

- Dockerfile
Built and pushed the image from this change to: pdmack/rapidsai-base:latest 
Doing this to try to further develop a current image for kubeflow/kubeflow#1809
> Update Dockerfile for latest src tree structure

- cpp/tests/hash_map/map_test.cu
- travisci/libcudf/build_libcudf.sh
- travisci/libcudf/build_libcudf_cffi.sh
This minor change fixes #416 and gets CUDA-10 building and all tests passing.
> [REVIEW] Fix failing test for issue #416

- CHANGELOG.md
From now on every PR author should add a human-readable explanation of the PR at the appropriate location in this file. This will be a pre-condition for merging the PR. This PR does so.
> [REVIEW] Add CHANGELOG.md

- cpp/src/io/csv/csv_reader.cu
- cpp/tests/io/csv/csv_test.cu
This is to fix #440. The main change is to reduce threads from 1024. It also fixes the simple test, as it was not running if the test file was missing.
> [REVIEW] Fix csv_test CUDA too many resources requested fail

- CHANGELOG.md
- README.md
A few tweaks, indentation changes, formatting, and reordering to improve comprehension and ease of installation of the development environment.
> Update installation readme

- CHANGELOG.md
- python/cudf/dataframe/numerical.py
- python/cudf/tests/test_applymap.py
This PR fix the [#162-Assertion error while using applymap to change the output dtype](https://github.com/rapidsai/cudf/issues/162).
> added changes to fix 162

- CHANGELOG.md
- python/cudf/dataframe/column.py
- python/cudf/dataframe/numerical.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Allow Series.append() with different numeric dtype

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/formatting.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/utils.py
> [REVIEW] Enable DataFrame creation from_pandas with numeric column names.

- CHANGELOG.md
- python/cudf/__init__.py
- python/cudf/dataframe/__init__.py
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Add cudf.from_pandas function

- CHANGELOG.md
- cpp/src/io/csv/datetime_parser.cuh
- cpp/src/io/csv/type_conversion.cuh
- cpp/tests/io/csv/csv_test.cu
- python/cudf/tests/test_csvreader.py
Fixes #546.
- Change daysSinceEpoch() algorithm to the one referenced in datetime_ops.cu
- formula itself is pretty nifty, plus it seems good to have the same source for date/timestamp calculations as the rest of cuDF
- Add the problematic dates to the existing dates pytest
- Fix 'firstOcurance()' spelling error and move it to datetime_parser.cuh
> [REVIEW] CSV Reader: Fix days being off-by-one when parsing some dates

- CHANGELOG.md
- ci/checks/style.sh
- python/cudf/__init__.py
- python/cudf/dataframe/__init__.py
- python/cudf/io/__init__.py
These are already handled with the exclusions setup.cfg file
> [REVIEW] Remove noqa marks from __init__.py files

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
- Add default argument to q
- Create columns argument with default None
- Handle existence of columns argument
- Return the result instead of printing it
This fixes #423
> [REVIEW] Fix issues with .quantile method.

- CHANGELOG.md
- cpp/tests/io/csv/csv_test.cu
Fixes #676.
* Add missing `nrows` parameter to read_csv() which requires a default of -1
> [REVIEW] Fix 'gdf_csv_test_Dates' gtest failure due to missing nrows parameter

- CHANGELOG.md
- python/cudf/bindings/cudf_cpp.pyx
- python/cudf/bindings/join.pyx
- python/cudf/bindings/reduce.pyx
- python/cudf/bindings/sort.pyx
- python/cudf/dataframe/buffer.py
- python/cudf/tests/test_joining.py
> [REVIEW] Check for gdf supported column types

- CHANGELOG.md
- python/cudf/dataframe/datetime.py
- python/cudf/tests/test_datetime.py
> [REVIEW] Fixes #602: properly convert nulls in datetime to NaT when converting to numpy/pandas

- CHANGELOG.md
- python/cudf/bindings/cudf_cpp.pyx
- python/cudf/bindings/join.pyx
- python/cudf/bindings/reduce.pyx
- python/cudf/bindings/sort.pyx
- python/cudf/tests/test_stats.py
This should fix #528.
The release gil was not added to calls in cudf_cpp.pyx because that file contains only trivial calls that populate a struct.
**TODO:**
> [REVIEW] Release GIL before all libcudf calls from Cython

- CHANGELOG.md
- python/cudf/io/csv.py
- python/cudf/tests/test_csvreader.py
Add compression field to read_csv_strings()
> [REVIEW] Add compression field to read_csv_strings()

- CHANGELOG.md
- python/cudf/dataframe/buffer.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Test Series indexing, integer scalars and sequences

- CHANGELOG.md
- python/cudf/dataframe/__init__.py
- python/cudf/dataframe/categorical.py
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/datetime.py
- python/cudf/dataframe/index.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_index.py
This is a precursor to properly tackling #666 
Still need to add tests, but all current pytests should be passing
> [REVIEW] Refactor Index class, add CategoricalIndex

- CHANGELOG.md
- README.md
Closes https://github.com/rapidsai/cudf/issues/663
> [REVIEW] Added debug instructions to README.

- CHANGELOG.md
- cpp/include/cudf/io_types.h
- cpp/src/io/csv/csv_reader.cu
Resolves a signed/unsigned mismatch warning.
> [WIP] Update nrows and header type to gdf_size_type

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/cudautils.py
> [REVIEW] Prevent reading undefined memory in gpu_expand_mask_bits; fixes #733

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
Fixes #666
Piggybacks off a lot of the built in pandas compatibility in PyArrow.
> [REVIEW] Fixes #666; Update to_arrow and from_arrow for better Pandas compatibility

- CHANGELOG.md
- cpp/src/dataframe/cudf_table.cuh
Related to #808 but recreated to only have a single change
> [REVIEW] FIX undefined variable in `gdf_table`

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/io/comp/cpu_unbz2.cpp
- cpp/src/io/comp/unbz2.h
- cpp/src/io/comp/uncomp.cpp
- python/cudf/tests/test_csvreader.py
Add bzip2 decompression support to read_csv()
Fixes issue #701
> [REVIEW] Add bzip2 decompression support to read_csv()

- CHANGELOG.md
- cpp/src/io/csv/type_conversion.cuh
- cpp/tests/io/csv/csv_test.cu
- python/cudf/tests/test_csvreader.py
Fixes #675. 
This PR contains mainly two changes:
- Handle scientific notation for floating point numbers
- recognize exponent portion and modify final value accordingly
- Fix parsing to recognize empty fields of simply quotes or spaces
- allow adjustForWhitespaceAndQuotes() to decrement end_idx pass start_idx by 1 so that the condition in the CUDA kernel knows this is an empty field, rather than a single char/digit
> [REVIEW] CSV Reader: Fix scientific notation parsing and null values for empty quotes

- CHANGELOG.md
- cpp/src/join/joining.cu
- python/cudf/tests/test_joining.py
> [REVIEW] Fix bug wherein empty left join causes crash

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Handle unnamed indexes in to/from arrow

- CHANGELOG.md
- cpp/include/cudf/io_types.h
- cpp/src/io/csv/csv_reader.cu
- cpp/src/io/csv/type_conversion.cuh
- cpp/tests/io/csv/csv_test.cu
- python/cudf/io/csv.py
- python/cudf/tests/test_csvreader.py
Fixes #712 and fixes #708. 
This PR refactors some of the CSV reader to better support filtering blank/empty lines and comments. Notably, it tries to consolidate some of the row/record processing so we don't have multiple device->host or vice versa transfers.
* Consolidate and clarify record/row processing
* filter out rows outside of the byte ranges
* filter out rows with comments and empty lines
* reduce row window according to header, skiprows, nrows, skipfooter
* Fix some corner cases when of combinations of header, skiprows, comment, nrows
* skiprows operates on lines technically (does not ignore comments/blanks), while header operates on rows (ignores comments/blanks)
* Copy updated header logic from read_csv() to read_csv_strings()
* Most of the input logic to read_csv() should be …
> [REVIEW] CSV Reader: Add support for ignoring blank lines and comment lines

- CHANGELOG.md
- python/cudf/__init__.py
- python/cudf/_gdf.py
- python/cudf/dataframe/categorical.py
- python/cudf/dataframe/column.py
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/dataframe.py
- python/cudf/io/__init__.py
- python/cudf/io/parquet.py
- python/cudf/tests/test_multi.py
- python/cudf/tests/test_parquet.py
- python/cudf/utils/utils.py
Adds cuDF API to read/write file formats using PyArrow / Pandas.
Fixes #896 
Fixes #910
> [REVIEW] Add PyArrow based parquet readers / writers to Python, fix category dtype handling, fix arrow ingest buffer size issues

- CHANGELOG.md
- python/cudf/dataframe/series.py
This PR addresses https://github.com/rapidsai/cudf/issues/905.
> [REVIEW] value_counts return int type on empty columns

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
This was spun off from my earlier PR for skipping blank and comments lines. It's mostly a clean-up PR. 
As the header row (if present) is not used for the data field parsing kernels, and the column name parsing is done by the CPU, we can avoid copying it to GPU memory.
* Do not copy header row to GPU memory
- simplifies/removes some header row conditions
* Remove unused findSetBit() function
> [REVIEW] CSV Reader: Avoid host->device->host copy for header row data

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/formatting.py
- python/cudf/tests/test_dataframe.py
Pretty straight forward.
- binaryops
- comparisonops
- tests
Fixes #900
> [REVIEW] Add binary and comparison ops to dataframe, tests.

- CHANGELOG.md
- cpp/src/io/csv/type_conversion.cuh
- cpp/tests/io/csv/csv_test.cu
- python/cudf/tests/test_csvreader.py
Fixes #919.
* Fix convertStrToHash() to use start index, as original code assumed it was already at the start
- remove extra tail calculations and revert back to original to take care of remaining bytes
* Add doxygen comments and copyright header
* Add pytest and gtest
> [REVIEW] CSV Reader: Fix category GDF_CATEGORY hashes not being computed properly

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/utils.py
> [REVIEW] Fix handling objects of all nulls in series creation

- CHANGELOG.md
- ci/gpu/build.sh
- python/cudf/__init__.py
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/index.py
- python/cudf/dataframe/series.py
- python/cudf/io/__init__.py
- python/cudf/io/feather.py
- python/cudf/io/hdf.py
- python/cudf/io/json.py
- python/cudf/io/parquet.py
- python/cudf/tests/test_feather.py
- python/cudf/tests/test_hdf.py
- python/cudf/tests/test_json.py
- python/cudf/tests/test_parquet.py
Also may fix small issues related to Parquet unit tests.
> [REVIEW] Add feather, JSON, HDF5 readers / writers from PyArrow / Pandas

- CHANGELOG.md
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/cudautils.py
The current implementation of `Series.hash_encode`
uses `np.mod` on a `NumericalColumn`. This is extremely
slow so we add a numba kernel to speed this up.
Closes #935.
> [REVIEW] Add numba modulo kernel for hash_encode

- CHANGELOG.md
This PR updates the RMM submodule to the latest version.
> [REVIEW] Update RMM submodule to latest 

- CHANGELOG.md
- python/cudf/dataframe/datetime.py
- python/cudf/dataframe/numerical.py
- python/cudf/tests/test_binops.py
> [REVIEW] Add comparison binaryops to Datetime Series / Index / Column

- CHANGELOG.md
- python/cudf/__init__.py
- python/cudf/dataframe/__init__.py
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_joining.py
> [REVIEW] add top level merge func for convenience

- CHANGELOG.md
- python/cudf/dataframe/categorical.py
- python/cudf/dataframe/numerical.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_categorical.py
- python/cudf/tests/test_dataframe.py
- python/cudf/tests/test_stats.py
- python/cudf/utils/cudautils.py
Close #793 
Seems to fail when dtype != float currently
> [WIP] Rename Series.unique_count() to nunique() to match pandas

- CHANGELOG.md
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
This fixes https://github.com/rapidsai/cudf/issues/983
@mrocklin
> [REVIEW] Add external series groupby support

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Fix dtype in selecting 0 rows from objects

- CHANGELOG.md
- python/cudf/bindings/cudf_cpp.pyx
- python/cudf/bindings/join.pyx
- python/cudf/bindings/reduce.pyx
- python/cudf/bindings/replace.pyx
- python/cudf/bindings/sort.pyx
- python/cudf/dataframe/categorical.py
- python/cudf/dataframe/column.py
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/datetime.py
- python/cudf/dataframe/index.py
- python/cudf/dataframe/numerical.py
- python/cudf/dataframe/series.py
- python/cudf/reshape/__init__.py
- python/cudf/utils/applyutils.py
- python/cudf/utils/cudautils.py
> [REVIEW] Replace relative path imports with absolute paths in cudf

- CHANGELOG.md
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/cudautils.py
> [REVIEW] Fix 0 sized kernel launches, fix empty sort

- CHANGELOG.md
- python/cudf/dataframe/column.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/index.py
- python/cudf/tests/test_index.py
fixes #824
cc @kkraus14 @thomcom
> [REVIEW] add property setter for index and return correct index on head()

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] index into dataframe with columns

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
This PR address the issue #883.
> [REVIEW] added changes for df init using ndarray

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/multi.py
- python/cudf/tests/test_dataframe.py
fixes https://github.com/rapidsai/cudf/issues/968
> [REVIEW] concatenation along columns

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/groupby/groupby.py
- python/cudf/groupby/legacy_groupby.py
- python/cudf/tests/test_dataframe.py
- python/cudf/tests/test_json.py
- python/cudf/tests/test_sorting.py
This adds a `to_frame` method and the drop= keyword to `reset_index`
> [REVIEW] Reset index drop

- CHANGELOG.md
- cpp/src/binary/binary_ops.cu
- python/cudf/tests/test_binops.py
Fix for #696 . 
New approach is to simply copy the mask from the one input column that has it.
In case neither input columns have a mask, the output mask is set to all 1.
> [REVIEW] Fix error in binops when only one input col has null mask

- CHANGELOG.md
- cpp/include/cudf/functions.h
- cpp/src/replace/replace.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/replace/replace-nulls_tests.cu
This  is a Pull Request. It implements gdf_replace_nulls function.  
gdf_error gdf_replace_nulls(gdf_column* col_out, const gdf_column* new_values_column);
It will take in two gdf_columns.
* The first one is expected to be a regular gdf_column, the second one has to be a column of the same type as the first, and it has to be of  size one or of the same size as the other column.
*  case 1: If the second column contains only one value, then this function will replace all nulls in the first column with the value in the second  column.
* case 2: If the second column is of the same size as the first, then the function will replace all nulls of the first column with the corresponding elements of the  second column 
All the best,
> [REVIEW] Replace Nulls

- CHANGELOG.md
- cpp/src/io/csv/type_conversion.cuh
- cpp/tests/io/csv/csv_test.cu
- python/cudf/tests/test_csvreader.py
Fixes #987 and fixes #1035.
* Track the exponent sign so we effectively ignore leading zeros
* Maintain fractional part in decimal form as there could be exceedingly long number of digits
* Use exp10() rather than exp10f() to allow max value for double types
* Add pytest and gtest test case
> [REVIEW] CSV Reader: Fix parsing floating point precision and leading zero exponents

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Fix column creation with all valid nan

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
> Added support for DataFrame.loc[scalar] 

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/io/csv.py
- python/cudf/reshape/general.py
- python/cudf/utils/ioutils.py
See #652 
Experimentally I've changed docstrings from sphinx to use the numpydoc standard.
I started changing around results to pass doctests, but thought I'd throw this up first as a WIP to get feedback beforehand.  
Docs build nicely with `make html`
Tests fail if we add `py.test ... --doctest-modules`
cc @randerzander
> [REVIEW] Switch to Numpydoc for docstrings

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Fix dtype handling for loc / iloc

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_joining.py
cc @thomcom @kkraus14 @randerzander
> Add indicator and suffixes keywords to merge

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
Small PR to clean up a docstring from a previous PR
> [REVIEW] Fix Docstring

- CHANGELOG.md
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
Fixes https://github.com/rapidsai/dask-cudf/issues/118
> Add unsupported keywords to Series.fillna

- CHANGELOG.md
- python/cudf/dataframe/column.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/index.py
- python/cudf/dataframe/series.py
Fixes https://github.com/rapidsai/cudf/issues/1127
> [REVIEW] Fix join performance with index parameters

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Add ufunc for sqrt

- CHANGELOG.md
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
Resolves https://github.com/rapidsai/cudf/issues/1161
> [REVIEW] to_frame now accepts name argument

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_joining.py
cc @thomcom @kkraus14 I would like to get this in to 0.6 if possible
> [REVIEW] Support left_on/right_on and also on=str in merge

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
Fixes #1176 
Currently it creates a massive list host side which becomes a huge bottleneck.
> [REVIEW] Fix iloc performance

- CHANGELOG.md
- docs/source/dask-cudf.md
- docs/source/index.rst
> Adding dask-cudf API doc page

- CHANGELOG.md
- cpp/CMakeLists.txt
- docs/source/dask-cudf.md
- docs/source/index.rst
Auto-merge triggered by push to `branch-0.6` that creates a PR to keep `branch-0.7` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.6 to branch-0.7 [skip ci]

- CHANGELOG.md
- ci/gpu/build.sh
Trying to fix failing gpuCI builds on the release PR...
> [REVIEW] Fix gpu build script

- CHANGELOG.md
- setup_pip.py
Just adds the dlpack includes to the cython extension.
> [REVIEW] Add dlpack include to pip build

- CHANGELOG.md
- CONTRIBUTING.md
- Updates `CONTRIBUTING.md` to reflect the new naming conventions for the conda environment yml files.
Moved to new PR for branch clarity.
> [REVIEW] Update CONTRIBUTING for new conda environment yml naming conventions

- CHANGELOG.md
- python/cudf/dataframe/column.py
Create new categories by looping over the list of categories instead of each value in the Categorical column. Fixes https://github.com/rapidsai/cudf/issues/1288.
Not sure where unit tests should go for this, but I validated the fix locally and saw this drop in run times:
```
CPU times: user 1min 59s, sys: 1.48 s, total: 2min 1s
Wall time: 2min 1s
CPU times: user 10.4 ms, sys: 3.3 ms, total: 13.7 ms
Wall time: 13.6 ms
```
> [REVIEW] loop over each category instead of each value

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] add exclude to select_dtype

- CHANGELOG.md
- python/cudf/bindings/join.pyx
Update the string of the exception message.
Closes: #1272
> Fix Inaccurate error message in join.pyx

- CHANGELOG.md
- CONTRIBUTING.md
Also cleans up some of the writing style / punctuation.
> [REVIEW] Update CONTRIBUTING.md to use -DCMAKE_CXX11_ABI=ON

- CHANGELOG.md
- python/cudf/utils/utils.py
Fixes https://github.com/rapidsai/cudf/issues/1324
> [REVIEW] Fix null bitmaps dtype to be int8 consistently

- CHANGELOG.md
- python/cudf/dataframe/categorical.py
Add "na_position" argument to CategoricalColumn sort_by_values.
Fixes https://github.com/rapidsai/cudf/issues/1333.
> Add na_position argument to CategoricalColumn sort_by_values

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_query.py
- python/cudf/utils/queryutils.py
> [REVIEW] Added local_dict arg in df.query() method

- CHANGELOG.md
- cpp/src/io/comp/uncomp.cpp
Fixes #1320.
* Header check uses sig[] instead of blksz field for last byte
- compiler warning because sig is only three bytes defined
- functionality doesn't change before/after because access and overall header size is the same
> [REVIEW] Fix out of bounds warning when checking Bzip2 header

- CHANGELOG.md
- python/cudf/dataframe/numerical.py
- python/cudf/tests/test_replace.py
> [REVIEW] Fix fillna behaviour with different dtypes

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dask.py
> [REVIEW] Add DataFrame.mean that raises NotImplementedError

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- initialize col_dtype
- Addressing https://github.com/rapidsai/cudf/issues/1378
> [REVIEW] Fixed build failure caused due to error: 'col_dtype' may be used uninitialized

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
> Implement DataFrame._get_numeric_data

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
Fixes https://github.com/rapidsai/cudf/issues/1074
> Add innocuous axis= keyword to DataFrame.drop

- CHANGELOG.md
- cpp/src/copying/gather.cu
- cpp/src/copying/scatter.cu
- cpp/src/utilities/cudf_utils.h
- cpp/tests/utilities/column_wrapper.cuh
See issue #1368 . Split off from #1366.
Note: Can be reviewed, but the code depends on the fix for issue #1369 which hasn't been merged yet.
> [REVIEW] refactored set_null_count() 

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
Addresses #1348. 
Currently series objects are created multiple times while adding a column. This PR reorders when the series is created during `_prepare_series_for_add` and passes the series directly to ` _sanitize_columns` and ` _sanitize_values` with the only exception where the data being added is a single scalar. This reduces the time taken to add a column by ~3x.
> [REVIEW] Remove creation of series multiple times while adding column

- CHANGELOG.md
- ci/local/build.sh
> Fix permissions issues caused by root docker container

- ci/local/build.sh
> [REVIEW] Forgot to escape newline in local build script [skip ci]

- CHANGELOG.md
- cpp/src/io/parquet/parquet_reader.cu
- cpp/src/io/utilities/wrapper_utils.hpp
Fixes #1485.
This PR updates the implementation to use `device_buffer` and removes the temporary `device_ptr` wrapper definition.
* Remove unique_ptr-based device_ptr from utils header
* Convert raw usage of RMM to device_buffer
* Re-organize final column transfer step to match CSV reader
> [REVIEW] Parquet Reader: Use device_buffer rather than device_ptr

- CHANGELOG.md
- python/cudf/bindings/cudf_cpp.pxd
- python/cudf/bindings/cudf_cpp.pyx
- python/cudf/bindings/groupby.pyx
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_string.py
> [REVIEW] Convert groupby CFFI to Cython

- CHANGELOG.md
- cpp/src/io/parquet/parquet_reader.cu
- python/cudf/bindings/transpose.pxd
- python/cudf/bindings/transpose.pyx
- python/cudf/dataframe/dataframe.py
> [REVIEW] Convert transpose CFFI to Cython

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
- This PR adds `ndim` to Series and DataFrames, analogous to pandas
This closes #1515
> [REVIEW] Add Series and DataFrame.ndim

- CHANGELOG.md
- docs/source/api.rst
Fixes https://github.com/rapidsai/cudf/issues/1442
> [REVIEW] fix doc issue to ensure correct labelling of cudf.series

- CHANGELOG.md
- python/cudf/bindings/csv.pyx
- python/cudf/tests/test_csvreader.py
Fixes #1156.
Only fixes the simple case where all types in a list assumed to be the same. Mixed combination types would be more complicated to handle...
PANDAS also supports float column names as indexing, which cudf currently doesn't support.
* If column names are used, convert to its type when assigning
* Add pytests for string, int, range, and None scenarios
> [REVIEW] CSV Reader: Fix integer column name indexing

- CHANGELOG.md
- python/cudf/bindings/orc.pyx
- python/cudf/bindings/parquet.pyx
- python/cudf/tests/test_orc.py
- python/cudf/tests/test_parquet.py
- python/cudf/utils/ioutils.py
Fixes #1581 and fixes #1582.
- Add missing `import errno` and fix incorrect OR logic
- Change default engine `read_orc` docstring to match behavior
- Add pytests for file not found
> [REVIEW] ORC/Parquet Reader: Fix missing import for FileNotFoundError exception

- CHANGELOG.md
- python/cudf/dataframe/column.py
> [REVIEW] Return by reference if possible in `column.to_dense_buffer`

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_groupby.py
This is for compatibility with dask dataframe after https://github.com/dask/dask/pull/4771
> Support the group_keys=True parameter in groupby method

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_groupby.py
Auto-merge triggered by push to `branch-0.7` that creates a PR to keep `branch-0.8` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.7 to branch-0.8 [skip ci]

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
- cpp/src/io/orc/timezone.cpp
- cpp/src/io/orc/timezone.h
Fix ORC timestamp conversion to UTC
Fixes #1669
> [REVIEW] Fix ORC timestamp to UTC conversion

- CHANGELOG.md
- conda/recipes/cudf/meta.yaml
> [REVIEW] Add cython as runtime dependency to conda recipe

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
Minor change to avoid treating strings as lists when indexing a dataframe by the column name.  This bug is described in issue #1505
> [REVIEW] Fixing loc bug when indexing by column name

- README.md
Updates for `branch-0.7`:
* Updated build status icon for branch 0.7 build
* Removed docs status icon since doc generation is still manually invoked
* Updated version in install commands
* Removed PIP details
> [DOC] Updates for branch-0.7

- CHANGELOG.md
- python/cudf/dataframe/categorical.py
Fixes https://github.com/rapidsai/cudf/issues/1614, this PR is another 750ms perf improvement in my large-categorical perf dive. @kkraus14
> [WIP] Access CategoricalColumn categories by index instead of iteration

- CHANGELOG.md
- docs/source/dask-xgb-10min.ipynb
- docs/source/index.rst
* Fixed `index.rst` to properly point to `10min.ipynb`
* Added `dask-xgb-10min.ipynb` to `index.rst`
> [REVIEW] Add Docs for Dask-XGBoost

- CHANGELOG.md
- README.md
Added installation instructions for cudf version 0.6 and 0.7
> [REVIEW] update readme conda install instructions for cudf version 0.6 and 0.7

- CHANGELOG.md
- python/cudf/groupby/groupby.py
This resolves an issue in dask-cudf https://github.com/rapidsai/dask-cudf/issues/231
> [REVIEW] [HOTFIX] Fix issue by handling multiindex in series groupby

- CHANGELOG.md
- python/cudf/dataframe/index.py
> [REVIEW] Don't make RangeIndex the default choice for an empty index

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/multiindex.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
Resolves https://github.com/rapidsai/dask-cudf/issues/125
> [REVIEW] Concatenate MultiIndex from groupby results for dask-cudf

- CHANGELOG.md
- python/cudf/bindings/gpuarrow.pyx
- python/cudf/tests/test_gpu_arrow_parser.py
> [REVIEW] Fix handling read only schema buffers in gpuarrow reader

- CHANGELOG.md
- CONTRIBUTING.md
- build.sh
- ci/docs/build.sh
- ci/gpu/build.sh
- conda/recipes/cudf/build.sh
- conda/recipes/libcudf/build.sh
This PR adds a new top-level script named `build.sh` that allows a contributor to build from source using the same commands and options the CI system, container builds, doc builds, nightly unit test runs, and (eventually) ASV build & test iterations use. The relevant CI scripts have been updated to call this script and all related documentation should be updated as well.
This PR allows a maintainer to update the common build steps in one place while also simplifying the build process for all contributors and other build-related operations.
The changes were tested using the gpuCI container via the `ci/local/build.sh` testing script, where cudf branch-0.8 was successfully built and tested without errors.
> [REVIEW] Added build.sh script, updated CI scripts and documentation

- CHANGELOG.md
- cpp/src/io/parquet/parquet_reader.cu
- python/cudf/bindings/parquet.pyx
- python/cudf/tests/test_parquet.py
Fixes #1733.
When there is no explicit index column in the dataframe, the resulting Parquet file has index column data and an index column name that is auto-generated to `__index_level_0__` in the PANDAS-specific metadata.
When reading back the Parquet into a dataframe, the name for the index column should be `None` to match the original dataframe.
* Check for PANDAS compat when assigning index column name
* Fix index column name when it's a single character
* Add parameterized pytests for index col names
> [REVIEW] Parquet Reader: Fix index column name to match PANDAS compat

- CHANGELOG.md
- cpp/doxygen/Doxyfile
> [REVIEW] Update libcudf version in docs [skip ci]

- CHANGELOG.md
- build.sh
Assuming python is in PATH instead of using PYTHON env var, since gpuCI uses PYTHON for the version number.
> Assuming python is in PATH instead of using PYTHON env var

- CHANGELOG.md
- cpp/include/cudf/io_types.h
- cpp/src/io/orc/orc_reader.cu
- python/cudf/bindings/orc.pxd
- python/cudf/bindings/orc.pyx
- python/cudf/io/__init__.py
- python/cudf/io/orc.py
- python/cudf/tests/test_orc.py
- python/cudf/utils/ioutils.py
Fixes #1773.
* Add `read_orc_metadata` to return row and stripe info
* Add `stripe` parameter to read only a single stripe from file
* Add pytest for stripe reading
* Optimize `select_stripes` to not modify ff.stripes
- use vector alloc for stripefooters info
- use pointers rather than deferencing stripefooter struct
> [REVIEW] ORC Reader: Add support for stripe selection

- CHANGELOG.md
- cpp/include/cudf/types.h
- python/cudf/bindings/cudf_cpp.pxd
Fixes https://github.com/rapidsai/cudf/issues/1545
> [REVIEW] Fixing cudf reduction for POWER platform

- CHANGELOG.md
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
This fixes
https://github.com/rapidsai/dask-cudf/issues/263
> [REVIEW] Fix issue by with _apply_basic_agg operation string iterator bug

- CHANGELOG.md
- python/cudf/dataframe/numerical.py
- python/cudf/tests/test_pandas_interop.py
Fixed #1829 by manually constructing a Pandas series of type `np.object`.
> [REVIEW]Support of `to_pandas()` of boolean series with null values

- CHANGELOG.md
- python/cudf/bindings/join.pyx
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_joining.py
Fixed #1187. `merge()` now support the `left_on`, `right_on`, `sort` argument.
Removed the `on`  argument in `cpp_join.join()`, which now also returns the names of the joined columns.
In is up to `merge()` to either preserve the original order or sort them lexicographically.
Finally, I have simplified the clean up of the temporary columns used as indexes.
> [REVIEW] Support left_on and right_on for DataFrame merge operator 

- CHANGELOG.md
- python/cudf/bindings/stream_compaction.pyx
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
Uses apply_boolean_mask introduced in #1654.
Closes #1871
Closes #991
Depends on #1807
> [REVIEW] Expose `apply_boolean_mask` in Python for selection by boolmask

- CHANGELOG.md
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda9.2.yml
- python/cudf/dataframe/datetime.py
- python/cudf/dataframe/numerical.py
- python/cudf/dataframe/string.py
- python/cudf/tests/test_string.py
> [REVIEW] Add a bunch of missing typecasting to/from strings as well as tests

- CHANGELOG.md
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
This fixes: #1941 
1. Fixed the default value of `ignore_index`. We are setting it to `True`, where as pandas sets it to `False`.
2. Added unit tests to validate the same.
> [REVIEW] Ignore index fix in series append

- CHANGELOG.md
- python/cudf/tests/test_query.py
- python/cudf/utils/queryutils.py
> [REVIEW] Fix handling nulls in query

- CHANGELOG.md
- cpp/include/cudf/binaryop.hpp
- cpp/src/binaryop/jit/code/operation.cpp
- cpp/src/binaryop/jit/code/traits.cpp
- cpp/src/binaryop/jit/util/type.cpp
- python/cudf/bindings/binops.pxd
- python/cudf/bindings/binops.pyx
- python/cudf/tests/test_binops.py
> Implement pymod, a special modulo that follows python's sign rules

- CHANGELOG.md
- python/cudf/groupby/legacy_groupby.py
This PR fixes a bug introduced by #1759 
Closes issue #1989
> [REVIEW] Fix `apply_grouped` example rendering

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/io_functions.h
- cpp/include/cudf/io_readers.hpp
- cpp/include/cudf/io_types.h
- cpp/src/io/orc/orc_reader_impl.cu
- cpp/src/io/orc/orc_reader_impl.hpp
- python/cudf/bindings/orc.pxd
- python/cudf/bindings/orc.pyx
Issue #1668.
Update ORC reader interface:
* Add C++ interface to replace C-ish interface
- move ORC reader into the `cudf` namespace
- remove `read_orc()` and `orc_read_args`
- add `OrcReader` and `OrcReaderOptions`
- change the return type to `cudf::table` with exceptions
- replace C-style char strings and pointer/size pairs with C++ alternatives
* Update Cython bindings and wrapper layer
* Move ORC reader implementation to C++ impl class
> [REVIEW] Convert `read_orc()` into a C++ API

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda9.2.yml
> [REVIEW] Explicitly add pip to the environment files to remove warning [skip ci]

- CHANGELOG.md
- cpp/include/cudf/io_readers.hpp
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/src/io/cuio_common.cpp
- cpp/src/io/json/json_reader_impl.cu
- python/cudf/tests/test_csv.py
- python/cudf/tests/test_json.py
Fixes #2023.
This PR removes the hard-coding of '.csv' for uncompressed files, as the input could be `.txt` or `.data`, etc. Now, we simply treat any file that doesn't match a compressed type as uncompressed, to match PANDAS and expected behavior.
* If file extension does not match known types, treat as `none`
- remove explicit checks for `.csv` (could be `.txt`, etc.)
* Default to `none` as a compression type in args struct
- fixes issue where setting to `none` had no effect
* Add parametrized pytest for previously uncovered scenarios
- collapse the `gzip` and `bzip2` tests as well, since it's basically the same
> [REVIEW] CSV Reader: Fix reading of uncompressed files without a recognized file extension

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
Updated the java API to deal with the changes to read_csv and read_parquet
> [REVIEW] Updated java code to compile with modified parquet and csv apis [skip ci]

- CHANGELOG.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/Aggregate.java
- java/src/main/java/ai/rapids/cudf/BinaryOp.java
- java/src/main/java/ai/rapids/cudf/BinaryOperable.java
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/java/ai/rapids/cudf/UnaryOp.java
- java/src/main/java/ai/rapids/cudf/UnsafeMemoryAccessor.java
- java/src/main/native/src/CudfJni.cpp
- java/src/main/native/src/RmmJni.cpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
- java/src/test/java/ai/rapids/cudf/RmmMemoryAccessorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
- java/src/test/java/ai/rapids/cudf/UnaryOpTest.java
These are the latest changes/fixes to the java API.
> [REVIEW] Latest java code changes [skip ci]

- CHANGELOG.md
- python/cudf/dataframe/string.py
- python/cudf/tests/test_replace.py
* Implement find_and_replace for replacing single values in a StringColumn
* Raise `NotImplementedError` otherwise
> [HOTFIX] find_and_replace for StringColumn

- CHANGELOG.md
- python/cudf/dataframe/categorical.py
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/dataframe/string.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/utils.py
Add `reindex()` method to DataFrame and Series. No support for `level` yet until I get a better understanding of multi-indexes.
Unrelated to reindex itself (but necessary to get the tests passing), I also updated `DataFrame.merge` to pass the categorical dtype into `build_column` after the `cpp_join` call. Can split this out into a separate issue/PR if necessary.
Closes #1779.
> [REVIEW] Add reindex() to DataFrame and Series

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
Some of the java APIs for host buffers were not consistent with java APIs.  They were missing an offset.  This fixes that.
> [REVIEW] Added in offset param host buffer readers in java.

- CHANGELOG.md
- cpp/src/io/csv/csv_reader_impl.cu
- python/cudf/tests/test_csv.py
Fixes #2122.
It looks like a large diff due to changing tabs to spaces.
**TIP**: In the Github diff page, append `?w=1` to the URL to ignore whitespace to make it easier to review.
ex. [https://github.com/rapidsai/cudf/pull/2154/files?w=1](https://github.com/rapidsai/cudf/pull/2154/files?w=1)
* Move boolean value field check out of numeric check
- should be same place as NA field check
* Use spaces instead of tabs for indentation
* Add pytest
> [REVIEW] CSV Reader: Fix bools misdetected as strings dtype

- CHANGELOG.md
- python/cudf/cudf/tests/test_rolling.py
- python/cudf/cudf/window/rolling.py
> Add getitem and getattr methods to Rolling

- CHANGELOG.md
- python/cudf/cudf/dataframe/string.py
- python/cudf/cudf/tests/test_string.py
> [REVIEW] Fix issue in astype conversion of string column to 'str'

- CHANGELOG.md
- python/cudf/cudf/bindings/csv.pyx
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/utils/ioutils.py
This pr exposes the `chunksize` argument (number of rows to write out at a time). Particularly useful if the data to be written leads to OOM errors on GPU. (Since to_csv has a memory overhead)
Fixes #2137
> [REVIEW] Expose chunksize as param to_csv

- CHANGELOG.md
- cpp/src/utilities/type_dispatcher.hpp
No functional changes, documentation updates only.
> Added documentation for specializing type dispatched functors

- CHANGELOG.md
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/indexing.py
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/io/orc.py
- python/dask_cudf/dask_cudf/io/tests/test_orc.py
> [REVIEW] Fix one row dataframe head call

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- python/cudf/cudf/utils/ioutils.py
- Fixes #2182 
- Update `Readme.md` with 0.8 install instructions (prev 0.7)
- Update build from source instructions with new cudf path, added dask-cudf
- Unrelated to dask-cudf merge. Fixed typo in `to_csv` docs
> Doc fixes for install instructions

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/QuantileMethod.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/CudfJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
These are the java bindings for calculating exact and approx quantiles
> [Review] Support for Quantiles

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Aggregate.java
- java/src/main/java/ai/rapids/cudf/AggregateOp.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This uses the new Aggregate API
> [Review]Use the new aggregates API

- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] implement isna, isnull, notna as dataframe functions

- CHANGELOG.md
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/dataframe/index.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/tests/test_duplicates.py
> [REVIEW] Implement drop_duplicates for Series

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
This is follow-on PR that was discussed in https://github.com/rapidsai/cudf/pull/2212 .
> Readers: Remove copying of result pointers to gdf_column

- CHANGELOG.md
- python/cudf/cudf/bindings/groupby/groupby.pyx
- python/cudf/cudf/tests/test_groupby.py
> Fix erroneous conversion of groupby result to categorical

- CHANGELOG.md
- cpp/src/io/convert/dlpack/cudf_dlpack.cpp
- cpp/tests/io/convert/dlpack_test.cu
- python/cudf/cudf/tests/test_dlpack.py
> Fix for bug in DLPack read multiple columns

- CHANGELOG.md
- cpp/src/groupby/hash_groupby.cuh
- cpp/src/table/table.cpp
- cpp/tests/groupby/groupby_test.cu
- cpp/tests/join/join_tests.cu
- cpp/tests/orderby/orderby_tests.cu
- cpp/tests/utilities/column_wrapper.cuh
- cpp/tests/utilities/cudf_test_utils.cu
- cpp/tests/utilities/cudf_test_utils.cuh
> [REVIEW] Zero initialize gdf dtype extra info

- CHANGELOG.md
- python/cudf/cudf/dataframe/numerical.py
- python/cudf/cudf/tests/test_binops.py
> Handle float16 in normalize_binop_value

- CHANGELOG.md
- python/cudf/cudf/dataframe/column.py
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] Fix quantile api and other trivial issues around it

- CHANGELOG.md
- python/cudf/cudf/dataframe/columnops.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] Fix missing dtype handling in cudf.Series & columnops.as_column

- python/cudf/cudf/dataframe/index.py
- python/cudf/cudf/tests/test_categorical.py
- python/cudf/cudf/tests/test_index.py
1. Fixes: #2346 
2. Cleanup of `codes` and `categories` in `StringIndex` - do they need to be present ? They error and I don't see any code flow using them ?
> [REVIEW] Fixed issue with `codes` of CategoricalIndex

- CHANGELOG.md
- python/cudf/cudf/tests/test_rolling.py
- python/cudf/cudf/window/rolling.py
> Fix handling of window arg after Rolling.__getattr__/__getitem__

- python/cudf/cudf/bindings/unaryops.pxd
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/indexing.py
- python/cudf/cudf/tests/test_dataframe.py
This fixes:
1. #2383 
2. Build issue
We seem to be typecasting all datetimes to datetime[ms] in our series column formation too. Performing a similar typecast for a scalar value aswell.
> [REVIEW] Fix to a scalar datetime(of type Days) issue

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
> byte count for strings

- CHANGELOG.md
- python/cudf/cudf/bindings/copying.pyx
- python/cudf/cudf/bindings/sort.pyx
- python/cudf/cudf/bindings/typecast.pyx
- python/cudf/cudf/dataframe/buffer.py
- python/cudf/cudf/dataframe/datetime.py
- python/cudf/cudf/dataframe/numerical.py
- python/cudf/cudf/tests/test_avro.py
Mostly a convenience change 
* Replace `**kwargs` with default parameters
* Better handling of dtype parameter
> Small improvement to typecast utility

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/CudfJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Fixes some bugs in the JNI handling of empty strings and string categories.
> [REVIEW] Fix issues with empty strings and string categories

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Java column vector APIs for NVString based upper and lower string case mutators.
> Upper and lowercase mutators for string column vectors

- CHANGELOG.md
- python/cudf/cudf/dataframe/column.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_multi.py
- python/cudf/cudf/tests/utils.py
Fixes #1881 by implementing concatenation of dataframes with columns of different dtypes.
It uses [`np.find_common_type()`](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.find_common_type.html) to find a suitable data type and then cast the columns before the concatenation.
> [REVIEW] Concatenation of different typed columns

- CHANGELOG.md
- python/cudf/cudf/dataframe/string.py
PR makes a small change to the imports and usage of cudautils in string.py
cc @kkraus14
> fix cudautils import in string.py -- needed for ucp

- CHANGELOG.md
- conda/recipes/cudf/meta.yaml
Fixes https://github.com/rapidsai/cudf/issues/2544
> [REVIEW] Remove duplicate dlpack definition

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
> Bump numba version to 0.45.1

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/JSONOptions.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/CudfJni.cpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Java bindings for reading JSON file
> Java: parse JSON

- CHANGELOG.md
- python/cudf/cudf/bindings/copying.pyx
> Fix int32/int64 bug in _normalize_maps

- CHANGELOG.md
- cpp/benchmarks/search/search_benchmark.cu
- python/cudf/cudf/bindings/copying.pyx
Auto-merge triggered by push to `branch-0.9` that creates a PR to keep `branch-0.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.9 to branch-0.10 [skip ci]

- CHANGELOG.md
- java/pom.xml
Just updating the java version to match the CUDF version it is using.
> Update java version to 0.10-SNAPSHOT

- CHANGELOG.md
- python/cudf/cudf/bindings/groupby/common.pxd
- python/cudf/cudf/bindings/groupby/groupby.pyx
- python/cudf/cudf/bindings/groupby/hash.pxd
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/groupby/groupby.py
- python/cudf/cudf/tests/test_groupby.py
> Add groupby dropna= parameter

- CHANGELOG.md
- python/cudf/cudf/dataframe/series.py
Fixes https://github.com/rapidsai/cudf/issues/2576.
> fix docs discrepancy in Series.append

- CHANGELOG.md
- python/cudf/cudf/dataframe/categorical.py
- python/cudf/cudf/tests/test_dataframe.py
> Fix astype() for null categorical columns

- CHANGELOG.md
- cpp/src/io/orc/orc_reader_impl.cu
Skip_rows was not being adjusted after excluding stripes
Fixes #2633
> [REVIEW] ORC reader: Fix incorrect data when skip_rows does not fall within the first stripe

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ORCOptions.java
- java/src/main/java/ai/rapids/cudf/ParquetOptions.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Update Java API to be in sync with libcudf.
https://github.com/rapidsai/cudf/pull/2585 was merged recently.
> [REVIEW] Update Java bindings to specify timestamp units for ORC and Parquet readers

- CHANGELOG.md
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/tests/io/csv/csv_test.cu
> [REVIEW] Ensure csv reader sets datetime column time units

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
- python/cudf/cudf/core/groupby/legacy_groupby.py
PR Moves dispatching code from dask into cudf
I'll be change this PR from distributed accordingly: https://github.com/dask/distributed/pull/2998 
cc @mrocklin @kkraus14
> [REVIEW] Dask Serialization Dispatch

- CHANGELOG.md
- python/cudf/cudf/_lib/cudf.pyx
- python/cudf/cudf/tests/test_binops.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/utils/dtypes.py
Fixes #2671 
Current approach maps np.dtype('q') or np.longlong type to `int64`.
> [REVIEW] Add support for np.longlong

- CHANGELOG.md
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/utils/cudautils.py
- Fixes the null handling in the `round` kernel by simply passing nulls/NaNs through and using the column's mask to handle the resulting values.
- Fixes integer handling by short-circuiting the round for integer columns.
- Improves test robustness 
- Updates `round` to only allow non-negative `decimal` values.
Should've done all of these originally (my mistake).
This closes #2670
> [REVIEW] Fix null and integer handling in round

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/binaryop/binaryop.cpp
- cpp/src/jit/launcher.cpp
- cpp/src/jit/types_h_jit.cpp
- cpp/src/jit/types_h_jit.h
- cpp/src/rolling/rolling.cu
- cpp/src/transform/transform.cpp
This PR updates the submodule Jitify. The latest update in Jitify fixes a bug while running on Turing architecture using CUDA version < 10.
> Update dependency Jitify

- CHANGELOG.md
- cpp/benchmarks/CMakeLists.txt
> [REVIEW] Fix build issue with benchmarks

- CHANGELOG.md
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
- python/dask_cudf/dask_cudf/io/tests/test_csv.py
Addresses #2426 by handling a file-handle `path` input argument to `to_csv` (a feature assumed by dask).  Simple tests are added for cudf and dask_cudf.
> [REVIEW] Allow file-handle input to csv writer

- CHANGELOG.md
- cpp/src/io/avro/avro_reader_impl.cu
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/src/io/json/json_reader_impl.cu
- cpp/src/io/orc/orc_reader_impl.cu
- cpp/src/io/parquet/parquet_reader_impl.cu
Fixes #2667.
* Add a nullptr check to ensure `nvstrings` instance succeeded
> [REVIEW] IO Readers: Fix possible silent failures when creating `NvStrings` instance

- CHANGELOG.md
- java/pom.xml
- java/src/main/native/CMakeLists.txt
This just updates the java code where to find libNVStrings now that it is integrated into cudf.
> [REVIEW] Fix java build for nvstrings integration

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
This just updates the java code to use the new API.
> Fix java to use new quantile API

- CHANGELOG.md
- java/src/main/native/src/CudfJni.cpp
The check to allocate validity vectors for time processing functions does not match what libcudf expects.  This fixes it.
> Fix validity processing for time in java

- CHANGELOG.md
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_multiindex.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
This fixes #2696 by handling a mutliindex-based pandas Series in `from_pandas`.  The reproducers described in the issue have been added as tests.
> [REVIEW] Handing multiindex for Series.from_pandas

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Addresses https://github.com/rapidsai/cudf/issues/2359.
> [REVIEW] Stopgap alias for to_gpu_matrix()

- CHANGELOG.md
- README.md
Link to API Docs in the current README.md returns 404 - it currently points to 
https://rapidsai.github.io/projects/cudf/en/latest/index.html. 
It would appear the current best place to link to the API docs is https://docs.rapids.ai/api/cudf/stable/
> [REVIEW] Fix broken link to API Docs in README.md

- CHANGELOG.md
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/tests/io/csv/csv_test.cu
- python/cudf/cudf/tests/test_csv.py
Fixes #2626.
* Return an empty table or a table with columns of no rows
* Add gtest and pytests
> [REVIEW] CSV Reader: Fix exception when there's no rows to process

- CHANGELOG.md
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/src/io/csv/csv_reader_impl.hpp
Part 2 of #1667.
* Rename to match lower-case coding style
* Consolidate row offset filtering to single function
* Consolidate row offset gathering to single function
* Clean-up the header row parsing
> [REVIEW] CSV Reader: Clean-up row offset operations

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
This adds in some more debugging to help understand data movement in the java code.
> [REVIEW] Add in some more NVTX ranges to java code

- CHANGELOG.md
- python/dask_cudf/dask_cudf/io/parquet.py
- python/dask_cudf/dask_cudf/io/tests/test_s3.py
Fixes #2799 
Credit to @rjzamora for suggesting the approach. 
- Added a separate path for local filesystem to avoid creating a host buffer for the local filesystem case. Test with ~8GB of data showed that going via python host buffer was 25% slower than directly passing the filename down to libcudf. (1.08s vs 1.45s)
> [REVIEW] Dask-cudf read_parquet multiple filesystems

- CHANGELOG.md
- cpp/benchmarks/join/join_benchmark.cu
> Fixing join benchmark build

- CHANGELOG.md
- python/dask_cudf/dask_cudf/backends.py
Now that #2807 is merged, the `group_split_cudf` can be modified to simply return the result of `scatter_by_map`:
```python
@group_split.register(cudf.DataFrame)
def group_split_cudf(df, c, k):
return df.scatter_by_map(c, map_size=k)
```
Note that this PR also drops the registration of cudf.Series and cudf.Index since those types are not actually supported (and are not currently needed).
> [REVIEW] Update group_split_cudf to use scatter_by_map

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
- cpp/tests/utilities/cudf_gtest.hpp
- cpp/tests/utilities/type_list.hpp
- cpp/tests/utilities_tests/type_list_tests.cpp
> Add GTest type list utilities

- CHANGELOG.md
- python/dask_cudf/dask_cudf/io/parquet.py
[Dask#5391](https://github.com/dask/dask/pull/5391) recently changed the `ArrowEngine` code enough to break `dask_cudf.read_parquet`.  This PR should address these changes.
**What has changed**:  In order to avoid excessive task-graph sizes, `ArrowEngine` now assumes that the `ParquetDatasetPiece` can be created within `read_partition` (and not stored in the graph).
> [REVIEW] Fix dask_cudf read_parquet bug after upstream dask changes

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
- python/cudf/cudf/core/column/string.py
This PR makes cudf use the new [UCX Python bindings](https://github.com/rapidsai/ucx-py/pull/180). 
It depend on this DASK PR: [#3059](https://github.com/dask/distributed/pull/3059), which has now been merged.
> [REVIEW] Using the new UCX-Py

- CHANGELOG.md
- cpp/src/io/avro/avro_gpu.cu
- cpp/src/io/comp/brotli_dict.cpp
- cpp/src/io/comp/brotli_dict.h
- cpp/src/io/comp/cpu_unbz2.cpp
- cpp/src/io/comp/debrotli.cu
- cpp/src/io/comp/gpuinflate.cu
- cpp/src/io/comp/gpuinflate.h
- cpp/src/io/comp/io_uncomp.h
- cpp/src/io/comp/snap.cu
- cpp/src/io/comp/unbz2.h
- cpp/src/io/comp/uncomp.cpp
- cpp/src/io/comp/unsnap.cu
- cpp/src/io/orc/dict_enc.cu
- cpp/src/io/orc/stripe_data.cu
- cpp/src/io/orc/stripe_enc.cu
- cpp/src/io/orc/stripe_init.cu
- cpp/src/io/orc/timezone.cpp
- cpp/src/io/orc/timezone.h
- cpp/src/io/parquet/page_data.cu
- cpp/src/io/parquet/page_hdr.cu
- cpp/src/io/utilities/block_utils.cuh
- cpp/tests/io/comp/decomp_test.cu
Move compressors & decompressors to cudf::io namespace, share commonly used block-level macros & helpers.
> [REVIEW] Move GPU [de]compressors to cudf::io namespace

- CHANGELOG.md
- cpp/src/io/orc/stripe_enc.cu
Compressed size was not being updated if a block ends up being uncompressed.
> [REVIEW] Fix ORC writer uncompressed block indexing

- CHANGELOG.md
- cpp/src/io/comp/gpuinflate.cu
- cpp/src/io/comp/gpuinflate.h
- cpp/src/io/orc/orc_gpu.h
- cpp/src/io/orc/orc_reader_impl.cu
- cpp/src/io/orc/stripe_init.cu
All uncompressed blocks in a stream were being copied by a single warp, which is fine for the typical case of a single block of a few dozen bytes, but becomes extremely costly if we have large random data chunks. Keep track of uncompressed blocks, and use a separate kernel to make the copy.
> [REVIEW] Fix slow orc reader perf with large uncompressed blocks

- CHANGELOG.md
- python/cudf/cudf/_lib/avro.pyx
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/_lib/orc.pyx
- python/cudf/cudf/_lib/parquet.pyx
Fixes #2923.
* Use param type of `size_t` and `gdf_size_type` rather than `int`
* Move Avro reader to `nogil` calls
> [REVIEW] CSV Reader: Fix using `byte_range` for large datasets

- CHANGELOG.md
- cpp/src/io/comp/unsnap.cu
syncwarp before the non-literal reads rather than after non-literal writes (race condition for copy from an immediately preceding literal block, made more likely with PR #2887 )
> [REVIEW] Fix sm_70+ race condition in gpu_unsnap

- CHANGELOG.md
- cpp/src/io/orc/orc_writer_impl.cu
- cpp/tests/io/io_test_utils.cpp
- cpp/tests/io/io_test_utils.hpp
- cpp/tests/io/orc/orc_test.cpp
- python/cudf/cudf/tests/test_orc.py
Fixes #2960 and fixes #2976.
* Fix wrong index when string column isn't the first column
* Fix wrong index when subindexing into dictionary alloc
* Add gtest for mixed int/string columns
* Add pytest that's a variation of the repro sample provided by @ayushdg (thanks!)
> [REVIEW] ORC Writer: Segfault when writing mixed numeric and string columns

- CHANGELOG.md
- cpp/include/cudf/io_readers.hpp
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/src/io/cuio_common.cpp
- cpp/src/io/cuio_common.hpp
- cpp/src/io/io_functions.cpp
- cpp/src/io/json/json_reader_impl.cu
- cpp/src/io/json/json_reader_impl.hpp
- cpp/tests/io/json/json_test.cpp
- python/cudf/cudf/_lib/includes/json.pxd
- python/cudf/cudf/_lib/json.pyx
Fixes #2929.
* Add new C++ JSON (lines) reader ctors that take in Arrow file source and host buffer source
* Modifies Cython layer to conform with the other readers
> [REVIEW] JSON Reader: Support ARROW_RANDOM_FILE input

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Adds the ability to find and replace all values in a Column Vector 
From java docs:
Returns a vector with all values "oldValues[i]" replaced with "newValues[i]".
Warning:
Currently this function doesn't work for Strings or StringCategories.
NaNs can't be replaced in the original vector but regular values can be replaced with NaNs
Nulls can't be replaced in the original vector but regular values can be replaced with Nulls
Mixing of types isn't allowed, the resulting vector will be the same type as the original.
e.g. You can't replace an integer vector with values from a long vector
Usage:
this = {1, 4, 5, 1, 5}
oldValues = {1, 5, 7}
newValues = {2, 6, 9}
result = this.findAndReplaceAll(oldValues, newValues);
result = {2, 4, 6, 2, 6}  (1 and 5 replaced with 2 and 6 but 7 wasn't found so no …
> find and replace

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
Revert a commit from the ORC writer PR that was fixing a problem that did not exist.
> [REVIEW] Fix orc reader RLEv2 patch position regression

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/TimestampColumnVectorTest.java
Refactor some String category gather operation and add String Category support for timestamp conversion.
> asTimestamp string category support

- CHANGELOG.md
- cpp/src/io/comp/unsnap.cu
Attempt to process sequences of short 2-byte and 3-byte symbols in parallel
Merge consecutive but independent short lz77 copies
Greatly speeds up "slow" columns in the 1.5:1 to 2:1 compression range that tend to be the bottleneck (mix of 1-2 bytes literals and 6-7 bytes copies).
Switch to use negative distance to indicate a literal run as opposed to a greater-than-64 length, and reduce maximum stream size to 2GB to reflect the 31-bit distance/literal length limitation.
Remaining worst-case bottleneck are columns with heavy use of 3-4 bytes literals with 4-5 bytes copies (mostly unimpacted by this optimization), in the 1:1 to 1.4:1 range (typically semi-random float64 columns)
> [REVIEW] Snappy decompression optimizations phase 1

- CHANGELOG.md
- python/cudf/cudf/core/index.py
Calling `np.array` on a NumPy array will cause a copy. This can be avoided by calling `np.asarray`, which will preserve an existing array when passed in.
xref: https://github.com/rapidsai/cudf/issues/1888
> [REVIEW] Use `asarray` to coerce indices to a NumPy array

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
The location of a header changed and the java code needs to be fixed too.
> [REVIEW] Change java location of io_readers.hpp

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
This updates the APIs further for host side concatenation for serialized buffer.
> [REVIEW] Add in option to concat buffers on host

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Fixes https://github.com/rapidsai/cudf/issues/1037.
> [REVIEW] Dataframes cast on initialization if dtype is passed

- CHANGELOG.md
- cpp/src/table/table_view.cpp
- cpp/tests/CMakeLists.txt
- cpp/tests/table/table_view_tests.cu
Support for zero columned `table_view` and test case.
> [REVIEW]Support for zero columned `table_view`

- CHANGELOG.md
- cpp/src/io/orc/stripe_enc.cu
NULLs were being read from the wrong place for anything other than very short number of rows.
> [REVIEW] ORC writer: Fix ByteRLE encoding of NULLs

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
- java/src/main/native/CMakeLists.txt
- java/src/main/native/src/HostMemoryBufferJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/HostMemoryBufferTest.java
Expose in the java API some of the underlying buffers to make some I/O operations much faster.
> [REVIEW] Expose underlying buffers

- CHANGELOG.md
- cpp/src/io/orc/dict_enc.cu
Missing nullptr check in gpuCompactStringDictionaries, causing a crash if there are multiple string columns and at least one of them had its dictionary disabled in early detection.
> [REVIEW] Fix orc writer crash with multiple string columns

- CHANGELOG.md
- cpp/src/binaryop/legacy/binaryop.cpp
- cpp/src/io/csv/legacy/csv_reader_impl.cu
- cpp/src/io/legacy/io_functions.cpp
- cpp/src/io/orc/legacy/orc_reader_impl.cu
- cpp/src/iterator/legacy/iterator.cuh
This code is redundant and bothers me.
> [REVIEW] Small cleanup: remove `== true`

- CHANGELOG.md
- cpp/src/io/comp/uncomp.cpp
MacOS default zip v8.31 compressor apparently sets the minimum version to 7.88 instead of 2.0
> [REVIEW] Disable minimum zip version check when loading compressed csv

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_pandas_interop.py
This is a simple fix for the [current dask_cudf CI errors](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fcudf%2Fprb%2Fcudf-gpu-build/detail/cudf-gpu-build/4088/pipeline).  After a recent change in Dask,  `from_pandas` now needs to support `pd.RangeIndex`.
Thanks to @quasiben for pointing me to this issue and for suggesting this solution!
> [REVIEW] Handle pd.RangeIndex in from_pandas

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/replace.hpp
- cpp/src/replace/replace.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/replace/replace_tests.cu
Add normalize_nans_and_zeros functions (in-place and copying versions) and accompanying tests.
> Add cudf::normalize_nans_and_zeros.

- CHANGELOG.md
- cpp/include/cudf/table/row_operators.cuh
Part of https://github.com/rapidsai/cudf/issues/2931 needed for `hash` and `hash_partition`
> [REVIEW] Port row_hasher to cudf++

- CHANGELOG.md
- conda/recipes/cudf/meta.yaml
As `cython` is only needed to build the Python bindings and does not contain any needed runtime libraries, drop it from the run requirements.
> Drop `cython` from run requirements

- CHANGELOG.md
- python/cudf/cudf/tests/test_dataframe.py
Follow up to https://github.com/rapidsai/cudf/pull/3300/files.
> Fix `insert` non-assert test case

- CHANGELOG.md
- cpp/include/cudf/utilities/bit.hpp
This is a fix to the compilation errors some people were seeing with `bit.hpp`
```
.../bit.hpp(106): error: cannot use an entity undefined in device code
```
Adding `CUDA_HOST_DEVICE_CALLABLE` to all functions that can be called from device.
> [REVIEW] Adding device callable to bit functions

- CHANGELOG.md
- python/cudf/cudf/io/orc.py
- python/cudf/cudf/tests/test_orc.py
- python/dask_cudf/dask_cudf/io/orc.py
- python/dask_cudf/dask_cudf/io/tests/test_orc.py
While the main-line dask implementation of `read_orc` uses ORC **stripes** to partition tasks, the `dask_cudf` implementation currently uses entire files.  This can obviously be an issue for large files (large compared to GPU memory).  This PR simply borrows much of the upstream dask implementation to partition on stripes.
cc @randerzander
> [REVIEW] Partition by stripes in dask_cudf ORC reader

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Closes #3302 
After [dask#5579](https://github.com/dask/dask/pull/5579), upstream dask now supports the `dropna` argument for groupby aggregations (which is already supported by cudf).  This PR simply adds a `test_groupby_dropna` test to dask_cudf and removes assertions in `StringIndex` and `DatetimeIndex` that currently prevent index construction with null values.
> [REVIEW] Enable dropna kwarg in dask_cudf groupby aggregations

- CHANGELOG.md
- cpp/include/cudf/column/column_view.hpp
- cpp/include/cudf/detail/copy.hpp
- cpp/include/cudf/detail/valid_if.cuh
- cpp/src/copying/slice.cpp
- cpp/tests/utilities/column_utilities.hpp
Removing external includes from `column_view.hpp`
close #3385
> [REVIEW] Removing external includes from `column_view.hpp`

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/HostPrediction.java
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryListener.java
- java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/CudfTestBase.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
- java/src/test/java/ai/rapids/cudf/TimestampColumnVectorTest.java
Adds in a java API to track host off heap memory usage.
It also fixes a number of small memory leaks in the tests that I found while manually testing this patch.
> [REVIEW] Java host memory management API

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/tests/test_concat.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Closes #3420 
Small fix to preserve the StringColumn index name during concatination (and adding two related tests).
> Fix index-name bug in StringColumn concat

- CHANGELOG.md
- cpp/src/io/orc/legacy/orc_writer_impl.hpp
- cpp/src/io/orc/writer_impl.hpp
Was incorrectly defined as 4MB instead of the intended 64MB
> [REVIEW] Fix ORC Writer default stripe size

- CHANGELOG.md
- python/nvstrings/nvstrings.py
> Fix small doc error in capitalize Docs

- CHANGELOG.md
- cpp/src/io/orc/timezone.cpp
Timezone translation table had one extra unused entry, and the length is used to infer the number of transitions.
Fixes #3430
> [REVIEW] ORC reader: fix length of timezone table

- CHANGELOG.md
- cpp/docs/TRANSITIONGUIDE.md
Updating string_view and UTF-8 sections of the transition guide.
> [REVIEW] Update transition guide string_view section

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_index.py
Fixes https://github.com/rapidsai/cudf/issues/3477.
> [WIP] Fix as_index deep copy via Index.rename inplace arg

- CHANGELOG.md
- python/nvstrings/nvstrings.py
Small fixes to the NVStrings Docs
This fix closes #3121
> Fix errors in NVStrings Docs [Skip-CI]

- CHANGELOG.md
- cpp/include/cudf/detail/gather.cuh
- cpp/include/cudf/strings/detail/gather.cuh
- cpp/tests/copying/gather_tests.cu
- cpp/tests/copying/scatter_to_tables_tests.cpp
- cpp/tests/strings/gather_tests.cu
Gather has been updated to produce invalid rows in a table if an invalid index is contained in the gather map and if `ignore_out_of_bounds` is true.
> [REVIEW] Fix gather null mask allocation for invalid index

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_index.py
> [REVIEW] Fix index name issue with iloc/get_item in RangeIndex

- CHANGELOG.md
- python/dask_cudf/dask_cudf/core.py
Current [cudf test failures](https://gpuci.gpuopenanalytics.com/view/RAPIDS%20branch-gpu-matrix/job/rapidsai/job/gpuci/job/cudf/job/branches/job/cudf-gpu-matrix-branch-0.11/CC_VERSION=7,CUDA=10.0,LINUX_VERSION=centos7,PYTHON_VERSION=3.7/lastCompletedBuild/testReport/) are related to [a recent PR in main-line dask](https://github.com/dask/dask/pull/5613).  That change leads to a failure in dask_cudf, because it assumes that the parallel `DataFrame` constructor is using the `HighLevelGraph` API.  This fix does just that.
> [Hotfix]Use HighLevelGraph api in DataFrame constructor

- CHANGELOG.md
- python/cudf/cudf/tests/test_repr.py
> Fix 0.11 automerge [skip ci]

- CHANGELOG.md
- cpp/src/io/comp/uncomp.cpp
Iteratively decompress large files when the initial size is not known.
Fixes #731
> [REVIEW] Fix 4GB limit for gzipped-compressed csv files

- CHANGELOG.md
- java/pom.xml
Updating the package version to match the cudf version on branch-0.12.
> Update Java package to 0.12-SNAPSHOT

- CHANGELOG.md
- python/cudf/cudf/_lib/binops.pyx
- python/cudf/cudf/_lib/cudf.pyx
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/tests/test_binops.py
Closes https://github.com/rapidsai/cudf/issues/3552
> [REVIEW] Support python NoneType in numeric binops

- CHANGELOG.md
- cpp/include/cudf/detail/gather.cuh
> [REVIEW] Fix cuda memory access error in gather_bitmask_kernel

- CHANGELOG.md
- cpp/src/io/avro/legacy/avro_reader_impl.cu
- cpp/src/io/avro/reader_impl.cu
- python/cudf/cudf/tests/test_avro.py
AVRO reader was returning columns in reverse order by default, in an attempt to match fastavro results.
Instead, make the avro test dataframe comparison independent of column order.
Should resolve part of #2882
> [REVIEW] Remove avro column reordering

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/aggregation.hpp
- cpp/src/binaryop/legacy/binaryop.cpp
Closes https://github.com/rapidsai/cudf/issues/3613
Some additional changes needed to build cudf with gcc-8
> [REVIEW] Fixes for building with gcc-8

- CHANGELOG.md
- cpp/src/hash/concurrent_unordered_map.cuh
- cpp/src/hash/concurrent_unordered_multimap.cuh
- cpp/tests/hash_map/map_test.cu
- cpp/tests/hash_map/multimap_test.cu
Hash map test was failing due to missing `cudaStreamSynchronize(stream)`call, this was removed in the #3548 as per the discussion https://github.com/rapidsai/cudf/pull/3548#discussion_r355078040, so calling cuda sync in test.
> [REVIEW] Fix hash map test failure

- CHANGELOG.md
- cpp/include/cudf/types.hpp
- cpp/src/utilities/legacy/bit_util.cuh
- cpp/src/utilities/legacy/cudf_utils.h
Closes https://github.com/rapidsai/cudf/issues/3034
> [REVIEW] Remove duplicate CUDA_DEVICE_CALLABLE definitions

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_index.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Adding `from_pandas` definition for pd.Index, enabling `memory_usage` on dask_cudf DataFrame objects.  Although #3610 implemented `memory_usage` in cudf, these changes are needed for functionality in dask.
> [REVIEW] Enable memory_usage in dask_cudf

- CHANGELOG.md
- cpp/include/cudf/detail/sorting.hpp
- cpp/include/cudf/sorting.hpp
- cpp/src/sort/sort.cu
- cpp/tests/sort/sort_test.cpp
Adding cudf::sort and cudf::sort_by_key which will be using sorted_order and gather internally. Test cases have been updated to take care of these APIs as well.
close #3580
> [REVIEW] Adding cudf::sort and cudf::sort_by_key

- CHANGELOG.md
- cpp/src/io/orc/reader_impl.cu
- cpp/src/io/orc/writer_impl.cu
microseconds and milliseconds units were swapped in libcudf++ ORC reader & writer
Resolves #3658
> [REVIEW] Fix libcudf++ ORC swapped microseconds and milliseconds units

- CHANGELOG.md
- cpp/src/join/hash_join.cuh
CHECK_CUDA was not passing any stream argument, which caused the failure.
> [REVIEW] Fixing CHECK_CUDA debug build issue

- CHANGELOG.md
- python/nvstrings/cpp/pytext.cpp
- python/nvstrings/tests/test_text.py
This PR closes #3626. 
python-to-C++ code was not handling the devptr.
It required minor code changes and fixed now.
> fixed bug while passing input GPU memory pointer in nvtext.scatter_count()

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/transform.hpp
- cpp/include/cudf/transform.hpp
- cpp/src/transform/bools_to_mask.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/transform/bools_to_mask.cpp
Converting given bool column to equivalent mask. Null element is considered false.
closes #3275
> [REVIEW] Add bools_to_mask

- CHANGELOG.md
- cpp/include/cudf/column/column_device_view.cuh
- cpp/tests/CMakeLists.txt
- cpp/tests/column/column_device_view_test.cu
This adds support for begin/end iterators for mutable_column_device_view. But, this support is limited to only fixed_width_type columns.
> [REVIEW] Add mutable_column_device_view::begin()/end()

- CHANGELOG.md
- python/nvstrings/cpp/pytext.cpp
- python/nvstrings/nvtext.py
- python/nvstrings/tests/test_text.py
This PR closes #2801 after completion. I have changed the default delimiter to whitespace for the following functions in order to be in consistent with `nvtext.tokenize()`.
For more details, please refer: #2801
> changed the default delimiter to `whitespace` for nvtext methods 

- CHANGELOG.md
- cpp/src/hash/hashing.cu
- cpp/tests/hashing/hash_partition_test.cpp
Fixes bug mentioned at https://github.com/rapidsai/cudf/pull/3636#issuecomment-570716960
> [REVIEW] Fix hash_partition hashing all columns instead of columns_to_hash

- CHANGELOG.md
- cpp/src/join/hash_join.cuh
- cpp/tests/join/join_tests.cu
expected_size was getting changed even before it was getting compared because of which the indices size found were smaller and resizing later updated rest of the values with 0's.
closes #3702
> [REVIEW] Fix inner_join incorrect result issue

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_pickling.py
Fixes https://github.com/rapidsai/cudf/issues/3798
...but probably not what we want
> [REVIEW] Keep name when unpickling an Index

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/unary.hpp
- cpp/src/unary/nan_ops.cu
- cpp/tests/unary/unary_ops_test.cu
Adding support for is_nan and is_not_nan.
close #3763
> [REVIEW] Adding is_nan and is_notnan

- CHANGELOG.md
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
Due to https://github.com/cupy/cupy/issues/2971
> Avoid CuPy 7.1.0 for now

- CHANGELOG.md
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
> Fix automerge [skip-ci]

- CHANGELOG.md
- cpp/src/io/avro/legacy/avro_reader_impl.cu
- cpp/src/io/avro/reader_impl.cu
- python/cudf/cudf/tests/test_avro.py
rmm::device_buffer::size() was incorrectly being used (bytes) instead of the size of the original vector size (elements).
Re-enable the avro reader test
Fixes #3797
> [REVIEW] Fix cuda crash in AVRO reader

- CHANGELOG.md
- python/cudf/cudf/core/index.py
> Don't always deepcopy an index

- CHANGELOG.md
- cpp/src/io/parquet/writer_impl.cu
Writing an empty dataframe causes launch errors.
Needed for #3716 (test coverage on the python side)
> [REVIEW] Parquet writer: fix empty dataframe causing cuda launch errors

- CHANGELOG.md
- python/cudf/cudf/_lib/cudf.pyx
> [REVIEW] Fix memory leak in string columns with nulls

- CHANGELOG.md
- cpp/src/io/comp/gpuinflate.cu
gzip header length was not being subtracted from the inflate data size
Fixes OOB part of #3800
> [REVIEW] Fix OOB read in gpuinflate prefetcher

- ci/release/update-version.sh
Just updating the version in nvstrings docs
> [REVIEW] Add nvstring full version to update-version.sh [skip-ci]

- CHANGELOG.md
- cpp/include/cudf/detail/gather.cuh
- cpp/include/cudf/strings/detail/gather.cuh
libcudf build was broken in debug mode with the following error message
```
[build] [  2%] Building CUDA object CMakeFiles/cudf.dir/src/round_robin/round_robin.cu.o
[build] [  2%] Building CUDA object CMakeFiles/cudf.dir/src/filling/repeat.cu.o
[build] /Users/dmakkar/Developer/GrpQuantile/cudf/cpp/include/cudf/types.hpp(190): error: calling a __host__ function("std::vector< ::cudf::column_view, std::allocator< ::cudf::column_view> > ::~vector") from a __host__ __device__ function("cudf::column_view::~column_view") is not allowed
[build] 
[build] 1 error detected in the compilation of "/tmp/tmpxft_00004ff3_00000000-6_round_robin.cpp1.ii".
[build] CMakeFiles/cudf.dir/build.make:127: recipe for target 'CMakeFiles/cudf.dir/src/round_robin/round_robin.cu.o' failed
[build] make[3]: *** …
```
> [REVIEW] Fixes the broken debug build

- CHANGELOG.md
- cpp/src/column/column.cu
- cpp/tests/copying/slice_tests.cu
- cpp/tests/utilities/column_utilities.cu
This PR is in order to address https://github.com/rapidsai/cudf/issues/3885
> [REVIEW] materializing a string column from a sliced string view fix

- CHANGELOG.md
- cpp/src/io/parquet/legacy/parquet_reader_impl.cu
- cpp/src/io/parquet/reader_impl.cu
Rowgroup array index zero was being used regardless of array being empty
Needed for #3716
> [REVIEW] Fix segfault reading empty parquet file

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
cc @mike-wendt who asked me to put this in for 0.12
> [REVIEW] Fix libcudf tests cmake to properly detect and link against nvstrings and nvcategory

- CHANGELOG.md
- conda/recipes/cudf/meta.yaml
- cpp/tests/CMakeLists.txt
- python/cudf/cudf/_libxx/__init__.py
- python/cudf/cudf/_libxx/column.pyx
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
PR to solve conflicts of automerge #3901
> [REVIEW] Solve conflicts of automerge #3901 

- CHANGELOG.md
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Closes #3954 
Adds dispatch function definition for cudf.Series (and corresponding test coverage).
> [REVIEW] Add dask_cudf dispatch function to hash cudf.Series

- CHANGELOG.md
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_pickling.py
> [REVIEW] Fix Series pickle

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
Cleans up some of the special case handling in the `else` case in `Buffer`. Also handles any Python objects supporting [the Python Buffer Protocol]( https://docs.python.org/3/c-api/buffer.html ).
> Simplify and generalize data handling in `Buffer`

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
Adding `as_table` to convert Column to Table in python, this will help pass column as tables to lower cython APIs that expect Table such as `drop_nulls`, `drop_duplicate` and etc.
> [REVIEW] Adding `as_table` to convert Column to Table in python

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/UnaryOp.java
- java/src/test/java/ai/rapids/cudf/UnaryOpTest.java
This brings the java unary ops inline with the c++ code again.
> [REVIEW] Fix java unary op enum and add missing ops

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/frame.py
Adding to_frame and fix for categorical column issue
> [REVIEW] Adding to_frame and fix for categorical column issue

- CHANGELOG.md
- build.sh
This update will enable building and running cudf without installing into conda environment. 
`build.sh -n` will work now without the need to install nvstrings (also set `export NVSTRINGS_ROOT=cpp/build`).
_Additional information:_
Instructions for setting up cudf build without installation. 
https://github.com/karthikeyann/dotfiles/blob/master/conda/build_cudf_without_installing.sh
> [REVIEW] Updates to enable cudf build without installing

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/utils/cudautils.py
> Drop old `to_device` utility wrapper function

- CHANGELOG.md
- python/cudf/cudf/_libxx/io_types.pxd
> added cython definition for io readers cudf/io/io_types.hpp

- CHANGELOG.md
- cpp/include/cudf/io/functions.hpp
- cpp/include/cudf/io/readers.hpp
- cpp/src/io/functions.cpp
- cpp/src/io/orc/reader_impl.cu
- cpp/src/io/orc/reader_impl.hpp
- cpp/src/io/parquet/reader_impl.cu
- cpp/src/io/parquet/reader_impl.hpp
Removes the 1-group limit to the rowgroup/stripe-based API
Should help perf with dask
> [REVIEW] ORC/Parquet: add count parameter to stripe/rowgroup-based reader API

- CHANGELOG.md
- python/cudf/cudf/_lib/cudf.pyx
- python/cudf/cudf/_lib/unaryops.pyx
> [REVIEW] Fix memory leaks in `GDF_STRING` cython and `nans_to_nulls` cython

- CHANGELOG.md
- cpp/src/column/column.cu
Closes https://github.com/rapidsai/cudf/issues/4006
> [REVIEW] Eliminate extra copy in column constructor

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
This fix on JNI side incorporates the changes to quantile per : https://github.com/rapidsai/cudf/pull/4021
> [REVIEW] Fix JNI quantile compile issue

- CHANGELOG.md
- cpp/include/cudf/copying.hpp
- cpp/src/copying/contiguous_split.cu
- cpp/src/copying/split.cpp
- cpp/tests/copying/split_tests.cu
This was due a check which removed the last possible vector. 
close #4027
> [REVIEW] Fix `cudf::split` issue returning one less than expected column vectors

- CHANGELOG.md
- cpp/src/io/parquet/page_dict.cu
Parquet dictionary encoding may result in out-of-range dictionary indices
Fixes #4034
> [REVIEW] Parquet writer: fix for out-of-range dictionary indices

- CHANGELOG.md
- cpp/include/cudf/types.hpp
- cpp/src/column/legacy/interop.cpp
- cpp/src/io/utilities/type_conversion.cu
- cpp/tests/utilities/type_lists.hpp
- python/cudf/cudf/_libxx/lib.pxd
Closes https://github.com/rapidsai/cudf/issues/4048
> [REVIEW] Removed unused CATEGORY type_id

- CHANGELOG.md
- python/dask_cudf/dask_cudf/tests/test_groupby.py
sort_index for multi_index has issues and need to be addressed. So, using sort_values and then reset_index.
> [REVIEW] Fix multi-index dask test with sort issue

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
This has fix for two sets of test case failure.
Thank you @rjzamora for helping me on this bug.
Hopefully the last.
> [REVIEW] Fix dask groupby mutliindex test case issues in join

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
> Simply use `mask.size` to create the array view

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
> Copy from `Buffer`'s pointer directly to host

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
> Keep mask on GPU for bit unpacking

- CHANGELOG.md
> [REVIEW] Fix automerge 0.12 --> 0.13 [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/PartitionedTable.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This adds Java bindings for libcudf's `round_robin_partition`.
> Add Java bindings for round robin partition

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
When use_index is enabled, and the last rowgroup contains fewer than 1024 rows, it is possible for the initial run offset to result in fewer values produced by the RLE decoding of the secondary data stream result than the RLE run of the primary data stream.
When this happens, the primary data stream produces zero output, and the deadlock prevention logic would bypass the normal RLE decoding of the primary data stream, resulting in zero or no output.
Fixes #4047
> [REVIEW] ORC reader: fix potentially incorrect timestamp decoding in last rowgroup

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
> Added cast of numeric columns to/from string

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
As `Buffer` objects are faster and lighter weight to construct (not to mention the future of handling data in cuDF), construct `Buffer` objects to hold the relevant string content. These can then be added as frames to send with Distributed and UCX-Py since they know how to ship them.
cc @kkraus14 @quasiben
> Use `Buffer`'s to serialize `StringColumn`

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/aggregation.hpp
- cpp/include/cudf/detail/aggregation/aggregation.hpp
- cpp/include/cudf/reduction.hpp
- cpp/src/aggregation/aggregation.cpp
- cpp/src/groupby/sort/group_nunique.cu
- cpp/src/groupby/sort/group_reductions.hpp
- cpp/src/groupby/sort/groupby.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/groupby/sort/group_nunique_test.cu
addresses C++ portion of #1974
> [REVIEW] add groupby.nunique() aggregation

- .gitignore
- CHANGELOG.md
- python/cudf/cudf/_libxx/lib.pxd
> [REVIEW] Add dictionary to Cython type enum

- CHANGELOG.md
- python/cudf/cudf/_libxx/io/functions.pxd
- python/cudf/cudf/_libxx/io/io_types.pxd
- python/cudf/cudf/_libxx/io/types.pxd
> [REVIEW] Port cudf/io/functions.hpp to cython

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
- python/cudf/cudf/core/buffer.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/dtypes.py
- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/series.py
Dask uses the "type-serialized" header to store pickled type information. Not to mention the "type" header is often used by Dask to mean something different. As a result Dask could potentially stomp on the information we are storing in the "type" header. So instead of deviating from Dask, just store the pickled type information in "type-serialized" as well. This should make it easier to more tightly integrate our serialization with Dask's down the road.
> Use "type-serialized" for pickled types like Dask

- CHANGELOG.md
- cpp/include/cudf/detail/groupby/sort_helper.hpp
- cpp/src/groupby/sort/group_nunique.cu
- cpp/src/groupby/sort/group_quantiles.cu
- cpp/src/groupby/sort/group_reductions.hpp
- cpp/src/groupby/sort/groupby.cu
- cpp/src/groupby/sort/sort_helper.cu
> [REVIEW] groupby group_offsets size and unnecessary device dispatch fix.

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
To match the type used for device arrays viewing `Buffer`, also use `uint8` for host arrays created from `Buffer`. This also matches the type of `bytes` and `bytearray` in Python.
> Use `uint8` type for host array copy of `Buffer`

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
To simplify cuDF's registration of serializers, list the classes once and just reuse this list in all places where it is needed.
> List serializable classes once

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
As these serialization functions are no longer `DataFrame` specific, rename them to more generically refer to cuDF objects that can be serialized.
> Rename cuDF serialize functions to be more generic

- CHANGELOG.md
- cpp/src/io/parquet/page_dict.cu
nvstr_hash16 was potentially reading an extra 4 bytes if the string was not 4B aligned
> [REVIEW] Parquet writer: fix OOB read when computing string hash

- CHANGELOG.md
- python/cudf/cudf/_libxx/__init__.py
- python/cudf/cudf/_libxx/includes/transpose.pxd
- python/cudf/cudf/_libxx/transpose.pyx
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/dtypes.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_multiindex.py
libcudf++ transpose bindings for DataFrame. Closes #3947.
> [REVIEW] Add libcudf++ transpose Cython implementation

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Java ColumnVector.asString(format) can be used to cast a timestamp into a string vector given a strftime format string. 
;
> implemented asString method on ColumnVector

- CHANGELOG.md
- ci/gpu/build.sh
- ci/gpu/test-notebooks.sh
- ci/utils/nbtest.sh
- ci/utils/nbtestlog2junitxml.py
Added notebook testing to gpu ci build.
> [REVIEW] Add notebook testing

- .gitattributes
- CHANGELOG.md
This should reduce our frequent merge conflicts of `CHANGELOG.md` in PRs.
https://about.gitlab.com/blog/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/#update
> [REVIEW] reduce CHANGELOG.md merge conflicts [skip ci]

- CHANGELOG.md
- cpp/src/io/utilities/block_utils.cuh
> [REVIEW] Fix potential race condition in memcpy_block

- CHANGELOG.md
- cpp/include/cudf/aggregation.hpp
- cpp/include/cudf/detail/aggregation/aggregation.cuh
- cpp/include/cudf/detail/aggregation/aggregation.hpp
- cpp/include/cudf/rolling.hpp
- cpp/src/aggregation/aggregation.cpp
- cpp/src/groupby/hash/groupby.cu
- cpp/src/groupby/sort/group_count.cu
- cpp/src/groupby/sort/group_reductions.hpp
- cpp/src/groupby/sort/groupby.cu
- cpp/src/rolling/rolling.cu
- cpp/src/rolling/rolling_detail.hpp
- cpp/tests/groupby/sort/group_count_test.cu
- cpp/tests/groupby/sort/groupby_keys_test.cu
- cpp/tests/rolling/rolling_test.cpp
closes https://github.com/rapidsai/cudf/issues/3708
> [REVIEW] Add COUNT aggregation that includes null values

- CONTRIBUTING.md
Fix for #4178, 
Build steps in documentation changed per actual run and review comments in #4178 , no unit-test for code required.
> [DOC][REVIEW] Update to build nvstrings using standalone make [skip ci]

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Fixes the java tests after changes to windowing went in.
> [REVIEW] Fixed java window tests

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
> Exposing the getNativeView() to public

- CHANGELOG.md
- python/cudf/cudf/_libxx/lib.pxd
- python/cudf/cudf/core/dataframe.py
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/tests/test_core.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Closes #4090 
Fixes a bug in `python/cudf/cudf/core/dataframe.py::_take_columns` and addresses some problems with the `to_pandas`-`from_pandas` round-trip used to create `meta_nonempty` in dask_cudf.  Both of these bugs lead to problematic "dtype-preservation" during certain dask_cudf operations.
> [REVIEW] Fix dtype-preservation bugs in cudf/dask_cudf

- CHANGELOG.md
- cpp/src/io/parquet/page_data.cu
Unsafe read of page_state_s.out_pos can cause writing data to the wrong row
> [REVIEW] Fix race condition in parquet reader

- CHANGELOG.md
- cpp/src/rolling/jit/code/kernel.cpp
- cpp/src/rolling/rolling.cu
- cpp/tests/rolling/rolling_test.cpp
It seems like compiler optimization was causing issues, for which I am using volatile keyword to keep the `process_rolling_window` and `ballot_sync` separate. This seems to stop the erratic failures in rolling. There are couple of other changes which handles negative indices. This PR is derived from #4185 which will be closed.
> [REVIEW] Fix for rolling tests CI failure

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Fixes the java build now that hash aggregation has gone in.
> [REVIEW] Fix java build errors around hash aggregate [skip ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
> [REVIEW] Fix losing `StringIndex` name in `_meta_nonempty`

- CHANGELOG.md
- cpp/src/io/parquet/page_data.cu
Data offset may be incorrectly considered out-of-range
Fixes #4286
> [REVIEW] Parquet reader: fix empty string potentially read as null

- CHANGELOG.md
- python/cudf/cudf/_libxx/__init__.py
- python/cudf/cudf/_libxx/arrow/_cuda.pxd
- python/cudf/cudf/_libxx/arrow/_cuda.pyx
- python/cudf/cudf/_libxx/cpp/arrow/libarrow_cuda.pxd
- python/cudf/cudf/_libxx/cpp/gpuarrow.pxd
- python/cudf/cudf/_libxx/gpuarrow.pyx
- python/cudf/cudf/_libxx/move.pxd
- python/cudf/cudf/comm/gpuarrow.py
Moves `gpuarrow.pyx` and related files into `_libxx`, clean up a few import paths while we're at it. Closes https://github.com/rapidsai/cudf/issues/3932.
> [REVIEW] Move gpuarrow.pyx and related libarrow_cuda files into _libxx

- CHANGELOG.md
- python/cudf/cudf/_libxx/unary.pyx
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/column/string.py
> [REVIEW] Port casting to new libcudf APIs

- .gitignore
> Ignore dask-worker-space

- CHANGELOG.md
- cpp/src/io/parquet/reader_impl.cu
Make sure to always create columns even if not reading any rowgroups
Needed for #4290
> [REVIEW] Parquet reader: allow returning empty columns

- CHANGELOG.md
- cpp/src/groupby/groupby.cu
- cpp/tests/groupby/sort/group_count_test.cu
- cpp/tests/groupby/sort/group_max_test.cu
- cpp/tests/groupby/sort/group_mean_test.cu
- cpp/tests/groupby/sort/group_median_test.cu
- cpp/tests/groupby/sort/group_min_test.cu
- cpp/tests/groupby/sort/group_nth_element_test.cu
- cpp/tests/groupby/sort/group_nunique_test.cu
- cpp/tests/groupby/sort/group_quantile_test.cu
- cpp/tests/groupby/sort/group_std_test.cu
- cpp/tests/groupby/sort/group_sum_test.cu
- cpp/tests/groupby/sort/group_var_test.cu
Fixed #4293 
Adds empty cols test to every agg to test dtype of output.
> [REVIEW] Fix empty values case in groupby

- CHANGELOG.md
- python/dask_cudf/dask_cudf/backends.py
[dask#5973](https://github.com/dask/dask/pull/5973) introduces the `ignore_index=` argument to the `group_split_dispatch` and `concat_dispatch` functions.  ~This~ **The upstream** change improves the performace of `set_index`, but will break the `dask_cudf` code without the changes introduced in this PR.
> [REVIEW] Preemptive fix for expected dask.dataframe dispatch changes

- python/cudf/cudf/_libxx/cpp/strings/wrap.pxd
- python/cudf/cudf/_libxx/strings/wrap.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
This implements one api(`wrap`) in : #3992 
Had to do it as a separate PR due to git issues to pull changes in the original PR: #4311
> [REVIEW] Port libcudf strings wrap api to cython/python

- CHANGELOG.md
- cpp/src/io/functions.cpp
- cpp/src/io/parquet/chunked_state.hpp
- cpp/src/io/parquet/parquet.h
- cpp/src/io/parquet/writer_impl.hpp
Last minute change Olivier and I discussed didn't get in before the previous PR was merged. 
https://github.com/rapidsai/cudf/pull/4345
> [REVIEW] Move pq_chunked_state into it's own header file to match orc.

- CHANGELOG.md
- cpp/include/cudf/io/functions.hpp
- cpp/include/cudf/io/writers.hpp
- cpp/src/io/functions.cpp
- cpp/src/io/orc/chunked_state.hpp
- cpp/src/io/orc/orc.h
- cpp/src/io/orc/writer_impl.cu
- cpp/src/io/orc/writer_impl.hpp
- cpp/src/io/parquet/writer_impl.cu
- cpp/tests/io/orc_test.cu
[Mostly copy-pasting from the parquet chunked support]
Resolves #3004 
Also handle correct base column data ptr, which should resolve #4359
> [REVIEW] chunked write support for ORC writer

- CHANGELOG.md
- cpp/src/io/comp/gpuinflate.cu
state->blast is used at the end of the loop but could be modified at the start of the next iteration.
Tentative fix for #3883
> [REVIEW] Fix race condition in gpuinflate

- CHANGELOG.md
- java/pom.xml
Updating the pom to reflect the updated project version.
> Update Java package to 0.14-SNAPSHOT [skip ci]

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/dask-cudf/meta.yaml
> Require Dask + Distributed 2.12.0+

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Now that following issues are fixed, enabling stuff related to them:
#4255 
#4355 
#4318
> [REVIEW] Enable `.str.slice` & `.str.get` and `.str.zfill` unit-tests

- CHANGELOG.md
- python/cudf/cudf/_libxx/column.pyx
- python/cudf/cudf/_libxx/copying.pyx
- python/cudf/cudf/_libxx/hash.pyx
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_string.py
Should have used base_size while creating the column from column view.
> [REVIEW] Fix string issue for parquet reader and support `keep_index` for `scatter_to_tables`

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Enabling `.str.cat` since the following issues are fixed:
#4361 
#4349
#4395
Fixing `.str.split` as needed from the discussion we had in : 
#4357
> [REVIEW] Enable `.str.cat` and fix `.str.split` on python side

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/tests/test_dropna.py
> [REVIEW] Fix dropna issue for a DataFrame having np.nan

- CHANGELOG.md
- cpp/src/io/parquet/reader_impl.cu
Lines got swapped in the port. Needed for PR #4290
> [REVIEW] Fix use_pandas_index having no effect in libcudf++ parquet reader

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/BinaryOp.java
- java/src/main/java/ai/rapids/cudf/BinaryOperable.java
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
> [REVIEW] java bindings for bitwise shift operators [skip ci]

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
PR fixes and an assertion error when cuda frames are 0 length
cc @kkraus14
> Fix 0 length buffers during serialization 

- cpp/include/cudf/binaryop.hpp
- python/cudf/cudf/_libxx/__init__.py
- python/cudf/cudf/_libxx/binaryop.pxd
- python/cudf/cudf/_libxx/binaryop.pyx
- python/cudf/cudf/_libxx/cpp/binaryop.pxd
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/tests/test_udf_binops.py
> [WIP] Port binaryop cython

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Allow bindings to do string match for regex patterns.
> [REVIEW] Add JNI and java bindings for matches_re [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/replace.hpp
- cpp/src/groupby/hash/groupby.cu
- cpp/tests/groupby/sort/group_max_test.cu
- cpp/tests/groupby/sort/group_min_test.cu
- python/cudf/cudf/_libxx/__init__.py
- python/cudf/cudf/_libxx/cpp/nvtext/generate_ngrams.pxd
- python/cudf/cudf/_libxx/cpp/nvtext/ngrams_tokenize.pxd
- python/cudf/cudf/_libxx/cpp/nvtext/normalize.pxd
- python/cudf/cudf/_libxx/cpp/nvtext/tokenize.pxd
- python/cudf/cudf/_libxx/nvtext/generate_ngrams.pyx
- python/cudf/cudf/_libxx/nvtext/ngrams_tokenize.pyx
- python/cudf/cudf/_libxx/nvtext/normalize.pyx
- python/cudf/cudf/_libxx/nvtext/tokenize.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_text.py
- python/dask_cudf/dask_cudf/accessor.py
- python/dask_cudf/dask_cudf/core.py
- python/nvstrings/cpp/CMakeLists.txt
> [REVIEW] Fix 0.14 automerge [skip ci]

- CHANGELOG.md
- python/cudf/cudf/_libxx/parquet.pyx
- python/cudf/cudf/tests/test_parquet.py
> [REVIEW] Remove copying to host for metadata generation in `generate_pandas_metadata`

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
- python/cudf/cudf/core/column/string.py
Auto-merge triggered by push to `branch-0.13` that creates a PR to keep `branch-0.14` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
> Register a few more types for Dask serialization

- CHANGELOG.md
- cpp/src/groupby/sort/legacy/sort_helper.cu
This fix is needed in case we might have to roll back to legacy groupby for python.
> [REVIEW] Fix exec dangling pointer issue in legacy groupby

- CHANGELOG.md
- cpp/benchmarks/fixture/benchmark_fixture.hpp
Benchmark builds were broken after recent thrust_allocator PR.
> [REVIEW] Added missing rmm_api.h include to benchmark_fixture.hpp

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR adds Java and JNI bindings for string replace
> [REVIEW] Add Java and JNI bindings for string replace [skip ci]

- CHANGELOG.md
- cpp/src/io/orc/stripe_enc.cu
> [REVIEW] Fix potential OOB write in ORC writer compression stage

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_copying.py
- python/dask_cudf/dask_cudf/backends.py
Resolves: #4334 
Rest of the usages of `nvstrings` are to be kept intact and decided to be removed in `0.14`.
> [REVIEW] Remove usage of `nvstrings` in `data_array_view`

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] String concatenation fix in `DataFrame.rename`

- CHANGELOG.md
- cpp/include/cudf/binaryop.hpp
- cpp/src/binaryop/jit/code/operation.cpp
- cpp/src/binaryop/jit/util.hpp
- cpp/tests/binaryop/binop-integration-test.cpp
- cpp/tests/binaryop/util/operation.h
this pr Closes #3765 by providing a binary operator to compute log of an arbitrary base
> [REVIEW] binary operator to compute log of an arbitrary base

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_stats.py
> [REVIEW] Add Alias for `kurtosis` as `kurt`

- CHANGELOG.md
- cpp/include/cudf/scalar/scalar_factories.hpp
- cpp/src/strings/strings_scalar_factories.cpp
- cpp/tests/scalar/factories_test.cpp
- cpp/tests/strings/factories_test.cu
Fixes #4085 
Fixes https://github.com/rapidsai/cudf/issues/4085#issuecomment-583953626
> [REVIEW] Fix validity bug in string scalar factory

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
keep_index wasn't properly handled while gathering key indices.
close #4647
> [REVIEW] Fix to handle `keep_index` in `partition_by_hash`

- CHANGELOG.md
- python/dask_cudf/dask_cudf/sorting.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Small bug fix in `_shuffle_group` (ensuring that `scatter_by_map` is called correctly).
> Bug fix in _shuffle_group for repartition

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
- python/cudf/cudf/core/groupby/groupby.py
`black` changed the groupby code, not sure why it wasn't caught previously 🤷‍♂
> [REVIEW] Upgrade numba version requirement

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Adds java and JNI bindings for contains_re regex method.
> [REVIEW] Add java and JNI bindings for contains_re [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/BinaryOp.java
- java/src/main/java/ai/rapids/cudf/BinaryOperable.java
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
- java/src/test/java/ai/rapids/cudf/UnaryOpTest.java
Adds Java bindings for:
- log2 unary op
- log10 unary op
- log_base binary op
> [REVIEW] Add Java bindings for log2/log10 unary ops and log_base binary op [skip ci]

- CHANGELOG.md
- build.sh
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/sorting.hpp
- cpp/include/cudf/rolling.hpp
- cpp/include/cudf/sorting.hpp
- cpp/src/rolling/rolling.cu
- cpp/src/sort/rank.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/grouped_rolling/grouped_rolling_test.cpp
- cpp/tests/sort/rank_test.cpp
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/java/ai/rapids/cudf/WindowAggregate.java
- java/src/main/java/ai/rapids/cudf/WindowAggregateOp.java
- java/src/main/java/ai/rapids/cudf/WindowOptions.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
- python/cudf/cudf/_libxx/cpp/sorting.pxd
- python/cudf/cudf/_libxx/cpp/types.pxd
- python/cudf/cudf/_libxx/sort.pxd
- python/cudf/cudf/_libxx/sort.pyx
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_rank.py
Fixing simple merge conflicts with CHANGELOG and TableJni.cpp.  Also adds CUDF_TEST_PROGRAM_MAIN to the grouped rolling test so RMM gets initialized properly.
> Fix merge of branch-0.13 into branch-0.14

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/BaseDeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryCleaner.java
- java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/main/native/src/CudaJni.cpp
- java/src/test/java/ai/rapids/cudf/HostMemoryBufferTest.java
This exposes some CUDA APIs for events and streams synchronization.  It also makes the MemoryCleaner more scalable and stable.  It is getting used a lot more for various things and we want it to be efficient.
> [REVIEW] Expose events and more stream functionality in java [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/tests/test_indexing.py
> [REVIEW] Fix loc issue with Multiindex on DataFrame and Series

- CHANGELOG.md
- cpp/tests/io/comp/decomp_test.cu
> [REVIEW] Fix decompression gtests using EXPECT_STREQ to compare byte arrays

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/CudfTestBase.java
This updates the java quantile API and tests to match the modified cudf API
> [REVIEW] Fix Java build to deal with new quantiles API [skip-ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Expose the sequence API through java.
> [REVIEW] Add in java support for sequence [skip ci]

- CHANGELOG.md
These were mistakenly removed in #4235
> DOC Add missing changelog entries [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_dataframe.py
Test cases have been added.
closes #2735
> [REVIEW] Fix dataframe slicing with strides

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
> [REVIEW] update the iloc exp in dataframe.py

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This adds the capability for a String column to be titlized
> Java bindings for titlizing a String column [skip ci]

- CHANGELOG.md
- cpp/src/io/functions.cpp
> [REVIEW] Add CUDF_FUNC_RANGE to top-level cuIO function APIs

- CHANGELOG.md
- python/cudf/cudf/_lib/partitioning.pyx
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_sorting.py
During Internal profiling, we noticed that `unique_count` is a very expensive call compared to other operations in `scatter_by_map`.
Instead of removing that code entirely, side-stepping that part of code and only performing that operation if a `debug` flag is set as suggested by @rjzamora for debugging purposes.
cc: @jrhemstad @kkraus14
> [REVIEW] [PERF] Side step `unique_count` calculation in `scatter_by_map`

- CHANGELOG.md
- cpp/include/cudf/detail/utilities/cuda.cuh
> [REVIEW] Remove unused single_lane_block_popc_reduce

- CHANGELOG.md
- python/cudf/cudf/core/column_accessor.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
This PR attempts to improve the performance of `cudf.concat`. It may also improve performance of other operations.
> [REVIEW] Performance improvements relating to `concat`

- CHANGELOG.md
- java/buildscripts/build-info
- java/pom.xml
to be able to trace the source code that goes along with a particular jar we are adding in a version file that contains the name of the user that built it, the version from the pom file, the git hash, the branch it was built from , the date and the git url.
An Example output:
$ cat ./java/target/extra-resources/cudf-java-version-info.properties
version=0.14-SNAPSHOT
user=tgraves
revision=2f860bb8a59999962c74c41b11111
branch=javaversioninfo
date=2020-04-09T22:05:23Z
url=git@github.com:tgravescs/cudf.git
> [REVIEW] Add in the build information when building the java jar file [skip ci]

- python/cudf/cudf/__init__.py
- python/cudf/cudf/utils/gpu_utils.py
This is a temporary fix to skip setup validation when Dask workers are created.
Sample script used for testing:
```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import rmm
import time
import cudf
if __name__ == "__main__":  
cluster = LocalCUDACluster()
client = Client(cluster)
print(client)
time.sleep(120)
print("initialize call")
print("success")
```
```bash
Every 0.5s: nvidia-smi                                            Thu Apr  9 13:50:38 2020
Thu Apr  9 13:50:38 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id …
```
> [REVIEW] Temporary fix to skip validation on Dask related runs

- python/cudf/cudf/core/series.py
> [REVIEW] Add docs and clarify limitations of `applymap`

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_setitem.py
Test case has been added to check the inplace scenario.
close #4891
> [REVIEW] Fix series inplace handling

- CHANGELOG.md
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/multiindex.py
Only code changes and no test case.
> [REVIEW] Fix to `reset_index` inplace in MultiIndex and other places
