- pygdf/_gdf.py
- pygdf/column.py
- pygdf/dataframe.py
- pygdf/series.py
- pygdf/tests/test_stats.py
Exposed libgdf quantile functionality in `dataframe.py` and `series.py`. Main difference from pandas, if calculating multiple quantiles in `dataframe.py` it returns a dataframe with 2 columns: the requested quantiles and the calculated values. Pandas returns the quantiles as indices. Could add that functionality depending on review feedback.
> [REVIEW] Quantile bindings

- pygdf/_gdf.py
- pygdf/applyutils.py
- pygdf/buffer.py
- pygdf/column.py
- pygdf/columnops.py
- pygdf/cudautils.py
- pygdf/dataframe.py
- pygdf/gpu_ipc_broker.py
- pygdf/gpuarrow.py
- pygdf/groupby.py
- pygdf/index.py
- pygdf/libgdf_groupby.py
- pygdf/numerical.py
- pygdf/queryutils.py
- pygdf/tests/conftest.py
- pygdf/tests/test_dataframe.py
- pygdf/tests/test_gpu_arrow_parser.py
- pygdf/tests/test_pickling.py
- pygdf/tests/test_serialize.py
- pygdf/tests/test_sparse_df.py
- pygdf/utils.py
Modifications to use the RMM Memory Manager in pygdf. This depends on the sister PR for libgdf: https://github.com/gpuopenanalytics/libgdf/pull/159
RMM provides a Python API compatible with `cuda.device_array`, `cuda.to_device`, `cuda.device_array_like`, etc. from Numba. To use them, `from librmm_cffi import rmmlib as rmm` and just replace `cuda` in the above functions with `rmm`.
This is a work in progress.
> [REVIEW] Memory Manager

- README.md
- conda_environments/builddocs_py35.yml
- docs/source/index.rst
- readthedocs.yml
Created custom conda pkg with the libraries from the 396.44 driver to allow these CPU builds to succeed without having to force install a driver.
Docs off of this branch for inspection: https://cudf.readthedocs.io/en/fix-rtd-builds/index.html
> [REVIEW] RTD build update to fix missing libcuda.so error

- cudf/columnops.py
- cudf/numerical.py
- cudf/tests/test_dataframe.py
Needed to add typecasting to/from int8 for booleans to be properly handled since Arrow uses a bit array
> [REVIEW] Add handling pyarrow boolean arrays in input/out, add tests; Fixes #322

- libgdf/src/reductions.cu
Running `cuda-memcheck make pytest` turned up this error. Fix is trivial: only call `gdf_is_valid()` for indices less than the number of rows.
> [REVIEW] FIX out-of-bounds access error in reductions.cu

- cudf/categorical.py
- cudf/columnops.py
- cudf/dataframe.py
- cudf/libgdf_groupby.py
- cudf/tests/test_groupby.py
Currently after a groupby-agg, the dtype of categorical columns is changed to `int8`. This fix converts them back to categorical dtype.
Also adds tests for `sort` and `hash` based groupby for categoricals.
> [REVIEW] Preserve categorical dtype after groupby-agg (Fixes #288)

- cudf/tests/test_dataframe.py
Not bumping support to Arrow 0.11 quite yet, but fixes the only PyTest failure related to using PyArrow 0.11.
> [REVIEW] Fix PyArrow 0.11 handing of booleans

- libgdf/CMakeLists.txt
- libgdf/src/hashmap/managed_allocator.cuh
Fixes two minor issues I noticed today in trying to build libgdf using the cudf master branch (each issue in a separate file): #362 and #363 .
Note: I have only checked that this _builds_, I haven't run any tests, so caveat emptor.
> [REVIEW] Removes noexcept from managed_allocator & a CMakeLists fix for NVstrings

- .gitignore
cudf has a `.gitignore` file, but it's missing some common-sense entries which cause untracked files which should definitely be ignored, even as we build parts of it (e.g. libgdf). So, I've taken the liberty of making several common-sense additions:
* Patch-related extensions (`.diff`, `.rej`, `.orig`)
* Eclipse-IDE-related hidden files (`.cproject`, `.settings`)
* Static (in addition to dynamic) compiled libraries
* CMake-build-related folders for libgdf
> Some common-sense additions to .gitignore

- libgdf/src/tests/join/join-tests.cu
Fixes #375 
InputTooLarge previously initialized a very large column and then ran a join that would fail (as expected) before it ever touched the data because the size of the column was too large. This modified test just creates a very large but empty column, which is far faster.
Also some minor line-length cleanup (although not the whole file, just the parts I touched.)
> [REVIEW] Faster InputTooLarge Join test completes in ms rather than minutes.

- conda/environments/builddocs_py35.yml
- docs/requirement.txt
- docs/source/10min.rst
- docs/source/conf.py
- docs/source/index.rst
This PR adds a "10 Minutes to cuDF" section to the documentation, analogous to the ["10 Minutes to Pandas"](https://pandas.pydata.org/pandas-docs/stable/10min.html) documentation. Examples are drawn from the cuDF cheatsheet, existing documentation, and the Pandas documentation.
To support this new documentation, the PR adds `ipython` to the docs requirements file (for the ipython sphinx extensions) and updates `conf.py` and `index.rst` accordingly.
This documentation is currently in its own `rst` file, though it could naturally be moved to the Developer Documentation section.
> [REVIEW] Feature/10 min to cudf

- cpp/CMakeLists.txt
This fixed #413  and is pretty self-explanatory.
> [REVIEW] Fixed include file paths for the installation command in CMakeLists.txt

- python/cudf/bindings/cudf_cpp.pyx
- python/cudf/dataframe/columnops.py
- python/cudf/tests/test_dataframe.py
> [REVIEW] Properly cast string dtypes to programmatic dtypes when instantiating columns

- python/cudf/dataframe/column.py
- python/cudf/tests/test_multi.py
After merging the change to concatenation it triggers an illegal memory access when there are nulls / a validity mask. I've added more comprehensive tests that trigger this here to make triaging easier.
cc @dantegd @harrism
> [REVIEW] Concatenation illegal memory access with nulls

- cpp/include/cudf/io_types.h
- cpp/src/io/csv/csv_reader.cu
- cpp/tests/io/csv/csv_test.cu
- python/cudf/io/csv.py
- python/cudf/tests/test_csvreader.py
String columns can now be read in with quotation marks at the beginning and end of the string. The quotation marks can be kept or removed based on user preference.
Also, if the string within the quotation mark has a field delimiter, that delimiter is ignored and not does not terminate the field.
> [REVIEW] Adding support to read strings with delimiters

- CHANGELOG.md
- Dockerfile
- README.md
- cpp/CMakeLists.txt
fixes #431 
Additions:
Add pytest & steps to install libcudf cffi bindings to the cudf conda environment
Removed:
Unused libgdf HASH_JOIN CMake argument
'-j2' argument to build - not sure if 2 core restriction was added by accident, or whether there's a community preference to limit cores used during build
> [REVIEW] Improve Dockerfile: install libcudf cffi bindings, add pytest, remove unused cmake flag

- CHANGELOG.md
- cpp/include/cudf/functions.h
- cpp/python/tests/test_reductions.py
- cpp/python/tests/utils.py
- cpp/src/dataframe/type_dispatcher.hpp
- cpp/src/reductions/reductions.cu
- python/cudf/bindings/cudf_cpp.pxd
- python/cudf/bindings/reduce.pyx
- python/cudf/dataframe/numerical.py
This PR refactors reductions.cu to use `type_dispatcher`. It simplifies the public cuDF reductions API to just 5 functions: `gdf_sum`, `gdf_product`, `gdf_min`, `gdf_max`, and `gdf_sum_of_squares` (note *not* `gdf_sum_squared`, which has a different mathematical meaning!)
I also improved public API documentation for these functions.
This should fix #419, @beckernick 
I also expanded the libcudf test_reductions.py test to test sum_of_squares for integer types (handling overflow cases and ignoring the sum comparison when it overflows). So this should now also fix #421 and #443 (which I filed before I realized reductions unit tests were written as pytests).
Note that I had to duplicate `type_dispatcher` to `host_type_dispatcher` to avoid host/device errors (adding pragmas didn't help). I …
> Update reductions.cu to use type_dispatcher

- CHANGELOG.md
- README.md
fixes: https://github.com/rapidsai/cudf/issues/494
A slight error in the cuDF README results in an error leading one to believe the `pyarrow` is missing. However, the error is really just a result of running `pytest` in the wrong directory.
> [REVIEW] Update README to correct cffi pytest failure

- CHANGELOG.md
- python/cudf/tests/test_dataframe.py
- python/cudf/tests/utils.py
This adds an `assert_eq` function for testing and then shows off the use of that function while testing reductions and binary operators.  This serves as a proof of concept for testing generally as described in 
https://github.com/rapidsai/cudf/issues/520
I think that this PR can stand on its own, but we should wait for a decision in #520 .  My apologies for pushing something before discussion.
Closes #520
> [REVIEW] Add assert_eq and test reductions and binary operators

- .gitignore
- CHANGELOG.md
This is for convenience-of-build, only.
* Now ignoring `build/` just like `cpp/build` in case we don't build within the subdirectory
* Comment tweaks
> [REVIEW] Minor tweaks in .gitignore

- CHANGELOG.md
- print_env.sh
Closes https://github.com/rapidsai/cudf/issues/574
- Adds a check such that `git` information will only be displayed if the script is invoked within a git repository.
- Corrects what is displayed if `conda` and `pip` are not found
> [REVIEW] Update `print_env.sh` to better handle missing commands

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
Addresses the following test warnings:
```python
/home/jenkins/workspace/cudf-prb/python/cudf/dataframe/series.py:75: DeprecationWarning: 
pandas.core.common.is_categorical_dtype is deprecated. import from the public API: pandas.api.types.is_categorical_dtype instead
```
> [REVIEW] Fix deprecation warning for is_categorical_dtype

- CHANGELOG.md
- python/cudf/dataframe/series.py
- python/cudf/tests/test_binops.py
If GDF doesn't like true integer division, we should just call floor division for integers. Deal?
> [REVIEW] Add condition check for truediv of integers to prevent GDF error

- CHANGELOG.md
- cpp/CMakeLists.txt
This change fixes CMakeLists.txt to correctly handle CMAKE_BUILD_TYPE when it is specified on the command line, so that debug options get set correctly when `-DCMAKE_BUILD_TYPE=Debug` is specified on the cmake command line.
My approach is based on this Kitware blog post: https://blog.kitware.com/cmake-and-the-default-build-type/
Fixes #551
> [REVIEW] Correctly handle cmake build type

- CHANGELOG.md
- cpp/src/join/join_compute_api.h
- cpp/tests/join/join_tests.cu
Fixes: https://github.com/rapidsai/cudf/issues/369
- Updated the computation of the size of hash table allocation into its own function. Improved computation to better guard against overflow.
- Added test to check for possible overflow on hash table size computation.
- Removed MaxJoinTest as it is no longer necessary with the independent unit testing of the hash table size computation. 
- Updated `create_dummy_input` to only allocate a single element to avoid the time spent allocating the unnecessary memory. Instead, artificially sets the size of the `gdf_column`s. 
- Reduced the run time of `JOIN_TEST` by 15x (30s -> 2s)
> [REVIEW] Isolate computation of hash table size to function

- CHANGELOG.md
- python/cudf/dataframe/buffer.py
Fixes cudf issue [#560](https://github.com/rapidsai/cudf/issues/560).
> [REVIEW] Fix issue 560: numba>=0.42 requires one-to-one copying.

- CHANGELOG.md
- cpp/CMakeLists.txt
Fixes #641.
Problem:
- zlib header is usually in the env include path so that path was added first in the include directories list
- `make install` copies the libcudf headers (such as io_types.h) into the env include path
- subsequent builds will use the stale copies of the headers rather than the source headers as a result
This quick change moves the zlib include to after the libcudf includes. Alternatively, we could do more substantial reordering to ensure the libcudf sources are always first. Let me know what everyone prefers!
> [REVIEW] CMAKE: Fix env include path taking precedence over libcudf source headers

- CHANGELOG.md
- cpp/include/cudf/types.h
- cpp/src/join/joining.cu
- cpp/src/utilities/error_utils.cpp
Closes https://github.com/rapidsai/cudf/issues/395
I believe this is the only offending code for https://github.com/rapidsai/cudf/issues/395 
Added a check to ensure that two columns of `GDF_TIMESTAMP` must have the same resolution in order to be joined on.
> [REVIEW] Add check for GDF_TIMESTAMP resolution to Join

- CHANGELOG.md
- python/cudf/io/csv.py
- python/cudf/tests/test_csvreader.py
Simple change to allow users to use the default compression value for buffer input. 
Previously compression=None was required as the default value, 'infer' would lead to failure. 
This change addresses the issue and sets the compression type to None if the input is a buffer, instead of a file.
Modifications in the test demonstrate the purpose of the change.
> [REVIEW] CSV reader: automatically set compression type to None with buffer input

- CHANGELOG.md
- cpp/src/join/joining.cu
- python/cudf/tests/test_joining.py
> [REVIEW] Fix merge on empty inputs

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
- python/cudf/tests/test_joining.py
Fixes the specific issue presented in #626.
> [REVIEW] Fix uncaught string initialization when `object` dtype is in from_pandas and column creation

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
* Modified the internal logic to treat the header parameter effectively as additional row offset - total number of skipped rows is skiprows+header. This means that the header row is always the first one to be read.
* As part of the logic change, fixed a bug where having skiprows+nrows larger that the actual number of rows would cause a crash. 
* Added error checking to the uploadDataToDevice() call.
Fixes #656
> [REVIEW] Fix read_csv behavior with skiprows+header to match pandas version.

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- cpp/src/io/csv/type_conversion.cuh
- python/cudf/tests/test_csvreader.py
This fixes issue #700 wherein type inference fails when there's whitespace among the entries. This can make it into 0.5.
> [REVIEW] Fix type inference failures caused by whitespace

- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
Changes to read_csv back end:
* Skip data conversion when number of records is zero.
* Raise an error when there are no data rows and data type inference is used.
Fixes #707
> [REVIEW] Fix issue in CSV reader with empty dataframe

- CHANGELOG.md
- cpp/src/dataframe/cudf_table.cuh
The constructor of `gdf_table` flattens an array of `num_cols` `gdf_column`s from a array of structures (AoS) into a structure of arrays (SoA) in device memory. 
Previously, it did this by using `thrust::device_vector::push_back` to add each `gdf_column`s `data` and `valid` pointers to `thrust::device_vectors`. This was inefficient, as each push_back requires a memcopy and kernel invocation, however it was negligible if `num_cols` was small.
Working `gdf_transpose` (https://github.com/rapidsai/cudf/pull/356) where there is possibly millions of columns exposed how inefficient this can be. This PR improves the performance by instead using host-side `std::vector`s to perform the AoS->SoA conversion, and then copies the SoA in bulk to the device (instead of a single element at a time). 
fixes …
> [REVIEW] Improve performance of `gdf_table` constructor

- CHANGELOG.md
- cpp/CMakeLists.txt
CMake `execute_process` executes commands in parallel, so we had a race condition between creating directories and creating a symlink into the directories. Split the directory creation and symlinking into two separate processes that execute sequentially.
> [REVIEW] Fix CMake race condition for NVStrings

- .gitmodules
- CHANGELOG.md
After RMM merge, the git submodule points to the `rmm/master` branch which breaks testing for CI.
Example output seen:
```
CMake Error at thirdparty/rmm/CMakeLists.txt:60 (add_subdirectory):
add_subdirectory not given a binary directory but the given source
directory "/conda/envs/gdf/conda-bld/libcudf_1548310410120/work/cpp/tests"
is not a subdirectory of
"/conda/envs/gdf/conda-bld/libcudf_1548310410120/work/cpp/thirdparty/rmm".
When specifying an out-of-tree source a binary directory must be explicitly
specified.
CMake Error at CMakeLists.txt:245 (add_custom_target):
add_custom_target cannot create target "python_cffi" because another target
with the same name already exists.  The existing target is a custom target
created in source directory …
```
> [REVIEW] FIX Pin submodule to known working branches

- CHANGELOG.md
- cpp/CMakeLists.txt
Fixes #777 
As @kkraus14 pointed out this line hard codes the ABI setting to `0` or off, ignoring the new flag `CMAKE_CXX11_ABI` introduced in #668. Removal should fix the issue, but will run tests to check.
> [REVIEW] Remove hard coded ABI off setting

- CHANGELOG.md
- setup_pip.py
Updates the commit-ish of RMM submodule to tip of `branch-0.5` and updates rmm paths for pip package builds.
> BLD Update RMM paths

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/bitmask/bitmask_ops.cu
- cpp/src/bitmask/valid_ops.cu
- cpp/src/compaction/stream_compaction_ops.cu
- cpp/src/dataframe/cudf_table.cuh
- cpp/src/datetime/datetime_ops.cu
- cpp/src/filter/filter_ops.cu
- cpp/src/groupby/groupby_compute_api.h
- cpp/src/groupby/hash_groupby.cuh
- cpp/src/hash/hash_ops.cu
- cpp/src/hash/hashing.cu
- cpp/src/io/convert/csr/cudf_to_csr.cu
- cpp/src/quantiles/quantiles.h
- cpp/src/sqls/sqls_rtti_comp.h
- cpp/src/sqls/sqls_set_ops.h
- cpp/src/unary/unary_ops.cu
fixes https://github.com/rapidsai/cudf/issues/792
Previously, `rmm::exec_policy(stream)` returned a Thrust execution policy that would use RMM for temporary Thrust allocations in addition to running on the desired stream.
Due to a bug in `rmm::exec_policy`, the returned Thrust execution policy would be returned with a reference to a local variable that is not valid after the function returns. This would cause errors when using Thrust algorithms with the `rmm::exec_policy`. 
To fix this, `rmm::exec_policy` was updated to return a `std::unique_ptr` that points to the Thrust execution policy that uses RMM for temporary allocation. Furthermore, it no longer specifies that the execution policy should run on the specified stream, requiring the usage to be updated from:
``` …
```
> [REVIEW] Update `rmm::exec_policy` usage 

- .gitmodules
- CHANGELOG.md
- README.md
Needed to fork (cub and moderngpu) and update to tip of the branch to resolve situation where RMM `branch-0.5` was not being updated, leading to errors. Commits are not supported in `.gitmodules` so by forking the repos above we can create a branch that is at our desired commit.
This is to fix an issue where after merging #794 all builds fail because `branch-0.5` for the RMM submodule points to an old commit.
> [HOTFIX] Point git submodule to branches of forks instead of exact commits

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/index.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
- Correct leak by carefully assigning boolmask index to new df when
masked
- Correct issue with Series not actually using an index specified in its
constructor
- Add range initialization to `RangeIndex.__init__`
- Add range initialization to `Series.__init__`
- Fix issue with pyarrow serialization not recognizing binary string
- Add properties to RangeIndex:
- _values
- is_contiguous
- size
- to_gpu_array
> [REVIEW] Fix memory leak by preserving the boolean mask index

- CHANGELOG.md
- cpp/src/utilities/wrapper_types.hpp
`wrappers.hpp` was missing an include for `<type_traits>`.
This causes a failure to build on CentOS systems.
My guess is on Ubuntu systems that it was being included somewhere up the include chain, but not on CentOS.
> [REVIEW] Added missing type_traits include.

- .gitignore
- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/formatting.py
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_categorical.py
- python/cudf/tests/test_groupby.py
- python/cudf/tests/test_libgdf_groupby.py
This fixes #828 (also #739 and #740).
Add better indexing to Groupby objects (`['y']`, `.y`, and `[['y']]`). This also adds support for as_index=True when a single index and a single aggregation is specified, with results that perfectly match pandas. If multi-index is specified, the index columns will be returned as normal columns as `MultiIndex` is not yet supported. If multi-aggregation is specified, the prefix aggregation types are still appended to column names, until `MultiColumn` is supported.
- Change default to as_index=True to match pandas
- Change `cudf` as_index NotImplementedError to a warning, so I don't have to modify _every_ test.
- Remove the multi-aggregation column prefix when multi-aggregation is not used
- Implement __getitem__ and __getattr__
- Implement UnaryIndex - …
> [REVIEW] Add better indexing to groupby.

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
- Add `level` argument, making it or `by` optional, but not both
- If level=0, convert the DF index into a column, groupby it, and
convert it back to index.
- Add tests
> [REVIEW] Add DataFrame.groupby(level=0) functionality

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
Fixes #928 
* CSV reader now resets the byte_range_size to zero, if the size is larger than the input file. This prevents the byte_range from polluting the logic further down the line, and should not have unintended effects because that large byte range is functionally equivalent to zero.
* Added a test for the case where byte range is larger than the input file.
* Expanded one of the CSV tests to also check the dataframe shape.
> [REVIEW] CSV Reader: fix an issue where the last data row is missing when using byte_range

- CHANGELOG.md
- cpp/src/utilities/wrapper_types.hpp
- cpp/tests/types/types_test.cpp
The wrapper types were missing post and prefix increment/decrement operators. 
This PR adds them along with associated unit tests.
> [REVIEW] Added increment and decrement operators for the wrapper types

- CHANGELOG.md
- cpp/src/bitmask/valid_ops.cu
- cpp/src/utilities/cudf_utils.h
- cpp/tests/bitmask/valid_ops_test.cu
Previously, `count_nonzero_mask` would return `GDF_DATASET_EMPTY` if the passed in bitmask was null.
Since the bitmask in a column is optional, `count_nonzero_mask` should instead simply return `num_rows` when the bitmask is null.
Just for fun, also added a utility function `set_null_count` to update the null count for a `gdf_column`.
> [REVIEW] Fixed count_nonzero_mask for null masks

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
Fixes #946 
* Fixed the logic when removing extra record starts after uploading the data to the GPU; byte_range is excluded from this, as it does not actually affect the additional number of rows. The byte_range values are used such that only required rows are loaded in all cases (no need to remove extra rows). Now, only the OEF record start is excluded from the record count.
* Fixed the byte_range test, which did not check the dataframe content correctly.
* Updated the error message that's returned when the byte_range offset is larger than the input file.
> [REVIEW] CSV Reader: fix issue with missing rows when using byte_range

- CHANGELOG.md
- cpp/python/tests/test_hashing.py
- cpp/python/tests/test_sorting.py
- docs/Makefile
- docs/source/api.rst
- docs/source/conf.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/io/feather.py
- python/cudf/io/hdf.py
- python/cudf/io/json.py
- python/cudf/io/orc.py
- python/cudf/io/parquet.py
- python/cudf/utils/ioutils.py
1. Fixing broken Series API docs
2. Adding Parquet, ORC, JSON, Feather, HDF file reader/writers to API docs
3. Moving the above io module docstrings to cudf/python/utils/ioutils.py:
These docstrings are currently repeated in cudf/python/dataframe/dataframe.py and cudf/io/${type}.py, moving to ioutils eliminates the duplicated content
4. Fixing flake8 issues with a couple of cpp/python tests
5. Fixing docstring formatting for DataFrame/Series methods
> [REVIEW] API doc updates

- CHANGELOG.md
- python/cudf/io/csv.py
- python/cudf/tests/test_csvreader.py
Fixes #922 
* Add the index_col parameter to read_csv() and read_csv_strings().
* Supports ints and strings to specify the index column.
* Add the test different index_col types.
> [REVIEW] CSV Reader: Add index_col parameter to specify the column name or index to be used as row labels

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/series.py
- python/cudf/multi.py
- python/cudf/tests/test_dataframe.py
This PR improves the naive approach of concatenation for Series and Dataframes.  Code is now in one files (multi.py) and handle concatenation of `Series` and `Dataframes` together.
cc @mrocklin @kkraus14
> [REVIEW] Better Concat

- CHANGELOG.md
- cpp/src/utilities/trie.cuh
@mike-wendt reported an error in building libcudf on CentOS7 + CUDA10.
I triaged the issue, and it appears to be some failure in the combination of CUDA10 Thrust + CentOS7 libc++. 
I isolated to a more minimal reproducer:
```
// compile with nvcc --std=c++11 ./test.cu
#include <thrust/device_vector.h>
#include <thrust/host_vector.h>
struct foo {
//foo() = default; // This code will fail to compile on CentOS7 + CUDA10 without a default ctor
foo(int n) : value{n} { }
int value;
};
thrust::host_vector<foo> return_vector(){
thrust::host_vector<foo> h_vec;
h_vec.push_back(foo{0});
return h_vec;
}
int main(void){
thrust::device_vector<foo> d_vec = return_vector();
}
```
It appears that adding a default constructor for `SerialTrieNode` solved the problem.
> [REVIEW] Added default constructor for SerialTrieNode to solve Thrust bug on CentOS7

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
Fixes #1051 
* Exclude the last character in the column name when the terminator follows it, when using \r\n as the line terminating sequence.
* Modify a test to check the column names when \r\n is used as line terminator.
> [REVIEW] CSV Reader: Fix an issue where a column name includes the return character

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- python/cudf/io/csv.py
Issue #1049 
* Free memory buffers immediately after last use to lower the peak memory consumption with NVString columns;
* Fix a heap corruption issue caused by incorrect copy size when header=None and names=None;
* Remove an outdated line of code in read_csv_strings(), that causes issues when using this function with names=None;
> [REVIEW] CSV Reader: Minor fixes and memory usage improvements

- CHANGELOG.md
- python/cudf/dataframe/datetime.py
- python/cudf/tests/test_datetime.py
PR adds sorting on datetime columns.  This is necessary for building indexes for dask:
https://github.com/rapidsai/dask-cudf/issues/129
cc @kkraus14
> [REVIEW] Sort Datetime

- CHANGELOG.md
- cpp/tests/table/table_tests.cu
- python/cudf/dataframe/categorical.py
- python/cudf/dataframe/column.py
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_categorical.py
This PR introduces the following changes:
* `set_categories()` now returns a `Series` (the appropriate return type since it is part of the public API).
*  The old `set_categories()` is renamed to `_set_categories()` which can be used internally when a `Column` is needed.
> [REVIEW] Return a Series (not a Column) in Series.cat.set_categories

- CHANGELOG.md
- cpp/src/io/comp/uncomp.cpp
- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
Fixes #1083 
* CSV Reader now includes the last line even when not terminated;
* Modified many tests to exclude the last terminator;
* Fix the output buffer size with bzip2 compression, to exclude the padding that is added when the output size is unknown;
* Remove the extra byte in chunk allocation, the additional byte is not used anymore;
> [REVIEW] CSV Reader: The last data row does not need to be line terminated

- CHANGELOG.md
- python/cudf/__init__.py
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/numerical.py
- python/cudf/ops.py
- python/cudf/tests/test_ops.py
Fixes #1055. Sets a simple template for improving all unaryops and extending them from libgdf. Cython has to be this simple.
> [REVIEW] cudf.sqrt

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
Quick fix to `_mimic_inplace()` that ensures that the `null_count` is properly set after an inplace operation.
> [REVIEW] Copy null_count from result in mimic_inplace()

- .gitmodules
Auto-merge triggered by push to `branch-0.6` that creates a PR to keep `branch-0.7` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.6 to branch-0.7 [skip ci]

- CHANGELOG.md
- python/cudf/tests/test_categorical.py
These tests are using the `np.all` and `np.any` ufuncs on a `cudf.Series`. It isn't clear why this ever worked. The fix is to cast the `cudf.Series` `to_array` so that the ufuncs work explicitly. Implicit ufunc conversions shouldn't work on `cudf` objects because they can be extremely expensive.
> [REVIEW] Fix two categorical tests that are failing due to weird implicit ndarray type conversion

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
This PR fixes the issue #1172 . There is very minor change in `dataframe._sanitize_columns()` in order to handle this.
> [REVIEW]Fix dtypes issue #1172 while adding a col to empty object dataframe

- CHANGELOG.md
- cpp/src/copying/gather.cu
Add missing Thrust exec policy on `thrust::copy` in gather.cu.
Fixes #1241
> Add explicit Thrust exec policy to fix NVCATEGORY_TEST segfault

- CHANGELOG.md
- ci/cpu/prebuild.sh
Sometimes cudf packages weren't being labeled as `main`. This was because cudf was build 4 times and upload each time, but `LABEL_MAIN` is true for only 2 of those builds. So often the main cudf would be overwritten.
This PR fixes that by only building cudf twice.
> [REVIEW] Prevent cudf upload overwrites

- CHANGELOG.md
- cpp/src/utilities/trie.cuh
Issue #716 
* Each array of child nodes in a trie is sorted in the ascending order. Once the current node is larger than the key character we are looking for, we can terminate the search and return false.
* This PR modifies serializedTrieContains() to make use of this property to improve trie performance.
* The performance improvement should be the largest for number fields, where the search will terminate after a single comparison.
> [REVIEW] Improve performance of the CUDA trie used in the CSV reader

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- cpp/src/utilities/trie.cuh
- python/cudf/tests/test_csvreader.py
Fixes #1117 
* Expand the data type detection to cover scientific notation of floating-point numbers.
* Add a test to cover different cases of numbers in this format.
> [REVIEW] CSV Reader: Fix data type detection for floating-point numbers in scientific notation

- CHANGELOG.md
- cpp/src/hash/hashing.cu
We were getting a value returned by a void function which is undefined in CentOS but somehow defined properly in Ubuntu...
> [HOTFIX] Fix hash_partition exceptions on CentOS

- cpp/CMakeLists.txt
- cpp/include/cudf/io_types.h
- cpp/src/io/csv/csv_reader.cu
- cpp/src/io/utilities/parsing_utils.cu
- cpp/src/io/utilities/parsing_utils.cuh
Set up utility functions for file parsing:
* Replace the countRecords kernel with thrust library calls;
* Make the launch_countRecords into a generic utility function;
* Make the storerecordStart kernel and launch_storerecordStart generic;
* move all of the above into a separate file, making the code reusable;
Other:
* Use Async CUDA calls for memory copies and sets;
* fix chunk allocation for small files - no longer allocates full chunk size when the file is smaller than chunk size;
* Refactor the code that set the record starts into a separate function;
* Rename the CSV specific typedefs to be more generic. usable in the utility functions;
> [REVIEW] Refactor some of the CSV Reader kernels into generic utility functions

- CHANGELOG.md
- cpp/include/cudf/types.h
- cpp/src/binary/jit/code/operation.cpp
- cpp/src/binary/jit/util/type.cpp
- cpp/tests/binary/integration/binary-operation-integration-test.cpp
- cpp/tests/binary/util/operation.h
- python/cudf/bindings/binops.pyx
- python/cudf/bindings/cudf_cpp.pxd
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/index.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_binops.py
- python/cudf/tests/test_dataframe.py
Adds JIT compiled bitwise binary ops
Resolves #49
> [REVIEW] Bitwise binary ops AND, OR, XOR (&, |, ^)

- CHANGELOG.md
- cpp/src/comms/ipc/ipc.cu
Issue #1307 pointed out that on some platforms the compiler warns (therefore error) that a `catch` block in `ipc.cu` is catching a polymorphic exception by value. This PR changes it to a const reference.
> Fix catch polymorphic exception by reference in ipc.cu

- CHANGELOG.md
- cpp/src/utilities/device_atomics.cuh
- cpp/tests/utilities_tests/device_atomics_test.cu
Implement  `atomicAnd`, `atomicOr`, `atomicXor` overload for all signed/unsigned integer types. 
The supported types are:
singed/unsigned integer 8/16/32/64 bits
Cuda natively supports 32/64 bitwise logical operations.
Close #1357
Implement:
> [REVIEW] Add: atomicAnd/Or/Xor 

- CHANGELOG.md
- python/cudf/dataframe/series.py
- Update Series.quantile to use linear interpolation by default, to [match pandas](https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/core/series.py#L2004)
Since `describe` does not expose the quantile interpolation keyword argument, we should be mimicking pandas and using linear interpolation by default.
> [REVIEW] Change series quantile default to linear interpolation

- CHANGELOG.md
- cpp/CMakeLists.txt
- python/cudf/_gdf.py
- python/cudf/bindings/cudf_cpp.pxd
- python/cudf/bindings/nvtx.pyx
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/datetime.py
- python/cudf/dataframe/numerical.py
- python/cudf/dataframe/series.py
- python/cudf/groupby/groupby.py
- python/cudf/io/csv.py
This PR adds Cython bindings for the `gdf_nvtx_range_push` and `gdf_nvtx_range_pop` functions, while removing the old CFFI bindings.
It also fixes a bug in `CMakeLists.txt` relating to the `USE_NVTX` option.
> [REVIEW] Add Cython bindings for NVTX functions

- CHANGELOG.md
- CONTRIBUTING.md
- Updates the process of cloning cudf to use `CUDF_HOME` the environment variable. Currently, this step errors as written.
This PR closes #1290.
> [REVIEW] Update CONTRIBUTING to use the environment variable CUDF_HOME

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
This PR adds the pop method to the DataFrame object, analogous to pandas's [pop method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pop.html).
- Adds a DataFrame level `pop` method and associated unit tests
This closes #1410
> [REVIEW] Add DataFrame.pop()

- CHANGELOG.md
- cpp/include/cudf/functions.h
- cpp/src/bitmask/valid_ops.cu
... and updated the doxygen for `gdf_count_nonzero_mask()` in `cudf/functions.h`.
Fixes #1370.
> [REVIEW] Set `*count` to 0 when there are 0 rows to count valid bits for

- CHANGELOG.md
- ci/gpu/build.sh
- conda/recipes/cudf/meta.yaml
- conda/recipes/libcudf/meta.yaml
- conda/recipes/libcudf_cffi/meta.yaml
Fixes #1414.
Bumping NVStrings to 0.7 to match development version of cuDF.
> [REVIEW] Bump NVStrings to 0.7

- CHANGELOG.md
- cpp/CMakeLists.txt
The `-lineinfo` option to `nvcc` is useful to allow CUDA profilers and `cuda-memcheck` to display code or line numbers, even with a release build. 
This PR adds a cmake variable (`CMAKE_CUDA_LINEINFO`), which is `OFF` by default, which can be specified at cmake configuration time to enable passing `-lineinfo` to `nvcc` when compiling CUDA code.
> [REVIEW] Add a CMake option to compile CUDA code with -lineinfo

- CHANGELOG.md
- ci/gpu/build.sh
- python/.coveragerc
Currently outputs test percentage coverage of the `cudf` module in the output of gpuCI.
Will be adding it to the status update for gpuCI as well.
Also removed unnecessary install from the build script since the package is installed in our base image.
> [REVIEW] Add Python coverage test to gpu build

- CHANGELOG.md
- python/cudf/tests/test_dask.py
Fixes https://github.com/rapidsai/cudf/issues/1488
This is a follow up to PR ( https://github.com/rapidsai/cudf/pull/1363 ). Adds a minimum version requirement to Dask for this test to ensure upstream PR ( https://github.com/dask/dask/pull/4359 ) is included. If that minimum version is not met, the test is skipped. A reason is added to explain why this test is skipped in that case.
cc @harrism @kkraus14
> [REVIEW] Require Dask 1.1.0+ for testing `is_dataframe_like`

- CHANGELOG.md
- cpp/src/io/csv/csv_writer.cu
This is to fix the call an NVStrings method the causes csv-writer compile failure.
> [REVIEW] Fix csv-writer call to updated NVStrings method

- CHANGELOG.md
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/string.py
- python/cudf/tests/test_replace.py
This pr fixes the bug `fillna` fails for cudf string series [issue](https://github.com/rapidsai/cudf/issues/1448)
> [REVIEW] added nvstrings fill_na function

- CHANGELOG.md
- cpp/src/hash/hashing.cu
- cpp/src/table/device_table.cuh
Small PR broken off from https://github.com/rapidsai/cudf/pull/1478 since it was hiding a bug.
> [REVIEW] Added an overload for `hash_row` that doesn't use initial hash values

- CHANGELOG.md
- python/cudf/comm/gpuarrow.py
As these closures don't seem to require any state from the method they are in (or from the class itself for that matter), refactor them out as independent functions intended for internal use.
> [REVIEW] Refactor closures as private functions in gpuarrow

- CHANGELOG.md
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
Pandas does this. It may be tricky particularly because pandas doesn't require they be named. Cudf doesn't work great with unnamed columns atm.
This fixes #1096
> [REVIEW] Add arbitrary list of Series as a valid argument to Groupby function

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
Fix incorrect starting row position when skiprows!=0, which could lead to last <skiprow> rows being uninitialized.
Resolves #1640
> [REVIEW] Fix potentially uninitialized tail rows when skiprows!=0

- CHANGELOG.md
- python/cudf/bindings/cudf_cpp.pxd
- python/cudf/bindings/cudf_cpp.pyx
- python/cudf/dataframe/column.py
This is needed for interoperability with other libraries such as xgboost.
@mt-jones
> [REVIEW] Add a way to get a pointer to the underlying gdf_column of a Column

- CHANGELOG.md
- python/cudf/bindings/groupby.pyx
- python/cudf/tests/test_groupby.py
Fix to ensure that passing `as_index=False` works properly with MultiIndex groupby
> [REVIEW] Fix groupby as_index behaviour with MultiIndex

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
Fixes https://github.com/rapidsai/dask-cudf/issues/234
Fixes https://github.com/rapidsai/cudf/issues/1064
This PR automatically drops unsupported dtypes (object) from numeric groupby aggregations. This is inline with Pandas behavior in this case.
> [REVIEW] Drop object columns automatically when running numeric groupby aggregations.

- CHANGELOG.md
- python/cudf/dataframe/multiindex.py
- python/cudf/groupby/groupby.py
An O(N^2) replacement operation was easily replicated with a cpp level replace. Thanks @shwina for your help!
Fixes https://github.com/rapidsai/cudf/issues/1685
> [REVIEW] Correct performance regression with 0.7 groupby.

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/utils.py
Fixes a bug in dask-cudf with read_csv and datetime64[ms] columns
> [REVIEW] Handle datetime64[ms] in `select_dtypes`

- ci/release/update-version.sh
This just removes one of the paths that no longer exists.
This PR will not trigger a release. But is required for any future releases.
> [REL] Fix update-version since cffi is gone [skip ci]

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_query.py
Fixes issues caused by calling query on empty dataframe by adding a check on the `query` function . 
Fixes https://github.com/rapidsai/cudf/issues/1646
Fixes https://github.com/rapidsai/dask-cudf/issues/199
> [REVIEW] Fix query function on empty dataframe

- CHANGELOG.md
- python/cudf/bindings/groupby.pyx
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
Fixes #1509 
This functionality can only be supported by `as_index=True`, which was not possible with the original implementation of Groupby. I enabled a special case when a single column is grouped as its own index.
> [REVIEW] Fix issue by handling same-column-as-index rules for the first time.

- CHANGELOG.md
- cpp/src/utilities/device_atomics.cuh
- cpp/src/utilities/device_operators.cuh
- cpp/tests/device_atomics/device_atomics_test.cu
Supersedes https://github.com/rapidsai/cudf/pull/1691
Because https://github.com/rapidsai/cudf/pull/1691 was based off of branch-0.8, I had to cherry-pick it's commits onto a new branch based off of release-0.7.2.
In order to hotfix the abysmal performance of groupby when summing int64, provides an overload for atomicAdd `int64` that simply casts to `uint64`. Because 2s complement is used, this is safe. 
> Compared to other systems for representing signed numbers (e.g., ones' complement), two's complement has the advantage that the fundamental arithmetic operations of addition, subtraction, and multiplication are identical to those for unsigned binary numbers (as long as the inputs are represented in the same number of bits - as the output, and any overflow beyond those bits is discarded …
> [HOTFIX] Overload for atomicAdd on int64

- CHANGELOG.md
- python/cudf/bindings/groupby.pyx
- python/cudf/tests/test_groupby.py
- python/cudf/tests/test_libgdf_groupby.py
- python/cudf/tests/test_string.py
This PR extends #1730 and fixes pytests so that they don't compare dtypes when doing groupby-count.
> [HOTFIX] Fix dtype for groupby-count

- CHANGELOG.md
- python/cudf/dataframe/numerical.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
- python/cudf/utils/cudautils.py
While we will eventually implement `round` in libcudf (#1270), in the meantime some users want to be able to round numeric Series. This PR implements `round` functionality via Numba using floor division and the modulo operator to determine whether to round up or down.
@robocopnixon, you can use this PR.
> [REVIEW] Series.round via numba kernel

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
Long strings of NULLs can cause out-of bounds writes in the row position array, overwriting data values in shared mem.
Also fix decoding of boolean runs longer than 128 (ORC byte RLE can go up to 130).
> [REVIEW] ORC Reader: fix long strings of NULLs corrupting decoded values

- CHANGELOG.md
- python/cudf/tests/test_dataframe.py
- python/cudf/tests/test_sparse_df.py
* Reduce the size of the dataframe in `test_dataframe_transpose`
* Simplify `test_reading_arrow_sparse_data` to just compare the dataframe obtained from the `GpuArrowReader` with the original DF (I don't think that this is circular logic - as all we really want to test is whether the reader can construct the DF correctly given the schema and gpu_data).
> [REVIEW] Speed up unit tests

- CHANGELOG.md
- python/cudf/reshape/general.py
- Adds a `col_level` keyword argument to `melt`, that defaults to `None` and is required to be None. Used the tuple in case we eventually implement multi-level melt in stages.
This closes #1721 and will also close rapidsai/dask-cudf#209
> [REVIEW] Add col_level keyword argument to melt

- CHANGELOG.md
- cpp/src/hash/hashing.cu
- cpp/src/table/device_table.cuh
- cpp/tests/device_table/device_table_tests.cu
- cpp/tests/hashing/hash_partition_test.cu
- cpp/tests/utilities/column_wrapper.cuh
This was split off from https://github.com/rapidsai/cudf/pull/1478
In order to provide more efficient row-level operators for `device_table` when the columns are non-nullable, this PR adds a `nullable` boolean template parameter to the `rows_equal` and `hash_row` functions.
Because these flags are template arguments, their value is known at compile time. As such, the compiler will optimize away the code path that checks for null values when the flag equals `false`. This is a convenient way to provide optimal performance row operators without the need for code duplication in creating two sets of operators. 
This PR also adds a `row_equality_comparator` functor for use where a functor is necessary to compare equality of two rows. 
Finally, updates `copy_row` to optionally update the target …
> [REVIEW] Add nullability template argument to device_table row operators

- CHANGELOG.md
- python/cudf/dataframe/column.py
- python/cudf/dataframe/columnops.py
- python/cudf/dataframe/string.py
- python/cudf/tests/test_multi.py
Concatenating nulls to a column currently fails because a column of nulls in cuDF can have any dtype. This PR enables the concatenation of nulls of any dtype to a column.
Fixes #1723
> [REVIEW] Allow concatenating columns with null columns

- CHANGELOG.md
- python/cudf/bindings/json.pyx
- python/cudf/tests/test_json.py
Fixes #1769 
* Add support for BytesIO and StringIO input to read_json(), based on the CSV reader implementation;
* Expand the json_input test fixture to generate input of the newly added types;
> [REVIEW] JSON reader: add support for BytesIO and StringIO input

- CHANGELOG.md
- cpp/src/io/csv/csv_reader.cu
- python/cudf/tests/test_csvreader.py
Fixes #1598 
* Default the column type to string when no data is available for inference, instead of throwing;
* Modified the Python test to match the new POR;
> [REVIEW] CSV Reader: default the column type to string for empty dataframes

- CHANGELOG.md
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
```
import cudf
df = cudf.DataFrame()
df['a'] = [0,1,0,1,2]
df['b'] = [11,2,15,12,2]
df['c'] = [11,2,15,12,2]
df.groupby('a',as_index=True).agg({'b':['min','max'],'c':'max'}).to_pandas()
```
Done.
```
df = cudf.DataFrame()
df['a'] = [0,1,0,1,2]
df['b'] = [11,2,15,12,2]
df['c'] = [11,2,15,12,2]
df.groupby('a',as_index=True).agg({'b':'min','c':['max','min']}).to_pandas()
```
Done
```
import cudf
df = cudf.DataFrame()
df['a'] = [0,1,0,1,2]
df['b'] = [11,2,15,12,2]
df.groupby('a',as_index=True).agg({'b':['min','max']}).to_pandas()
```
Done
Fixes #1814
> [REVIEW] Fix issues with multiple aggregation and groupby

- CHANGELOG.md
- cpp/src/io/json/json_reader.cu
- cpp/src/io/json/json_reader.hpp
- python/cudf/tests/test_json.py
Issue #1519
* Modify data type detection in JSON reader to include boolean values/columns;
* Include true and false tries when parsing integer values, to set the field values to 0/1;
* Add Python tests for boolean columns;
> [REVIEW] JSON Reader: add suport for bool8 columns

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_binops.py
This PR fixes #1736 by inserting new NaN columns with the length of the largest operand.
However, this does **not** work when operands share columns with different length. 
E.g. `cudf.DataFrame({'x': [1, 2]}) + cudf.DataFrame({'x': [1, 2, 3]}` will raise `NotImplementedError`.
To support this case, we need to insert NaN rows until the length of the operands matches -- similar to how [`.reindex()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex) works in Pandas. Thus, we might consider implementing #1779 before handling this case.
I have added testing of both cases.
Finally, there is still an issue with NaN and pow(). The problem is the following cases where the result is not NaN:
```python
pow(1, NaN) == 1
pow(NaN, 0) == 1 …
```
> Operators on different sized dataframes

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/tests/test_dataframe.py
- This PR updates `_apply_support_method` to pass keyword arguments to the grabbed method.
- There are several ways to accomplish this, but I think the simplest is to simply remove `*args` in favor of an explicit method argument (since this private method is designed to apply a single method), and unpack the keyword arguments twice.
- This PR also updates the DataFrame statistical methods to leverage `**kwargs`, allowing them to pass through arguments to the Series methods. I think this is a good choice, as it simplifies the code by only explicitly enumerating keyword arguments used in DataFrame-specific logic (such as `numeric_only`, if we decide to implement this down the road) and will help alleviate dask-related API issues that pop up from missing keyword …
> [REVIEW] Allow DataFrame support methods to pass arguments to the methods

- CHANGELOG.md
- cpp/tests/column/column_test.cu
- cpp/tests/transpose/transpose_test.cu
- cpp/tests/unary/unary_ops_test.cu
- cpp/tests/utilities/column_wrapper.cuh
- cpp/tests/utilities/cudf_test_utils.cu
- cpp/tests/utilities/cudf_test_utils.cuh
New type-erased version of the utility `gdf_equal_columns`. Uses type dispatcher on the type of the first column to call the typed version.
Closes #1844
> [REVIEW] type-erased gdf_equal_columns, and fix for gdf_equal_columns logic

- CHANGELOG.md
- python/cudf/dataframe/column.py
- python/cudf/dataframe/columnops.py
`columnops.column_empty_like` and `columnops.column_empty` currently return a generic `Column` object. This PR improves it to return the appropriately typed column (numerical, string, datetime or categorical). For example:
```
In [1]: cudf.dataframe.columnops.column_empty(4, 'datetime64[ms]', False)                                                                                                               
Out[1]: <cudf.dataframe.datetime.DatetimeColumn at 0x7f6bd1b7fb38>
```
> Utilities for making *typed* empty columns

- CHANGELOG.md
- python/cudf/dataframe/string.py
- python/cudf/tests/test_string.py
> [REVIEW] Fixed #1375 by moving the nvstring check into the wrapper function

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/numerical.py
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
- This PR adds the `all` and `any` methods to Series and DataFrames (and the `any` method to NumericalColumns), analogous to pandas.
Note that the behavior of `pandas.all([None])` does not match Python's built in `all`'s behavior. This PR matches pandas. Additionally, pandas does not appear to restrict the values of `bool_only`. For example:
```python
import pandas as pd
pdf = pd.DataFrame([[1, True],
[2, False],
[3, False]])
print(pdf.all(bool_only='example'))
print(pdf.all())
1    False
dtype: bool
0     True
1    False
dtype: bool
```
> [REVIEW] Series and Dataframe methods for all and any

- CHANGELOG.md
- python/cudf/dataframe/numerical.py
- python/cudf/tests/test_dataframe.py
If an integer column has minus and 0 value, the any, all result got wrong
e.g.  [-2, -1, 0, 3, 5]  the expected result is True for `any`, False for `all`
However, the old implementation do 'min' or 'max' of integer column, then cast it to boolean, the result got wrong.
This PR corrects it using `dtype=np.bool_` reduction option for `any` and `all`.
Related PR #1863 Issue #1874
> [REVIEW] Bug fix: add dtype for any, all

- CHANGELOG.md
- python/cudf/dataframe/multiindex.py
- python/cudf/indexing.py
- python/cudf/tests/test_multiindex.py
This fixes https://github.com/rapidsai/dask-cudf/issues/125, which depended on MultiIndex supporting `iloc` indexing. This PR adds iloc indexing to dataframes with multiindexes.
> [REVIEW] Add iloc and tests for MultiIndex dataframes

- CHANGELOG.md
- python/cudf/dataframe/series.py
- python/cudf/tests/test_dataframe.py
Summary of Changes
- This PR adds a dtype check to the all/any methods to ensure they can currently only be used on NumericalColumns or dataframes of NumericalColumns
- If called on a non-NumericalColumn based Series or a DataFrame containing non-NumericalColumns, these methods will now raise a NotImplementedError
- Adds an xfailing test for future implementation that includes object columns
In the future, we can implement this for object and datetime columns.
> [REVIEW] Add column dtype checking for the all/any methods

- CHANGELOG.md
- python/cudf/tests/test_onehot.py
- python/cudf/utils/utils.py
Unlike cudf, pandas doesn't directly expose a one hot encoding method in its dataframes. One hot encoding is done though a global utility [`pandas.get_dummies`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html). More context can be found in issue #1063 
This PR implements a cudf approximation of that, to the extent that's currently possible. More specifically:
```python
def get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, 
sparse=False, drop_first=False, dtype=None)
def get_dummies(df, prefix, prefix_sep='_', cats={}, columns=None, dtype='float64')
```
- `data` maps directly to `df`
- `prefix`  and `prefix_sep` share the same functionality
- `dummy_na` is not supported. Instead, this implementation follows the default pandas …
> [REVIEW] Add a pandas-esque get_dummies wrapper around cudf.DataFrame.one_hot_encoding

- CHANGELOG.md
- cpp/src/bitmask/bit_mask.cuh
- cpp/src/copying/slice.cu
- cpp/src/rolling/rolling.cu
- cpp/src/utilities/bit_util.cuh
- cpp/tests/binary/integration/binary-operation-operands-null-test.cpp
- cpp/tests/column/column_test.cu
- cpp/tests/utilities/column_wrapper.cuh
- cpp/tests/utilities/cudf_test_utils.cuh
- cpp/tests/utilities/valid_vectors.cpp
Rename `namespace gdf` to `namespace cudf` to bring it up to date.
> [REVIEW] Rename namespace gdf to namespace cudf

- CHANGELOG.md
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
This fixes https://github.com/rapidsai/cudf/issues/1920 and https://github.com/rapidsai/dask-cudf/issues/93
> [REVIEW] Use prefix removal instead of multiindex for when two aggs are called on a SeriesGroupby

- CHANGELOG.md
- cpp/src/utilities/wrapper_types.hpp
- cpp/tests/types/types_test.cpp
Constructing a `cudf::bool8` with any value should be the same as first casting that value to `bool` and then constructing the `bool8`.
This PR adds a specialization for `wrapper` constructor for `GDF_BOOL8` that ensures the above is true. 
Also removed an errant `HOST_DEVICE_CONSTANT` definition that was not used.
> Add specialization for bool8 constructor to cast argument to bool

- CHANGELOG.md
- cpp/docs/TRANSITIONGUIDE.md
- cpp/include/cudf/groupby.hpp
- cpp/src/groupby/new_groupby.cu
Fixes https://github.com/rapidsai/cudf/issues/1970
> Update usage of `std::tuple` to `std::pair` in external libcudf APIs 

- CHANGELOG.md
- python/cudf/dataframe/numerical.py
Remove unnecessary type cast for Numerical column `mean_var` and `mean` and use dtype=np.float64 for reduction instead.
> [REVIEW] Improve Numerical column: `mean_var` and `mean`

- CHANGELOG.md
- cpp/src/io/parquet/page_data.cu
- python/cudf/tests/test_parquet.py
Fix incorrect type definition causing signed right-shift instead of unsigned right-shift.
Resolves #1986
> [REVIEW] Fix signed/unsigned type mismatch causing incorrect NULLs bits

- CHANGELOG.md
- python/cudf/tests/test_string.py
Added 8400 unit-tests for `test_string_cat` as part of PR: #1964 
Reduced them down to 1944 by removing redundant parameters.
cc: @thomcom , @kkraus14
> Removed few redundant unit-tests from test_string.py::test_string_cat 

- CHANGELOG.md
- python/cudf/groupby/groupby.py
- python/cudf/tests/test_groupby.py
Another corner case of pandas behavior with empty dataframes is fixed by this submission.
Fixes https://github.com/rapidsai/cudf/issues/1999 and https://github.com/rapidsai/dask-cudf/issues/273
> [REVIEW] Fix dask-cudf issue with many partitions

- CHANGELOG.md
- python/cudf/dataframe/dataframe.py
- python/cudf/dataframe/multiindex.py
- python/cudf/tests/test_multiindex.py
Fixes https://github.com/rapidsai/cudf/issues/1561
The primary contribution of this PR is that `cudf.from_pandas(pdf)` will correctly return a cudf MultiColumn object if `pdf` has a MultiColumn.
This also fixes our transpose function with multiindex/multicolumn.
> [REVIEW] Improve .column element of MultiColumn

- .github/CODEOWNERS
Adding the java code owners as specified in https://github.com/rapidsai/cudf/pull/1995
> [REVIEW] Add cudf-java-codeowners

- CHANGELOG.md
- cpp/src/stream_compaction/stream_compaction.cu
- cpp/tests/stream_compaction/stream_compaction_tests.cu
- python/cudf/tests/test_dataframe.py
Fixes #2046 from the C++ side. Return `cudf::empty_like(input)` when the input column *or* the input mask are zero-length.
> apply_boolean_mask: return empty column for empty mask

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
Looks like something changed compiler wise in Ubuntu 18.04 where tests find libcudf.so but can't find the transitive dependencies of libcudf.so such as librmm.so and libNVCategory.so. This could likely be fixed in a better way with RPATH / RUNPATH settings, but didn't want to fight with those so close to release. Added the needed transitive dependencies to the link command of the tests.
> [REVIEW] Fix bug with unfound transitive dependencies for GTests in Ubuntu 18.04

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
Something in our Ubuntu 18.04 toolchain changed with regards to `RUNPATH` vs `RPATH` where transitive dependencies are no longer found properly so all of the linked libraries need to be defined until a better solution can be determined.
> [REVIEW] Fix transitive dependencies for `cudftestutil`

- CHANGELOG.md
- docs/source/_static/params.css
- docs/source/conf.py
This fixes the param formatting for our python docs.
> [REVIEW] Stylesheet workaround for doc params [skip ci]

- CHANGELOG.md
- README.md
Auto-merge triggered by push to `branch-0.8` that creates a PR to keep `branch-0.9` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.8 to branch-0.9 [skip ci]

- CHANGELOG.md
- cpp/include/cudf/table.hpp
- cpp/src/groupby/hash/groupby.cu
- cpp/src/table/table.cpp
Closes https://github.com/rapidsai/cudf/issues/2101
Previously, the intermediate result table in groupby was not being freed, causing a sizable memory leak.
> [HOTFIX] Fix memory leak in groupby

- CHANGELOG.md
- cpp/tests/binaryop/unit/jit-cache-multiprocess-test.cpp
- cpp/tests/binaryop/unit/jit-cache-test.cu
- cpp/tests/binaryop/unit/jit-cache-test.hpp
This will hopefully fix the breaks in tests that were reported [here](https://gpuci.gpuopenanalytics.com/view/rapids-branch-gpu-matrix/job/gpuCI/job/cudf/job/branches/job/cudf-gpu-matrix-branch-0.8/CC_VERSION=5,CUDA=9.2,LINUX_VERSION=ubuntu16.04,PYTHON=3.7/36/console) and [here](https://gpuci.gpuopenanalytics.com/view/rapids-branch-gpu-matrix/job/gpuCI/job/cudf/job/branches/job/cudf-gpu-matrix-branch-0.8/CC_VERSION=7,CUDA=9.2,LINUX_VERSION=centos7,PYTHON=3.6/36/console)
For the single process test, the problem was that the cache is not guaranteed to exist and could've been deleted. JitCache handles that case by recompiling but the test would've only passed if it came from file cache.
For the Multi process test, the issue was that both the parent and child process pointed to the same GPU …
> [REVIEW] Fix the test errors in JitCache

- CHANGELOG.md
- cpp/tests/binaryop/unit/jit-cache-multiprocess-test.cpp
- cpp/tests/binaryop/unit/jit-cache-test.cu
- cpp/tests/binaryop/unit/jit-cache-test.hpp
Changed the kernel launch to single block, single thread. 
Earlier the kernel launch was using maximum occupancy. The operation happening in the kernel is this:
```c++
// out[0] = 1, data0 = 4, N=3
for( int i=0; i<N; ++i )
out[0] *= data0;
// Now out[0] = 1*4*4*4 = 64
```
This is wrong, the threads shouldn't be writing to the same location. But the bug didn't appear in single process tests because all the threads ran concurrently. When using multiple processes, some kernel launches would've been delayed for either process because a similar kernel launch was taking place from the other process. When the rest of the kernel launches came to run, they'd see the output already populated and then they'd multiply 64 to it again.
```c++
// out[0] = 64, data0 = 4, N=3
for( int i=0; i<N; ++i ) …
```
> Fix the bug in JitCache tests

- CHANGELOG.md
- java/src/main/native/src/CudfJni.cpp
cudf binops is failing in the java API because it requires a validity buffer on output columns when any of the inputs has a validity buffer.  But in reality it should be checking the null count.
Without this if we read in data from a file, and there are no nulls in the data we will end up keeping empty validity vectors in all the processing for no good reason.
> [REVIEW] Work around for issues with binops and validity checks in Java

- CHANGELOG.md
- cpp/src/copying/copy_range.cuh
- cpp/tests/filling/filling_tests.cu
This is a small fix for `cudf::copy_range`, re: https://github.com/rapidsai/cudf/issues/2142, and adds a test.
The original code was doing a `cudaMemsetAsync` to fill the `null_count` on to the device with the source's `null_count`. `cudaMemsetAsync` operates per byte of the destination, and `gdf_size_type` is 4 bytes, so this doesn't have the intended effect. 
One way to fix is to use `cudaMemcpyAsync`, which this PR does. Another would be to `cudaMemsetAsync` to 0, and then add up to the original `null_count` host-side after kernel is done. One issue with the second approach is that you could get a negative `null_count` from the kernel, so if the gdf_size_type ever became unsigned, we could have underflow issues.
> [REVIEW] Fix null_count bug in cudf::copy_range

- CHANGELOG.md
- cpp/src/io/csv/csv_reader_impl.cu
- cpp/src/io/csv/csv_reader_impl.hpp
- cpp/src/io/csv/type_conversion.cuh
- cpp/src/io/utilities/parsing_utils.cuh
- python/cudf/tests/test_csv.py
Fixes #1925.
* Add `hex`, `hex64`, and `hex32` dtypes
- actual dtypes are `GDF_INT64`, `GDF_INT64`, and `GDF_INT32`
- indicates explicit request to parse with base-16
* Remove hexadecimal inference from dtype detection
* Remove `determineBase` from numeric parsing
* Combine column enablement, hex, and other flags
* Add pytests
> [REVIEW] CSV Reader: Add `hex` dtype for explicit hexadecimal parsing

- CHANGELOG.md
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/reshape/general.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_onehot.py
This fixes: #2203 , #1853 
Changes made in this PR:
cc: @randerzander , @beckernick @kkraus14
> [REVIEW] Matching get_dummies & select_dtypes behavior to pandas

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/Cudf.java
- java/src/main/native/src/CudfJni.cpp
- java/src/test/java/ai/rapids/cudf/ReductionTest.java
This updates the Java bindings to adapt to the renaming of gdf_reduction_op to cudf::reduction::operators and cudf::reduction to cudf::reduce.
> Update Java bindings for reduction rename

- CHANGELOG.md
- ci/gpu/build.sh
- ci/local/build.sh
Sometimes the most annoying and confusing issues are solved with a single line...
This should fix `local/build.sh` from breaking as it was not properly recognizing the directory as a git repo. This results in `git describe --tags` providing empty output. This obviously leads to conda installs being wrong and the script ultimately failing.
> [REVIEW] Fix Local Build Script

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
The first two values must be excluded from the number of delta residuals
Fixes #2238
> [REVIEW] Fix length of RLEv2 delta sequence with nonzero delta residual width

- .github/CODEOWNERS
- CHANGELOG.md
Separate dask group was already created and populated, just adds it to the github `.CODEOWNERS` file.
> [REVIEW] Add dask codeowners [skip ci]

- CHANGELOG.md
- python/cudf/cudf/dataframe/index.py
- python/cudf/cudf/tests/test_groupby.py
- python/cudf/cudf/tests/test_index.py
GenericIndex.copy() is broken leading to issues such as #2310 and the following:
```
In [1]: import cudf                                 
In [2]: a = cudf.dataframe.index.StringIndex(['a', 'b', 'c'])                                           
In [3]: a                                           
Out[3]: StringIndex(['a' 'b' 'c'], dtype='object')
In [4]: a.rename('b')                               
Out[4]: GenericIndex(['a', 'b', 'c'], dtype=object, name='b')
```
Fixes #2310
> Fix copy behaviour for GenericIndex

- CHANGELOG.md
- python/cudf/cudf/dataframe/categorical.py
- python/cudf/cudf/dataframe/column.py
- python/cudf/cudf/dataframe/datetime.py
- python/cudf/cudf/dataframe/numerical.py
- python/cudf/cudf/tests/test_datetime.py
- This PR factors out `_unique_segments` and `unique_count` from the column subclasses and brings them to the parent Column class to reduce code copying. I think this also makes sense logically as these methods are not conceptually tied to any type of column, but the column itself.
- Adds a not implemented `sort_by_values` to the Column class, requiring it to be implemented by the subclasses. Not bringing it into the parent class as the categorical column implementation relies on knowledge that it can become a numerical column. This is the same reason that the implementations of unique are kept in the subclasses.
- Implements `unique`, `nunique`, and `value_counts` for Datetime columns.
This closes #2314 and should allow #2245 to avoid additional branching logic for …
> [REVIEW] Implement unique, nunique, and value_counts for datetime columns via refactor

- CHANGELOG.md
- python/cudf/cudf/dataframe/categorical.py
- python/cudf/cudf/tests/test_categorical.py
Ensure `set_categories` preserves current element order. Closes https://github.com/rapidsai/cudf/issues/2306.
> [REVIEW] Ensure order is preserved in CategoricalAccessor._set_categories

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
Patch offset and values are incorrectly read from the bitstream
Fixes #2322
> [REVIEW] ORC Reader: Fix patched base RLEv2 value with nonzero patch width

- CHANGELOG.md
- cpp/include/cudf/groupby.hpp
- cpp/src/groupby/new_groupby.cu
- cpp/tests/groupby/without_agg/groupby_wo_agg_test.cu
gdf_group_by_without_aggregations was returning device_vector and it had to return column, so the current set of changes will return gdf_column, once cudf column is available, it will be changed to it close #2239 .
> [REVIEW] gdf_group_by_without_aggregations returns gdf_column close #2239

- CHANGELOG.md
- python/cudf/cudf/dataframe/index.py
- python/cudf/cudf/dataframe/multiindex.py
- python/cudf/cudf/utils/utils.py
`slice` objects already have an `indices()` method, obviating the need for the current `standard_python_slice` utility.
> Just use `slice.indices()` to get slice start/stop/step

- CHANGELOG.md
- codecov.yml
Disable CodeCov's ability to post a fail status until we discuss a standard we want to set.
> [REVIEW] Remove CodeCov Status Failures

- CHANGELOG.md
- python/cudf/cudf/tests/test_apply_rows.py
- python/cudf/cudf/tests/utils.py
- python/cudf/cudf/utils/applyutils.py
Fixes #2155
`apply_rows` had strange behavior for null inputs, causing output location to be skewed/shifted, and nulls to end up at the end. This PR addresses that by introducing pessimistic null handling, wherein if any input is null, all outputs will be null. Why? Because `apply_rows` uses Numba, and Numba doesn't handle nulls. Therefore we have to determine the validity of the output based solely on the input, and not the operation itself. Thus, if we see any invalid input for a given row, we make all output invalid for that row.
> [REVIEW] apply_rows: pessimistic null handling

- CHANGELOG.md
This is to add an entry to the CHANGELOG to refer to the correct PR that had a change to fix a bug in the java serialization of the validity buffer: https://github.com/rapidsai/cudf/commit/0143c8c0d76f541e2aeeb28069b57fdd79e7a0f4, which was accidentally merged here: https://github.com/rapidsai/cudf/pull/2481
> CHANGELOG for validity buffer serialization issue

- CHANGELOG.md
- cpp/src/io/convert/dlpack/cudf_dlpack.cpp
- cpp/tests/groupby/hash/single_column_multi_agg.cu
This replaces an `assert` in the dltensor deleter that prevented freeing device memory in release builds. Uses RMM_TRY as it should now.
Fixes #2400
> Fix to_dlpack memory leak in dltensor deleter

- CHANGELOG.md
- python/cudf/cudf/dataframe/dataframe.py
- python/cudf/cudf/dataframe/series.py
- python/cudf/cudf/tests/test_dataframe.py
This PR adds `_constructor`, `_constructor_sliced`, and `_constructor_expanddim` to the python API for `Series` and `DataFrame`.  The motivation for these simple additions are explained a bit in [cudf#2506](https://github.com/rapidsai/cudf/issues/2506) (the `_constructor_sliced` is "needed" to support both pandas and cudf for some sorting work in dask).
Note that the new properties are designed to match [the pandas API](https://pandas.pydata.org/pandas-docs/stable/development/extending.html#override-constructor-properties):
> Adding _constructor properties to Series and DataFrame

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
In chunks with NULLs, threads at the end of the block may read stale row position data and overwrite good data with stale values.
> [REVIEW] Orc reader: Fix non-deterministic data decoding at end of chunk

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
conditions
These is a bug fix (https://github.com/rapidsai/cudf/issues/2564)  for the java side of things that we hope can go in to branch-0.9.
> [REVIEW] ColumnVector.fromScalar fixes for null scalars, and double free in error

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
Resolves incorrect data decoding for RLEv2 mode2 with negative base values.
> [REVIEW] Fix incorrect base value mask in 64-bit ORC RLEv2 mode2

- CHANGELOG.md
Cleanup of changelog for 0.9 release. Moved a few things from improvement to new feature and vice versa. Fixed typos, inconsistencies, long lines.
> Changelog cleanup for 0.9 release

- CHANGELOG.md
- cpp/src/io/orc/stripe_init.cu
Primary data stream index of DECIMAL columns does not include the RLE run
> [REVIEW] ORC reader: fix parsing of DECIMAL index stream

- CHANGELOG.md
- cpp/src/bitmask/legacy/bitmask_ops.cu
- cpp/src/column/legacy/column.cpp
Remove use of cudaMallocManaged in gdf_column_concat as it (and other uses) prevents use of libcudf on platforms with out managed memory support.
This PR does not attempt to refactor gdf_column_concat into a "more modern" cudf::concat, although we should do that...
> Remove managed memory from gdf_column_concat

- CHANGELOG.md
- cpp/benchmarks/search/search_benchmark.cu
Currently search benchmark cannot compile because it's missing `<random>` header.
```
/home/hao/cudf/cpp/benchmarks/search/search_benchmark.cu(89): error: namespace "std" has no member "mt19937"
```
This PR fixes the issue.
> [BUG] Add header to search benchmark

- CHANGELOG.md
- cpp/src/groupby/hash/groupby.cu
- cpp/src/groupby/hash/groupby_kernels.cuh
- cpp/src/hash/concurrent_unordered_map.cuh
- cpp/src/hash/concurrent_unordered_multimap.cuh
- cpp/src/hash/hash_functions.cuh
- cpp/src/join/join_compute_api.h
- cpp/src/join/join_kernels.cuh
- cpp/tests/hash_map/map_test.cu
- cpp/tests/hash_map/multimap_test.cu
Removes the dependence of the `concurrent_unordered_map` and `concurrent_unordered_multimap` classes on managed memory allocation.
`concurrented_unordered_map`
`concurrented_unordered_multimap`
I also had to remove the `const` from members from either map class as `const` members implicitly delete the copy-assignment operator. The copy-assignment operator is required (for some reason) in functors passed to Thrust. In short, if you want a `map` object to be a member (instead of what was previously a _pointer_) of a functor passed to Thrust, it needs to have a copy-assignment operator.
> Remove managed allocator from hash map classes

- CHANGELOG.md
- python/cudf/cudf/dataframe/column.py
- python/cudf/cudf/dataframe/index.py
- python/cudf/cudf/tests/test_serialize.py
This PR changes how serialization is done for indexes.  Previously, the serialization scheme only stored the pickle-able data.  This is both inefficient and probably wrong.   Now cuDF will grab with DeviceNDArray if the index is GPU backed. 
cc @kkraus14
> [Review] Fix Index (De-)Serialization

- CHANGELOG.md
- cpp/src/io/utilities/datasource.hpp
Fixes #2620.
* Missing virtual dtor in abstract base class
> [REVIEW] IO Readers: Fix datasource memory map failure for multiple reads

- CHANGELOG.md
- cpp/tests/types/types_test.cpp
Take 2...
Fix #2593 by explicitly casting negative int to char to ensure proper compilation on TX2/Xavier/Nano.
> [REVIEW] Fixing static char cast from type int to char with arm; issue 2593

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Partitioning of strings using the java API failed prior to this change.  Now it works for STRING_CATEGORY, but not STRINGS.
> [REVIEW] Fix string partitioning in java API

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This fixes issues with the java concat API.  Specifically it makes it work with string_categories and fixes it losing the time units.
> Make concat not lose time units and work with string categories

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR is the column version of: https://github.com/rapidsai/cudf/pull/2641
Arguably we should refactor the table concat to use the column concat, but I am not sure if there will be a table based concat in cudf c++, so I am leaving them independent for now.
> [REVIEW] Fix ColumnVector concatenate for string categories and to keep timestamp units

- CHANGELOG.md
- cpp/src/io/avro/avro_gpu.cu
Scratch block data in shared mem was shared between all warps instead of having one scratch space per warp
Resolves #2666
> [REVIEW] Fix race condition in AVRO reader

- CHANGELOG.md
- cpp/src/io/avro/avro_reader_impl.cu
- cpp/src/io/avro/avro_reader_impl.hpp
Was incorrectly using vector::memory_size() instead of vector::size() when passing the number of compressed blocks to the decompression kernel.
Also, NVStrings::create_from_index was potentially being called with data that was already freed for dictionary enums.
> [REVIEW] AVRO Reader: fix errors when decoding compressed streams

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_monotonic.py
Addresses https://github.com/rapidsai/cudf/issues/1957.
Dask uses `iloc` to chop up cuDF dataframes. Without this fix, the sum memory footprint of the resulting distributed dataframe will be larger then that of the original due to the pieces carrying `GenericIndex` instead of `RangeIndex` objects, which are lighter.
> [REVIEW] Return RangeIndex from contiguous slice of RangeIndex

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/NvtxColor.java
- java/src/main/java/ai/rapids/cudf/NvtxRange.java
- java/src/main/native/CMakeLists.txt
- java/src/main/native/src/NvtxRangeJni.cpp
Adding Java bindings to libcudf's NVTX APIs so Java code can create NVTX ranges. The range is designed to be used always in a try-with-resources block to ensure ranges are closed in the proper order.
> Add Java bindings for NVTX ranges

- CHANGELOG.md
- cpp/src/io/csv/csv_writer.cu
Reference #2678 
This change improves the speed of the csv-writer up to 2x depending on the data.
The main change is to build the CSV format in device memory instead of CPU memory.
This means the output data matrix is now also computed in CUDA code.
The only remaining device-to-host copy is right before writing the output file.
No new test cases are required since the overall function and code-paths remains the same.
As mentioned in #2678, this is the first step for other improvements we can make to the csv-writer.
> [REVIEW] Compute CSV format in device code to improve performance

- .gitmodules
- CHANGELOG.md
Just pinning the jitify branch to `feature/api_v2 branch_v0.10` per conversation with @devavret
> [REVIEW] Switch jitify branch

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
- cpp/CMakeLists.txt
- cpp/tests/CMakeLists.txt
- python/cudf/setup.py
cuSpatial can't find the `cudf.pxd` header because of a missing `__init__.pxd`, so fixing shipping the headers in general after the Python reorg.
Additionally, shipping the `libcudftestutil.a` static lib as part of the libcudf conda package.
> [REVIEW] Fix missing headers / libs needed for cuspatial build

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_multi.py
- python/cudf/cudf/utils/utils.py
This pr closes #188 and #1162 . 
Currently, in `cudf` we don't support `sort = True` and `pandas` currently by default `sorts` columns (which will be depreciated soon to `sort` = `False` ) .  
This implementation only supports `sort` = `False` we can do a follow up pr to allow `sort=True` if the need arises. 
See: https://github.com/rapidsai/cudf/blob/50a9dc7f8f207ffd9236b5409d7e0694168bb908/python/cudf/cudf/core/reshape.py#L26-L27
Currently, we don't support concatenation of non string column with string columns. 
Though doing this is just a one line change i think we should not implicitly support this behavior as we may run into a lot of issues when we use this with `dask-cudf` as we can silently cast up to strings leading to memory shoot ups and other metadata dtype problems . 
In the …
> [REVIEW] Add concatenation for data-frame with different headers (empty and non-empty)

- CHANGELOG.md
- python/nvstrings/cpp/CMakeLists.txt
Simply adds some additional hints to the NVStrings python cmake to find libnvstrings.so and headers (and nvtext and nvcategory) if they have been built locally and not installed.
> Allow building nvstrings python if nvstrings built locally but not installed

- CHANGELOG.md
- cpp/custrings/category/NVCategory.cu
Fixes #2755 by synchronizing the default stream after the async copy.
This only addresses the two instances identified where NVCategory code was directly accessing host memory while a device write could still be pending.  It does not address potential issues where NVCategory calls can return with device-to-host writes still pending (e.g.: `create_index`, `get_values`).
> [REVIEW] Fix async race in NVCategory::get_value and get_value_bounds

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
The join API recently changed to a C++ API.  This updates the code to use that new API and documents clearly the order of the columns returned, as it has changed.
This also updates the tests to be clearer about the columns returned, and hopefully a clearer in general.
> [REVIEW] Fixed java code to use new join API

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Fixes https://github.com/rapidsai/cudf/issues/2686
Our `DataFrame::drop` method didn't support `column` as an argument like Pandas. It does now.
> [REVIEW] Add column argument to cudf drop

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
- Adds `notnull` methods to Series/DataFrames for dask compatibility of other statistical methods (#2719 ).
- Removes `**kwargs` from the DataFrame methods. They are unnecessary and don't exist in pandas.
Closes #2840
> [REVIEW] Series/DataFrame notnull

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_cuda_apply.py
- python/cudf/cudf/utils/applyutils.py
In testing this gave a ~15x speedup for `apply_rows` with a sufficiently large DataFrame and basic UDF. For `apply_chunks` removes the guesswork in supplying `tpb` / `blkct` parameters and lets CUDA handle the kernel configuration by default (can still override if desired).
> [REVIEW] Optimizations of kernel launch configurations for apply functions

- CHANGELOG.md
- cpp/custrings/strings/substr.cu
- python/nvstrings/tests/test_substr.py
Closes #2782 
This fixes the `nvstrings` `slice` and `slice_from` methods which were handling the (0,0) range incorrectly as described in the issue.
The expected behavior is to return empty strings for this case like Pandas does.
> [REVIEW] Fix nvstrings.slice and slice_from for range (0,0)

- CHANGELOG.md
- ci/cpu/custreamz/build_custreamz.sh
- conda/recipes/custreamz/meta.yaml
Use YYMMDD tag for nightly build. Done as requested in: https://github.com/rapidsai/ops/issues/452
> Use YYMMDD tag in custreamz nightly build

- Dockerfile
Fixes #2889 - Building cudf from Dockerfile
1. README example works after this fix:
```bash
(cudf) root@dd6b538dd424:/cudf/python/cudf# python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf, io, requests
/conda/envs/cudf/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.
For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
warnings.warn(errors.NumbaDeprecationWarning(msg)) …
```
> [REVIEW] Add setup.py install for nvstrings

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/NvtxRange.java
Small fix so if NvtxRange is the first thing loaded by java that it will in turn load any needed native dependencies.
> [REVIEW] Fix java nvtxrange dependency loading

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
Fixes java side to use operators in `cudf::groupby::operators`
RE: https://github.com/rapidsai/cudf/pull/2605
> [REVIEW] Fix java hash aggregate compilation

- CHANGELOG.md
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/utils/cudautils.py
- python/cudf/cudf/utils/utils.py
- Changes the rounding algorithm to avoid the floating point representation issue caused by using Python's `fmod`.
- Adds a utility function `rint` that is the equivalent of numpy's `rint` [C ufunc](https://github.com/numpy/numpy/blob/31ffdecf07d18ed4dbb66b171cb0f998d4b190fa/numpy/core/src/npymath/npy_math_internal.h.src#L279)
This closes #2921 
```python
import cudf
zscores_df = cudf.DataFrame()
for x in range(1,17):
zscores_df['zscore'] = [float(-0.6459412758761901)]
zscores_df['zscore'] = zscores_df['zscore'].round(decimals=x)
print("ZSCORE", zscores_df['zscore'][0])
ZSCORE -0.6
ZSCORE -0.65
ZSCORE -0.646
ZSCORE -0.6459
ZSCORE -0.64594
ZSCORE -0.645941
ZSCORE -0.6459413
ZSCORE -0.64594128
ZSCORE -0.645941276
ZSCORE -0.6459412759
ZSCORE -0.64594127588
ZSCORE …
```
> [REVIEW] Update rounding algorithm to avoid using fmod

- CHANGELOG.md
- cpp/include/cudf/column/column_device_view.cuh
For performance reasons, the previous `column_device_view::is_null` and `column_device_view::is_valid` functions would _not_ first check for the existence of the null bitmask before attempting to read the specified bit. Therefore it was undefined behavior to invoke this functions if `nullable() == false`.
This may violate the principle of least surprise for some users. Therefore, the old behavior for `is_null/is_valid` functions have been renamed to `is_null_nocheck`/`is_valid_nocheck`. The new `is_null/is_valid` will now check for `nullable() == false` before attempting to read the bits.
> [REVIEW] Add safe versions of `is_null`/`is_valid`. Rename the old ones

- CHANGELOG.md
- cpp/src/table/legacy/device_table.cuh
The `_stream` member of legacy `device_table` was never initialized. Fixed by just capturing the `create()` stream parameter in the deleter lambda and passing it to `destroy()`, rather than keeping a member stream around since it isn't used elsewhere.
Fixes #3037
> Fix uninitialized stream parameter in device_table deleter

- CHANGELOG.md
- cpp/include/cudf/utilities/traits.hpp
- cpp/tests/wrappers/timestamps_test.cu
Namespace name change from `exp` to `experimental` was merged with old name.
This PR is to fix the error so builds will not fail.
> [REVIEW] exp to experimental namespace name change issue

- CHANGELOG.md
- ci/release/update-version.sh
Updating `update-version.sh` for new docs locations
Tested with `major` arg and confirmed major version numbers were incremented in .py files in new doc locations.
> Updating update-version.sh for new docs locations

- CHANGELOG.md
- docs/cudf/source/guide-to-udfs.ipynb
Summary of Changes
- Changes top-level header format H1(#) to H2 (##) for sub-sections; H1 sub-section headers caused incorrect rendering of the Table of Contents
> [REVIEW] Fix UDF doc markdown formatting

- CHANGELOG.md
- CONTRIBUTING.md
The PR updates the instructions for building `nvstrings` python packages in the contributing.md documentation.
> [BUG] Add nvstrings python build instructions to contributing.md

- CHANGELOG.md
- cpp/tests/strings/array_tests.cu
- cpp/tests/strings/factories_test.cu
- cpp/tests/strings/utilities.cu
- cpp/tests/utilities/column_wrapper.hpp
- cpp/tests/utilities_tests/column_wrapper_tests.cu
Merge of #2971 caused automatic merge of #3130.
But the rename of this file was left out of 2917 and in causing a build issue.
```
/cudf/cpp/tests/utilities_tests/column_wrapper_tests.cu:18:48: fatal error: tests/utilities/column_utilities.cuh: No such file or directory
compilation terminated.
...
```
This PR fixes the affected files and also completes the changes requested on 3130.
> [REVIEW] Rename column_wrapper.cuh to column_wrapper.hpp

- CHANGELOG.md
- cpp/include/cudf/column/column_device_view.cuh
Closes https://github.com/rapidsai/cudf/issues/3167
`mutable_column_device_view::head<T>()` was calling the default (void) instantiation of `column_device_view_base::head()` which caused the const_cast<T*> to fail. Use the correct instantiation for T instead. Also changed the implementation of data() to call column_device_view_base similarly.
> [REVIEW] Fix mutable_column_device_view head

- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/native/src/RmmJni.cpp
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
- java/src/test/java/ai/rapids/cudf/ByteColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/CudfTestBase.java
- java/src/test/java/ai/rapids/cudf/Date32ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/Date64ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/DoubleColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/FloatColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/HostMemoryBufferTest.java
- java/src/test/java/ai/rapids/cudf/IntColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/LongColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/PinnedMemoryPoolTest.java
- java/src/test/java/ai/rapids/cudf/ReductionTest.java
- java/src/test/java/ai/rapids/cudf/RmmMemoryAccessorTest.java
- java/src/test/java/ai/rapids/cudf/ShortColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
- java/src/test/java/ai/rapids/cudf/TimestampColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/UnaryOpTest.java
I doubt this can go in.  It fixes all of the unit test failure we have been seeing in java for 0.10 and is the equivalent for the fixes #3139 and #3092
> [REVIEW] Init RMM with no pooling at the beginning

- CHANGELOG.md
- build.sh
- conda/recipes/libcudf/build.sh
- conda/recipes/libnvstrings/build.sh
- cpp/CMakeLists.txt
Sets `CUDA_VERSION`, `CUDA_MAJOR_VERSION`, and `CUDA_MINOR_VERSION` variables that were previously set by the deprecated `FindCUDA` cmake package. 
See also:
* [Modern cmake + cuda examples](https://gitlab.kitware.com/robertmaynard/cmake_cuda_tests)
* [FindCUDALibs.cmake](https://gitlab.kitware.com/robertmaynard/cmake_cuda_tests/blob/fa997dbf80b2bfb3168149a7e9375d5c4c51c0fb/cmake/FindCUDALibs.cmake)
> [REVIEW] Set cmake cuda version variables

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
- java/src/main/java/ai/rapids/cudf/Rmm.java
Fixes #3215 
This default-initializes RMM when the Java native dependencies are loaded.  This addresses the issue in #3139 where the `ai.rapids.cudf.Rmm` class may not be referenced before native code is executed and therefore leave RMM uninitialized.  By hooking it into the native deps loader, this makes it impossible to call libcudf code without default-initializing RMM first.
> Default initialize RMM when Java native dependencies are loaded

- CHANGELOG.md
- python/cudf/cudf/core/series.py
- python/cudf/cudf/utils/numbautils.py
An [update to numba](https://github.com/numba/numba/pull/4609) in version 0.46+ was recently introduced that corrected the `__cuda_array_interface__` property of `numba` device arrays. In short, the interface now allows for the case where `__cuda_array_interface__['strides'] == None`. However the [CuPy 6.5 release](https://github.com/cupy/cupy/blob/b086a9589c7136ef012315980abcb6953b7e1371/cupy/core/core.pyx#L2516) hasn't caught up to this and while the necessary changes have been merged, they won't be included with `CuPy` until `7.0`. Normally we might choose to pin `numba=0.45.1`, however [the fix for the ucx bug](https://github.com/numba/numba/blob/0.46.0rc1/CHANGE_LOG#L108) is actually included in `numba=0.46`. 
This creates a situation where we need `numba=0.45.1` to fix …
> [REVIEW] Introduce temporary patched numba array to fix Numba 0.46/CuPy 6.3 Compatibility 

- CHANGELOG.md
- cpp/src/predicates/is_sorted.cu
Closes https://github.com/rapidsai/cudf/issues/3221
The old `is_sorted` was constructing a temporary `device_vector` when constructing the `row_inequality_comparator`. This ends up getting free'd as soon as the constructor exits, which leaves the comparator object with a dangling pointer.
> [REVIEW] Fix is_sorted

- CHANGELOG.md
- cpp/src/io/orc/stripe_enc.cu
Literal runs of exactly 128 were encoded as a zero byte instead of 0x80.
> [REVIEW] ORC writer: fix incorrect ByteRLE encoding of literal_run=128

- CHANGELOG.md
- cpp/src/io/orc/stripe_enc.cu
If the minimum value in an unsigned literal batch had its most significant bit set, it would get decoded as a negative value.
Unsigned patched base mode encodes the base value as signed, so need to take this into consideration when computing the base value byte width.
> [REVIEW] Fix ORC writer integer RLEv2 mode2 unsigned base value encoding

- CHANGELOG.md
- cpp/src/predicates/legacy/is_sorted.cu
Another case of using a temporary that is immediately deleted and leaves `exec` with a reference to a destroyed object.
```
auto exec = rmm::exec_policy(stream)->on(stream);
```
`rmm::exec_policy(stream)` returns a `unique_ptr` to a Thrust execution policy object. Invoking `->on(stream)` returns another execution policy to run on a stream.
The problem is that when `rmm::exec_policy(stream)->on(stream)` returns, the `unique_ptr` is destroyed and `exec` references a deleted object.
> Fix is_sorted, again. 

- CHANGELOG.md
- cpp/src/column/column_device_view.cu
Children are not supported for mutable_column_device_view. The CUDF_EXPECTS check for this was incorrect and fixed by this PR.
> [REVIEW] Invalid children check in mutable_column_device_view

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
`PinnedMemoryPool` uses a single-thread executor to allocate the pinned memory pool in the background on startup.  This background thread is created as a non-daemon thread.  If the executor is never shutdown properly before the application's main thread exits, the application will hang due to the lingering non-daemon worker thread.
This updates the pinned pool initialization to immediately shutdown the executor after the initializtaion task is submitted and also use daemon threads.
> Fix shutdown hang issues with pinned memory pool init executor

- CHANGELOG.md
- cpp/include/cudf/null_mask.hpp
- cpp/src/bitmask/null_mask.cu
- cpp/tests/bitmask/bitmask_tests.cu
Adds utility function to get the number of bitmask words necessary to represent `n` bits. 
Adds some tests for other bitmask utilities as well.
> Add num_bitmask_words 

- CHANGELOG.md
- CONTRIBUTING.md
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
- conda/recipes/libcudf/meta.yaml
- conda/recipes/libnvstrings/meta.yaml
- cpp/cmake/Templates/Arrow.CMakeLists.txt.cmake
Upgrades Arrow to v0.15.1 to eliminate nvcc compiler warnings.
> [REVIEW] Upgrade arrow-cpp and pyarrow to v0.15.1

- CHANGELOG.md
- cpp/include/cudf/detail/unary.hpp
- cpp/src/filling/legacy/repeat.cu
- cpp/src/filling/legacy/tile.cu
- cpp/src/groupby/legacy/groupby_without_aggregation.cu
- cpp/src/stream_compaction/legacy/drop_duplicates.cu
- cpp/src/unary/legacy/null_ops.cu
Closes https://github.com/rapidsai/cudf/issues/2636
Statements like this are a bug:
`auto exec = rmm::exec_policy(stream)->on(stream);`
This is because you'll be left with a reference to an invalid object.
Instead:
```
thrust::sort(rmm::exec_policy(stream)->on(stream), ...);
// or
auto exec = rmm::exec_policy(stream);
thrust::sort(exec->on(stream), ...);
```
The reason is `rmm::exec_policy(stream)` returns a unique_ptr to a Thrust execution policy object. Invoking `->on(stream)` returns another execution policy to run on a stream.
The problem is that when `rmm::exec_policy(stream)->on(stream)` returns, the unique_ptr is destroyed and exec references a deleted object. 
This PR fixes a number of latent, silent errors in libcudf.
> [REVIEW] Fix storing invalid RMM exec policies

- CHANGELOG.md
- cpp/src/strings/strings_column_factories.cu
- cpp/tests/strings/factories_test.cu
Strings column factory functions were throwing exceptions when given empty data. Zero data should return empty columns instead.
> [REVIEW] Remove zero-size exception from strings factory functions

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/BitVectorHelper.java
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
- java/src/main/native/include/jni_utils.hpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
libcudf expects validity buffer sizes to be padded to a 64-byte boundary, but the Java bindings were only padding to 64 _bits_.  This causes device memory read overruns when libcudf tries to copy a Java-created validity buffer to an output vector.  The invalid read access is more likely to occur when not running with RMM in pooled mode.
> Fix Java to pad validity buffers to 64-byte boundary

- CHANGELOG.md
- cpp/include/cudf/strings/string_view.cuh
- cpp/include/cudf/strings/string_view.inl
The `string_view` class encapsulates a utf8 sequence of chars and provides methods for simple view operations on those bytes. The number of characters can be different the size in bytes. String operations that use position or length values are always specified in character units.
Calculating the number of characters for a string requires traversing each character to count them up. This can become expensive for long strings. This PR adds a cached member variable to the `string_view` class to keep the number of characters once computed in the `length()` member function.
> [REVIEW] Add cache member for number of characters in string_view class

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/strings/convert/convert_booleans.hpp
- cpp/src/strings/convert/convert_booleans.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/strings/booleans_tests.cu
Port NVStrings `to_booleans` and `from_booleans` APIs to cudf strings column.
These convert boolean columns to strings column and vice versa.
> [REVIEW] Port NVStrings boolean to/from strings converters

- CHANGELOG.md
- cpp/include/cudf/column/column_view.hpp
Disabling `column_view` iterators for non fixed-width types.
close #3355
> [REVIEW] Disabling `column_view` iterators for non fixed-width types

- CHANGELOG.md
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/io/__init__.py
- python/dask_cudf/dask_cudf/io/parquet.py
- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
Closes #3365 
This PR adds explicit definitions for `to_parquet` and `write_partition` in dask_cudf.  Previously, dask_cudf was falling back to upstream dask for this functionality.  However, there is pandas-specific code in [`write_partition`](https://github.com/dask/dask/blob/4a42071f50d12f30e15afe1348a147cb45ebaa69/dask/dataframe/io/parquet/arrow.py#L464) that is causing problems for cudf-based dask dataframes.  Since we will soon need to define a `CudfEngine` implementation of `write_partition` when a GPU-accelerated `cudf.io.to_parquet` is supported,  it probably makes sense to add an initial implementation to address the #3365 bug.
> [REVIEW] Adding to_parquet and write_partition definitions to dask_cudf

- CHANGELOG.md
- cpp/include/cudf/table/table.hpp
- cpp/include/cudf/table/table_view.hpp
- cpp/src/table/table.cpp
- cpp/src/table/table_view.cpp
- cpp/tests/table/table_tests.cpp
- cpp/tests/table/table_view_tests.cu
Add `select` to table_view
Remove asserts in `table_view::column` and use `std::vector::at` instead
Remove `column_indices` size check from `table::select`
> [REVIEW] Add select method to table_view

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/strings/detail/fill.hpp
- cpp/src/strings/filling/fill.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/strings/fill_tests.cu
Create a `strings::detail::fill()` function to fill a column of strings with a `string_scalar`.
```
std::unique_ptr<column> cudf::strings::detail::fill( strings_column_view const& strings,
size_type first, size_type last,
string_scalar const& value,
memory_resource, stream );
```
> [REVIEW] Add fill() function for strings column

- CHANGELOG.md
- cpp/src/rolling/legacy/rolling.cu
- cpp/tests/rolling/legacy/rolling_test.cu
Fix for https://github.com/rapidsai/cudf/issues/2689.
Properly compute null counts in the same style as valid_if and copy_if_else.
> [REVIEW] Null count fix for rolling_window.  Fixes #2689

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
This small change enables functionality like `df[[True, False, False]]` when the DataFrame is indexed with a MultiIndex.
> [REVIEW] Support getitem with bools when DataFrame has a MultiIndex

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
PR fixes two things:
- serialize column names (needed when columns are integers9
- call StringColumn constructor when deserializing Strings
Resolves https://github.com/rapidsai/cudf/issues/3406
cc @pentschev
> Fix Serialization

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/backends.py
Closes #3363 
In order to use the upstream dask covariance/correlation implementation, a few changes are needed in cudf/dask_cudf:
1. `concat_cudf` must support `axis=1` (already supported in `cudf`, so this is a trivial change)
2. cudf must define a dataframe-level `cov` method
This PR addresses both of these changes.  However, (2) is only addressed with a cupy-based implementation (which does *not* handle dataframes with null values).
TODO Before Merging:
> [REVIEW] Enable covariance/correlation in dask_cudf

- CHANGELOG.md
- cpp/custrings/strings/datetime.cu
- cpp/custrings/tests/test_datetime.cu
Fixed a bug in parse_into_parts where we weren't checking for end-of-string at the right place.  This could cause length (an unsigned int) to roll negative which would prevent us from every bailing early. 
I just moved the if check before the other if(){continue;} check that was causing the rollover.  Also added some tests to verify this new behavior.
> [REVIEW] Correct end-of-string checking in strings timestamp parsing.  Fixes #3353

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
When using the java api  and pulling a columnt hat contains strings back off the GPU to host memory, we leak memory.  The reason for this is the NVStrings are special so we can't just RMM free the memory address, we have to actually delete the NVString. This patch uses freeCudfColumn just like OffHeapState.cleanImpl does.
I tested this on both a small file where we put data on GPU, then pull it back off to do a udf. Without this patch if you dump out the rmm log you will see leaked memory, with this patch no more leaked memory.  I also ran it on the Mortgage ETL example where I was regularly seeing OOM with partition sizes over 512MB, and those errors went away.
> [REVIEW] Fix memory leak with strings when pulling data off the GPU

- CHANGELOG.md
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
This pr adds check for length of device array for shift/diff before launching kernels.
PR fixes issue #3433  .
> [REVIEW] Fix diff and shift for empty series

- CHANGELOG.md
- cpp/include/cudf/strings/copying.hpp
- cpp/include/cudf/strings/detail/scatter.cuh
- cpp/include/cudf/strings/detail/utilities.hpp
- cpp/src/strings/copying/copying.cu
- cpp/src/strings/utilities.cu
- cpp/src/strings/utilities.hpp
- cpp/tests/strings/array_tests.cu
Special scatter function for handling strings columns.
Closes #3437 
The caller must set the null mask in the output column.
This is needed for #3354
> [REVIEW] Strings scatter detail function

- CHANGELOG.md
- cpp/tests/utilities/column_utilities.cu
- cpp/tests/utilities_tests/column_utilities_tests.cu
Some issues were discovered in the print column implementation.
First, the std::transform method does not guarantee serial order, so the mechanism used in this implementation might not check validity correctly.
Second, there was confusion about what should be printed in the case of invalid entries.  After some slack discussion, the conclusion was we should change the printed character from @ to NULL.  So a numeric column with values { 0, 1, 2 } where the 1 is invalid would print (with a comma delimiter) as "0,NULL,2".  Similarly, a string column with values { "a", nullptr, "c" } where nullptr is invalid would print (with a comma delimiter) as "a,NULL,c".
> [REVIEW] Fix printing of invalid entries

- CHANGELOG.md
- cpp/tests/utilities/timestamp_utilities.cuh
Unnecessary use of `std::abs` after calculating `min` and `max` and really we should be using `std::minmax` but until C++17 when we have structured bindings it doesn't improve things much - so just left a comment.
> Small cleanup and comment

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
- cpp/tests/utilities/column_utilities.cu
- cpp/tests/utilities/column_utilities.hpp
- cpp/tests/utilities/timestamp_utilities.cuh
- cpp/tests/utilities_tests/column_utilities_tests.cpp
- cpp/tests/utilities_tests/column_utilities_tests.cu
`to_host` handles copying the bit mask to the host differently for strings and fixed-width columns. This PR adds a single utility, `bitmask_to_host()` which both `to_host` functions now use, so they behave the same.
> [REVIEW] Add bitmask_to_host column utility

- CHANGELOG.md
- cpp/include/cudf/utilities/traits.hpp
- cpp/tests/CMakeLists.txt
- cpp/tests/bitmask/bitmask_tests.cu
- cpp/tests/utilities/base_fixture.hpp
This PR adds a few testing improvements
Merge after #3475
> Add is_boolean trait and random timestamp generator for testing

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Adds an `inplace` argument to `DataFrame.drop()`, which fixes https://github.com/rapidsai/cudf/issues/3493.
Using in-place avoids a copy and can improve performance significantly (see https://github.com/dask/dask/pull/5657)
> df.drop(): added inplace=False argument

- CHANGELOG.md
- ci/cpu/upload_anaconda.sh
- ci/docs/build.sh
We no longer rely on these labels for version matching and use cudatoolkit package to do so.
> FIX Remove unused CUDA conda labels

- CHANGELOG.md
- cpp/include/cudf/strings/strings_column_view.hpp
- cpp/src/strings/copying/concatenate.cu
- cpp/src/strings/strings_column_view.cu
- cpp/tests/strings/concatenate_tests.cu
Strings column concatenate does not handle zero-sized columns correctly.
Additionally, the code is not handling the column_view offset when creating the output column.
The following test was causing a seg-fault:
```
cudf::column_view zero_size_strings_column( cudf::data_type{cudf::STRING}, 0, nullptr, nullptr, 0);
std::vector<cudf::strings_column_view> strings_columns;
strings_columns.push_back(cudf::strings_column_view(zero_size_strings_column));
std::vector<const char*> h_strings{ "aaa", "bb", "" };
cudf::test::strings_column_wrapper strings1( h_strings.begin(), h_strings.end() );
strings_columns.push_back(cudf::strings_column_view(strings1));
cudf::strings::detail::concatenate(strings_columns);
```
> [REVIEW] Fix strings column concatenate handling zero-sized columns

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
As we have not yet tested CuPy 7, restrict cuDF usage to CuPy 6 for now.
> Restrict CuPy to 6

- CHANGELOG.md
- cpp/src/unary/unary_ops.cuh
- cpp/tests/unary/unary_ops_test.cu
Closes https://github.com/rapidsai/cudf/issues/3534
This addresses: https://github.com/rapidsai/cudf/issues/3534#issuecomment-562218380
Add missing `null_mask` copy and corresponding test cases.
> [REVIEW] Fix unary_op null_mask bug and add missing test cases

- CHANGELOG.md
- python/cudf/cudf/tests/test_repr.py
CI issues recently cropped up with these hypothesis tests. Hypothesis will automatically timeout tests if they take too long. If a test times out in one generation, but not in another, hypothesis fails the test and calls it flaky.
This PR removes the deadline from the other hypothesis tests.
This could lead to longer run times for tests, or theoretically hung tests. One alternative is to set the deadline to 1000msec instead of None. This moves the goalpost but the same issue could arise again. Opinions?
> [HOTFIX][REVIEW] Remove deadline from two other hypothesis driven tests.

- CHANGELOG.md
- cpp/include/cudf/io/functions.hpp
- cpp/include/cudf/io/readers.hpp
- cpp/include/cudf/io/types.hpp
- cpp/include/cudf/io/writers.hpp
- cpp/src/io/avro/reader_impl.cu
- cpp/src/io/avro/reader_impl.hpp
- cpp/src/io/csv/reader_impl.cu
- cpp/src/io/csv/reader_impl.hpp
- cpp/src/io/functions.cpp
- cpp/src/io/orc/reader_impl.cu
- cpp/src/io/orc/reader_impl.hpp
- cpp/src/io/orc/writer_impl.cu
- cpp/src/io/orc/writer_impl.hpp
- cpp/src/io/parquet/reader_impl.cu
- cpp/src/io/parquet/reader_impl.hpp
- cpp/src/io/parquet/writer_impl.cu
- cpp/src/io/parquet/writer_impl.hpp
- cpp/tests/io/csv_test.cu
- cpp/tests/io/orc_test.cu
- cpp/tests/io/parquet_test.cu
Resolves #3522 
This change adds a table_metadata struct to pass in the column names and user metadata (see types.hpp).
For (future) nesting support, the ordering of names in the column_names vector is a pre-order traversal of the column tree. In the example below (2 top-level columns: struct column "col1" and string column "col2"), the column names would consist of 6 entries ordered as  `{"col1", "s3", "f5", "f6", "f4", "col2"}`.
```
col1     col2 
/ \ 
/   \ 
s3    f4 
/ \ 
/   \ 
f5    f6 
```
This is similar to the order described in the [ORC specification](https://orc.apache.org/specification/ORCv1/) with the root node removed (or considering the table as the root node with the top-level columns as children).
> [REVIEW] Add support for column names in libcudf++ io readers/writers

- CHANGELOG.md
- cpp/include/cudf/detail/utilities/hash_functions.cuh
- cpp/tests/hashing/hash_test.cpp
- cpp/tests/utilities/type_lists.hpp
Closes #3233 
Restructured the MurmurHash function to do traditional template specialization rather than SFINAE.  The SFINAE definitions were getting too complicated, this seems much simpler to me.
Added specialization for float and double.  Added unit tests for float and double checking 0.0, -0.0, NaN, -NaN and infinity to make sure they all work properly.
> [REVIEW] Specialize hash functions for floating point

- .github/CODEOWNERS
- CHANGELOG.md
In the middle of giving all repo's codeowners groups, OPS shouldn't be specific to any one repo, so its being renamed to avoid creating a bunch of new groups.
> [REVIEW] Update OPS codeowners group name [skip ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Closes #3634 
Currently, `dask_cudf` cannot handle the `sorted=True` argument for `set_index` operations, because it will end up trying to use `cudf.concat` on scalar values.  This is a simple fix, along with a test for `set_index(..., sorted=True)`.
> [REVIEW] Fix sorted set_index operations in dask_cudf

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/benchmarks/copying/contiguous_split_benchmark.cu
- cpp/include/cudf/copying.hpp
- cpp/include/cudf/detail/copy.hpp
- cpp/src/copying/contiguous_split.cu
- cpp/src/copying/slice.cpp
- cpp/src/copying/split.cpp
- cpp/tests/CMakeLists.txt
- cpp/tests/copying/slice_tests.cu
- cpp/tests/copying/slice_tests.cuh
- cpp/tests/copying/split_tests.cu
Implementation of contiguous_split() functionality.   Performs a deep-copying split operation on a table_view where the output is arranged in a memory-contiguous way per output table-view.  That is, each output table_view and all associated internal column_views share one contiguous chunk of allocated memory.  Thus, these various objects are not owned by top level tables or columns and have a special lifetime controlled by the returned contiguous_split_result objects.  
The basic algorithm is structured as:
```
for(each input column in a table){
split_table_subcolumns[i] = slice(in.column(i), splits);
}
for(each output table i){
contiguous_buf_size = 0;
for(each subcolumn j){
contiguous_buf_size += compute(split_table_columns[j][i]);
}
buf = alloc(contiguous_buf_size);
for(each subcolumn …
```
> [REVIEW] contiguous_split function.

- CHANGELOG.md
Update Jitify submodule reference to include a fix for GCC 8.
Related issue: https://github.com/rapidsai/cudf/issues/3613
Related PR: https://github.com/rapidsai/cudf/pull/3622
> [REVIEW] Update Jitify submodule ref to include gcc-8 fix

- CHANGELOG.md
- cpp/src/strings/find.cu
- cpp/tests/strings/find_tests.cu
Closes #3669 
Logic for ends-with incorrectly marks matching string as false.
> [REVIEW] Fix ends_with logic for matching string case

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Fix the loop in `.insert` so that it doesn't needlessly iterate over columns that won't be moved.
> [REVIEW] Improve DataFrame.insert performance for wide frames

- CHANGELOG.md
- cpp/src/io/csv/legacy/csv_writer.cu
Closes #3666 
The csv_writer C++ code crashes if passed a null columns vector. 
The assert test for this was after the first dereference causing the segfault.
Only minor changes are needed to support null columns parameter and create an empty file as consistent with Pandas to_csv.
I did not see a port of `csv_writer` to libcudf++ at this time.
If that code does exist somewhere, then I could port the fix to that code as well.
> [REVIEW] Allow for null columns parameter in csv_writer

- CHANGELOG.md
- build.sh
There should only be one cmake configure step in the build. Small fix with removing quotes on the benchmarks variable as well.
> [REVIEW] Remove multiple CMake configure steps in root build script

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda9.2.yml
- conda/recipes/cudf/meta.yaml
Closes issue #3715 
PR updates numba in conda recipes and developer environments to >0.46.0. Version 0.45 was causing the problem described in the issue above, discovered only in cuML developer environments that had 0.45.1 by default. CI containers already pull 0.46.
> [REVIEW] Update numba to 0.46 in conda files

- CHANGELOG.md
- python/cudf/cudf/_libxx/lib.pxd
Updates the "types.hpp" path in `libxx/lib.pxd` to unblock cuGraph CI builds (related: https://github.com/BradReesWork/cugraph/pull/1)
> [REVIEW] Update libxx cython types.hpp path

- CHANGELOG.md
- cpp/include/cudf/detail/merge.cuh
- cpp/src/merge/merge.cu
There is an extra type-dispatcher call in merge.cuh that is unnecessary.
Removing this extra call seems to fix an nvcc infinite compile for code changes in an unrelated PR.
Hoping this change will prevent possible future compile issues.
**Details**
The template Element argument defined here is not used.
https://github.com/rapidsai/cudf/blob/0659418df9adc233f222dc37726efc8bc4410490/cpp/include/cudf/detail/merge.cuh#L82
Therefore, the extra type-dispatch call here is not required:
https://github.com/rapidsai/cudf/blob/0659418df9adc233f222dc37726efc8bc4410490/cpp/include/cudf/detail/merge.cuh#L153
Also, in the process of debugging this, I found several unnecessary header file includes that can be removed as well.
> [REVIEW] Remove extra type-dispatcher call from merge

- CHANGELOG.md
- cpp/src/io/csv/csv_gpu.cu
- cpp/tests/io/csv_test.cu
Modify floating-point parsing in CSV reader to set the invalid elements to null:
* Modify the number parsing to detect invalid characters, instead of producing an incorrect result;
* Propagate the validity of the parsed number and use the value to set the validity bit to true only for valid floating-point numbers;
* Add a C++ test that checks the validity mask for different invalid floating point strings;
Fixes #3635
> CSV reader: Set invalid float values to NaN/null.

- CHANGELOG.md
- cpp/src/io/comp/io_uncomp.h
- cpp/src/io/comp/uncomp.cpp
Use size_t for the compressed file size instead of int32_t.
Issue #3379
> Fix segfault when reading compressed CSV files larger than 4GB

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_search.py
- python/cudf/cudf/tests/test_setitem.py
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Fixes #3735
Fixes #3779
Uses the newly added `Series._align_to_index` to align inputs to handle `__setitem__`, `assign`, and `insert` calls where the input is a pandas Series or a cudf Series that can differ in size from the dataframe.
> [REVIEW] Python changes to align index on input Series to setitem calls

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Fixes https://github.com/rapidsai/cudf/issues/3848
> [WIP] Fix merge typecast scope issue

- CHANGELOG.md
- python/cudf/cudf/core/groupby/legacy_groupby.py
This kernel contains what looks like extra enumeration logic that prevents it from producing the correct result when there is more than one thread per block. 
Fixes https://github.com/rapidsai/cudf/issues/3615
> Fix CUDA kernel logic in apply_grouped moving average example

- CHANGELOG.md
- cpp/custrings/strings/attrs.cu
The `NVStrings::byte_count()` member function returns `int64` by the internal calculation was truncating into an `int32` value. The code logic was modified to ensure the `int64` value is not truncated.
> [REVIEW] Fixed size calculation in NVStrings::byte_count()

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/core/multiindex.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Fixes https://github.com/rapidsai/cudf/issues/3784
This issue had two causes: We didn't properly handle `cupy.ndarray` as a boolean row-mask, and we didn't support use of `iloc[[]]` as a syntax for boolean row-mask. This PR corrects those issues.
> [REVIEW] Repair issue involving `split_out`

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
Fixes https://github.com/rapidsai/cudf/issues/3887
cc @kkraus14 @shwina @dantegd
> Drop `ptr=None` from `DeviceBuffer` call

- conda/recipes/cudf/meta.yaml
#3486 did not bump the conda recipe version
> [REVIEW] Update cudf meta for pandas version #3486 [skip-ci]

- CHANGELOG.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
- java/src/main/native/CMakeLists.txt
The new JNI has moved to libcudf++ and no longer uses NVCategory and NVStrings, but libcudf.so still links against those libraries for its legacy code and therefore they must be available in order for libcudf.so to successfully load.  This PR restores the code that places those two dependency libs in the cudf jar and dynamically loads them before attempting to load libcudf.so.
These two libraries can be removed from the jar and load table when libcudf.so stops dynamically linking against them.
> Restore legacy NVStrings and NVCategory dependencies in Java jar

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_multiindex.py
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
This PR addresses three fundamental issues:
1. libcudf++ refactor breaks MultiIndex flattening
Flattening MultiIndexes into a set of tuple column names used to work implicitly with Pandas approach. Using `_data` and `OrderedColumnDict`  in the refactor affected this implicit parallel.
2. Groupby column structure varies between `.agg({'a': 'count'})` and `.agg({'a': ['count']})`.
We have been returning a single column structure for both of the above cases - This worked with implicit column flattening #1 above, but now needs to be separated to work in dask.
3. Without implicit column flattening, `MultiIndex` needs to support a series of numpy `__array_function__` protocol functions to work in dask.
When columns were being flattened, protocol functions were being called on `list` instead of …
> [REVIEW] dask cudf groupby `.agg` multicolumn handling fix

- CHANGELOG.md
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/tests/test_sort.py
Closes #3873 (Although we do still want to improve general performance -- In progress)
This PR adds a small change to effectively "short circuit" the usual batcher-sortnet algorithm when there is only a single partition.
I also modified the behavior of `ignore_index`, because it seemed to be "incorrect" (however, I'm happy to revert this if I'm mistaken)
> Minor dask_cudf sort_values optimization for single partitions

- CHANGELOG.md
- cpp/src/bitmask/null_mask.cu
- cpp/tests/utilities/column_utilities.cu
- cpp/tests/utilities/column_utilities.hpp
- cpp/tests/utilities_tests/column_utilities_tests.cpp
The device_buffer being created for mask is bigger due to padding and kernel is not updating these padded bytes, so there are chances these bytes have some residual values. Which caused issue in one of the test cases. The test case has been updated to just check bits equivalent to number of elements.
> [REVIEW] Fix for copy_bitmask issue with uninitialized device_buffer

- CHANGELOG.md
- cpp/include/cudf/quantiles.hpp
- cpp/src/quantiles/quantiles.cu
- cpp/tests/quantiles/quantiles_test.cu
Related to #4011.
Changing `cudf::experimental::quantiles` name/signature in preparation for multi-column API to reduce confusion.
> quantiles: rename and adjust signature for clarity.

- CHANGELOG.md
- cpp/include/cudf/column/column.hpp
- cpp/include/cudf/datetime.hpp
- cpp/include/cudf/detail/copy_range.cuh
- cpp/include/cudf/detail/fill.hpp
- cpp/include/cudf/detail/repeat.hpp
- cpp/include/cudf/filling.hpp
- cpp/include/cudf/null_mask.hpp
- cpp/include/cudf/scalar/scalar.hpp
- cpp/src/bitmask/null_mask.cu
- cpp/src/column/column.cu
- cpp/src/copying/copy_range.cu
- cpp/src/datetime/datetime_ops.cu
- cpp/src/filling/fill.cu
- cpp/src/filling/legacy/tile.cu
- cpp/src/filling/repeat.cu
- cpp/src/hash/hash_allocator.cuh
- cpp/src/io/functions.cpp
- cpp/src/table/table.cpp
- cpp/tests/column/factories_test.cpp
- cpp/tests/scalar/factories_test.cpp
- cpp/tests/utilities/base_fixture.hpp
Corresponds to https://github.com/rapidsai/rmm/pull/262
> Update RMM include files

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Add JNI bindings and java api for is_nan and is_not_nan. Currently needs the compile fix per : https://github.com/rapidsai/cudf/pull/4037 to compile and test.
> [REVIEW] JNI and Java support for is_nan and is_not_nan

- cpp/custrings/doxygen/Doxyfile
- cpp/doxygen/Doxyfile
This should be updated with each release. This results in the doxygen files showing the wrong version for the correct release.
> Correct doxygen version [skip-ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/DType.java
Quick fix for when DICTIONARY32 type went in.
> Fixed mismatch with dtype enums again

- CHANGELOG.md
- java/pom.xml
This makes it so that the classifier comes from the cuda version without hard coded mapping rules.
> [REVIEW] Improve how java classifiers are produced

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/DType.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/ScalarTest.java
Fixing the Java build that was still referencing the recently removed CATEGORY data type.
> Update Java bindings to reflect removal of CATEGORY data type

- CHANGELOG.md
- cpp/src/round_robin/round_robin.cu
- cpp/tests/round_robin/round_robin_test.cpp
Currently `round_robin_partition` explicitly checks for and prevents partitioning to a single partition.  While this is a degenerate partitioning that is equivalent to copying the input table, the code does perform this degenerate partitioning correctly.
Removing this restriction can simplify calling code that would otherwise need to check for this degenerate case and reference-count the input or perform a separate copy instead.
> Allow round_robin_partition to single partition

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
- java/src/main/native/src/ColumnVectorJni.cpp
Passing a one byte data buffer for all null strings case can cause corruption given that the cudf layer can handle null data buffers. This PR address this issue by letting the buffer be null if there is no data.
> [REVIEW] All null string entries should have null data buffer

- CHANGELOG.md
- python/dask_cudf/dask_cudf/tests/test_groupby.py
This PR sets `npartitions=2` to cover the multi-partition codepath in `test_groupby_multiindex_reset_index`.
Apparently black also made a tiny change to a comma.
> [REVIEW] Use two partitions in test_groupby_multiindex_reset_index

- CHANGELOG.md
- cpp/include/cudf/strings/copying.hpp
- cpp/src/strings/copying/copying.cu
- cpp/src/strings/sorting/sorting.cu
- cpp/src/strings/strings_column_factories.cu
- cpp/src/strings/utilities.cuh
- cpp/tests/strings/array_tests.cu
Before starting on #4050 
When porting NVStrings to libcudf++, some needed cudf functions had not yet been ported.
Early ported code relied on legacy `valid_if` function and needed to be moved to the newer `valid_if` libcudf++ ported version.
Also, now that cudf `gather` and `scatter` support strings columns, the strings-only versions of these API can be removed. This will ripple into fixing up other code (e.g. slice) and some test code.
> [REVIEW] Remove legacy calls from libcudf strings column code

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
- python/cudf/cudf/core/buffer.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
This is a combination and simplification of the approaches in PR ( https://github.com/rapidsai/cudf/pull/4023 ) and PR ( https://github.com/rapidsai/cudf/pull/4077 ). Though it's worth noting the former remains valuable beyond this context.
Namely this PR adds `__cuda_array_interface__` to the `Buffer` class. Also it adds serialization methods that leverage this for direct `Buffer` serialization. This is then leveraged by other cuDF serialization methods to allow `Buffer`s to ship themselves as frames. This all thanks to Distributed and ucx-py's ability to leverage `__cuda_array_interface__` when shipping objects over the wire. Should cut out some overhead added by building Numba representations of `Buffer`s, which is now no longer needed.
> Redux serialize `Buffer` directly with `__cuda_array_interface__`

- CHANGELOG.md
- cpp/include/cudf/strings/detail/gather.cuh
- cpp/src/join/join.cu
- cpp/tests/join/join_tests.cu
This PR implements a fix to joins that allows for input parameter `column_in_common` to be empty. The fix is simply copied from PR #4044 from brandon-b-miller. I believe that PR #4044 will also be containing a lot more for the python side, but having this fix would help resolves #3974 faster.
> [REVIEW] implemented fix for joins for column_in_common is empty

- CHANGELOG.md
- cpp/src/copying/contiguous_split.cu
- cpp/src/io/json/reader_impl.hpp
- cpp/src/strings/copying/copying.cu
- cpp/src/strings/sorting/sorting.cu
While working with `contiguous_split`, I noticed in the Nsight traces that `cudaMalloc` and `cudaFree` were being called quite a bit by this function.  Digging into the code, I saw `thrust::device_vector` being used instead of `rmm::device_vector`.  That bypasses RMM and loses the performance benefit of memory pooling.
This PR updates places in non-test code to use `rmm::device_vector` instead of `thrust::device_vector`.
> Use rmm::device_vector instead of thrust::device_vector

- CHANGELOG.md
- cpp/src/hash/hashing.cu
This PR is a quick change based on PR #3808 
- Change threshold for using optimized hash partition code (based on shared memory output cache + cub block scan #3808) from 512 partitions to 1024 partitions 
- Tested on V100, seeing up to 2X speedup on 1024-partition cases
@harrism @trevorsm7 
```
Before using optimized code for 1024 partitions: 
Benchmark                                                    Time             CPU   Iterations
Hashing/hash_partition/131072/1/1024/manual_time         0.238 ms        0.261 ms         2919
Hashing/hash_partition/262144/1/1024/manual_time         0.293 ms        0.317 ms         2365
Hashing/hash_partition/524288/1/1024/manual_time         0.406 ms        0.430 ms         1720
Hashing/hash_partition/1048576/1/1024/manual_time        0.641 ms …
```
> [REVIEW] Change threshold of optimized code for hash partition

- CHANGELOG.md
- cpp/src/strings/copying/concatenate.cu
- cpp/tests/table/table_tests.cpp
The `strings::detail::concatenate(columns)` code error causes invalid-argument in `cudaMemcpy` call.
Closes #4055 
Problems found in the code logic:
- The computed size of the output column is larger than needed.
- The offset adjustment logic was computing incorrect values.
- Typo in the child column `data<>()` call.
The last one specifically produced the invalid argument error but was sometimes hidden because of the first error.
> [REVIEW] Fix strings concatenate logic with column offsets

- CHANGELOG.md
- cpp/src/copying/contiguous_split.cu
- cpp/tests/copying/split_tests.cu
Fixes #4114
Tables with mixed column types including strings could cause some internal indexing issues that resulted in corrupted output/split columns.   Core issue was a thrust::transform() that was storing offset values in an output array just pushing the elements on to the end instead of respecting their expected column indices.
> [REVIEW] Fixed a bug in contiguous_split() involving tables of mixed types.

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
It turns out we already have the information needed to determine the number of strings stored without needing to call the `nvstrings` API. So extract this information from the offset `Buffer` instead.
cc @kkraus14
> Get `len` of `StringColumn`s without `nvstrings`

- CHANGELOG.md
- cpp/src/binaryop/binaryop.cpp
- cpp/src/rolling/rolling.cu
- cpp/src/transform/transform.cpp
Fixes #3659 
Uses new jitify option `-remove-unused-globals` to remove unnecessary unused globals that were introduced into RAPIDS PTX when including libcu++ headers. This should solve the performance regression in #3659. 
Depends on NVIDIA/jitify#40 (merged), and rapidsai/jitify#7 (which merges the former into rapidsai fork of jitify). This PR updates the libcudf jitify submodule.
> [REVIEW] Use jitify -remove-unused-globals to fix binops slowdown.

- CHANGELOG.md
- cpp/include/cudf/filling.hpp
- cpp/src/filling/fill.cu
- cpp/tests/filling/fill_tests.cu
Fixes #4112
Renames in-place `fill` to `fill_in_place`
> [REVIEW] Rename in-place fill to fill_in_place

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This fixes two issues in the Java bindings:
- libcudf's mutating `fill` is now `fill_in_place`.
- rolling window aggregations for SUM on INT32 now return INT64 and MEAN returns FLOAT64.
The former is a simple change in the JNI code to call the correct method, and the latter is a straightforward update to the unit tests to expect the new result types.
> Update Java for mutating fill and rolling window changes

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Fix an edge case where no index names are passed to `DataFrame._from_unique_ptr` which propagates a `None` index to `DataFrame._from_table`.
> [REVIEW] Support empty index case in DataFrame._from_table

- CHANGELOG.md
- cpp/custrings/tests/test_convert.cu
- python/nvstrings/tests/test_convert.py
The `test_convert` module was using `EXPECT_EQ` for checking float and double values.
Changed the code to use `EXPECT_NEAR` instead.
> [REVIEW] Fix NVStrings test_convert failure in 10.2 build

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
In the event that serializing CUDA objects directly is not possible, this performs the next best thing, which is to serialize objects using Dask's serialization protocol. The protocol requires that data be on the host in 1-D contiguous `memoryviews`. So we perform serialization as we otherwise would. As a last step we perform a device-to-host transfer of the frames. Then we hand this off to Dask to serialize. When deserializing the data, all of the deserializers already work as frames are turned into `Buffer`s, which perform a host-to-device transfer if needed. This provides us an option that avoids pickling. As a result we are able to serialize things with Dask more efficiently using this protocol.
> Add Dask serializers for cuDF objects

- CHANGELOG.md
- cpp/src/table/table.cpp
- cpp/tests/merge/merge_test.cpp
- cpp/tests/table/table_tests.cpp
constructor was not updating number of rows while creating table from table_view which created the issue.
close #4152
> [REVIEW] Fix merge issue with empty table return if one of the two tables are empty

- CHANGELOG.md
- cpp/include/cudf/copying.hpp
- cpp/include/cudf/detail/copy_range.cuh
- cpp/src/copying/copy_range.cu
- cpp/tests/copying/copy_range_tests.cpp
Related to #4112 
Renames in-place `copy_range` to `copy_range_in_place`
> [REVIEW] Rename in-place copy_range to copy_range_in_place

- CHANGELOG.md
- cpp/src/strings/copying/concatenate.cu
- cpp/tests/table/table_tests.cpp
Another use case in #4055 uncovered calculation error when concatenating strings columns with offsets. The child column sizes were being used incorrectly.
Additional tests have been handled to cover more combinations of column_view offsets/sizes.
This PR also includes replacing the CPU for-loop with parallel CUDA kernel to help minimize the number of values (specific offset entries in child columns) copied from device to host.
Closes #4055
> [REVIEW] Really fix the bug in strings concatenate with offsets

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
Previously this was being `assert`ed in the Dask serializers. However we want to make sure we are passing `Buffer`s and not constructing other objects (like Numba's `DeviceNDArrays`) in CUDA serializers as well. So go ahead and move this to CUDA serializers where it still also affects Dask serializers.
> Assert Dask CUDA serializers have `Buffer` frames

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
Part of `Buffer`'s serializers' work includes handling subclasses (like cuML's `Array`). However it doesn't handle any keyword arguments those subclass constructors may need. This changes that by adding an optional (by default trivial) "constructor-kwargs" header. Subclasses can then call their parents' serializer and pack this header with relevant content afterwards. This way during deserialization this content can be passed into the subclass' constructor.
cc @dantegd
> Add Buffer "constructor-kwargs" header

- CHANGELOG.md
- cpp/include/cudf/detail/copy_if.cuh
- cpp/include/cudf/detail/gather.cuh
- cpp/include/cudf/detail/scatter.cuh
- cpp/include/cudf/strings/detail/gather.cuh
- cpp/src/copying/gather.cu
- cpp/src/filling/repeat.cu
- cpp/src/groupby/sort/sort_helper.cu
- cpp/src/hash/hashing.cu
- cpp/src/join/join.cu
- cpp/src/join/semi_join.cu
- cpp/src/quantiles/quantiles.cu
- cpp/src/reshape/tile.cu
- cpp/src/round_robin/round_robin.cu
- cpp/tests/copying/gather_tests.cu
- cpp/tests/hashing/hash_partition_test.cpp
Closes https://github.com/rapidsai/cudf/issues/4103
Closes https://github.com/rapidsai/cudf/issues/4120
The `hash_partition` optimization in PR https://github.com/rapidsai/cudf/pull/3748 included a fallback for non-fixed-width columns using `column_gatherer`. When the source column contains a null mask, `column_gatherer` would allocate a mask for the output and leave it in uninitialized state. However, hash_partition only computes the null mask if the source actually contains nulls. This resulted in a bug where an input strings column with all-valid null mask would produce an output column with an uninitialized/all-nulls mask.
I added unit tests for the above case and refactored the null mask allocation outside of `column_gatherer`.
> [REVIEW] Fix hash partition null mask allocation

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
Fixes #4173
When a string column is empty, it does not have `self.base_children` so just I'm just adding a check against that case.
> Fix __sizeof__ calculation in string column

- CHANGELOG.md
- cpp/src/copying/contiguous_split.cu
- cpp/tests/copying/split_tests.cu
- cpp/tests/utilities/table_utilities.cu
- cpp/tests/utilities/table_utilities.hpp
contiguous_split() had a small hack in it to get around an issue with slice().  Slice was returning UNKNOWN_NULL_COUNT for all sliced columns.  This caused computation of that number silently within contiguous_split() which caused performance issues because of the scale contiguous_split runs at (ten of thousands or more columns).  
slice() has been changed to produce proper null counts (https://github.com/rapidsai/cudf/issues/3600) so the hack is no longer necessary.
> [REVIEW] Remove UNKNOWN_NULL_COUNT workaround from contiguous_split()

- CHANGELOG.md
- build.sh
- ci/gpu/build.sh
This PR runs Google Test executables directly instead of using `make`. This is to increase the output for developers when running tests.
> [REVIEW] Update Google Test Execution

- CHANGELOG.md
- python/cudf/cudf/_libxx/__init__.py
- python/cudf/cudf/_libxx/includes/sort.pxd
- python/cudf/cudf/_libxx/lib.pxd
- python/cudf/cudf/_libxx/sort.pyx
- python/cudf/cudf/core/_sort.py
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/dataframe.py
<!--
Thank you for contributing to cuDF :)
Here are some guidelines to help the review process go smoothly.
1. Please write a description in this text box of the changes that are being
made.
2. Please ensure that you have written units tests for the changes made/features
added.
3. There are CI checks in place to enforce that committed code follows our style
and syntax standards. Please see our contribution guide in `CONTRIBUTING.MD`
in the project root for more information about the checks we perform and how
you can run them locally.
4. If you are closing an issue please use one of the automatic closing words as
noted here: https://help.github.com/articles/closing-issues-using-keywords/
5. If your pull request is not ready for review but you want to make use of the
continuous integration …
> [REVIEW] Porting sort.pyx to use new libcudf APIs

- CHANGELOG.md
- build.sh
- python/cudf/setup.py
Filing this WIP PR to test optionally cythonizing in parallel.
In testing it seems cythonize's `nthreads` argument controls the Cython -> C++ pre-processing, so reading this from a `PARALLEL_LEVEL` env variable is a nice boost to cython re-compile times.
<details>
<summary>Click to see <code>setup.py build_ext --inplace -j22</code> output from a clean-build</summary><pre>
$ build-cudf-python 
Compiling cudf/_lib/arrow/_cuda.pyx because it changed.
Compiling cudf/_lib/avro.pyx because it changed.
Compiling cudf/_lib/binops.pyx because it changed.
Compiling cudf/_lib/concat.pyx because it changed.
Compiling cudf/_lib/copying.pyx because it changed.
Compiling cudf/_lib/csv.pyx because it changed.
Compiling cudf/_lib/cudf.pyx because it changed.
Compiling cudf/_lib/dlpack.pyx because it …
> [REVIEW] Cythonize in parallel

- CHANGELOG.md
- cpp/src/strings/copying/concatenate.cu
Some details in #4202 on the regression.
In the process of fixing the offsets/size calculation errors in `strings::detail::concatenate` the CPU for-loop over the table-view columns was replaced with a `thrust::for_each` to process each column in parallel. Each column thread would copy their section of offsets and chars to the output memory blocks. Using `thrust::transform` and `thrust::copy` and even `memcpy` inside the kernel was much slower than doing cudaMemcpy on each section in the CPU for-loop.
This PR reverts the code to reinstate the original for-loop but also fix the offsets/size calculations.
Closes #4202
> [REVIEW] Fix performance regression in strings::detail::concatenate

- CHANGELOG.md
- cpp/src/strings/convert/convert_datetime.cu
- cpp/tests/strings/datetime_tests.cu
Details in #4160 
Closes #4160 
The %p and %I specifiers for 12-hour format not handling midnight correctly.
Also, the %z was specified as supported but did not produce any output.
This PR to add tests for all supported specifiers for `from_timestamps` as well as `to_timestamps`
> [REVIEW] Fix from_timestamps 12-hour specifiers

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
Add `BUILD_LEGACY_TESTS` cmake option to enable/disable building the legacy C++ tests.
This flag is opt-in, and will skip building/linking any C++ test of the pattern `LEGACY_<name>_TEST`. 
This makes libcudf rebuild times are improved if you don't need to build the legacy tests. This commit cherry-picked from https://github.com/rapidsai/cudf/pull/4223.
> [REVIEW] Add BUILD_LEGACY_TESTS cmake option

- CHANGELOG.md
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Fixes #4252 
We can just use mainline Dask code here now 😄
Also added a unit test for String index name alignment as I initially thought it could be that, but I was mistaken.
> [REVIEW] Fix losing index name in dask-cudf `reset_index`

- CHANGELOG.md
- python/cudf/cudf/utils/ioutils.py
This Pr updates the logic used to check if the filesystem being used while reading is local or not.
1. Previous implementation checked if the `protocol` was `file` based on the information here: https://github.com/intake/filesystem_spec/blob/master/fsspec/registry.py
2. When using cudf or dask (not distributed) this is not an issue since all fs objects being checked have `protocol="file"`.
3. In dask distributed setting, the fs being passed down is of the type `fsspec.implementations.local.LocalFileSystem` but has `protocol="abstract"` which is the default protocol of it's parent class. (Not sure why the protocol name is lost in the distributed setting).
Due to the points mentioned above the `local_filesystem` check was failing in a distributed setting and cudf was going via the `BytesIO` …
> [REVIEW] Update _is_local_filesystem logic

- CHANGELOG.md
- cpp/include/cudf/binaryop.hpp
- cpp/src/binaryop/jit/code/operation.cpp
- cpp/src/binaryop/jit/util.hpp
- cpp/tests/binaryop/binop-integration-test.cpp
- cpp/tests/binaryop/util/operation.h
Closes  https://github.com/rapidsai/cudf/issues/3791
Note : ShiftRightUnsigned is the closest C++ equivalent to Java's  >>>
> [REVIEW] Add ShiftLeft (<<), ShiftRight (>>) and ShiftRightUnsigned (>>>) binops.

- CHANGELOG.md
- python/cudf/cudf/core/_sort.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_string.py
- python/cudf/cudf/utils/utils.py
Related to #4334 
Moved as much of the nvstrings related code to use StringColumns directly. There's a couple notable gaps surrounding `concat` and `__getitem__` related things that can hopefully be tackled as we port `copying.pyx` and `concat.pyx`.
> [REVIEW] Move a bunch of internal nvstrings code to use native StringColumns

- CHANGELOG.md
- cpp/include/cudf/io/writers.hpp
- cpp/src/io/functions.cpp
- cpp/src/io/parquet/parquet.h
`/include/io/writers.hpp` was including `/src/cudf/io/parquet/parquet.h` to get at types needed for the `pq_chunked_state struct`.  Since this struct itself is intended to be anonymous, it can be buried further down in the parquet writer code (`/src/cudf/io/parquet/parquet.h`), removing the bad include.
> [REVIEW] Removed bogus backwards include in cuIO code.

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/java/ai/rapids/cudf/RmmEventHandler.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/CudfJni.cpp
- java/src/main/native/src/RmmJni.cpp
- java/src/test/java/ai/rapids/cudf/RmmTest.java
This adds the ability for the Java RMM event handler to be called when total allocation thresholds are crossed during allocation and deallocation.  Calling back into the JVM from native code is relatively expensive.  This provides a way for a Java application to be informed when certain RMM memory thresholds are crossed without resorting to calling Java on every RMM allocation and deallocation.
> Add memory threshold callbacks for Java RMM event handler [skip ci]

- CHANGELOG.md
- cpp/src/strings/combine.cu
- cpp/tests/strings/combine_tests.cu
Closes #4349 
This is similar to #4307 where the empty string parameter was being incorrectly interpreted as a null string. This caused the result where nulls were not being properly replaced during the concat.
The logic has been fixed for this. Also, some of the logic was updated to use the more current libcudf++ style.
Also added a test case for empty string narep.
> [REVIEW] Fix strings::concat when narep parameter is an empty string

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/sequence.hpp
- cpp/include/cudf/filling.hpp
- cpp/src/filling/sequence.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/filling/sequence_tests.cpp
- cpp/tests/filling/sequence_tests.cu
Closes https://github.com/rapidsai/cudf/issues/4325
Generate a column of values based on input numeric scalars specifying an initial value and a step.
Only issue worth calling out with the PR is in sequence.cu.   In the type dispatched functor that ultimately calls thrust,  instead of using a lambda I'm using an external functor (tabulator).  The reason for this is an obscure link error that comes up from time to time when using type dispatched functors that utilize SFINAE :  device lambdas (possibly any lambda) will sometimes cause the error.  The only way around it is to use an external functor.   For another example, see : ```normalize_nans_and_zeros_lambda``` in replace.cu
> [REVIEW] Add cudf::sequence() for generating a column of incrementing values.

- CHANGELOG.md
- cpp/tests/copying/legacy/scalar_scatter_tests.cu
Since the legacy tests will be deleted soon, disabling these intermittently failing legacy tests.
> [REVIEW] Disable ScatterValid and ScatterNull legacy tests due to recent failures

- CHANGELOG.md
- python/cudf/cudf/_libxx/merge.pyx
- python/cudf/cudf/tests/test_reshape.py
libucdf++ follows the following rule,
```
Ascending, null_order::AFTER
1, 2, 3, NULL
Descending, null_order::AFTER
NULL, 3, 2, 1
Ascending, null_order::BEFORE
NULL, 1, 2, 3
Descending, null_order::BEFORE
3, 2, 1, NULL
```
and python/cython had to handle situation where `ascending=False` to reverse na_postion from "first" to "last" and vice-versa. 
closes #4246
> [REVIEW] Fix sorted merge issue with null values and ascending=False

- CHANGELOG.md
- cpp/include/cudf/scalar/scalar.hpp
Ensures derived class destructors get called in all circumstances.
Closes https://github.com/rapidsai/cudf/issues/4396
> [REVIEW] Make scalar destructor virtual.

- CHANGELOG.md
- cpp/src/strings/combine.cu
- cpp/tests/strings/combine_tests.cu
The `join_strings()` function returns a column with a single string concatenating all the strings from the input column. In the case where all the strings in the input column are null, the logic was incorrectly setting the null-mask for the output column.
Added several tests for this case as well.
Closes #4395
> [REVIEW] Fix join_strings logic with all-null strings and non-null narep

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
Fixes https://github.com/rapidsai/cudf/issues/4421
Adds a few checks around serialization. Some of these are safe-guards. Some of these will raise errors to catch problematic behavior we have seen. Hopefully this will make sure we are getting top-performance when serializing. Also should make it easier to catch the cases where we are not.
cc @cjnolet (who raised this point offline)
cc @dantegd (for awareness)
> Tighten up Dask serialization checks

- CHANGELOG.md
- python/cudf/cudf/_libxx/cpp/strings/contains.pxd
- python/cudf/cudf/_libxx/cpp/strings/find.pxd
- python/cudf/cudf/_libxx/cpp/strings/find_multiple.pxd
- python/cudf/cudf/_libxx/strings/char_types.pyx
- python/cudf/cudf/_libxx/strings/contains.pyx
- python/cudf/cudf/_libxx/strings/find.pyx
- python/cudf/cudf/_libxx/strings/find_multiple.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
This resolves: #3990 
Ported
~~- [ ] `nvstrings.nvstrings.match_strings` --> `Series.str.match` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.match.html#pandas.Series.str.match)~~ **Not porting this, as `match_strings` isn't implemented.**
> [REVIEW] Port nvstrings (Sub)string Comparisons functions to cuDF Python/Cython

- CHANGELOG.md
- cpp/src/strings/combine.cu
- cpp/tests/strings/combine_tests.cu
This is a fix currently in 0.14 in #4402 that needs to be back ported to 0.13.
The join_strings() function returns a column with a single string concatenating all the strings from the input column. In the case where all the strings in the input column are null, the logic was incorrectly setting the null-mask for the output column.
Added several tests for this case as well.
> [REVIEW] Fix join_strings logic with all-null strings and non-null narep -- back port PR4402

- CHANGELOG.md
- cpp/CMakeLists.txt
The previous `USE_NVTX` cmake configuration was based on the old libcudf NVTX APIs that would completely avoid the need to link `libnvToolsExt` into the library. That wasn't the best way to do things. Now that https://github.com/rapidsai/cudf/pull/4304  was merged, using `USE_NVTX=OFF` will break builds. 
Instead, we should always link `libnvToolsExt` and instead make use of the `DISABLE_NVTX` macro to make calls to NVTX APIs be no-ops.
> [REVIEW] Change NVTX to always be linked.

- CHANGELOG.md
- cpp/include/cudf/scalar/scalar.hpp
- cpp/include/cudf/scalar/scalar_device_view.cuh
- cpp/tests/binaryop/binop-integration-test.cpp
Reference #4477 
The `string_scalar` and `string_scalar_device_view` both create `string_view` instances from their `_data` and `_size` elements. Unfortunately, when these are created with empty strings the `_data` member variable is nullptr. When this is used to create the `string_view` it identifies the string as a null-string instead of an empty string.
This means that comparing empty strings from a strings column for example with a `string_view` created from an empty `string_scalar` will not match since `null != empty`.
This PR fixes the `value()` method for `string_scalar` and `string_scalar_device_view` to return the correct `string_view` for a valid, empty string.
Also, added binary-operation test for the EQUAL operator for this case as described in #4477
> [REVIEW] Fix string_scalar.value to return an empty string_view for empty string-scalar

- CHANGELOG.md
- java/src/main/native/src/RmmJni.cpp
RMM 0.13 added a new `supports_get_mem_info` API for `device_memory_resource`.  This updates the Java RMM event handler resource wrapper to fix the JNI build.
> Update Java memory resource handler for new supports_get_mem_info API [skip ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/tests/test_distributed.py
PR skips tests which requires 2+ GPUs
cc @dillon-cullinan
> skip-multi-gpu-test

- CHANGELOG.md
- build.sh
- ci/gpu/build.sh
Add an option to build legacy tests in root `build.sh`. Default behavior for CI is to skip legacy testing completely.
> [REVIEW] Optionally build legacy tests

- CHANGELOG.md
- cpp/include/cudf/scalar/scalar.hpp
The scalar destructor fix in #4399 is crucial to avoiding device memory fragmentation, but that PR was merged only into 0.14.  This backports the fix to branch-0.13.
> Backport scalar destructor fix

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/HostBufferConsumer.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/java/ai/rapids/cudf/TableWriter.java
- java/src/main/java/ai/rapids/cudf/WriterOptions.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/CudfJni.cpp
- java/src/main/native/src/RmmJni.cpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Adds in support so when writing to Parquet or Orc we can do it one table at a time, instead of all at once.  It also lets us write the data into a memory buffer instead of a local file.
> [REVIEW] Adds in support for chunked writers to java [skip-ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/accessor.py
- python/dask_cudf/dask_cudf/core.py
`cytoolz` has some more performant implementations of the same things in `toolz`. By importing `tlz` instead of `toolz`, we will pick up the `cytoolz` implementations when they are available. Otherwise we fallback to the `toolz` implementations.
> Import `tlz` for optional `cytoolz` support

- CHANGELOG.md
- cpp/CMakeLists.txt
- python/nvstrings/cpp/CMakeLists.txt
In anticipation of https://github.com/rapidsai/rmm/pull/331, disables warnings as errors from deprecation warnings.
> [REVIEW] Disable errors from deprecation warnings.

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
Slight tweak to the checks added in PR ( https://github.com/rapidsai/cudf/pull/4423 ).
> Use `elif` in Dask deserialize check

- CHANGELOG.md
- cpp/CMakeLists.txt
After https://github.com/rapidsai/rmm/pull/331, builds are kind of noisy with deprecation warnings. While this is intentional to motivate removing the use of deprecated APIs, it does make it difficult to diagnose other compiler errors when stdout is flooded with deprecation warnings.
This PR adds an option (disabled by default) to hide the deprecation warnings.
> [REVIEW] Add CMake option to disable deprecation warnings

- CHANGELOG.md
- java/src/main/native/CMakeLists.txt
Disabled compilation failures on JNI native code, for deprecation warnings.
E.g.
```
../src/strings/utilities.cuh:82:48:   required from ‘auto cudf::strings::detail::make_strings_children(SizeAndExecuteFunction, cudf::size_type, cudf::size_type, rmm::mr::device_memory_resource*, cudaStream_t) [with SizeAndExecuteFunction = cudf::strings::detail::_GLOBAL__N__56_tmpxft_00006cba_00000000_8_backref_re_compute_75_cpp1_ii_c02a6011::backrefs_fn<112>; cudf::size_type = int; cudaStream_t = CUstream_st*]’
../src/strings/replace/backref_re.cu:205:173:   required from here
/home/mithunr/workspace/anaconda2/envs/cudf_dev/include/rmm/thrust_rmm_allocator.h:61:10: warning: ‘rmmError_t rmm::free(void*, cudaStream_t, const char*, unsigned int)’ is deprecated [-Wdeprecated-declarations] …
```
> Disable compile-errors on deprecation warnings, for JNI [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Scalar.java
The Scalar class in the Java bindings has native methods but was not ensuring the native dependencies were loaded before calling those methods.  This adds a static block to the class to make sure the native dependencies are loaded when the Scalar class is loaded.
> Load JNI native dependencies for Scalar class [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
Instead of converting the data to arrow in `__reduce__`, simply follow the same pattern we are using serialize. This should allow for a pretty efficient pickling method when pickling of `StringColumn`s is required.
> Optimize `__reduce__` in `StringColumn`

- CHANGELOG.md
- CONTRIBUTING.md
Add a note that `channel_priority` should be disabled when creating conda environment from the yml file. Otherwise will get package conflicts.
> [REVIEW] Add doc note on conda channel_priority

- CHANGELOG.md
- cpp/tests/utilities/base_fixture.hpp
Cut down on some of the warnings after https://github.com/rapidsai/rmm/pull/331 by removing the deprecated init/finalize in the cudf test fixture.
> [WIP] Remove RMM init/finalize from cudf test fixture.

- CHANGELOG.md
- python/dask_cudf/dask_cudf/sorting.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Closes [#4621](https://github.com/rapidsai/cudf/issues/4621)
Small fix to make sure we generate a dask_cudf DataFrame object as the output to `rearrange_by_hash` (rather than a dask.dataframe object).  I also made some small changes to `test_repartition_hash_staged` to assert that the type is correct (and to make it run a bit faster).
> [Bugfix] Fix hash-based repartitionbug in dask_cudf

- CHANGELOG.md
- cpp/tests/stream_compaction/legacy/drop_duplicates_tests.cu
Fixes segfault in CI testing for legacy tests. 
CC @raydouglass
> [REVIEW] Remove dangling pointer to RMM exec policy in drop duplicates test

- CHANGELOG.md
- cpp/src/copying/concatenate.cu
- cpp/tests/copying/concatenate_tests.cu
Closes https://github.com/rapidsai/cudf/issues/4629
- Throw if no columns were passed to concatenate
- Return empty column if all columns to concat are empty
> [REVIEW] Fix handling of empty inputs for concatenate

- CHANGELOG.md
- cpp/benchmarks/hashing/hashing_benchmark.cpp
- cpp/include/cudf/partitioning.hpp
The hashing benchmark is failing to build on branch-0.14 because the table.hpp header doesn't get included with partition.hpp.
> [REVIEW] Fix missing include in partition header

- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Changes the string column concatenate function to use an array of strings rather than a variable number of arguments reinterpreted as an array. The translation of the Java variable arguments does not play well with the Scala plugin side.
> Change stringConcatenate to use array argument [skip ci]

- CHANGELOG.md
- cpp/src/strings/regex/regexec.cu
- cpp/tests/strings/contains_tests.cpp
Closes #4636 
The regex pattern is converted into an set of structs and then copied into a single buffer of device memory. This means the structs must be aligned correctly in the memory in order to deference them in device code.
The "[a-z]*" pattern created a circumstance where the reclass struct was copied into a misaligned section of the device buffer. This PR adds logic to ensure each section of structs are copied to an aligned location.
Also added a test case for this pattern.
> [REVIEW] Fix misaligned error when computing regex device structs

- CHANGELOG.md
- python/cudf/cudf/tests/test_repr.py
Fixes #4677 
The tests were generating a column name index backed by a `RangeIndex` which is something cudf just doesn't support for column names. Pandas seems to actually format these differently which then causes failures since when cuDF converts to Pandas for printing it materializes the column names into an `Int64Index`.
> [REVIEW] Fix `test_repr` tests that generated RangeIndex column names

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
As going through `"dask"` serialization can result in data being split for better compression, ensure the original number of bytes in the frame is stored in `header["lengths"]`. That way on `"dask"` deserialization the frames can be merged back into their original sizes before `"cuda"` serialization is performed.
> Include frame lengths in Dask serialized header

- CHANGELOG.md
- cpp/include/cudf/column/column_factories.hpp
- cpp/include/cudf/dictionary/dictionary_column_view.hpp
- cpp/include/cudf/dictionary/dictionary_factories.hpp
- cpp/include/cudf/dictionary/encode.hpp
- cpp/include/cudf/strings/attributes.hpp
- cpp/include/cudf/strings/convert/convert_booleans.hpp
- cpp/include/cudf/strings/convert/convert_floats.hpp
- cpp/include/cudf/strings/convert/convert_integers.hpp
- cpp/include/cudf/strings/convert/convert_ipv4.hpp
- cpp/include/cudf/strings/padding.hpp
Closes #4658 
Comment about the null-mask was on the wrong on both dictionary factory functions.
Also corrected some doxygen warnings and added comment to `strings` and `dictionary` namespaces so they appear nicely in the generated docs.
> [REVIEW] Fix comments for make_dictionary_column factory functions

- CHANGELOG.md
- cpp/CMakeLists.txt
Fix compiler argument syntax in `CMakeLists.txt` that cause ccache to throw preprocessor errors.
Here's the difference in compile times using ccache (more in [this gist](https://gist.github.com/trxcllnt/498c215de31d99ca277322961f3887bd)):
libcudf C++ | Cold cache  | Warm cache
------------|-------------|-----------
real        | 13m6.068s   | 0m7.502s
user        | 158m33.972s | 0m38.947s
sys         | 8m30.461s   | 0m27.859s
cudf Cython | Cold cache | Warm cache
------------|------------|-----------
real        | 1m4.233s   | 0m15.507s
user        | 19m19.318s | 4m10.264s
sys         | 1m1.963s   | 0m12.706s
> [REVIEW] Fix compiler argument syntax for ccache

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/BaseDeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBufferView.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
This PR exposes `MemoryBuffer` and `MemoryBuffer.slice`, so that it is easier for callers to work with `MemoryBuffer` as opposed to specializing everything for `HostMemoryBuffer`, `DeviceMemoryBuffer`, etc.
> [REVIEW] Make MemoryBuffer public, and add MemoryBuffer.slice [skip-ci]

- CHANGELOG.md
- python/cudf/cudf/_libxx/column.pyx
- python/cudf/cudf/_libxx/transpose.pyx
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/tests/test_categorical.py
- python/dask_cudf/dask_cudf/io/parquet.py
call to codes materializes the column and gets a new column without any offset which resulted in the issue #4678 
closes #4678
> [REVIEW] Fix Slicing issue with categorical column in DataFrame

- CHANGELOG.md
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
This fixes a couple of columns that can be leaked in a unit test.  These leaks can cause issues if later unit tests in the same JVM process reinitializes RMM, invalidating the memory resource allocators associated with the columns that were leaked.
> Fix column leaks in Java unit test [skip ci]

- CHANGELOG.md
- cpp/src/strings/regex/regex.cuh
- cpp/src/strings/regex/regex.inl
- cpp/src/strings/replace/multi_re.cu
- cpp/src/strings/replace/replace_re.cu
- cpp/tests/strings/replace_regex_tests.cpp
Closes #4622 
The replace logic will increment through each string trying to match the given regex pattern. If the pattern is found, the corresponding replacement string replaces the matched bounds in the input string. The replace then continues trying to match the next occurrence of the pattern by repositioning to the end of the matched bounds. When the pattern is an empty string the width of the bounds is 0 thereby causing in an infinite loop looking for the next occurrence.
This PR corrects this logic for the multiple-pattern replace API as well as the single-pattern replace API by checking for the empty regex object.
Also, test cases were added to pass empty regex patterns.
> [REVIEW] Fix strings::replace_re handling empty regex pattern

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/MemoryCleaner.java
- java/src/main/java/ai/rapids/cudf/Rmm.java
If a non-default GPU is used the memory cleaner thread was still on the default GPU so they were not being collected, even though all of the code indicated that it was a success.
> [REVIEW] Fix issue with not setting GPU on background thread [skip ci]

- CHANGELOG.md
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda10.2.yml
- conda/recipes/cudf/meta.yaml
`fsspec` 0.7.0 was released ~7hrs ago and is breaking dask tests due to recent changes. This is to update the allowed versions to prevent the failures.
Follows updates made in rapidsai/integration#17
> [HOTFIX] FIX Update fsspec version

- CHANGELOG.md
- cpp/src/strings/padding.cu
- cpp/tests/strings/pad_tests.cu
Closes #4354 
Passing pad widths in Pandas `center()` results in different behavior if the width parameter is an odd vs even value. If the width is odd and the resulting pad is also odd (string width is even), then the extra padding character goes on the _left_ of the resulting string. If the width is even and the resulting pad is odd (string width is odd), then the extra padding character goes on the _right_ of the resulting string.
```
ps = pd.Series(["fox","foxx"])
ps.str.center(6,"+")
0    +fox++
1    +foxx+
ps.str.center(7,"+")
0    ++fox++
1    ++foxx+
```
Using width=6 and odd-lengthed string 'fox' the extra padding char '+' goes on the right.
Using width=7 and even-lengthed string 'foxx' the extra padding char '+" goes on the left.
More examples are in the #4354 description and …
> [REVIEW] Fix strings::pad when using pad::both with odd width

- CHANGELOG.md
- cpp/include/cudf/utilities/error.hpp
- cpp/src/strings/contains.cu
- cpp/src/strings/regex/regcomp.cpp
- cpp/tests/strings/contains_tests.cpp
- cpp/tests/strings/replace_regex_tests.cpp
- python/cudf/cudf/core/column/string.py
Closes #3732 
Closes #3725 
Any regex quantifier requires a previous item to repeat in the expression pattern.
For example "a*" means to match "a" zero or more times.
An invalid quantifier expression like simply "*" (no preceding char to check) was causing the regex parser to go into an infinite loop trying to resolve the previous item.
Likewise, an invalid escape sequence like "\" (single backslash) was being silently ignored.
The code logic has been fixed in this PR and errors are returned for invalid regex patterns.
Closes #4671 
The `contains()` was incorrectly returning false for empty string with regex pattern ".*"
This was due to the end-parm being set to 0 (size of empty string) on the regex find() function.
The find() allows the end-parm to be -1 to indicate to the end of the …
> [REVIEW] Fix regex infinite loop while parsing invalid quantifier pattern

- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryCleaner.java
- java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/main/native/src/RmmJni.cpp
- java/src/test/java/ai/rapids/cudf/RmmMemoryAccessorTest.java
For the second time we spent way too long debugging a seg fault when RMM was shut down in a unit test after another test leaked some device memory.  This adds in a best effort guard against that happening.
> [REVIEW] Protect against shutting down RMM with memory pending [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_datetime.py
Fixes: #4736 
1. We seem to be defaulting to `nan_as_null=True` while creating a column from `Series` but not while creating a column in `DataFrame.__init__`. Since we don't take `nan_as_null` parameter from the user, setting it to `True` as default to align the default behavior with `Series`.
2. Enabled a passing `xfail` totally un-related to this PR.
> [REVIEW] Setting `nan_as_null=True` while creating a column in DataFrame creation

- CHANGELOG.md
- cpp/CMakeLists.txt
- java/README.md
- java/pom.xml
- java/src/main/native/CMakeLists.txt
This fixes #4759 
This provides changes similar to those in https://github.com/rapidsai/rmm/pull/343
The default is kept the same to dynamically link against libcudart but static linking can be enabled.  I have manually tested this. I am not really sure that we want to have automated tests for this as it would require us to relink and rerun at least some of the tests, and python wants dynamic linking.
> [REVIEW] Added in an option to statically link against cudart

- .gitignore
- CHANGELOG.md
- python/cudf/setup.py
> [REVIEW] Add `cudf._cuda` to setup.py

- CHANGELOG.md
- cpp/tests/CMakeLists.txt
- cpp/tests/device_table/device_table_tests.cu
- cpp/tests/nvcategory/nvcategory_test.cu
- cpp/tests/utilities/base_fixture.hpp
Issue #797 
- Replace deprecated `rmmInitialize` and `rmmFinalize` with `rmm::mr::set_default_resource`.
- Move the test environment set up to its constructor, no need to use `SetUp`/`TearDown` any more.
- Code tested with non-legacy tests **cannot** use RMM_ALLOC any more, as it requires `rmmInitialize`. 
- Rename `nvcategory` and `device_table` tests so CMake treats them as legacy.
> [REVIEW] Replace the use of deprecated rmm APIs in the test environment

- CHANGELOG.md
- cpp/include/fixed_point/fixed_point.hpp
Number of issues with existing documentation:
* incorrectly formatted examples
* missing line breaks
* missing doxygen comments on namespaces
> [REVIEW] Fix `fixed_point` documentation

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TimestampColumnVectorTest.java
This updates the Java bindings to adapt to the timestamp parsing changes that occurred in #4811.  The `%f` format specifier no longer automatically determines how many digits to consume based on the timestamp type, so parsing to nanoseconds was not consuming enough digits after the change.
> Update Java bindings for timestamp cast formatting changes [skip ci]

- CHANGELOG.md
- java/src/main/native/src/NvtxRangeJni.cpp
The old cudf NVTX APIs will be removed soon, so this updates the cudf Java bindings to use the new nvtx3 APIs.
> Update Java bindings to use new NVTX API [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/native/src/RmmJni.cpp
- java/src/test/java/ai/rapids/cudf/RmmTest.java
This adds a static Java method to retrieve the total amount of memory allocated via RMM.  This is tracked by a simple RMM `device_memory_resource` that wraps the existing RMM default resource, delegating to it for all operations but also tracking the amount of memory seen to be successfully allocated.
> Add JNI total memory allocated API [skip ci]

- CHANGELOG.md
- cpp/src/transform/transform.cpp
- cpp/tests/transform/integration/unary-transform-test.cu
Fixes #4835
Transform was unable to handle CUDA UDFs passed as a single line of string. This was because Jitify expects the first line of the string source to be the name of the source. So it discards it.
This problem is specific to Transform as all other JIT enabled functionalities already prepend and empty new line to their string code. `rolling` happened to include it by chance.
> [REVIEW] Fixes bug in transform in handling single line UDFs

- CHANGELOG.md
- cpp/src/io/csv/legacy/csv_reader_impl.cu
- cpp/src/io/csv/reader_impl.cu
- cpp/tests/io/csv_test.cu
- python/cudf/cudf/tests/test_csv.py
Closes #3156 
Fix `select_rows` in CSV reader:
- Enable filtering of the first element when `byte_offset` is used. When parsing from the start of the file, a zero entry is added to mark the start of the first row. `select_row` used to skip filtering of this entry, but it should not be skipped when parsing with `byte_offset` (the first entry could be a quotation character, which need to be filtered out).
- When filtering rows and `byte_offset` is used, avoid updating the quotation state before hitting the first line terminator. This is important for cases where the byte range starts within a string, so quotation state get inverted in the entire filtering of the byte range.
- Add C++ and Python tests that fail when either of the fixes above is not present.
> [REVIEW] Fix CSV parsing with byte_range parameter and string columns

- CHANGELOG.md
- java/pom.xml
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/HostMemoryBufferTest.java
I started seeing a failure in the `PinnedMemoryPoolTest` due to the pinned pool being initialized in the `HostMemoryBufferTest` and not being shutdown after it exists.
> [REVIEW] HostMemoryBufferTest should tear down the pinned memory pool [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ContiguousTable.java
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
The Java bindings currently deserialize a table into a contiguous buffer, but the caller cannot access the underlying device buffer that encompasses the entire table.  The Java bindings already have a `ContiguousTable` class to describe contiguous tables, and it would be nice to expose this for use-cases that could take advantage of contiguous table buffers.
> Expose contiguous table when deserializing from Java [skip ci]

- CHANGELOG.md
- cpp/benchmarks/merge/merge_benchmark.cpp
Changes to column wrapper from PR https://github.com/rapidsai/cudf/pull/3581 require that range constructors use parentheses rather than braces, which broke one of the benchmarks.
> [REVIEW] Fix broken column wrapper in benchmark

- CHANGELOG.md
- cpp/tests/utilities/base_fixture.hpp
Executing `cuda-memcheck` against any gtests program results in errors reported after the tests complete.
```
Program hit cudaErrorCudartUnloading (error 4) due to "driver shutting down" on CUDA API call to cudaGetDevice.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3c43a3]
=========     Host Frame:/usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.10.2 (cudaGetDevice + 0x186) [0x4c306]
=========     Host Frame:/conda/envs/rapids/lib/librmm.so (_ZN5cnmem7ContextD2Ev + 0x2b) [0x10f9b]
=========     Host Frame:/conda/envs/rapids/lib/librmm.so (_ZN5cnmem7Context7releaseEv + 0x56) [0x111f6]
```
This only happens if `rmm_mode=pool` which is now the default.
The problem occurs because the default …
> [REVIEW] Move memory resource from RmmTestEnvironment to the custom gtest main() scope

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/PinnedMemoryPool.java
- java/src/main/java/ai/rapids/cudf/RmmEventHandler.java
- java/src/main/java/ai/rapids/cudf/Scalar.java
The RmmTest unit test can occasionally fail because it tests a scenario where closing a device buffer throws an exception.  This can leave the cleaner tracking object in a state where the resource has been released but the tracking object thinks it still needs to be released, causing the Rmm shutdown code to throw an exception on the "leaked" resource.
This updates the `cleanImpl` methods to always mark the resource as being cleaned even if the cleanup throws.  An exception at this point means we cannot retry the cleanup, so the resource is always marked as cleaned to prevent retry later (e.g.: at shutdown) before the exception is propagated to the application.
> Mark Java cleaner objects as being cleaned even if exception is thrown [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Adds annotations for the `.columns` getter and setter as those seem to be extremely time consuming, e.g., within a call to `groupby.agg()`:
Underneath each `DataFrame` is a `ColumnAccessor` object, a proprietary dict-like object that holds the mapping of column names to columns. It is accessible via the `._data` attribute:
```python
In [3]: a = cudf.DataFrame({'a': [1, 2, 3], 'b': ['a', 'b', 'c']})
In [4]: print(a._data)
ColumnAccessor(OrderedColumnDict([('a', <cudf.core.column.numerical.NumericalColumn object at 0x7f0e084b0730>), ('b', <cudf.core.column.string.StringColumn object at 0x7f0e084cdb90>)]), multiindex=False, lev
el_names=(None,))
```
`DataFrame.columns` returns an object of type `pandas.Index`, containing just the names of the columns. 
```python
In [5]: a.columns
Out[5]: …
```
> [REVIEW] Add annotations for the `.columns` property and setter

- CHANGELOG.md
- python/cudf/cudf/_lib/nvtx/nvtx.py
This should enable using `@annotate` with functions that need to be pickled/serialized by Dask. cc: @jrhemstad
> [REVIEW] Use ContextDecorator instead of contextmanager for nvtx.annotate

- CHANGELOG.md
- python/cudf/cudf/_lib/nvtx/nvtx.py
Automatically get the decorated function's name and use it as the `message` when annotating with NVTX. Thus, following are equivalent:
```python
@annotate("my_func", color="red")
def my_func(x):
pass
```
```python
@annotate(color="red")
def my_func(x):
pass
```
> [REVIEW] Get decorated function name as message when annotating

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
This is a holdover from old nvstrings code. Since we no longer needed it (and is already handled above), go ahead and drop it.
> [REVIEW] Drop old `valid` check in `element_indexing`

- CHANGELOG.md
- java/README.md
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/CudaJni.cpp
- java/src/main/native/src/RmmJni.cpp
- java/src/main/native/src/ScalarJni.cpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/RmmMemoryAccessorTest.java
- java/src/test/java/ai/rapids/cudf/RmmTest.java
The CUDA runtime will automatically search for a GPU to use if a thread has not specifically requested a device, and Java processes tend to run with many threads.  If one of the Java threads using cudf does not use the same device being used by other cudf threads then this will lead to an invalid state that can trigger application crashes.
To avoid these crashes, this changes the Java cudf bindings tol remember which CUDA device was used to initialize the Rapids Memory Manager (RMM) via cudf.  Java cudf methods will automatically update the thread's CUDA device to match the RMM device if necessary.
> Java methods ensure calling thread's CUDA device matches RMM device [skip ci]

- CHANGELOG.md
- python/cudf/cudf/_cuda/gpu.pyx
- python/cudf/cudf/utils/gpu_utils.py
Instead of calling `malloc` on memory we don't call `free` on in `deviceGetName`, just allocate memory on the stack and let C clean it up when we scope out. Plus this is a bit more DRY friendly when working with object sizes. Go ahead and convert the result to a Python `str` to simplify working with it in Python code later.
> Use stack for memory in `deviceGetName`

- CHANGELOG.md
- python/dask_cudf/dask_cudf/sorting.py
- python/dask_cudf/dask_cudf/tests/test_core.py
This PR is intended to fill in some gaps in the existing `rearrange_by_hash` implementation (used for hash-based repartitioning in `dask_cudf`). The changes include:
1. **Handle `npartitions` argument without falling back to the upstream-Dask shuffle routine**.  Eventually we want to use upstream dask for the shuffle in all cases (e.g. after changes like [dask#6066](https://github.com/dask/dask/pull/6066) are fiinished/accepted).  However, the hash-based shuffle routine in `dask_cudf` is currently less memory intensive.  This PR allows the `dask_cudf` routine to be used when the number of output partitions (`npartitions`) does **not** match the orginal partition count.  Before this PR, the dask_cudf algorithm could only handle an N-to-N shuffle.
2.  **Add `_simple_shuffle` routine for the …
> Cleanup dask_cudf rearrange_by_hash and implement edge cases

- CHANGELOG.md
- python/cudf/cudf/_cuda/gpu.pyx
Should limit Python to C++ object conversion to the function declaration and allow use of `attr` in C++ contexts within the function.
> Use `cudaDeviceAttr` in `getDeviceAttribute`

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Adds Java binding for `strip` method to remove leading and trailing whitespace.
I was unsure about the correct code for predicting device size and based it on the implementation for `stringReplace` since that seemed roughly equivalent.
> [REVIEW] Add Java bindings for strip [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
When the pinned memory pool support was originally added it was "opt-in" to have host memory buffers default to using the pinned memory pool by setting the Java system property `ai.rapids.cudf.prefer-pinned` to true.  At this point we always want host buffers to leverage a pinned memory pool unless they explicitly say otherwise, so we're always running with that extra property set.
To simplify the configuration, this changes the default so Java HostMemoryBuffer instances will attempt to allocate from the pinned memory pool before falling back to system memory, changing the pinned memory behavior to "opt-out".
> Change Java HostMemoryBuffer default to prefer pinned memory [skip ci]

- CHANGELOG.md
- python/cudf/cudf/_lib/aggregation.pyx
- python/cudf/cudf/_lib/transform.pyx
- python/cudf/cudf/tests/test_udf_binops.py
- python/cudf/cudf/utils/applyutils.py
- python/cudf/cudf/utils/cudautils.py
Many "internal" parts of Numba were moved with the release of 0.49. The old module locations can still be imported with a shim for the 0.49 release, but its use results in the emission of NumbaDeprecationWarning messages. The shims will be removed in Numba 0.50.
This PR avoids the deprecation warnings and enables import from the new module paths where available, so that cuDF can be used with Numba 0.48, 0.49, or (a future release of) 0.50.
Once Numba 0.49 or above is a cuDF requirement, the `try .. except ImportError` blocks can be replaced with imports exclusively from the new locations.
> Fix Numba deprecation warnings with Numba 0.49+

- CHANGELOG.md
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
A recent change fixed some bugs in shift right unsigned. The java test covering that operator was faulty because it relied on java itself to produce the result for a short, which java does not support an unsigned right shift on a short.  It casts it to an int before doing the cast.  Because of that the test itself was invalid and was inadvertently relying on the broken behavior to work.
So I just removed that part of the test
> [REVIEW] Fix invalid java test [skip-ci]

- CHANGELOG.md
- cpp/include/cudf/copying.hpp
- cpp/include/cudf/detail/search.hpp
- cpp/include/cudf/detail/stream_compaction.hpp
- cpp/include/cudf/join.hpp
- cpp/include/cudf/legacy/join.hpp
- cpp/include/cudf/legacy/search.hpp
- cpp/include/cudf/search.hpp
- cpp/include/cudf/sorting.hpp
- cpp/include/cudf/stream_compaction.hpp
This is essentially removing the `@example` specifier or replacing it with a `@code` block.
The invalid examples page can be seen here:
https://docs.rapids.ai/api/libcudf/nightly/examples.html
https://docs.rapids.ai/api/libcudf/stable/examples.html
This is doxygen struggling to work with an invalid `@example` usage in various source files.
This PR simply removes them or replaces them as appropriate. The page/tab will disappear.
There are no code changes in the PR. This is only fixing comments.
> [REVIEW] Remove invalid examples page from libcudf doxygen

- CHANGELOG.md
- cpp/src/io/functions.cpp
> [REVIEW] Fix metadata_out parameter not reaching parquet write_all()

- CHANGELOG.md
- cpp/tests/utilities/column_utilities.cu
- cpp/tests/utilities_tests/column_utilities_tests.cpp
These changes enable higher precision printing of floating-point values such as doubles and floats when comparing columns (`expect_column_equals`).
Previously:
```
../../../../tests/utilities/column_utilities.cu:220: Failure
Expected: differences.size()
Which is: 1
To be equal to: size_t{0}
Which is: 0
differences:
lhs[0] = 0, rhs[0] = 0
```
With these changes:
```
differences:
lhs[0] = 0, rhs[0] = 1.5604449514735574e-12
```
This empowers developers to write unit tests with specific expected values. For instance, higher precision may be required when writing functions which utilize trigonometric operations.
_Note:_ I intentionally avoid using `std::fixed`, as that will unnecessarily lengthen the string.
> [REVIEW] column_utilities: print more precise numerical strings

- CHANGELOG.md
- cpp/include/cudf/strings/string.cuh
- cpp/tests/strings/chars_types_tests.cpp
Closes #5083 
Converting a single-character string with only the sign '+' or '-' to integer or float will throw an exception in Pandas. This PR fixes the functions `is_integer/all_integer` and `is_float/all_float` functions used by cudf to return false if only the sign character is present.
Also, adds gtests for sign-only strings.
> [REVIEW] Return false for sign-only string in libcudf is_float and is_integer

- CHANGELOG.md
- cpp/src/hash/hashing.cu
- cpp/src/join/join.cu
This change fixes `hash()` and `construct_join_output_df()` so that they pass down the user-provided memory resource correctly.
> [REVIEW] Fix `hash()` and `construct_join_output_df()` to use user-provided memory resource correctly

- CHANGELOG.md
- CONTRIBUTING.md
Updating the documentation to reflect that pre-commit hooks will now run `clang-format` for C++/CUDA as well as the existing hooks for Python.
> [REVIEW] Update CONTRIBUTING.md for `clang-format` pre-commit hook [skip ci]

- CHANGELOG.md
- cpp/benchmarks/column/concatenate_benchmark.cpp
- cpp/include/cudf/concatenate.hpp
- cpp/include/cudf/detail/concatenate.cuh
- cpp/src/copying/concatenate.cu
- cpp/src/join/join.cu
- cpp/tests/copying/concatenate_tests.cu
- cpp/tests/io/orc_test.cu
- cpp/tests/io/parquet_test.cu
- java/src/main/native/src/TableJni.cpp
- python/cudf/cudf/_lib/cpp/concatenate.pxd
Closes https://github.com/rapidsai/cudf/issues/5081
Also removes unnecessary `experimental` namespace from `concatenate`; the legacy version of this API was named `cudf::concat`, so there isn't a name conflict.
> [REVIEW] Remove table concatenate from experimental namespace and add detail API with stream parameter

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
Simple change to naming to avoid ambiguity between byte and character length.
> Java change string character length naming [skip ci]

- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_label_encode.py
When using `cudf` to load up dataset with many categorifiable columns, I noticed much bigger memory footprint compared to `pandas`, after `astype('category')` on many columns.
It points to `core/series.py: label_encoding()`, where `np.int32` is used as the starting point of searching for a minimum type size.  In many workloads the number of categories for a series is under a couple of hundreds, and fits well within `np.int8` or `np.int16`.  Doing so will save a lot of memory foot print for larger tabular datasets, with many categorifiable columns.
`np.uint8` would be even better, but that'd be a more involved change, punting for now.
Simple test showing the memory usage of the resulting labels:
```
sz = 100000
for n_cats in [65535, 255, 127, 10]: 
s = cudf.Series([ str(i%n_cats) for i in …
```
> Use lot less memory in `label_encoding()`

- CHANGELOG.md
- ci/gpu/build.sh
Installs `contextvars` on Python 3.6, which is [now needed by Distributed]( https://github.com/dask/distributed/blob/77f6c55f2482544871cf38b3730fb6f902bf2682/requirements.txt#L3 ). Can be dropped after there is a Distributed release with that requirement listed.
cc @kkraus14 @cjnolet
> Install `contextvars` backport on Python 3.6

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
When Python pickle's protocol 5 or greater is used, this change will support more efficient serialization of out-of-band buffers. This is analogous to Dask's custom serialization except for pickling. As such this is helpful in *any* Python serialization case where pickling is used. If an older pickling protocol is used, we simply proceed as before.
> Support out-of-band buffers in Python pickling

- CHANGELOG.md
- java/pom.xml
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/CudaJni.cpp
This fixes a couple of issues when building CUDF/Java with GCC-8:
1. `native_jstring::operator =()` and `Java_ai_rapids_cudf_Cuda_eventQuery()` neglect to return values. This has been remedied.
1. `rmm.hpp` generates a number of deprecation errors, simply from inclusion:
```
[exec] In file included from /home/mithunr/workspace/dev/rapids/cudf/java/src/main/native/src/TableJni.cpp:31:
[exec] /home/mithunr/workspace/dev/rapids/cudf/java/src/main/native/include/jni_utils.hpp: In member function 'cudf::jni::native_jstring& cudf::jni::native_jstring::operator=(const cudf::jni::native_jstring&&)':
[exec] /home/mithunr/workspace/dev/rapids/cudf/java/src/main/native/include/jni_utils.hpp:438:3: error: no return statement in function returning non-void [-Werror=return-type]
```
This obfuscates …
> Fix JNI build on GCC 8

- CHANGELOG.md
- cpp/src/copying/shift.cu
- cpp/src/unary/unary_ops.cuh
This is a fix for #5140. Note that this change still ignores the stream argument because [`allocate_like`](https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/include/cudf/copying.hpp#L168-L171) currently does not take it. This should be fixed once the `allocate_like` is modified to take a stream argument.
> [REVIEW] Use user-provided resource correctly in `unary_operation()` and `shift()`

- CHANGELOG.md
- cpp/include/cudf/detail/copy_if.cuh
> [REVIEW] Allocate null count using the default resource in `copy_if`

- CHANGELOG.md
- cpp/include/cudf/strings/detail/combine.hpp
- cpp/include/cudf/strings/detail/converters.hpp
- cpp/src/strings/combine.cu
- cpp/src/strings/convert/convert_booleans.cu
- cpp/src/strings/convert/convert_datetime.cu
- cpp/src/strings/convert/convert_floats.cu
- cpp/src/strings/convert/convert_integers.cu
This PR is simply adding detail headers for declaring the following strings API functions:
- `to_integers/from_integers`
- `to_floats/from_floats`
- `to_booleans/from_booleans`
- `to_timestamps/from_timestamps`
Also adding detail header for `concatenate` and `join_strings`
These functions are used in the CSV writer (in #4484) but it calls the external API instead of the detail API since these headers did not exist.
https://github.com/rapidsai/cudf/blob/80d562d2636780e11ea0cdb68ac2412ac3073619/cpp/src/io/csv/writer_impl.cu#L297
https://github.com/rapidsai/cudf/blob/80d562d2636780e11ea0cdb68ac2412ac3073619/cpp/src/io/csv/writer_impl.cu#L286
https://github.com/rapidsai/cudf/blob/80d562d2636780e11ea0cdb68ac2412ac3073619/cpp/src/io/csv/writer_impl.cu#L245 …
> [REVIEW] Add detail headers for strings converter functions

- CHANGELOG.md
- python/cudf/cudf/_lib/dlpack.pyx
A`dlpack` can only be used once.  Functions that set its name to `"used_dltensor"` should also invoke its `deleter()` as well.
`cupy.fromDlpack()` went through [the same problem in July 2018](https://github.com/cupy/cupy/pull/1445), fixed by [adding a `deleter()` call](https://github.com/cupy/cupy/blob/e6474838a922b7869fb56380c8b9421702da1b26/cupy/core/dlpack.pyx#L148-L152) in the finalizer `__dealloc__()` of the memory mgr, who set the tensor name to `"used_dltensor"`.
Fixes #4277
> Fix memory leak in dlpack.pyx:from_dlpack()

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
This fixes build/CI issue that is failing style checks.
It appears that new header files have to be added manually to the `conda/recipes/libcudf/meta.yaml` file in order to pass copyright style check.
> [REVIEW] Add new headers from 5198 to conda/recipes/libcudf/meta.yaml

- CHANGELOG.md
- python/cudf/cudf/tests/test_datetime.py
- python/cudf/cudf/utils/dtypes.py
Fixes #5120 
Assigning cudf series/dataframes with datetime scalars of time_unit `'D', 'W', 'M', 'Y'` creates a series with the corresponding dtype `datetime64[D]` etc. but fails downstream since these time units are not supported. This PR does the following:
> [REVIEW] Automatically typecast unsupported datetime scalars

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
The existing helper methods DataFrame.clean_renderable_dataframe and DataFrame.get_renderable_dataframe appear as part of the public API. They have been converted to underscore methods _clean_renderable_dataframe and _get_renderable_dataframe instead.
I do no think this requires new tests or updating existing tests as they do not affect any existing functionality or tests.
Closes #5164
> [WIP] Make DataFrame.clean_renderable_dataframe() and DataFrame.get_renderable_dataframe non-public methods

- CHANGELOG.md
- python/cudf/cudf/_lib/column.pyx
Since Cython 0.26+, `auto_pickle` is already added to any `cdef class`. So this shouldn't be needed. Besides pickling is largely handled through `serialize` and `deserialize` methods of `Serializable` subclasses.
> Drop `auto_pickle` decorator

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_datetime.py
Fixes: #5117 
1. Checking for `'None'` values and erroring to match pandas behavior.
2. Setting the result values to `null` if we find any `'NaT'` values in the input column.
> [REVIEW] Add support to check for "NaT" and "None" strings while typecasting to `datetime64`

- CHANGELOG.md
- python/cudf/cudf/core/abc.py
As NumPy arrays are always pickleable and they support pickle protocol version 5 (out-of-band pickling) on their own, just use NumPy arrays when pickling `Serializable` objects.
> Rely on NumPy arrays for out-of-band pickling

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda10.2.yml
- conda/recipes/cudf/meta.yaml
Already we are using NumPy in the code. Thus far this has worked because Numba requires NumPy. So we have depended on NumPy implicitly. This makes the NumPy requirement explicit.
> Explicitly require NumPy

- CHANGELOG.md
- java/pom.xml
Updating the Java version to match the libcudf version.
> Update package version for Java bindings [skip ci]

- CHANGELOG.md
- java/README.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
This removes nvstrings and nvcategory from what is packaged in the java jar.  They are no longer used so we can remove them.
This also adds in packaging of libnvrtc if static linking is enabled.  This is not 100% perfect as libnvrtc will do a dlopen on libnvrtc-builtins.so  But it is a step in the right direction.
> [REVIEW] Remove unused native deps from java library [skip-ci]

- CHANGELOG.md
- python/cudf/cudf/core/abc.py
To ensure that the result after deserialization looks like that before serialization, make sure to coerce frames in device deserialization to `Buffer` objects. As a result, when subclasses get frames in `deserialize` they can rely on them being `Buffer`s.
> Coerce frames to `Buffer`s in deserialization

- CHANGELOG.md
- python/cudf/cudf/tests/test_pickling.py
This test assumes that pickling the data will yield something of the same size. While that seems reasonable, it's not quite right as a bunch of information about how to extract the pickled data and rebuild Python objects will be included. So instead merely check that the pickled data is at least the size of the object. IOW no data was lost by pickling. However don't tightly enforce equality.
> Fix pickling sizeof test

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_indexing.py
Fixes issue #5329.  Use `@property` because `loc` and `iloc` are.
> Fix broken alias from DataFrame.{at,iat} to {loc,iloc}

- CHANGELOG.md
- cpp/benchmarks/stream_compaction/apply_boolean_mask_benchmark.cpp
Trivial fix of num_columns to column_size in a benchmark that caused a segfault.
> [REVIEW] Fix APPLY_BOOLEAN_MASK_BENCH segfault

- CHANGELOG.md
- python/cudf/cudf/comm/serialize.py
As Dask already routes to the right deserialization function based on whether `"dask"` or `"cuda"` deserialization was used, split the deserialization function into 2 deserialization functions for these 2 cases. This should avoid us needing to check which deserialization to perform. Also this is very lightweight to implement thanks to the fact that this logic is already captured in methods of `Serializable`.
> Split Dask deserialization methods by dask/cuda

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/reshape.hpp
- cpp/include/cudf/join.hpp
- cpp/src/join/cross_join.cu
- cpp/src/join/semi_join.cu
- cpp/src/reshape/tile.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/join/cross_join_tests.cpp
Closes #3194.
This PR adds a feature for [cross join](https://www.w3resource.com/sql/joins/cross-join.php), which accepts two input tables and produces an output table with the cartesian product of their rows.
> [REVIEW] Cross join feature.

- CHANGELOG.md
- cpp/include/cudf/detail/repeat.hpp
- cpp/include/cudf/filling.hpp
- cpp/src/filling/repeat.cu
- cpp/tests/filling/repeat_tests.cu
- python/cudf/cudf/_lib/cpp/filling.pxd
- python/cudf/cudf/_lib/filling.pyx
- python/cudf/cudf/core/frame.py
**Description:** This PR changes the API for `cudf::repeat` to use `size_type` instead of `scalar const &`. (The other overload, which accepts a column with the number of times to repeat each row, is unchanged.)
Closes #5355.
> [REVIEW] Change cudf::repeat to use size_type for the number of repeats.

- CHANGELOG.md
- cpp/src/join/cross_join.cu
Applies the API change to `cudf::repeat` from #5355 to the `cudf::cross_join` feature introduced in #5327. (I should have merged `branch-0.15` into one of those PRs before the other PR was merged.)
> [REVIEW] Apply API change from cudf::repeat in cudf::cross_join.

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
Removes the dependency on the (unused) `rmm._DevicePointer`.
> [REVIEW] Remove dependency on `rmm._DevicePointer`

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
Previously if we constructed a `Buffer` from a `Buffer`, the new `Buffer` would reference the old `Buffer` used to create that. However this can result in `Buffer`s that have chained references, which is inefficient and unneeded. Also it makes it difficult to determine what object actually owns the data. Instead just shortcut around the provided `Buffer` and reference the object owning the data. This will avoid chained `Buffer`s and ensure the underlying data remains valid even if the old `Buffer` scopes out. Plus makes it easier to inspect the `Buffer`.
cc @quasiben @pentschev
> Avoid chaining `Buffer`s

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/tests/test_dataframe.py
I noticed that using `quantile` in dask_cudf was causing a pyarrow error in `to_column`.  It seems that the following behavior was not supported:
```python
import cudf, cupy
data = cupy.array([0.1, 0.2, 0.3])
cudf.Series([data[0], data[2]])
``` 
**Error**:
```
E   pyarrow.lib.ArrowInvalid: Could not convert 0.1 with type cupy.core.core.ndarray: did not recognize Python value type when inferring an Arrow data type
```
This PR introduces a simple fix (handles the case that the elements of `arbitrary` are of type `cupy.ndarray`).  I'll be happy to raise a separate issue if others feel a more robust solution is needed here.
> Handle array of cupy scalars in to_column

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/DType.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
This fixes the Java test build by updating the native type IDs to match the new IDs after the unsigned types were added.  It also fixes the Table interleave strings unit test which no longer throws now that string column interleaving is supported in libcudf.
> Fix Java data type IDs and string interleave test [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/tests/test_column.py
Fixes: #5395 
This PR fixes an issue in column creation when there is a `pyarrow.ChunkedArray` passed and we have a `dtype` value as non-None, we were doing an equality check against an not know dtype to numpy which is "empty".
> [REVIEW] Fix issue with column creation when chunked arrays are passed

- CHANGELOG.md
- cpp/include/cudf/strings/detail/copy_if_else.cuh
- cpp/include/cudf/strings/detail/copy_range.cuh
- cpp/include/cudf/strings/detail/merge.cuh
- cpp/include/cudf/strings/detail/scatter.cuh
- cpp/include/cudf/strings/detail/strings_column_factories.cuh
- cpp/src/bitmask/null_mask.cu
- cpp/src/dictionary/dictionary_factories.cu
- cpp/src/strings/combine.cu
- cpp/src/strings/copying/concatenate.cu
- cpp/src/strings/strings_column_factories.cu
- cpp/src/strings/substring.cu
Issue #5067
Fix a missed case where empty null masks are initialized with the default memory recourse and returned to the caller if the input is not nullable.
Since `device_buffer` holds on to the memory resource, it should be initialized with the correct resource even if no allocation is happening at the time.
> [REVIEW] Use the correct memory resource when creating empty null masks

- build.sh
This PR removes some _legacy_ args remnants leftover from #5396
> [skip ci] Remove legacy tests env variable from build.sh

- CHANGELOG.md
- cpp/include/cudf/strings/substring.hpp
- cpp/src/strings/substring.cu
Current build includes a compile warning for `cudf::strings::slice_strings` function in `src/cpp/strings/substring.cu` 
```
Building CUDA object CMakeFiles/cudf.dir/src/strings/substring.cu.o
_deps/thrust-src/thrust/iterator/iterator_adaptor.h(210): warning: incrementing a bool value is deprecated
detected during:
instantiation of "void thrust::iterator_adaptor<Derived, Base, Value, System, Traversal, Reference, Difference>::increment() [with Derived=thrust::counting_iterator<__nv_bool, thrust::use_default, thrust::use_default, thrust::use_default>, Base=__nv_bool, Value=__nv_bool, System=thrust::any_system_tag, Traversal=thrust::random_access_traversal_tag, Reference=__nv_bool, Difference=signed int]" 
....
```
The warning occurs because the dispatcher functor `compute_substrings` …
> [REVIEW] Fix compile warning by disallowing bool column type for slice_strings

- CHANGELOG.md
- cpp/doxygen/rapids.css
This PR adds some CSS for libcudf Doxygen to allow long class names in lists to wrap, improving readability of documentation, especially in "narrow" browser windows (previously they were only readable on my screen when the window was maximized!)
Before:
After:
> [REVIEW] Enable wrapping long class names in libcudf Doxygen tables [skip-ci]

- CHANGELOG.md
- cpp/include/cudf/utilities/traits.hpp
- cpp/tests/types/traits_test.cpp
This trait is unused. On top of that, I don't think it is necessary to name the `not` (aka complement) of `is_compound` when we already have `is_fixed_width`.
> [REVIEW] Remove unused `is_simple` trait

- CHANGELOG.md
- cpp/tests/utilities/column_utilities.cu
This PR https://github.com/rapidsai/cudf/pull/4990 got merged and was a little bit behind.  An overload for duration types hadn't had it's param list updated.   One line fix here.
> [REVIEW] Build compile error fix in column_utilities.cu

- CHANGELOG.md
- cpp/benchmarks/fixture/benchmark_fixture.hpp
- cpp/benchmarks/join/generate_input_tables.cuh
- cpp/src/column/column_device_view.cu
- cpp/src/hash/hash_allocator.cuh
- cpp/src/io/comp/uncomp.cpp
- cpp/src/reductions/scan.cu
- cpp/src/strings/regex/regexec.cu
- cpp/src/strings/utilities.cu
- cpp/src/table/table_device_view.cu
- cpp/tests/error/error_handling_test.cu
Closes #5444
In anticipation of https://github.com/rapidsai/rmm/pull/396, removes all references to deprecated RMM headers and APIs.
> [REVIEW] Remove deprecated RMM APIs and headers.

- CHANGELOG.md
- python/cudf/cudf/_lib/strings/translate.pyx
- python/cudf/cudf/tests/test_string.py
Fixes #5453 
The `str.maketrans()` function creates character mapping table for the `translate()` API. The values are stored as unicode code-point values (integers). The `cudf::strings::translate()` is expecting UTF-8 encoded characters in its translate table parameter.
For consistency with other strings APIs, the Cython code logic for `translate()` is changed to convert the unicode values to UTF-8 encoded values when creating the mapping table for the call to libcudf.
Also added some multi-byte characters to the pytest function.
> [REVIEW] Fix str.translate to convert table characters to UTF-8

- CHANGELOG.md
- cpp/src/text/utilities/tokenize_ops.cuh
Closes #5412 
This PR improves the speed of tokenization in the `nvtext::ngrams_tokenizer` as well as other nvtext tokenize APIs.
The internal nvtext tokenizing function currently uses a `cudf::string_view::const_iterator` to navigate and locate token delimiters. Once located, the byte-offsets need to be retrieved to build the output. The internal `characters_tokenizer` functor was using character positions to keep track of found tokens. This means converting these positions to byte-offsets for each token can be costly for long strings containing multi-byte UTF-8 characters as described in the issue.
This PR modifies the functor to store byte-offsets internally instead of character positions so the conversion is not required. The iterator maintains both character and byte position so the …
> [REVIEW] Fix nvtext ngrams_tokenize performance for multi-byte UTF8

- CHANGELOG.md
- ci/gpu/build.sh
Install dependencies via `rapids-build-env` and `rapids-notebook-env` (which are pre-installed in the containers).
This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/
> [REVIEW] Install meta packages for dependencies

- CHANGELOG.md
- cpp/benchmarks/fixture/benchmark_fixture.hpp
Fixes errors caused by multiple initialization of cnmem in google benchmarks.
> [REVIEW] Fix benchmark_fixture cnmem errors

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/cmake/Modules/ConfigureArrow.cmake
- cpp/cmake/Templates/Arrow.CMakeLists.txt.cmake
- cpp/tests/CMakeLists.txt
Link Arrow libraries statically per java requirements.
This partially rolls back #5408.
Fixes #5457 
@kkraus14 @jlowe
> [REVIEW] allow linking arrow libraries statically

- CHANGELOG.md
- cpp/src/dictionary/add_keys.cu
- cpp/src/dictionary/decode.cu
- cpp/src/dictionary/encode.cu
- cpp/src/dictionary/remove_keys.cu
- cpp/src/dictionary/search.cu
- cpp/src/dictionary/set_keys.cu
Closes #4323 
This adds the NVTX CUDF_FUNC_RANGE() calls to the dictionary APIs.
- encode
- decode
- add_keys
- remove_keys
- remove_unused_keys
- set_keys
- get_index
> [REVIEW] Add NVTX range calls to dictionary APIs

- CHANGELOG.md
- python/cudf/cudf/tests/test_binops.py
- python/cudf/cudf/tests/test_column.py
- python/cudf/cudf/tests/test_copying.py
- python/cudf/cudf/tests/test_cuda_array_interface.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_feather.py
- python/cudf/cudf/tests/test_hdf.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_json.py
- python/cudf/cudf/tests/test_repr.py
- python/cudf/cudf/tests/test_reshape.py
- python/cudf/cudf/tests/test_scalar.py
- python/cudf/cudf/tests/test_sorting.py
- python/cudf/cudf/tests/test_string.py
- python/cudf/cudf/tests/test_udf_binops.py
- python/cudf/cudf/tests/test_unaops.py
- python/cudf/cudf/tests/utils.py
- python/cudf/cudf/utils/dtypes.py
Use sorted lists so pytests are collected deterministically. This fixes running pytests in parallel with `pytest-xdist`.
> [REVIEW] Use sorted lists instead of sets for pytest parameterization

- CHANGELOG.md
- cpp/include/cudf/detail/copy_if.cuh
This PR uses rmm::device_uvector in place of rmm::device_vector for `cudf::detail::copy_if`. This can serve as an example of how to make this change in libcudf algorithms, which we need to do throughout the library in order to resolve #2631 and #5380
First and foremost, this makes the code safe to use on non-default streams (see #2631). In the new code, notice that every line of code in copy.if.cuh that allocates, reads, or writes device memory takes a stream parameter now, whereas before a lot of the simple operations on `device_vector` (including the constructor) did not. From now on we should be looking for this pattern in libcudf in reviews.
You can see in these screenshots from NSight systems the impact of this change. This is using device_vector (before this PR). You can see at the …
> [REVIEW] Use rmm::device_uvector in place of rmm::device_vector for `cudf::detail::copy_if`

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/TimestampColumnVectorTest.java
This adds week day, last day of month, and day of year to the java APIs.  This should make the java API in sync with cudf on date time operations.
> [REVIEW] Java APIs for missing date/time operators [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This adds in join APIs for `fullJoin` and `crossJoin`, which were missing from java.
> [REVIEW] Add missing join types to java [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/frame.py
Instantiate Table instances in `Frame._concat()` to avoid overhead from all the small `DF.insert()` calls in the DF constructor.
This is a small perf boost individually that can add up when doing many `concat` operations.
> [REVIEW] Instantiate Table instances in Frame._concat to avoid DF.insert() overhead

- CHANGELOG.md
- cpp/include/cudf/strings/convert/convert_integers.hpp
- cpp/src/strings/convert/convert_hex.cu
- cpp/tests/strings/integers_tests.cu
- python/cudf/cudf/_lib/cpp/strings/convert/convert_integers.pxd
- python/cudf/cudf/_lib/string_casting.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Reference #5131 
This PR creates a new strings API as described in #5131
```
std::unique_ptr<column> is_hex(
strings_column_view const& strings,
rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```
This PR also exposes the function as `str.ishex()` in cudf.
This PR includes gtest and pytest for the new API as well.
> [REVIEW] Add is_hex strings API

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_categorical.py
Fixes: #5617 
This PR fixes issue where we were trying to cast `cats` with `self` dtype irrespective of a check if only one of them is an `object` dtype. In which case we should be returning `na_sentinel`.
With this change we actually don't have to re-typecast the categorical column being constructed in `as_categorical_column`, thus avoiding double type-casting.
> [REVIEW] Fix issue related to typecasting when using a `CategoricalDtype`

- CHANGELOG.md
- cpp/include/cudf/join.hpp
- cpp/src/join/hash_join.cuh
- cpp/src/join/join.cu
- cpp/src/join/nested_loop_join.cuh
- cpp/src/join/semi_join.cu
- cpp/tests/join/join_tests.cpp
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
By default, `NULL` join keys compare as equal, in CUDF. This is consistent
with the semantics in Pandas.
However, this behaviour cannot be parameterized to follow SQL semantics
(which dictates that `NULL <> NULL`).
This commit allows the caller of `cudf::*join()` to choose between SQL
and Pandas semantics, while keeping the default behaviour intact.
> [REVIEW] Parameterize Null comparator behaviour in Joins

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
Fixes #5661
This exposes the `ColumnVector(long nativePointer)` constructor in the Java bindings to allow other Java packages to construct a `ColumnVector` instance from an existing `cudf::column` instance.
> Make Java ColumnVector(long nativePointer) constructor public [skip ci]

- CHANGELOG.md
- java/README.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
- java/src/main/native/CMakeLists.txt
- java/src/main/native/src/RmmJni.cpp
Depends on https://github.com/rapidsai/rmm/pull/425.
@harrism @revans2 @jlowe
> [REVIEW] switch from CNMeM to `pool_memory_resource` [skip ci]

- CHANGELOG.md
- cpp/src/io/csv/writer_impl.cu
- python/cudf/cudf/tests/test_csv.py
Due to split, it introduced an empty table with `0` rows which caused this issue. 
closes #5588
> [REVIEW] Fix chunksize issue with `DataFrame.to_csv`

- CHANGELOG.md
- build.sh
- ci/gpu/build.sh
Always build and test with per-thread default stream enabled, as discussed in #5614.
@harrism @jrhemstad @kkraus14
> [REVIEW] enable per-thread default stream in gpu ci

- CHANGELOG.md
- python/cudf/cudf/core/abc.py
When using an older Python version that lacks pickle protocol 5, make sure to use `pickle5` with `Serializable` (when available). This is [what Dask does]( https://github.com/dask/distributed/blob/d9da4d79cafa1e5f46058b45f2e8209c99590506/distributed/protocol/serialize.py#L43 ) as well. So this should make sure we are compatible.
> Use `pickle5` in `Serializable` (when available)

- CHANGELOG.md
- ci/local/build.sh
PR fixes local docker image ('DOCKER_IMAGE' string) used by build script:
- Replaces py3.6 with py3.7 (in line with dropping Python 3.6 support for v0.15 -> https://github.com/rapidsai/ops/issues/1017)
This fix was missing from https://github.com/rapidsai/cudf/pull/5656
> [REVIEW] update docker image to py3.7 [skip-ci]

- CHANGELOG.md
- cpp/include/cudf/strings/char_types/char_types.hpp
- cpp/src/strings/char_types/char_types.cu
- cpp/tests/strings/chars_types_tests.cpp
- python/cudf/cudf/_lib/cpp/strings/char_types.pxd
- python/cudf/cudf/_lib/strings/char_types.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Closes #5520 
Create a new strings API that can filter characters from strings by specifying the character types.
Also, allows for an optional replacement character or string in place of each removed character.
> [REVIEW] Add filter_characters_of_type strings API

- CHANGELOG.md
- cpp/src/hash/concurrent_unordered_map.cuh
- cpp/src/hash/concurrent_unordered_multimap.cuh
This is a workaround for an unknown bug that gives the following error on gcc 7.4.0 and CUDA 10.1:
```bash
/home/ashwint/workspace/github/rapidsai/cudf/cpp/src/hash/concurrent_unordered_multimap.cuh: In instantiation of ‘concurrent_unordered_multimap<Key, Element, size_type, unused_key, unused_element, Hasher, Equality, Allocator, count_collisions>::create(size_type, bool, const Hasher&, const Equality&, const allocator_type&, cudaStream_t)::<lambda(Self*)> [with Key = unsigned int; Element = int; size_type = long unsigned int; Key unused_key = 4294967295; Element unused_element = 2147483647; Hasher = MurmurHash3_32<unsigned int>; Equality = equal_to<unsigned int>; Allocator = default_allocator<thrust::pair<unsigned int, int> >; bool count_collisions = false; Self = …
```
> [REVIEW] Fix compilation issue with gcc 7.4.0 and CUDA 10.1

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
As of right now in branch-0.15, cuDF DataFrames cannot be constructed from numba arrays: 
```python
>>> from numba import cuda
>>> import numpy as np
>>> a = cuda.to_device(np.arange(10))
>>> b = cudf.DataFrame(a)
File "<stdin>", line 1, in <module>
File "/home/galahad/miniconda3/envs/ns0715-38/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)
File "/home/galahad/miniconda3/envs/ns0715-38/lib/python3.8/site-packages/cudf/core/dataframe.py", line 223, in __init__
if len(arr_interface["descr"]) == 1:
KeyError: 'descr'
```
That is because the `descr` attribute of the `__cuda_array_intereface__` is optional, and Numba device arrays in particular don't have it. This PR applies a small fix to check for the existence of …
> [REVIEW] Small fix for dataframe constructor with cuda array interface objects that don't have `descr` field

- CHANGELOG.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/test/java/ai/rapids/cudf/CudfTestBase.java
This fixes  #5685
This fixes  #5686
This fixes #5706
This fixes a number of things that the cu-spacial team has requested to help them build java bindings for their project.  These include providing a common way to load native dependencies; better access to testing classes that we have written; and opening up the Table constructor so other libraries can return a Table from code in a JNI function.
> [REVIEW] Update java build to help cu-spacial with java bindings [skip-ci]

- CHANGELOG.md
- cpp/src/jit/common_headers.hpp
This addresses a JIT compile error on Power9. I created a corresponding PR for libcudacxx [here](https://github.com/rapidsai/thirdparty-freestanding/pull/3)
The underlying issue is that the 'hacky' headers in `libcudacxx/include/simt/cfloat` define a too small/large value for `LDBL_MIN` and `LDBL_MAX`, which work for x86_64 but are not portable to ppc. See the link above for the type of JIT error encountered with BlazingSQL queries.
The solution I took was to export another CPU architecture define to NVRTC via jitify, which gets picked up by libcudacxx.
> Support for JIT compilation of libcudacxx on ppc64

- CHANGELOG.md
- python/cudf/cudf/tests/test_array_function.py
- python/cudf/cudf/tests/test_concat.py
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_datetime.py
- python/cudf/cudf/tests/test_fill.py
- python/cudf/cudf/tests/test_groupby.py
- python/cudf/cudf/tests/test_indexing.py
- python/cudf/cudf/tests/test_joining.py
- python/cudf/cudf/tests/test_json.py
- python/cudf/cudf/tests/test_pickling.py
- python/cudf/cudf/tests/test_query.py
- python/cudf/cudf/tests/test_replace.py
- python/cudf/cudf/tests/test_reshape.py
- python/cudf/cudf/tests/test_stats.py
- python/cudf/cudf/tests/test_string.py
- python/cudf/cudf/tests/test_text.py
Since the logic for comparing cudf/Pandas objects is in the `assert_eq` utility function, we should aim to use that wherever possible.
cc: @brandon-b-miller
> [REVIEW] Replace use of assert_frame_equal in tests with assert_eq

- CHANGELOG.md
- cpp/benchmarks/column/concatenate_benchmark.cpp
The concatenate benchmark is taking an excessive amount of CI time because it sweeps a large range of parameters. Increasing the range multiplier from 4 to 8 will greatly reduce the number of test cases, which should alleviate the issue.
> [REVIEW] Reduce number of concatenate benchmark test cases

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Recently libcudf stopped supporting casting between timestamp and integral columns which broke the Java bindings.  Without a cast that reinterprets the bits, like the `logical_cast` being added in #5358, Java would need to manifest a duration column first.
This updates the Java bindings for cast to preserve the old behavior of casting between timestamps and integers.  When `logical_cast` is added, support for casting between timestamps and integral types with the old cast method will be removed and instead applications must either use the new cast method in those cases or explicitly cast to a duration first.
> Update JNI cast for inability to cast timestamp and integer types [skip ci]

- CHANGELOG.md
- java/src/main/native/CMakeLists.txt
#5659 added `SPDLOG_INCLUDE` to the JNI cmake, but it only looks under RMM_ROOT/_deps and CONDA_PREFIX/include.  In a non-conda environment CONDA_PREFIX is not going to be set, and RMM_ROOT may be set to where RMM is installed rather than the RMM build directory.  Therefore cmake needs to search for the spdlog includes under RMM_ROOT/include as well.
> Add RMM_ROOT/include to the spdlog search path in JNI build [skip ci]

- CHANGELOG.md
- docs/cudf/source/index.rst
- docs/cudf/source/internals.md
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/core/column_accessor.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/tests/test_column_accessor.py
Begin documenting the internals of cuDF with `ColumnAccessor`. Also renames the `get_by*` methods of `ColumnAccessor` to `select_by*`.
> [REVIEW] Add cuDF internals documentation (ColumnAccessor) 

- CHANGELOG.md
- cpp/src/jit/cache.h
This small PR fixes a docstring in `src/jit/cache.h` to match the implemented behavior (which is consistent with the docstring in `src/jit/cache.cpp`).
This PR is a fix-up of #5758.
> [REVIEW] Update cache docstring.

- CHANGELOG.md
- cpp/src/column/column.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/dictionary/slice_test.cpp
Closes #5768 
When creating a new `cudf::column` from a `cudf::column_view` of a dictionary type that was created by slicing a dictionary column, the new column logic was not accounting for the offset in that sliced view.
This PR corrects the `create_column_from_view` logic (already specialized for dictionary type) which copies the `keys` and `indices` child columns.
Also, the `gtests/DICTIONARY_TEST` was accidentally removed in this change:
https://github.com/rapidsai/cudf/pull/5572/files#diff-7f4ca86c1e86c9dd7460309b8d4da71b
This PR reinstates the gtest and adds a new test case for creating a column from a view.
> [REVIEW] Fix column create from dictionary column view

- CHANGELOG.md
- cpp/benchmarks/reduction/reduce_benchmark.cpp
Runtime 00:22:46 REDUCTION_BENCH
~- [x] fix number of iterations (1000)~
- column sizes are 10k,100k,1M,10M,100M.
This change reduces to ~6.5 minute.
> [REVIEW] Reduce number of cases of reduction benchmark

- CHANGELOG.md
- python/cudf/setup.py
Not all `.pxd` files in the Cython were being exported, because not all directories in `cudf/_lib` were packages that could be discovered by `setup.py`.
Fixes #5809
> [REVIEW] Make Cython subdirs packages and simplify package_data

- CHANGELOG.md
- python/cudf/cudf/_lib/orc.pyx
- python/cudf/cudf/io/orc.py
- python/cudf/cudf/utils/ioutils.py
Fixes #5707
Hive assumes that the metadata is included in ORC files.
In the C++ API, `enable_statistics`'s default is already `true`, so this PR also establishes consistency between the Python and C++ APIs.
No measurable overhead was observed in the benchmark due to enabled statistics.
> [WIP] Enable ORC statistics generation by default

- CHANGELOG.md
- conda/recipes/dask-cudf/meta.yaml
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_series.py
- python/dask_cudf/dask_cudf/backends.py
Reverts PR ( https://github.com/rapidsai/cudf/pull/5774 )
Requires PR ( https://github.com/rapidsai/integration/pull/89 )
Reverts back to @galipremsagar original `tolist`. Also bumps the Dask + Distributed version requirements to 2.22.0+ to include PR ( https://github.com/dask/dask/pull/6444 ).
cc @kkraus14
> Revert fallback for `tolist` being absent

- CHANGELOG.md
- ci/cpu/build.sh
- ci/cpu/prebuild.sh
- conda/recipes/custreamz/meta.yaml
Added `cudf_kafka` to list of run dependencies for custreamz in conda recipe
This closes #5821
> [REVIEW] Add cudf_kafka to the list of custreamz run dependencies in the conda

- CHANGELOG.md
- cpp/include/cudf/detail/iterator.cuh
- cpp/include/cudf/wrappers/dictionary.hpp
This PR makes the `dictionary32` constructor from an `int32` explicit. An implicit constructor here defeats the purpose of being a strongly typed wrapper.
This is a dependency of #5494.
The underlying issue this solves is similar to [a change made](https://github.com/rapidsai/cudf/pull/5735/files#diff-777506cef1eaa73782fd6985a6b0f430L50) in #5735, where timestamps could be constructed from a duration type's representation. Quoting from discussion with @jrhemstad:
> The exact mechanism that caused this `operator*` problem is this:
> Boiling away the cruft, the `operator*` definition looks like this:
> ```
> template <class T, class Period, class Rep>
> enable_if_t
> <
>     is_convertible<T, common_type_t<T, Rep>::type>::value,
>     duration<common_type_t<T, Rep>::type, Period>
> >
> …
```
> [REVIEW] Explicit dictionary constructor

- CHANGELOG.md
- ci/cpu/prebuild.sh
There is an error in the prebuild.sh bash script preventing cudf_kafka and libcudf_kafka packages from being uploaded to anaconda.
this closes #5836
> syntax fix for bash anaconda upload script

- CHANGELOG.md
- python/cudf/cudf/core/abc.py
Leverages a feature in Dask to bypass copying of frames on host. ( https://github.com/dask/distributed/pull/4004 ) This can offer a notable speed up when working with `"dask"` serialization.
cc @quasiben
> Mark host frames as not needing to be writeable

- CHANGELOG.md
- python/cudf_kafka/cudf_kafka/_lib/kafka.pxd
- python/cudf_kafka/cudf_kafka/_lib/kafka.pyx
- python/custreamz/custreamz/kafka.py
get_watermark_offset, unsubscribe, and close are missing from custreamz cython interface. They should be added to kafka.pyx and kafka.pxd
This closes: #5840
> [REVIEW] Added custreamz functions that were missing in interface layer

- CHANGELOG.md
- cpp/include/cudf/detail/copy_if.cuh
- cpp/include/cudf/fixed_point/fixed_point.hpp
PR #5704 added the `fixed_point` type as an official libcudf type through the `type-dispatcher`.
This caused a series of compile warnings like the following:
```
/opt/conda/envs/rapids/conda-bld/libcudf_1596199878217/work/cpp/include/cudf/detail/copy_if.cuh(107): warning: dynamic initialization is not supported for a function-scope static __shared__ variable within a __device__/__global__ function
09:01:26           detected during:
09:01:26             instantiation of "void <unnamed>::scatter_kernel<T,Filter,block_size,has_validity>(cudf::mutable_column_device_view, cudf::size_type *, cudf::column_device_view, const cudf::size_type *, cudf::size_type, cudf::size_type, Filter) [with T=numeric::decimal32, Filter=<unnamed>::boolean_mask_filter<true>, block_size=256, has_validity=true]" …
```
> [REVIEW] Disable numeric::fixed_point for use in cudf::copy_if

- CHANGELOG.md
- cpp/include/cudf/fixed_point/fixed_point.hpp
- cpp/tests/fixed_point/fixed_point_tests.cu
This PR adds an explicit conversion template specialization from `fixed_point` values to `bool`. Below, I explain the problem this is solving in case it's helpful for someone in the future.
While developing the AST interpreter (#5494), I implemented a logical "and" operator. I noticed that the expression `fixed_point_value && true` tries to convert fixed_point to a bool with [this cast operator](https://github.com/rapidsai/cudf/blob/120c871176a47eb27d76cf56a698ae881f493f56/cpp/include/cudf/fixed_point/fixed_point.hpp#L332-L343) but fails to compile (`bool` passes the `is_integral` trait, and is thus an allowed cast by [the `is_supported_construction_value` trait](https://github.com/rapidsai/cudf/blob/120c871176a47eb27d76cf56a698ae881f493f56/cpp/include/cudf/fixed_point/fixed_point.hpp#L66- …
> [REVIEW] Add explicit conversion for fixed_point to bool.

- CHANGELOG.md
- ci/cpu/cudf_kafka/build_cudf_kafka.sh
The cudf_kafka Anaconda package is inconsistent in the version of Python it uses. Some builds result in Python 3.7 while others result in Python 3.8. It seems to be a matter of which build finishes first in CI as to the final version in the package.
Also the custreamz Anaconda package requires that cudf_kafka be manually installed first. It should be the case that installing custreamz from conda should automatically install cudf_kafka.
This closes #5865
> [REVIEW] cudf_kafka python version inconsistencies in Anaconda packages

- CHANGELOG.md
- ci/gpu/build.sh
- python/dask_cudf/dask_cudf/tests/test_distributed.py
As we are proposing dropping `ucx-py` from `rapids-build-env` in PR ( https://github.com/rapidsai/integration/pull/94 ), this explicitly adds `ucx-py` to cuDF's CI, which is needed by [this test]( https://github.com/rapidsai/cudf/blob/0b7ad98c7c2d23e989d57ac47481f5ca9873b58c/python/dask_cudf/dask_cudf/tests/test_distributed.py#L57 ). Also adds `dask-cuda`, which is needed by [these tests]( https://github.com/rapidsai/cudf/blob/0b7ad98c7c2d23e989d57ac47481f5ca9873b58c/python/dask_cudf/dask_cudf/tests/test_distributed.py#L13 ).
> Explicitly require `dask-cuda` and `ucx-py` on CI

- CHANGELOG.md
- conda/recipes/cudf_kafka/meta.yaml
- conda/recipes/custreamz/meta.yaml
- cpp/libcudf_kafka/CMakeLists.txt
libcudf_kafka is not passing its transitive dependencies to custreamz which is causing for docker container image builds to fail for centos7 across all python and cuda versions.
This closes: #5871
> [REVIEW] libcudf_kafka r_path is causing docker build failures on centos7

- CHANGELOG.md
- cpp/src/strings/char_types/char_cases.cu
This is a small code improvement that I did because I recently reviewed https://github.com/rapidsai/cudf/pull/5816 where there was an opportunity to replace two `std::for_each`s with better algorithms (`std::transform` & `std::accumulate`). This then made me wonder if there were other `std::for_each`s that could be replaced. This led me to this code - and led me down a rabbit hole and I spent my Friday evening profiling C++14 vs C++20 `std::accumulate` vs `std::for_each`. I will present the results on the August 28 `Better Code` meeting.
**Summary:** Don't use `std::accumulate` when the accumulator is non-trivial (i.e. in this case it would have been a `std::unordered_set`) until C++20 and once you are using it - there is no need to mark parameters or return type of lambda as `&&` or to …
> [REVIEW] Small code improvement / cleanup

- CHANGELOG.md
- cpp/libcudf_kafka/src/kafka_consumer.cpp
Clients who choose to use a single KafkaConsumer object may experience local client socket timeouts which given the previous implementation would break the consumption loop. This changes so that the consumption loop is not broken on that event.
This closes #5886
> [REVIEW] Do not break consumption loop on local client timeout

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/DeviceMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
After #5815 columns created from a contiguous table are not incrementing the refcount of the underlying device memory buffer.  That means columns are no longer being "sliced" from the buffer such that they are able to hold the buffer open after the buffer closes.  The RAPIDS Accelerator for Apache Spark relies upon this behavior.
This updates the `ColumnVector` constructor for a column built from a contiguous table to increment the reference count of the underlying buffer and add it to the list of items to close when the column is finally closed.  To avoid having to explicitly slice the underlying buffer and create unnecessary object overhead, I exposed the reference counting as a method as has been done in other cudf Java classes.
> Fix reference count on Java DeviceMemoryBuffer after contiguousSplit [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/native/src/CudaJni.cpp
Get rid of the synchronous `cudaMemcpy` and `cudaMemset` calls. For `cudaMemcpy`, reuse the existing stream version; for `cudaMemset` I just changed it since I didn't find any users.
The cpp file got reformatted by clang-format, but the actual change is just getting rid of the native method calling `cudaMemcpy`, and changing `memset` to `asyncMemset`.
Part of https://github.com/NVIDIA/spark-rapids/issues/533.
@jlowe @revans2
> [REVIEW] call cudaMemcpyAsync/cudaMemsetAsync in JNI [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
1. Please write a description in this text box of the changes that are being
made.
Added a more thorough check in `assertColumn`s in` TableTest `and fixed one test that was caught by this change
2. Please ensure that you have written units tests for the changes made/features
added.
Tests with list columns are affected and they now take the new path when `assertColumnsAreEqual` is called.
Fixes https://github.com/rapidsai/cudf/issues/5888
> [REVIEW] Revised assertEquals for List Columns in java tests [skip-ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This fixes an oversight bug with nullcount on child columns for list. I have modified a test as well to show the issue as other tests were not catching this.
> [REVIEW] Fix null count for child device column vector [skip-ci]

- CHANGELOG.md
- java/src/main/native/CMakeLists.txt
After #5933 the Java build fails outside of a conda environment because it cannot find the Arrow includes.  This updates the JNI cmake to locate the Arrow include path.
> Find Arrow include directory for JNI builds [skip ci]

- CHANGELOG.md
- conda/recipes/cudf/meta.yaml
- conda/recipes/cudf_kafka/meta.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/libcudf/meta.yaml
- cpp/tests/jit/jit-cache-multiprocess-test.cpp
- cpp/tests/jit/jit-cache-test.hpp
- python/cudf/cudf/core/dataframe.py
Recent changes to `rmm::mr::get_default_resource()` caused the CUDA context
to be created in the JITCACHE_MULTIPROCESS_TEST before the child process is
forked, which caused the child to not get a context.  This PR fixes the failure.
> [REVIEW] Fix jitcache-multiprocess test failure, fix CUDA 11 related CI issues

- CHANGELOG.md
- ci/benchmark/build.sh
Fixes the following error in libcudf nightly benchmark builds:
```
mkdir: missing operand
```
Forgot to remove this line when updating for S3 functionality.
> [REVIEW] FIX Remove unnecessary mkdir command [skip-ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/tests/test_concat.py
- python/cudf/cudf/tests/test_multiindex.py
Fixes: #5923 
This PR fixes the return type of `MultiIndex.argsort` which previously is a `NumericalColumn` and is now being changed to a `cupy.array` for consistency with `Index.argsort`/`pd.Index.argsort` .
> [REVIEW] Fix return type of `MultiIndex.argsort`

- CHANGELOG.md
- python/cudf/cudf/core/buffer.py
Originally there were some issues in CuPy and Numba with how they implemented `__cuda_array_interface__` and handled other objects that supported it where they couldn't handle `strides` of `None` cleanly. So we added `strides` here with what it should be. However both libraries have since cleaned this up ( CuPy 6.6.0+, https://github.com/cupy/cupy/pull/2669 and Numba 0.46.0+, https://github.com/numba/numba/pull/4609 ) and we require newer versions of both. As some code contains fast paths when `strides` is `None`, switch to using `None` here as we ensure contiguous data in `Buffer`s. This should allow us to take advantage of those fast paths where possible.
> [REVIEW] Just use `None` for `strides` in `Buffer`

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_datetime.py
Fixes: #5939 
This PR fixes issue related to `string` to `datetime64` when all values of the column are null. In this scenario `self[self.notna()]` will always result in empty column, and `self[self.notna()][0]` will lead to index error, hence guarding this code-flow with an all null check.
> [REVIEW] Fix issue related to `string` to `datetime64` column typecast

- CHANGELOG.md
- cpp/src/interop/from_arrow.cu
- cpp/src/io/json/reader_impl.cu
- cpp/src/lists/copying/gather.cu
When compiling libcudf with gcc-9 under CUDA 11, getting these type of errors:
```bash
error: moving a local object in a return statement prevents copy elision
```
Compiler suggests removing the `std::move()` call.
@jrhemstad @kkraus14
> [REVIEW] fix gcc-9 compile errors under CUDA 11

- CHANGELOG.md
- java/src/main/native/src/ScalarJni.cpp
Make the JNI code compile under gcc-9 with CUDA 11.
The file got clang-formatted, the only real change is the last one.
@jlowe @revans2
> [REVIEW] fix JNI gcc-9 compile error [skip ci]

- CHANGELOG.md
- cpp/src/text/edit_distance.cu
When compiling with gcc-9 under CUDA 11, it produces these warnings:
```bash
warning: invalid narrowing conversion from "signed int" to "unsigned long"
```
I think gcc-9 is more strict about type conversions when using the curly brace initialization.
@davidwendt
> [REVIEW] fix gcc-9 warnings

- CHANGELOG.md
- ci/gpu/build.sh
Fixes A100 builds showing this error:
```python
E           OSError: could not create numbered dir with prefix pytest- in /tmp/pytest-of-jenkins after 10 tries
```
cc @kkraus14 @rapidsai/ops
> [REVIEW] Specify `--basetemp` for `py.test` run

- CHANGELOG.md
- java/src/main/native/src/RmmJni.cpp
The JNI can install an RMM memory resource that calls back into Java to handle allocation failures.  If the callback fails to address the issue then it rethrows the C++ exception, but instead of throwing the original exception object it makes a copy of the object at the `std::bad_alloc` level, losing the `what()` details of the specific exception.   This fixes the JNI memory handler to throw the original C++ exception object.
> Fix Java memory resource handler to rethrow original exception object [skip ci]

- Dockerfile
- ci/checks/changelog.sh
- ci/cpu/upload_anaconda.sh
This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.
> [WIP] Update CI scripts to remove references to master [skip ci] 

- CHANGELOG.md
- python/cudf/cudf/tests/test_json.py
- python/cudf/cudf/utils/ioutils.py
If a string passed into a `read_*` call contains `://`, fsspec tries to interpret it as a protocol to read from. We need to catch the error in this situation and continue to pass the string into the actual read call downstream.
Fixes #6046
> [REVIEW] Fix fsspec handling of string with "://"

- CHANGELOG.md
- java/pom.xml
- java/src/main/native/src/TableJni.cpp
This fixes the Java bindings build after #6024 updated the ORC read args structure and removed a field being written by the JNI code.  This also updates the package version from 0.15-SNAPSHOT to 0.16-SNAPSHOT.
> Fix Java build for ORC read args change and update package version [skip ci]

- CHANGELOG.md
- cpp/tests/utilities/column_utilities.cu
While "debugging" and trying to understand the `CUDF_TEST_EXPECT_COLUMNS_EQUAL` code I got down the "call stack" to find a function `print_differences` that is responsible for 2 things:
1. Printing the differences
2. Performing the `EXPECT_EQ` on the difference `thrust::device_vector`
For a function called `print_differences` I was very surprised to find the final `EXPECT_EQ` inside - especially when you combine that with the fact that the first line of the function is:
```cpp
if (differences.size() <= 0) { return; }
```
The options are to remain the function to something like `check_if_any_differences_and_print` but whenever you have to put `AND` or `OR` into a function name - that is a sign you should refactor.
This small clean up job pulls out the `EXPECT_EQ` and renames …
> [REVIEW] Small refactor of `print_differences`

- CHANGELOG.md
- cpp/src/strings/convert/convert_datetime.cu
- cpp/tests/strings/datetime_tests.cpp
Closes #6109 
The `cudf::strings::to_timestamp()` conversion logic was not initializing to year 1970 so if the year is not included in the string/format specifiers the incorrect year was being used.
Also added gtest per examples in #6109
> [REVIEW] Fix to_timestamp to initialize default year to 1970

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ArrowIPCOptions.java
- java/src/main/java/ai/rapids/cudf/ArrowIPCWriterOptions.java
- java/src/main/java/ai/rapids/cudf/StreamedTableReader.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
This does a number of different things around the arrow IPC format for java.
It fixes a bug where we could not read more than a 10MB buffer.
It adds in a few more APIs to be able to better batch reading and writing data.
It provides callbacks to let you know when it needs the GPU and when it no longer needs the GPU to better deal with concurreny.
> [REVIEW] Small fixes and improvements to java Arrow IPC [skip-ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/tests/test_datetime.py
Fixes: #6136 
This PR fixes issue where we weren't handling UTC timezone identifier in string data, which is represented by "Z".
> [REVIEW] Fix issue related to inferring `datetime64` format with UTC timezone in string data

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Closes #6018 
- Guards the warning with column counts. Add "ignore non-numeric columns" to the warnings.
> [REVIEW] Row-wise op warning when necessary

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/tests/CMakeLists.txt
- thirdparty/CMakeLists.txt
As suggested in https://github.com/rapidsai/rmm/pull/538.
@harrism @kkraus14
> [REVIEW] use the CUB submodule in Thrust instead of fetching it

- CHANGELOG.md
- java/src/main/native/CMakeLists.txt
#6182 fixes some issues with going to 1.0.1 for arrow, but it also looks like cub changed locations by default in the build.  This updates the java cmake to look in the new location by default.
> [REVIEW] Fix the java build now that cub has moved locations [skip ci]

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
This fixes the JNI build by updating to the parquet options builders added in #6051.
> Update JNI to use parquet options builder [skip ci]

- CHANGELOG.md
- cpp/include/cudf/detail/search.hpp
- cpp/include/cudf/search.hpp
- cpp/src/search/search.cu
Closes #6193 
The `cudf::contains()` that accepts a `cudf::scalar` does not require a memory-resource since it only returns a `bool`.
No python/cython code updates are required.
> [REVIEW] Remove unnecessary memory-resource parameter in cudf::contains API

- CHANGELOG.md
- cpp/CMakeLists.txt
RMM has transitioned to a header-only library with only the legacy cnmem memory resource remaining in librmm.so.  libcudf has removed all references to cnmem, so it no longer needs the librmm.so dependency.
> Remove librmm dependency for libcudf

- CHANGELOG.md
- java/pom.xml
This updates the Java build to exclude the native shared libs from the sources jar.
> Remove shared libs from Java sources jar [skip ci]

- .github/CODEOWNERS
- CHANGELOG.md
This PR updates the `.github/CODEOWNERS` file so that Ops isn't responsible for `ci/` folders that exist in subdirectories (like the one introduced in #6204, `java/ci`).
The syntax was pulled from the last example in the GitHub docs about the `CODEOWNERS` file here:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#example-of-a-codeowners-file
> [REVIEW] Update CODEOWNERS file [skip-ci]

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
With the latest round of changes to support nested columns the results of some JNI functions are no longer cached.  This means that we can now run into situations where they are used after the original data is freed, and I would much rather have an NPE thrown than get a SEG fault.
> [REVIEW] Add in some JNI checks for null handles [skip ci]

- CHANGELOG.md
- CONTRIBUTING.md
- build.sh
- conda/recipes/libcudf/meta.yaml
- cpp/CMakeLists.txt
- cpp/cmake/Modules/ConfigureArrow.cmake
- cpp/cmake/Modules/ConfigureGoogleBenchmark.cmake
- cpp/cmake/Modules/ConfigureGoogleTest.cmake
- cpp/libcudf_kafka/cmake/Modules/ConfigureGoogleTest.cmake
We historically had a CMake variable to control the cxx11 ABI as we used to build against old ABI projects in Ubuntu, which by default uses the new ABI. This removes this option from the CMake as its no longer used.
If someone absolutely needs the old ABI they can still manually pass in compilers flags via variables like `CMAKE_C_FLAGS`, `CMAKE_CXX_FLAGS`, `CMAKE_CUDA_FLAGS`, etc.
> [REVIEW] Remove cxx11 abi handling from CMake

- CHANGELOG.md
- java/pom.xml
- java/src/main/native/CMakeLists.txt
This is the same change as in #6209 applied to the JNI build.  Ideally this should be merged shortly after that PR.
> Remove CXX11 ABI flag from JNI build [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
- java/pom.xml
- java/src/main/native/CMakeLists.txt
This adds the ability to configure the spdlog logging level on the cmake command-line, defaulting to no logging.
> Add cmake command-line setting for spdlog logging level

- CHANGELOG.md
- cpp/src/io/parquet/page_data.cu
Fixes  
https://github.com/rapidsai/cudf/issues/6200
We weren't respecting row bound capping (skip rows / num rows) when writing out validity bits in the kernel.  Kind of surprised this didn't show up more frequently.  :shrug:
**Please don't merge this until we get confirmation from @williamBlazing that it fixes his issue.**  It seems to have cleared it up for everyone else.
> [REVIEW] Parquet reader bounds checking error fix. 

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/replace/nans.cu
- cpp/src/replace/nulls.cu
- cpp/src/replace/replace.cu
In the process of trying to add dictionary support to the replace functions I found that the `cpp/src/replace/replace.cu` was too large to navigate. Also noticed that it had three distinct sets of functions with no common code between them. Therefore, I split the source into 3 separate files:
- `replace.cu` keeps the `find_all_and_replace()` function (originally coded in 2018 by BlazingSQL and updated by NVIDIA)
- `nulls.cu` now holds the `replace_nulls()` functions and their specializations
- `nans.cu` now holds the `replace_nans()` and `normalize_nans_and_zeros()` functions and specializations
Also, some minor fixes to doxygen formatting were added. No code was changed, only moved.
The header file `cpp/include/cudf/replace.hpp` is not changed and neither are the gtests or python …
> [REVIEW] Split up replace.cu into multiple source files

- CHANGELOG.md
- cpp/include/cudf/io/avro.hpp
- cpp/include/cudf/io/detail/avro.hpp
- cpp/include/cudf/io/detail/json.hpp
- cpp/include/cudf/io/detail/parquet.hpp
- cpp/include/cudf/io/json.hpp
- cpp/include/cudf/io/parquet.hpp
- cpp/include/cudf/strings/translate.hpp
- cpp/src/interop/to_arrow.cpp
- cpp/src/transform/encode.cu
Fixes #6250 
Replace remaining calls to RMM `get_default_resource` with `get_current_device_resource`
> Remove remaining calls to RMM get_default_resource

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
Conda-forge is currently going through a migration from boost 1.72.0 --> 1.74.0. This has seemed to cause some issues where some builds are getting 1.74 at build time and then 1.72 at runtime and is generally causing issues. Pinning to 1.72.0 for now to stabilize things and will move to 1.74 once the migration is done.
> [REVIEW] Pin conda boost-cpp to 1.72.0

- CHANGELOG.md
- cpp/benchmarks/common/generate_benchmark_input.cpp
Issue #6000
Code added in https://github.com/rapidsai/cudf/pull/6174 has a missing return statement that generates an error when compiling with GCC 8.4.
Added a CUDF_FAIL if the type does not match any valid distribution and rewrote the function to use switch statement.
> [REVIEW] Fix compilation error with GCC 8

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
This fixes the JNI build by updating to the ORC options builder APIs added in #6138.
> Update JNI to use ORC options builder [skip ci]

- CHANGELOG.md
- cpp/include/cudf/io/orc.hpp
The deprecated entries from `rmm/mr/device/default_memory_resource.hpp` have been removed along with the file itself.
Only one file was left including it (cpp/include/cudf/io/orc.hpp> and thus causing CI build failures today.
This PR removes the include statement which is no longer needed in order to fix the builds.
> [REVIEW] Remove include statement for missing rmm/mr/device/default_memory_resource.hpp file

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
This fixes the JNI build by updating to the CSV options builder added in #6122.
> Update JNI to use CSV options builder [skip ci]

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
Current code causes a gcc-9 compilation error:
```bash
[exec] /home/rou/src/cudf/java/src/main/native/src/ColumnVectorJni.cpp: In function ‘jint Java_ai_rapids_cudf_ColumnVector_getNativeNumChildren(JNIEnv*, jobject, jlong)’:
[exec] /home/rou/src/cudf/java/src/main/native/src/ColumnVectorJni.cpp:1374:1: error: control reaches end of non-void function [-Werror=return-type]
[exec]  1374 | }
[exec]       | ^
[exec] cc1plus: all warnings being treated as errors
[exec] CMakeFiles/cudfjni.dir/build.make:107: recipe for target 'CMakeFiles/cudfjni.dir/src/ColumnVectorJni.cpp.o' failed
[exec] make[2]: *** [CMakeFiles/cudfjni.dir/src/ColumnVectorJni.cpp.o] Error 1
[exec] CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/cudfjni.dir/all' failed
[exec] make[1]: *** [CMakeFiles/cudfjni.dir/all] …
```
> [REVIEW] fix gcc-9 compile error on ColumnVectorJni.cpp [skip ci]

- CHANGELOG.md
- cpp/tests/utilities_tests/span_tests.cu
Fixes `span_tests.cu` includes missed in https://github.com/rapidsai/cudf/pull/6201.
> [REVIEW] Fix span_tests.cu includes

- CHANGELOG.md
- java/src/main/native/src/RmmJni.cpp
remove the size_map and the related mutex since https://github.com/rapidsai/rmm/issues/302 had been closed
> remove individual size tracking from JNI tracking resource adaptor [skip ci]

- CHANGELOG.md
- cpp/src/dictionary/remove_keys.cu
The `std::move()` call prevents copy elision:
```
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu: In instantiation of ‘std::unique_ptr<cudf::column> cudf::dictionary::detail::_GLOBAL__N__46_tmpxft_00004b4a_00000000_7_remove_keys_cpp1_ii_8f7b9da6::remove_keys_fn(const cudf::dictionary_column_view&, KeysKeeper, rmm::mr::device_memory_resource*, cudaStream_t) [with KeysKeeper = __nv_dl_wrapper_t<__nv_dl_tag<std::unique_ptr<cudf::column> (*)(const cudf::dictionary_column_view&, const cudf::column_view&, rmm::mr::device_memory_resource*, CUstream_st*), cudf::dictionary::detail::remove_keys, 1>, const bool*>; cudaStream_t = CUstream_st*]’:
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:160:65:   required from here
/home/rou/src/cudf/cpp/src/dictionary/remove_keys.cu:83:27: error: …
```
> [REVIEW] fix gcc-9 compilation error

- CHANGELOG.md
- ci/checks/changelog.sh
I'm pretty sure this typo exists in all the other RAPIDS repos too.
> Replace a misspelled reference to `master` branch with `main` branch in a comment in changelog.sh

- CHANGELOG.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/MemoryCleaner.java
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/java/ai/rapids/cudf/UnsafeMemoryAccessor.java
- java/src/main/java/ai/rapids/cudf/nvcomp/BatchedLZ4Compressor.java
- java/src/main/java/ai/rapids/cudf/nvcomp/BatchedLZ4Decompressor.java
- java/src/main/java/ai/rapids/cudf/nvcomp/CompressionType.java
- java/src/main/java/ai/rapids/cudf/nvcomp/Decompressor.java
- java/src/main/java/ai/rapids/cudf/nvcomp/LZ4Compressor.java
- java/src/main/java/ai/rapids/cudf/nvcomp/Nvcomp.java
- java/src/main/java/ai/rapids/cudf/nvcomp/NvcompCudaException.java
- java/src/main/java/ai/rapids/cudf/nvcomp/NvcompException.java
- java/src/main/java/ai/rapids/cudf/nvcomp/NvcompJni.java
- java/src/main/native/CMakeLists.txt
- java/src/main/native/cmake/Modules/ConfigureNvcomp.cmake
- java/src/main/native/cmake/Templates/Nvcomp.CMakeLists.txt.cmake
- java/src/main/native/src/NvcompJni.cpp
- java/src/test/java/ai/rapids/cudf/HostMemoryBufferTest.java
- java/src/test/java/ai/rapids/cudf/UnsafeMemoryAccessorTest.java
- java/src/test/java/ai/rapids/cudf/nvcomp/NvcompTest.java
This adds JNI bindings to the nvcomp compression library.  It also adds:
- a `getLongs` utility method for `HostMemoryBuffer`
- expose ability to get the underlying raw handle of a CUDA stream
- expose `MemoryCleaner` for implementing other objects with leak-checking semantics on garbage collection
- expose allocating a `DeviceMemoryBuffer` on a CUDA stream
Ideally these bindings would be hosted in the nvcomp repo and produce a standalone nvcomp jar artifact, but in the short-term it was deemed better to place them with cudf for now.  The nvcomp bindings need Java definitions for concepts like `HostMemoryBuffer`, `DeviceMemoryBuffer`, CUDA streams, etc. that already exist in the cudf bindings.
> Add JNI bindings to nvcomp [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/frame.py
> [REVIEW] Avoids materializing `RangeIndex` during frame concatnation (when not needed)

- CHANGELOG.md
- cpp/src/io/csv/csv_common.h
- cpp/src/io/orc/writer_impl.cu
- cpp/src/strings/char_types/is_flags.h
Fixes #6333 
gcc-10 also complained about the missing includes.
@OlivierNV
> [REVIEW] fix array out-of-bound errors in Orc writer

- CHANGELOG.md
- README.md
I failed to install the nightly version of cudf via conda command provided in README; `conda install -c rapidsai-nightly -c nvidia -c numba -c conda-forge cudf python=3.6 cudatoolkit=10.2`. And I installed it successfully with `python 3.7`.
According to error log (which partially pasted below), it seems that the nightly version of cudf requires` python[version='>=3.7,<3.8.0a0']`.
So, I am trying to fix conda commands with this PR.  
```
Package libffi conflicts for:
certifi -> python[version='>=3.8,<3.9.0a0'] -> libffi[version='3.2.*|>=3.2.1,<3.3.0a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3a0']
libffi
cudf -> python[version='>=3.7,<3.8.0a0'] -> libffi[version='>=3.2.1,<3.3.0a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3a0']
setuptools -> python[version='>=3.6,<3.7.0a0'] -> …
```
> [FIX] README: fix conda commands for outdated python version [skip-ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/tests/test_accessor.py
- python/dask_cudf/dask_cudf/tests/test_delayed_io.py
`pandas.util.testing` is deprecated ( https://github.com/pandas-dev/pandas/pull/30745 ). The preferred way forward is to use `pandas.testing`. So this updates Dask-cuDF usage accordingly.
> Use `pandas.testing`

- CHANGELOG.md
- java/pom.xml
- java/src/main/native/CMakeLists.txt
- java/src/main/native/cmake/EvalGpuArchs.cmake
- java/src/main/native/src/map_lookup.cu
- java/src/main/native/src/map_lookup.hpp
Native code in `cudf/java` to support looking up a Map column `map<string, string>`. This is very specific to looking up string maps. (The Java bindings for this will follow.)
For some minimal context: A Spark `map<string, string>` column will be represented as a `list_view<struct_view<string_view, string_view>>`. The code in this commit should allow one to look up a "map column" by a `string_view` scalar value, to receive a column of `string_view`, with nulls where the map-row does not contain the key.
Peripherally, I have modified the `java/src/main/native/CMakeLists.txt` for how GPU architectures are detected, bringing it in line with what `libcudf` does.
> [REVIEW] Native code for string-map lookups for cudf-java

- CHANGELOG.md
- cpp/tests/io/parquet_test.cpp
Fixes #6334 
I was able to reproduce the ambiguous constructor build error with devtoolset-7 (based on GCC 7.3.1) and devtoolset-8 (based on GCC 8.3.1).  I can't readily explain why I do not see the error outside of the devtoolset environment with GCC 7.5.0, but it's easy to update the test so all the build environments are happy.
> Fix ambiguous constructor compile error with devtoolset

- CHANGELOG.md
- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
Trivial/minor change to a single `dask_cudf.read_parquet` test.
**Motivation**:
As [dask#6534](https://github.com/dask/dask/pull/6534) nears a "merge-ready" state, I am doing my best to avoid future compatibility problems between dask_cudf and post-6534 dask.  That PR will most likely change the default `"pyarrow"` engine from `ArrowEngine` to `ArrowDatasetEngine`.  That change should not break any `dask_cudf.read_parquet` functionality, but it **will**  (likely) affect the behavior of `dask.dataframe.read_parquet(.., engine="pyarrow")`.  More specifically, the order that hive-partitioned columns are appended to the final DataFrame may differ.
This PR simply avoids the column-index check in one test (`test_roundtrip_from_dask_partitioned`), since it is expected to fail after dask#6534 is …
> Preemptive fix for possible dask_cudf.read_parquet CI failure

- CHANGELOG.md
- java/src/main/native/src/CudfJni.cpp
Closes #6112 
A simple check to make sure libcudf and JNI are built with the same PTDS mode.
@jlowe @abellina
> [REVIEW] make sure ptds mode is compatible between libcudf and JNI [skip ci]

- CHANGELOG.md
- java/README.md
In case anyone is picky about their environment. :)
```console
$ sudo apt install libboost-filesystem-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
libboost-filesystem1.71-dev libboost-filesystem1.71.0 libboost-system1.71-dev libboost-system1.71.0 libboost1.71-dev
Suggested packages:
libboost1.71-doc libboost-atomic1.71-dev libboost-chrono1.71-dev libboost-container1.71-dev libboost-context1.71-dev libboost-contract1.71-dev libboost-coroutine1.71-dev libboost-date-time1.71-dev
libboost-exception1.71-dev libboost-fiber1.71-dev libboost-graph1.71-dev libboost-graph-parallel1.71-dev libboost-iostreams1.71-dev libboost-locale1.71-dev libboost-log1.71-dev libboost-math1.71-dev …
```
> [REVIEW] add instruction for building libboost_filesystem from source [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
- java/pom.xml
- java/src/main/native/CMakeLists.txt
Same fix as https://github.com/rapidsai/rmm/pull/577.
The existing code doesn't actually allow you to turn off rmm logging from the command line since passing in `OFF` is considered `false` by cmake, so the `if` clause is executed, setting the logging level to `INFO`.
I left the default as `INFO` in the maven file. @jlowe do we want to set it to `OFF`?
@harrism
> [REVIEW] fix rmm logging level so that it can be turned off

- CHANGELOG.md
- java/src/main/native/src/map_lookup.cu
Newer gcc versions complain about this:
```console
[exec] [ 91%] Building CUDA object CMakeFiles/cudfjni.dir/src/map_lookup.cu.o
[exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu: In instantiation of ‘std::unique_ptr<cudf::column> cudf::_GLOBAL__N__57_tmpxft_00012f16_00000000_10_map_lookup_compute_80_cpp1_ii_ab7b9cf2::get_gather_map_for_map_values(const cudf::column_view&, cudf::string_scalar&, rmm::mr::device_memory_resource*, cudaStream_t) [with bool has_nulls = true; cudaStream_t = CUstream_st*]’:
[exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:158:104:   required from here
[exec] /home/rou/src/cudf/java/src/main/native/src/map_lookup.cu:128:28: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
[exec] …
```
> [REVIEW] remove unnecessary std::move() call [skip ci]

- CHANGELOG.md
- build.sh
Currently if `PARALLEL_LEVEL` is not set, it defaults to an empty string. Later in the script this causes a command to look like: `python setup.py build_ext --inplace -j` which isn't allowed as for Python you need to add a number of threads after `-j`.
To fix this, defaulting `PARALLEL_LEVEL` to the output of `nproc` which should be the default behavior of passing `-j` anyway.
> [REVIEW] Fix `build.sh` when `PARALLEL_LEVEL` env variable isn't set

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/io/parquet.py
Hello from Chicago 👋 
I've been getting familiar with `cudf` recently. I wanted to contribute back to this project, so I ran `pylint` over this project's Python code. A lot of the warnings from that linter are subjective style things that I think are best ignored or left to maintainers, but I did find a few small warnings that I think should be fixed.
This PR proposes removing a few unused variables. I think this makes the affected code a little easier to read, and reduces the risk of name conflicts between variables.
I specifically am proposing fixing these warnings:
```text
python/cudf/cudf/core/dataframe.py:7312:8: W0612: Unused variable 'idx' (unused-variable)
python/cudf/cudf/core/reshape.py:450:11: W0612: Unused variable 'var' (unused-variable)
python/cudf/cudf/core/series.py:980:8: …
```
> [REVIEW] remove unused variables

- CHANGELOG.md
- java/src/main/native/cmake/Templates/Nvcomp.CMakeLists.txt.cmake
This updates the JNI build to pull a fixed commit from nvcomp rather than from branch-1.1 which could move and thus potentially cause problems with providing a repeatable build for cudf 0.16.
> Update JNI build to pull fixed nvcomp commit [skip ci]

- CHANGELOG.md
- java/src/main/native/cmake/Templates/Nvcomp.CMakeLists.txt.cmake
Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column_accessor.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/datasets.py
- python/cudf/cudf/tests/dataset_generator.py
- python/cudf/cudf/tests/test_s3.py
- python/cudf/cudf/utils/utils.py
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/io/orc.py
Following up on #6400 ...I'm starting to get familiar with `cudf`, and wanted to contribute back. Using `pylint`, I think I've found another class of minor issue that could lead to bugs in this project's Python code.
There are several places in this project where functions use mutable types like dictionaries and lists as default values. This is a dangerous practice, because when you use such literals as defaults, Python creates them and stores them one time.
For example:
```python
import uuid
def do_stuff(d={}):
d[str(uuid.uuid4())] = "hello"
return d
do_stuff()
do_stuff()
do_stuff()
```
This PR proposes fixing those cases
I chose to fix cases like this by defaulting those arguments to `None` and then immediately replacing them, like this
```python
def do_stuff(d=None):
d = d or None …
```
> [REVIEW] fix uses of dangerous default values in Python code

- CHANGELOG.md
- python/cudf/cudf/tests/test_feather.py
- python/cudf/cudf/tests/test_hdf.py
- python/cudf/cudf/tests/test_json.py
- python/cudf/cudf/tests/test_parquet.py
- python/cudf/cudf/tests/test_serialize.py
- python/cudf/cudf/tests/utils.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Replaces more usages of `pandas.util.testing` with `pandas.testing`. The former is deprecated and the latter is recommended going forward.
xref: https://github.com/pandas-dev/pandas/pull/30745
> Use `pandas.testing` in `cudf`

- CHANGELOG.md
- java/src/main/native/cmake/Templates/Nvcomp.CMakeLists.txt.cmake
When nvcomp pushed new commits to branch-1.1 it broke the JNI build since shallow clones are not allowed on arbitrary commits.  This updates the JNI build to fetch the v1.1.0 tag from nvcomp.
> Update build to fetch nvcomp v1.1.0 [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/HostColumnVectorCore.java
Minor fix to expose the list and struct getters (even if inefficient) to assist testing and making it inline with other getters on the host side.
> [REVIEW] Make java apis getList and getStruct public [skip ci]

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
Downstream users developing against libcudf will need the dlpack headers in order to properly compile code that uses certain libcudf headers. We may want to split into a `libcudf-dev` package in the future, but until we do that we should enforce a `run` requirement on dlpack to make sure that downstream packages that build against libcudf have the necessary headers.
cc @jakirkham
> [REVIEW] add dlpack to libcudf conda run section

- CHANGELOG.md
- java/buildscripts/build-info
Issue #6490 
**Describe the bug
There is an offensive word in the cuDF java binaries.
Steps/Code to reproduce bug
Our cuDF java binaries are built from the source code of nvspark/cudf Gitlab repo, which is the down-stream of this GitHub rapidsai/cudf.
When building cuDF java binaries, the build-info is collected via the script java/buildscripts/build-info.
In this build-info (an example showing as below), the down-stream repo URL contains the offensive word.
version=0.16-SNAPSHOT
user=
revision=9ec5093e18dcea3978931288d14f0476b58347ae
branch=HEAD
date=2020-09-27T03:53:03Z
url=https://gitlab-master.nvidia.com/nvspark/cudf.git
This build-info will be packaged into the cuDF binaries, and be released onto public maven repo.
Expected behavior
cuDF java binaries should not have any offensive …
> Remove repo URL from Java build-info [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
Adds the identical method that old builder has for building columns to the new ColumnBuilder, plus a `toString` and some nits.
> [REVIEW] Add helper method to ColumnBuilder with some nits [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
Fixes #6117 
Sets `JITIFY_PRINT_LOG` to zero via cmake, since by default jitify prints its log to `stdout`, which can corrupt application data generated on `stdout`.
See also https://github.com/NVIDIA/jitify/issues/79
> Disable Jitify log printing

- CHANGELOG.md
- cpp/src/text/subword/wordpiece_tokenizer.cu
Closes #6501 
The `mark_string_start_and_ends` kernel did not have enough threads to set the end-of-string marker for the last string if the number of rows was divisible by `THREADS_PER_BLOCK=64`. The end-of-string marker relies on the trailing offset at `num_strings+1` to work correctly. If the number of strings is not divisible by 64 then extra threads are launched for one block and the logic handles the edge case correctly.
> [REVIEW] Fix end-of-string marking boundary condition in subword-tokenizer

- CHANGELOG.md
- cpp/src/io/parquet/page_data.cu
- python/cudf/cudf/tests/test_parquet.py
Fixes : https://github.com/rapidsai/cudf/issues/6477
Core issue was the order in which pages were being visited when doing an exclusive_scan_by_key at the end of the preprocess step.
Tests added.
> Fix issue reading parquet files containing lists with multiple row groups.

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
This updates Java's `ColumnVector` JNI interface to create separate address and length accessors for the data, validity, and offset buffers.  The original API returned the address and length in a `long[]` which causes the JNI to callback into the JVM to create the array.  Even though it's more JNI calls, it turns out to be more efficient to access the address and length separately, as it avoids the JNI->JVM callback and avoids temporary object creation.
This also updates `DeviceColumnViewAccess` to be a static class since it really has no reason to reach back into the parent class instance.  Everything it needs can be provided via static method calls using the view handle associated with it.
Using a microbenchmark that stresses table metadata creation in the plugin, which in turn hammers …
> Refactor DeviceColumnViewAccess to avoid JNI returning an array [skip ci]

- CHANGELOG.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
- java/src/main/native/CMakeLists.txt
This fixes the JNI build after libcudf.so became composed of many other shared libraries.
> Adapt JNI build to libcudf composition of multiple libraries [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/lists.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/tests/test_core.py
memory_usage calls were throwing a ```AttributeError: 'ListDtype' object has no attribute 'itemsize'```
exception when called on list columns. Fix by implementing ```__sizeof__``` for list columns
> [REVIEW] Fix memory_usage calls for list columns

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
This modifies the Java native dependency loading logic to use a thread pool to load the dependencies in parallel.  This reduces the startup time of a simple Java application that uses cudf from 2 seconds to 1.3 seconds on my test system.
> Load JNI library dependencies with a thread pool [skip ci]

- CHANGELOG.md
- java/src/main/native/src/RmmJni.cpp
https://github.com/rapidsai/rmm/pull/601 changed the pool resource initialization so that instead of passing max std::size_t value to indicate no limit, it now uses `thrust::optional<std::size_t>`.  Passing the old value causes startup to fail with an exception like this:
```
ai.rapids.cudf.CudfException: RMM failure at: /home/jlowe/miniconda3/envs/cudf10.1/include/rmm/mr/device/pool_memory_resource.hpp:102: Error, Maximum pool size required to be a multiple of 256 bytes
```
This updates the JNI code to pass `thrust::nullopt` instead of the old default value when there's no specified pool limit.
> Fix JNI RMM initialize with no pool allocator limit [skip ci]

- CHANGELOG.md
- cpp/include/cudf/reshape.hpp
- cpp/src/reshape/byte_cast.cu
Found this when I noticed a doxygen error in `reshape.hpp`
https://github.com/rapidsai/cudf/blob/47a3d32cc343293c5240c1c60f0dcd3ef7e26691/cpp/include/cudf/reshape.hpp#L75
This line should be right before the end bracket for the `namespace cudf` line so the `cudf::byte_cast` appears in the correct doxygen group.
Noticed that `cudf::byte_cast` includes a `cudaStream_t` parameter unlike all the other APIs in this header file. This PR creates the appropriate `cudf::detail::byte_cast` and move the `cudaStream_t` parameter to that call per the coding guidelines here:
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/docs/TRANSITIONGUIDE.md#streams
> [REVIEW] Create cudf::detail::byte_cast for cudf::byte_cast

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
#6430  added struct_type support to to_arrow()/from_arrow().
The change in signature broke cudf/jni code.
```     [exec] /home/mithunr/workspace/dev/cudf/01/java/src/main/native/src/TableJni.cpp: In function ‘jlong Java_ai_rapids_cudf_Table_convertCudfToArrowTable(JNIEnv*, jclass, jlong, jlong)’:
[exec] /home/mithunr/workspace/dev/cudf/01/java/src/main/native/src/TableJni.cpp:1193:45: error: invalid initialization of reference of type ‘const std::vector<cudf::column_metadata>&’ fr
om expression of type ‘std::vector<std::__cxx11::basic_string<char> >’
[exec]      *result = cudf::to_arrow(*tview, state->column_names);
[exec]                                       ~~~~~~~^~~~~~~~~~~~
[exec] In file included from /home/mithunr/workspace/dev/cudf/01/java/src/main/native/src/TableJni.cpp:24: …
```
> Fix JNI build broken by to_arrow signature change

- CHANGELOG.md
- java/src/main/native/src/CudaJni.cpp
Looking at a recent Nsight profile of a Java application using cudf, I noticed a lot of CPU samples in `cudaGetDevice`.  This is caused by the `auto_set_device` calls made in each cudf JNI function to ensure each thread is using the same device used when RMM was initialized.  Initially we thought calling `cudaGetDevice` would be "cheap enough", but this is apparently not the case, at least when profiling under Nsight.
This changes the cudf JNI code to track the thread's CUDA device in a thread local rather than needing to call `cudaGetDevice` on each cudf call to obtain it.  This saved 0.5ms per `Table.contiguousSplit` call in a microbenchmark, and I noticed it also significantly reduced the time dilation we've seen in Nsight profiles of cudf Java applications.
> Use thread-local to track CUDA device in JNI [skip ci]

- CHANGELOG.md
- cpp/src/join/hash_join.cu
The `hash_join` code was using `0` for the stream instead of the provided stream. Not only was this a bug, but it also led to an ambiguous constructor because `rmm::device_scalar<int> failure(0, 0);` was ambiguous.
> Use correct stream in hash_join

- CHANGELOG.md
- java/src/main/native/src/RmmJni.cpp
This fixes the JNI build by updating to the new device memory resource API that uses `rmm::cuda_stream_view` instead of `cudaStream_t` directly.
> Update JNI to new RMM cuda_stream_view API [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
This changes the JNI native dependency load order to always load libcudf_base.so before loading libcudf_comms.so.
When built with some toolchains, libcudf_comms.so has an explicit dependency on libcudf_base.so whereas with other toolchains it does not.  The JNI code currently loads libcudf_base.so and libcudf_comms.so in parallel, but this only works when building with a toolchain smart enough to realize libcudf_comms.so does not need libcudf_base.so despite linking against it.
> Fix JNI native dependency load order [skip ci]

- CHANGELOG.md
- java/src/main/native/CMakeLists.txt
This fixes some changes to the JNI cmake that were checked in incorrectly.
> Revert bad CMake changes for JNI [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Aggregation.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
This fixes two issues related to Java classes and native dependencies:
- HostColumnVector loads native libraries despite not having any native methods
- Aggregation does not load native libraries yet has native methods
> Fix Java HostColumnVector unnecessarily loading native dependencies [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Fixes: #6639 
This PR adds parameter validation to raise error when `axis=1` for some of the dataframe APIs that rely on cupy. This also has changes to fix where the strings of other errors were being truncated.
> [REVIEW] Add error message for unsupported `axis` parameter in DataFrame APIs

- CHANGELOG.md
- cpp/src/io/orc/stripe_data.cu
- cpp/src/io/orc/stripe_enc.cu
Replaced SHFL_XOR calls with cub::WarpReduce in `stripe_data.cu`
The performance impact for this PR is compared in this [gist](https://gist.github.com/kaatish/621b87e81cd1f4f76da0ad82afc4ccda). The worst slowdown is 7% and best speedup is 5%.
> [REVIEW] Replaced SHFL_XOR calls with cub::WarpReduce

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/DType.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/main/java/ai/rapids/cudf/HostColumnVectorCore.java
- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/DecimalColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/ScalarTest.java
This PR supports decimal fetching/appending for (Host)ColumnVector.  In specific, with this PR, we are able to get/append `java.math.BigDecimal` from/to ColumnVector. This is a minimum work to provide essential interface for the plugin-side development.
* Considering `java.math.BigDecimal` is a boxed type,  this PR only implemented `Builder.appendBoxed` method for BigDecimal (left `Builder.appendArray` unsupported).
* Each BigDecimal will be verified before appending to HostColumnVector.Builder, which ensures:
* All scales in same HostColumnVector are consistent.
* Transfer BigDecimal to cuDF::fixed_point without any precison loss. If any overflow occurs, corresponding exception will be thrown.
* Decimal types can be used as basic type of nested types.
> [REVIEW] Support fixed-point decimal for HostColumnVector [skip ci]

- CHANGELOG.md
- cpp/include/cudf/dictionary/detail/iterator.cuh
- cpp/include/cudf/utilities/traits.hpp
This adds a pair iterator for dictionary column types that returns key/valid pairs for each row access.
This is useful in PR #6585 and will be useful in supporting dictionary type columns in `cudf::reduce`.
This PR also adds an `cudf::is_dictionary` to `traits.hpp`
The `cudf::is_unsigned` was declared in an odd place in the `traits.hpp` and so was also moved in this PR.
> [REVIEW] Add cudf::dictionary::make_dictionary_pair_iterator

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Cuda.java
This should make `nvcomp` use the correct cuda stream.
@jlowe @abellina
> [REVIEW] Explicitly set legacy or per-thread default stream in JNI [skip ci]

- CHANGELOG.md
- cpp/include/cudf/round.hpp
- cpp/src/round/round.cu
- cpp/tests/round/round_tests.cpp
This PR is the final of 3 PRs and resolves https://github.com/rapidsai/cudf/issues/3790. 
1. Implement `cudf::round` floating point and integer types (`HALF_UP`) https://github.com/rapidsai/cudf/pull/6562
2. Implement `cudf::round` floating point and integer types (`HALF_EVEN`) https://github.com/rapidsai/cudf/pull/6647
3. Implement `cudf::round` `decimal32` & `decimal64` (`HALF_UP` and `HALF_EVEN`) :arrow_backward: 
The PR to do list is as follows:
> [REVIEW] Implement `cudf::round` `decimal32` & `decimal64` (`HALF_UP` and `HALF_EVEN`)

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/nvcomp/BatchedLZ4Decompressor.java
- java/src/main/java/ai/rapids/cudf/nvcomp/Decompressor.java
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/DecimalColumnVectorTest.java
Fixes the following resource leaks that were triggering leak warnings on JVM shutdown in the cudf Java unit tests:
- nvcomp decompression metadata objects do not release the underlying resource on `close`
- ColumnVectorTest duration type unit tests do not close a vector copied back to the host for verification
- DecimalColumnVectorTest error checking tests do not close the column vector when the constructor does not throw
> Fix leak warnings in JNI unit tests [skip ci]

- CHANGELOG.md
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/tests/test_csv.py
Fixes: #6688 
`na_rep` was not being applied to column names, column names can be `None` too. So this PR introduces changes that will apply `na_rep` for column names as well.
> [REVIEW] Apply `na_rep` to column names in csv writer

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/DType.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This adds support for LIST and STRUCT column types to JCudfSerialization.
In addition this contains fixes to problems in the Java nested column builder code and column equality testing code that were found with the jcudf nested type unit tests.  A simpler syntax for adding test code to build tables with list and struct column elements was also added.
> Add nested type support to Java table serialization [skip ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/io/parquet.py
- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
Simple fix for `read_parquet` bug.  Without this PR, explicitly setting `index=False` will result in failures when there is actually an index name listed in the "pandas metadata".
> Handle index=False in dask_cudf.read_parquet

- CHANGELOG.md
- cpp/benchmarks/CMakeLists.txt
- java/pom.xml
The cmakelists for cuDF benchmarks (which are not built by default) failed to compile when
ARROW_STATIC_LIB was enabled. This fixes that failure. 
Also adds a cmake variable passthrough to the cuDF JNI pom.xml to enable building
cuDF JNI bindings when the cuDF build directory is not the default of cudf/cpp/build, 
as is common when using rapids-compose to build from source.
> Fix cuDF benchmarks build with static Arrow lib and fix rapids-compose cuDF JNI build [skip-ci]

- CHANGELOG.md
- cpp/include/cudf/detail/copy.hpp
- cpp/include/cudf/reduction.hpp
- cpp/src/reductions/all.cu
- cpp/src/reductions/any.cu
- cpp/src/reductions/max.cu
- cpp/src/reductions/min.cu
- cpp/src/reductions/product.cu
- cpp/src/reductions/simple.cuh
- cpp/src/reductions/sum.cu
- cpp/src/reductions/sum_of_squares.cu
Closes #6717 
This PR removes the 2nd type-dispatch from the simple reduce operations: `any()`, `all()`, `min()`, `max()`, `sum()`, `product()`, and `sum_of_squares()`. It is replaced with logic using either the same type as the input column type or a hardcoded type as follows:
- `any()` and `all()` expect only `BOOL8` as the output type
- `min()` and `max()` expect the output type to match the column input type
- `sum()`, `product()`, and `sum_of_squares()` allow any output type but may incur an extra scalar cast operation
The cast operation is only required if the output type does not match the input type or if the output type is not `INT64` for integer columns or `FLOAT64` for floating point columns. The extra cast only applies to `sum()`, `product()`, and `sum_of_squares()` ops.
This …
> [REVIEW] Remove 2nd type-dispatcher call from cudf::reduce for simple operations

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR simply adds Java bindings for the `is_timestamp` method, along with a unit test.
> [REVIEW] Add Java bindings for is_timestamp [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
Adds a JCudfSerialization method to concatenate serialized tables into a ContiguousTable
> Add Java API to concatenate serialized tables to ContiguousTable [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
This updates and exposes some APIs to make it simpler to build nested types on the CPU before sending the data to the GPU for processing.
> Update nested JNI builder so we can do it incrementally. [skip ci]

- CHANGELOG.md
- python/cudf/cudf/tests/test_scalar.py
pytest-xdist expects the parameters for each pytest to be in sorted order. Hence it will fail when it hits `test_scalar_invalid_implicit_conversion` pytest. This PR will sort the input parameters.
> [REVIEW] Fix sort order of parameters in `test_scalar_invalid_implicit_conversion` pytest

- CHANGELOG.md
- cpp/include/cudf/column/column_view.hpp
- cpp/include/cudf/utilities/traits.hpp
- cpp/src/column/column_view.cpp
- cpp/src/filling/fill.cu
- cpp/tests/column/column_view_test.cpp
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/DecimalColumnVectorTest.java
Currently, we will get unexpected results when creating decimal column vectors from decimal scalar and row number. The reason is that we perform `in_place_fill` with fixed-point data type directly.
This PR attempts to fix this problem through peforming `in_place_fill` with underlying data type of fixed-point columns. Related tests are provided in java package.
> [REVIEW] Support creating decimal vectors from scalar

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/test/java/ai/rapids/cudf/ReductionTest.java
Recently #6717 changed some of the output formats that a reduction can support.  This updates the java APIs to clean that up.
This also fixes #6783 but only as a temporary work around.
> Update java reduction APIs to reflect C++ changes [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR is about to support building decimal columns with Table.TestBuilder, which is widely used in automatic tests of spark-rapids plugin.
> [REVIEW] Support building decimal columns with Table.TestBuilder [skip ci]

- CHANGELOG.md
- cpp/include/cudf/column/column_device_view.cuh
- cpp/include/cudf/detail/iterator.cuh
- cpp/src/replace/clamp.cu
- cpp/tests/replace/clamp_test.cpp
> Implement `cudf::clamp` for `decimal32` and `decimal64`

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
This fixes the JNI build after #6648.  The JNI data_sink was updated to use RMM stream views before the data_sink API was updated.
> Fix JNI build [skip ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
Fixes the following issues in `ColumnBuilder`:
- The builder is `AutoCloseable` but cannot be closed after a column is built
- Some column building code uses builders without a try-with-resources to close them safely on exception
> Fix resource management in Java ColumnBuilder [skip ci]

- CHANGELOG.md
- java/ci/Dockerfile.centos7
- java/ci/README.md
- java/ci/build-in-docker.sh
Update Dockerfile to install CMake 3.19 as RMM required 3.18+
Add cmake into PATH in build script
Change PTDS default ON
> Use CMake 3.19 for RMM when building cuDF jar [skip ci]

- CHANGELOG.md
- java/ci/build-in-docker.sh
For the internal cudf jar building, we'll use a settings.xml to define the maven repo.
Use the settings.xml if it exists in ci.
No change for the external build.
> Use settings.xml if existing for internal build [skip ci]

- CHANGELOG.md
- cpp/include/cudf/detail/copy_if.cuh
- cpp/tests/stream_compaction/apply_boolean_mask_tests.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR attempts to enable `copy_if` for fixed-point decimal columns, in order to support filtering table which includes decimal columns.
> [REVIEW] Enable copy_if for fixed-point decimal columns

- CHANGELOG.md
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
This PR introduces stopgap solution to write categorical data to csv. In addition, there are also changes to raise error messages to some of the existing issues in CSV reader and writer.
> [REVIEW] Enable workaround to write categorical columns in csv

- CHANGELOG.md
- python/cudf/cudf/tests/test_categorical.py
- python/cudf/cudf/utils/utils.py
This PR closes part of #2269 and is created in place of https://github.com/rapidsai/cudf/pull/5306 . 
I created this PR because that PR https://github.com/rapidsai/cudf/pull/5306  got messy after rebasing from an earlier branch of `cudf`. 
The purpose of this is to fix the below pandas Categorical assignment which in turn fixes  #2269  .  
```python
import numpy as np
import pandas as pd
import cudf
head = cudf.DataFrame({'a':[1]})
cat_s = pd.Categorical.from_codes(np.zeros(len(head), dtype=int), categories=['cat.csv'])
head.assign(path=cat_s)
```
> [REVIEW]Fix categorical scalar insertion

- CHANGELOG.md
- cpp/include/cudf/detail/copy_range.cuh
- cpp/src/copying/copy_range.cu
- cpp/tests/copying/copy_range_tests.cpp
> Implement `cudf::copy_range` for `decimal32` and `decimal64`

- CHANGELOG.md
- cpp/include/cudf/detail/copy_if_else.cuh
- cpp/src/copying/copy.cu
- cpp/src/dictionary/replace.cu
- cpp/src/replace/nans.cu
- cpp/tests/copying/copy_range_tests.cpp
- cpp/tests/copying/copy_tests.cu
> Implement `cudf::copy_if_else` for `decimal32` and `decimal64`

- CHANGELOG.md
- cpp/src/strings/copying/copying.cu
- cpp/tests/replace/replace_nulls_tests.cpp
Fixes #6803 
This optimizes string slice copying in the case where the string column view starts at offset 0.  In that case the offset values do not need to be modified, and all the column buffers can be copied.
> Avoid gather when copying strings view from start of strings column

- CHANGELOG.md
- cpp/include/cudf/lists/detail/scatter.cuh
- cpp/tests/copying/scatter_list_tests.cu
Addendum to https://github.com/rapidsai/cudf/pull/6768, to support scatter on columns of type `list<struct>`.
Depends on #6768.
The hard part was the tests.
~(This branch is based off of that in #6768, and shows all commits from that PR. Only the last 4 commits are material to `struct_view` support.)~
> Add support for scatter() on lists-of-struct columns

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
The parameter order of writeParquetBufferBegin was different between JNI and native.
> Correct the param order of writeParquetBufferBegin[skip ci]

- CHANGELOG.md
- cpp/src/groupby/hash/groupby.cu
- cpp/src/groupby/hash/groupby_kernels.cuh
The compile time/size of `cpp/src/groupby/hash/groupby.cu` is one of the top offenders for building libcudf.
Current top 5 slowest compiles:
```
1813479 CMakeFiles/cudf_base.dir/src/sort/sort.cu.o
1805726 CMakeFiles/cudf_base.dir/src/sort/stable_sort.cu.o
1091904 CMakeFiles/cudf_base.dir/src/stream_compaction/drop_duplicates.cu.o
979061 CMakeFiles/cudf_base.dir/src/groupby/hash/groupby.cu.o  <----
685116 CMakeFiles/cudf_join.dir/src/join/semi_join.cu.o
...
```
The two sort.cu files may be improved in a later PR. The `drop_duplicates.cu` is being addressed in #6822 
The simple change here is to `compute_single_pass_aggs` functor defined here: https://github.com/rapidsai/cudf/blob/591bead156398635aa39a2c3d7f441d9dfddf39b/cpp/src/groupby/hash/groupby_kernels.cuh#L65-L66
The …
> [REVIEW] Move template param to member var to improve compile of hash/groupby.cu

- CHANGELOG.md
- cpp/src/copying/contiguous_split.cu
- cpp/tests/copying/split_tests.cpp
This PR attempts to address #6842, which may be caused by multiple reasons.
For now, one certain problem is contiguous splitting on null (fully invalid) string columns, which only contains single child column (offset column). This PR is about to fix this problem with below changes:
1.  Skip non-exist chars buffer for string column views when `setup_source_buf_info`.
2. Adapt size computing for empty leaf columns when`build_output_columns`.
3. Provide specialized test case for null string columns, which will fail without above changes.
> [REVIEW] Fix contiguous split of null string columns

- CHANGELOG.md
- cpp/src/io/orc/orc_common.h
- cpp/src/text/subword/detail/codepoint_metadata.ah
- cpp/src/text/subword/detail/cp_data.h
- cpp/src/text/subword/detail/hash_utils.cuh
Newer gcc compilers seem to be unhappy about not including `cstdint`:
```console
/home/rou/src/cudf/cpp/src/io/orc/orc_common.h(24): error: identifier "uint32_t" is undefined
```
> [REVIEW] fix uint32_t undefined errors

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
- cpp/include/cudf/column/column_device_view.cuh
- cpp/include/cudf/detail/utilities/alignment.hpp
- cpp/include/cudf/detail/utilities/cuda.cuh
Closes #6857 
This function contains only C++ STL code and no CUDA code. Also, including it in the `column_device_view.cuh` required a new dependency on `cub/cub.cuh` (per the `cuda.cuh`) as found when building blazingSQL.
> Move align_ptr_for_type() from cuda.cuh to alignment.hpp

- CHANGELOG.md
- cpp/benchmarks/type_dispatcher/type_dispatcher_benchmark.cu
Compile error for `type_dispatch_benchmark.cu`
```
[40+16+94=149] Building CUDA object benchmarks/CMake...H.dir/type_dispatcher/type_dispatcher_benchmark.cu.o
FAILED: benchmarks/CMakeFiles/TYPE_DISPATCHER_BENCH.dir/type_dispatcher/type_dispatcher_benchmark.cu.o 
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_ -Igoogletest/install/include -Igooglebenchmark/install/include -I_deps/thrust-src -I_deps/jitify-src -I_deps/libcudacxx-src/include -I/usr/local/cuda/targets/x86_64-linux/include -Iinclude -I../include -I../ -I../src -I../thirdparty/dlpack/include -I/conda/envs/rapids/include -I../benchmarks -Xcompiler -Wno-parentheses -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 --expt-extended-lambda …
```
> Fix compile error in type_dispatch_benchmark.cu

- CHANGELOG.md
- cpp/src/copying/concatenate.cu
- cpp/tests/copying/concatenate_tests.cu
Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

- CHANGELOG.md
- ci/benchmark/build.sh
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda10.2.yml
- conda/environments/cudf_dev_cuda11.0.yml
- conda/recipes/dask-cudf/run_test.sh
Avoid dependency resolution failure in latest version of pip by explicitly specifying versions for dask and distributed
Closes: #6868
> Specify git branches to avoid pip unresolvable issues

- CHANGELOG.md
- python/cudf/cudf/tests/test_array_function.py
- python/cudf/cudf/tests/test_array_ufunc.py
- python/cudf/cudf/utils/utils.py
This pr adds index handling when dispatching to cupy functions with `__ufunc__` and `__array_function__` for cudf.Series.  
This PR does the following: 
Please note that I am unsure how to handle `list` inputs here. 
The problem being solved here is below:
With this **PR #6839** we get the correct index when we do the following:
```python
>>> cudf_s1 = cudf.Series(data=[-1, 2, 3, 0], index=[2, 3, 1, 0])
>>> cudf_s2 = cudf.Series(data=[-1, -2, 3, 0], index=[2, 3, 1, 0])
>>> o = np.logaddexp(cudf_s1, cudf_s2)
>>> o.index
Int64Index([2, 3, 1, 0], dtype='int64')
>>> print(o)
2   -0.306853
3    2.018150
1    3.693147
0    0.693147
dtype: float64
```
On **Master** we get:
```python
>>> cudf_s1 = cudf.Series(data=[-1, 2, 3, 0], index=[2, 3, 1, 0])
>>> cudf_s2 = cudf.Series(data=[-1, -2, 3, 0], …
```
> [REVIEW]Handle index when dispatching __array_function__ and __array_ufunc__ to cupy for cudf.Series

- CHANGELOG.md
- java/src/main/native/src/map_lookup.cu
#6875 updated the gather bounds checking enums which broke the `map_lookup` code in the JNI.  This updates the code to use the new API.
> Update JNI to new gather boundary check API [skip ci]

- CHANGELOG.md
- cpp/include/cudf_test/base_fixture.hpp
When using parameter `--rmm_mode=managed` for gtests `Invalid RMM allocation mode: managed` exception is thrown.
The logic in `include/cudf_test/base_fixture.hpp` is just missing a return statement.
> Fix rmm_mode=managed parameter for gtests

- java/src/main/native/CMakeLists.txt
The include directory was renamed from `simt` to `cuda`.
> fix libcu++ include path for jni [skip ci]

- CHANGELOG.md
- cpp/tests/merge/merge_dictionary_test.cpp
- cpp/tests/merge/merge_test.cpp
The `cudf::merge` API expects the key columns to be sorted. This means that if null rows are included, these null entries should all appear either at beginning or at the end of the column depending on the null_order for the sort. The `MergeDictionaryTest.WithNull` gtest placed null rows in the middle of the column. The expected results should also have included null entries at the beginning or the end.
This PR also includes an extra test for checking merge results are consistent with the sort parameters `cudf::order` and `cudf::null_order`. This test also includes a larger number of rows to ensure `thrust::merge` requires more than one tile/block in its runtime logic.
> Fix cudf::merge gtest for dictionary columns

- java/ci/README.md
- java/pom.xml
Updating the Java bindings package version to match the libcudf version.
> Update Java bindings version to 0.18-SNAPSHOT [skip ci]
