rapidsai/cudf

- CHANGELOG.md
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
With [4835](https://github.com/rapidsai/cudf/issues/4835) now closed. We can add cuda methods to transform vectors
> Added cuda method to test transform [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/utils/dtypes.py
> [REVIEW] Add support for casting unsupported `dtypes` of same kind

- CHANGELOG.md
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/tests/test_indexing.py
- python/cudf/cudf/tests/test_scan.py
Added support for cupy in `series.loc` and there is also a change in `test_scan.py` to reduce test run time, earlier it was around `120~130` seconds, after this change it would be around `3~4s`.
> [REVIEW] Adding support for `cupy.ndarray` in `series.loc`

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR adds Java and JNI bindings for string split
> [REVIEW]Add Java and JNI bindings for stringSplit [skip ci]

- CHANGELOG.md
- python/cudf/cudf/utils/applyutils.py
Numba 0.49 removes the vendored six library. This PR removes the use of six in applyutils, which is no longer necessary when supporting only Python 3. The replacements are:
- `exec_` from `numba.utils` is replaced with `exec`.
- `six.integer_types` is replaced with `int`
> Fix import errors with Numba 0.49+

- CHANGELOG.md
- cpp/benchmarks/copying/gather_benchmark.cu
- cpp/benchmarks/copying/scatter_benchmark.cu
- cpp/tests/io/legacy/io_test_utils.hpp
replace braces with parenthesis (to call constructor instead of initializer list).
some minor benchmark bug as part of https://github.com/rapidsai/cudf/issues/4209
_Originally posted by @trevorsm7 in https://github.com/rapidsai/cudf/pull/4853#issuecomment-615540325_
> [REVIEW] scatter, gather benchmark constructor fix

- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- README.md
- conda/recipes/libcudf/meta.yaml
- conda/recipes/libnvstrings/meta.yaml
- python/nvstrings/README.md
closes https://github.com/rapidsai/cudf/issues/4791
> [REVIEW] Document supported NVIDIA GPUs and CUDA versions for cuDF

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/io/json.py
- python/cudf/cudf/tests/test_json.py
When no path is given to `to_json`, it serializes the data to a string (rather than a file). However, this string is lost to the void because the result of the underlying call to pandas is ignored. This results in the following divergence with pandas:
```py
import cudf
import pandas as pd
pdf = pd.DataFrame({'a': [1, 2, 3], 'b': ['a', 'b', 'c']})
gdf = cudf.from_pandas(pdf)
print('pandas:')
print(pdf.to_json())
print('cudf:')
print(gdf.to_json())
```
=>
```
pandas:
{"a":{"0":1,"1":2,"2":3},"b":{"0":"a","1":"b","2":"c"}}
cudf:
/* warning omitted */
None
```
This PR fixes the divergence by returning the results of `to_json`.
I'd really appreciate some guidance from the team on these two considerations:
1. What other IO functions would it make sense to extend in this way? (If there are any, …
> [REVIEW] Return the result of `to_json`

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/series.py
- python/dask_cudf/dask_cudf/tests/test_core.py
> [REVIEW] Add missing parameters to `DataFrame.replace` & `Series.replace`

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/tests/test_concat.py
Fixes: #4099 
Since we currently don't support multiple columns with the same names in cuDF, we will be raising an error if we find multiple columns with the same names. But this is actually the case when we invoke `concat` from our `__repr__` functions and `get_dummies` function. Due to this reason introduced an internal flag `ignore_duplicate_columns`, which when is set to `True` we will ignore the newly introduced duplicate column name check.
> [REVIEW] Raise Error when there are duplicate columns sent to `cudf.concat`

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
Missed `null_count` here in #4985  -- apologies :(
> Fix Column.__reduce__ to accept `null_count`

- CHANGELOG.md
- CONTRIBUTING.md
Hi!
When following the setting up environment guide (https://github.com/rapidsai/cudf/blob/branch-0.14/CONTRIBUTING.md#setting-up-your-build-environment), pre_commit package cannot be found.
I have added the channel conda-forge in order to help its resolution.
Hope it helps!
Regards,
Miguel
> Fix #5019 - conda install pre_commit not found [skip ci]

- CHANGELOG.md
- cpp/src/binaryop/jit/code/operation.cpp
- cpp/tests/binaryop/binop-integration-test.cpp
> [REVIEW] Fix bug with unsigned right shift and scalar lhs

- CHANGELOG.md
- cpp/src/jit/cache.cpp
- Allows cache path access to fail. Falls back on no file cache. Closes #4973 
- Custom JIT cache path also contains cudf version directories to avoid inter version clashes. Closes #4987 
- Changed read file locks to shared to fix occasional hiccups in reading from NFS
> [REVIEW] Jit cache path improvements

- CHANGELOG.md
- python/cudf/cudf/_lib/nvtx/nvtx.py
So that it plays nicely with Dask
> [REVIEW] Make `annotate` picklable

- CHANGELOG.md
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/reshape.py
With recent changes, we wouldn't need to find unique columns in all `objs` as when `axis=1` the columns will have to be unique and there is a check already inplace.
> [REVIEW] Remove call to `unique()` in concat when `axis=1`

- CHANGELOG.md
- cpp/src/io/csv/csv_gpu.cu
- cpp/src/io/csv/reader_impl.cu
- cpp/src/io/json/json_gpu.cu
- cpp/src/io/utilities/parsing_utils.cuh
- cpp/tests/io/csv_test.cu
Fixes returning empty columns, hexadecimal dtypes, and doublequote support.
Resolves #5044
> [REVIEW] Fix regressions in the libcudf++ csv reader port

- CHANGELOG.md
- cpp/include/cudf/detail/iterator.cuh
- cpp/src/replace/clamp.cu
- cpp/tests/iterator/iterator_test.cu
fixes https://github.com/rapidsai/cudf/issues/4330
avoid D->H copy of value while creating scalar iterator (value and pair)
`make_scalar_iterator(scalar const&)`
`make_pair_iterator(scalar const&)`
> [REVIEW] make_scalar_iterator avoid D->H copy of value

- CHANGELOG.md
- java/src/main/native/src/TableJni.cpp
Updates the JNI code to deal with the null_policy enum change
> [REVIEW] Fix java code for null_policy enum [skip-ci]

- CHANGELOG.md
- python/dask_cudf/dask_cudf/tests/test_accessor.py
This issue #5037 has been fixed with a `dask` upstream fix: https://github.com/dask/dask/pull/6153
However, since the `as_known` test was missing in `dask_cudf`, adding it in this PR.
Fixes: #5037
> [REVIEW] Add `.cat.as_known` related test in `dask_cudf`

- CHANGELOG.md
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_indexing.py
Added test cases.
closes #5071
> [REVIEW] Fix losing nulls while creating DataFrame from dictionary

- .pre-commit-config.yaml
- CHANGELOG.md
- cpp/include/cudf/strings/string_view.inl
- cpp/scripts/run-clang-format.py
- cpp/src/strings/regex/regex.inl
We missed `.inl` files that are in the `strings` directory. The PR updates the python script, git commit hook and formats the `.inl` files.
> [REVIEW] Add missing `.inl` files to clang-format and git commit hook

- CHANGELOG.md
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/tests/test_dataframe.py
closes #5102 
This PR also has a change which is to fix the hash_encode test case failure issue.
> [REVIEW] Fix read_csv issue with names and header

- CHANGELOG.md
- cpp/benchmarks/transpose/transpose_benchmark.cu
- cpp/scripts/run-clang-format.py
Resolves https://github.com/rapidsai/cudf/issues/5116
> [REVIEW] Display more useful info on `clang-format` CI Failure

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/DType.java
For some cases, we need to get column info and pass it to JNI layer to do some cuda operations.
> [REVIEW] add getSizeInBytes for DType

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Just as it sounds add in JNI bindings for extract
> [REVIEW] Add in java API for regular expression extract [skip-ci]

- python/cudf/cudf/core/column/string.py
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/tests/test_accessor.py
Fixes: #5127 
1. Dask has generic kind of meta-objects which are of form `dict`/`tuples`, etc..At some point in the execution they are getting materialized to `pandas.DataFrame` or `pandas.Series`. Instead we would like the meta data to be correctly pointing to `cudf` data-types. Hence adding the `make_meta_object` backend in `dask_cudf`.
2. Modified the error message and added a warning in `str.split` since we currently only support `expand=True` due to the fact that we don't support nested lists types in our columns.
3. Added tests in `dask_cudf` for an upstream fix: https://github.com/dask/dask/pull/6194
> [REVIEW] Add `make_meta_object` in `dask_cudf` backend and add `str.split` test

- CHANGELOG.md
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/setup.py
- python/dask_cudf/dask_cudf/backends.py
> Fix style checks

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/BinaryOp.java
- java/src/main/java/ai/rapids/cudf/BinaryOperable.java
- java/src/test/java/ai/rapids/cudf/BinaryOpTest.java
Adds in the java bindings for NULL_EQUALS, NULL_MAX and NULL_MIN
> [REVIEW] Added java null aware bin ops bindings [skip ci]

- CHANGELOG.md
- cpp/src/io/csv/csv_gpu.cu
Likely related to #5190 (not verified)
> [REVIEW] Fix potential OOB read in csv reader

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_query.py
- python/cudf/cudf/utils/applyutils.py
- python/cudf/cudf/utils/queryutils.py
This adds `index` support to `DataFrame.query`,  where earlier index were not included as part of query and index names in query would have resulted in `KeyError`, now it works as expected.
This also adds support of `index` keyword in query, this would fail in case `cudf.MultiIndex`.
close #5195
> [REVIEW] Add index support in `DataFrame.query`

- CHANGELOG.md
- ci/checks/headers_test.sh
- ci/checks/style.sh
- conda/recipes/libcudf/meta.yaml
- conda/recipes/libnvstrings/meta.yaml
closes https://github.com/rapidsai/cudf/issues/2167
> [REVIEW] add ci test for libcudf, libnvstrings headers existence check

- CHANGELOG.md
- cpp/benchmarks/synchronization/synchronization.hpp
- cpp/benchmarks/type_dispatcher/type_dispatcher_benchmark.cu
- cpp/include/cudf/fixed_point/fixed_point.hpp
- cpp/include/cudf/strings/detail/modify_strings.cuh
- cpp/include/nvstrings/NVCategory.h
- cpp/include/nvstrings/NVStrings.h
- cpp/src/copying/shift.cu
- cpp/src/io/csv/writer_impl.cu
- cpp/tests/io/csv_test.cu
- cpp/tests/iterator/iterator_test.cu
- cpp/tests/replace/replace_tests.cu
- cpp/tests/strings/replace_tests.cpp
- cpp/tests/utilities/base_fixture.hpp
- cpp/tests/wrappers/timestamps_test.cu
more spelling fixes for https://github.com/rapidsai/cudf/issues/5154
> [REVIEW] more spell check fixes in cpp comments and strings

- CHANGELOG.md
- cpp/src/io/orc/reader_impl.cu
has_timestamp_column was not computed correctly when passing in column names
Fixes #5246
> [REVIEW] ORC reader: fix loading individual timestamp columns

- CHANGELOG.md
- ci/cpu/build.sh
- conda/recipes/cudf/meta.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/libcudf/meta.yaml
- conda/recipes/libnvstrings/meta.yaml
- conda/recipes/nvstrings/meta.yaml
Should consider adding the shortened git commit to the builds instead of exporting it via scripts.
> [WIP] Add short git commit to conda package name

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Implements Java bindings for `replace_with_backrefs`.
> [REVIEW] Implement Java bindings for replace_with_backrefs

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_datetime.py
> Manual Merge Branch 0.14 -> Branch 0.15

- CHANGELOG.md
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/tests/test_concat.py
Fixes: #5281 
This PR adds support to ignore `None` values in list-like input to `cudf.concat`.
> [REVIEW] Add support to ignore `None` in `cudf.concat` input

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Fixes: #5341 
This PR adds `__getitem__` support to `StringMethods`.
> [REVIEW] Add support for `StringMethods.__getitem__`

- CHANGELOG.md
- cpp/src/strings/utilities.cu
> [REVIEW] Initialize conversion tables on a per-context basis

- CHANGELOG.md
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/tests/test_indexing.py
> [REVIEW] Fix loc indexing issue with `datetime` type index

- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/utils/dtypes.py
- python/cudf/cudf/utils/utils.py
Fixes: #2206 
This PR adds support for assigning 0-dim values to a DataFrame, so the fix here is actually needed in detecting a scalar with `is_scalar` method and `to_cudf_compatible_scalar` to get the scalar value from the 0-dim array.
> [REVIEW] Handle `0-dim` inputs while broadcasting to a column

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/tests/test_core.py
~~**Note: CI will fail until the above dask fix is merged, but this is ready for review.**~~
> [REVIEW] Fix `DataFrame.__init__` for list of scalar inputs and related dask issue

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Implements Java bindings for zfill.
> [REVIEW] Add Java bindings for zfill [skip-ci]

- CHANGELOG.md
- CONTRIBUTING.md
> [REVIEW] update cmake version in contrib guide [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/series.py
Resolves: #5338 
This PR throws a proper error message rather than throwing an error with our internal classes to the end user.
> [REVIEW] Add Error message to `StringColumn.unary_operator`

- CHANGELOG.md
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] Aligning signature of `Series.value_counts` to Pandas

- CHANGELOG.md
- cpp/src/text/tokenize.cu
- python/cudf/cudf/_lib/cpp/nvtext/tokenize.pxd
- python/cudf/cudf/_lib/nvtext/tokenize.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_text.py
> [REVIEW] Add python plumbing for `.str.character_tokenize`

- CHANGELOG.md
- cpp/include/cudf/strings/find.hpp
- cpp/src/strings/find.cu
- cpp/tests/strings/find_tests.cpp
- python/cudf/cudf/_lib/cpp/strings/find.pxd
- python/cudf/cudf/_lib/strings/find.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
- python/cudf/cudf/utils/dtypes.py
Resolves: #5074 
This PR adds support for `target` parameter to be `column_view` in libcudf. Additionally, cudf api `.str.startswith` & `.str.endswith` will also now support list-like inputs.
> [REVIEW] Add support for column inputs in `strings::starts_with` and `strings::ends_with`

- CHANGELOG.md
- python/cudf/cudf/_lib/cpp/strings/attributes.pxd
- python/cudf/cudf/_lib/strings/attributes.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Resolves: #5461 
This PR adds bindings to `count_bytes` API and plumbs it to python API(`.str.byte_count`).
> [REVIEW] Add `.str.byte_count` python api and cython(bindings)

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
Merge does not preserve key order.
Fixes #5476
> [REVIEW] Fix merge sort docs 

- CHANGELOG.md
- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/tests/test_groupby.py
> [REVIEW] Ensure flat index after groupby if nlevels == 1

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
> [REVIEW] Fix `loc` and `iloc` doc 

- CHANGELOG.md
- java/README.md
- java/pom.xml
- java/src/main/java/ai/rapids/cudf/NativeDepsLoader.java
> [REVIEW] link boost static libraries in java [skip ci]

- CHANGELOG.md
- build.sh
allow cudf library build in any directory.
(This will enable developers in building multiple branches in same repo)
> [REVIEW] allow build lib in custom dir

- CHANGELOG.md
- python/cudf/cudf/_lib/cpp/nvtext/replace.pxd
- python/cudf/cudf/_lib/nvtext/replace.pyx
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_text.py
Resolves : #5407 
This PR adds plumbings for recently ported nvtext `replace_tokens` to `.str.replace_tokens`.
> [REVIEW] Add plumbings for `.str.replace_tokens`

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Resolves: #5435 
This PR adds public-facing python APIs for existing `is_integer` & `is_float` libcudf strings APIs.
> [REVIEW] Add `.str.isinteger` & `.str.isfloat`

- CHANGELOG.md
- ci/local/build.sh
> [REVIEW] Update docker image in local build [skip-ci]

- CHANGELOG.md
- cpp/src/dlpack/dlpack.cpp
- cpp/tests/dlpack/dlpack_test.cpp
- python/cudf/cudf/tests/test_dlpack.py
> [REVIEW] Unsigned types support in dlpack

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/tests/test_index.py
> [REVIEW] Add support for `cudf.Index` to create Indexes

- CHANGELOG.md
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/ScalarJni.cpp
This fixes the build for java.  The type_id changes were mostly fixed, but not 100%
> [REVIEW] Fix java build around type_id [skip ci]

- CHANGELOG.md
- cpp/src/io/csv/reader_impl.cu
> [REVIEW] Make sure to allocate bitmasks of string columns only once

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] Add `__arrow_array__` protocol and raise a descriptive error message 

- CHANGELOG.md
- cpp/src/io/parquet/parquet.cpp
We need to start "modernizing" `cuIO`. This PR is just a small step - refactors a confusing `for` loop into a "rotated" `std::find_if`. Also uses C++ range-based `for` loops.
> [REVIEW] Refactor `CompactProtocolReader::InitSchema`

- CHANGELOG.md
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/tests/test_indexing.py
> [REVIEW] Fix loc and iloc issue with column like input

- CHANGELOG.md
- cpp/src/io/parquet/writer_impl.cu
- python/cudf/cudf/_lib/parquet.pyx
- python/cudf/cudf/io/parquet.py
- python/cudf/cudf/tests/test_parquet.py
> [REVIEW] Fix issue related to string types being represented as binary types

- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/tests/test_binops.py
- python/cudf/cudf/tests/test_categorical.py
- python/cudf/cudf/tests/test_concat.py
- python/cudf/cudf/tests/test_datetime.py
- python/cudf/cudf/tests/test_groupby.py
- python/cudf/cudf/tests/test_string.py
Fixes: #5599 
This PR adds support for concatenation of `Series` & `DataFrame` in `cudf.concat` when `axis=0`.
We could as well add support for `Index` types with `DataFrame` but this might hide any issues if `cudf.concat` is passed any index objects from dask side, as of now `pd.concat` supports only `Series` and `DataFrame` types. Hence didn't add that support for now, but could be added in future if there is a use-case around it..?
> [REVIEW] Add support for concatenation of `Series` & `DataFrame` in `cudf.concat` when `axis=0`

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ColumnVector.java
- java/src/main/java/ai/rapids/cudf/DType.java
- java/src/main/java/ai/rapids/cudf/HostColumnVector.java
- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/main/native/src/ScalarJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR creates the Java bindings for the DType.DURATION_* 
I don't see any operations currently that are supported for these types which will be supported as they are added in cudf.
> [REVIEW] Java bindings for duration type [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] Fix issue related to Dataframe init when passing in `columns`

- CHANGELOG.md
- ci/local/build.sh
update docker image in local build.sh script
> [WIP] update docker image [skip-ci]

- CHANGELOG.md
- cpp/src/io/parquet/page_enc.cu
- python/cudf/cudf/tests/test_parquet.py
> Fix crash in parquet writer while writing criteo day 0 dataset

- CHANGELOG.md
- python/cudf/cudf/tests/test_pickling.py
Requires PR ( https://github.com/rapidsai/integration/pull/72 )
As older Python versions lack builtin support for pickle protocol 5, test this by using `pickle5`.
> Use `pickle5` to test older Python versions

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_onehot.py
> [REVIEW] Add support for `dummy_na` in `get_dummies`

- CHANGELOG.md
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_concat.py
> [REVIEW] Fix Frame._concat() with categorical columns

- CHANGELOG.md
- cpp/benchmarks/io/orc/orc_writer_benchmark.cpp
> [REVIEW] Disable unsigned type in ORC writer bench

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_multiindex.py
- python/cudf/cudf/tests/test_series.py
> [REVIEW] Add support for `size` property in `DataFrame`/ `Series` / `Index`/ `MultiIndex`

- CHANGELOG.md
- ci/benchmark/build.sh
This script will be used to run and parse benchmark results.
> [REVIEW] gpuCI Benchmark Integration [skip-ci]

- CHANGELOG.md
- java/pom.xml
Update the java slf4j version to 1.7.30 to match Spark 3.0 version number so we don't have any conflicts with the versioning.
> [REVIEW] Update Java slf4j version to match Spark 3.0 [skip ci]

- CHANGELOG.md
- java/src/main/native/src/RmmJni.cpp
> [REVIEW] Switch JNI code to use the RMM owning wrapper [skip ci]

- CHANGELOG.md
- python/cudf/cudf/__init__.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_categorical.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_multiindex.py
- python/cudf/cudf/tests/test_repr.py
- python/cudf/cudf/tests/test_string.py
- python/cudf/cudf/utils/dtypes.py
> [REVIEW] Fix `Index.__repr__` to allow representation of null values

- ci/cpu/build.sh
- conda/recipes/dask-cudf/build.sh
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/dask-cudf/run_test.sh
- docs/cudf/source/api.rst
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_categorical.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_series.py
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/sorting.py
Resolves: #5689 
This PR removes support for `Series.tolist` & `Index.tolist` and raises Error instead. For upstream API support in dask, we have added a dispatch in PR https://github.com/dask/dask/pull/6444 and registered respective dispatch in our backend in `dask-cudf`
> [REVIEW] Disable `tolist` API in `Series` & `Index` and add `tolist` dispatch in `dask-cudf`

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/tests/test_indexing.py
- python/cudf/cudf/tests/test_repr.py
Fixes: #5757 
This PR fixes three issues:
1. In `DataFrame.iloc` we are extracting the start, stop locations from slice but not actually slicing the `index` and hence we end up only creating an incorrect RangeIndex, fixed this issue by slicing the existing `RangeIndex` with `start` & `stop`.
2. When we try to slice and empty dataframe which has an index we seem to be ignoring the index altogether - Fixed this as well.
3. In `DataFrame.__repr__` we are incorrectly slicing an empty dataframe aswell into 4 quadrants to concat and convert to pandas for printing - This actually results in non-uniform values of the index when DataFrame is empty. Hence handling this as a special case and added tests for the same.
> [REVIEW] Fix issue related to `iloc` and slicing a `DataFrame`

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/native/include/jni_utils.hpp
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/CudaJni.cpp
- java/src/main/native/src/CudfJni.cpp
- java/src/main/native/src/RmmJni.cpp
- java/src/main/native/src/ScalarJni.cpp
- java/src/main/native/src/TableJni.cpp
- java/src/main/native/src/cudf_jni_apis.hpp
- java/src/test/java/ai/rapids/cudf/RmmTest.java
This fixes #5784 
@byin-nvidia
Please take a look at this and let me know if this meets your needs.
> [REVIEW] JNI Header Cleanup for cuspacial [skip-ci]

- CHANGELOG.md
- cpp/include/cudf/table/table_device_view.cuh
- cpp/src/table/table_device_view.cu
Fixes https://github.com/rapidsai/cudf/issues/5792
There's no good/easy way to test this, but I can certainly look at ways of doing this if folks have concerns.
> [REVIEW] Fixes a leak in mutable_table_device_view

- CHANGELOG.md
- python/cudf/cudf/tests/utils.py
> [REVIEW] Get nullable_pd_dtype from kwargs if provided in assert_eq

- CHANGELOG.md
- CONTRIBUTING.md
- java/README.md
Fixes #5794 
@kkraus14 @revans2 @jlowe
> [REVIEW] clarify documentation on boost dependency

- CHANGELOG.md
- cpp/include/cudf/lists/lists_column_view.hpp
- python/cudf/cudf/_lib/column.pyx
- python/cudf/cudf/_lib/cpp/column/column.pxd
- python/cudf/cudf/_lib/cpp/lists/lists_column_view.pxd
- python/cudf/cudf/_lib/types.pxd
- python/cudf/cudf/_lib/types.pyx
- python/cudf/cudf/core/column/lists.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_column.py
- python/cudf/cudf/utils/dtypes.py
Note: This no longer needs a C++ review
> [REVIEW] Enable computing views of ListColumns

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Adds in java support for the repeat command.
> [REVIEW] Add in JNI support for the repeat command [skip-ci]

- CHANGELOG.md
- conda/environments/cudf_dev_cuda10.0.yml
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda10.2.yml
- conda/recipes/custreamz/meta.yaml
This PR pins `dask` and `distributed` versions to `2.22.0` in dev yaml's and custreamz  recipe.
> [REVIEW] Pin `dask` and `distributed` version to `2.22.0`

- CHANGELOG.md
- python/cudf_kafka/cudf_kafka/_lib/kafka.pxd
- python/cudf_kafka/cudf_kafka/_lib/kafka.pyx
- python/custreamz/custreamz/kafka.py
> [REVIEW] custreamz incompatibilities with python streamz-api fixes

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_multiindex.py
Resolves: #5676 
This PR adds support for `Index.sort_values` API.
> [REVIEW] Add support for `Index.sort_values`

- CHANGELOG.md
- docs/cudf/source/api.rst
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
> [REVIEW] Raise informative error in `DataFrame.iterrows` and `DataFrame.itertuples`

- CHANGELOG.md
- cpp/src/io/orc/writer_impl.cu
- cpp/src/io/parquet/writer_impl.cu
- cpp/tests/io/orc_test.cpp
- cpp/tests/io/parquet_test.cpp
- python/cudf/cudf/tests/test_orc.py
- python/cudf/cudf/tests/test_parquet.py
> [REVIEW] Fix bug in parquet writer in writing string column with offset

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Adds in java API for merge (merge sort)
> [REVIEW] Add in java support for merge sort [skip-ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
Just adds in the basic gather API so it can be used through java.
> [REVIEW] Added in gather support for JNI [skip-ci]

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ArrowIPCWriterOptions.java
- java/src/main/java/ai/rapids/cudf/CompressedMetadataWriterOptions.java
- java/src/main/java/ai/rapids/cudf/HostBufferProvider.java
- java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java
- java/src/main/java/ai/rapids/cudf/ParquetWriterOptions.java
- java/src/main/java/ai/rapids/cudf/StreamedTableReader.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/java/ai/rapids/cudf/WriterOptions.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This adds in support for reading/writing arrow IPC formatted data.
> [REVIEW] Add in APIs to read/write arrow IPC formatted data from java [skip-ci]

- CHANGELOG.md
- python/cudf/cudf/_lib/column.pyx
- python/cudf/cudf/_lib/cpp/column/column_factories.pxd
- python/cudf/cudf/_lib/cpp/filling.pxd
- python/cudf/cudf/_lib/filling.pyx
- python/cudf/cudf/core/column/__init__.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/indexing.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/core/window/rolling.py
- python/cudf/cudf/utils/applyutils.py
- python/cudf/cudf/utils/cudautils.py
- python/cudf/cudf/utils/utils.py
> [REVIEW] Use libcudf instead of cupy for `arange` or column creation from a scalar.

- CHANGELOG.md
- cpp/CMakeLists.txt
Fixes #5976 
@jrhemstad @kkraus14
> [REVIEW] fix CMake option to turn off NVTX

- CHANGELOG.md
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/timedelta.py
- python/cudf/cudf/tests/test_datetime.py
- python/cudf/cudf/tests/test_timedelta.py
Fixes: #5977 
This PR handle `NAT` values in fillna and will not fill remove the mask in this case thus maintaining the null values as is, but the `base_data` value will be changed to min(int64). 
cc: @brandon-b-miller @kkraus14
> [REVIEW] Handle `nat` in `fillna` for datetime and timedelta types

- CHANGELOG.md
- docs/cudf/source/api.rst
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_datetime.py
> [REVIEW] Add support for `.dt.strftime`

- .pre-commit-config.yaml
- CHANGELOG.md
> [REVIEW] Change black version to 19.10b0 in .pre-commit-config.yaml [skip-ci]

- CHANGELOG.md
- ci/gpu/build.sh
- docs/cudf/source/internals.md
Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

- CHANGELOG.md
- cpp/tests/utilities/type_lists.hpp
Needed for https://github.com/rapidsai/cuspatial/pull/268
> [REVIEW] Import traits.hpp for cudftestutils consumers

- CHANGELOG.md
> [REVIEW] Fix 0.15 --> 0.16 Automerge

- CHANGELOG.md
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_series.py
> [REVIEW] Fix issue in `Series.factorize` to correctly pick `na_sentinel` value

- CHANGELOG.md
- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/tests/test_datetime.py
Fixes: #6097 
This PR fixes issue where inputs other than `str`/`object` types are passed with the `format` parameter.
> [REVIEW] Handle `format` for other input types in `to_datetime`

- CHANGELOG.md
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_datetime.py
> [REVIEW] Add support for `dayofweek` property in `DateTimeIndex` and `DateTimeProperties`

- CHANGELOG.md
- python/custreamz/README.md
> [REVIEW] fix Dataframe name typo and legacy addition of consumer

- CHANGELOG.md
- cpp/src/io/csv/datetime.cuh
- python/cudf/cudf/tests/test_csv.py
closes https://github.com/rapidsai/cudf/issues/6105
make days to int64_t to make the expression compute in 64-bit arithmetic
> [REVIEW] days to int64_t to compute 64 bit arithmetic

- CHANGELOG.md
- cpp/src/copying/slice.cpp
- cpp/tests/copying/slice_tests.cpp
When an empty column is being sliced with start and end {0, 0}, normally we would expect an empty column of same type, but it was returning empty vector.
> [REVIEW] Fix slice issue with empty column

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Fixes: #6153 
This PR remove special code added for handling empty dataframe inputs in `DataFrame.append`, whereas the same is being handled correctly in `cudf.concat`.
> [REVIEW] Fix issue related to empty `Dataframe` with columns input to `DataFrame.appened`

- CHANGELOG.md
- python/cudf/cudf/io/parquet.py
- python/cudf/cudf/tests/test_parquet.py
- python/cudf/cudf/utils/ioutils.py
- python/dask_cudf/dask_cudf/io/parquet.py
- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
The `write_to_dataset` parquet code is currently using a deprecated pyarrow API to generate a random file name.  This PR avoids the deprecation issue by using `uuid4.hex` directly.  This PR also follows the lead of [dask#6451](https://github.com/dask/dask/pull/6451) by enabling the user to specify a specific `filename` argument to `write_to_dataset`.  
The dask_cudf to_parquet code will now avoid the uuid4-based approach to file naming.
> Avoid guid use from deprecated pyarrow.compat

- CHANGELOG.md
- python/dask_cudf/dask_cudf/io/csv.py
- python/dask_cudf/dask_cudf/io/tests/test_csv.py
Closes #6010 
When the user specifies `chunksize=None`, `dask_cudf` will read an entire file to define the metadata of the new DataFrame.  This PR uses the first 5 rows instead (and adds relevant test coverage for both gzip and uncompressed data).
> Avoid reading full csv files for metadata in dask_cudf

- CHANGELOG.md
- python/dask_cudf/dask_cudf/io/parquet.py
- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
`dask_cudf.to_parquet` does not currently preserve index coluns correctly.  This PR simply sets the index within `write_partition` to make sure CuIO can write the correct pandas metadata (specifying the proper index).
Note that this PR does not use `set_index(..., inplace=True)`, since `inplace` is not supported (see #6198) - That feature can be added (on the python side) in this PR, but it may make more sense to attack that in a separate (small) PR.
> Fix index preservation for dask_cudf parquet

- CHANGELOG.md
- cpp/src/io/json/json_gpu.cu
- cpp/src/io/json/reader_impl.cu
During my recent code review of https://github.com/rapidsai/cudf/pull/6162/, I noticed several opportunities to use `<algorithm>` that were out of scope of the PR. Now that that PR has merged - this is a small follow up.
> [REVIEW] Small clean up to use more algorithms

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/reduction_functions.hpp
- cpp/src/reductions/nth_element.cu
- cpp/src/reductions/reductions.cpp
- cpp/tests/reductions/reduction_tests.cpp
> Add nth element agg with null handling for column

- CHANGELOG.md
- cpp/src/io/avro/avro_gpu.cu
- cpp/src/io/comp/debrotli.cu
- cpp/src/io/comp/gpuinflate.cu
- cpp/src/io/comp/snap.cu
- cpp/src/io/comp/unsnap.cu
- cpp/src/io/csv/csv_gpu.cu
- cpp/src/io/orc/dict_enc.cu
- cpp/src/io/orc/stripe_data.cu
- cpp/src/io/orc/stripe_enc.cu
- cpp/src/io/orc/stripe_init.cu
- cpp/src/io/parquet/page_data.cu
- cpp/src/io/parquet/page_dict.cu
- cpp/src/io/parquet/page_enc.cu
- cpp/src/io/parquet/page_hdr.cu
- cpp/src/io/statistics/column_stats.cu
- cpp/src/io/utilities/block_utils.cuh
> [REVIEW] Revert 6206

- CHANGELOG.md
- thirdparty/CMakeLists.txt
> [REVIEW] Switch thrust to use the NVIDIA/thrust repo

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Rmm.java
- java/src/main/java/ai/rapids/cudf/RmmAllocationMode.java
- java/src/main/native/src/RmmJni.cpp
> [REVIEW] Add JNI support for `arena_memory_resource` [skip ci]

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
- cpp/CMakeLists.txt
- cpp/include/cudf/utilities/default_stream.hpp
- cpp/src/utilities/default_stream.cpp
- cpp/tests/CMakeLists.txt
- cpp/tests/utilities_tests/default_stream_tests.cpp
Closes #6111.
This is an alternative, simpler solution than #6324. We can revisit this once https://github.com/rapidsai/rmm/pull/413 is merged.
@harrism @jrhemstad @kkraus14 @abellina
> [REVIEW] add ability to query if PTDS is enabled

- CHANGELOG.md
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/_lib/io/utils.pxd
- python/cudf/cudf/_lib/io/utils.pyx
- python/cudf/cudf/_lib/orc.pyx
- python/cudf/cudf/_lib/parquet.pyx
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/utils/ioutils.py
Fixes: #6279 
This PR adds support for writing to a `StringIO` object in `to_csv`. This change will also now enable `to_csv` to return the csv as string when the given `path` is `None`.
> [REVIEW] Add support to return csv as string when `path=None` in `to_csv` 

- CHANGELOG.md
- cpp/cmake/Templates/Arrow.CMakeLists.txt.cmake
- cpp/cmake/Templates/GoogleBenchmark.CMakeLists.txt.cmake
- cpp/cmake/Templates/GoogleTest.CMakeLists.txt.cmake
- cpp/libcudf_kafka/cmake/Templates/GoogleTest.CMakeLists.txt.cmake
Noticed we are still doing a full clone in a few places. Hopefully this speeds up the build a bit.
@harrism @jlowe
> [REVIEW] perform shallow clone of external projects

- CHANGELOG.md
- build.sh
- conda/recipes/cudf/meta.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
Currently the Cythonization is done in parallel, but the actual compilation is not. Adding the `-j` flag with appropriate environment variable to parallelize the compilation as well.
> [REVIEW] Compile Cython code in parallel

- CHANGELOG.md
- conda/recipes/libcudf/meta.yaml
- cpp/CMakeLists.txt
- cpp/include/cudf/detail/indexalator.cuh
- cpp/include/cudf/dictionary/detail/replace.hpp
- cpp/include/cudf/dictionary/detail/update_keys.hpp
- cpp/include/cudf/dictionary/dictionary_factories.hpp
- cpp/src/dictionary/dictionary_factories.cu
- cpp/src/dictionary/replace.cu
- cpp/src/dictionary/set_keys.cu
- cpp/src/replace/nulls.cu
- cpp/tests/replace/replace_nulls_tests.cpp
Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

- CHANGELOG.md
- python/cudf/cudf/_lib/hash.pyx
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_dataframe.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Closes #6394 
Corrects an empty offset list to contain zeros in the output of `libcudf.hash.hash_partition`.
**Background/Motivation**: The groupby logic introduced in #6248 is now leveraging `partition_by_hash` to split groupby aggregations into multiple output partitions.  Dask-CuDF assumes that `partition_by_hash` will output a list of `nparts` dataframe objects - Even if the method is called on an empty DataFrame.  Without this fix, the output of `partition_by_hash` will just be an empty list.
> Avoid empty offset list in hash_partition output

- CHANGELOG.md
- java/ci/README.md
- java/pom.xml
Updating the Java bindings to reflect the new version.
> Update Java bindings version to 0.17-SNAPSHOT [skip ci]

- CHANGELOG.md
- cpp/src/io/csv/writer_impl.cu
- cpp/src/strings/convert/convert_datetime.cu
- cpp/tests/io/csv_test.cpp
- cpp/tests/strings/datetime_tests.cpp
- python/cudf/cudf/tests/test_csv.py
> [REVIEW] Fix DateTime type value truncation while writing to csv

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/Cuda.java
- java/src/main/native/src/CudfJni.cpp
Part of https://github.com/NVIDIA/spark-rapids/issues/619.
@jlowe @abellina
> [REVIEW] add JNI api to check if PTDS is enabled [skip ci]

- CHANGELOG.md
Resolves conflict for Auto merge: https://github.com/rapidsai/cudf/pull/6576
> [REVIEW] Resolve conflict for auto merge Branch 0.17-merge 0.16

- CHANGELOG.md
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/tests/test_binops.py
- python/cudf/cudf/tests/test_categorical.py
- python/cudf/cudf/tests/test_column.py
- python/cudf/cudf/tests/test_column_accessor.py
- python/cudf/cudf/tests/test_concat.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_datetime.py
- python/cudf/cudf/tests/test_duplicates.py
- python/cudf/cudf/tests/test_groupby.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_joining.py
- python/cudf/cudf/tests/test_json.py
- python/cudf/cudf/tests/test_multiindex.py
- python/cudf/cudf/tests/test_rank.py
- python/cudf/cudf/tests/test_reductions.py
- python/cudf/cudf/tests/test_replace.py
- python/cudf/cudf/tests/test_sorting.py
- python/cudf/cudf/tests/test_stats.py
- python/cudf/cudf/tests/test_string.py
- python/cudf/cudf/tests/test_timedelta.py
- python/cudf/cudf/tests/utils.py
> [REVIEW] Use `assert_exceptions_equal` to assert exceptions in pytests

- CHANGELOG.md
- python/cudf/cudf/comm/gpuarrow.py
- python/cudf/cudf/core/buffer.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/column/timedelta.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/testing/testing.py
- python/cudf/cudf/tests/utils.py
- python/cudf/cudf/utils/dtypes.py
- python/dask_cudf/dask_cudf/backends.py
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/io/csv.py
> [REVIEW] Add operator overloading to column and clean up error messages

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/series.py
This PR updates documentation of `DataFrame.to_pandas` and `Series.to_pandas`.
> [REVIEW] Update `to_pandas` api docs 

- CHANGELOG.md
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
Fixes: #6664 
This PR fixes addresses issue of changing the caller object's index name by making a shallow copy of it.
> [REVIEW] Fix issue where index name of caller object is being modified in csv writer

- CHANGELOG.md
- cpp/include/cudf/io/csv.hpp
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/utils/ioutils.py
Fixes: #6678 , #6677 
This PR:
> [REVIEW] Fix issue related to `na_values` input in `read_csv`

- CHANGELOG.md
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Fixes: #6707
This PR checks for duplicate columns when a pandas dataframe is passed via `cudf.from_pandas`.
> [REVIEW] Raise informative error while converting a pandas dataframe with duplicate columns

- CHANGELOG.md
- python/cudf/cudf/core/column/lists.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_serialize.py
Closes #6718 
Adds `serialize`/`deserialize` definitions to `ListColumn`, along with a simple test.
Note: This does not address `StructColumn` (perhaps this could be a separate issue/PR?)
> Add serialization methods for ListColumn

- CHANGELOG.md
- cpp/src/io/utilities/type_conversion.cu
- python/cudf/cudf/_lib/csv.pyx
- python/cudf/cudf/tests/test_csv.py
- python/cudf/cudf/utils/ioutils.py
> [REVIEW] Fix implementation of `dtype` parameter in `cudf.read_csv`

- CHANGELOG.md
- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/tests/test_core.py
Closes #6738 
`map_partitions` was not producing proper `Series`/`Index` types after `compute`.  Using the upstream `_concat` method resolves the issue.
> Fix concat bug in dask_cudf Series/Index creation

- CHANGELOG.md
- docs/cudf/source/api.rst
- python/cudf/cudf/comm/gpuarrow.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/core/window/rolling.py
- python/cudf/cudf/testing/testing.py
- python/cudf/cudf/utils/ioutils.py
Fixes: #6714 
This PR contains fixes to places where docs is broken/throwing a warning due to incorrect formatting.
All the warnings will be removed with these fixes:
```bash
pgali@dt07:/nvme/0/pgali/cudf/docs/cudf$ make clean
Removing everything under 'build'...
pgali@dt07:/nvme/0/pgali/cudf/docs/cudf$ make html
Running Sphinx v3.3.0
Adding copy buttons to code blocks...
making output directory... done
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... …
```
> [REVIEW] Fix cudf python docs and associated build warnings

- CHANGELOG.md
- java/src/main/java/ai/rapids/cudf/ParquetWriterOptions.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/CMakeLists.txt
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR is dependent upon #5096.
Added changes to the following files
ParquetWriterOptions.java
TableJni.cpp
TableTest.java
Table.java
> [REVIEW] Parquet writer int96 [skip ci]

- CHANGELOG.md
- python/cudf/cudf/core/column/string.py
> [REVIEW] Fix `.str.replace_with_backrefs` docs examples

- CHANGELOG.md
- python/cudf/cudf/_lib/nvtext/generate_ngrams.pyx
- python/cudf/cudf/_lib/nvtext/ngrams_tokenize.pyx
- python/cudf/cudf/_lib/nvtext/replace.pyx
- python/cudf/cudf/_lib/nvtext/tokenize.pyx
- python/cudf/cudf/_lib/strings/char_types.pyx
- python/cudf/cudf/_lib/strings/combine.pyx
- python/cudf/cudf/_lib/strings/find.pyx
- python/cudf/cudf/_lib/strings/replace.pyx
- python/cudf/cudf/_lib/strings/replace_re.pyx
- python/cudf/cudf/_lib/strings/split/partition.pyx
- python/cudf/cudf/_lib/strings/split/split.pyx
- python/cudf/cudf/_lib/strings/strip.pyx
- python/cudf/cudf/_lib/strings/translate.pyx
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/column/timedelta.py
- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/utils/utils.py
Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/native/src/ColumnViewJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Adding Java bindings for the `url_decode` and `url_encode` functions.
> Add Java bindings for URL conversion [skip ci]

- CHANGELOG.md
- python/cudf/cudf/_lib/groupby.pyx
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_groupby.py
> Manual merge of branch 0.17 into branch 0.18 [skip-ci]

- cpp/src/io/csv/csv_gpu.cu
- cpp/tests/io/csv_test.cpp
> [REVIEW]Fix int to datetime conversion in csv_read

- python/dask_cudf/dask_cudf/io/csv.py
- python/dask_cudf/dask_cudf/io/tests/test_csv.py
Closes #6850 
dask_cudf version of the `dask.dataframe` changes proposed in [dask#6960](https://github.com/dask/dask/pull/6960).  Uses `fsspec` to infer the default `compression` argument from the suffix of the first file-path argument.
> Add compression="infer" as default for dask_cudf.read_csv

- python/cudf/cudf/core/algorithms.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/lists.py
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/core/scalar.py
- python/cudf/cudf/core/series.py
> [REVIEW] Update cudf python docstrings with new null representation (`<NA>`)

- cpp/src/reductions/scan.cu
- cpp/tests/reductions/scan_tests.cpp
Adding support for `cudf::scan` for `decimal32` and `decimal64`. `cudf::scan` only supports 4 operations (sum, product, min and max) but the decimal types will only support `SUM`, `MAX` and `MIN`.
> `cudf::scan` support for `decimal32` and `decimal64`

- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda10.2.yml
- conda/environments/cudf_dev_cuda11.0.yml
This PR adds `pyorc` package to dev environment yml files.
> [REVIEW] Add `pyorc` to dev environment

- cpp/benchmarks/common/generate_benchmark_input.cpp
- cpp/tests/copying/split_tests.cpp
https://github.com/rapidsai/cudf/pull/7105/ somehow got merged but broke compilation. These are the necessary fixes.
> Fix compilation failure caused by `-Wall` addition.

- cpp/src/aggregation/result_cache.cpp
- cpp/src/comms/ipc/ipc.cpp
After recent changes in libcudf compilation in #7105, the compilation of libcudf on my local machine is broken and these changes fixed the compilation errors.
> [REVIEW] Fix compilation errors in libcudf

- cpp/tests/jit/jit-cache-multiprocess-test.cpp
- cpp/tests/jit/jit-cache-test.hpp
> Fix JIT cache multi-process test flakiness in slow drives

- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/groupby.py
Adds a `CudfSeriesGroupBy` class to dask_cudf.  This allows the optimizations from #6248 to be used for `CudfSeriesGroupBy.mean` (in addition to `CudfDataFrameGroupBy.aggregate`).
> Add CudfSeriesGroupBy to optimize dask_cudf groupby-mean

- cpp/src/jit/cache.cpp
- cpp/tests/jit/jit-cache-test.hpp
Adds a level to JIT cache which segregates kernels compiled for different compute capabilities.
Closes #5469
> Add JIT cache per compute capability

- python/cudf/cudf/_fuzz_testing/parquet.py
- python/cudf/cudf/_fuzz_testing/tests/fuzz_test_parquet.py
This PR adds coverage for `skiprows` and `num_rows` parameters in parquet reader fuzz tests.
> [REVIEW] Add coverage for `skiprows` and `num_rows` in parquet reader fuzz testing

- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/native/src/ColumnViewJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

- java/src/test/java/ai/rapids/cudf/ArrowColumnVectorTest.java
Found leaks in the ArrowColumnVectorTest so fix them.
Signed-off-by: Thomas Graves <tgraves@nvidia.com>
> Fix Arrow column test leaks [skip ci]

- cpp/src/io/orc/writer_impl.cu
- python/cudf/cudf/tests/test_orc.py
> Throw if bool column would cause incorrect result when writing to ORC

- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_binops.py
Fixes: #7536 
This PR enables re-indexing in some of the equality-related APIs, note that we will still error when we call the dunder methods.
> [REVIEW] Fix index mismatch issue in equality related APIs

- ci/benchmark/build.sh
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda10.1.yml
- conda/environments/cudf_dev_cuda10.2.yml
- conda/environments/cudf_dev_cuda11.0.yml
- conda/recipes/dask-cudf/run_test.sh
- cpp/src/rolling/grouped_rolling.cu
- python/dask_cudf/dask_cudf/io/orc.py
PR to trigger the release of v0.18.1
> [RELEASE] Release v0.18.1 cudf

- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/native/src/ColumnViewJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Adds JNI bindings for improved is_integer with bounds checks
> Added JNI support for new is_integer [skip ci]

- python/cudf/cudf/_lib/parquet.pyx
- python/cudf/cudf/tests/test_parquet.py
Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

- conda/recipes/cudf/meta.yaml
- conda/recipes/cudf_kafka/meta.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/libcudf_kafka/meta.yaml
This reverts commit 7d49f75df9681dbe1653029e7d508355884a6d86 - #7743.
> Revert "Update conda recipes pinning of repo dependencies (#7743)" [skip-ci]

- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_replace.py
Fixes: #7284 
In this PR, we are also handling `OverflowError` that are generate while trying to replace a value in a column. In this case too we'd have to return a deep copy without propagating the error to end-user.
Also introduced a test param for this case.
> [REVIEW] Handle `OverflowError` in `replace`

- cpp/src/io/comp/debrotli.cu
- cpp/src/io/comp/gpuinflate.cu
- cpp/src/io/comp/unsnap.cu
- cpp/src/io/utilities/block_utils.cuh
See https://github.com/rapidsai/cudf/pull/7951
> [REVIEW][HOTFIX] Fix slow decompression performance

- cpp/src/io/comp/debrotli.cu
- cpp/src/io/comp/gpuinflate.cu
- cpp/src/io/comp/unsnap.cu
- cpp/src/io/utilities/block_utils.cuh
This PR serves as the mechanism to release cuDF.
> [RELEASE] v0.18.2 `cudf` release [skip-ci]

- cpp/src/io/orc/stripe_data.cu
- cpp/src/io/orc/stripe_init.cu
Resolves issue with ORC reader.
There were two issues,
There was a missing check to keep number of streams that needs to be accessed.
The position which was being used to calculate buffer length was wrong, and assigned non-zero value for a stream whose length is zero.
> Fix ORC reader issue with bystream reader

- conda/environments/cudf_dev_cuda11.0.yml
- conda/environments/cudf_dev_cuda11.1.yml
- conda/environments/cudf_dev_cuda11.2.yml
- conda/recipes/cudf/meta.yaml
- python/cudf/requirements/cuda-11.0/dev_requirements.txt
- python/cudf/requirements/cuda-11.1/dev_requirements.txt
- python/cudf/requirements/cuda-11.2/dev_requirements.txt
- python/cudf/setup.py
- python/dask_cudf/dev_requirements.txt
- python/dask_cudf/setup.py
This PR relaxes pandas version pinning which was introduced in `0.19`.
> [REVIEW] Unpin pandas to patch version

- CONTRIBUTING.md
- conda/environments/cudf_dev_cuda11.0.yml
- conda/environments/cudf_dev_cuda11.1.yml
- conda/environments/cudf_dev_cuda11.2.yml
- conda/recipes/cudf_kafka/meta.yaml
- conda/recipes/libcudf_kafka/meta.yaml
Fixes: #8001 
This PR changes the minimum CMake version to 3.18 at remaining places in the code-base.
> [REVIEW] Bump cmake minimum version to 3.18 in dev environments

- cpp/src/lists/extract.cu
- cpp/tests/lists/extract_tests.cpp
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
> [RELEASE] v0.19.1 cudf

- cpp/include/cudf/strings/detail/strings_column_factories.cuh
- cpp/src/groupby/sort/group_quantiles.cu
- cpp/src/rolling/rolling_detail.cuh
- cpp/tests/merge/merge_test.cpp
> Remove references to deprecated "rmm/thrust_rmm_allocator.h"

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
- python/cudf/cudf/tests/test_reductions.py
Fixes: #8014 
This PR introduces the column equality checks that are missing in the dataframe level equality operations.
> [REVIEW] Add column validation in equality operations

- cpp/src/join/semi_join.cu
- cpp/tests/join/semi_join_tests.cpp
Adding support for joining on structs for left_anti_join, left_semi_join, and left_semi_anti_join.
closes #7912
> Adding struct support for semi_join

- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/decimal.py
- python/cudf/cudf/core/dtypes.py
- python/cudf/cudf/tests/test_decimal.py
- python/cudf/cudf/tests/test_serialize.py
- python/cudf/cudf/tests/utils.py
Fixes https://github.com/rapidsai/cudf/issues/8034
> Adds serialization of Decimal Columns and dtypes

- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/tests/test_datetime.py
This PR checks for the parameter being passed to `errors` in `cudf.to_datetime`.
This PR only partially addresses #8010
> [REVIEW] Add validation for `errors` parameter in `cudf.to_datetime`

- cpp/src/join/semi_join.cu
- cpp/tests/join/semi_join_tests.cpp
Current PR follows #7963, fixing issue(#7936) for left semi/anti join.
> Fix semi join on mixed nullability columns

- cpp/benchmarks/CMakeLists.txt
- cpp/benchmarks/quantiles/quantiles_benchmark.cpp
- cpp/src/quantiles/quantiles.cu
Converts internals of cudf::quantiles to use device_uvector instead of device_vector. Also adds a quantiles benchmark.
Contributes to #7287
Performance is better (sometimes significantly, when the number of quantiles requested is larger).
```
Comparing /home/mharris/rapids/cudf/cpp/build/quantiles_before.json to /home/mharris/rapids/cudf/cpp/build/quantiles_after.json
Benchmark                                                      Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------
Quantiles/no_nulls/65536/1/1/manual_time                    -0.0234         -0.0185             0             0             0             0 …
```
> Convert cudf::quantiles to use device_uvector

- cpp/include/cudf/detail/aggregation/aggregation.cuh
- cpp/include/cudf/detail/utilities/device_atomics.cuh
- cpp/include/cudf_test/column_utilities.hpp
- cpp/src/aggregation/result_cache.cpp
- cpp/src/io/json/reader_impl.cu
Small cleanup PR. Follow up to #7931
> Remove remaining "when C++17" comments

- java/rmm_log.txt
- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/main/native/src/ColumnVectorJni.cpp
- java/src/main/native/src/CudaJni.cpp
- java/src/main/native/src/ScalarJni.cpp
- java/src/main/native/src/cudf_jni_apis.hpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/ScalarTest.java
This PR is to add the JNI support for scalar of list, along with building a ColumnVector from a list scalar.
Since the PR https://github.com/rapidsai/cudf/pull/7584 inroduced the list scalar in cpp.
> JNI support for scalar of list [skip ci]

- conda/environments/cudf_dev_cuda11.0.yml
- conda/environments/cudf_dev_cuda11.1.yml
- conda/environments/cudf_dev_cuda11.2.yml
Remove conda defaults channel in dev environments
> ENH Remove conda defaults channel in dev environments

- python/dask_cudf/dask_cudf/groupby.py
- python/dask_cudf/dask_cudf/tests/test_groupby.py
Redirects Python built-in functions to their named equivalent aggregation in Dask-cuDF; this ensures that the Dask-cuDF codepath is used for these aggregations regardless of how they're specified, see [#7812 (comment)](https://github.com/rapidsai/cudf/issues/7812#issuecomment-820518107).
> Redirect callable aggregations to their named equivalent in dask-cuDF

- python/cudf/cudf/core/algorithms.py
- python/cudf/cudf/core/series.py
Fixes: https://github.com/rapidsai/cudf/issues/7922
This PR fixes the docstring of `factorize` APIs where the return types were incorrect.
> [REVIEW] Fix `factorize` doc string

- python/cudf/cudf/core/buffer.py
- python/cudf/cudf/tests/test_buffer.py
> Add a `copy()` method to `Buffer`

- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR is trying to add java binding support for making List of List based on https://github.com/rapidsai/cudf/pull/8046. But the existing jni API makeList has already supported to create List of List, this PR just add unit tests for making list of list.
> add Java unit tests for making list of list

- python/cudf/cudf/core/column/decimal.py
- python/cudf/cudf/tests/test_replace.py
This enables using the `fillna` method on decimal columns with integer scalars or series as the fill value. It also enables using decimal scalars and series as the fill value even when they have a different precision and scale than the column being filled.
Closes #8156
> [REVIEW] Enable decimal fillna with integer scalars and series

- java/ci/Dockerfile.centos7
> Bump up GDS user-space lib version to 0.95.1 [skip ci]

- python/cudf/cudf/core/column/string.py
Closes #8094 
This PR changes the `_split_by_character` utility to copy the input strings offsets column as the offsets column for the output lists column.
> Update split-by-char to use input offsets column

- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/java/ai/rapids/cudf/WindowOptions.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
Since it's a breaking PR, and the corresponding spark-rapids PR has some issues. Just revert this cudf PR. Sorry
This reverts commit 2a169c801adc7f5d45144f8291a81fc21b9bf759.
> Revert #7909 add java bindings for non-timestamps range window queries [skip ci]

- java/src/main/java/ai/rapids/cudf/Scalar.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/java/ai/rapids/cudf/WindowOptions.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR is to add java bindings for integral (boolean-exclusive) and
timestamps supporting for range window
Please refer to https://github.com/rapidsai/cudf/pull/7909
> add java bindings for non-timestamps range window queries [skip ci]

- java/ci/README.md
- java/pom.xml
> Update cudfjni version to 21.06 [skip ci]

- conda/recipes/cudf/meta.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
Pass compiler environment variables to conda python build
> Pass compiler environment variables to conda python build

- README.md
As part of this commit https://github.com/rapidsai/cudf/commit/84065228e0c0b5d94cdc6a44518eb9c353290c89 we accidentally changed the release version of readme to `21.06`, whereas the stable version currently in `rapidsai` channel is `0.19`.
> [DOC] Fix cudf release version in readme

- cpp/include/cudf/detail/aggregation/aggregation.cuh
- cpp/src/rolling/lead_lag_nested_detail.cuh
- cpp/src/rolling/rolling_collect_list.cuh
- cpp/src/rolling/rolling_detail.cuh
- cpp/src/rolling/rolling_detail.hpp
- cpp/tests/rolling/grouped_rolling_test.cpp
- cpp/tests/rolling/rolling_test.cpp
- cpp/tests/rolling/rolling_test.hpp
Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

- java/ci/README.md
- java/pom.xml
update cudf JNI version to 21.08, and preparing nightly artifact build
> Update Java bindings to 21.08-SNAPSHOT [skip ci]

- ci/benchmark/build.sh
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda11.0.yml
- conda/environments/cudf_dev_cuda11.2.yml
- conda/recipes/dask-cudf/run_test.sh
> [REVIEW] Pin dask for ci in `21.06`

- java/src/main/java/ai/rapids/cudf/Aggregation.java
- java/src/test/java/ai/rapids/cudf/TableTest.java
> [Java] CollectSetAggregation: implement RollingAggregation interface [skip ci]

- cpp/src/sort/sort_impl.cuh
the fast-path for single column sort will not use any sorted_indices, this PR just move the sorted_indices behind the single column sort code block
> Minor code refactor for sorted_order

- CONTRIBUTING.md
This PR closes issue #8123. It removes a slight error in the Cython command in the CuDF `contributing.md` page.
> Fix Cython formatting command in Contributing.md.

- cpp/include/cudf/detail/scatter.cuh
- cpp/src/copying/copy.cu
- cpp/tests/copying/copy_if_else_nested_tests.cpp
- cpp/tests/copying/scatter_struct_tests.cpp
- cpp/tests/utilities/column_utilities.cu
> [WIP] Scatter for structs may incorrectly flip the null bit in a child column 

- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
I collected various minor improvements that weren't pertinent to other more focused changesets during Python refactorings.
> Minor clean up of various internal column and frame utilities

- cpp/src/merge/merge.cu
Small cleanup post https://github.com/rapidsai/cudf/pull/8422
> Small cleanup

- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR is for https://github.com/rapidsai/cudf/issues/8281, since the bug has been fixed by https://github.com/rapidsai/cudf/pull/8507. So just enable the test.
> enable window lead/lag test on struct [skip ci]

- java/ci/Dockerfile.centos7
> Update GDS lib version to 1.0.0 [skip ci]

- python/cudf/cudf/testing/testing.py
Resolves #8646 so that testing equality between different types of frames can be based on approximate rather than exact equality. Note that this is a blocker for packages that need to move away from relying on `cudf.tests.utils` for testing functions, since that module is no longer exposed by `cudf`.
> Add proper support for tolerances in testing methods.

- CONTRIBUTING.md
> [skip-ci] Fix instructions for running cuDF/dask-cuDF tests in CONTRIBUTING.md

- cpp/cmake/Modules/JitifyPreprocessKernels.cmake
- cpp/include/cudf/transform.hpp
- cpp/src/transform/jit/masked_udf_kernel.cu
- cpp/src/transform/transform.cpp
- python/cudf/cudf/_lib/cpp/transform.pxd
- python/cudf/cudf/_lib/transform.pyx
- python/cudf/cudf/core/__init__.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/udf/__init__.py
- python/cudf/cudf/core/udf/_ops.py
- python/cudf/cudf/core/udf/classes.py
- python/cudf/cudf/core/udf/lowering.py
- python/cudf/cudf/core/udf/pipeline.py
- python/cudf/cudf/core/udf/typing.py
- python/cudf/cudf/tests/test_extension_compilation.py
- python/cudf/cudf/tests/test_udf_masked_ops.py
- python/cudf/cudf/utils/cudautils.py
Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

- docs/cudf/source/10min.ipynb
- docs/cudf/source/dask-cudf.rst
ref: https://github.com/dask/dask/pull/7890
> Fix dask.dataframe API docs  links after reorg

- conda/environments/cudf_dev_cuda11.0.yml
- conda/environments/cudf_dev_cuda11.2.yml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- python/cudf/cudf/tests/test_cuda_array_interface.py
- python/custreamz/dev_requirements.txt
- python/dask_cudf/dev_requirements.txt
- python/dask_cudf/setup.py
This PR introduces max version pinnings for `dask` & `distributed` to `2021.07.1`
> [REVIEW] Pin max `dask` & `distributed` versions 

- python/cudf/cudf/utils/gpu_utils.py
Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip gpuci]

- README.md
This PR updates stable version in `README.md`
> [REVIEW] Update stable version in readme[skip ci]

- cpp/src/io/parquet/writer_impl.cu
- java/pom.xml
- java/rmm_log.txt
- java/src/main/java/ai/rapids/cudf/ParquetColumnWriterOptions.java
- java/src/main/java/ai/rapids/cudf/ParquetWriterOptions.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/CMakeLists.txt
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
This PR adds the appropriate schema for Map type when writing parquet file
Keeping the Java bindings very simple to restrict the user from adding more columns than a Map supports, i.e. key and value
> Map support for ParquetWriter 

- python/cudf/cudf/utils/cudautils.py
Closes https://github.com/rapidsai/cudf/issues/9084
> Import fix

- java/src/main/native/CMakeLists.txt
fix https://github.com/rapidsai/cudf/issues/9167
verified locally w/ `ENABLE_GDS=ON`
> Fix cufilejni build include path

- python/dask_cudf/dask_cudf/backends.py
This PR does a cleanup of try/except blocks around dask dispatch objects which were introduced to maintain backward compatibility. This PR removes all such `try/except` blocks that are present in `2021.6.0` version of dask.
> [REVIEW] `dask_cudf` dispatch registering cleanup

- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/native/src/ColumnViewJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This adds in support for drop list duplicates in JNI
> Add JNI support for drop_list_duplicates

- java/src/main/native/src/TableJni.cpp
#9096 inadvertently removed the null equality parameter for the left semi and left anti equality joins in the JNI code.  This restores the old behavior since #9096 only targeted conditional joins.
> Fix JNI code for left semi and anti joins

- cpp/src/copying/copy.cu
- cpp/src/groupby/sort/group_nunique.cu
- cpp/src/groupby/sort/group_replace_nulls.cu
- cpp/src/lists/combine/concatenate_list_elements.cu
- cpp/src/lists/copying/gather.cu
- cpp/src/merge/merge.cu
- cpp/src/replace/clamp.cu
- cpp/src/replace/replace.cu
- cpp/src/rolling/grouped_rolling.cu
- cpp/src/rolling/rolling_detail.cuh
- cpp/src/strings/filling/fill.cu
This PR fixes some internal libcudf calls which were not passing stream parameters to detail functions.
> Fix some libcudf calls not passing the stream parameter

- java/ci/README.md
- java/pom.xml
- java/src/main/native/CMakeLists.txt
update cudf JNI version to 21.12.0
> Update cudf java bindings to 21.12.0-SNAPSHOT

- cpp/include/cudf/detail/aggregation/aggregation.hpp
- cpp/tests/groupby/mean_tests.cpp
Forward-merge triggered by push to `branch-21.10` that creates a PR to keep `branch-21.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.10 to branch-21.12 [skip gpuci]

- ci/cpu/prebuild.sh
Cuda 11.0 is not supported for arm64
> Fix default cuda version in prebuild.sh for arm64

- python/dask_cudf/dask_cudf/core.py
- python/dask_cudf/dask_cudf/groupby.py
- python/dask_cudf/dask_cudf/io/parquet.py
- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
A similar fix for this problem was recently submitted in #9159 and closed in favor of #9203. It seems that the test added in the latter PR was not actually capturing the original problem. However, after [dask#8072](https://github.com/dask/dask/pull/8072) is merged, the new test will certainly start failing.
> Avoid casting to list or struct dtypes in dask_cudf.read_parquet

- cpp/cmake/thirdparty/get_cucollections.cmake
Update cuco git tag to fetch the latest version
> Update cuco git tag

- conda/environments/cudf_dev_cuda11.5.yml
This PR adds 11.5 dev yml file to the cudf repo.
> [REVIEW] Add `11.5` dev.yml to `cudf`

- python/cudf/cudf/_lib/parquet.pyx
- python/cudf/cudf/tests/test_parquet.py
Forward-merge triggered by push to `branch-21.12` that creates a PR to keep `branch-22.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.12 to branch-22.02 [skip gpuci]

- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/tests/test_dataframe.py
This PR fixes a few issues with the `multiindex.memory_usage` function and enables the test for this function.
> [REVIEW] Fix multiindex memory_usage

- cpp/src/io/orc/writer_impl.cu
Fixes #9781
Current PR is to fix the problem of the alignment of Map column meta in ORC writer, to make it working like [Parquet writer](https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/src/io/parquet/writer_impl.cu#L497).
> Fix ORC writer on the alignment of Map column meta 

- cpp/benchmarks/io/parquet/parquet_writer_benchmark.cpp
This fixes a compilation error introduced in #9810. Tagging @devavret @vuule for review. Feel free to push to this PR with any fixes.
> Fix compilation of benchmark for parquet writer.

- ci/gpu/build.sh
- ci/gpu/java.sh
- ci/release/update-version.sh
Update `ucx-py` version on release using `rvc`
> Update ucx-py version on release using rvc

- conda/recipes/dask-cudf/meta.yaml
> Add missing imports tests

- CONTRIBUTING.md
This change is needed since https://github.com/rapidsai/cudf/commit/967f3397fb486368d74916ae344c0e1d9eb0a1a8 by @bdice
> Fix cudf compilation instructions.

- java/src/main/java/ai/rapids/cudf/JSONOptions.java
- java/src/main/java/ai/rapids/cudf/Table.java
- java/src/main/native/src/TableJni.cpp
- java/src/test/java/ai/rapids/cudf/TableTest.java
- java/src/test/resources/people.json
This PR is trying to add JSON reader support for java bindings.
> Java bindings for JSON reader support

- conda/environments/cudf_dev_cuda11.5.yml
- conda/recipes/cudf/meta.yaml
- python/cudf/cudf/utils/gpu_utils.py
Forward-merge triggered by push to `branch-22.02` that creates a PR to keep `branch-22.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.02 to branch-22.04 [skip gpuci]

- ci/benchmark/build.sh
- ci/gpu/build.sh
- conda/environments/cudf_dev_cuda11.5.yml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- python/custreamz/dev_requirements.txt
- python/dask_cudf/dev_requirements.txt
- python/dask_cudf/setup.py
This PR pins max `dask` & `distributed` versions.
> [REVIEW] Pin `dask` & `distributed` versions

- python/cudf/cudf/io/orc.py
> [REVIEW] Deprecate `decimal_cols_as_float` in ORC reader

- ci/cpu/prebuild.sh
Always upload all cudf packages
> Always upload cudf packages [skip-ci]

- python/cudf/cudf/core/frame.py
Some examples in docstrings were misaligned, this PR fixes it.
> [REVEIW] Fix docstrings alignment in `Frame` methods

- python/dask_cudf/dask_cudf/io/tests/test_parquet.py
As pointed out in [this issue comment](https://github.com/rapidsai/cudf/pull/10141#discussion_r798111727), we should be good to update some of dask-cudf's parquet testing to reflect bug fixes merged in https://github.com/dask/dask/pull/6047.
cc @rjzamora in case you see some other tests that could be resolved here
> Update dask-cudf parquet tests to reflect upstream bugfixes to `_metadata`

- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/core/single_column_frame.py
This PR adds some missing `nvtx` annotations for `Series` and `Index`.
> [REVIEW] Add `nvtx` annotations for `Series` and `Index`

- cpp/CMakeLists.txt
- cpp/include/cudf/copying.hpp
- cpp/include/cudf/strings/detail/combine.hpp
- cpp/include/nvtext/bpe_tokenize.hpp
- cpp/src/copying/shift.cu
- cpp/src/strings/copying/shift.cu
- cpp/src/text/subword/bpe_tokenizer.cu
- cpp/src/text/subword/bpe_tokenizer.cuh
- cpp/src/text/subword/load_merges_file.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/copying/shift_tests.cpp
- cpp/tests/text/bpe_tests.cpp
- python/cudf/cudf/core/column/column.py
Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

- java/ci/README.md
- java/pom.xml
As title, update cudf JNI version 22.06.0-SNAPSHOT
> Update cudfjni 22.06.0-SNAPSHOT

- python/cudf/cudf/_lib/column.pyi
Adds back a comment that was accidentally removed in #10523.
> [skip ci] add accidentally removed comment.

- conda/environments/cudf_dev_cuda11.5.yml
This is a follow-up to #10523 that updates the conda environment now that the [conda-forge package should be available](https://github.com/conda-forge/black-feedstock/pull/42).
> Update conda environment.

- cpp/include/cudf/io/orc.hpp
- cpp/src/io/orc/reader_impl.cu
- cpp/src/io/orc/reader_impl.hpp
- cpp/src/io/orc/stripe_data.cu
- cpp/tests/io/orc_test.cpp
- python/cudf/cudf/_lib/cpp/io/orc.pxd
- python/cudf/cudf/_lib/orc.pyx
- python/cudf/cudf/io/orc.py
- python/cudf/cudf/tests/test_orc.py
- python/cudf/cudf/utils/ioutils.py
> Remove deprecated `decimal_cols_as_float` in the ORC reader

- .pre-commit-config.yaml
- conda/environments/cudf_dev_cuda11.5.yml
This PR undoes #10535 (which was just a patch for cudf 22.04) on cudf 22.06 since we have implemented the longer term solution in #10523.
> Remove Click pinnings that are unnecessary after upgrading black.

- conda/environments/cudf_dev_cuda11.5.yml
Resolves merge conflicts in #10550.
> Forward-merge branch-22.04 to branch-22.06

- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/timedelta.py
- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/testing/_utils.py
- python/cudf/cudf/tests/test_timedelta.py
This PR simplifies the handling of binary operations for datetime and timedelta columns. It reduces the number of nearly identical helper functions and consolidates logic for datetime-timedelta interop into the DatetimeColumn since timedeltas don't need to know how to work with datetimes. These changes also significantly reduce the number of redundant checks for the type of the other operand. The raised errors are no longer as highly customized as they used to be, but the type of exception is still the same which is the level of pandas compatibility that we want to provide, and the changes let us take advantage of reflection which is a major advantage.
> Refactor binary ops for timedelta and datetime columns

- python/cudf/cudf/_lib/cpp/lists/contains.pxd
- python/cudf/cudf/_lib/lists.pyx
- python/cudf/cudf/core/column/lists.py
- python/cudf/cudf/tests/test_list.py
This PR adds python bindings for `cudf::list::index_of` in the form of `ListMethods.index`
> Add python bindings for cudf::list::index_of

- cpp/docs/BENCHMARKING.md
add device data generation to benchmark documentation
> add data generation to benchmark documentation

- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_replace.py
Fixes: #10728 
This PR resolves the issue where `columns` can be of type `MultiIndex` and retains the column types by calling into `_from_columns_like_self` which calls the required method `_set_column_names_like`.
> [REVIEW] Fix `fillna` to retain `columns` when it is `MultiIndex`

- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_udf_masked_ops.py
Closes https://github.com/rapidsai/cudf/issues/10715
> Retain series name in `Series.apply`

- python/cudf/cudf/testing/_utils.py
- python/cudf/cudf/testing/dataset_generator.py
This PR resolves an issue where all random strings generated in a series are of the same length. With this change rows of a string column will have random length data.
this PR:
```python
In [1]: from cudf.testing.dataset_generator import rand_dataframe
In [2]: cudf.DataFrame.from_arrow(rand_dataframe(
[
{
"dtype": "str",
"null_frequency": 0,
"cardinality": 100,
"max_string_length": 10,
},
],
rows=10,
))['1']
Out[2]: 
0                                          
1                                     }\1\nl
2                              vd|byshzO<R*4
3                           TmA5@%BK
WWXow`,
4              #WK
p1W\rTK3.. %}XnXmf>%d`SKp
5                                     a`N!Ua
6                                           
7       i` n6Ma}WthGa-Rd}wL@_O`i<=@|#YL E:X:
8 …
```
> [REVIEW] Fix random string data length to become variable

- python/cudf/cudf/core/indexed_frame.py
- python/cudf/cudf/testing/testing.py
- python/dask_cudf/dask_cudf/io/orc.py
> Missing `f` prefix on f-strings fix

- docs/cudf/source/user_guide/dask-cudf.md
According to https://github.com/rapidsai/cudf/issues/3176#issuecomment-545582810, the documentation is outdated. I have amended it.
> Update Dask + Pandas to Dask + cuDF path

- docs/cudf/source/user_guide/dask-cudf.md
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- java/ci/README.md
- java/pom.xml
update build version of cudfjni to 22.08.0-SNAPSHOT
> update cudfjni to 22.08.0-SNAPSHOT

- cpp/src/io/parquet/page_enc.cu
- cpp/tests/io/parquet_test.cpp
When page row limit is a multiple of chunk size, then an extra chunk is written per page (eg if max_page_size_rows is 20000, 25000 will actually be written). This change fixes that.
> Fix small error in page row count limiting

- README.md
- conda/environments/cudf_dev_cuda11.5.yml
- pyproject.toml
- python/cudf/pyproject.toml
- python/cudf_kafka/pyproject.toml
- python/custreamz/pyproject.toml
- python/dask_cudf/pyproject.toml
Starting `22.02` we dropped support for python `3.7`: https://docs.rapids.ai/notices/rsn0014/, but there are places in code-base that still have 3.7 usages. This PR removes and upgrades those usages.
> [REVIEW] Drop python `3.7` in code-base

- cpp/include/cudf/groupby.hpp
This PR fixes include that are not grouped correctly in `groupby.hpp`.
This is my first pull request that I'm working on with @bdice !
> Fix groupby include

- docs/cudf/source/api_docs/dataframe.rst
This PR adds a docstring entry for `DataFrame.value_counts` under appropriate sub-heading.
> [REVIEW] Add docstring entry for `DataFrame.value_counts`

- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/native/include/maps_column_view.hpp
- java/src/main/native/src/ColumnViewJni.cpp
- java/src/main/native/src/maps_column_view.cu
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
This PR adds a Java method to find out if a Map column contains a list of keys
> [Java] Added a Java method to check the existence of a list of keys in a map

- conda/environments/cudf_dev_cuda11.5.yml
This PR adds `nvcc` conda package to `cudf` dev environment.
> [REVIEW] Add `nvcc` conda package in dev environment

- python/cudf/cudf/core/frame.py
- python/cudf/cudf/core/indexed_frame.py
This PR is a trivial move of a function from frame.py to indexed_frame.py. That function is only used in one place throughout cuDF, inside `IndexedFrame.drop`.
> Move _drop_rows_by_label from Frame to IndexedFrame

- cpp/src/io/parquet/compact_protocol_reader.cpp
- cpp/src/io/parquet/compact_protocol_reader.hpp
- cpp/src/io/parquet/compact_protocol_writer.cpp
- cpp/src/io/parquet/compact_protocol_writer.hpp
- cpp/src/io/parquet/parquet.hpp
- cpp/src/io/parquet/parquet_common.hpp
Adds some necessary structs to parquet.hpp as well as methods to CompactProtocolReader/Writer to address #9268
I can add tests if necessary once #11177 is merged, or testing can be deferred to be included in a future PR (based on #11171)
> Add thrift support for parquet column and offset indexes

- python/cudf/cudf/_lib/CMakeLists.txt
Add a small note pointing to a CMake bug and when it will be fixed.
> [skip ci] Document why Development component is needing for CMake.

- cpp/tests/rolling/grouped_rolling_test.cpp
- cpp/tests/rolling/rolling_test.cpp
- cpp/tests/rolling/rolling_test.hpp
closes https://github.com/rapidsai/cudf/issues/5466
> cleanup unused code in rolling_test.hpp

- cpp/tests/io/parquet_test.cpp
Closes #11038
Adds read_footer() method that will be used in future work.
> Modify CheckPageRows in parquet_test to use datasources

- ci/release/update-version.sh
- conda/environments/cudf_dev_cuda11.5.yml
Ideally `dask-cuda` should be pinned to the same version of the `cudf` - just similar to `rmm`. This PR makes that change.
> [REVIEW] Pin `dask-cuda` in dev environment

- java/src/main/java/ai/rapids/cudf/ColumnView.java
- java/src/main/native/src/ColumnViewJni.cpp
- java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
Closes https://github.com/rapidsai/cudf/issues/11033
Allow `extractAllRecord` to take an `idx` > 0 and exposes `cudf::strings::extract_all_record`
> Enable positive group indices for extractAllRecord on JNI

- .pre-commit-config.yaml
- python/cudf/pyproject.toml
- python/cudf_kafka/pyproject.toml
- python/custreamz/pyproject.toml
- python/dask_cudf/pyproject.toml
This PR simply makes explicit what we already do, which is have a single `black` config that we apply to all four Python packages contained in the cudf repo. Contributes to #10758.
> Remove redundant black config specifications.

- .pre-commit-config.yaml
- python/cudf/setup.cfg
- python/dask_cudf/dask_cudf/core.py
- setup.cfg
This PR moves the mypy config to the top-level setup.cfg and changes pre-commit to run mypy on all subpackages. Contributes to #10758.
> Run mypy on all packages

- cpp/include/cudf/io/detail/parquet.hpp
- cpp/src/io/functions.cpp
- cpp/src/io/parquet/reader_impl.cu
- cpp/src/io/parquet/reader_impl.hpp
Closes #10903.
This PR makes the parquet reader class take a stream parameter.
> Update parquet reader to take stream parameter

- python/cudf/setup.py
- python/dask_cudf/setup.py
This resolves #8104. Note that that issue also requests an update to requirements.txt files, but those no longer exist.
> Add cupy version to setup.py install_requires

- cpp/src/io/parquet/page_enc.cu
In my endless wandering through parquet code, I found this unused code. Removing it.
> removing some unused code

- cpp/src/io/parquet/page_enc.cu
- cpp/src/io/parquet/parquet_gpu.hpp
- cpp/src/io/parquet/writer_impl.cu
Closes #10948 
Adds support for dictionary encoding with 24 bit indices.
> Add 24 bit dictionary support to Parquet writer

- docs/cudf/source/api_docs/dataframe.rst
- docs/cudf/source/api_docs/series.rst
This PR updates a few missing data operation APIs in docs.
> [REVIEW] Update missing data handling APIs in docs

- conda/recipes/libcudf/meta.yaml
- cpp/CMakeLists.txt
- cpp/include/cudf/lists/detail/set_operations.hpp
- cpp/include/cudf/lists/set_operations.hpp
- cpp/include/doxygen_groups.h
- cpp/src/lists/set_operations.cu
- cpp/src/lists/utilities.cu
- cpp/src/lists/utilities.hpp
- cpp/tests/CMakeLists.txt
- cpp/tests/lists/set_operations/difference_distinct_tests.cpp
- cpp/tests/lists/set_operations/have_overlap_tests.cpp
- cpp/tests/lists/set_operations/intersect_distinct_tests.cpp
- cpp/tests/lists/set_operations/union_distinct_tests.cpp
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

- cpp/examples/basic/CMakeLists.txt
This version of CPM corrects issues when the build directory contains symlinks
> libcudf c++ example updated to CPM version 0.35.3

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Resolves: https://github.com/rapidsai/cudf/issues/10116
> Fix for: error when assigning a value to an empty series

- cpp/src/rolling/grouped_rolling.cu
The preceding/following columns constructed for the grouped rolling window
functions are temporary columns, to be discarded after aggregation. These
should be constructed on the default memory resource.
This commit should correct the problem.
> Fix incorrect memory resource used in rolling temp columns

- ci/cpu/upload.sh
This PR fixes an issue where the `strings_udf` conda package for python 3.9 is missing, due to the way `strings_udf` is plumbed through CI.
> Add `strings_udf` package for python 3.9

- python/cudf/cudf/core/column/column.py
Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

- conda/environments/cudf_dev_cuda11.5.yml
This PR switches the `pyorc` install from a `pip` wheel to a `conda` package.
xref: https://github.com/rapidsai/cudf/pull/7085#discussion_r553446553
> Use conda-forge's `pyorc`

- cpp/doxygen/developer_guide/TESTING.md
Update text to include coding tests outside the `cudf` or the `cudf::test` namespace.
Realized our test guidelines needed to be updated while working on #11734.
> Update Unit Testing in libcudf guidelines to code tests outside the cudf::test namespace

- cpp/src/io/utilities/parsing_utils.cuh
- cpp/src/strings/json/json_path.cu
- cpp/tests/io/json_test.cpp
Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

- python/cudf/cudf/_lib/binaryop.pyx
- python/cudf/cudf/core/column/decimal.py
- python/cudf/cudf/tests/test_binops.py
> [REVIEW] Fix decimal binary operations

- CODE_OF_CONDUCT.md
This repo's `CODE_OF_CONDUCT.md` is superseded by an organization-wide policy: https://github.com/rapidsai/.github/pull/3
> Use rapidsai CODE_OF_CONDUCT.md

- java/src/main/native/src/ColumnVectorJni.cpp
This removes some special case code that is no longer needed.
> Clean up existing JNI scalar to column code

- docs/cudf/source/api_docs/index_objects.rst
- docs/cudf/source/api_docs/series.rst
- python/cudf/cudf/core/_base_index.py
- python/cudf/cudf/core/index.py
- python/cudf/cudf/core/series.py
- python/cudf/cudf/tests/test_index.py
- python/cudf/cudf/tests/test_series.py
Resolves: #11975 
This PR adds support for `Series.hasnans` and `Index.hasnans`
> [REVIEW] Add `Series.hasnans` and `Index.hasnans`

- python/strings_udf/cpp/include/cudf/strings/udf/replace.cuh
Add udf function for replacing all occurrences of a target string within a source string with a replacement string.
This is to support #12207
> Add cudf::strings:udf::replace function

- ci/benchmark/build.sh
- ci/cpu/build.sh
- ci/gpu/build.sh
- conda/environments/all_cuda-115_arch-x86_64.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- dependencies.yaml
- python/dask_cudf/setup.py
> Forward merge 22.12 into 23.02

- python/cudf/cudf/core/join/_join_helpers.py
- python/cudf/cudf/core/join/join.py
- python/cudf/cudf/tests/test_joining.py
> Fix warnings in test_joining.py

- cpp/tests/table/experimental_row_operator_tests.cu
Fixes `table` gtests source files coded in namespace `cudf::test`
This only required fixing `experimental_row_operator_tests.cu`
No function or test has changed just the test source code reworked per namespaces.
> Fix table gtests coded in namespace cudf::test

- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/tests/test_groupby.py
> Fix warnings in test_groupby.py

- docs/cudf/source/user_guide/guide-to-udfs.ipynb
This PR adds the latest features to the `strings_udf` docs and adds a bit about the memory allocation mechanism since it is user facing for now. Also removes the MVC restriction since it no longer exists.
> `strings_udf` doc update

- cpp/src/text/generate_ngrams.cu
Rework `nvtext::generate_character_ngrams` to use the internal `make_strings_children`. This simplifies the code and allows the operation to throw an error if it the output would exceed the size limit of a column.
Reference #12167
> Rework nvtext::generate_character_ngrams to use make_strings_children

- docs/cudf/source/api_docs/string_handling.rst
- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_string.py
Adds support for `str.removeprefix()` and `str.removesuffix` to cudf.
Closes #12555
> Add strings methods removeprefix and removesuffix

- docs/cudf/source/api_docs/groupby.rst
Include missing groupby functions in documentation
> Include missing groupby functions in documentation

- python/cudf/cudf/_lib/groupby.pyx
- python/cudf/cudf/core/dtypes.py
- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/tests/test_groupby.py
Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.02 to branch-23.04

- cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
Signed-off-by: Sameer Raheja <sraheja@nvidia.com>
> Fix link to NVTX

- ci/benchmark/build.sh
- ci/cpu/build.sh
- ci/gpu/build.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/dask-cudf/run_test.sh
- dependencies.yaml
- python/dask_cudf/setup.py
This PR resolves conflicts in auto merger: https://github.com/rapidsai/cudf/pull/12707
> [REVIEW] Resolve auto-merger

- python/cudf/cudf/tests/test_groupby.py
- python/cudf/udf_cpp/groupby/function.cu
Closes https://github.com/rapidsai/cudf/issues/12686
> Fix faulty conditional logic in JIT `GroupBy.apply`

- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/tests/test_groupby.py
Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.04 to branch-23.06

- python/cudf/cudf/core/column_accessor.py
This PR removes a `MultiIndex` construction workaround that retains correct dtypes of each level. Thus fixing 19 pytests:
```bash
= 907 failed, 86196 passed, 2034 skipped, 992 xfailed, 165 xpassed in 536.13s (0:08:56) =
```
```bash
= 926 failed, 86177 passed, 2034 skipped, 992 xfailed, 165 xpassed in 545.17s (0:09:05) =
```
> [REVIEW] Fix `MultiIndex` as column construction with `pandas-2.0`

- cpp/examples/basic/CMakeLists.txt
- cpp/examples/strings/CMakeLists.txt
- cpp/libcudf_kafka/CMakeLists.txt
- cpp/src/io/parquet/writer_impl.cu
- cpp/src/io/utilities/column_buffer.cpp
- cpp/src/reductions/scan/scan.cuh
- cpp/src/reductions/scan/scan_exclusive.cu
- cpp/src/reductions/scan/scan_inclusive.cu
- fetch_rapids.cmake
- java/src/main/native/CMakeLists.txt
> Remove more instances of `UNKNOWN_NULL_COUNT`

- python/cudf/cudf/tests/test_parquet.py
Pandas-2.0 fixed the following issue where dtype of the column was being changed even when `np.nan` was not being written to it:
```python
In [1]: import pandas as pd
In [2]: df = pd.DataFrame({'a':[1, 2, 3]})
In [3]: df.dtypes
Out[3]: 
a    int64
dtype: object
In [4]: df
Out[4]: 
a
0  1
1  2
2  3
In [7]: df[[False]*3] = np.nan
In [8]: df
Out[8]: 
a
0  1
1  2
2  3
In [9]: df.dtypes
Out[9]: 
a    int64
dtype: object
```
Bug in pre-2.0:
```python
In [1]: import pandas as pd
In [2]: df = pd.DataFrame({'a':[1, 2, 3]})
In [3]: df.dtypes
Out[3]: 
a    int64
dtype: object
In [4]: df
Out[4]: 
a
0  1
1  2
2  3
In [7]: df[[False]*3] = np.nan
In [8]: df
Out[8]: 
a
0  1.0
1  2.0
2  3.0
In [9]: df.dtypes
Out[9]: 
a    float64
dtype: object
```
`make_pdf` was basically operating correctly with the help …
> Fix parquet pytests errors with pandas-2.0

- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/cudf/meta.yaml
- dependencies.yaml
- python/cudf/cudf/tests/test_array_ufunc.py
- python/cudf/pyproject.toml
- python/dask_cudf/pyproject.toml
> Update cupy dependency

- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- conda/recipes/cudf/meta.yaml
This PR addresses a couple of minor items that were left incomplete when #13289 was merged, see https://github.com/rapidsai/cudf/pull/13289/#discussion_r1186481862 and https://github.com/rapidsai/cudf/pull/13289/#discussion_r1186485621.
> Address feedback from 13289

- python/cudf/cudf/core/column/string.py
- python/cudf/cudf/tests/test_text.py
Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.06 to branch-23.08

- cpp/include/cudf/ast/expressions.hpp
- cpp/include/cudf/datetime.hpp
- cpp/include/cudf/detail/indexalator.cuh
- cpp/include/cudf/detail/tdigest/tdigest.hpp
- cpp/include/cudf/detail/utilities/vector_factories.hpp
- cpp/include/cudf/io/orc_metadata.hpp
- cpp/include/cudf/table/row_operators.cuh
Remove/update repeated documentation text
Remove declaration repetitions in tdigest.hpp
> Cleanup doc repetitions in libcudf

- python/cudf/cudf/tests/test_groupby.py
This PR fixes a groupby pytest by performing a special version based handling, we will need this handling because of no support for `numeric_only` in groupby.agg yet.
> Fix a groupby pytest related to `numeric_only`

- build.sh
Fixes a bug introduced in https://github.com/rapidsai/cudf/pull/13507
> Make sure to build without isolation or installing dependencies

- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/tests/test_reshape.py
> Fix cudf.melt when there are more than 255 columns

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- ci/build_wheel_cudf.sh
- ci/build_wheel_dask_cudf.sh
- ci/release/update-version.sh
- ci/test_wheel_cudf.sh
- ci/test_wheel_dask_cudf.sh
> Branch 23.10 merge 23.08

- ci/test_wheel_dask_cudf.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/dask-cudf/run_test.sh
- dependencies.yaml
- python/dask_cudf/pyproject.toml
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.08 to branch-23.10

- cpp/include/cudf/filling.hpp
- cpp/src/filling/calendrical_month_sequence.cu
- cpp/src/filling/fill.cu
- cpp/src/filling/repeat.cu
- cpp/src/filling/sequence.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/streams/filling_test.cpp
> Expose streams in public filling APIs

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
PR updates `rapidsai/ci` references to `rapidsai/ci-conda`
> Update image names

- cpp/benchmarks/text/ngrams.cpp
- cpp/benchmarks/text/tokenize.cpp
- cpp/include/nvtext/generate_ngrams.hpp
- cpp/include/nvtext/ngrams_tokenize.hpp
- cpp/src/lists/count_elements.cu
- cpp/src/replace/clamp.cu
- cpp/src/text/generate_ngrams.cu
- cpp/src/text/jaccard.cu
- cpp/src/text/ngrams_tokenize.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/streams/text/ngrams_test.cpp
- cpp/tests/text/ngrams_tests.cpp
- cpp/tests/text/ngrams_tokenize_tests.cpp
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_dataframe.py
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.10 to branch-23.12

- ci/test_wheel_dask_cudf.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/custreamz/meta.yaml
- conda/recipes/dask-cudf/meta.yaml
- conda/recipes/dask-cudf/run_test.sh
- dependencies.yaml
- python/dask_cudf/pyproject.toml
This PR resolves conflicts in auto-merger: https://github.com/rapidsai/cudf/pull/14228
> Forward merge `23.10` into `23.12`

- ci/release/update-version.sh
- cpp/examples/README.md
- cpp/examples/basic/CMakeLists.txt
- cpp/examples/build.sh
- cpp/examples/fetch_dependencies.cmake
- cpp/examples/nested_types/CMakeLists.txt
- cpp/examples/nested_types/deduplication.cpp
- cpp/examples/nested_types/example.json
- cpp/examples/strings/CMakeLists.txt
Manual forward merge from 23.12 to 24.02. This PR should not be squashed. Closes #14425.
> Forward-merge branch-23.12 to branch-24.02

- cpp/src/transform/row_conversion.cu
A call to a deprecated `cudf::make_strings_column` factory function was introduced in #14664.
This call had been previously fixed in #14461 but was lost when the source file was moved in #14664.
> Fix call to deprecated factory function

- ci/build_wheel_cudf.sh
This was an oversight in #13531
> Fix CMake args

- docs/cudf/source/conf.py
Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.02 to branch-24.04

- .github/workflows/pr.yaml
> Branch 24.04 merge branch 24.02

- python/cudf/cudf/core/indexed_frame.py
- python/cudf/cudf/tests/test_indexing.py
Closes https://github.com/rapidsai/cudf/issues/14863.
> Align datetimeindex slicing behaviour with Pandas 2.x

- python/cudf/cudf/tests/test_duplicates.py
- python/cudf/cudf/tests/test_string.py
- python/dask_cudf/dask_cudf/tests/test_core.py
A few cleanups in test files following #14916.
> Update tests for pandas 2.

- python/cudf/pyproject.toml
- python/cudf_kafka/pyproject.toml
- python/custreamz/pyproject.toml
- python/dask_cudf/pyproject.toml
> Exclude tests from builds

- cpp/src/json/json_path.cu
Updates `cudf::get_json_object()` to use the offsetalator to build the output strings column.
It adds a sizes vector to hold the output row lengths which is then converted to offsets using the new `make_offsets_child_column()` utitlity.
> Use offsetalator in cudf::get_json_object()

- docs/cudf/source/developer_guide/index.md
> Fix broken link for developer guide

- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/tests/test_reductions.py
- python/cudf/cudf/tests/test_sorting.py
> Fix reductions when DataFrame has MulitIndex columns

- docs/cudf/source/user_guide/index.md
- docs/cudf/source/user_guide/pandas-2.0-breaking-changes.md
Forward-merge triggered by push to `branch-24.04` that creates a PR to keep `branch-24.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.04 to branch-24.06

- python/cudf/cudf/_lib/json.pyx
- python/cudf/cudf/_lib/parquet.pyx
Since the performance in these files is not critical, we don't need to elide bounds checking in (for example) list accesses.
- Closes #15360
> Remove boundscheck=False setting in cython files

- python/cudf/cudf/pandas/scripts/run-pandas-tests.sh
Locally these don't seem to hang or crash workers
> Enable tests/scalar and test/series in cudf.pandas tests

- python/cudf/cudf/core/indexed_frame.py
Lighter weight alternative to https://github.com/rapidsai/cudf/pull/15843 to unblock dask-cuda's breakage.
> Remove problematic call of index setter to unblock dask-cuda CI

- .pre-commit-config.yaml
- cpp/cmake/thirdparty/patches/cccl_override.json
- cpp/cmake/thirdparty/patches/revert_pr_211_cccl_2.5.0.diff
- cpp/cmake/thirdparty/patches/thrust_disable_64bit_dispatching_cccl_2.5.0.diff
- cpp/cmake/thirdparty/patches/thrust_faster_scan_compile_times_cccl_2.5.0.diff
- cpp/cmake/thirdparty/patches/thrust_faster_sort_compile_times_cccl_2.5.0.diff
- cpp/src/io/comp/statistics.cu
- cpp/src/io/orc/reader_impl_decode.cu
- cpp/src/io/orc/stripe_init.cu
- cpp/src/io/parquet/page_string_decode.cu
- cpp/src/io/parquet/reader_impl_preprocess.cu
- cpp/src/io/utilities/data_casting.cu
- cpp/src/join/distinct_hash_join.cu
- cpp/src/strings/split/split_re.cu
Resolves conflicts in : https://github.com/rapidsai/cudf/pull/15868
> Manual merge of Branch 24.08 from 24.06

- python/cudf_polars/cudf_polars/dsl/ir.py
- python/cudf_polars/tests/test_python_scan.py
> Raise early on unhandled PythonScan node

- python/cudf_polars/cudf_polars/containers/column.py
- python/cudf_polars/tests/containers/__init__.py
- python/cudf_polars/tests/containers/test_column.py
- python/cudf_polars/tests/containers/test_dataframe.py
This ensures we cover all implementation.
> Test behaviour of containers

- python/cudf_polars/cudf_polars/dsl/expr.py
- python/cudf_polars/tests/expressions/test_agg.py
Also add more expansive comments on the unreachable paths.
> Add full coverage for whole-frame Agg expressions

- python/cudf/cudf/_lib/pylibcudf/libcudf/lists/lists_column_view.pxd
> Add missing methods to lists/list_column_view.pxd in pylibcudf

- .github/workflows/build.yaml
Publish nightlies for cudf-polars.
> Publish cudf-polars nightlies

- cpp/cmake/thirdparty/get_thread_pool.cmake
- python/cudf/cudf/pandas/_wrappers/pandas.py
> Branch 24.10 merge branch 24.08

- docs/cudf/source/cudf_pandas/how-it-works.md
- python/cudf/cudf/_lib/pylibcudf/utils.pyx
- python/cudf/cudf/pandas/__init__.py
> Forward-merge branch-24.08 into branch-24.10

- .github/workflows/build.yaml
This was missed in #16299 and is necessary to get builds published.
> Add build job for pylibcudf

- python/cudf/cudf/_lib/pylibcudf/column.pyx
- python/cudf/cudf/_lib/pylibcudf/libcudf/types.pxd
- python/cudf/cudf/_lib/pylibcudf/types.pxd
- python/cudf/cudf/_lib/pylibcudf/types.pyx
- python/cudf/cudf/pylibcudf_tests/test_column_from_device.py
> Backport: Remove cuDF dependency from pylibcudf column from_device tests (#16441)

- python/cudf_polars/cudf_polars/dsl/expr.py
- python/cudf_polars/tests/expressions/test_numeric_unaryops.py
- python/cudf_polars/tests/test_groupby.py
- python/cudf_polars/tests/test_sort.py
This PR adds support for additional unaryops through `cudf-polars`. 
Closes https://github.com/rapidsai/cudf/issues/16566
> Add more `cudf-polars` unaryops

- cpp/benchmarks/sort/rank_lists.cpp
- cpp/benchmarks/sort/rank_structs.cpp
> Fix `cudf::rank` not getting enough params

- python/cudf_polars/cudf_polars/dsl/expr.py
- python/cudf_polars/tests/expressions/test_stringfunction.py
This way if we don't support any features of the pattern, we correctly fall back to CPU.
> Move creation of regex program to initialisation

- .github/workflows/test.yaml
Following up #16645, and adding a gpu node type to the nightly CI job
> [BUG] Add gpu node type to cudf-pandas 3rd-party integration nightly CI job

- docs/cudf/source/conf.py
- python/cudf/cudf/core/multiindex.py
Mostly just return type annotations. No logic changes.
> Add return type annotations to MultiIndex

- python/cudf_polars/cudf_polars/dsl/expr.py
- python/cudf_polars/tests/expressions/test_booleanfunction.py
We previously didn't support this case correctly, but it's not too bad.
This would be much easier if we could do it in libcudf, hence: https://github.com/rapidsai/cudf/issues/16475
> Implement Kleene logic handling for Any/All and bitwise Or/And

- python/cudf/cudf/core/reshape.py
- python/cudf/cudf/tests/test_onehot.py
> Support drop_first in get_dummies

- ci/release/update-version.sh
Adds a `dependency.yaml` for `cudf.pandas` third party tests to `update-version.sh`
> Add cudf.pandas dependencies.yaml to update-version.sh

- cpp/include/cudf/column/column_device_view.cuh
- cpp/include/cudf/column/column_view.hpp
- cpp/include/cudf/detail/aggregation/aggregation.hpp
- cpp/include/cudf/detail/groupby/sort_helper.hpp
- cpp/include/cudf/detail/utilities/host_vector.hpp
- cpp/include/cudf/dictionary/dictionary_column_view.hpp
- cpp/include/cudf/groupby.hpp
- cpp/include/cudf/io/json.hpp
- cpp/include/cudf/lists/lists_column_view.hpp
- cpp/include/cudf/scalar/scalar.hpp
- cpp/include/cudf/strings/detail/char_tables.hpp
- cpp/include/cudf/strings/regex/regex_program.hpp
- cpp/include/cudf/strings/string_view.cuh
- cpp/include/cudf/strings/strings_column_view.hpp
- cpp/include/cudf/structs/structs_column_view.hpp
- cpp/include/cudf/tdigest/tdigest_column_view.hpp
- cpp/include/cudf/utilities/span.hpp
This PR includes a first set of fixes found by applying the latest version of clang-tidy to our code base. To keep things reviewable, I've restricted this PR to a smaller set of changes just to the includes.
> clang-tidy fixes part 1

- cpp/src/io/json/nested_json_gpu.cu
> Branch 24.12 merge branch 24.10

- python/cudf/cudf/_lib/strings/translate.pyx
- python/pylibcudf/pylibcudf/libcudf/strings/CMakeLists.txt
- python/pylibcudf/pylibcudf/libcudf/strings/translate.pxd
- python/pylibcudf/pylibcudf/strings/CMakeLists.txt
- python/pylibcudf/pylibcudf/strings/__init__.pxd
- python/pylibcudf/pylibcudf/strings/__init__.py
- python/pylibcudf/pylibcudf/strings/translate.pxd
- python/pylibcudf/pylibcudf/strings/translate.pyx
- python/pylibcudf/pylibcudf/tests/test_string_translate.py
> Add string.translate APIs to pylibcudf

- .devcontainer/cuda12.5-conda/devcontainer.json
- ci/release/update-version.sh
This will make sure that profilers are available by default for everyone using our devcontainers.
> Add profilers to CUDA 12 conda devcontainers

- cpp/src/datetime/timezone.cpp
Resolves https://github.com/rapidsai/cudf/issues/8795.
Also needed for https://github.com/rapidsai/cudf/pull/16998.
> Include timezone file path in error message

- cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
> Changing developer guide int_64_t to int64_t

- cpp/include/cudf/join.hpp
- cpp/src/join/conditional_join.cu
- cpp/src/join/mixed_join.cu
- python/pylibcudf/pylibcudf/join.pxd
- python/pylibcudf/pylibcudf/join.pyx
- python/pylibcudf/pylibcudf/libcudf/join.pxd
- python/pylibcudf/pylibcudf/tests/test_join.py
Expose these join types to pylibcudf, they will be useful for implement inequality joins in cudf polars.
> Expose mixed and conditional joins in pylibcudf

- docs/cudf/source/user_guide/io/io.md
- python/cudf/cudf/utils/ioutils.py
> Add documentation for low memory readers

- cpp/CMakeLists.txt
> Add version config

- ci/run_cudf_polars_polars_tests.sh
This is likely the easiest fix for avoiding CI errors from this part of the code.
> Ignore errors when testing glibc versions

- python/cudf/cudf/core/frame.py
- python/cudf/cudf/tests/test_dataframe.py
> Return categorical values in to_numpy/to_cupy

- python/cudf_polars/cudf_polars/testing/plugin.py
On Ubuntu 20.04, the tzdata package contains a bunch of symlinks for
obsolete timezone names. However, the chrono_tz package that polars
uses doesn't read /usr/share/zoneinfo, instead packaging the current
zoneinfo database from IANA. Consequently, when this
hypothesis-generated test runs and generates timezones from the
available zoneinfo-reported timezones, we can get an error from polars
that the requested timezone is unknown. Since this is random, just
skip it, rather than xfailing.
> Skip polars test that can generate timezones that chrono_tz doesn't know

- cpp/src/io/fst/agent_dfa.cuh
- cpp/src/io/fst/in_reg_array.cuh
- cpp/src/io/parquet/page_enc.cu
- cpp/src/strings/case.cu
- cpp/src/strings/replace/multi.cu
- cpp/src/strings/replace/replace.cu
- cpp/src/strings/split/split.cuh
- cpp/src/text/tokenize.cu
- cpp/src/text/vocabulary_tokenize.cu
We are deprecating a lot of old features, that have better replacements.
Make cuDF build with latest cccl
> Make cudf build with latest CCCL

- .github/CODEOWNERS
- .pre-commit-config.yaml
Issue: https://github.com/rapidsai/pre-commit-hooks/issues/61
> Add `verify-codeowners` hook

- python/cudf/cudf/core/_internals/copying.py
- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/lists.py
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/indexed_frame.py
- python/cudf/cudf/core/multiindex.py
Towards https://github.com/rapidsai/cudf/issues/17843
> Remove cudf.Scalar from scatter APIs

- docs/cudf/source/cudf_polars/index.rst
due to questions that arose, I wanted to clarify up front that the GPU Open beta works on a single GPU.
Closes #17871
> Explicitly call out that the GPU open beta runs on a single GPU

- ci/cudf_pandas_scripts/third-party-integration/run-library-tests.sh
- ci/cudf_pandas_scripts/third-party-integration/test.sh
- python/cudf/cudf_pandas_tests/third_party_integration_tests/tests/conftest.py
This PR fixes cudf ci nightly test failures: https://github.com/rapidsai/cudf/actions/runs/13097249137/job/36541039646
> Fix third-party `cudf.pandas` tests

- docs/cudf/source/pylibcudf/index.rst
Fixes incorrect pylibcudf/libcudf example created in #17803.
> Fix incorrect example in pylibcudf docs

- cpp/src/io/avro/reader_impl.cu
- cpp/src/quantiles/tdigest/tdigest_aggregation.cu
This avoids failures in CCCL CI
Pulled out of #17793
> Initialize inout parameter

- ci/test_cudf_polars_polars_tests.sh
- python/cudf_polars/cudf_polars/testing/plugin.py
These tests re failing in CI, but I'm not able to reproduce the error locally. This PR is intended to unblock CI, while I investigate.
> Skip failing polars tests

- ci/test_cudf_polars_polars_tests.sh
- python/cudf_polars/cudf_polars/testing/plugin.py
Manual forward merge. The commits should _not_ be squashed.
> Forward merge branch-25.02 to branch-25.04

- .github/workflows/test.yaml
This enables narwhals tests in nightly CI.
> Run narwhals tests nightly.

- python/pylibcudf/pylibcudf/libcudf/utilities/traits.pxd
> Make pylibcudf traits raise exceptions gracefully rather than terminating in C++

- .github/workflows/test.yaml
This job was removed from PRs in https://github.com/rapidsai/cudf/pull/18091 but I forgot to remove the corresponding nightly test job.
> Remove now non-existent job

- python/cudf/cudf/core/subword_tokenizer.py
- python/cudf/cudf/tests/test_dlpack.py
> Branch 25.04 merge branch 25.02

- python/cudf/cudf/core/df_protocol.py
- python/cudf/cudf/core/subword_tokenizer.py
- python/cudf/cudf/tests/test_dlpack.py
PR to release `v25.02.02` patch
> [RELEASE] `v25.02.02`

- docs/cudf/source/user_guide/cupy-interop.ipynb
> Use protocol for dlpack instead of deprecated function in cupy notebook

- python/cudf/cudf/core/column/column.py
- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/numerical.py
- python/cudf/cudf/core/column/timedelta.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/scalar.py
- python/cudf/cudf/utils/dtypes.py
Similar to https://github.com/rapidsai/cudf/pull/18141
> Prune more seldom used dtype utils

- .github/workflows/pr.yaml
- python/cudf_polars/cudf_polars/callback.py
xref https://github.com/rapidsai/shared-workflows/pull/293
> Disable ARM CI in C++ and Python test CI jobs

- python/cudf/cudf/core/_internals/where.py
- python/cudf/cudf/core/column/column.py
Toward https://github.com/rapidsai/cudf/issues/17843
> Remove cudf.Scalar in where

- cpp/src/io/fst/agent_dfa.cuh
- cpp/src/io/fst/dispatch_dfa.cuh
It can easily overflow, so use `cuda::ceil_div` instead
> Drop `CUB_QUOTIENT_CEILING`

- cpp/src/ast/operators.cpp
- cpp/src/io/statistics/typed_statistics_chunk.cuh
- cpp/src/reductions/minmax.cu
> Drop more thrust functions with libcu++ ones

- python/cudf_polars/cudf_polars/dsl/expressions/slicing.py
- python/cudf_polars/cudf_polars/dsl/expressions/sorting.py
- python/cudf_polars/cudf_polars/dsl/translate.py
- python/cudf_polars/tests/test_top_and_bottom_k.py
> Support `top-k` expression

- python/cudf/cudf/core/column/categorical.py
- python/cudf/cudf/tests/test_binops.py
closes https://github.com/rapidsai/cudf/issues/18196
> Support comparitive binops between catgorical and non categorical

- cpp/src/interop/to_arrow_device.cu
> Remove RMM macro usage from to_arrow_device.cu

- cpp/src/text/vocabulary_tokenize.cu
Fix the logic in the nvtext vocabulary-tokenizer to support large strings appropriately. Minor changes to types and kernel calls.
> Support large strings in nvtext vocabulary-tokenizer

- cpp/CMakeLists.txt
> Fix zstd build interface include definition

- .github/workflows/pr.yaml
- ci/test_narwhals.sh
- dependencies.yaml
> Test against stable tags for narwhals

- python/pylibcudf/pylibcudf/column.pyx
- python/pylibcudf/pylibcudf/contiguous_split.pyx
- python/pylibcudf/pylibcudf/null_mask.pyx
- python/pylibcudf/pylibcudf/transform.pyx
- python/pylibcudf/pylibcudf/utils.pxd
- python/pylibcudf/pylibcudf/utils.pyx
> Remove casting functions in pylibcudf utils

- CONTRIBUTING.md
- docs/cudf/source/developer_guide/documentation.md
- Closes #18410  
cc: @brandon-b-miller
> improve docs related to documentation contribution

- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/core/column/timedelta.py
- python/cudf/cudf/tests/test_datetime.py
- python/cudf/cudf/tests/test_timedelta.py
xref https://github.com/rapidsai/cudf/issues/5695
> Use `cached_property` for Datetime and Timedelta column properties

- cpp/benchmarks/io/cuio_common.cpp
- cpp/src/utilities/host_memory.cpp
Discovered in CCCL CI: https://github.com/NVIDIA/cccl/actions/runs/14806960648/job/41576694188#step:6:2863
> Add missing header to host_memory.cpp

- python/cudf/cudf/tests/test_repr.py
Resolves https://github.com/rapidsai/cudf/issues/18665.
> Skip test_large_unique_categories_repr in CI

- .github/workflows/test.yaml
Follow on to #18692 to include same change for nightly tests.
> Run unit-tests-cudf-pandas on branch-25.06 for nightly tests

- python/cudf/benchmarks/API/bench_series.py
Follow up of https://github.com/rapidsai/cudf/pull/18555 (specifically this [comment](https://github.com/rapidsai/cudf/pull/18555#issuecomment-2829131432))
> Add more `cudf.Series` microbenchmarks

- python/pylibcudf/pylibcudf/column.pyx
- python/pylibcudf/pylibcudf/tests/common/utils.py
- python/pylibcudf/pylibcudf/tests/test_column_from_array.py
Contributes to https://github.com/rapidsai/cudf/issues/15132. Follows up #18425, to address comments https://github.com/rapidsai/cudf/pull/18425#discussion_r2045760125 and https://github.com/rapidsai/cudf/pull/18425#discussion_r2081792098
>  Support creating a pylibcudf Column from a general ndarray

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- dependencies.yaml
- python/cudf/pyproject.toml
I don't think we use this package anymore after https://github.com/rapidsai/cudf/pull/18715
> Remove pytest-rerunfailures

- python/cudf_polars/cudf_polars/testing/plugin.py
https://github.com/pola-rs/polars/issues/22558
> Skip test that fails due to polars issue

- python/pylibcudf/pylibcudf/tests/test_column_from_array.py
> Avoid going OOM in `test_row_limit_exceed_raises` by using dummy array

- .github/workflows/pr.yaml
- ci/cudf_pandas_scripts/fetch_pandas_versions.py
- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- conda/recipes/cudf/recipe.yaml
- cpp/include/cudf/detail/join/distinct_hash_join.cuh
- cpp/include/cudf/table/experimental/row_operators.cuh
- cpp/include/cudf/table/primitive_row_operators.cuh
- cpp/src/io/comp/uncomp.cpp
- cpp/src/join/distinct_hash_join.cu
- dependencies.yaml
- python/cudf/cudf/io/parquet.py
- python/cudf/cudf/pandas/_wrappers/pandas.py
- python/cudf/cudf/tests/test_parquet.py
- python/cudf/cudf/utils/ioutils.py
- python/cudf/pyproject.toml
- python/dask_cudf/pyproject.toml
- python/pylibcudf/pylibcudf/tests/test_column_from_array.py
Manual forward merge from 25.06 to 25.08. Supersedes https://github.com/rapidsai/cudf/pull/18803
> Forward-merge branch-25.06 to branch-25.08

- python/cudf_polars/cudf_polars/dsl/ir.py
- python/cudf_polars/cudf_polars/testing/io.py
- python/cudf_polars/tests/test_scan.py
> Scan a headerless CSV file with column names provided

- python/cudf/cudf/core/indexed_frame.py
- python/cudf/cudf/core/join/_join_helpers.py
- python/cudf/cudf/core/join/join.py
- python/cudf/cudf/core/tools/datetimes.py
- python/cudf/cudf/core/tools/numeric.py
- python/cudf/cudf/core/window/rolling.py
Towards https://github.com/rapidsai/cudf/issues/10820.
Will help us better identify if objects needs to be moved to different locations for better import dependency chains
> Remove toplevel `import cudf` from window/tools/join directories

- python/cudf/cudf/io/avro.py
- python/cudf/cudf/io/csv.py
- python/cudf/cudf/io/dlpack.py
- python/cudf/cudf/io/hdf.py
- python/cudf/cudf/io/json.py
- python/cudf/cudf/io/orc.py
- python/cudf/cudf/io/parquet.py
- python/cudf/cudf/io/text.py
Towards https://github.com/rapidsai/cudf/issues/10820.
Will help us better identify if objects needs to be moved to different locations for better import dependency chains
> Remove toplevel `import cudf` from cudf/io files

- python/cudf_polars/cudf_polars/dsl/expressions/aggregation.py
- python/cudf_polars/tests/expressions/test_len.py
closes https://github.com/rapidsai/cudf/issues/18846
> Fix cudf_polars pl.col(...).len() always excluding null values

- python/cudf_polars/cudf_polars/dsl/ir.py
> Update `__all__` in `cudf_polars/dsl/ir.py`

- python/cudf/cudf/pandas/__init__.py
Previously if an `rmm` resource was already configured, installing `cudf.pandas` would warn. This made for a noisy experience if the user loaded `cuml.accel` before loading `cudf.pandas`.
This PR changes the warning to only be raised if the user explicitly set `CUDF_PANDAS_RMM_MODE`. This makes sense to me - if the user made an explicit request for `cudf.pandas` to do something and `cudf` ignores it, the user should be made aware. But for users that never asked `cudf.pandas` to do something with rmm, warning about rmm (with the environment variable in the message) doesn't feel actionable.
This change lets users mix loading `cudf.pandas` after `cuml.accel` without seeing a warning.
```python
%load_ext cuml.accel
%load_ext cudf.pandas
```
I didn't add a test here (I didn't see any existing …
> Only warn in cudf.pandas if rmm mode explicitly set and rmm already configured

- .github/workflows/build.yaml
Being able to run the examples directly can be helpful for C++ developers looking to gain some familiarity with the performance and functionality of libcudf.
> Upload examples conda package

- java/ci/build-in-docker.sh
fix #18851,  as a follow-up of https://github.com/rapidsai/cudf/pull/18682. 
Verified with internal pipeline.
> Add CUDF_INSTALL_DIR for JAVA build script

- docs/cudf/source/conf.py
- python/cudf/cudf/api/extensions/accessor.py
- python/cudf/cudf/core/_internals/timezones.py
- python/cudf/cudf/core/buffer/exposure_tracked_buffer.py
- python/cudf/cudf/core/dataframe.py
- python/cudf/cudf/core/groupby/groupby.py
- python/cudf/cudf/core/multiindex.py
- python/cudf/cudf/core/series.py
Towards https://github.com/rapidsai/cudf/issues/10820
> Remove top level cudf imports in core

- python/cudf/cudf/core/indexing_utils.py
- python/cudf/cudf/tests/test_indexing.py
- python/custreamz/custreamz/tests/test_dataframes.py
Replaces https://github.com/rapidsai/cudf/pull/18894
> Branch 25.08 merge branch 25.06

- python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py
> parameterized ucx / ucxx

- python/custreamz/custreamz/tests/test_dataframes.py
This attempts to fix the flaky custreamz test that failed at https://github.com/rapidsai/cudf/actions/runs/15216870051/job/42805595449?pr=18942#step:9:1828
The previous fix possibly failed because the fixture to disable gc diagnosis ran when the test module was imported, but when the `client` fixture creates the Dask cluster, it reenabled it
https://github.com/dask/distributed/blob/801d0ed73649e654e7111d0208d0f6fcacf47acb/distributed/worker.py#L85 https://github.com/dask/distributed/blob/801d0ed73649e654e7111d0208d0f6fcacf47acb/distributed/scheduler.py#L4258
> Fix flaky custreamz test

- CONTRIBUTING.md
Adds pylibcudf to the build command in the contributing guide.
> Update the contributing guide to include pylibcudf in the build command

- python/cudf_polars/cudf_polars/experimental/benchmarks/pdsh.py
Help us check that we're match polars CPU.
> Add validate arg to polars pdsh benchmarks

- python/cudf_polars/tests/containers/test_column.py
In https://github.com/rapidsai/cudf/pull/18953/files#r2167631601, we found an issue with (de)serialization of cudf_polars data types with a multi-GPU setup. Polars lets you use either datatype classes or instances in most places. These are similar in most ways (hash the same, compare equal) but our deserialization implementation relies on isinstance checks which are not the same.
This could cause issues if we tried to deserialize a type like `'i8'` that wasn't already in our cache. This simulates that situation on a single worker by clearing the cache before deserialzation.
This was fixed in https://github.com/rapidsai/cudf/pull/19193, but I've added a regression test here.
> Add test for deserializing cudf_polars class instances

- python/cudf/cudf/core/dataframe.py
> Correct docstring for `DataFrame.apply` to match code

- cpp/include/cudf/detail/null_mask.cuh
Fixes a case in `segmented_offset_bitmask_binop` where a bit shift may exceed the size of the underlying type (`bitmask_type`). This is considered undefined-behavior in C++.
> Fix bit shift overflow in segmented_offset_bitmask_binop utility

- python/cudf_polars/cudf_polars/experimental/benchmarks/pdsds.py
- python/cudf_polars/cudf_polars/experimental/benchmarks/pdsds_queries/q1.py
- python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py
In https://github.com/rapidsai/cudf/issues/19200, there are several queries that fail at translation time. Because we pass `raise_on_fail=True` this causes  cudf_polars to raise an exception which halts progress when running all queries. This PR catches that exception and prints a "failed validation" message. It also supports range syntax making it easier to run a subset of the queries.
> Support range syntax and improve validation message when running PDS-H/PDS-DS

- conda/recipes/cudf-polars/recipe.yaml
This adds a dependency missed in #19410.
> Add conda dependency on nvidia-ml-py.

- cpp/src/join/mixed_join_kernels_semi.cu
This PR simplifies the mixed semi-join kernel by removing CG-related logic, as the underlying code path is only ever used with a CG size of 1.
> Get rid of CG logic in the mixed semi-join kernel

- python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py
This updates the software versions we record in the pdsh benchmarks to include the commit hash for cudf-polars and rapidsmpf. 
Note that this changes the serialized representation. Instead of
```json
"software": {
"cudf_polars": "{version}"
}
```
it will now be:
```json
"software": {
"cudf_polars": {
"version": "{version}",
"commit": "{commit}"
}
}
```
> Capture commit hashes in pdsh benchmarks

- python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py
This PR updates the cudf-polars benchmark suite to catch `pynvml.NVMLError_NotSupported`, which is raised on systems without traditional dedicated GPU memory.
This should have been included in [#19444](https://github.com/rapidsai/cudf/pull/19444), which closed [#19427](https://github.com/rapidsai/cudf/issues/19427). It was an oversight by me due to testing primarily on systems with dedicated device memory.
> Avoid querying device memory on systems without it in cudf-polars benchmarks

- cpp/include/cudf/partitioning.hpp
- python/pylibcudf/pylibcudf/binaryop.pxd
- python/pylibcudf/pylibcudf/binaryop.pyi
- python/pylibcudf/pylibcudf/binaryop.pyx
- python/pylibcudf/pylibcudf/libcudf/binaryop.pxd
- python/pylibcudf/pylibcudf/libcudf/partitioning.pxd
- python/pylibcudf/pylibcudf/libcudf/quantiles.pxd
- python/pylibcudf/pylibcudf/libcudf/reduce.pxd
- python/pylibcudf/pylibcudf/libcudf/search.pxd
- python/pylibcudf/pylibcudf/partitioning.pxd
- python/pylibcudf/pylibcudf/partitioning.pyi
- python/pylibcudf/pylibcudf/partitioning.pyx
- python/pylibcudf/pylibcudf/quantiles.pxd
- python/pylibcudf/pylibcudf/quantiles.pyi
- python/pylibcudf/pylibcudf/quantiles.pyx
- python/pylibcudf/pylibcudf/reduce.pxd
- python/pylibcudf/pylibcudf/reduce.pyi
- python/pylibcudf/pylibcudf/reduce.pyx
- python/pylibcudf/pylibcudf/search.pxd
- python/pylibcudf/pylibcudf/search.pyi
- python/pylibcudf/pylibcudf/search.pyx
Contributes to https://github.com/rapidsai/cudf/issues/15163
> Add streams to all modules with three or fewer functions

- python/cudf/cudf/core/column/datetime.py
- python/cudf/cudf/tests/test_datetime.py
closes https://github.com/rapidsai/cudf/issues/19568
> Fix strftime with non-exact %a, %A, %b, %B

- python/pylibcudf/pylibcudf/libcudf/stream_compaction.pxd
- python/pylibcudf/pylibcudf/stream_compaction.pxd
- python/pylibcudf/pylibcudf/stream_compaction.pyi
- python/pylibcudf/pylibcudf/stream_compaction.pyx
> Add streams to stream_compaction

- python/pylibcudf/pylibcudf/scalar.pyx
I decided there wasn't a great place in the developer docs for this information, but the existing comment didn't have much information so I expanded it substantially.
Resolves #14249
> Improve documentation around why we need no_gc_clear on pylibcudf Scalars

- python/pylibcudf/pylibcudf/join.pxd
- python/pylibcudf/pylibcudf/join.pyi
- python/pylibcudf/pylibcudf/join.pyx
- python/pylibcudf/pylibcudf/libcudf/join.pxd
> Add streams to pylibcudf join APIs

- python/cudf_polars/cudf_polars/dsl/translate.py
- python/cudf_polars/cudf_polars/dsl/utils/aggregations.py
- python/cudf_polars/cudf_polars/dsl/utils/groupby.py
- python/cudf_polars/cudf_polars/dsl/utils/rolling.py
- python/cudf_polars/tests/expressions/test_rolling.py
- python/cudf_polars/tests/test_groupby.py
- python/cudf_polars/tests/test_rolling.py
Closes https://github.com/rapidsai/cudf/issues/19679. Also unblocks #19242
> Match polars semantics for rolling-sum with all-null windows (non-empty)

- docs/cudf/source/developer_guide/testing.md
Updates the documented, test organization conventions being worked towards in https://github.com/rapidsai/cudf/issues/9999 and https://github.com/rapidsai/cudf/issues/15723
> Update cuDF classic testing documention regarding testing organization

- python/cudf/cudf/tests/private_objects/test_nrt_stats.py
Skips a few flaky tests while we investigate
xref https://github.com/rapidsai/cudf/issues/19880
> Skip flaky stats tests pending follow up

- python/pylibcudf/tests/io/test_json.py
Disabling this test until we can resolve https://github.com/rapidsai/cudf/issues/19900.
> Disable test on non-default stream

- python/pylibcudf/pylibcudf/strings/reverse.pyi
I noticed this omission while I was going through stream and memory resource changes.
> Add missing type stub

- python/cudf/cudf/pandas/_wrappers/pandas.py
closes https://github.com/rapidsai/cudf/issues/19818
> Avoid undefined numpy protocols on cudf.pandas proxy objects

- python/pylibcudf/pylibcudf/interop.pxd
- python/pylibcudf/pylibcudf/interop.pyi
- python/pylibcudf/pylibcudf/interop.pyx
- python/pylibcudf/pylibcudf/join.pyx
- python/pylibcudf/pylibcudf/labeling.pyx
- python/pylibcudf/pylibcudf/libcudf/interop.pxd
- python/pylibcudf/pylibcudf/libcudf/join.pxd
- python/pylibcudf/pylibcudf/libcudf/labeling.pxd
- python/pylibcudf/pylibcudf/libcudf/merge.pxd
- python/pylibcudf/pylibcudf/libcudf/round.pxd
- python/pylibcudf/pylibcudf/libcudf/transpose.pxd
- python/pylibcudf/pylibcudf/merge.pxd
- python/pylibcudf/pylibcudf/merge.pyi
- python/pylibcudf/pylibcudf/merge.pyx
- python/pylibcudf/pylibcudf/round.pyx
- python/pylibcudf/pylibcudf/transpose.pxd
- python/pylibcudf/pylibcudf/transpose.pyi
- python/pylibcudf/pylibcudf/transpose.pyx
I also noticed that in #20001 the mrs were not actually being passed to the underlying C++ API calls. I've fixed that in this PR and will make sure that gets fixed accordingly in subsequent PRs.
Contributes to #15170
> Add memory resource parameters to interop, merge, and transpose

- ci/cudf_pandas_scripts/pandas-tests/run.sh
We really only need to see why tests fail when they fail.
> Reduce verbosity of running the pandas test suite

- python/pylibcudf/pylibcudf/column.pyx
- python/pylibcudf/pylibcudf/contiguous_split.pxd
- python/pylibcudf/pylibcudf/contiguous_split.pyx
- python/pylibcudf/pylibcudf/io/timezone.pyx
- python/pylibcudf/pylibcudf/libcudf/column/column.pxd
- python/pylibcudf/pylibcudf/libcudf/io/timezone.pxd
- python/pylibcudf/pylibcudf/libcudf/null_mask.pxd
- python/pylibcudf/pylibcudf/libcudf/table/table.pxd
- python/pylibcudf/pylibcudf/libcudf/transform.pxd
- python/pylibcudf/pylibcudf/null_mask.pxd
- python/pylibcudf/pylibcudf/null_mask.pyx
- python/pylibcudf/pylibcudf/transform.pxd
- python/pylibcudf/pylibcudf/transform.pyx
I think this covers all the remaining places where we need memory resource arguments.
Closes #15170
> Add remaining memory resources
