python/cudf/cudf/core/_base_index.py
python/cudf/cudf/tests/test_joining.py

Fix join of MultiIndex to Index with one column and overlapping name.

---

java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This PR adds a few more edge cases as a sanity test on the request of @sameerz

[Java] Added a few more tests for Decimal to String cast

---

java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

This adds Java binding for `cudf::drop_duplicates`.
Note that when choosing which duplicate element to keep, only `KEEP_FIRST` or `KEEP_LAST` option can be selected. In other words, this does not support `KEEP_NONE` to remove all duplicate elements.
Closes #9115.

Add JNI for `cudf::drop_duplicates`

---

cpp/src/dictionary/detail/concatenate.cu
cpp/src/io/orc/timezone.cpp
cpp/src/io/parquet/page_enc.cu
cpp/src/io/parquet/writer_impl.cu
cpp/src/strings/filter_chars.cu
cpp/src/strings/replace/backref_re.cu
cpp/src/strings/translate.cu
cpp/src/transform/row_bit_count.cu

See: https://github.com/rapidsai/cudf/pull/9588#discussion_r751889583
In a recent PR review, @jrhemstad suggested switching to vector factories for one-way host-device data copying (that is, cases where using a `hostdevice_vector` isn't the right choice).
This PR applies that suggestion more broadly across the code base, replacing a number of simple cases where a (device) vector was being constructed followed by a call to `CUDA_TRY(cudaMemcpyAsync(...))` with the corresponding factory functions. This makes the code a little more concise and encourages broader use of these factory functions in the future.

Use vector factories for host-device copies.

---

cpp/docs/DOCUMENTATION.md

Updates doxygen build instructions in the libcudf documentation guide.

Fix build instructions for libcudf doxygen

---

java/src/main/java/ai/rapids/cudf/Table.java
java/src/test/java/ai/rapids/cudf/TableTest.java

Relates to #9851.  This removes deprecated methods from the Java Table class, including APIs that would allow writing ORC files without specifying metadata via writer options needed for some columns (e.g.: precision for decimal columns).  This also fixes a test where decimal precisions where not specified despite trying to write decimal columns to ORC.  Javadoc errors introduced by #9096 were also corrected.

Remove deprecated methods from Java Table class

---

python/dask_cudf/dask_cudf/sorting.py

It is possible to pass a list of `ascending` booleans to dask-cudf's `sort_values`, which is not yet supported by `quantile_divisions` (which computes divisions for all sort-by columns sorted in ascending order), and can cause undefined behavior.
This small PR adds a check that `ascending` is a boolean before computing quantile divisions; note that this check happens _after_ the single-partition case is handled, as cuDF can handle lists of `ascending` booleans.

Enforce boolean `ascending` for dask-cudf `sort_values`

---

cpp/src/io/utilities/file_io_utilities.cpp

Workaround for a known cuFile issue that can lead to segfault if cuFile library is dynamically unloaded.
Using `RTLD_NODELETE` when calling `dlopen` so that the library is not unloaded in `dlclose`.
Also adds a check for the result of dlopen, to help triage cuFile use issues.

Load libcufile.so with RTLD_NODELETE flag

---

cpp/benchmarks/CMakeLists.txt

closes https://github.com/rapidsai/cudf/issues/2784
Adds run_benchmarks target for running benchmarks with json output
You can run all benchmarks with  `make run_benchmarks` or `ninja run_benchmarks`
json will be stored in `benchmarks/results/*.json`
The benchmark stdout will still print.

add run_benchmarks target for running benchmarks with json output

---

java/src/main/native/CMakeLists.txt

When the Java bindings use libcudf as a static library dependency, the resulting link is missing zlib as a dynamic link dependency.  This can result in runtime errors such as `undefined symbol: inflateInit2_` when trying to load a file using gzip compression.  This adds zlib to the cudfjni link when using libcudf.a as the cudf dependency.

Add zlib to cudfjni link when using static libcudf library dependency

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/groupby/group_no_requests_benchmark.cu
cpp/src/groupby/hash/groupby.cu

The following fixes what looks like an unintended fallback to sort aggregate introduced in https://github.com/rapidsai/cudf/pull/9545 for a grouping only (no aggregation request) case.
In the PR, the `std::all_of` function is used to determine whether the aggregation requests would be for struct types. That said, when there are no aggregation requests the `std::all_of` function will return true, causing a fallback to the sort aggregation (relevant code: https://github.com/rapidsai/cudf/pull/9545/files#diff-e409f72ddc11ad10fa0099e21b409b92f12bfac8ba1817266696c34a620aa081R645-R650).
I added a benchmark `group_no_requests_benchmark.cu` by mostly copying `group_sum_benchmark.cu` but I changed one critical part. I am re-creating the `groupby` object for each `state`:
```
for (auto _ : state) { …
```

Fix fallback to sort aggregation for grouping only hash aggregate

---

python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_series.py

Closes #9825 
This PR fixes the bug that when there are ties with most frequent categories in categorical series, the order returned is undefined. We break the tie by sorting the category and take its top.
Also included in this PR: refactors `describe` to use a dictionary items to describe for better readability. And enables https://github.com/rapidsai/cudf/blob/024003ca444f9d1a8374a1133337419f22cc880a/python/cudf/cudf/tests/test_series.py#L405

Break tie for `top` categorical columns in `Series.describe`

---

cpp/src/io/orc/writer_impl.cu

Follow up of https://github.com/rapidsai/cudf/pull/9808
Skips some kernels when input columns are empty to avoid OOB memory access.

Fix a memcheck error in ORC writer

---

java/src/main/native/src/TableJni.cpp

This fixes the java build after #9810 went in.
There is a lot of copy/paste in this first draft, because I just wanted to get something to work. Not sure if it is worth going back to make it common everywhere.

Fix the java build after parquet partitioning support

---

java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

This PR adds Java binding for both `cudf::scatter` APIs:
```
std::unique_ptr<table> scatter(
table_view const& source,
column_view const& scatter_map,
table_view const& target,
...)
```
and
```
std::unique_ptr<table> scatter(
std::vector<std::reference_wrapper<const scalar>> const& source,
column_view const& indices,
table_view const& target,
...)
```
Closes #9892.

Implement JNI for `cudf::scatter` APIs

---

python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/tests/test_datetime.py

Pandas uses the [following regex](https://github.com/pandas-dev/pandas/blob/8fefaa5a9a7c3f3a1c35c36c1140117dab73c9c7/pandas/_libs/tslibs/offsets.pyx#L3506-L3508) to convert freqeuncy strings into offset, which is exposed in public api `pd.tseries.frequencies.to_offset`. Currently cudf depends on a [custom  regex](https://github.com/rapidsai/cudf/blob/fdd9bb00dc0ba5ac373feaa079b782029130dae3/python/cudf/cudf/core/tools/datetimes.py#L819-L821) to perform the conversion. We probably shouldn't reinvent the wheels here as it might make it harder to track changes in pandas.

Use pandas `to_offset` to parse frequency string in `date_range`

---

cpp/include/cudf/detail/merge.cuh
cpp/include/cudf/strings/detail/merge.cuh
cpp/src/dictionary/detail/merge.cu
cpp/src/merge/merge.cu
cpp/tests/copying/sample_tests.cpp
cpp/tests/interop/from_arrow_test.cpp
cpp/tests/interop/to_arrow_test.cpp
cpp/tests/io/orc_test.cpp
cpp/tests/transform/mask_to_bools_test.cpp

While watching @bdice and @isVoid's Better Code talk, I noticed a pair of `thrust::get`s that could be replaced by structured bindings. I did a quick search and found all the places the clean up could be done. That is what this PR does.

Replace `thrust/std::get` with structure bindings

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/groupby/group_no_requests_benchmark.cu
cpp/src/groupby/hash/groupby.cu

This is a cherry-pick of https://github.com/rapidsai/cudf/commit/335862bf5bc8433d5d0896adf8210a13c5a21ab3 for the 21.12 branch.
I'll run a few tests with this, so posting as is (a clean cherry-pick) just to get the ball rolling.

Fix fallback to sort aggregation for grouping only hash aggregate (21.12)

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/CMakeLists.txt
java/src/main/native/src/ColumnViewJni.cpp
java/src/main/native/src/ColumnViewJni.cu
java/src/main/native/src/ColumnViewJni.hpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This commit introduces a JNI function `ColumnVector#copyWithValidity(ColumnView boolean_column)` to use a `BOOL8` column as the validity buffer of a column.
As per the convention in the JNI layer, this method does not modify the current object. A new `ColumnVector` is returned, containing the contents of the current object. The validity of the returned `ColumnVector` is set to the `DeviceBuffer` representation of the logical contents of the supplied `BOOL8` column.
This method will be useful to set a column's validity based on a column resulting from a boolean operation.

JNI: Function to copy and set validity from bool column.

---

cpp/src/join/hash_join.cu
cpp/src/join/hash_join.cuh
cpp/src/join/join_common_utils.cuh
cpp/src/join/join_common_utils.hpp
cpp/src/join/semi_join.cu

Follow on PR for this comment: https://github.com/rapidsai/cudf/pull/9623#discussion_r758635105
The join hasher and equality-comparator were previously hardcoded with `has_nulls=true` (and migrated to `nullate::YES`) to help minimize code size. The new `nullate::DYNAMIC` allows for runtime checking of nulls so this can now be used here instead.

Use dynamic nullate for join hasher and equality comparator

---

docs/cudf/source/api_docs/io.rst
python/cudf/cudf/utils/ioutils.py

Fixes: #9771 
This PR fixes the broken **see also** links in sphinx docstrings.

[REVIEW] Fix see also links for IO APIs

---

ci/gpu/build.sh
ci/gpu/java.sh

I see CI timeouts occurring at the step where local conda artifacts for libcudf and libcudf_kafka are installed. This PR uses `gpuci_mamba_retry` instead of `conda` to install those local artifacts (this change was also recently made in https://github.com/rapidsai/cugraph/pull/1928).
Example timeouts:
- https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-gpu-test/CUDA=11.5,GPU_LABEL=driver-495,LINUX_VER=ubuntu20.04,PYTHON=3.8/5764/console
- https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-gpu-test/CUDA=11.5,GPU_LABEL=driver-495,LINUX_VER=ubuntu20.04,PYTHON=3.8/5773/console

Use gpuci_mamba_retry to install local artifacts.

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java
java/src/main/native/src/ColumnVectorJni.cpp

cudf Java build is broken by https://github.com/rapidsai/cudf/pull/9942. So update the `hash` JNI accordingly.

Fix cudf java build error.

---

cpp/cmake/thirdparty/get_thrust.cmake

Compile times between 1.12 and 1.15 are comparable.
libcudf library size with 1.15 is < 1MB smaller compared to 1.12

Upgrade thrust version to 1.15

---

cpp/src/io/parquet/reader_impl.cu
cpp/src/io/parquet/reader_impl.hpp
cpp/src/io/parquet/writer_impl.cu
cpp/src/io/parquet/writer_impl.hpp

Rename aggregate_metadata in writer to fix name collision

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java
java/src/main/java/ai/rapids/cudf/HostColumnVectorCore.java

#9485 regressed the fix in #9332.  This restores the fix.  It also eliminates the problematic `ColumnVector.closeBuffers` which, despite the plurality in the name, only closed one buffer and had dubious utility in converting throwables into runtime exceptions.

Fix regression HostColumnVectorCore requiring native libs

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

Fixes https://github.com/rapidsai/cudf/issues/9969
Due to a bug in `GroupBy.__getitem__`, selecting a column of a `GroupBy` and then doing a shift, diff, or fill operation would result in the operation being performed on the wrong values. This PR fixes `GroupBy.__getitem__` so we now have the right behaviour.

Fix groupby shift/diff/fill after selecting from a  `GroupBy`

---

cpp/src/io/avro/avro_gpu.h
cpp/src/io/avro/reader_impl.cu
cpp/src/io/comp/gpuinflate.h
cpp/src/io/csv/reader_impl.cu
cpp/src/io/csv/writer_impl.cu
cpp/src/io/orc/timezone.cuh
cpp/src/io/orc/writer_impl.hpp
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/reader_impl.cu
cpp/src/io/parquet/writer_impl.hpp
cpp/src/io/utilities/column_buffer.hpp
cpp/src/io/utilities/hostdevice_vector.hpp
cpp/tests/io/comp/decomp_test.cpp
cpp/tests/utilities_tests/span_tests.cu

Removes defaults for internal stream parameters.
Fixes cases where default stream was used instead of propagating the stream.

Clean up CUDA stream use in cuIO

---

cpp/benchmarks/io/parquet/parquet_reader_benchmark.cpp
cpp/src/io/parquet/writer_impl.cu
cpp/tests/io/parquet_test.cpp

Use default value for decimal precision in parquet writer when not specified

---

conda/recipes/libcudf/meta.yaml

Style check was failing in the last couple of PRs but not loudly enough to break CI.

Add missing list filling header in meta.yaml

---

cpp/src/reductions/struct_minmax_util.cuh
cpp/tests/groupby/max_tests.cpp
cpp/tests/groupby/min_tests.cpp

When comparing structs, we need to flatten its view into a `table_view` and compare the table's rows. Nulls check for the comparison needs to be done by checking nulls in the input structs column at all levels.
This PR fixes a bug that checks for nulls only at the top level. Unit tests designed specifically to detect this bug have also been added.

Fix null check when comparing rows of structs in `min` and `max` reduction/groupby operations

---

conda/recipes/cudf_kafka/meta.yaml
conda/recipes/custreamz/meta.yaml

This PR updates the `conda` recipes for `custreamz` and `cudf_kafka`. The environment variable should be `PYTHON`, not `python` (case sensitive).

Fix `conda` recipes for `custreamz` & `cudf_kafka`

---

cpp/include/cudf/utilities/traits.hpp

The current implementation of `cudf::is_numeric` is equivalent to the implementation of `cuda::std::is_arithmetic`. This PR simplifies the implementation in cuDF and aligns it with libcudacxx.
Notes:
- `bool` returns true from both `(cuda::)std::is_integral` and `(cuda::)std::is_arithmetic`, so `bool` is considered a "numeric" type. This behavior is unchanged.
- We must use `cuda::std::is_arithmetic` rather than `std::is_arithmetic` to [support 128-bit integer types](https://github.com/NVIDIA/libcudacxx/blob/05e3bae155a17759bc7fd4d1904b6b5da4c9be51/include/cuda/std/detail/libcxx/include/type_traits#L754-L757) (as we do with `cuda::std::is_integral` in the current implementation)
See also: https://en.cppreference.com/w/cpp/types/is_arithmetic

Use `cuda::std::is_arithmetic` in `cudf::is_numeric` trait.

---

java/src/main/native/src/row_conversion.cu

CUDA_DEVICE_CALLABLE was deprecated immediately after merging 8444 which included some new calls that were missed.

Remove `CUDA_DEVICE_CALLABLE` macro usage

---

ci/benchmark/build.sh
ci/cpu/upload.sh
ci/gpu/build.sh

This is a tiny PR that wraps shell script variables in quotes. This fixes an issue I saw in the upload script when `${BUILD_MODE}` was not set during local testing of the CI environment.

Wrap CI script shell variables in quotes to fix local testing.

---

cpp/doxygen/regex.md

Fixes a documentation error found while diagnosing a hex regex pattern question.
The hex escape sequence only specifies a single character (not a single byte). So this means it can only be used to match ASCII characters (code-points 0-127) and not all UTF-8 characters. This is the same as for octal escape sequences. Also, the example provided for hex in the documentation has been corrected to use a valid ASCII character.

Fix regex doc describing hexadecimal escape characters

---

cpp/CMakeLists.txt

cudftestutil no longer propagates compiler flags to external users

---

cpp/include/cudf_test/type_lists.hpp
cpp/tests/transpose/transpose_test.cpp

This is a follow on to PR #9937.
Adds to the gtests in  `transpose_test.cpp` to include strings as supported by `cudf::transpose`. No function has changed -- only additional tests have been added.
The utility functions in `transpose_test.cpp` were enhanced to include string types by accepting a column-wrapper type template parameter as required.

Add strings tests to transpose_test.cpp

---

java/src/main/native/src/RmmJni.cpp
java/src/test/java/ai/rapids/cudf/RmmTest.java

Update JNI to use new arena mr constructor

---

java/src/main/native/src/ColumnVectorJni.cpp
java/src/main/native/src/ColumnViewJni.cpp

This commit fixes a couple of minor, host-side memory leaks
in the JNI native code. The objects in question did not need
to go on the heap. They have, in this commit, been switched to 
stack objects.

Fix memory leaks in JNI native code.

---

build.sh

Previously the script would do a comparison check like "$V"=="ON" which isn't a comparison in bash but a joining of strings ( "OFF==ON"). To do a comparison of two strings you need to have white space around `==`.

build.sh respects the `--build_metrics` and `--incl_cache_stats` flags

---

cpp/src/reductions/struct_minmax_util.cuh
cpp/tests/groupby/max_tests.cpp
cpp/tests/groupby/min_tests.cpp

This is another fix for https://github.com/NVIDIA/spark-rapids/pull/4434, when the null order is wrongly handled if the input structs column does not have nulls at the top level but only has null at the children levels.

Fix null check when comparing structs in `arg_min` operation of reduction/groupby

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/meta.yaml

Relaxes version constraints to allow CuPy 10.
xref: https://github.com/rapidsai/integration/pull/413

Allow CuPy 10

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_repr.py

Fixes: #8963 
This PR fixes a trivial issue in `concat` where the assumption was that `_with_type_metadata` is an in-place operation, but it isn't.

[REVIEW] Fix repr and concat of `StructColumn`

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #9928 
This PR fixes 2d array assignment in `setitem`

[REVIEW] Fix dataframe setitem with `ndarray` types

---

cpp/src/interop/from_arrow.cu
cpp/src/interop/to_arrow.cu
cpp/tests/interop/arrow_utils.hpp
cpp/tests/interop/from_arrow_test.cpp
cpp/tests/interop/to_arrow_test.cpp

Resolves C++ side of https://github.com/rapidsai/cudf/issues/9980.
The reason this PR is breaking is because Arrow only has a notion of `decimal128` (see `arrow::Type::DECIMAL`). We can still support both `decimal64` **and** `decimal128` for `to_arrow` but for `from_arrow` it only makes sense to support one of them, and `decimal128` (now that we have it) is the logical choice. Therfore, the switching of the return type of a column coming `from_arrow` from `decimal64` to `decimal128` is a breaking change.
Requires:
* https://github.com/rapidsai/cudf/issues/7314
* https://github.com/rapidsai/cudf/pull/9533

`decimal128` Support for `to/from_arrow`

---

cpp/src/io/orc/aggregate_orc_metadata.cpp

Add check for negative stripe index in ORC reader

---

java/src/test/java/ai/rapids/cudf/TableTest.java

After #9986 reading Arrow in libcudf now returns DECIMAL128 instead of DECIMAL64.  This updates the Java tests to expect DECIMAL128 instead of DECIMAL64 by upcasting the decimal columns in the original table being round-tripped through Arrow before comparing the result.

Update Java tests to expect DECIMAL128 from Arrow

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/meta.yaml
python/cudf/cudf/utils/gpu_utils.py

This PR replaces custom CUDA bindings that are provided by RMM, with official CUDA Python bindings. This PR should be merged after the RMM PR  https://github.com/rapidsai/rmm/pull/930

Replace custom CUDA bindings previously provided by RMM with official CUDA Python bindings

---

conda/recipes/cudf_kafka/meta.yaml
conda/recipes/custreamz/meta.yaml

Adding build string constraints with Python version is not required for `python-confluent-kafka` dependency as the python version is fixed during conda build with `--python` flag

Simplify custreamz and cudf_kafka recipes files

---

conda/recipes/cudf_kafka/meta.yaml
conda/recipes/custreamz/meta.yaml

Forward-merge triggered by push to `branch-22.02` that creates a PR to keep `branch-22.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.02 to branch-22.04 [skip gpuci]

---

java/src/main/java/ai/rapids/cudf/HostColumnVector.java

I know that this is past the freeze date. This is a fix for a P1 bug that we just found when trying to build Scalar values of Lists and Structs that contain Decimal128 values. We might be able to work around it some other way, but it would take a lot of changes to the existing Spark plugin code to do that so I wanted to try this first.

Fix for appending decimal128 under list and struct types

---

cpp/docs/BENCHMARKING.md

This PR relates to #7960 and indicates that new benchmarks should be written using [NVBench](https://github.com/NVIDIA/nvbench). (This PR does not resolve that issue because it does not transition any existing benchmarks to nvbench, it is only an update in the developer guide.)

Update benchmarking guide to use NVBench.

---

python/cudf/cudf/tests/test_dataframe.py

The test `test_dataframe.py::test_memory_usage_multi` is currently flaky. In theory it can fail for any value of the `rows` parameter, but in practice we only observe failures for the smaller value of 10. The reason for this is that the data for the `MultiIndex` is being constructed by randomly sampling from an array of size 3, and for a sufficiently small sample (e.g. 10) the probability that selection will not actually include all three values (e.g. a sample of `[0, 1, 1, 1, 0, 1, 1, 0, 0, 1]`) is not vanishingly small and occurs with observable frequency. The resulting `MultiIndex` will encode the levels for that column as a column with only two values, and as a result the column will occupy 8 fewer bytes (one 64 bit integer or float) less of space than expected. This PR changes that …

Fix flaky memory usage test by guaranteeing array size.

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/numerical.py

This PR avoid make `nan_as_null` a no-op if `nan_count` is 0, i.e., there are no nulls present.

[REVIEW] Avoid `nan_as_null` op if `nan_count` is 0

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_dropna.py

Currently when `drop_nan == False`, variable `data_columns` was not created and referenced below. This PR fixes that.

Correctly construct `data_column` variable when `drop_nan == False` in `_drop_na_rows`

---

python/cudf/cudf/core/udf/pipeline.py
python/cudf/cudf/tests/test_udf_masked_ops.py

This PR fixes an issue in caching `apply` UDFs where we were incorrectly getting a cache miss on the same function/dataframe. This was happening because `dict_values` objects don't compare as equal.

Fix UDF Caching

---

ci/checks/style.sh
ci/release/update-version.sh

Updates cmake-format script to branch 22.04. (@robertmaynard Is this supposed to be updated whenever we bump the release version?)

Update cmake-format script for branch 22.04.

---

python/cudf/cudf/errors.py
python/cudf/cudf/utils/gpu_utils.py

This PR resolves #10076. It improves `gpu_utils.py` by removing code for handling CUDA < 11.0, which we no longer support.
This is marked as "breaking" because of minor Python API changes. I changed the name of an error class from `UnSupportedCUDAError` to `UnsupportedCUDAError` and removed an unused error class named `UnSupportedGPUError`. It appears the `UnSupportedGPUError` class was introduced in #4692 but has never been used in the code.

Update gpu_utils.py to reflect current CUDA support.

---

cpp/include/cudf/io/orc.hpp
cpp/src/io/orc/reader_impl.cu
cpp/src/io/orc/reader_impl.hpp
python/cudf/cudf/_lib/cpp/io/orc.pxd

The option was put in place to prevent Python users of the read_orc API to read decimal columns as 128bit, since this type was not supported in Python at the time.
Now that decimal128 in supported in Python, this option can be removed.
The change in technically breaking, but it is very unlikely that anyone is using the API.

Remove the option to completely disable decimal128 columns in the ORC reader

---

python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #10117 
This PR adds a duplicate column validation check in `ColumnAccessor.rename_levels`

[REVIEW] Raise duplicate column error in `DataFrame.rename`

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Currently, Java binding for `strings::split` calls the API with the default max split value. This PR adds a parameter for it, allowing to specify max split from Java.
This is non-breaking because the Java code implicitly uses the default max split value.

Add `maxSplit` parameter to Java binding for `strings:split`

---

cpp/benchmarks/fixture/benchmark_fixture.hpp

benchmark fixture - fix sharing static object pointer, replace with static shared pointer.

benchmark fixture - static object pointer fix

---

cpp/include/cudf/io/orc.hpp

Deprecate `decimal_cols_as_float` in ORC reader (C++ layer)

---

cpp/docs/DEVELOPER_GUIDE.md

Updates the developer guide to address #9854. With this change, any new or refactored detail APIs should have no default stream parameter. We may resolve that issue or perhaps leave it open until a majority of code has no default stream.

Update developer guide to recommend no default stream parameter.

---

cpp/benchmarks/io/csv/csv_reader.cpp
cpp/benchmarks/io/csv/csv_writer.cpp
cpp/benchmarks/io/cuio_common.cpp
cpp/benchmarks/io/cuio_common.hpp
cpp/benchmarks/io/orc/orc_reader.cpp
cpp/benchmarks/io/orc/orc_writer.cpp
cpp/benchmarks/io/parquet/parquet_reader.cpp
cpp/benchmarks/io/parquet/parquet_writer.cpp
cpp/benchmarks/io/parquet/parquet_writer_chunks.cpp

Most cuIO benchmarks used dataframes of fixed size as input. After writing to a file in the given format, its size can vary greatly depending on the encoding and compression.
This PR adds a counter to output the file size, as it can be often corelated with the performance of readers/writers.

[FEA] Add file size counter to cuIO benchmarks

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/tests/test_list.py

Fixes: #10122 
This PR fixes an issue where the list columns children[1]'s dtype wasn't being preserved correctly.

[REVIEW] Preserve the correct `ListDtype` while creating an identical empty column

---

cpp/src/groupby/groupby.cu

This PR refactors the `groupby::get_groups` method. It replaces several lines of construct-and-copy with a vector factory function and makes stream usage more clear.

Refactor groupby::get_groups.

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java
java/src/main/java/ai/rapids/cudf/ColumnView.java

This fixes a memory leak that we were seeing when running some tests.  I will be doing some more testing to be sure that all of the memory leaks are gone, but it should be a good step forward.

Fix JNI leak of a cudf::column_view native class.

---

docs/cudf/source/api_docs/index_objects.rst
docs/cudf/source/api_docs/series.rst
docs/cudf/source/user_guide/10min.ipynb
python/cudf/cudf/core/column/column.py

This PR cleans up some remaining places where `to_array` needs to be removed. Actual cleanup was done in: https://github.com/rapidsai/cudf/pull/10124/

[REVIEW] Remove cleaned up methods from docs

---

python/dask_cudf/dask_cudf/groupby.py

Dask deprecated `index` property in GroupBy class: https://github.com/dask/dask/pull/8441, this PR changes the usages to `.by`

[REVIEW] Replace `dask` groupby `.index` usages with `.by`

---

cpp/benchmarks/io/orc/orc_reader.cpp
cpp/benchmarks/io/parquet/parquet_reader.cpp

Closes: #9961
Skipping the following:
- ORC reader: row selection through stripe selection
- ORC reader: lists column with row selection
- Parquet reader: row selection through row group selection
- Parquet reader: lists column with row selection

Skip ORC and Parquet readers' benchmark cases that are not currently supported

---

cpp/include/cudf/fixed_point/fixed_point.hpp

As pointed out by @bdice in https://github.com/rapidsai/cudf/pull/10179, the docs are backwards for some of the binary operations on `fixed_point`. This PR fixes them and removes the `<br>` HTML tag as well.

Fix `fixed_point` binary operation documentation

---

cpp/src/join/hash_join.cuh
cpp/src/join/mixed_join_semi.cu
cpp/src/join/semi_join.cu

This PR fixes the `cuCollections` pair issue via https://github.com/NVIDIA/cuCollections/pull/138 thus we don't have to pass rvalues to `cuco::make_pair`.

Fix cuco pair issue in hash join

---

python/cudf/cudf/tests/test_dataframe.py

This PR refactors some DataFrame tests, including [suggestions](https://github.com/rapidsai/cudf/pull/10141#discussion_r798106517) from @vyasr in #10141 that are not related to that PR's focus.

Refactor DataFrame tests.

---

python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py

Removes unnecessary nunique function in Series, as indicated by @vyasr here https://github.com/rapidsai/cudf/pull/10077#discussion_r796134577.
Seem to have made a mistake when correcting the style of my last commit and not have kept the original changes of that commit.

Remove unnecessary nunique function in Series.

---

cpp/src/binaryop/compiled/util.cpp

This PR fixes a compile error in `binaryop/compiled/util.cpp`, when a function with return type `std::optional` return `{}` instead of `std::nullopt`. As such, nvcc 11.5/g++-10.3 yell:
```
../src/binaryop/compiled/util.cpp: In function 'std::optional<cudf::data_type> cudf::binops::compiled::get_common_type(cudf::data_type, cudf::data_type, cudf::data_type)':
../src/binaryop/compiled/util.cpp:48:15: error: '<anonymous>' may be used uninitialized in this function [-Werror=maybe-uninitialized]
48 |       return {};
|               ^
```

Fix compile error in `binaryop/compiled/util.cpp`

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/utils/utils.py

This PR contributes to #9038, merging implementations of memory_usage and __iter__. It also removes an unnecessary override of take (saves about 25% of runtime for data <1M rows) and deprecates Series.merge, which doesn't exist in pandas.

Some consolidation of indexed frame methods

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java
java/src/main/native/src/ColumnVectorJni.cpp
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Previously, the Spark-rapids plugin only needs to call `lists::drop_list_duplicates` to create map which requires the input to be non-nullable. As such, the output of the JNI is just a lists column without bitmask. When operating on nullable input lists column, it produces incorrect results.
This PR fixes that.

Fix bitmask of the output for JNI of `lists::drop_list_duplicates`

---

docs/cudf/source/conf.py

This PR fixes an issue with the doc builds. `get_html_theme_path()` was removed in the commit below. After some local testing, it seems that the lines in this PR can be removed without any issues.
- https://github.com/pydata/pydata-sphinx-theme/commit/579d7ce695cb5c2611aa7b8ab76fbc3efc5fab26

Fix docs builds

---

java/src/main/java/ai/rapids/cudf/Aggregation128Utils.java
java/src/main/native/CMakeLists.txt
java/src/main/native/src/Aggregation128UtilsJni.cpp
java/src/main/native/src/aggregation128_utils.cu
java/src/main/native/src/aggregation128_utils.hpp
java/src/test/java/ai/rapids/cudf/Aggregation128UtilsTest.java

This adds a couple of custom kernels for Java to help accelerate sum aggregations on 128-bit types and check for overflows.  The first kernel extracts a 32-bit chunk from an 128-bit type which can be used to feed four 32-bit chunks into a sum aggregation.  The second kernel takes the resulting upscaled 64-bit integer results and reassembles the parts into a 128-bit type column along with a boolean column to indicate whether the value overflowed.
By splitting the 128-bit type into 32-bit chunks, a sum aggregation on DECIMAL128 which is a sort-based aggregation can be turned into a hash-based aggregation on 32-bit integer inputs for improved performance.  As a bonus, this approach can also check for overflow which is difficult to do when aggregating on DECIMAL128 sums directly.

Java utilities to aid in accelerating aggregations on 128-bit types

---

cpp/include/cudf/table/row_operators.cuh

There was one missed change from template param has_nulls to member Nullate _has_nulls. It worked because has_nulls resolved to pointer to the function `has_nulls(table_view)` which is always true and didn't break at runtime because the subsequent is_null has a built in nullmask check.

Fix a leftover _has_nulls change from Nullate

---

cpp/src/io/utilities/config_utils.cpp
cpp/src/io/utilities/config_utils.hpp
cpp/src/io/utilities/file_io_utilities.cpp
docs/cudf/source/basics/io-gds-integration.rst

Modified `getenv_or` to allow the default value of any type.
Adds environment variables:
- `LIBCUDF_CUFILE_THREAD_COUNT`: integer, number of threads in the pool used for I/O (default 16);
- `LIBCUDF_CUFILE_SLICE_SIZE`: integer, maximum size of cuFile reads/writes in bytes (default 4MB).

Add environment variables for I/O thread pool and slice sizes

---

python/cudf/cudf/_lib/utils.pyx
python/cudf/cudf/tests/test_parquet.py

Fixes: #10172 
`pa.pandas_compat.construct_metadata` constructs the correct metadata but is being overridden by special `list` & `struct` handling logic as `string`, rather than retaining it as `object`. This PR fixes the issue and modifies existing tests to validate the issue.

[REVIEW] Fix `decimal` metadata in parquet writer

---

cpp/benchmarks/CMakeLists.txt
cpp/libcudf_kafka/tests/CMakeLists.txt
cpp/tests/CMakeLists.txt

This PR adds a CMake `install` rule for test targets. This step is a prerequisite to being able to package tests in their own `conda` package, which will enable us to deprecate _Project Flash_.

Add CMake `install` rule for tests

---

ci/gpu/build.sh

This PR increases the number of cores allocated to `pytest-xdist` and also changes distribution algorithm for `cudf` to `loadscope`.
This PR:
```
custreamz:
= 600 passed, 6 skipped, 145 xfailed, 96 xpassed, 7 warnings in 88.10s (0:01:28) =
dask-cudf:
= 891 passed, 13 skipped, 2 xfailed, 1 xpassed, 115 warnings in 63.42s (0:01:03) =
cudf(loadscope):
= 88743 passed, 2408 skipped, 985 xfailed, 1978 xpassed, 3115 warnings in 1195.87s (0:19:55) =
```
`branch-22.04`:
```
custreamz:
= 600 passed, 6 skipped, 145 xfailed, 96 xpassed, 5 warnings in 102.16s (0:01:42) =
dask-cudf:
= 891 passed, 13 skipped, 2 xfailed, 1 xpassed, 113 warnings in 78.00s (0:01:18) =
cudf:
= 88745 passed, 2408 skipped, 985 xfailed, 1978 xpassed, 3113 warnings in 2249.52s (0:37:29) =
```

[REVIEW] Change pytest distribution algorithm and increase parallelism in CI

---

python/cudf/cudf/core/column/methods.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_pack.py

After internal profiling, it appears that `_init_from_dict_like` was being repeatedly called even for `ColumnAccessor` inputs, which is not necessary and is an expensive method where we do proper index re-alignment. This PR handles by raising an error when a developer tries to create a `DataFrame` with `ColumnAccessor`, and also changes multiple of those instances where such calls are present to `_from_data` call which will now avoid going through `_init_from_dict_like` method for `ColumnAccessor` input. For a dataframe of shape `30_00_000 x 3` the speed up is about **2.5x to 4x**.
```python
In [2]: x = cudf.DataFrame(
...:     {
...:         "a": [1, 2, 3] * 10_00_000,
...:         "b": [3, 4, 5] * 10_00_000,
...:         "c": ["a", "b", "c"] * 10_00_000,
...:     }, …
```

[REVIEW] Optimize `DataFrame` creation across code-base

---

cpp/benchmarks/common/generate_input.cpp

Data generator uses `sizeof` for all fixed width types and thus gets incorrect size for the decimal types. This leads to random tables that are actually half the requested size, causing incorrect benchmark bandwidth results.
This PR changes the `avg_element_size` to use `data_type::size_of`, which accounts for decimal types.
Note: expected to effectively half the BW of decimal benchmarks that specify the table size in bytes.

Fix the data generator element size for decimal types

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java

Hopefully this is the last one, and this one only happens when we have an empty column vector (no rows).  So much less common. I will be running more tests to check/verify a lot of this.

Yet another small JNI memory leak

---

cpp/src/strings/regex/regcomp.cpp
cpp/tests/strings/contains_tests.cpp

Closes #10223 
Fix the regex octal pattern logic to stop parsing after 3 digit characters.
Updated the gtest to include adjacent octal and digit characters.

Fix regex octal parsing to limit to 3 characters

---

cpp/include/cudf/strings/findall.hpp
cpp/src/strings/search/findall.cu
cpp/src/strings/search/findall_record.cu
cpp/tests/strings/findall_tests.cpp
python/cudf/cudf/_lib/cpp/strings/findall.pxd
python/cudf/cudf/_lib/strings/findall.pyx
python/cudf/cudf/core/column/string.py
python/cudf/cudf/tests/test_string.py

Add the `regex_flags` parameter to the strings `findall()` and `findall_record` functions so that matching regex patterns is consistent other strings regex APIs.

Add regex flags to strings findall functions

---

cpp/src/strings/regex/regcomp.cpp
cpp/tests/strings/contains_tests.cpp

Closes #10213 
Fixes parsing logic for `\x` hex characters specified in a regex pattern.
This also adds a gtest checking for all 127 possible matchable hex characters.

Fix strings handling of hex in regex pattern

---

cpp/include/cudf/strings/detail/convert/fixed_point.cuh
cpp/tests/strings/fixed_point_tests.cpp

Closes #10221 
Fixes exponent handling for large exponents. Avoids using the `exp10` function for exponent adjusts since it only accepts and returns `double` which can become imprecise for large exponents. 
Also adds a gtest using the values from #10221.

Fix string to decimal128 conversion handling large exponents

---

cpp/include/cudf/aggregation.hpp
cpp/include/cudf/detail/aggregation/aggregation.hpp
cpp/include/cudf/detail/scan.hpp
cpp/include/cudf/rolling.hpp
cpp/src/aggregation/aggregation.cpp
cpp/src/groupby/sort/group_rank_scan.cu
cpp/src/groupby/sort/group_scan.hpp
cpp/src/groupby/sort/scan.cpp
cpp/src/reductions/scan/rank_scan.cu
cpp/src/reductions/scan/scan.cpp
cpp/tests/groupby/groupby_test_util.hpp
cpp/tests/groupby/rank_scan_tests.cpp
cpp/tests/reductions/rank_tests.cpp
java/src/main/java/ai/rapids/cudf/Aggregation.java
java/src/main/java/ai/rapids/cudf/GroupByScanAggregation.java
java/src/main/java/ai/rapids/cudf/ScanAggregation.java
java/src/main/native/src/AggregationJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java
java/src/test/java/ai/rapids/cudf/TableTest.java

Fixes #9644.
The `percent_rank()` aggregation is a ranking function, similar
to `rank()` and `dense_rank()`. It calculates the fractional/relative
rank of a row within a group of rows in a column, and returns a double
value in the range [0.0, 1.0] for each row in the group/column.
This commit includes the `libcudf` changes to support `percent_rank()`
aggregations, and the supporting JNI bindings.
Note that `percent_rank()` is typically used as a window aggregation. It
is implemented as a (grouped) scan aggregation, just as `rank()` and
`dense_rank()` because it operates across the whole group of rows. (i.e.
the window specification if fixed, spanning the entire group.)
References:
1. [SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/percent-rank-transact-sql)
2. …

Support `percent_rank()` aggregation

---

python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_array_ufunc.py

This PR fixes cases like `cupy.array([1, 2, 3]) < cudf.Series([1, 2, 3])`. The code would previously attempt to find a reflected operator `Series.__rle__`, but no such operator exists because of the inherent symmetry in comparison operators. These changes fix the detection of such operators to just use operator `__ge__` in this case.

Add tests of reflected ufuncs and fix behavior of logical reflected ufuncs

---

cpp/src/join/join.cu

This PR includes several changes in the hash join `detail` functions:
- Fixes a bug where public join APIs were invoked in `detail` join functions. External invocations are replaced with the corresponding `detail` ones.
- Uses structured bindings to improve code readability
- Add an early exit before the actual join operation to improve performance

Improve hash join detail functions

---

cpp/benchmarks/string/url_decode.cpp

Fixes out-of-memory error that occurs when running the `STRINGS_BENCH` `UrlDecode` benchmark combined with any other benchmark. The following minimal command shows the error:
```
benchmarks/STRINGS_BENCH '--benchmark_filter=UrlDecode|translate_large/16'
...
------------------------------------------------------------------------------------------------------------------
Benchmark                                                        Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------------------------
StringTranslate/translate_large/16777216/32/manual_time       17.4 ms         17.5 ms           40 bytes_per_second=15.8359G/s
terminate called after throwing an instance of 'rmm::out_of_memory' …
```

Fix out-of-memory error in UrlDecode benchmark

---

cpp/benchmarks/binaryop/compiled_binaryop.cpp

Fixes out-of-memory error that occurs when running the `BINARYOP_BENCH` `COMPILED_BINARYOP` benchmark combined with the `BINARYOP` benchmark. The following minimal command shows the error:
```
benchmarks/BINARYOP_BENCH '--benchmark_filter=COMPILED_BINARYOP|100000000/10'
...
BINARYOP<double, TreeType::IMBALANCED_LEFT, false>/binaryop_double_imbalanced_unique/100000000/10/manual_time                              40.4 ms         40.4 ms           17 bytes_per_second=202.953G/s
terminate called after throwing an instance of 'rmm::out_of_memory'
what():  std::bad_alloc: out_of_memory: RMM failure at:/conda/envs/rapids/include/rmm/mr/device/pool_memory_resource.hpp:192: Maximum pool size exceeded
Aborted (core dumped)
```
The `COMPILED_BINARYOP` is using a `TEMPLATED_BENCHMARK_F` macro which …

Fix out-of-memory error in compiled-binaryop benchmark

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/join/join.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/utils/utils.py

Replaces our custom `cached_property` with that provided by `functools` since Python 3.8. This uncovered a couple of typing bugs that previously eluded us.

Replace custom `cached_property` implementation with functools

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_struct.py

Closes #10155 
`build_struct_column` requires that the field names to be strings. But dataframe column names can be any hashable types. Passing in column names as field names in `to_struct` is thus unsafe. This PR adds a check and raise a warning if the cast to string is required to take place.

Convert Column Name to String Before Using Struct Column Factory

---

java/src/main/java/ai/rapids/cudf/ColumnWriterOptions.java
java/src/main/native/src/TableJni.cpp

Closes #9851
This PR is to fix the bug raised in #9851 : Currently, Java bindings set decimal precision for each column when building OrcWriterOptions. It fills zero for non-decimal columns which do not carry precision information. In principle, we should only set precision for decimal columns.
It is not easy to write a test for this change, since we won't try to read non-decimal data as decimal type in both spark-rapids and cuDF Java.

Allow Java bindings to use default decimal precisions when writing columns

---

.pre-commit-config.yaml

Since #10253 added copyright checks, it is helpful to have the corresponding check enabled via pre-commit so that copyright issues can be found locally before pushing.

Add copyright check as pre-commit hook.

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_concat.py
python/cudf/cudf/tests/test_dataframe.py

This PR deprecates `DataFrame.iteritems` to be inline with pandas https://github.com/pandas-dev/pandas/pull/45321/files. This PR also introduces `DataFrame.items` to support a dask breaking change: https://github.com/dask/dask/pull/8660

[REVIEW] Deprecate `DataFrame.iteritems` and introduce `.items`

---

cpp/benchmarks/type_dispatcher/type_dispatcher.cu

Use `cudf::sequence` to move input generation to device in type dispatcher benchmark.
Splitting PR https://github.com/rapidsai/cudf/pull/10109 for review

move input generation for type dispatcher benchmark to device

---

cpp/CMakeLists.txt
cpp/benchmarks/CMakeLists.txt
cpp/tests/CMakeLists.txt

Currently cudf requires compiler extensions to use `__int128_t` with standard library containers. Ensure the correct compilation flags are always providied.

Explicitly request CMake use `gnu++17` over `c++17`

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/utils/utils.py

This PR removes double index equality & reindexing checks in `DataFrame` construction and `insert` code-flows.
`scalar_broadcast_to`, a **2.2x speedup** for `str` dtype, numeric types perf remains the same:
```python
In [12]: %timeit cudf.utils.utils.scalar_broadcast_to('abc', 400000000, "str")
100 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [25]: %timeit cudf.utils.utils.scalar_broadcast_to('abc', 400000000, "str")
227 ms ± 10 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
`assign`, a **1.2x-1.4x speedup**:
```python
In [9]: import numpy as np
In [10]: df = cudf.DataFrame(
...:     {
...:         "a": [1, 2, 3, np.nan] * 10000000,
...:         "b": ["a", "b", "c", "d"] * 10000000,
...:         "c": [0.0, 0.12, np.nan, 10.12] * 10000000,
...:     },
...: …
```

[REVIEW] DataFrame `insert` and creation optimizations

---

cpp/benchmarks/join/join_common.hpp

Use device functions to move input generation to device in join benchmark.
Splitting PR https://github.com/rapidsai/cudf/pull/10109 for review

device input generation in join bench

---

python/cudf/cudf/core/series.py
python/cudf/cudf/core/window/rolling.py

This PR addresses some issues that were causing documentation builds to fail. Namely:
1. Changing all `Example` headers to `Examples` (`Examples` is correct, `Example` is incorrect. see: https://numpydoc.readthedocs.io/en/latest/format.html#examples)
2. Ensuring all headers have correct underline length

Fix documentation issues [skip ci]

---

conda/recipes/libcudf_kafka/meta.yaml

From my local testing, it seems that the `librdkafka` `run_exports` is now fixed, so this line can be safely removed.

Remove `TODO` in `libcudf_kafka` recipe

---

ci/gpu/build.sh
python/cudf/cudf/tests/conftest.py
python/cudf/cudf/utils/utils.py

This PR introduces a decorator that can be used to mark APIs that are unnecessarily expensive and should be avoided in internal usage. The decorator does nothing by default, but when the corresponding environment variable is set the decorator wraps decorated functions in a check of the current call stack. If the caller of that API is within the cudf source tree, it will raise an exception that may optionally also indicate an alternate API for developers to use instead. This implementation is completely transparent to users (including having no performance impact aside from some negligible additional import time from applying the decorator) but can be an invaluable tool to developers seeking to reduce Python overheads in cuDF Python. This decorator has been tested and shown to work (both …

Prevent internal usage of expensive APIs

---

build.sh
ci/benchmark/build.sh
ci/gpu/build.sh

The `-l` flag was introduced in #3504, but I don't see it being used anywhere. Seems safe to remove unless anyone else thinks otherwise.

Remove extraneous `build.sh` parameter

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/string/copy.cu

Use device functions to move input generation to device in copy benchmark.
Splitting PR https://github.com/rapidsai/cudf/pull/10109 for review

move input generation for copy benchmark to device

---

cpp/include/cudf/detail/utilities/hash_functions.cuh

Fixes declaration of the internal `MurmurHash3_32::hash_combine()` to add the `const` qualifier.
Found this while working on #10270 and trying to call `hash_combine` from a `const` instance.

Add const qualifier to MurmurHash3_32::hash_combine

---

cpp/include/cudf/column/column_view.hpp
cpp/include/cudf/utilities/span.hpp
cpp/tests/CMakeLists.txt
cpp/tests/column/column_view_device_span_test.cpp

This PR adds an implicit conversion operator from `column_view` to `device_span<T const>`. The immediate purpose of this PR is to make it possible to use the API `segmented_reduce(column_view data, device_span<size_type> offsets, ...)` in PR #9621.
This PR also resolves #9656 by adding a `column_view` constructor from `device_span<T const>`.
More broadly, this PR should make it easier to refactor instances where `column.data()` is used with counting iterators to build transform iterators, or other patterns that require a length (e.g. vector factories to copy to host).

Add conversions between column_view and device_span<T const>.

---

python/cudf/cudf/tests/test_array_ufunc.py

This PR hides pandas warnings in `test_array_ufunc.py`. (I am working through one test file at a time so we can enable `-Werr` in the future.) These warnings come from specific functions like `arccos` for which the provided integer inputs are out-of-range. It is fine for us to hide these warnings because they do not come from cudf.
Alternatives and why I chose against them:
- Why not limit the test data input to be in the domain of the ufunc? Limiting data inputs would hide the warning. However, it would decrease our coverage that ensures cudf and pandas agree on those results for values outside the domain of the ufunc (particularly trigonometric functions). It would additionally require inputs to be generated based on the ufunc, which would be lengthy.
- Why not make cudf raise a warning …

Hide warnings from pandas in test_array_ufunc.py.

---

cpp/include/cudf/detail/utilities/hash_functions.cuh
cpp/include/cudf/hashing.hpp
cpp/include/cudf/partitioning.hpp
cpp/include/cudf/types.hpp
python/cudf/cudf/_lib/cpp/hash.pxd
python/cudf/cudf/_lib/cpp/types.pxd
python/cudf/cudf/_lib/hash.pyx

Move the `hash_id` and `DEFAULT_HASH_SEED` declarations from `types.hpp` to `hashing.hpp`.

Move hash type declarations to hashing.hpp

---

java/src/main/native/src/row_conversion.cu

#8444 modified JCUDF transcoding logic (in Java/JNI) to use `cudaMemcpyAsync()`
and `cuda::barrier` to allow for asynchronous memcpy on GPUs that support it.
While this works for `__CUDA_ARCH__ >= 700`, for older GPUs (e.g. Pascal),
JCUDF conversions cause CUDA errors and failures. E.g.
```
ai.rapids.cudf.CudfException: after reduction step 2: cudaErrorInvalidDeviceFunction:
invalid device function
```
`cudaMemcpyAsync()` is not supported on Pascal GPUs or prior. (They lack the hardware,
apparently.)
For older GPUs, rather than fail spectacularly, it would be good to provide
a more stable (if less efficient) fallback implementation, via `memcpy()`.
This commit adds code to conditionally use `cudaMemcpyAsync()` or `memcpy()`,
depending on the GPU in play.

Add Pascal support to JCUDF transcode (row_conversion)

---

cpp/src/round/round.cu
cpp/tests/round/round_tests.cpp

Signed-off-by: sperlingxx <lovedreamf@gmail.com>
Fixes up the overflow round on `nullable` fixed-point columns. In previous implementation, we built the zero replacement column via `cudf::detail::fill_in_place` with a zero scalar. However, this API overwrites the null mask of original column with the validity of the zero scalar, which is unexpected.

Fixes up the overflowed fixed-point round on nullable column

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This PR is to expose the `cudf::list::extract_list_element(column_view, column_view)` API to JNI, along with its tests.
closes https://github.com/rapidsai/cudf/issues/10340

Add JNI for extract_list_element with index column

---

java/src/main/java/ai/rapids/cudf/HostColumnVector.java
java/src/test/java/ai/rapids/cudf/ColumnBuilderHelper.java
java/src/test/java/ai/rapids/cudf/DecimalColumnVectorTest.java

This PR is to add new append method for `HostColumnVector.ColumnBuilder`. This newly-added method `appendDecimal128` allows users to add binary data, which represents the unscaled value of BigDecimal, as cuDF Decimal128.
This PR serves as a prerequisite of https://github.com/NVIDIA/spark-rapids/issues/4784.

JNI: Support appending DECIMAL128 into ColumnBuilder in terms of byte array

---

python/cudf/cudf/_lib/column.pyi
python/cudf/cudf/_lib/column.pyx
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/tests/test_dataframe.py

We previously used to cache the `Column.memory_usage` output in `Column._cached_sizeof` but it probably was missed to be included in the recent refactors. This PR re-enables caching of `memory_usage`.
`Column.memory_usage` should be a no-op on consecutive calls and **60% faster**:
```python
In [2]: s = cudf.Series(["abc ", " d e", None, "10 11 234355"] * 10000000)
In [3]: s
Out[3]: 
0                   abc 
1                    d e
2                   <NA>
3           10 11 234355
4                   abc 
...     
39999995    10 11 234355
39999996            abc 
39999997             d e
39999998            <NA>
39999999    10 11 234355
Length: 40000000, dtype: object
In [3]: %timeit s.memory_usage()
2.86 µs ± 53.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops …
```

[REVIEW] Enable caching for `memory_usage` calculation in `Column`

---

python/cudf/cudf/tests/test_binops.py

This PR catches or silences warnings in `test_binops.py`. (I am working through one test file at a time so we can enable `-Werr` in the future.) Most of the warnings come from deprecated binops inside cudf. Once the deprecated code is removed, these tests will fail until the workaround is removed.
Another warning comes from numpy, `DeprecationWarning: elementwise comparison failed; this will raise an error in the future.`. This warning can be circumvented by comparing with `series == scalar` instead of `scalar == series`. I believe that seeing this warning is expected when comparing `scalar == series`, if both numpy and pandas/cudf implement `__eq__` that accept one another's array-like types, but I'm not certain.

Fix warnings in test_binops.py.

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/df_protocol.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/window/rolling.py
python/cudf/cudf/io/parquet.py
python/cudf/cudf/testing/testing.py
python/cudf/cudf/tests/test_df_protocol.py

This PR uses the feature introduced in #10263 to remove the usage of DataFrame.columns where possible.
Currently this removes a large number of internal uses but not all of them to verify that CI does indeed fail as expected since some changes were made on #10263 after the last test of CI by reviewer request. I will convert this from a draft once I see CI fail and once all the necessary changes have been made for tests to pass.

Remove internal columns usage

---

cpp/src/jit/cache.cpp

In file `jit/cache.cpp`, a program cache always internally reserves a `std::unordered_map` using a size set by an environment variable `LIBCUDF_KERNEL_CACHE_LIMIT_PER_PROCESS`. If that environment variable does not exist, a default value (`std::numeric_limit<size_t>::max`) is used. Such default value is huge, leading to allocating a huge (impossible) size of memory chunk that crashes the system.
This PR changes that default value from `std::numeric_limit<size_t>::max` to `1024^2`. This is essentially a reverse of the PR https://github.com/rapidsai/cudf/issues/10312 but set the default value to `1024` instead of `100`.
Note that `1024^2` is just some random number, not based on any specific calculation.
Closes #10312 and closes #9362.

Fix `std::bad_alloc` exception due to JIT reserving a huge buffer

---

build.sh

This PR removes `__pycache__`, `.so` & `.pyc` files.

[REVIEW] Add cleanup of python artifacts

---

python/cudf/cudf/core/_compat.py
python/cudf/cudf/tests/test_categorical.py

This PR catches or silences warnings in `test_categorical.py`. (I am working through one test file at a time so we can enable `-Werr` in the future.) Most of the warnings come from deprecated `inplace` arguments to pandas' categorical functions. The `inplace` argument will be removed in pandas 2.0. Until then, we should just hide the warning.
Additionally, I refactored some `inplace` behavior to make the expected behavior of the test clearer.

Fix warnings in test_categorical.py.

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/ops.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/tests/test_array_ufunc.py
python/cudf/cudf/tests/test_binops.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_pickling.py

This PR builds on #10217 and #10287 to bring full ufunc support for Index types, expanding well beyond the small set previously supported in the `cudf.core.ops` namespace. By using most of the machinery introduced for IndexedFrame in the prior two PRs we avoid duplicating much logic so that all ufunc dispatches flow through a relatively standard path of known methods prior to a common cupy dispatch. With this change we are also able to deprecate the various ufunc operations defined in cudf/core/ops.py that exist only for this purpose as well as a number of Frame methods that are not defined for the corresponding pandas types. Users of those APIs are recommended to calling the corresponding numpy/cupy ufuncs instead to leverage the new dispatch.
This PR also fixes a bug where index binary …

Refactor array_ufunc for Index and unify across all classes

---

docs/cudf/source/api_docs/dataframe.rst
docs/cudf/source/api_docs/index_objects.rst
docs/cudf/source/api_docs/series.rst

PR #10124 removed several deprecated methods. This PR also removes their documentation. cc: @vyasr

Remove documentation for methods removed in #10124.

---

cpp/src/copying/concatenate.cu
cpp/tests/copying/concatenate_tests.cu

Fixes https://github.com/rapidsai/cudf/issues/10333.
The repro case in the issue showed an illegal access error where the `output_index` of the strided loop in `fused_concatenate_kernel` can overflow for a large number of rows. 
For example, given 5 tables of exactly 250M rows each we would expect a result with 1,250,000,000 rows. 
The kernel is launched with 4,882,813 blocks (# of rows / 256 threads rounded up) with a stride of 1,250,000,128 (256 * 4,882,813). When `output_index` reaches 897,483,520, it overflows `output_index` on the first iteration.
The change below prevents the overflow by making `output_index` an `int64_t` and adds a test that shows that we can now concatenate up to `size_type::max - 1` rows.

Avoid overflow in fused_concatenate_kernel output_index

---

docs/cudf/source/api_docs/dataframe.rst
docs/cudf/source/api_docs/series.rst

This PR removes doc item for deprecated function `one_hot_encoding`.

Remove doc for deprecated function `one_hot_encoding`

---

python/cudf/cudf/tests/test_csv.py

This PR silences warnings in `test_csv.py`. (I am working through one test file at a time so we can enable `-Werr` in the future.)
The only warning in this file is related to integer overflow in pandas. Currently, the test data is as follows:
https://github.com/rapidsai/cudf/blob/21325e8348f33b28e434d08d687a28f251c38f67/python/cudf/cudf/tests/test_csv.py#L1313-L1319
First, I note that this "hex" dtype is not part of the pandas API. It is a cuDF addition (#1925, #2149).
Note that there are dtypes for `int32` / `hex32`, and the test data contains both a negative value `-0x1000` and a value `9512c20b`. The negative value `-0x1000` has a sensible interpretation if the results are meant to be signed, but then the value `9512c20b` is out of range (the maximum signed 32-bit value would be …

Fix warnings in test_csv.py.

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py
python/cudf/cudf/utils/utils.py

This PR cleans up the implementation of `__array_function__` for `Series` and `DataFrame` to bring them further into alignment. It also inlines a number of functions defined in `utils/utils.py` that were previously used only in `Series.__array_ufunc__`, building on the improvements in #10217, #10287, and #10346 to clear out methods related to the old `__array_ufunc__` dispatch that are now only used by this `__array_function__` implementation. Inlining these methods also allows significant simplification since they were handling cases that are no longer relevant or possible. Unlike those previous PRs, this one does not actually enable any new features. Although it should marginally accelerate array functions by simplifying the dispatch logic, the fact that this API makes few promises …

Refactor array function

---

cpp/include/cudf/io/text/multibyte_split.hpp
cpp/src/io/text/multibyte_split.cu

#10150 broke compiler support for GCC 11 (built locally) because it was missing `#include <optional>` in a couple files. This fixes it. cc: @cwharris

Include <optional> in multibyte split.

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_setitem.py

Fixes: #10305  This PR fixes issues where the `scalar` that is being assigned was being type-casted to the column's type. Added test coverage for the same.

[REVIEW] Fix issue with column and scalar re-assignment 

---

cpp/include/cudf/detail/sorting.hpp
cpp/include/cudf/sorting.hpp
cpp/src/sort/sort.cu
cpp/src/sort/stable_sort.cu
cpp/tests/CMakeLists.txt
cpp/tests/sort/sort_test.cpp
cpp/tests/sort/stable_sort_tests.cpp

This PR adds a new `stable_sort_by_key` API into libcudf. The new API is helpful to simplify Cython/JNI bindings of `drop_duplicates` (https://github.com/rapidsai/cudf/pull/10370).

Add `cudf::stable_sort_by_key`

---

java/src/main/native/src/RmmJni.cpp

We use the `limiting_resource_adaptor` in front of the async allocator to track the total size of allocations and trigger spills. By default the adaptor aligns to 256, but the async allocator internally aligns to 512. This causes the limiting adaptor to under count allocation sizes, leading to OOMs in the async allocator. This PR changes the limiting adaptor to also use 512. This seems to help with a customer query that we were seeing OOMs before.
Note that CUDA is planning to switch back to 256 in the future so this may need to be revisited.
Fixes #10384

Limiting async allocator using alignment of 512

---

cpp/benchmarks/binaryop/compiled_binaryop.cpp

Fixes `BINARYOP_BENCH` which is throwing an error for non-numeric types:
```
terminate called after throwing an instance of 'cudf::logic_error'
what():  cuDF failure at: /cudf/cpp/src/filling/sequence.cu:139: init scalar type must be numeric
```
The `compiled_binaryop.cpp` was recently changed in #10300 to create test columns using the benchmark utility `create_sequence_table` which internally calls `cudf::sequence` API. Unfortunately, [only `numeric` types can be used with this API](https://github.com/rapidsai/cudf/blob/a9b6cb113bcacecd0752d2957971c0d417cf719e/cpp/src/filling/sequence.cu#L139) which throws an error for types like `timestamp, duration, and decimal` which are being measured in this file. https://docs.rapids.ai/api/libcudf/stable/group__transformation__fill.html#gaeda630c9dc …

Fix error thrown in compiled-binaryop benchmark

---

python/cudf/cudf/tests/test_rolling.py

Fixes or catches warnings in `test_rolling.py`. Part of #10363. (I am working through one test file at a time so we can enable `-Werr` in the future.)

Fix warnings in `test_rolling`

---

cpp/CMakeLists.txt
cpp/include/cudf/detail/reduction_functions.hpp
cpp/src/reductions/collect_ops.cu
cpp/src/reductions/reductions.cpp
cpp/tests/CMakeLists.txt
cpp/tests/reductions/collect_ops_tests.cpp

Closes #7807 
Curreent PR is to support the collect aggregation family in reduction context, which includes collect_list, collect_set, merge_lists, and merge_sets.
The implementations are inspired by corresponding collect aggregations in groupby context.

Support collect aggregations in reduction

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py

A quick fix to set column names in the `_from_columns_like_self` factory. Since dataframe column names are slightly more complex than simple Frame, this fix makes sure column name metadata (such as multi level names) are properly copied to the result dataframe.
Addresses this comment: https://github.com/rapidsai/cudf/pull/10315#issuecomment-1049285506

Set column names in `_from_columns_like_self` factory

---

codecov.yml
python/cudf/cudf/utils/utils.py

This PR enables github-check for `codecov` that annotates code changes that are not being covered in pytests.

[REVIEW] Enable `codecov` github-check in CI

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/single_column_frame.py

This fixes an unnecessary import. `str` is equivalent to `builtins.str`, so we don't need to `import builtins`.

Use str instead of builtins.str.

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/single_column_frame.py

The APIs `DataFrame.nunique`, `Series.nunique`, and `ColumnBase.distinct_count` have a `method` argument. The pandas API for `nunique` [does not have a `method` argument](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). This `method` argument was meant to distinguish distinct counts computed by sort/hash approaches, but there are two issues: only `"sort"` is supported as an input value, and the algorithm in libcudf actually uses a _hash-based approach_. To resolve this inconsistency and align with the pandas API, I have removed the `method` parameter from `DataFrame.nunique`, `Series.nunique`, and `ColumnBase.distinct_count`.
This is a breaking change but I don't think a deprecation is needed. The `nunique` feature was added in 22.04 via #10077, so it has not …

Drop unsupported method argument from nunique and distinct_count.

---

python/cudf/cudf/io/parquet.py
python/cudf/cudf/tests/test_parquet.py

Resolves part of https://github.com/rapidsai/cudf/issues/10363, there still are some warnings remaining, which I tried to resolve and went down a rabbit hole of a bug inside pyarrow<->pandas conversions so will take it up later.

[REVIEW] Fix some warnings in `test_parquet.py`

---

cpp/src/groupby/sort/group_collect.cu

After puring null entries via copy_if, the null mask of the input column will be preversed, despite it is useless. We can clean up the unused null mask to save some device memory.

Clean up null mask after purging null entries

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/java/ai/rapids/cudf/SegmentedReductionAggregation.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/SegmentedReductionTest.java

This adds in JNI support for #9621. It also adds in a helper API to allow us to do the processing on a list easily.

JNI support for segmented reduce

---

cpp/benchmarks/reduction/anyall.cpp
cpp/benchmarks/reduction/dictionary.cpp
cpp/benchmarks/reduction/reduce.cpp
cpp/benchmarks/reduction/scan.cpp

Fixes benchmarks compile errors introduced by #10357 
Example:
```
/cudf/cpp/benchmarks/reduction/reduce.cpp: In function ‘void BM_reduction(benchmark::State&, const std::unique_ptr<cudf::aggregation>&)’:
/cudf/cpp/benchmarks/reduction/reduce.cpp:52:46: error: invalid initialization of reference of type ‘const std::unique_ptr<cudf::reduce_aggregation>&’ from expression of type ‘const std::unique_ptr<cudf::aggregation>’
52 |     auto result = cudf::reduce(input_column, agg, output_dtype);
```
Aggregation types for reduce and scan were modified to include template types.

Fix benchmarks to work with new aggregation types

---

java/src/main/java/ai/rapids/cudf/ColumnVector.java
java/src/main/java/ai/rapids/cudf/GroupByAggregation.java
java/src/main/java/ai/rapids/cudf/ReductionAggregation.java
java/src/test/java/ai/rapids/cudf/ReductionTest.java

Exposes public APIs for collect operations as `ReductionAggregation`, which are essential to spark-rapids.  In addition, this PR also extends the test framework of Reduction to discriminate output types from input types.

JNI support for Collect Ops in Reduction

---

python/cudf/cudf/core/tools/numeric.py
python/cudf/cudf/tests/test_numerical.py

Fixes: #10049 
This PR fixes an incorrect error being displayed when `cudf.to_numeric` is called by passing an input with `bool` dtype. Technically `bool` is the lowest `dtype` size possible in `numpy` so this is a no-op because `to_numeric` is aimed at downcasting inputs.

[REVIEW] Fix error in `cudf.to_numeric` when a `bool` input is passed

---

python/dask_cudf/dask_cudf/backends.py

Updated imports to be compatible with latest dask after https://github.com/dask/dask/pull/8796
This change is also compatible with dask versions prior to the above dask PR.
Tested `import dask_cudf` with both dask `2022.02.2a220314` and `2022.02.2a220315`.

Update dask_cudf imports to be compatible with latest dask

---

cpp/src/copying/contiguous_split.cu
cpp/tests/copying/split_tests.cpp

This is a fix for an integer overflow in `contiguous_split.cu::copy_data`. 
We encountered this problem when running a large query with the spark-rapids plug-in.  The plug-in OOM callback was reporting negative numbers for some failed allocations.  It treats the allocation size as a `long`.   The allocations were coming from `contiguous_split` with a large number of rows (399,000,000) of type `UINT64`.
With help from @nvdbaranec, I was able to isolate the problem to this line:
```
size_t const bytes = buf.num_elements * buf.element_size;
```
The two operands are both `INT32`.  So the result of the multiply is being sign-extended when assigning to `bytes`.
The fix is to cast these to `size_t` before the multiply.

Fix for integer overflow in contiguous-split

---

cpp/src/lists/drop_list_duplicates.cu
cpp/tests/lists/drop_list_duplicates_tests.cpp

For now, `get_indices_of_unique_entries_dispatch` only checks the outest layer of structures to determine whether the column contains null or not. It leads to the omission of intra null structures.
In current, 
`[Struct(Struct(1, "a", valid)), Struct(Struct(1, "a", valid), Struct(Struct(2, "a", invalid), Struct(Struct(1, "b", invalid)]` becomes
`[Struct(Struct(1, "a", valid)), Struct(Struct(2, "a", invalid), Struct(Struct(1, "b", invalid)]` after droping list duplicates even if null equality is EQUAL. However, it should be 
`[Struct(Struct(1, "a", valid)), Struct(Struct(2, "a", invalid)]`, because `Struct(1, "a")` and `Struct(2, "a")` are both invalid, despite they contain different elements.
Current PR is to fix above problem by checking all flattened coulumns for nulls.

Fix has_null predicate for drop_list_duplicates on nested structs

---

cpp/src/reductions/reductions.cpp
cpp/tests/reductions/collect_ops_tests.cpp

For certain aggregation operations, such as: `collect_list` or `collect_set`, their output types are List, while their input might not be List.  We need to handcraft the the default scalar for this scenario, since `make_default_constructed_scalar` can not create list scalars.

Fix empty reduce with List output and non-List input

---

cpp/src/io/comp/unsnap.cu
cpp/src/io/orc/reader_impl.cu
cpp/src/io/parquet/reader_impl.cu

- Add status checking of decompressed snappy parquet pages when using cuDF snappy decompression.
- Improve the performance of checking decompressed snappy parquet pages when using nvCOMP snappy decompression by reducing the number of synchronizes.

Make snappy decompress check more efficient

---

docs/cudf/source/api_docs/general_functions.rst

Add `cut` to API docs

---

docs/cudf/source/api_docs/general_functions.rst

Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

---

cpp/include/cudf/table/experimental/row_operators.cuh
cpp/src/io/parquet/compact_protocol_reader.hpp

Includes `<cstddef>` for `ptrdiff_t` in `parquet/compact_protocol_reader.hpp`. Compilation fails on GCC 11 without this include. Targeting 22.04 since this was broken yesterday in #10063.
Error output:
```
cudf/cpp/src/io/parquet/compact_protocol_reader.hpp:51:17: error: 'ptrdiff_t' does not name a type
51 |   [[nodiscard]] ptrdiff_t bytecount() const noexcept { return m_cur - m_base; }
|
cudf/cpp/src/io/parquet/compact_protocol_reader.hpp:22:1: note: 'ptrdiff_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
```
Also includes `<optional>` in `cpp/include/cudf/table/experimental/row_operators.cuh`, which was broken by #10164.

Include <cstddef> to fix compilation of parquet reader on GCC 11.

---

ci/benchmark/build.sh
ci/gpu/build.sh
conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/custreamz/meta.yaml
conda/recipes/dask-cudf/meta.yaml
python/custreamz/dev_requirements.txt
python/dask_cudf/dev_requirements.txt
python/dask_cudf/setup.py

This PR pins `dask` and `distributed` versions for release.

[REVIEW] Pin `dask` and `distributed`

---

cpp/include/cudf/detail/valid_if.cuh
cpp/include/cudf/types.hpp
cpp/src/copying/scatter.cu
cpp/src/replace/nulls.cu
cpp/src/rolling/jit/kernel.cu
cpp/src/rolling/rolling_detail.cuh
cpp/src/transform/compute_column.cu

Partially addresses  https://github.com/rapidsai/cudf/issues/10368
Specifically:
- `valid_if`
- `scatter`
- `rolling_window`
- `compute_column_kernel` (ast stuff)
- `replace_nulls` (fixed-width and strings)
The majority of the fixes are simply making the indexing variable a `std::size_t` instead of a `cudf::size_type`.  Although scatter had an additional place it was overflowing outside the kernel.
I didn't add tests for these fixes, but each of them were individually tested locally to make sure they actually manifested the issue and then were verified with the fixes.

Batch of fixes for index overflows in grid stride loops.

---

python/cudf/cudf/tests/test_stats.py

This PR skips `scipy` related code-path that pandas takes. This isn't a failure in CI, but cudf dev env doesn't require having a `scipy` package, hence adding an `importorskip`.

[REVIEW] Add `scipy` skip for a test

---

cpp/src/quantiles/tdigest/tdigest_aggregation.cu
cpp/tests/reductions/tdigest_tests.cu

A case was found where merging tdigests that contain very small numbers of centroids with high weight could cause an invalid resulting tdigest to be generated.  The issue was in the "gap fixup" code during the cluster generation step.
The diff here is unfortunate but the change is fundamentally:  Make sure we run through the gap-fixing code during the first pass (where we're just counting the # of buckets), and update the nearest weight (nearest_w) variable representing the centroid we just bucketed.
<s>Leaving a Do Not Merge tag on here for now to get confirmation of fix from Spark team.</s>

Fix an issue with tdigest merge aggregations.

---

python/cudf/cudf/_lib/binaryop.pyx
python/cudf/cudf/_lib/datetime.pyx
python/cudf/cudf/_typing.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/mixins/binops.py
python/cudf/cudf/core/mixins/binops.pyi
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/tests/test_list.py
python/cudf/cudf/tests/test_timedelta.py
python/cudf/cudf/utils/applyutils.py
python/cudf/cudf/utils/utils.py

This PR changes the way that binary operations are performed between columns. Instead of directly invoking the `_binaryop` method Frame binary operations now invoke operators directly using the `operator` module. Each `Column` subclass now only defines operations that are well-defined, relying on Python to handle raising `TypeError`s for all others. Binary operations return `NotImplemented` instead of raising a `TypeError` _except_ in specific cases where a meaningful error should be raised, allowing us to take advantage of reflected operations to prevent duplicate logic on how to handle binary operations between distinct types. Finally, various edge cases that were previously handled by Frames are now handled in Column so that different dtype columns are the sole source of truth on what …

Define proper binary operation APIs for columns

---

python/cudf/cudf/core/column/string.py
python/cudf/cudf/tests/test_string.py

This is a small fix to [match the pandas API](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html) for the `expand` parameter of `Series.str.split`. Only boolean values are allowed. Currently the default is set to `None` and then replaced with the intended default of `False`. This PR changes it to have a default value of `False`.
This is a tiny bit of an API break because users who explicitly passed `None` will now see an error instead of getting the intended default value, but the previous behavior was a bug with respect to pandas API compatibility.

Fix default value of str.split expand parameter.

---

cpp/benchmarks/reduction/segment_reduce.cu

Addresses part of https://github.com/rapidsai/cudf/issues/5773
uses `create_random_table` and moves benchmark input generation in device in reduction nvbench

move benchmark input generation in device in reduction nvbench

---

cpp/doxygen/regex.md
cpp/include/cudf/strings/findall.hpp
cpp/src/strings/search/findall_record.cu
cpp/tests/strings/findall_tests.cpp

Closes #10458 
Change the behavior of `cudf::strings::findall_record` to return an empty row when the search results in no matches for the corresponding input strings row. The previous behavior was returning a null row when no matches are found.

Fix findall_record to return empty list for no matches

---

cpp/src/join/mixed_join_kernels.cu
cpp/src/join/mixed_join_kernels_semi.cu
cpp/src/join/mixed_join_size_kernels.cu
cpp/src/join/mixed_join_size_kernels_semi.cu

The following change addresses a performance degradation we noticed in the `mixed_join` and `compute_mixed_join_output_size` that looks to be tied to the theoretical occupancy of these kernels, as limited by the number of registers used.
The regression is triggered by this patch: https://github.com/rapidsai/cudf/pull/9727, which improves handling of unreachable code paths. That said, somehow, this change is altering the number of registers these kernels need. Both `mixed_join` and `compute_mixed_join_output_size` are very sensitive to the register count, per NSight compute. With the patch, the register required changed from 92 to 102, and 118 to 141 respectively. 
The fix here hints the compiler what our block size is (128 threads). This, from our testing, allows the compiler to reduce …

Adds launch bounds hints to mixed join kernels to address regression seen in NDS q72 in Spark

---

cpp/include/cudf/strings/replace_re.hpp
cpp/src/strings/replace/backref_re.cu
cpp/tests/strings/replace_regex_tests.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Current PR is to adjust to the valid range of group index for cuDF API `cudf::strings::replace_with_backrefs`.
1.  enable 0 as group index
For now, the range of group index starts with 1, which doesn't include the special value 0. Zero-value as backref index usually refers the entire matching pattern. So does cuDF regexp system.
Therefore, what we only need to do is lifting the restrictions to allow zero-value passed as the group index of back references.
Example of zero-value index:
input: `aa-11 b2b-345`
pattern: `([a-z]+)-([0-9]+)`
replacement: `${0}:${1}:${2};`
output: ```aa-11:aa:11; b2b-345:b:345;```
2. group index should not exceed group count
For now, group indices can exceed group count. The exceeding ones will end up to be empty string. IMHO, it is better to throw an exception …

Adjust the valid range of group index for replace_with_backrefs

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/libcudf/meta.yaml
conda/recipes/libcudf_example/meta.yaml
conda/recipes/libcudf_kafka/meta.yaml

CMake 3.23 appears to have a bug relating to CUDA support that breaks our builds.

Pin CMake to prevent 3.23 bugs

---

conda/recipes/libcudf/build.sh

The Build Metrics Report was accidentally disabled in #10326. This will add the flags back to the `build.sh` that are required to generate the report during CI.

Re-enable Build Metrics Report

---

cpp/doxygen/regex.md
cpp/include/cudf/strings/split/split_re.hpp

Adds Replace Backreferences section to the [Regex Features](https://docs.rapids.ai/api/libcudf/stable/md_regex.html)  page to help document the replacement template patterns for `cudf::strings::replace_with_backref` API.
Also, adds `cudf::strings::split_re` and `cudf::strings::split_record_re` to the regex APIs listed at the top of the page.
And add a link to `regex_flags` where the line anchors and the `dot` pattern character are described.

Add Replace Backreferences section to Regex Features page

---

java/src/main/java/ai/rapids/cudf/Cuda.java
java/src/main/native/src/CudaJni.cpp

This commit introduces JNI bindings to retrieve the major and minor CUDA compute capability versions for the current CUDA device.
This feature enables introspection from `spark-rapids` to detect the GPU architecture, for model-specific behaviour.
This is required from NVIDIA/spark-rapids/pull/5122, to work around the erroneous behaviour of JNI `fixed_width_convert_to_rows()` on Pascal GPUs (#10569), (which in turn produces failures like NVIDIA/spark-rapids/issues/4980).

JNI Bindings to fetch CUDA compute capability versions.

---

cpp/include/cudf/lists/combine.hpp
cpp/include/doxygen_groups.h

Corrects the [Modules](https://docs.rapids.ai/api/libcudf/nightly/modules.html) page where the `lists_filling` group appears at the bottom:
The `lists_filling` group is added to the appropriate section in the [`doxygen_groups.h`](https://github.com/rapidsai/cudf/blob/branch-22.06/cpp/include/doxygen_groups.h) file.
Also added a doxygen description for `namespace lists` so it will appear in the [Namespace List](https://docs.rapids.ai/api/libcudf/nightly/namespaces.html) page. This becomes an easy way to find the documentation fo all the `lists` APIs.

Fix doxygen Modules page for cudf::lists::sequences

---

cpp/cmake/thrust.patch

Fixes `thrust.patch` to patch the CUB source for `sort` to minimize the inlining of the comparator functor. The build was updated in #10489 to thrust-1.16 which includes change to thrust sort using CUB's `DeviceMergeSort`. This means the previous patch does not apply to the new thrust/cub source. This dramatically increased the build for `sort.cu` and other related source files as can be seen in this Build Metrics Report from #10489: https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/8633/Build_20Metrics_20Report/
This PR moves the `pragma unroll` changes into the appropriate CUB source files reducing the build time back to the previous levels (or close to it I hope).

Add patch for thrust-cub 1.16 to fix sort compile times

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/numerical_base.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/column/struct.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/core/tools/datetimes.py
python/cudf/cudf/testing/testing.py
python/cudf/cudf/tests/test_column.py
python/cudf/cudf/tests/test_df_protocol.py
python/cudf/cudf/tests/test_series.py
python/cudf/cudf/tests/test_testing.py

This PR removes the `ColumnBase.__getitem__` method, which is heavily overloaded and easy to abuse, and changes everywhere that called it to use the appropriate method. There turn out to be exactly two places in the code that actually require the current implementation of this method, Series and Index indexing, so this functionality has been moved into `SingleColumnFrame`. Removing `__getitem__` also means that we no longer need to explicitly fail on `__iter__` and `__array__` since there is no longer an implicit fallback.
The one downside to this now is that it _is_ possible to create a numpy array from a column. However, it won't make a numpy array from the data, it will create an object dtype 0-D array _containing_ the column. This is how `np.array` and `np.asarray` behave for normal …

Remove ColumnBase.__getitem__

---

cpp/cmake/thirdparty/get_thrust.cmake
cpp/cmake/thrust.patch

PR #10489 updated from Thrust 1.15 to Thrust 1.16. However, this appears to be causing conflicts with other repositories -- [cuSpatial](https://github.com/rapidsai/cuspatial/pull/511#issuecomment-1087738627) and cuGraph have reported issues where their builds are finding Thrust 1.16 from libcudf instead of Thrust 1.15 which is [currently pinned by rapids-cmake](https://github.com/rapidsai/rapids-cmake/blob/06a657281cdd83781e49afcdbb39abc491eeab17/rapids-cmake/cpm/versions.json#L26).
This PR is intended to unblock local builds and CI builds for other RAPIDS packages until we are able to identify the root cause (which may be due to CMake include path orderingsrapids-cmake).
Last time Thrust was updated, [rapids-cmake was updated](https://github.com/rapidsai/rapids-cmake/pull/138) one day …

Revert Thrust 1.16 to Thrust 1.15

---

cpp/CMakeLists.txt
cpp/cmake/thirdparty/get_cucollections.cmake

This PR tracks private dependencies in the build and install export sets when building static libs. This is necessary for consumers to statically link `libcudf.a` via CMake.

[FEA] Enable building static libs

---

python/cudf/cudf/core/column/string.py
python/cudf/cudf/tests/test_string.py

Closes #10591 
Ensures `to_strip` parameter is a `str` type when converting it to `cudf.Scalar`. It will now through a `TypeError` as follows
```
libstrings.strip(self._column, cudf.Scalar(to_strip, "str"))
File "/conda/envs/rapids/lib/python3.8/site-packages/cudf-22.6.0a0+96.g0aef0c1c3e.dirty-py3.8-linux-x86_64.egg/cudf/core/scalar.py", line 78, in __init__
self._host_value, self._host_dtype = self._preprocess_host_value(
File "/conda/envs/rapids/lib/python3.8/site-packages/cudf-22.6.0a0+96.g0aef0c1c3e.dirty-py3.8-linux-x86_64.egg/cudf/core/scalar.py", line 128, in _preprocess_host_value
raise TypeError("Lists may not be cast to a different dtype")
TypeError: Lists may not be cast to a different dtype
```
This will also prevent the _sticky_ CUDA error.
Also, added the `str` parameter to …

Fix strings strip() to accept only str Scalar for to_strip parameter

---

python/cudf/cudf/core/column/lists.py
python/cudf/cudf/tests/test_list.py
python/cudf/cudf/tests/test_text.py
python/dask_cudf/dask_cudf/tests/test_accessor.py

Closes #10540.
As mentioned in the issue, this is a breaking change, although we could introduce this change in a non-breaking way by using a sentinel value for the kwarg if desired.

Add default= kwarg to .list.get() accessor method

---

java/pom.xml
java/src/main/native/CMakeLists.txt

This adds the ability for the JNI native libraries to be built as static libraries rather than shared libraries by specifying `-DBUILD_SHARED_LIBS=OFF` when configuring with cmake.  This can be useful for external projects that are leveraging the JNI libraries and would like to use an archive that they can link into their shared library.

Allow libcudfjni to be built as a static library

---

cpp/include/cudf/io/json.hpp

Same as https://github.com/rapidsai/cudf/pull/10626 but against the correct branch

Fix type-o in docstring for json_reader_options

---

cpp/benchmarks/sort/sort_structs.cpp
cpp/include/cudf/table/experimental/row_operators.cuh
cpp/src/table/row_operators.cu
cpp/tests/sort/sort_test.cpp

Fixes #10603
This PR is to fix a bug of the optimized struct row comparator. For now,  the struct row comparator assumes that structs being compared are non-empty, so it fails when comparing empty structs.

Fix struct row comparator's exception on empty structs

---

docs/cudf/source/user_guide/guide-to-udfs.ipynb

This PR updates our guide to UDFs notebook in the following ways:
- Notes deprecation of `cudf.Series.applymap`
- reorder sections such that `cudf.Series.apply` and `cudf.DataFrame.apply` are encountered before `applymap`, `apply_rows` and `apply_chunks`
- Adds recommendations about use cases for each of the above APIs to distinguish them
- Minor updates all over to better describe current state
EDIT: decided to just remove the docs for `applymap` at this point.

Update guide to UDFs with notes about `Series.applymap` deprecation and related changes

---

cpp/src/strings/convert/convert_datetime.cu
cpp/tests/strings/datetime_tests.cpp

Closes #10609 
This adds support for 'Z' in a timestamp string for the `%z` specifier. Normally, the `%z` specifier expects an hour-minute format like `+HHMM` but strptime and other libraries also accept a single 'Z' here. The following two strings should result in the same timestamp value: `"2022-04-07 09:15:00Z" and "2022-04-07 09:15:00+0000"`
The `cudf::strings::is_timestamp` and `cudf::strings::to_timestamps` have been updated to support this behavior. A gtest was updated to include this as a testcase.

Fix to_timestamps to support Z for %z format specifier

---

cpp/src/strings/convert/convert_floats.cu

Reference #10599 
Provides a slight improvement in accuracy for the internal stod device function used by the `cudf::strings::to_floats()` API.
Reduces the number of floating-point operations by 1 and also applies the exponent by conditionally multiplying or dividing depending on it being positive or negative. This slightly improves accuracy of the result since multiplying decimal fractions in floating point can compound errors.
```
>>> s = cudf.Series(['1.0','2.0','0.1','0.2','0.3'])
>>> x = cudf.to_numeric(s)
>>> x[0]
1.0        previously 0.9999999999999999
>>> x[1]
2.0        previously 1.9999999999999998
>>> x[2]
0.1        previously 0.09999999999999999
>>> x[3]
0.2        previously 0.19999999999999998
>>> x[4]
0.3        same
```
The 1.0 floating-point value in bits was …

Slightly improve accuracy of stod in to_floats

---

docs/cudf/source/api_docs/io.rst
python/cudf/cudf/utils/ioutils.py

Changes documented API name from `cudf.io.json.read_json` to `cudf.read_json`. This aligns with Pandas' documentation and eliminates an awkward switch of the `.. currentmodule` in Sphinx. See thread: https://github.com/rapidsai/cudf/pull/10638#discussion_r847838662

Use cudf.read_json as documented API name.

---

python/cudf/cudf/core/algorithms.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/utils/cudautils.py
python/cudf/cudf/utils/utils.py

Standardizes docstring section headings to reduce parsing warnings in Sphinx output. (I have a few other incoming PRs to fix documentation issues, this one is split into its own PR since it touches a lot of files.)

Fix docstring section headings.

---

docs/cudf/source/api_docs/dataframe.rst
docs/cudf/source/api_docs/index_objects.rst
docs/cudf/source/api_docs/series.rst
python/cudf/cudf/utils/ioutils.py

This adds a bunch of missing methods to the documentation and removes methods that no longer exist.
When building, Sphinx issues warnings like this one, which indicates that a method isn't documented:
```
.../cudf/docs/cudf/source/api_docs/api/cudf.Series.pct_change.rst: WARNING: document isn't included in any toctree
```
and this one, which indicates that a documented method no longer exists:
```
WARNING: [autosummary] failed to import cudf.Series.ceil.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Series'
* AttributeError: type object 'Series' has no attribute 'ceil'
* ImportError:
```
This PR doesn't fix all of the warnings/errors, but it is a good chunk of them.

Add missing APIs to documentation.

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py

Removes some unnecessary implementation detail from `apply` docstrings and updates them where necessary.

Remove implementation details from `apply` docstrings

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_stats.py

Add support for numeric_only in DataFrame._reduce, this way can use df.mean(numeric_only=True), etc. Resolves https://github.com/rapidsai/cudf/issues/2067. Also partially addresses https://github.com/rapidsai/cudf/issues/9009.

Add support for numeric_only in DataFrame._reduce

---

cpp/benchmarks/io/orc/orc_writer.cpp
cpp/benchmarks/sort/rank.cpp
cpp/benchmarks/string/convert_durations.cpp
cpp/include/cudf/detail/reduction_functions.hpp
cpp/libcudf_kafka/src/kafka_callback.cpp
cpp/libcudf_kafka/src/kafka_consumer.cpp
cpp/src/merge/merge.cu
cpp/src/structs/structs_column_view.cpp
cpp/tests/binaryop/binop-compiled-fixed_point-test.cpp
cpp/tests/hash_map/map_test.cu
cpp/tests/iterator/value_iterator_test_strings.cu
cpp/tests/partitioning/partition_test.cpp

This PR cleans up some C++ includes to use `#include <...>` instead of `#include "..."` where appropriate.

Clean up C++ includes to use <> instead of "".

---

cpp/cmake/thirdparty/get_cucollections.cmake

With the corrections in https://github.com/rapidsai/cudf/pull/10545 we didn't install the cuco headers / cmake files as they aren't needed for shared builds. But we forgot to remove the `find_package(cuco)` call from the generated cudf-config.cmake.

cuco isn't a cudf dependency when we are built shared

---

docs/cudf/source/user_guide/guide-to-udfs.ipynb

I noticed a couple lines I didn't expect in the UDF notebook in the User Guide while working on #10663. I didn't get these changes into that PR (had to wait for a local build to verify some things). The two changes are:
- We don't require `method="cudf"` in groupby statements.
- We don't need to execute `from cudf.utils import cudautils` to run this notebook.
(The cell execution counts also changed. There were some cells executed multiple times the last time this notebook was executed so they got out of order - this fixes it.)

Update UDF notebook in User Guide.

---

cpp/benchmarks/text/subword.cpp
cpp/include/cudf_test/file_utilities.hpp

Addressing a long-standing TODO. Since std::filesystem is available since C++17, use it to recursively delete temporary directories (used for benchmarks, etc.). 
Small step towards portable temp directory/file utilities.

Use `std::filesystem` for temporary directory location and deletion

---

python/cudf/cudf/_lib/column.pyx
python/cudf/cudf/_lib/null_mask.pyx
python/cudf/cudf/_lib/parquet.pyx
python/cudf/cudf/_lib/rolling.pyx
python/cudf/cudf/core/algorithms.py
python/cudf/cudf/core/column/datetime.py
python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/subword_tokenizer.py
python/cudf/cudf/tests/test_api_types.py
python/cudf/cudf/tests/test_contains.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_datetime.py
python/cudf/cudf/tests/test_duplicates.py
python/cudf/cudf/tests/test_hdfs.py
python/cudf/cudf/tests/test_orc.py
python/cudf/cudf/tests/test_scalar.py
python/cudf/cudf/utils/dtypes.py
python/cudf/cudf/utils/queryutils.py

This PR standardizes a few imports across the cudf code base. Changes include:
- Removed usage of some non-standard "two letter" names. For example, `import numpy as np` is common, but `import pyorc as po` and `import fastavro as fa` are non-standard and not the style used by their documentation. I left `import cupy as cp`, since both `import cupy` and `import cupy as cp` are prevalent in the code base (the one exception that I changed was a file that had both `import cupy` and `import cupy as cp`).
- Avoid the pattern `from some_package import x as x` -- just write `from some_package import x`
- Fixed some `cimport`s
- Always use `import datetime` instead of `import datetime as dt` to avoid conflicts with the many other `dt` names in our code (including local names that had the potential …

Standardize imports.

---

python/cudf/cudf/_fuzz_testing/json.py
python/cudf/cudf/_lib/csv.pyx
python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/api/types.py
python/cudf/cudf/comm/gpuarrow.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/core/cut.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/df_protocol.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/join/_join_helpers.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/series.py
python/cudf/cudf/testing/_utils.py

The codebase currently uses multiple ways of importing `collections.abc` classes in cudf. This can be problematic because the names in `collections.abc` can overlap with names in `typing`, so we need a way to disambiguate the two. This PR standardizes our imports such that abstract base classes follow a pattern so that `abc.` is always in the name of abstract base classes.
```python
from collections import abc
if isinstance(obj, abc.Mapping):
pass
```

Standardize usage of collections.abc.

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Current PR is to enable cuDF API `segmented_gather` in Java package. `segmented_gather` is essential to implement spark array functions like `arrays_zip`(https://github.com/NVIDIA/spark-rapids/issues/5229).

Enable segmented_gather in Java package

---

python/cudf/cudf/utils/gpu_utils.py

The call to `getDeviceCount()` can raise a `RuntimeError` when `libcuda.so` is missing. We should handle that too in `validate_setup()`.

Handle RuntimeError thrown by CUDA Python in `validate_setup`

---

cpp/src/io/parquet/chunk_dict.cu
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/writer_impl.cu

This PR includes several changes to improve parquet dictionary encoding:
- API cleanups: get rid of unused arguments
- Remove min block limit in ` __launch_bounds__`
- Simplify the grid-stride loop logic by using `while`
- All threads calculate start/end indices instead of one doing the calculation and broadcasting the result (no more shared memory or block-wide sync).
Other ideas tested but not eventually included in this PR due to zero or negative performance impact:
- Tuning hash map occupancy
- `cg::shfl` instead of shared memory + sync
- CG based `insert`/`find`
- Relaxed atomic for `num_dict_entries` and `uniq_data_size`
- `cg::reduce` instead of `cub::BlockReduce`
Before:
```
------------------------------------------------------------------------------------------------------------ …
```

Improve parquet dictionary encoding

---

docs/cudf/source/user_guide/guide-to-udfs.ipynb

Fixes an issue where sphinx was reading the `#`'s in the UDF guide markdown cells as section headings causing strange effects in the docs main index page.

Fix sphinx/jupyter heading issue in UDF notebook

---

cpp/include/cudf/strings/string.cuh
cpp/src/strings/convert/convert_floats.cu
cpp/src/strings/convert/convert_integers.cu

Minor change to change the unnecessary `cudf::strings::string` namespace in the `string.cuh` functions' declarations/definitions to just `cudf::strings`. The extra `string` namespace is confusing an not needed. Calling functions have been updated appropriately.

Remove cudf::strings::string namespace

---

cpp/docs/DEVELOPER_GUIDE.md
cpp/docs/DOCUMENTATION.md

Introduce deprecation policy to developer guide.

---

python/cudf/cudf/core/column/lists.py
python/cudf/cudf/tests/test_list.py

Closes https://github.com/rapidsai/cudf/issues/10687.

Add `.list.astype()` to cast list leaves to specified dtype

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/numerical.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/series.py
python/cudf/cudf/testing/_utils.py
python/cudf/cudf/tests/test_array_function.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_dropna.py
python/cudf/cudf/tests/test_duplicates.py
python/cudf/cudf/tests/test_index.py
python/cudf/cudf/tests/test_repr.py
python/cudf/cudf/tests/test_rolling.py
python/cudf/cudf/tests/test_scalar.py
python/cudf/cudf/tests/test_series.py
python/cudf/cudf/tests/test_stats.py
python/cudf/cudf/utils/utils.py

This PR excises some of the functions in `cudf/utils/utils.py` and moves others as close to their point of use as possible. Most of the moved functions were essentially single-use functions, while the removed functions were either unnecessary or had obvious preexisting replacements.

Remove or simplify various utility functions

---

python/cudf/cudf/_lib/merge.pyx
python/cudf/cudf/core/reshape.py

This PR refactors `merge_sorted` in `merge.pyx` to accept a list of columns, contributes to #10153

Cython API refactor: `merge.pyx`

---

cpp/CMakeLists.txt
cpp/cmake/Modules/FindcuFile.cmake
cpp/cmake/thirdparty/get_cufile.cmake
cpp/cmake/thirdparty/get_kvikio.cmake
cpp/cmake/thirdparty/get_nvcomp.cmake

When cudf is built statically we had the following three issues that
could cause consumers to fail to find cudf:
1. kvikio was not setup to be exported properly
2. Removed cuFile dependency when it isn't found
3. Hint where to find nvcomp when built by cudf

Correct build dir `cudf-config` dependency issues for static builds

---

python/cudf/cudf/tests/test_concat.py
python/cudf/cudf/tests/test_indexing.py
python/cudf/cudf/tests/test_multiindex.py
python/cudf/cudf/tests/test_repr.py

Small PR for improving consistency in cuDF Python test names. Follows up from https://github.com/rapidsai/cudf/pull/10729#discussion_r857972566. cc: @galipremsagar

Rename tests from multiIndex to multiindex.

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/main/native/src/ColumnViewJni.cu
java/src/main/native/src/ColumnViewJni.hpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Add generateListOffsets API, converting list lengths to list offsets, which is useful in the development of spark-rapids.
For example, the support of [array_repeat](https://github.com/NVIDIA/spark-rapids/issues/5226) and [arrays_zip](https://github.com/NVIDIA/spark-rapids/issues/5229) relies on this API.

JNI: Add generateListOffsets API

---

docs/cudf/source/user_guide/10min-cudf-cupy.ipynb

This PR updates a `from_dlpack` call that was missed in #10631.

Fix `cupy` function in notebook

---

python/cudf/cudf/api/types.py
python/cudf/cudf/core/dtypes.py

This PR combines a few `isinstance` checks to reduce the complexity of the logic.
Note: Some of these were identified by https://codereview.doctor/rapidsai/cudf. In some places, the bot correctly identified a problem but its suggestions were invalid or incomplete. I identified steps for improvement beyond what the bot suggested for most of these cases.

Improve use of isinstance.

---

python/cudf/cudf/_fuzz_testing/fuzzer.py
python/cudf/cudf/_lib/scalar.pyx
python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/core/dtypes.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/udf/typing.py
python/cudf/cudf/tests/test_multiindex.py
python/cudf/cudf/tests/test_repr.py

This PR uses the canonical builtin function `repr(x)` to compute representations instead of the double-underscored form `x.__repr__()`. The magic method `def __repr__(self): ...` is how a custom representation is defined for a class, but it is not the typical way to call that function. Same for `x.__iter__()` :arrow_right: `iter(x)` and similarly for `__hash__`, `__str__`, etc. This PR fixes all of the instances of that pattern that I could find, mostly affecting `repr(x)`.
Note that non-standard magic methods like `__dlpack__` or `__dataframe__` that are not defined in the Python object model do not necessarily follow this convention where a free function of the same name is used to call those methods.

Use canonical "magic methods" (replace `x.__repr__()` with `repr(x)`).

---

cpp/include/cudf_test/column_wrapper.hpp
cpp/src/io/parquet/page_enc.cu
cpp/src/io/parquet/reader_impl.cu
cpp/src/quantiles/quantile.cu
cpp/src/reshape/interleave_columns.cu
cpp/src/rolling/rolling_collect_list.cuh
cpp/src/strings/copying/concatenate.cu
cpp/tests/partitioning/hash_partition_test.cpp
cpp/tests/rolling/grouped_rolling_test.cpp
cpp/tests/rolling/rolling_test.cpp
cpp/tests/sort/rank_test.cpp
cpp/tests/transform/row_bit_count_test.cu
cpp/tests/unary/cast_tests.cpp

Addresses part of https://github.com/rapidsai/cudf/issues/10350 Take advantage of C++17 feature structured bindings
There are few usages where `std::tie` is used on existing variables and for ordered operator== comparisons. These usages are not replaced.

Use structured bindings instead of std::tie

---

python/cudf/cudf/_lib/cpp/lists/contains.pxd
python/cudf/cudf/_lib/lists.pyx
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/tests/test_list.py

This adds bindings for `index_of` to enable using `list.index` with a Series of search keys.
Closes #10692 
cc: @randerzander

Add bindings for index_of with column search key

---

cpp/include/cudf/strings/detail/scatter.cuh
cpp/src/lists/copying/scatter_helper.cu
cpp/src/strings/utilities.cu
cpp/tests/copying/scatter_tests.cpp

Closes #10717 
Fixes bug introduced with changes in #10673 which uses the `cudf::make_strings_column` that accepts a span of `string_view` objects with a null-placeholder. The placeholder can be unintentionally created in `create_string_vector_from_column` when given a strings column where all the rows are empty. The utility is fixed to prevent creating the placeholder for empty strings.
A gtest was added to scatter from/to an all-empty strings column to verify this behavior.

Fix scatter for all-empty-string column case

---

.pre-commit-config.yaml
python/.flake8
python/cudf/cudf/comm/gpuarrow.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/series.py

This PR enables D30* errors for pydocstyle. It also sets up the `ignore-decorators` configuration so that future PRs involving D10* errors will treat docutils decorators appropriately. Contributes to #10711.

Enable pydocstyle rules involving quotes

---

.pre-commit-config.yaml
python/.flake8
python/custreamz/custreamz/kafka.py

Follow-up to #10748 to enable the base pydocstyle rules on all Python packages (`dask_cudf`, `cudf_kafka`, `custreamz`) and test files. Contributes to #10711, #10758.

Enable pydocstyle for all packages.

---

cpp/benchmarks/io/cuio_common.cpp

Small improvement for the `try_drop_l3_cache` feature in cuIO benchmarks. 
Prevents unflushed output from the original process from intermingling with the output from the `popen` process.

Flush output streams before creating a process to drop caches

---

cpp/src/strings/search/find.cu
cpp/tests/strings/find_tests.cpp

Improves the performance on `cudf::strings::contains()` for long strings. This executes a warp per string to match a target over sections of a single string in parallel. The benchmark showed this to be faster than the current implementation only for longer strings (greater than 64 bytes). It also proved somewhat faster and more consistent than a pure character-parallel approach.
This change may also help improve the performance of the regex `contains_re()` function in the future.

Use warp per string for long strings in cudf::strings::contains()

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_reshape.py
python/dask_cudf/dask_cudf/sorting.py

This PR deprecates non-pandas conform method `cudf.merge_sorted` and change dask cudf usage to internal method `_merge_sorted`.
I also updated msg keyword in pytest.skip in multiple tests to reason, this removes 1000+ test warnings.
cc @vyasr @rjzamora

Deprecate `merge_sorted`, change dask cudf usage to internal method

---

cpp/benchmarks/text/subword.cpp

When porting the subword tokenizer code from CLX, the benchmark was not updated to measure multiple rows. This updates the benchmark to include a row test range and add the missing `cuda_event_timer`.

Add multiple rows to subword tokenizer benchmark

---

python/cudf/cudf/testing/_utils.py
python/cudf/cudf/tests/test_orc.py

This change fixes the deprecation warnings in `test_orc.py`. Fixed warnings:
- parsing timezone aware datetimes is deprecated; this will raise an error in the future
- DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
- FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
- DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
- FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.

Fixing deprecation warnings in test_orc.py

---

cpp/CMakeLists.txt
cpp/include/cudf/lists/detail/stream_compaction.hpp
cpp/include/cudf/lists/stream_compaction.hpp
cpp/src/lists/apply_boolean_mask.cu
cpp/tests/CMakeLists.txt
cpp/tests/lists/apply_boolean_mask_test.cpp
cpp/tests/lists/segmented_test.cu

Fixes #10650.
This commit introduces an `apply_boolean_mask()` method that interprets a boolean `LIST` column as a filter, to select elements from an arbitrary `LIST` input column.
E.g.
```c++
auto const input    = lcw<int32_t>{ {0,1,2}, {3,4}, {5,6,7}, {8,9} };
auto const selector = lcw<bool>   { {0,1,1}, {1,0}, {1,1,1}, {0,0} };
auto const results  = apply_boolean_mask( lists_column_view{input}, lists_column_view{selector} );
// results          == { {1,2}, {3}, {5,6,7}, {} };
```
The `input` and the `boolean_mask` should both have the same number of rows, and each row should have the same number of elements. 
Each output row copies the elements from the input where the boolean mask is non-null and true.

Segmented `apply_boolean_mask` for `LIST` columns

---

cpp/src/join/semi_join.cu

Closes https://github.com/rapidsai/cudf/issues/10464
Updates the `left_semi_join` to materialize the gather mask instead of generating it via a transform iterator.
Including the `map.contains` in the `gather` call reduced occupancy due to increasing register usage. As a result, explicitly materializing the gather mask is faster.

Optimize `left_semi_join` by materializing the gather mask

---

python/cudf/cudf/tests/test_orc.py

@bdice helped me look into an issue with deprecated warnings in #10772 and in the process, he pointed out that the skiprows test was unnecessarily complex. We looked into it some and it appeared to be a copy/paste of a more complex test. He asked that I make this PR to simplify this test, but all the credit for noticing and fixing it is his.

simplifying skiprows test in test_orc.py

---

java/src/main/java/ai/rapids/cudf/HostColumnVectorCore.java

This PR suggests a 3VL way of interpreting `isNull` for a `rowId` out of bounds. Such a value is unknown and therefore isNull should be `true`. 
NVIDIA/spark-rapids#5140 shows that `SpecificUnsafeProjection` may probe child columns for NULL even though the parent column row is also NULL. 
However there are no rows in the child CV when the parent row is NULL leading to an assert violation if asserts are enabled or an NPE if disabled.
Signed-off-by: Gera Shegalov <gera@apache.org>

HostColumnVectoreCore#isNull should return true for out-of-range rows

---

java/src/main/java/ai/rapids/cudf/ColumnView.java

This is an API I would like to use to help a customer with a UDF so I would like to make it public.

Make the JNI API to get list offsets as a view public.

---

docs/cudf/source/conf.py
python/cudf/cudf/core/frame.py

This PR adds `numpy` to the list of intersphinx references, which is needed to cross-reference numpy functions in cuDF's documentation. The Python intersphinx reference was updated to resolve a warning caused by a redirect. This also fixes a reference to `numpy.asarray`, which is a function (not a method).

Add NumPy to intersphinx references.

---

cpp/src/io/utilities/hostdevice_vector.hpp

`hostdevice_vector` members that are used for element access do not return const pointers/references when called on const objects.
This PR makes sure all function members of `hostdevice_vector` are const correct:
- operator[]
- begin
- end
- d_begin
- d_end
- host_ptr
- device_ptr

Fix element access const correctness in `hostdevice_vector`

---

.github/PULL_REQUEST_TEMPLATE.md

Although 2 cpp reviewers are automatically assigned to a PR, there is no documentation that indicates 2 are required. This PR adds to the list of guidelines in the [Pull Request Template](https://github.com/rapidsai/cudf/blob/branch-22.06/.github/PULL_REQUEST_TEMPLATE.md) that appears when a PR is created through the github web page.

Mention 2 cpp-reviewer requirement in pull request template

---

python/cudf/cudf/__init__.py
python/cudf/cudf/core/missing.py
python/cudf/cudf/core/scalar.py
python/cudf/cudf/core/udf/typing.py
python/cudf/cudf/tests/test_udf_masked_ops.py

This PR changes the way things are imported in our scalar code such that it's less prone to circular import issues. For instance before this we can't make `NA` the default value of a kwarg for, say, anything in `column.py`.

Rework `Scalar` imports

---

python/cudf/cudf/tests/test_s3.py
python/dask_cudf/dask_cudf/io/tests/test_s3.py

This is a follow-up PR to address review comments from here: https://github.com/rapidsai/cudf/pull/10769#pullrequestreview-968047334
This PR:

[REVIEW] Use `ThreadedMotoServer` instead of `subprocess` in spinning up `s3` server

---

python/cudf/cudf/_lib/scalar.pyx
python/cudf/cudf/core/_internals/where.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/numerical_base.py
python/cudf/cudf/core/column/struct.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/testing/testing.py
python/cudf/cudf/utils/dtypes.py

This PR changes cuDF so `NA` isn't used around the codebase from the top level `cudf` namespace and rather is imported directly from `missing`. This is part of https://github.com/rapidsai/cudf/issues/10820 and comes as a follow up to https://github.com/rapidsai/cudf/pull/10791#discussion_r867206392

Import `NA` from `missing` rather than using `cudf.NA` everywhere

---

.github/workflows/jni-docker-build.yml

related to https://github.com/NVIDIA/spark-rapids-jni/issues/203
I don't know if any restriction of using github actions in rapids org, 
so this PR is just a prototype and waiting for feedback :)
Example in my forked repo,
1. Manual trigger the build
2. example logs https://github.com/pxLi/cudf/runs/6319840419?check_suite_focus=true
3. pushed images https://hub.docker.com/r/pxli/cudf-jni-build/tags
Some open questions:
1. Trigger strategy? Manual, crontab, merge trigger, or others?
2. which org in docker hub should we push the image to? gpuci?
3. which account we should use to push?
4. do we want to keep the commit tags or we just overwrite the branch-XY tag only? mostly about space :)
Thanks!

Add cudf JNI docker build github action

---

python/cudf/setup.py
python/cudf_kafka/pyproject.toml
python/cudf_kafka/setup.py
python/custreamz/setup.py
python/dask_cudf/setup.py

This PR:
- adds a missing `cuda-python` dependency to cudf's `setup.py`. The package is used here (it is currently being supplied as a transitive dependency of RMM, but we should list all dependencies explicitly): https://github.com/rapidsai/cudf/blob/0cc29a0a0128c5632bd53fd41c0a568929b847ac/python/cudf/cudf/utils/gpu_utils.py#L18
- standardizes declarations of Cython dependencies (it is only a build system dependency in `pyproject.toml`, and never needed at runtime via `install_requires` in `setup.py`)
- standardizes definition of `extras_require` across all included Python packages

Add missing cuda-python dependency to cudf

---

python/dask_cudf/dask_cudf/groupby.py
python/dask_cudf/dask_cudf/tests/test_groupby.py

Converts string `by`-columns to lists when calling aggregation methods, which expect `Groupby.by` to be a list or tuple.
We might be able to do this conversion when initializing the groupby object, just started off with this approach as it seems like upstream Dask is pretty careful not to overwrite the original `by` input if it's a string.
Closes #10829

Add handling for string by-columns in dask-cudf groupby

---

python/cudf/cudf/tests/test_binops.py

Add tests for binaryops between two null scalars as per https://github.com/rapidsai/cudf/pull/10791#discussion_r866305789
This is technically `1307` tests but they only take about 5 seconds to run.

Add tests for null scalar binaryops

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

Contributes to #10650
Add JNI support for `apply_boolean_mask`
Refer to the descriptions of PR #10773
Signed-off-by: Chong Gao <res_life@163.com>

Add JNI support for apply_boolean_mask

---

java/src/main/java/ai/rapids/cudf/Cuda.java
java/src/main/native/src/CudaJni.cpp

Running tests locally, but putting this up as WIP for now.
Discussing with @jlowe a solution to https://github.com/NVIDIA/spark-rapids/issues/4818 could involve `cudaDeviceSynchronize.` I noticed that's not in our JNI exposed calls, so I am adding it here.

Adds the JNI call for Cuda.deviceSynchronize

---

cpp/src/strings/regex/regcomp.cpp
cpp/src/strings/regex/regcomp.h

Cleans up the internal `regcomp::optimize1()` function by replacing for-loops with STL functions. Hopefully this will make this part of the code a bit easier to understand and maintain.
No external function or behavior has changed.

Cleanup regex compile optimize functions

---

cpp/include/cudf/table/experimental/row_operators.cuh

Resolves issues raised in #10730 about `operator()` being `const` and accepting references. cc: @ttnghia @jrhemstad
I applied `const noexcept` across all `operator()`s in the experimental row comparators, to match the existing pattern.

Fix constness / references in weak ordering operator() signatures.

---

cpp/src/io/text/multibyte_split.cu

`sizeof-array-div` is a new warning added in gcc-11 and thrust 1.15 will trigger it when a `T` type is a fixed size array. Nothing is wrong with the thrust logic, so we just suppress the warning while we wait on thrust 1.16

Suppress sizeof-array-div warnings in thrust found by gcc-11

---

python/cudf/cudf/core/column/string.py

There is a typo in ngram() method documentation, consisting in a duplicated assignment.

Remove typo in ngram documentation

---

ci/checks/copyright.py
conda/recipes/libcudf/meta.yaml
cpp/doxygen/Doxyfile
cpp/include/cudf/column/column_device_view.cuh
cpp/include/cudf/table/experimental/row_operators.cuh
cpp/include/cudf/utilities/type_dispatcher.hpp
cpp/include/cudf_test/cxxopts.hpp
cpp/include/nvtext/bpe_tokenize.hpp

This PR fixes 433 doxygen warnings.
As prerequisite for doxygen CI check https://github.com/rapidsai/cudf/issues/9373, the warnings from doxygen should be minimized as much as possible. 
This is one of the series of PRs to fix doxygen documentation warnings.

fix doxygen warnings

---

cpp/src/interop/dlpack.cpp
cpp/tests/interop/dlpack_test.cpp
docs/cudf/source/api_docs/general_functions.rst

The implementation copying a full column at a time relies on
unit-stride, column-major data in the incoming dlpack tensor. Check
these preconditions and report error messages, rather than either
silently producing bad data (unit-stride, row-major 2D tensors) or
invalid memory accesses (non-unit-stride in the fastest-varying
dimension). Closes #10754 by providing an explicit error message for
this unsupported case.

More error checking in `from_dlpack`

---

cpp/src/stream_compaction/distinct.cu
cpp/tests/stream_compaction/distinct_tests.cpp

This PR fixes a bug in `cudf::distinct` where the `Nullate` of the comparator should be determined by whether nested nulls are present.

Fix a bug in `distinct`: using nested nulls logic

---

cpp/tests/stream_compaction/distinct_tests.cpp

This adds more nested types tests for `cudf::distinct`, including cases of `List<Struct<...>>` and `Struct<List<...>>`, and the input columns are sliced.
Partially addresses https://github.com/rapidsai/cudf/issues/10742.

Add more unit tests for `cudf::distinct` for nested types with sliced input

---

cpp/benchmarks/reduction/rank.cpp
cpp/benchmarks/stream_compaction/distinct.cpp
cpp/include/cudf/column/column_device_view.cuh
cpp/include/cudf/lists/list_view.hpp
cpp/src/copying/scatter.cu
cpp/src/interop/dlpack.cpp
cpp/src/io/csv/csv_gpu.cu
cpp/src/io/json/json_gpu.cu
cpp/src/io/text/multibyte_split.cu
cpp/src/lists/lists_column_view.cu

This is a small refactor, changing `list_view.cuh` to `list_view.hpp` as this file only contains the definition of `cudf::list_view` which is an empty class and nothing else.

Changing `list_view.cuh` to `list_view.hpp`

---

cpp/include/cudf/copying.hpp
cpp/include/cudf/datetime.hpp
cpp/include/cudf/io/parquet.hpp
cpp/include/cudf/io/text/data_chunk_source.hpp
cpp/include/cudf/join.hpp
cpp/include/cudf/lists/gather.hpp
cpp/include/cudf/strings/convert/convert_lists.hpp
cpp/include/cudf_test/tdigest_utilities.cuh
cpp/src/binaryop/compiled/binary_ops.cu
cpp/src/io/json/reader_impl.cu
cpp/src/io/orc/orc.h
cpp/src/io/statistics/typed_statistics_chunk.cuh
cpp/src/reductions/scan/scan_inclusive.cu
cpp/src/strings/json/json_path.cu
cpp/src/strings/regex/regcomp.h
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/core/cut.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/join/join.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/subword_tokenizer.py
python/cudf/cudf/io/parquet.py
python/cudf/cudf/testing/_utils.py
python/cudf/cudf/utils/docutils.py
python/dask_cudf/dask_cudf/io/parquet.py

Ran spell check on comments on public facing APIs and fixed them.

[DOC] spell check fixes

---

cpp/src/io/comp/nvcomp_adapter.cpp
cpp/src/io/comp/nvcomp_adapter.hpp
cpp/src/io/parquet/reader_impl.cu
python/cudf/cudf/tests/test_parquet.py

Adds ZSTD compression type to the nvcomp adapter. The zstd header is conditionally included so the code works without nvcomp 2.3.
Test changes:
- nvcomp 2.3 still not used in CI, so almost no test changes;
- Modifies a Python test that assumes the Zstandard is not supported, to also pass if reading is successful.

Support for Zstandard decompression in Parquet reader

---

cpp/include/cudf/lists/lists_column_device_view.cuh
cpp/include/cudf/structs/structs_column_device_view.cuh
cpp/include/cudf/table/experimental/row_operators.cuh

This PR renames the lists/structs device view method `sliced_child` to `get_sliced_child`. This resolves some inconsistent naming (`structs_column_view::get_sliced_child` vs. `structs_column_device_view::sliced_child`). Resolves #10666.

Rename `sliced_child` to `get_sliced_child`.

---

cpp/doxygen/Doxyfile
cpp/include/cudf/scalar/scalar.hpp
cpp/include/cudf/scalar/scalar_device_view.cuh
cpp/include/cudf/scalar/scalar_factories.hpp

fixes part of https://github.com/rapidsai/cudf/issues/9373
Add missing documentation in scalar/ headers to fix doxygen warnings

Add missing documentation in scalar/ headers

---

cpp/src/reductions/segmented_reductions.cpp
cpp/tests/reductions/rank_tests.cpp
cpp/tests/reductions/segmented_reduction_tests.cpp

Fixes `cudf::segmented_reduce` where the input `values` column is empty but the `offsets` are not. In this case, the `offsets` vector `{0,0}` specifies an empty segment which should result in a single null row. The logic has been fixed and new gtest cases have been added.
Closes #10556

Fix segmented_reduce on empty column with non-empty offsets

---

cpp/include/cudf/strings/convert/convert_datetime.hpp
cpp/include/cudf/strings/convert/convert_durations.hpp
cpp/include/cudf/strings/detail/converters.hpp
cpp/include/cudf/strings/padding.hpp
cpp/src/strings/convert/convert_datetime.cu
cpp/src/strings/convert/convert_durations.cu
cpp/src/strings/padding.cu

Follow on to #10810. This changes other occurrences of parameter type `std::string` to `std::string_view` in the non-regex APIs. 
This covers `cudf::strings::pad` fill-char and the to/from-timestamp/duration converters that accept format specifiers.

Change std::string parameters in cudf::strings APIs to std::string_view

---

cpp/include/cudf_test/column_wrapper.hpp
cpp/tests/quantiles/percentile_approx_test.cu
cpp/tests/utilities/column_utilities.cu
cpp/tests/utilities_tests/column_utilities_tests.cpp

Fixes:  https://github.com/rapidsai/cudf/issues/10855
Unsanitary lists (those with null rows that actually have backing underlying data) should not compare as equal to sanitized lists, but _should_ compare as equivalent.   Only one test in cudf was affected by this change, which I've opened a second issue for:
https://github.com/rapidsai/cudf/issues/10856
This PR also adds a utility function to `cudf::test::lists_column_wrapper`, 
`static lists_column_wrapper<T> make_one_empty_row_column(bool valid = true)`
Due to the way initializer lists and nested class initialization work, it was impossible to create a list column with 1 row that was empty, so I added this explicit function to handle the edge case.

Make cudf::test::expect_columns_equal() to fail when comparing unsanitary lists.

---

cpp/include/cudf_test/column_wrapper.hpp
cpp/tests/quantiles/percentile_approx_test.cu
cpp/tests/utilities/column_utilities.cu
cpp/tests/utilities_tests/column_utilities_tests.cpp

Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

---

docs/cudf/source/user_guide/io.md

Based on feedback from GDS team. Using the full name "Magnum IO GPUDirect Storage".

Use full name of GPUDirect Storage SDK in docs

---

cpp/include/cudf/table/experimental/row_operators.cuh

This PR adds documentation for strongly-typed index iterators. Requested by @vyasr.

Add strong index iterator docs.

---

conda/environments/cudf_dev_cuda11.5.yml

Dependent on: https://github.com/rapidsai/cudf/pull/10275
This PR adds required `conda` compilers in the environment file

[REVIEW] Use `conda` compilers in env file

---

python/cudf/cudf/core/indexed_frame.py

This clarifies that the deprecated `append` method is replaced by a top-level function `cudf.concat`. This has caused some user confusion, because it's not just a name change (`DataFrame.concat` doesn't exist).

Clarify append deprecation notice.

---

conda/environments/cudf_dev_cuda11.5.yml

As part of conda compiler migration https://github.com/rapidsai/cudf/pull/10275/ we switched to `9.x`, this PR removed `9.3` requirement and switches it `9.x`. This is because the following error is seen some machines:
```
Encountered problems while solving.
Problem: package gcc_linux-64-9.3.0-h44160b2_26 requires gcc_impl_linux-64 9.3.0.*, but none of the providers can be installed
```
Upgrading to `9.4.0` on those machines works fine. CI too picks up `9.4.0`, for ex: https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build-arm64/CUDA=11.5/4654/consoleText, hence fixes the broken dev environments.

[REVIEW] Fix `gcc_linux` version pinning in dev environment

---

cpp/benchmarks/common/generate_input.hpp

This PR fixes a missing include in `generate_input.hpp` that prevents benchmarks from building with GCC 11.

Include <optional> for GCC 11 compatibility.

---

java/src/main/java/ai/rapids/cudf/JCudfSerialization.java

to be usable in different packages of spark-rapids to address 
NVIDIA/spark-rapids#5513
Signed-off-by: Gera Shegalov <gera@apache.org>

Make SerializedTableHeader(numRows) public

---

cpp/include/cudf/detail/copy_if_else.cuh
cpp/include/cudf/types.hpp

Fixes parts of https://github.com/rapidsai/cudf/issues/9373
added missing documentation in types.hpp to fix doxygen warnings
fixes 30 warnings

Add missing documentation in cudf/types.hpp

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #10954 
This PR fixes the conversion of a single column `MultIndex` into `Index` in `sort_index`.

[REVIEW] Fix single column `MultiIndex` issue in `sort_index`

---

cpp/include/cudf/detail/null_mask.cuh
cpp/include/cudf/detail/null_mask.hpp
cpp/src/bitmask/null_mask.cu
cpp/src/reductions/simple_segmented.cuh
cpp/src/structs/utilities.cpp

Closes #10763
This PR removed `mr` parameter from inplace bitmask operations by following [guidance for temporary memory allocation](https://github.com/rapidsai/cudf/blob/branch-22.06/cpp/docs/DEVELOPER_GUIDE.md#temporary-memory).

Removed `mr` parameter from inplace bitmask operations

---

cpp/src/io/comp/nvcomp_adapter.cpp
python/cudf/cudf/tests/test_orc.py
python/cudf/cudf/tests/test_parquet.py

Closes #9055
Limiting due to known nvcomp issues.

Enable Zstandard decompression only when all nvcomp integrations are enabled

---

python/cudf/cudf/core/dtypes.py
python/cudf/cudf/tests/test_dtypes.py

Since v1.3, `pandas.IntervalDtype` also has a `closed` property, so handle that in `IntervalDtype.from_pandas`.
While we're here, add a more reasonable hash and equality (rather than deferring to `StructDtype`), fixing the previous behaviour that:
```python
from cudf import IntervalDtype
dt1 = IntervalDtype("int32", "both")
dt2 = IntervalDtype("int32", "right")
dtypes = set([dt1, dt2])
print(len(dtypes)) => 1
```

Handle closed property in IntervalDtype.from_pandas

---

ci/benchmark/build.sh
ci/gpu/build.sh
conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/custreamz/meta.yaml
conda/recipes/dask-cudf/meta.yaml
python/dask_cudf/setup.py

This PR pins `dask` & `distributed` for `22.06` release.

[REVIEW] Pin `dask` & `distributed` for release

---

cpp/src/io/parquet/page_enc.cu
cpp/src/io/parquet/parquet_gpu.hpp
cpp/tests/io/parquet_test.cpp

Added special handling for list cases where empty lists have empty offsets. Generally the size of offsets column in a list column is list column size + 1. For empty list columns, offsets are allowed to be empty instead of size 1. This caused issues in processing lists in the parquet writer.
This PR makes use of the `list_column_device_view` wrapper to handle this case wherever possible and replaces empty list columns with a temporary list column with offset of size 1 where `list_column_device_view` could not be used.
Fixes #10536

Fix the issue of empty lists having empty offsets

---

python/dask_cudf/dask_cudf/backends.py

This PR registers uses the (presumably shortly merged) dask `Grouper` dispatch to register `cudf.core.groupby.Grouper` objects to `cudf.DataFrame` objects. This should allow our own Grouper objects to be used in critical places in dask rather than pandas objects. 
This solution is favorable IMO rather than changing cuDF to handle pandas grouper objects directly. 
Xref https://github.com/dask/dask/pull/9074

Register `cudf.core.groupby.Grouper` objects to dask `grouper_dispatch` 

---

conda/recipes/libcudf/meta.yaml

A duplicate appears to have been added, perhaps during merge conflict resolution.

Remove extra instance of list_view.hpp in meta.yaml.

---

ci/cpu/build.sh
ci/gpu/build.sh

Use `mambabuild` to build `conda` packages. This should speed up the builds and help to debug `conda` conflict issues

Use mambabuild to build conda packages

---

python/dask_cudf/dask_cudf/backends.py

Backport of https://github.com/rapidsai/cudf/pull/10838

Register `cudf.core.groupby.Grouper` objects to dask `grouper_dispatch`

---

cpp/benchmarks/io/csv/csv_reader.cpp
cpp/benchmarks/io/csv/csv_writer.cpp
cpp/benchmarks/io/parquet/parquet_reader.cpp
cpp/benchmarks/io/parquet/parquet_writer.cpp

Adds duration columns to benchmarks of the formats that support these types (everything except ORC).

Add missing cuIO benchmark coverage for duration types

---

.gitignore
build.sh
ci/gpu/build.sh
ci/release/update-version.sh
conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/build.sh
conda/recipes/cudf/conda_build_config.yaml
conda/recipes/cudf/meta.yaml
cpp/CMakeLists.txt
python/cudf/CMakeLists.txt
python/cudf/cudf/_lib/CMakeLists.txt
python/cudf/cudf/_lib/io/CMakeLists.txt
python/cudf/cudf/_lib/nvtext/CMakeLists.txt
python/cudf/cudf/_lib/strings/CMakeLists.txt
python/cudf/cudf/_lib/strings/convert/CMakeLists.txt
python/cudf/cudf/_lib/strings/split/CMakeLists.txt
python/cudf/cudf/core/join/join.py
python/cudf/pyproject.toml
python/cudf/setup.py

This PR changes the Python build system for cudf to use scikit-build and leverage CMake under the hood.
This PR depends on rapidsai/rapids-cmake#198. Once that PR is merged, I can update the pull of rapids-cmake into the cudf Python CMake build.

Enable builds with scikit-build

---

cpp/src/io/orc/orc.cpp
cpp/src/io/orc/orc.hpp
cpp/src/io/orc/stripe_init.cu
python/cudf/cudf/tests/test_orc.py

Issue #10755
Fixes an issue in protobuf writer where the length on the row index entry was being written into a single byte. This would cause errors when the size is larger than 127.
The issue was uncovered when row group statistics were added. String statistics contain copies to min/max strings, so the size is unbounded.
This PR changes the protobuf writer to write the entry size as a generic uint, allowing larger entries.
Also fixed `start_row` in row group info array in the reader (unrelated).

Fix a row index entry error in ORC writer issue

---

cpp/src/groupby/sort/group_correlation.cu
cpp/tests/groupby/covariance_tests.cpp

This PR changes a requirement to ensure that both value inputs to a sort-groupby covariance computation are convertible to double.

Fix grouped covariance to require both values to be convertible to double.

---

cpp/benchmarks/fixture/rmm_pool_raii.hpp
cpp/include/cudf/detail/copy.cuh
cpp/include/cudf/detail/copy_range.cuh
cpp/include/cudf/detail/groupby.hpp
cpp/include/cudf/dictionary/detail/iterator.cuh
cpp/include/cudf/dictionary/detail/merge.hpp
cpp/include/cudf/dictionary/detail/search.hpp
cpp/include/cudf/dictionary/search.hpp
cpp/include/cudf/lists/lists_column_factories.hpp
cpp/include/cudf/strings/detail/convert/fixed_point.cuh
cpp/include/cudf/strings/detail/merge.cuh
cpp/include/cudf/strings/detail/strings_column_factories.cuh
cpp/include/cudf/utilities/type_checks.hpp
cpp/tests/iterator/optional_iterator_test.cuh
cpp/tests/iterator/pair_iterator_test.cuh
cpp/tests/iterator/value_iterator_test.cuh
cpp/tests/reductions/list_rank_test.cpp

This PR adds  the missing `#pragma once` in few header files in libcudf.
minor include cleanup "" to <>

Add missing #pragma once to header files

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/meta.yaml
python/cudf/setup.py

Fixes: #10990 
This PR pins the` protobuf` version to the latest and chooses narrower pinning because of the lower likelihood of breaking API changes between minor patch versions as opposed to major version changes.

[REVIEW] Pin `protobuf` version

---

conda/recipes/cudf/meta.yaml
conda/recipes/cudf_kafka/meta.yaml
conda/recipes/custreamz/meta.yaml
conda/recipes/dask-cudf/meta.yaml
conda/recipes/libcudf/meta.yaml

This PR fixes warning C1115 from conda-build and conda-verify in the package recipes.
```
tmp/tmpuvqmv1nw/dask-cudf-22.06.00a-cuda_11_py39_g425f2c4930_298.tar.bz2: C1115 Found invalid license "Apache" in info/index.json
```
For context, conda-build does some normalization of the license family (converting it to all caps) but conda-verify does not perform the same normalization.
- https://github.com/conda/conda-build/blob/1ed8da062f123e1fbca604df26b064b267a3d094/conda_build/license_family.py#L108
- https://github.com/conda/conda-verify/blob/f89feaa0d93c6c3f71ce9c2418b28ca5aef53127/conda_verify/checks.py#L248

Fix license families to match all-caps expected by conda-verify.

---

cpp/src/io/orc/orc.cpp
cpp/src/io/orc/orc.hpp
cpp/src/io/orc/stripe_init.cu
python/cudf/cudf/tests/test_orc.py

Issue #10755
Backporting the fix to 22.06
Fixes an issue in protobuf writer where the length on the row index entry was being written into a single byte. This would cause errors when the size is larger than 127.
The issue was uncovered when row group statistics were added. String statistics contain copies to min/max strings, so the size is unbounded.
This PR changes the protobuf writer to write the entry size as a generic uint, allowing larger entries.
Also fixed `start_row` in row group info array in the reader (unrelated).

Fix a row index entry error in ORC writer issue (#10989)

---

cpp/include/cudf/ast/expressions.hpp
cpp/include/cudf/dictionary/dictionary_column_view.hpp
cpp/include/cudf/rolling/range_window_bounds.hpp
cpp/include/cudf/tdigest/tdigest_column_view.cuh
cpp/include/cudf/wrappers/dictionary.hpp
cpp/include/cudf/wrappers/timestamps.hpp

Fixes parts of https://github.com/rapidsai/cudf/issues/9373
added missing documentation to fix doxygen warnings in multiple files
ast/, rolling, tdigest/, wrappers, dictionary/ headers
fixes 82 warnings.

Fix doxygen warnings in ast/, rolling, tdigest/, wrappers/, dictionary/ headers

---

cpp/include/cudf/fixed_point/fixed_point.hpp

Fixes parts of https://github.com/rapidsai/cudf/issues/9373
added missing documentation to fix doxygen warnings in `fixed_point/fixed_point.hpp`
fixes some existing docstrings.
fixes 47 warnings.

Fix doxygen warnings in fixed_point.hpp

---

docs/cudf/source/api_docs/general_functions.rst
python/cudf/cudf/__init__.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_reshape.py

This removes the public API of `cudf.merge_sorted`. This has been replaced by an internal API and does not need to be exposed in the cudf public API. Deprecated in #10713.

Remove public API of cudf.merge_sorted.

---

docs/cudf/source/api_docs/window.rst
python/cudf/cudf/_lib/rolling.pyx
python/cudf/cudf/core/window/rolling.py

This PR adds missing documentation for rolling var, std, count. Resolves #10665.

Add docs to rolling var, std, count.

---

build.sh
ci/gpu/build.sh
conda/recipes/cudf/build.sh

#10919 changed the Python build system to build its own internal copy of libcudf when invoked directly. It also modified our build.sh script (and associated CI scripts) accordingly so that everywhere that should be reusing a C++ build for a Python build would do so via CMake. This PR makes that behavior the default in build.sh, so any builds of the Python library using build.sh will revert to the prior behavior of searching for a C++ library and failing if one doesn't already exist on the path. Users can still provide the appropriate CMake arguments to the build.sh invocation to make it build libcudf within cuDF Python if they so desire.
Additionally, this PR avoids shadowing the `CMAKE_ARGS` environment variable in build.sh, which is important for conda-forge compatibility.

Change build.sh to find C++ library by default and avoid shadowing CMAKE_ARGS

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py

This PR fixes some documentation links to use rST format so they render correctly in the docs.

Fix docs for Numba UDFs.

---

python/cudf/cudf/_lib/cpp/io/parquet.pxd
python/cudf/cudf/_lib/parquet.pyx
python/cudf/cudf/tests/test_parquet.py
python/cudf/cudf/utils/ioutils.py

Closes https://github.com/rapidsai/cudf/issues/10978
Minor changes (and test coverage) to add `row_group_size_bytes` and `row_group_size_rows` arguments to `ParquetWriter` API.

Expose row-group size options in cudf ParquetWriter

---

cpp/src/text/subword/bpe_tokenizer.cu

Closes #11049 
Fix setting output size value for null and empty input strings in byte-encoding algorithm in the BPE API. The `byte_pair_encoding_fn` kernel is performing several calculations including the output encoding size. This was not properly setting the output size to 0 for null and empty strings. These need to zero to eventually compute the output offsets correctly.

Fix BPE uninitialized size value for null and empty input strings

---

cpp/doxygen/Doxyfile

A [doxygen tag file](https://www.doxygen.nl/manual/external.html) is a compact representation of entries in the doxygen documentation. Doxygen can generate tag files and read tag files from external sources. Local test shows that including tag file for libcudf does not have visible impact on build time and the tag file size is manageable (~126KB).
This is similar to rmm tag file: 
https://github.com/rapidsai/rmm/blob/c49493dea6caf7e8c840b1c83f20caa50de92d5f/doxygen/Doxyfile#L2084

Generate Doxygen Tag File for Libcudf

---

docs/cudf/source/api_docs/series.rst
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_series.py

Resolves: #10443 
This PR adds `between` API for `Series`. Here is the reference pandas API: https://pandas.pydata.org/docs/reference/api/pandas.Series.between.html

[REVIEW] Add support for `Series.between`

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

I believe this should close #11067, but I'm unable to reproduce the original bug locally. Will report back here once I'm able to do that.
Edit: it does.

Maintain the input index in the result of a groupby-transform

---

cpp/tests/utilities/column_utilities.cu
cpp/tests/utilities_tests/column_utilities_tests.cpp

Top level row counts were being compared incorrectly for the `_equivalent()` check.   No tests were affected by this, thankfully.  In addition, even though `_equal()` was correct, I made the same modification to the call (passing separate index lists for the two columns) to future-proof against internal changes to the comparison function.

Fix bug with row count comparison for expect_columns_equivalent().

---

cpp/src/io/comp/nvcomp_adapter.cpp
cpp/src/io/comp/nvcomp_adapter.cu
cpp/src/io/comp/nvcomp_adapter.cuh
cpp/src/io/comp/nvcomp_adapter.hpp
cpp/src/io/orc/orc_common.hpp
cpp/src/io/orc/stripe_enc.cu
cpp/src/io/orc/stripe_init.cu
cpp/src/io/orc/writer_impl.cu
cpp/src/io/orc/writer_impl.hpp
python/cudf/cudf/_lib/cpp/io/types.pxd
python/cudf/cudf/_lib/orc.pyx
python/cudf/cudf/tests/test_orc.py
python/cudf/cudf/utils/ioutils.py

Closes https://github.com/rapidsai/cudf/issues/11023
Expands the nvcomp adapter to cover compression. Supports SNAPPY and ZLIB.
Moves the ORC writer nvcomp compression from `stripe_enc.cu` to the adapter and add ZLIB support.
Adds padding to compressed blocks in writer to ensure alignment of output pointer alignment that is required for nvcomp ZLIB compression.
Minor changes:
- Make page/block/chunk naming consistent in the nvcomp adapter -> always use chunk (to match nvcomp).
- Rename members of `batched_args` so it also makes sense for compression.

Support for ZLIB compression in ORC writer

---

build.sh
java/ci/build-in-docker.sh

#10884 added a test that generates a CUDA fatal error, requiring a separate JVM process to avoid the error leaking into subsequent tests.  There are some CI scripts that are selecting all tests and then deselecting some, and this new test needs to be also excluded to avoid running it in the same JVM as other tests.

Exclude CudaFatalTest when selecting all Java tests

---

cpp/cmake/Modules/FindcuFile.cmake

We shouldn't presume that the CUDA Toolkit is always installed at /usr/local/cuda. Instead we use use `find_package(CUDAToolkit)` to find the correct location.

FindcuFile now searches in the current CUDA Toolkit location

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This PR adds Java method for getting values for a list of keys
fixes #10818

[Java] Added JNI for getMapValueForKeys

---

cpp/include/cudf/io/parquet.hpp
cpp/src/io/comp/nvcomp_adapter.cuh

Some recently merged PRs (https://github.com/rapidsai/cudf/pull/11018 + https://github.com/rapidsai/cudf/pull/11036) do not include enough header which may cause compile error in some systems (in particular, CUDA 11.7 + gcc-11.2). This PR adds the missing header (`<optional>`) to fix the compile issue.

Fix compile error due to missing header

---

java/src/main/native/src/row_conversion.cu

Spent some time investigating performance on column to row and row to column conversion code. Lots of wins here. Split PR up, so this is column to row work only. Row to column to follow. Also, planning to add tests and benchmarks into `spark-rapids-jni` once this is all updated.
```
Comparing 22.08/ROW_CONVERSION_BENCH to mwilson/column_to_row_optimization/ROW_CONVERSION_BENCH
Benchmark                                                                               Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
RowConversion/old_to_row_conversion/1048576/manual_time …
```

column to row refactor for performance

---

.dockerignore
.github/CODEOWNERS
MANIFEST.in
cpp/.clang-tidy

This PR removes the outdated files `.dockerignore` and `MANIFEST.in`. The Dockerfile was removed in #10069 so we don't need to keep the ignore file around anymore. The `MANIFEST.in` is very old (last updated in 2018, cad899bb9516c173e4b07bd48e8e7b5e10ca412d) and no longer correct for the current package structure.
Finally, I moved `.clang-tidy` into the `cpp/` directory. @codereport said that would be fine to clean up from the root and have no negative effects since clang-tidy isn't being run yet.

Clean up repo root

---

cpp/docs/DEVELOPER_GUIDE.md

The developer guide references a `scalar_view` class that does not exist. This PR removes that reference.
See #6558 for the rationale of why no such class exists.

Remove docs mentioning scalar_view since no such class exists.

---

docs/cudf/source/conf.py
python/cudf/cudf/tests/test_parquet.py

Needed for Sphinx 5 compatibility. Should fix the following warning occurring in doc builds.
```
Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
```
xref: https://github.com/sphinx-doc/sphinx/pull/10481

[REVIEW] Switch `language` from `None` to `"en"` in docs build

---

cpp/cmake/thirdparty/get_cucollections.cmake

This ensures that a consistent cuco version is used across all of RAPIDS. See https://github.com/rapidsai/rapids-cmake/pull/201.

Update get_cucollections to use rapids-cmake

---

python/cudf/cudf/core/frame.py
python/cudf/cudf/core/indexed_frame.py

This PR introduces a small new utility function `_from_data_like_self` to provide an additional hook for `Frame` and `IndexedFrame` to customize `_from_data`. Specifically in instances where the outputs need to share the index of the input for `IndexedFrame` methods, this hook provides the necessary entrypoint. This method is analogous to the already existing `_from_columns_like_self` method.
In the past I made efforts to consolidate our factory methods, and I'm not super happy with proliferating more of them again. However, I think in this case it is worth the tradeoff since this gets us very close to our goal of removing the `_index` attribute from the `Frame` class. Moreover, in the intermediate term I expect both this method and `_from_data` to be subsumed by `_from_columns` when we …

Add new `_from_data_like_self` factory

---

cpp/tests/hashing/hash_test.cpp

This PR refactors the libcudf Spark hashing tests to include reproducible Scala snippets and clarify feature/test coverage by splitting up a large test.
This is a precursor to implementing list support for Spark hashing #10378.

Refactor Spark hashing tests

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_concat.py

This PR fixes the two main issues that crop up in pandas 1.4.3 relative to 1.4.2, both around `pd.concat`:
- Columns are now sorted such that integer values come before string values. That is a behavior change that we mimic.
- When multiple objects with identical RangeIndexes are concatenated along axis 1 and sorting is requested, pandas now creates an integer index instead of a RangeIndex. This is not what we want since it increases memory pressure, so those tests have been modified to stop checking the index type and a [pandas issue has been raised](https://github.com/pandas-dev/pandas/issues/47501).

Fix compatibility issues with pandas 1.4.3

---

python/cudf/cudf/_fuzz_testing/io.py
python/cudf/cudf/_lib/sort.pyx
python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_column.py
python/cudf/cudf/tests/test_concat.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_groupby.py
python/cudf/cudf/tests/test_interpolate.py
python/cudf/cudf/tests/test_list.py
python/cudf/cudf/tests/test_onehot.py
python/cudf/cudf/tests/test_parquet.py
python/cudf/cudf/tests/test_replace.py
python/cudf/cudf/utils/utils.py

This PR refactors a few Python statements like `True if x else False` to just be `x`, (or `bool(x)` if a type conversion is needed).
Similar for `False if x else True` ➡️ `not x` (for these, no explicit type conversion is needed since the unary `not` will convert to bool).

Refactor inline conditionals.

---

python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_binops.py

The logic for aligning the indexes of two Series objects with a repeated value of the index is broken. We previously introduced an optimization that avoids a join operation, but unfortunately, that doesn't work in every situation, as seen in https://github.com/rapidsai/cudf/issues/11094. This PR removes that special-casing.
Closes #11094

Fix index alignment for Series objects with repeated index

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/meta.yaml
python/cudf/setup.py

Pin max version of `cuda-python` to `11.7.0`

Pin max version of `cuda-python` to `11.7.0`

---

python/cudf/cudf/core/column/methods.py
python/cudf/cudf/core/column/string.py

Various methods of StringMethods create a Frame from a libcudf method and pass that up to `_return_or_inplace`, which handles this as a special case where a method operating on a single column returns multiple columns (e.g. splitting a string column into multiple columns containing substrings). In all such cases, there is no need to pass the index through. When the parent object is an index, the index can simply be discarded, while if the parent is a Series the parent's index is always used for the new object. This removes various unnecessary constructions of the Frame class.

Remove usage of Frame in StringMethods

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py

This PR moves index-related logic from `Frame._copy_type_metadata` into the `IndexedFrame` override. It also removes all reference to the index parameter from the corresponding methods of various index types.

Clean up _copy_type_metadata

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/join/_join_helpers.py
python/cudf/cudf/core/join/join.py

This PR un-deprecates the `BaseIndex.join` method, which was erroneously deprecated, but reimplements it by converting the index objects to DataFrames under the hood. This reimplementation allows us to simplify much of the internals around merging, providing a single main code path implemented only for DataFrames. The behavior of `cudf.merge(Series, DataFrame)` is preserved via an explicit upcast as well. These changes allow further simplification of the (currently extremely complex) internals of merging, which hopefully will eventually allow us to extract a fast and simple merge function for internal use from the complexities of the public DataFrame.merge API. This change also removes any vestigial accesses to the Frame._index to enable us to remove that.

Standardize join internals around DataFrame

---

java/pom.xml
java/src/main/java/ai/rapids/cudf/MemoryCleaner.java

Contributes to https://github.com/NVIDIA/spark-rapids/issues/5854
Prints `RapidsHostMemoryStore.pool` leaked error log when running Rapids Accelerator test cases.
```
All tests passed.
22/06/27 17:45:57.298 Thread-7 ERROR HostMemoryBuffer: A HOST BUFFER WAS LEAKED (ID: 1 7f8557fff010)
22/06/27 17:45:57.303 Thread-7 ERROR MemoryCleaner: Leaked host buffer (ID: 1): 2022-06-27 09:45:16.0171 UTC: INC
java.lang.Thread.getStackTrace(Thread.java:1559)
ai.rapids.cudf.MemoryCleaner$RefCountDebugItem.<init>(MemoryCleaner.java:301)
ai.rapids.cudf.MemoryCleaner$Cleaner.addRef(MemoryCleaner.java:82)
ai.rapids.cudf.MemoryBuffer.incRefCount(MemoryBuffer.java:232)
ai.rapids.cudf.MemoryBuffer.<init>(MemoryBuffer.java:98)
ai.rapids.cudf.HostMemoryBuffer.<init>(HostMemoryBuffer.java:196) …
```

Provides a method for the user to remove the hook and re-register the hook in a custom shutdown hook manager

---

cpp/benchmarks/common/generate_input.cu

Issue #11204 
The new GPU-accelerated data generator does not account for run length when cardinality is not set.
This PR changes the logic so that the columns with correct average run length are generated even without specific cardinality.

Generate benchmark data with correct run length regardless of cardinality

---

cpp/src/io/comp/nvcomp_adapter.cpp

Needed due to an issue in nvCOMP 2.3.1 and 2.3.2.
nvCOMP integration falls back to `nvcompBatchedDeflateDecompressGetTempSize` when GetTempSizeEx is not available and for DEFLATE. Once DEFLATE issue is fixed, we'll condition GetTempSizeEx use on the nvCOMP version.

Avoid using `nvcompBatchedDeflateDecompressGetTempSizeEx` in cuIO

---

cpp/docs/DEVELOPER_GUIDE.md
docs/cudf/source/user_guide/data-types.md
docs/cudf/source/user_guide/pandas-comparison.md
python/custreamz/README.md

Fixes unresolved links in Markdown files
Ran `xrefcheck` and found few issues. 
At this point, It cannot be fully automated using xrefcheck because the .ipynb files are converted to html and their links are reported as errors

Fix unresolved links in markdown

---

java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

Java binding has `dropDuplicates` API to remove duplicate rows from a table. Previously it has been implemented by sorting the table then calling to `cudf::unique`. This PR changes the implementation to use `cudf::distinct` directly, which can significantly improve performance by avoiding sorting the input table.

Use `cudf::distinct` in Java binding

---

cpp/src/io/parquet/page_enc.cu
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/writer_impl.cu
cpp/src/io/parquet/writer_impl.hpp

Closes #10857 
The current behaviour of parquet writer is to get the estimate for maximum page compressed size by first finding the maximum page size and using nvcomp's `nvcompBatchedSnappyCompressGetMaxOutputChunkSize` API once for the largest page. The total output memory is allocated for max_compressed_page_size * num_pages.
This approach is pessimistic and over-allocates output buffer for batched compression.
This PR changes this to call `nvcompBatchedSnappyCompressGetMaxOutputChunkSize` for each page and sum up the result to get the output buffer size. This greatly reduces the peak memory consumption of parquet writer so the compression step is no longer the bottleneck.

Use per-page max compressed size estimate for compression

---

cpp/tests/rolling/empty_input_test.cpp

This PR fixes a small bug in `tests/rolling/empty_input_test`, which inconsistently occurs at some unknown points, on some unknown machine configuration, in some unknown situations:
```
C++ exception with description "parallel_for failed: cudaErrorInvalidDeviceFunction: invalid device function" 
thrown in the test body.
```
The bug is subtle and is due to creating data columns in static variables. Since the static variables are initialized first upon program startup, the GPU memory hold by these variables may be allocated outside of `rmm`, leading to undefined behavior.

Fix `tests/rolling/empty_input_test`

---

cpp/src/lists/copying/scatter_helper.cu

Fixes:  https://github.com/rapidsai/cudf/issues/11248
A transform iterator was calling `copy_bitmask()` to create a new `rmm::device_buffer` as a temporary.  The pointer from this was being stored in a `lists_column_view`, but the underlying temporary was being deleted immediately.  
The copy is unnecessary because the backing bitmask is coming from column views that have a safe lifetime for the duration of the operation.  So the fix is to just pass the original pointers along.

Fix a memory aliasing/crash issue in scatter for lists.

---

.pre-commit-config.yaml

Deprecated APIs should be announced with FutureWarning, check that
changes don't accidentally introduce DeprecationWarning using a regular
expression that is hopefully specific enough. Closes #11251.

Ensure DeprecationWarnings are not introduced via pre-commit

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_concat.py

fixes #11244 
When concatenating along axis 1, pandas always return a dataframe even though there are only 1 column involved. This PR conforms cuDF to that behavior.

Returns DataFrame When Concating Along Axis 1

---

conda/recipes/cudf/meta.yaml

Some of our nightly builds were failing with the error message (i.e. [here](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/branches/job/cudf-gpu-build-branch-22.08/63/CUDA=11.5/console)):
```
The reported errors are:
- Encountered problems while solving:
- nothing provides requested libcudf 22.08.00a
```
Adding an `=` before `libcudf` in the `cudf/meta.yaml` file seemed to resolve this problem for me locally.

Fix `cudf` recipe

---

conda/recipes/cudf_kafka/meta.yaml
conda/recipes/custreamz/meta.yaml
conda/recipes/dask-cudf/meta.yaml

#11267 seemed to fix some of the nightly build issues we've been experiencing, but there are other recipes that need to be updated as well.

Fix `cudf` recipes syntax

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_joining.py

Add NotImplementedError when on is specified in DataFrame.join.

---

python/cudf/cudf/core/frame.py

Closes https://github.com/rapidsai/cudf/issues/9328

Note null behavior in `where` docs

---

cpp/src/search/contains_table.cu
cpp/tests/join/semi_anti_join_tests.cpp

When hashing elements in a column, the nullable information needs to be taken into account. This could produce different results for the hash values of the same elements if the nullable condition is changed. As such, whenever we need to compute hashing for more than one column/table in the same operation, we need to take into account the nullable of all columns/tables, not just the one that is being hashed.
This PR fixes a bug when hashing two tables using different nullable values in `cudf::detail::contains`, which led to incorrect results when there is only one nullable table in the input.

Fix inconsistency when hashing two tables in `cudf::detail::contains`

---

conda/environments/cudf_dev_cuda11.5.yml

A new version of `pytorch` has been released, `1.12.0`. This version's packages don't statically link to `libcupti`(More explanation on that [here](https://github.com/pytorch/vision/issues/5635)). Until that is patched, we are going to run into the `libcupti` not found error: https://github.com/pytorch/pytorch/issues/74473#issuecomment-1187705802

[REVIEW] Pin `pytorch` to temporarily unblock from `libcupti` errors

---

docs/cudf/README.md
docs/cudf/source/developer_guide/documentation.md
docs/cudf/source/developer_guide/index.md

This PR adds a page describing how to write documentation for cuDF.

Add dev docs for documentation writing

---

cpp/tests/copying/utility_tests.cpp

Fixes:  https://github.com/rapidsai/cudf/issues/11247
These tests were using `cudf::test::expect_column_properties_equal()` which explicitly compares null counts.  However the tests were using uninitialized memory for the null mask, so it experienced random failures depending on what was returned from the memory manager.   The fix is to simply use a custom set of checks specific to these tests rather than the internal cudf functionality.

Fix invalid allocate_like() and empty_like() tests.

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/java/ai/rapids/cudf/TableWithMeta.java
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This just adds in a simple JNI binding for the join_strings cudf function.

Add JNI support for the join_strings API

---

cpp/tests/error/error_handling_test.cu

This change should make the test fail reliably, whereas the current approach is flaky and leads to not infrequent test failures.

Switch death test to use explicit trap.

---

cpp/CMakeLists.txt
cpp/tests/CMakeLists.txt

Resolves #3036 by making `make test` or `ninja test` default to showing output when tests fail.

Add --output-on-failure to ctest args.

---

cpp/src/binaryop/compiled/operation.cuh

Fixes a compile warning was introduced in PR #11025 : [link to log containing the warning](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/10790/consoleFull)
When a templated variable `y` is unsigned the compare `(y<0)` results in a compile warning:
```
/cudf/cpp/src/binaryop/compiled/operation.cuh(226): warning #186-D: pointless comparison of unsigned integer with zero
detected during:
instantiation of "auto cudf::binops::compiled::ops::IntPow::operator()(TypeLhs, TypeRhs)->TypeLhs [with TypeLhs=uint8_t, TypeRhs=uint8_t, <unnamed>=(void *)nullptr]"
```
Adding an `if constexpr` around the comparison removes the warning.

Fix unsigned-compare compile warning in IntPow binops

---

cpp/include/cudf/lists/stream_compaction.hpp
cpp/include/doxygen_groups.h

This PR follows up on #11149 to add the lists filtering (stream compaction) APIs to a doxygen group. The previous doxygen group `lists_drop_duplicates` is empty after #11326.

Add lists filtering APIs to doxygen group.

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/index.py
python/cudf/cudf/tests/test_datetime.py
python/cudf/cudf/tests/test_timedelta.py

Closes #11335 
This PR fixes an issue with `DatetimeIndex` & `TimedeltaIndex` where the underlying columns would still be of numeric or string types rather than `DatetimeColumn` and `TimedeltaColumn` respectively. This is the actual root cause that leads to errors in some downstream API calls.

[REVIEW] Fix `DatetimeIndex` & `TimedeltaIndex` constructors

---

cpp/benchmarks/io/text/multibyte_split.cpp
cpp/src/io/text/multibyte_split.cu

Improve's the performance of `multibyte_split` by converting one giant `get_next_chunk` read in to multiple smaller `get_next_chunk` reads, preventing the pinned host memory buffer from resizing, which was taking a very long time.
before:
after:

Improve multibyte_split performance

---

cpp/include/cudf/io/types.hpp
cpp/src/io/parquet/page_enc.cu
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/writer_impl.cu
cpp/src/io/parquet/writer_impl.hpp
cpp/tests/io/parquet_test.cpp

Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/series.py

This PR resolves #9038. Not all the remaining functions could be consolidated (for various reasons), but the combination was explored and where necessary the reasons not to combine the functions was documented in that issue. Some additional cleanup that was done during the exploration is also included in this PR, but ultimately `groupby` is the only method that was moved up to `IndexedFrame`.

Consolidate remaining DataFrame/Series APIs

---

python/cudf/cudf/core/column/lists.py
python/cudf/cudf/tests/test_list.py

This PR fixes the `memory_usage()` call for `ListSeries`. This is a bugfix. https://www.github.com/rapidsai/cuspatial/pull/585 depends on this. Perhaps it can get into `branch-22.08`?
Fixes #11346.

Fix memory_usage() for `ListSeries`

---

conda/environments/cudf_dev_cuda11.5.yml

This PR fixes timeouts like the following that are happening across all our s3 tests in code-base:
```python
File "/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
httplib_response = conn.getresponse()
File "/..pyenv/versions/3.9.6/lib/python3.9/http/client.py", line 1349, in getresponse
response.begin()
File "/..pyenv/versions/3.9.6/lib/python3.9/http/client.py", line 316, in begin
version, status, reason = self._read_status()
File "/..pyenv/versions/3.9.6/lib/python3.9/http/client.py", line 277, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") …
```

[REVIEW] Fix `moto` timeouts 

---

cpp/include/cudf/detail/utilities/device_operators.cuh
cpp/tests/groupby/max_tests.cpp
cpp/tests/groupby/min_tests.cpp
cpp/tests/reductions/scan_tests.cpp

This fixes a bug of device operators `min` and `max` in generating the `identity` value for floating-point numbers. In particular:
* `min::identity()` should return `cuda::std::numeric_limits<T>::infinity()` instead of `cuda::std::numeric_limits<T>::max()`, and
* `max::identity()` should return `-cuda::std::numeric_limits<T>::infinity()` instead of `cuda::std::numeric_limits<T>::lowest()`.
Closes https://github.com/rapidsai/cudf/issues/11352.

Set `+/-infinity` as the `identity` values for floating-point numbers in device operators `min` and `max`

---

python/cudf/cudf/_lib/column.pyx
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/tests/test_indexing.py

This PR fixes a subtle bug leading to a segfault when constructing a `Column` from a `column_view`.
Closes #11349

Fix constructing Column from column_view with expired mask

---

conda/recipes/cudf/meta.yaml
python/cudf/setup.py
python/dask_cudf/setup.py

Allows cuDF to be installed with CuPy 11.
xref: https://github.com/rapidsai/integration/pull/508

Allow CuPy 11

---

CONTRIBUTING.md
docs/cudf/README.md

Adds links to the developer guides to the contributing.md
Closes #11348

Update contributing doc to include links to the developer guides

---

cpp/src/strings/convert/convert_datetime.cu
cpp/tests/strings/datetime_tests.cpp

Fix truncated subsecond calculation to adjust for the actual digits read in decimal 10 notation.
Added new test strings to include an appended 'Z' after the subsecond digits to test this fix.
Closes #11350

Fix to_timestamps truncated subsecond calculation

---

conda/recipes/cudf/meta.yaml
python/cudf/setup.py
python/dask_cudf/setup.py

This reverts PR ( https://github.com/rapidsai/cudf/pull/11393 ). Thus constraining this back to CuPy 10.

Revert "Allow CuPy 11"

---

conda/recipes/cudf/meta.yaml
conda/recipes/libcudf/conda_build_config.yaml

Arrow 8.0.1 just got built and uploaded to conda-forge and there's an associated PR to update the pinning to 8.0.1. Currently the recipes pin to 8.0.0 explicitly which will cause solving issues. Instead of just changing to 8.0.1, this PR relaxes the pinning to allow minor and patch versions to get pulled as there hasn't been any nvcc compiler issues in a while and Arrow strives to not introduce API / ABI breakages in minor and patch versions. Additionally, the cudf recipe seems to be unnecessarily setting requiring a cuda build of pyarrow which should no longer be needed after #10995.
Would really like this in for 21.08 if possible, but happy to change to just pin 8.0.1 if preferred.

Relax arrow pinning to just 8.x and remove cuda build dependency from cudf recipe

---

java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This PR adds Java tests for the Spark list hashing feature added in #11292.
Depends on #11292.

Add Spark list hashing Java tests

---

conda/environments/cudf_dev_cuda11.5.yml

Arrow version pinnings were relaxed in this commit: https://github.com/rapidsai/cudf/commit/d740c3cd2719c889821153da339dedcb15480103, this PR performs the same change in dev env.

[REVIEW] Relax arrow version in dev env

---

conda/recipes/cudf/meta.yaml

As a CLI tool CMake belongs in the build section and shouldn't need to be present in the host requirements.

Move cmake to the build section.

---

cpp/src/io/text/multibyte_split.cu
cpp/tests/io/text/multibyte_split_test.cpp
python/dask_cudf/dask_cudf/io/text.py

Currently, if the beginning of a field coincides with either the beginning (inclusive) or end (exclusive) of a byte range, the field will be part of the output. This PR fixes the resulting field duplication if we concatenate the results from a partition of the input into byte ranges.
The issue stems from the fact that we use lower_bound to determine the beginning of a field, but upper_bound to determine its end, so if the end of the byte range coincides with the beginning of a field, the result from the range [a,b) doesn't fit exactly onto the result from the range [b,c).
To keep the previous behavior of emitting an empty field if the input ends with a delimiter, I needed to add a small fix that differentiates between byte ranges whose size matches the input size exactly, and ones that …

Fix read_text when byte_range is aligned with field

---

python/dask_cudf/dask_cudf/tests/test_distributed.py

This PR resolves the following error showing up in latest `distributed`:
```python
python/dask_cudf/dask_cudf/tests/test_distributed.py EE                                                                                                                                [100%]
=========================================================================================== ERRORS ===========================================================================================
_____________________________________________________________________________ ERROR at setup of test_basic[True] _____________________________________________________________________________
file /nvme/0/pgali/cudf/python/dask_cudf/dask_cudf/tests/test_distributed.py, line 24
@pytest.mark.parametrize("delayed", [True, False])
def …
```

[REVIEW] Fix `distributed` error related to `loop_in_thread`

---

cpp/cmake/thirdparty/get_arrow.cmake

Fixes #11425
Changes the `CUDF_VERSION_Arrow` cmake variable to be a cache entry so that a user can override it by providing `-DCUDF_VERSION_Arrow` at configure time.
Happy to repeat this pattern for other dependencies if desired.

Change cmake to allow controlling Arrow version via cmake variable

---

cpp/CMakeLists.txt

Instead of waiting to compilation time to get a confusing error about int128 support. Quickly terminate at CMake time when we detect an insufficient nvcc version.

Quickly error out when trying to build with unsupported nvcc versions

---

cpp/tests/io/json_test.cpp
python/cudf/cudf/_lib/cpp/io/json.pxd
python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/io/json.py
python/cudf/cudf/tests/test_json.py
python/cudf/cudf/utils/ioutils.py

Add Python API to expose the future experimental JSON reader implementation.
Add tests for C++ and Python experimental APIs.
Issue https://github.com/rapidsai/cudf/issues/8827

Python API for the future experimental JSON reader

---

python/cudf/cudf/tests/test_index.py

This PR fixes a flaky test introduced by #11272, cudf joins by default does not guarantee return orders and may lead to occasional test regression. This PR adds `sort` argument to make sure result is deterministic.
Note that `index.union` and `index.intersection` may also include random output ordering, but by default these methods sorts the result before returning so `sort` argument does not need to be modified.

Make Index Join Tests on Default Precisions Deterministic

---

cpp/include/cudf/utilities/traits.hpp
cpp/src/io/statistics/byte_array_view.cuh
cpp/src/io/statistics/statistics.cuh
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

When reviewing PR #11322 it was noted that it would be preferable to use `std::byte` for the data type, but at the time that didn't work out, so the plan was to address it later and issue #11362 was created to track it.
Fixes #11362

Convert byte_array_view to use std::byte

---

cpp/include/cudf/column/column.hpp
cpp/tests/column/column_test.cu

Closes #11115 
This PR adds a `column` constructor to be constructible from a `device_uvector&&` using move semantics.

Add column constructor from device_uvector&&

---

cpp/include/cudf/io/orc.hpp
cpp/include/cudf/io/parquet.hpp
cpp/src/io/orc/aggregate_orc_metadata.cpp
cpp/src/io/orc/aggregate_orc_metadata.hpp
cpp/tests/io/orc_test.cpp
java/src/main/native/src/TableJni.cpp
python/cudf/cudf/_lib/cpp/io/orc.pxd
python/cudf/cudf/_lib/orc.pyx
python/cudf/cudf/_lib/parquet.pyx
python/cudf/cudf/tests/test_orc.py

Changes are mostly equivalent to Parquet changes in https://github.com/rapidsai/cudf/pull/11018.
Store the `columns` option as `optional`:
- `nullopt` when columns are not passed by caller - read all columns.
- Empty vector when caller explicitly passes an empty list/vector - return empty dataframe.
- Vector of column names - read columns with given names.
Also includes a small cleanup of the code equivalent in the Parquet reader.
Fixes https://github.com/rapidsai/cudf/issues/11021

Return empty dataframe when reading an ORC file using empty `columns` option

---

cpp/include/cudf/io/types.hpp
cpp/src/io/parquet/compact_protocol_reader.hpp
cpp/src/io/parquet/parquet.hpp

As noted in https://github.com/rapidsai/cudf/issues/11368 we should strive towards not having thrust types in our 'public' API. 
This removes occurences of using `thrust::optional` from cudf/io host classes in preference of `std::optional`.

Convert thrust::optional usages to std::optional

---

.pre-commit-config.yaml
cpp/scripts/run-cmake-format.sh

The hooks for cmake-format and cmake-lint can fail silently if the necessary config files are not available. When creating these hooks we chose this behavior because depending on where and how people build the libraries the location of the format file may not be discoverable. However, this often leads to user confusion where the hooks appear to pass locally when in fact they never ran. This PR changes the hooks to be verbose so that they can provide more useful diagnostic output. In order to leave that output at a maintainable level, it forces these hooks to run serially. On my machine, this results in the cmake-format hook taking ~3.5s instead of ~1.2s to run on all files, which is an acceptable compromise for readable output.

Make CMake hooks verbose

---

docs/cudf/source/conf.py

This PR switches the loading of `custom.js` to `defer` because we will need the entire page to be loading until the methods in this script can even execute correctly.

[REVIEW] Defer loading of `custom.js`

---

python/cudf/cudf/_lib/cpp/io/parquet.pxd
python/cudf/cudf/_lib/parquet.pyx
python/cudf/cudf/io/parquet.py
python/cudf/cudf/tests/test_parquet.py
python/cudf/cudf/utils/ioutils.py

This PR removes support for `skiprows` & `num_rows` in parquet reader. A continuation of https://github.com/rapidsai/cudf/pull/11218

[REVIEW] Drop support for `skiprows` and `num_rows` in `cudf.read_parquet`

---

python/cudf/cudf/_lib/column.pyx

release() sets the null_count of a column to zero, so previously
asking for the null_count provided an incorrect value. Fortunately
this never exhibited in the final column, since Column.__init__ always
ignores the provided null_count and computes it from the null_mask (if
one is given).

column: calculate null_count before release()ing the cudf::column

---

ci/benchmark/build.sh
ci/gpu/build.sh
conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/custreamz/meta.yaml
conda/recipes/dask-cudf/meta.yaml
python/dask_cudf/setup.py

This PR unpins `dask` & `distributed` for `22.10` development.

[REVIEW] Unpin `dask` and `distributed` for development

---

conda/recipes/libcudf/build.sh
cpp/CMakeLists.txt

This PR is a breaking change that disables Arrow S3 support by default. Enabling this feature by default has caused build issues for many downstream consumers, all of whom (to my knowledge) manually disable support for this feature. Most commonly, that build error appears as `fatal error: aws/core/Aws.h: No such file or directory`. In my understanding, several downstream consumers of cudf no longer rely on Arrow S3 support from this library and instead get S3 access via fsspec. I am not aware of any users of libcudf who rely on this being enabled by default (or enabled at all).
See related issues and discussions: #8617, #11333, #8867, https://github.com/rapidsai/cudf/pull/10644#discussion_r853270226, https://github.com/NVIDIA/spark-rapids/pull/2827. Build errors caused by this default …

Disable Arrow S3 support by default.

---

cpp/include/cudf/utilities/traits.hpp

This PR removes the unused `is_struct` trait. Users should instead check the column `data_type` id, like `col->type().id() == cudf::type_id::STRUCT`.

Remove unused is_struct trait.

---

cpp/include/cudf/detail/labeling/label_segments.cuh

In `cudf::detail::label_segments`, when the input lists column has empty/nulls lists at the end of the column, its `offsets` column will contain out-of-bound indices. This leads to invalid memory access bug. Such bug is elusive and doesn't show up consistently. Test failures reported in https://github.com/NVIDIA/spark-rapids/issues/6249 are due to this.
The existing unit tests already cover such corner case. Unfortunately, the bug didn't show up until being tested on some systems. Even that, it was very difficult to reproduce it.
Closes https://github.com/rapidsai/cudf/issues/11495.

Fix out-of-bound access in `cudf::detail::label_segments`

---

python/cudf/cudf/_fuzz_testing/parquet.py
python/cudf/cudf/_fuzz_testing/tests/fuzz_test_parquet.py

In a previous PR https://github.com/rapidsai/cudf/pull/11480/, `skiprows` & `num_rows` were removed from `cudf.read_parquet`, this PR updates the corresponding parquet reader fuzz tests.

[REVIEW] Update parquet fuzz tests to drop support for `skiprows` & `num_rows`

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/meta.yaml
conda/recipes/libcudf/conda_build_config.yaml
cpp/cmake/thirdparty/get_arrow.cmake

This PR upgrades `arrow` to `9.x` in `cudf`.

[REVIEW] Upgrade to `arrow-9.x`

---

cpp/include/cudf/detail/copy_range.cuh

We can simplify the logic around determining the warp_mask by having both queries issued without a dependency

copy_range ballot_syncs to have no execution dependency

---

python/cudf/cudf/tests/test_binops.py
python/cudf/cudf/utils/dtypes.py

This PR resolves #11225. It fixes binary operator dispatch for reverse ops like `__radd__` acting on host scalars and `cudf.Scalar` objects in expressions like `1 + cudf.Scalar(3)`, which previously threw an error.

Fix reverse binary operators acting on a host value and cudf.Scalar

---

cpp/src/quantiles/tdigest/tdigest.cu
cpp/tests/quantiles/percentile_approx_test.cu

Closes #10856 
If all of the tdigest inputs to percentile_approx are empty, it will return a column containing null rows, as expected, but they will have unsanitary offsets. This PR checks if all the inputs are empty and returns an empty column as expected.

Sanitize percentile_approx() output for empty input

---

python/cudf/cudf/tests/test_feather.py

This fixes a test warning from `test_feather.py`.
```
cudf/python/cudf/cudf/tests/test_feather.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
The code used `distutils` to check the pandas version and import a special `feather` package if it was less than pandas 0.24. However, we no longer need to test against pandas versions that old so we can just remove this check entirely instead of updating it to use `packaging.version`.

Fix Feather test warning.

---

python/cudf/cudf/io/orc.py
python/cudf/cudf/utils/ioutils.py

Resolves the first step of #11519 by deprecating `skiprows` and `num_rows` in orc reader.

[REVIEW] Deprecate `skiprows` and `num_rows` in `read_orc`

---

cpp/src/io/utilities/column_utils.cuh
cpp/tests/io/parquet_test.cpp

This fixes the crash described in the bug related to writing nested data in parquet with the binary flag set to write binary data as byte_arrays. We were incorrectly selecting the top-most node instead of the list<int8>, which resulted in a crash down in the kernels when the data pointer was null for those upper list columns.
closes #11506

Fixing crash when writing binary nested data in parquet

---

cpp/src/binaryop/compiled/binary_ops.cu
cpp/src/binaryop/compiled/struct_binary_ops.cuh
java/src/main/native/src/ColumnViewJni.cpp
java/src/main/native/src/ScalarJni.cpp
java/src/test/java/ai/rapids/cudf/BinaryOpTest.java

Adds support for Spark's null aware equality binop and expands/improves Java testing for struct binops. Properly tests null structs and full operator testing coverage. Utilizes existing Spark struct binop support with JNI changes to force the full null-aware comparison.
Expands on #11153
Partial solution to #8964 -- `NULL_MAX` and `NULL_MIN` still outstanding.

Struct support for `NULL_EQUALS` binary operation

---

cpp/tests/io/parquet_test.cpp

As noticed in review of #11524 there are unnecessary asserts in the parquet tests. This removes those.
closes #11541

Removing unnecessary asserts in parquet tests

---

cpp/src/io/parquet/page_data.cu

This removes an implementation of a hashing function identical to the `MurmurHash3_32` used elsewhere in libcudf. This removes the re-implementation and instead uses the common hashing function code.

Reuse MurmurHash3_32 in Parquet page data.

---

java/src/main/java/ai/rapids/cudf/ColumnWriterOptions.java
java/src/main/java/ai/rapids/cudf/CompressionMetadataWriterOptions.java
java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

Adds in java APIs to support writing binary columns in parquet.

JNI support for writing binary columns in parquet

---

python/custreamz/custreamz/tests/test_dataframes.py

Should unblock CI that is now failing due to upstream breakage. It appears that ipywidgets 8.0.0 is incompatible with streamz 0.6.4.

xfail custreamz display test for now

---

java/src/main/java/ai/rapids/cudf/TableWithMeta.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

After #11364 `TableWithMeta` no longer returns the column names for a table since it is looking at the old `column_names` field instead of the newer `schema_info` field in the table metadata.  This updates the JNI to use the `schema_info` to get the column names and adds a test for this API which was missing before.

Fix JNI for TableWithMeta to use schema_info instead of column_names

---

python/dask_cudf/dask_cudf/groupby.py
python/dask_cudf/dask_cudf/tests/test_groupby.py

Dask-cudf groupby tests *should* be failing as a result of https://github.com/dask/dask/pull/9302 (see [failures](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-gpu-test/CUDA=11.5,GPU_LABEL=driver-495,LINUX_VER=ubuntu20.04,PYTHON=3.9/9946/) in #11565 is merged - where dask/main is being installed correctly).  This PR updates the dask_cudf groupby code to fix these failures.

Fix groupby failures in dask_cudf CI

---

python/cudf/cudf/core/column_accessor.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_reshape.py

Resolves: https://github.com/rapidsai/cudf/issues/10529

Fix for pivot: error when 'values' is a multicharacter string

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/io/text/multibyte_split.cpp

This adds a second benchmark testing byte ranges with 1% - 50% of the input size to the multibyte_split benchmarks.
Example output (--run-once):
<details>
```
| source_type | delim_size | delim_percent |    size_approx    | byte_range_percent | Samples |  CPU Time  | Noise |  GPU Time  | Noise | Peak Memory Usage | Encoded file size |
|-------------|------------|---------------|-------------------|--------------------|---------|------------|-------|------------|-------|-------------------|-------------------|
|           0 |          1 |             1 |      2^15 = 32768 |                  1 |      1x | 683.062 us |  inf% | 677.888 us |  inf% |        86.672 KiB |         315.000 B |
|           1 |          1 |             1 |      2^15 = 32768 |                  1 |      1x |  11.870 ms …
```

Add byte_range to multibyte_split benchmark + NVBench refactor

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/df_protocol.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/udf/utils.py
python/cudf/cudf/core/window/rolling.py
python/cudf/cudf/testing/dataset_generator.py
python/cudf/cudf/tests/test_parquet.py
python/cudf/cudf/utils/cudautils.py
python/cudf/cudf/utils/ioutils.py
python/cudf/cudf/utils/utils.py
python/custreamz/custreamz/kafka.py
python/dask_cudf/dask_cudf/core.py
setup.cfg

Recently I have reviewed a handful of PRs with problems in their docstrings that I've been fixing with GitHub review suggestions. I took 40 minutes and enabled a bunch of pydocstyle rules that we agreed on in #10711, to help prevent some of these problems and reduce the amount of review effort required for the future. There are a handful of big ones (`D200, D202, D205, D400`) that will require a more intense effort to implement -- those rules may not be worth the significant refactoring effort. I think this may resolve the part of #10711 that we wanted to tackle in the short term, though I'm happy to hear others' views (@shwina @vyasr).
Error code reference: https://www.pydocstyle.org/en/stable/error_codes.html

Enable more Pydocstyle rules

---

cpp/benchmarks/quantiles/quantiles.cpp

https://github.com/rapidsai/cudf/pull/11479 accidentally changed the distribution data type so the custom distribution was set for the wrong type.

Correct distribution data type in `quantiles` benchmark

---

python/cudf/cudf/core/frame.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #11589 
This PR fixes an issue with `DataFrame.to_arrow` when the column names are `int`/`tuples` i.e., non-string types.
The fix is trivial and retains the same behavior that of `pa.Table.from_pandas` which converts all non-string column names to `strings`.

[REVIEW] Fix an issue with `to_arrow` when column name type is not a string

---

java/src/main/native/src/row_conversion.cu

This fixes an issue where the Java API is using a default stream instead of the stream passed in. This is a small change separated from #11600 because it only touches one Java file and thus only needs a Java reviewer.

Use stream in Java API.

---

cpp/src/io/json/nested_json_gpu.cu

Fixes compile warning introduced in #11534 
```
/cudf/cpp/src/io/json/nested_json_gpu.cu(970): warning #177-D: variable "single_item_count" was declared but never referenced
```
Removed unreferenced variable declaration.

Fix compile warning in nested_json_gpu.cu

---

python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/dtypes.py
python/cudf/cudf/tests/test_categorical.py
python/dask_cudf/dask_cudf/backends.py
python/dask_cudf/dask_cudf/tests/test_core.py

Fixes: #11487 
This PR switches default value of `ordered` parameter in `CategoricalDtype` to `False`. This fixes some issues around concat and building categorical columns.

[REVIEW] Change default value of `ordered` to `False` in `CategoricalDtype`

---

cpp/benchmarks/reduction/segment_reduce.cu

Fixes exception thrown in `REDUCTION_NVBENCH`. 
```
Run:  [121/768] segmented_reduction_simple [Device=0 InputType=bool OutputType=F32 AggregationKinds=2 column_size=100000 num_segments=1000]
Fail: Unexpected error: cuDF failure at: /cudf/cpp/src/reductions/segmented_min.cu:33: segmented_min() operation requires matching output type
```
(There are 144 of these)
The code is refactored to reduce the generated benchmark code in order to match input and output types and to force the output type to `BOOL8` for aggregation kind `ALL`. This also removes code generated that is only _skipped_:
```
Run:  [277/768] segmented_reduction_simple [Device=0 InputType=I32 OutputType=I32 AggregationKinds=7 column_size=100000 num_segments=1000]
Skip: Invalid combination of dtype and aggregation type.
``` …

Fix exception in segmented-reduce benchmark

---

java/ci/Dockerfile.centos7

This changed the cmake version for jni building to 3.23.3. Matching PR to [this one](https://github.com/NVIDIA/spark-rapids-jni/pull/512).

changing version of cmake to 3.23.3

---

cpp/include/cudf/io/text/byte_range_info.hpp
cpp/src/io/text/multibyte_split.cu
cpp/tests/io/text/multibyte_split_test.cpp

This adds a new `multibyte_split` implementation that needs to scan the input only once, and takes full advantage of `byte_range`.
To accomplish this, I introduce a new data structure `output_builder` (naming bikeshedding welcome 😄 ) for pre-allocation for unknown, but bounded outputs.
The structure contains a vector of exponentially growing `device_uvector`s, such that either the last vector has size 0 and the second-to-last vector has `size() < capacity()`, or all vectors but the last are full (`size() == capacity()`). It provides the operations
* `next_output(stream)` returns a `split_device_span` of at least the `worst_cast_size` provided at construction pointing to the next free entries from the last two vectors.
* `advance_output(actual_size)` marks the first `actual_size` entries …

Single-pass `multibyte_split`

---

cpp/include/cudf/io/text/detail/multistate.hpp
cpp/src/io/text/multibyte_split.cu

This improves the `multibyte_split` kernel by
* Reducing register pressure: Instead of storing `ITEMS_PER_THREAD` individual states, store only the initial `multistate` for the thread and recompute the individual states on-the-fly
* Eliminating local memory usage: Manipulate the `multistate` via shifts instead of array random access
* Eliminating trie overhead: Since we have only a single delimiter, the trie is a path. We can do the traversal implicitly
* Memoizing which chars were a match: We don't need to recompute this information, but can store it in a bitmask
* Changing the block load algorithm: `BLOCK_LOAD_VECTORIZE` was slightly less efficient than `BLOCK_LOAD_WARP_TRANSPOSE`
* Reducing the allocation overhead by limiting the `output_builder` max allocation size
* Tuning the …

Tune multibyte_split kernel

---

cpp/src/io/parquet/writer_impl.cu

As brought up in #11626, converted type being written on INT32 and INT64 columns is not out of spec, but abnormal for parquet writers. This change brings cudf's writer in line with pandas and spark by not including converted type information on these types.
closes #11626

Removed converted type for INT32 and INT64 since they do not convert

---

cpp/benchmarks/io/json/nested_json.cpp

Fixes compile error introduced in PR #11466 due to mismatched changes occurring in PR #11534
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/11851/console

Fix compile error in benchmark nested_json.cpp

---

cpp/include/cudf/strings/padding.hpp
cpp/src/strings/padding.cu
cpp/tests/strings/pad_tests.cpp
python/cudf/cudf/core/column/string.py
python/cudf/cudf/tests/test_string.py

Fixes `cudf::strings::zfill` to match Python's `zfill` behavior. This will match Pandas 1.5 `zfill` as well.
The new behavior correctly skips the leading sign character when applying the '0' character fill.
Updates gtests and added more test data.
The pytest was updated to xfail for test data with leading sign characters until Pandas 1.5 is supported.
The Java tests did not include any test data with sign characters.
Closes #11632

Update zfill to match Python output

---

cpp/src/strings/json/json_path.cu

Fixes an issue where `get_json_object` returns an incorrect null count on large inputs.
The source of the bug is that each thread was resetting `out_valid_count` to zero, then only the threads that execute in the final block contribute to the value of `out_valid_count`.
cc: @thomcom

[FIX] Fix incorrect `nullCount` in `get_json_object`

---

cpp/src/io/orc/reader_impl.cu
cpp/src/io/parquet/reader_impl.cu
cpp/src/io/utilities/hostdevice_vector.hpp

The implementation of `hostdevice_vector` has a lot of code duplication and a defect (probably) because its span cast operators use `max_size` and not `size`. I'd like to give `hostdevice_vector` more `thrust::host_vector`-like functionality and semantics, so this is a first step towards that goal.
Needs to be benchmarked before merging, to see if the default-initialization slows anything down significantly

Simplify `hostdevice_vector`

---

cpp/benchmarks/io/fst.cu

This PR fixes an issue that arises from benchmark size exceeding our `size_type`'s supported max value size. 
Thanks to @GregoryKimball for reporting the issue 🙏

fixes overflows in benchmarks

---

cpp/include/cudf/detail/copy_if_else.cuh
cpp/src/copying/purge_nonempty_nulls.cu
cpp/src/groupby/sort/group_merge_m2.cu
cpp/src/unary/null_ops.cu

Fixes some calls that were not passing the stream variable to detail functions.
Found these while looking into improvements for #11577

Fix some libcudf detail calls not passing the stream variable

---

cpp/src/copying/concatenate.cu
cpp/src/datetime/datetime_ops.cu
cpp/src/filling/fill.cu
cpp/src/groupby/sort/group_correlation.cu
cpp/src/lists/copying/scatter_helper.cu
cpp/src/lists/set_operations.cu
cpp/src/reductions/simple_segmented.cuh
cpp/src/replace/nans.cu
cpp/src/round/round.cu
cpp/src/search/contains_column.cu
cpp/src/strings/capitalize.cu
cpp/src/strings/contains.cu
cpp/src/strings/like.cu
cpp/src/text/stemmer.cu
cpp/src/unary/math_ops.cu

Adds calls to `cudf::column.set_null_count()` when the null-count is known.
Found these while looking into improvements for #11577 
There are several ways to make a `cudf::column` object to be returned. Many times the column is created and then filled in by calling the `cudf::column.mutable_view()` function and using the `mutable_view` object. The `cudf::column::mutable_view()` function has a side-effect that invalidates it's internal null-count. This is for efficiency so the null-count is only computed when the value is specifically requested through the `cudf::column::null_count()` method. Computing the null-count inside `null_count()` requires a kernel launch. However, there are several places where the null-count is known before returning the column and setting the value means a later …

Call set_null_count on a returning column if null-count is known

---

ci/gpu/build.sh
cpp/src/io/utilities/data_sink.cpp

Fixed incorrect size when calling `device_write_async()`.
Additionally, CI now runs the csv, orc, and parquet tests using the KvikIO backend. 
cc. @vuule

Fix bug in `device_write()`: it uses an incorrect size

---

cpp/src/strings/regex/regcomp.cpp
cpp/tests/strings/contains_tests.cpp

Fixes the regex negated class NCCLASS builder to not automatically include the new-line character in the negated range.
This logic is from the original plan9 source but does not appear to be honored by any other known regex implementation.
Marking this as a breaking change since it changes the existing behavior in case someone is depending on the current logic.
Also added a new gtest to include `\n` data when matching with a negated class.
Closes #11643

Fix regex negated classes to not automatically include new-lines

---

python/cudf/cudf/_lib/cpp/io/types.pxd
python/cudf/cudf/_lib/io/utils.pyx
python/cudf/cudf/tests/test_s3.py

The intention of this PR is to address the dataset-truncation bug described in #11324. It seems that cudf does not currently handle multiple pyarrow-based datasources correctly.  This means `cudf.read_parquet` will return incorrect results when reading a list of files from remote storage (e.g. from s3 or gcs).
**The underlying problem**: Instead of passing a vector of `datasource` objects to libcudf, the python/cython API only passes along a `datasource` object for the very **first** file in the user-specified list.

Fix multi-file remote datasource bug

---

.pre-commit-config.yaml
conda/environments/cudf_dev_cuda11.5.yml
python/cudf/cudf/_typing.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/core/series.py
python/cudf/cudf/core/single_column_frame.py
setup.cfg

Update to current mypy, primarily since on Apple silicon, the previous pinned version of mypy is no longer installable (`typed-ast` does not build from source). This necessitates some minor updates to the type annotation rules, since the newer mypy version is a bit pickier.
While we're here, exclude directories we were previously just ignoring errors in.

Update to mypy 0.971

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_indexing.py

Maintain the index name after `.loc`

---

setup.cfg

As part of https://github.com/rapidsai/cudf/pull/11640, there was a missing exclusion for `cudf/cudf/utils/metadata/orc_column_statistics_pb2.py`, that causes the following errors:
```bash
(cudfdev) pgali@dt07:/nvme/0/pgali/cudf$ git commit -m "address reviews"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/nfs/pgali/.cache/pre-commit/patch1662993629-63423.
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1
python/cudf/cudf/utils/metadata/orc_column_statistics_pb2.py: …
```

[REVIEW] Ignore protobuf generated files in `mypy` checks

---

.pre-commit-config.yaml
ci/checks/headers_test.sh
ci/checks/style.sh

This PR runs the conda recipe checks for all headers in `include/` with `pre-commit` instead of as a separate step in `style.sh`. This means that developers using `pre-commit` will be able to fix mistakes before pushing, where errors would cause failures in CI. Combined with #11668, most of our style check suite will be executed via `pre-commit`, enabling us to simplify `style.sh`.

Check conda recipe headers with pre-commit

---

.pre-commit-config.yaml
ci/checks/style.sh
cpp/.clang-format
cpp/src/column/column_factories.cpp

This PR removes a redundant style check for clang-format. Our configuration in `.pre-commit-config.yaml` already runs clang-format so we don't need a separate step for that purpose in `style.sh`.

Remove redundant style check for clang-format.

---

cpp/CMakeLists.txt
cpp/benchmarks/CMakeLists.txt
cpp/tests/CMakeLists.txt

This is needed so that `rapids-cmake` population of `rpath-link` link options is provided to all executables.
Fixes #11628

Ensure that all cudf tests and benchmarks are conda env aware

---

python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/tests/test_groupby.py

When there are multiple groups in a groupby, passing `group_keys=True` raises an error:
```python
In [2]: gdf = cudf.DataFrame(
...: {"A": "a a b".split(), "B": [1, 1, 3], "C": [4, 6, 5]}
...: )
In [3]: g_group = gdf.groupby(["A", "B"], group_keys=True)
In [4]: g_group[["B", "C"]].apply(lambda x: x / x.sum())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [4], line 1
----> 1 g_group[["B", "C"]].apply(lambda x: x / x.sum())
File /nvme/0/pgali/envs/cudfdev/lib/python3.9/site-packages/cudf/core/groupby/groupby.py:782, in GroupBy.apply(self, function, *args)
778         result = cudf.concat(chunk_results)
779         if self._group_keys:
780 …
```

[REVIEW] Fix an issue related to `Multindex` when `group_keys=True`

---

cpp/src/rolling/detail/range_window_bounds.hpp
cpp/src/rolling/grouped_rolling.cu
cpp/src/rolling/range_window_bounds.cpp
cpp/tests/CMakeLists.txt
cpp/tests/rolling/grouped_rolling_range_test.cpp
cpp/tests/rolling/range_window_bounds_test.cpp
java/src/main/java/ai/rapids/cudf/Scalar.java
java/src/main/java/ai/rapids/cudf/Table.java
java/src/test/java/ai/rapids/cudf/TableTest.java

CUDF grouped RANGE window functions currently support only
integral types and timestamps as the ORDER BY (OBY) column.
This commit adds support for DECIMAL types (i.e. decimal32,
decimal64, and decimal128) to be used as the ORDER BY
column in RANGE window functions.
This feature allows `spark-rapids` to address https://github.com/NVIDIA/spark-rapids/issues/6400.

Support DECIMAL order-by for RANGE window functions

---

python/cudf/cudf/core/frame.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #11693 
This PR fixes `DataFrame.from_arrow` which does not preserve type metadata for `struct`, `list` & `decimal` types.

[REVIEW] Fix `DataFrame.from_arrow` to preserve type metadata

---

python/dask_cudf/dask_cudf/tests/test_groupby.py

Discussion in dask/dask#9490 and dask/dask#9491 suggests that split_out=None as a default value was never really intended and is likely to be deprecated.
cc @rjzamora

Drop split_out=None test from groupby.agg

---

cpp/src/io/text/multibyte_split.cu
cpp/tests/io/text/multibyte_split_test.cpp

multibyte_split does two scans to determine delimiters: One using the trie to determine matches, one to determine the offsets. For single-byte delimiters, the trie scan is unnecessary, since we can determine without context what is a delimiter. So I added a single `byte_split_kernel` by replacing the trie logic with a char comparison. The difference is quite significant:
| source_type | delim_size | delim_percent |    size_approx    |  GPU Time  | Peak Memory Usage | Encoded file size |
|-------------|------------|---------------|-------------------|------------|-------------------|-------------------|
|           0 |          1 |             1 | 2^30 = 1073741824 | 110.196 ms |         3.947 GiB |      1006.638 MiB |
|           0 |          2 |             1 | 2^30 = 1073741824 | …

Special-case multibyte_split for single-byte delimiter

---

ci/gpu/test-notebooks.sh
ci/local/build.sh
ci/utils/nbtest.sh
cpp/examples/basic/src/process_csv.cpp
cpp/include/cudf/io/text/detail/tile_state.hpp
cpp/tests/utilities/table_utilities.cu
docs/cudf/source/_ext/PandasCompat.py
print_env.sh
python/cudf/cudf/_lib/cpp/datetime.pxd
python/cudf/cudf/core/udf/__init__.py
python/cudf/cudf/core/udf/_ops.py
python/cudf/cudf/core/udf/api.py
python/cudf/cudf/core/window/__init__.py
python/cudf/cudf/tests/test_apply_rows.py
python/cudf/cudf/tests/test_datasets.py
python/cudf/cudf/tests/test_numpy_interop.py
python/cudf/cudf/tests/test_query_mask.py
python/dask_cudf/dask_cudf/io/json.py
python/dask_cudf/dask_cudf/io/tests/test_csv.py
python/dask_cudf/dask_cudf/io/tests/test_json.py
python/dask_cudf/dask_cudf/tests/test_delayed_io.py
python/dask_cudf/dask_cudf/tests/test_dispatch.py
python/dask_cudf/dask_cudf/tests/test_join.py
python/dask_cudf/dask_cudf/tests/test_sort.py
python/dask_cudf/dask_cudf/tests/test_struct.py

While working on #11711, I noticed a set of files that did not have copyright headers in place. This PR fixes them. I used the "start year" from the output of `git log` indicating the first commit to each file.

Add missing copyright headers.

---

cpp/cmake/thirdparty/get_thrust.cmake

Places the `PATCH_COMMAND` on it's own line separate from the `GIT_SHALLOW` command line.
Recently got a style-check error on `get_thrust.cmake`
https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fcudf%2Fprb%2Fcudf-style/detail/cudf-style/28876/pipeline
The style-check tool was used to fix this.

Fix get_thrust.cmake format at patch command

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/tests/test_list.py

Since libcudf doesn't keep track of StructDtype key names, round-tripping through outer_explode loses information. We know the correct dtype, since it is the element_type of the exploded list column, so attach that type metadata before handing back the return value.
Exploding a list series should be equivalent to unwrapping one level of list from the dtype, so that
x = cudf.Series([[{'a': 'b'}]])
x.explode().dtype == x.dtype.element_type
Previously this was not the case, since we would lose the names resulting in
x.explode().dtype == StructDtype({'0': dtype('O')})

Transfer correct dtype to exploded column

---

cpp/tests/io/json_tree.cpp
cpp/tests/io/nested_json_test.cpp

The stream is only `constexpr` in the default case for cudf. When compiled with PTDS (or in the future, with a custom stream) the `default_stream_value` is a constant, but not necessarily a compile-time constant.

Don't assume stream is a compile-time constant expression

---

python/cudf/cudf/core/df_protocol.py
python/cudf/cudf/tests/test_df_protocol.py

This will align the implementation with those in other libraries, xref https://github.com/data-apis/dataframe-api/issues/80.
Cc @shwina

Add a `__dataframe__` method to the protocol dataframe object

---

cpp/include/cudf/io/orc_metadata.hpp
cpp/src/io/orc/stats_enc.cu
python/cudf/cudf/tests/test_orc.py

Issue https://github.com/rapidsai/cudf/issues/9313
The root cause is that the sum value was encoded as an unsigned int. ORC specs show that the value should be encoded as signed.
Because both encode and decode where assuming unsigned encoding, the existing C++ test (OrcStatisticsTest, Basic) was passing even without this fix. Added a Python test that uses a different decode method, so it fails without the fix.

Fix ORC string sum statistics

---

cpp/doxygen/developer_guide/DOCUMENTATION.md

Updates the instruction to build the libcudf documentation files in DOCUMENTATION.md.
The `cmake --build . --target docs_cudf` will invoke the appropriate make tool as setup when cmake was configured for building libcudf.
Closes #11719

Update libcudf documentation build command in DOCUMENTATION.md

---

cpp/tests/copying/split_tests.cpp

Disables a `ContiguousSplitUntypedTest` that simply creates a very large (over 3GB) column to test the output buffer size does not overflow. The gtests ends requiring 25GB of device memory when used with the arena allocator as mentioned in #11249. Very large columns like this should be not part of the unit test for libcudf.
This PR disables the test so it can be available for testing on specific conditions outside of CI.
Closes #11249

Disable very large column gtest for contiguous-split

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/lists.py

This PR adds ability to construct a `ListColumn` when `size` is `None`:
```python
In [1]: from cudf.core.column import build_list_column
In [2]: from cudf.core.column import as_column
In [3]: build_list_column(indices = as_column([0, 3]), elements = as_column([0, 2, 4]))
...
TypeError: an integer is required
```

[REVIEW] Add ability to construct `ListColumn` when size is `None`

---

python/dask_cudf/dask_cudf/groupby.py
python/dask_cudf/dask_cudf/tests/test_groupby.py

The `sort=True` default change in https://github.com/dask/dask/pull/9486 was not meant to propagate to the DataFrameGroupby and SeriesGroupby classes just yet. This PR adds the necessary `sort=None` defaults needed to avoid CI failures.
cc @galipremsagar

Resolve dask_cudf failures caused by upstream groupby changes

---

cpp/tests/column/column_test.cu
cpp/tests/column/compound_test.cu
cpp/tests/copying/concatenate_tests.cu
cpp/tests/copying/detail_gather_tests.cu
cpp/tests/device_atomics/device_atomics_test.cu
cpp/tests/error/error_handling_test.cu
cpp/tests/fixed_point/fixed_point_tests.cu
cpp/tests/groupby/lists_tests.cu
cpp/tests/hash_map/map_test.cu
cpp/tests/io/json_type_cast_test.cu
cpp/tests/io/type_inference_test.cu
cpp/tests/iterator/iterator_tests.cuh
cpp/tests/iterator/optional_iterator_test_numeric.cu
cpp/tests/iterator/pair_iterator_test_numeric.cu
cpp/tests/join/conditional_join_tests.cu
cpp/tests/scalar/scalar_device_view_test.cu
cpp/tests/strings/factories_test.cu
cpp/tests/transform/row_bit_count_test.cu
cpp/tests/types/type_dispatcher_test.cu
cpp/tests/utilities/column_utilities.cu
cpp/tests/utilities_tests/span_tests.cu
cpp/tests/wrappers/timestamps_test.cu

Currently many of our tests are only stream-safe because libcudf runs everything on the default stream. This PR updates tests to ensure that any function that launches a kernel and supports passing streams will act on cudf's default stream even when it is _not_ CUDA's default stream.
There are other aspects required for stream-safety that are not addressed in this PR. For instance, some of our tests make use of `thrust::device_vector`, and its initialization is implicitly always on the default stream. I'll work on that in a separate PR since that also requires some discussion with the team on what expectations a stream-based libcudf API could like like for consumers that make use of thrust (i.e. do we start requiring device syncs for such consumers?). There are also numerous tests that …

Ensure that all tests launch kernels on cudf's default stream

---

cpp/tests/column/column_test.cu
cpp/tests/column/compound_test.cu
cpp/tests/copying/concatenate_tests.cu
cpp/tests/copying/detail_gather_tests.cu
cpp/tests/device_atomics/device_atomics_test.cu
cpp/tests/error/error_handling_test.cu
cpp/tests/fixed_point/fixed_point_tests.cu
cpp/tests/groupby/lists_tests.cu
cpp/tests/hash_map/map_test.cu
cpp/tests/io/json_type_cast_test.cu
cpp/tests/io/type_inference_test.cu
cpp/tests/iterator/iterator_tests.cuh
cpp/tests/iterator/optional_iterator_test_numeric.cu
cpp/tests/iterator/pair_iterator_test_numeric.cu
cpp/tests/join/conditional_join_tests.cu
cpp/tests/scalar/scalar_device_view_test.cu
cpp/tests/strings/factories_test.cu
cpp/tests/transform/row_bit_count_test.cu
cpp/tests/types/type_dispatcher_test.cu
cpp/tests/utilities/column_utilities.cu
cpp/tests/utilities_tests/span_tests.cu
cpp/tests/wrappers/timestamps_test.cu

Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

---

python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py

This PR Fixes: #11620 by passing `dtype` parameter wherever necessary in the API code to remove unnecessary pandas warnings to the end-user. Note this PR doesn't make changes to the testing code.

[REVIEW] Pass `dtype` param to avoid `pd.Series` warnings

---

cpp/src/dictionary/search.cu
cpp/src/interop/to_arrow.cu

This PR corrects a couple of places where we are running on the CUDA default stream instead of cudf's default stream.

Ensure all libcudf APIs run on cudf's default stream

---

ci/release/update-version.sh

This PR updates the version updater script so that we don't have to manually upgrade the strings_udf version in cmake file here: https://github.com/rapidsai/cudf/pull/11771

[REVIEW] Update strings udf version updater script

---

docs/cudf/source/api_docs/index.rst
docs/cudf/source/api_docs/list_handling.rst
docs/cudf/source/api_docs/series.rst
docs/cudf/source/api_docs/struct_handling.rst

[REVIEW] Add doc section for `list` & `struct` handling

---

python/cudf/cudf/core/frame.py
python/cudf/cudf/core/index.py
python/cudf/cudf/tests/test_index.py

This PR fixes: #11159 by returning correct object type for the result of `isna` & `notna` in `Index`.

Fix return type of `Index.isna` & `Index.notna`

---

cpp/CMakeLists.txt
cpp/include/cudf/io/text/data_chunk_source_factories.hpp
cpp/src/io/comp/nvcomp_adapter.cpp
cpp/src/io/text/bgzip_data_chunk_source.cu
cpp/src/io/text/data_chunk_source_factories.cpp
cpp/src/io/text/device_data_chunks.hpp
cpp/tests/io/text/data_chunk_source_test.cpp

This adds a BGZIP `data_chunk_reader` usable with `multibyte_split`. The BGZIP format is a modified GZIP format that consists of multiple blocks of at most 65536 bytes compressed data describing at most 65536 bytes of uncompressed data. The data can be accessed with record offsets provided by Tabix index files, which contain so-called virtual offsets (unsigned 64 bit) of the following form
```
63                    16       0
+----------------------+-------+
|      block offset    | local |
+----------------------+-------+
```
The lower 16 bits describe the offset inside the uncompressed data belonging to a single compressed block, the upper 48 bits describe the offset of the compressed block inside the BGZIP file. The interface allows two modes: Reading a full compressed file, and …

Add BGZIP `data_chunk_reader`

---

CONTRIBUTING.md
conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/conda_build_config.yaml
conda/recipes/cudf_kafka/meta.yaml
conda/recipes/libcudf/conda_build_config.yaml
conda/recipes/strings_udf/conda_build_config.yaml
cpp/CMakeLists.txt
cpp/libcudf_kafka/CMakeLists.txt
java/src/main/native/CMakeLists.txt
python/cudf/CMakeLists.txt
python/cudf/pyproject.toml
python/strings_udf/CMakeLists.txt
python/strings_udf/cpp/CMakeLists.txt

With rapids-cmake now requiring CMake 3.23.1 update consumers to correctly express this requirement

Document that minimum required CMake version is now 3.23.1

---

docs/cudf/source/user_guide/guide-to-udfs.ipynb
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py

This PR updates some docstrings around cuDF to show some examples of how to use strings inside UDFs, as well as provide some caveats. It also adds a section with some detail and examples to our guide to udfs ipython notebook.

Add docs for use of string data to `DataFrame.apply` and `Series.apply` and update guide to UDFs notebook

---

cpp/src/strings/regex/utilities.cuh

Fixes an out-of-bounds write error when a large number of strings requires a strided loop to meet an internal memory maximum. For row sizes that do not require strided loops, the row index never exceeds the size of the column preventing any out-of-bounds access. For large row counts, the CUDA `thread index` may be larger than the minimal count used for building the working-memory buffer. Since the kernel is launched with a thread-count with a specific block size, extra threads past the end of the minimal count are necessary to fill out the last block. These threads never contribute to the overall result but will attempt to access past the end of the working memory. Writing to this memory may corrupt memory for another kernel launched in parallel from another CPU thread. This change adds …

Fix regex out-of-bounds write in strided rows logic

---

python/dask_cudf/dask_cudf/sorting.py
python/dask_cudf/dask_cudf/tests/test_distributed.py

Due to some unfortunate issues with https://github.com/rapidsai/cudf/pull/11576 and https://github.com/rapidsai/dask-cuda/pull/992, I feel that these PRs should be reverted before the 22.10 release.  This PRs roll back some recent changes that allow users to explicitly pass `shuffle="explicit-comms"` to certain shuffle-based algorithms.
cc @wence-

Revert problematic shuffle=explicit-comms changes

---

python/cudf/cudf/core/scalar.py
python/cudf/cudf/tests/test_scalar.py

Root cause:
```python
In [1]: import numpy as np
In [2]: x = np.uint8(1)
In [3]: y = np.float64(1.0)
In [4]: x.__ge__(y)
Out[4]: NotImplemented
In [8]: x >= y
Out[8]: True
```
This is leading to the following error whenever there is a Scalar binary operation involved:
```python
python/cudf/cudf/tests/test_series.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../envs/cudfdev/lib/python3.9/contextlib.py:79: in inner
return func(*args, **kwds)
../envs/cudfdev/lib/python3.9/site-packages/cudf/core/series.py:2988: in describe
data = _describe_categorical(self, percentiles)
../envs/cudfdev/lib/python3.9/site-packages/cudf/core/series.py:152: in _describe_categorical
val_counts = …
```

[REVIEW] Fix operator `NotImplemented` issue with `numpy`

---

cpp/include/cudf/detail/nvtx/nvtx3.hpp

Compile warning was introduced in #11652 in `bgzip_data_chunk_source.cu`. The warning can be seen here https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-cpu-cuda-build/CUDA=11.5/12417/consoleFull (search for `177-D`)
```
/cudf/cpp/src/io/text/bgzip_data_chunk_source.cu(362): warning #177-D: variable "nvtx3_range__" was declared but never referenced
```
The `nvtx3_range__` is part of the `CUDF_FUNC_RANGE()` macro. The warning is incorrect and likely a compiler bug. The workaround in this PR is to add `[[maybe_unused]]` to the variable declaration.
I was not able to create a small reproducer for compile bug filing.

Fix compile warning from CUDF_FUNC_RANGE in a member function

---

python/cudf/cudf/utils/ioutils.py

Adding some examples to show off the nested type JSON reading

Add examples for Nested JSON reader

---

conda/environments/cudf_dev_cuda11.5.yml
conda/recipes/cudf/meta.yaml

Because of the issue discovered here: https://github.com/rapidsai/cudf/pull/11816, we would like to pin the max version of `numpy` to `<1.23` thus averting the same error in `22.08`.

[REVIEW] Pin `numpy` to `<1.23`

---

cpp/src/io/comp/nvcomp_adapter.cpp
cpp/src/io/orc/reader_impl.cu
python/cudf/cudf/tests/test_orc.py
python/cudf/cudf/utils/ioutils.py

Disable the use of nvCOMP DEFLATE because of issues with nvCOMP 2.4.
Also fix a Python test (did not block CI because the comparison in the test is only done with  `LIBCUDF_NVCOMP_POLICY="ALWAYS"`.

Disable nvCOMP DEFLATE integration

---

python/cudf/cudf/utils/ioutils.py

The docstring for `cudf.read_text` did not include the `byte_range` argument

Update docstring for cudf.read_text

---

cpp/benchmarks/io/csv/csv_writer.cpp
cpp/benchmarks/io/cuio_common.cpp
cpp/tests/io/csv_test.cpp
cpp/tests/io/json_test.cpp
cpp/tests/io/orc_test.cpp
cpp/tests/io/parquet_test.cpp

Some cuIO tests and benchmarks declare `cudf_io` alias for `cudf::io`. This saves a single letter so it's considered to be of very low utility.
Removing all occurrences of this alias.
Also removed a couple of builder calls where the option was being set to default value.

Remove `cudf_io` namespace alias

---

java/ci/README.md
java/pom.xml

Update JNI version to 22.12.0-SNAPSHOT

Update cudf JNI version to 22.12.0-SNAPSHOT

---

cpp/src/groupby/sort/group_single_pass_reduction_util.cuh
cpp/src/partitioning/round_robin.cu
cpp/src/search/search_ordered.cu

After reviewing usages of the "legacy" row operators, several of the includes are no longer needed.

Remove unused includes for table/row_operators

---

java/src/main/java/ai/rapids/cudf/HostColumnVectorCore.java

This avoids a potential null pointer exception when trying to read byte data from an empty column
- [] New or existing tests cover these changes.

JNI Avoid NPE for reading host binary data

---

cpp/benchmarks/common/generate_input.cu

closes https://github.com/rapidsai/cudf/issues/11850
Fixes decimal benchmark input data generation.
Generated data alternated between two values because `device_uvector<T>` has both value and scale. scale is fixed for a column and hence when this data is copied to `cudf::column`, this column values alternated between values and scale.
Fix is to use `device_storage_type_t<T>` instead of `T`.

Fix decimal benchmark input data generation 

---

cpp/src/io/comp/nvcomp_adapter.cpp

Closes https://github.com/rapidsai/cudf/issues/11878
This PR fixes an issue we noticed while trying to read a zstd parquet file where the cuDF code was causing a very large allocation to happen (something much higher than GPU memory like 50 or 60 GB).
We bisected the issue to this PR: https://github.com/rapidsai/cudf/pull/11652. 
The fix has been verified with the original file and Spark.
Thanks to @nvdbaranec, @jbrennan333, @mythrocks  and @vuule for help looking into this!

Fixes bug in temporary decompression space estimation before calling nvcomp

---

ci/checks/copyright.py

This PR improves the copyright check script to handle cases where the ancestor `branch-*` does not have an upstream set.

[REVIEW] Fix pre-commit copyright check

---

java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

closes https://github.com/rapidsai/cudf/issues/11882
Updated the `ArrowIPCTableWriter` to write en empty batch explicitly in the case of an empty table, because the Arrow IPC writer will write no batches out for this case, leading to an error as below when calling the `Pyarrow.Table.from_batches` without specifying a schema.
```
E                     File "pyarrow/table.pxi", line 1609, in pyarrow.lib.Table.from_batches
E                   ValueError: Must pass schema, or at least one RecordBatch
```
Signed-off-by: Liangcai Li <firestarmanllc@gmail.com>

[Java] ArrowIPCTableWriter writes en empty batch in the case of an empty table.

---

python/cudf/benchmarks/API/bench_dataframe.py

The version of `bench_isin` merged in #11125 used key and column names of the format `f"key{i}"` rather than the format `f"{string.ascii_lowercase[i]}"` as is used in the dataframe generator. As a result the `isin` benchmark using a dictionary argument short-circuits with no matching keys, and the `isin` benchmark using a dataframe argument finds no matches.
This PR also adjusts the `isin` arguments from `range(1000)` to `range(50)` to better match the input dataframe cardinality of 100. With `range(1000)`, every element matches but with `range(50)` only 50% of the elements match.

Conform "bench_isin" to match generator column names

---

cpp/benchmarks/stream_compaction/distinct.cpp
cpp/benchmarks/stream_compaction/unique.cpp

Use `state.set_cuda_stream` to set the stream for the nvbench benchmark. Then run `state.exec` on the public API instead of the detail API, e.g. `cudf::distinct` instead of `cudf::detail::distinct`.

Use public APIs in STREAM_COMPACTION_NVBENCH

---

python/cudf/cudf/core/index.py
python/cudf/cudf/tests/test_index.py

This PR raises a `NotImplementedError` for `ListColumn` or any new column that isn't supported by `cudf.Index` yet.

[REVIEW] Error on `ListColumn` or any new unsupported column in `cudf.Index`

---

ci/gpu/build.sh
codecov.yml

Many PRs are currently showing Codecov patch status check failures that appear to be the result of not uploading coverage reports for the string UDF tests. This PR should enable the missing coverage and ensure that we are actually measuring coverage of these code paths.

Add coverage for string UDF tests.

---

cpp/tests/io/type_inference_test.cu

Fixes an error in the `TypeInference.Timestamp` gtest where the `size` parameter was incorrect.
This error was found by the nightly builds and could be recreated using
```
compute-sanitizer --tool memcheck gtests/TYPE_INFERENCE_TEST --gtest_filter=TypeInference.Timestamp --rmm_mode=cuda
```

Fix memcheck error in TypeInference.Timestamp gtest

---

cpp/src/io/parquet/page_data.cu
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/reader_impl.cu
cpp/tests/io/parquet_test.cpp

Fixes https://github.com/NVIDIA/spark-rapids/issues/6718
There was a bug introduced recently https://github.com/rapidsai/cudf/pull/11752 where an insufficient check for whether an input column contained repetition information could cause incorrect results for column hierarchies with structs at the root.

Fix an issue reading struct-of-list types in Parquet.

---

cpp/src/io/json/json_column.cu
cpp/src/io/json/nested_json.hpp
cpp/src/io/json/nested_json_gpu.cu
cpp/tests/io/json_test.cpp
cpp/tests/io/json_tree.cpp
python/cudf/cudf/tests/test_json.py

Fixes `Unsupported column type` error during cudf column creation in Nested JSON reader due to empty list column.
During json tree creation, Empty list column does not have `device_json_column` child because it does have any rows, or a type.
This PR fixes the issue by creating an empty column as element child column. The list column still retains the null, and empty list information.

Fixes Unsupported column type error due to empty list columns in Nested JSON reader

---

cpp/src/io/text/bgzip_data_chunk_source.cu
cpp/tests/io/text/data_chunk_source_test.cpp

We accidentally checked the local offset against the compressed, not the uncompressed size. The new test failed prior to fixing the behavior.

Fix local offset handling in bgzip reader

---

cpp/src/io/text/multibyte_split.cu

In order to uniformize the interface for a future combined handling of byte ranges between read_csv and read_text, this PR replaces the `cutoff_offset` by a plain integer again, and handles finding the first out-of-bounds on the host side instead.

Handle `multibyte_split` byte_range out-of-bounds offsets on host

---

docs/cudf/source/user_guide/cupy-interop.ipynb
python/cudf/cudf/tests/test_dataframe.py

This fixes outdated documentation that refers to the `as_gpu_matrix` method, which was removed.

Fix documentation referring to removed as_gpu_matrix method.

---

docs/cudf/source/api_docs/string_handling.rst
python/cudf/cudf/_lib/strings/__init__.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/tests/test_string.py

Resolves: https://github.com/rapidsai/cudf/issues/10126
This PR adds `.str.find_multiple` API.

[REVIEW] Add `.str.find_multiple` API

---

conda/environments/cudf_dev_cuda11.5.yml
python/cudf/cudf/testing/dataset_generator.py
python/cudf/setup.py

The dependency pinning for `mimesis` in cudf's `setup.py` didn't match the conda environment. It was missing a pinning to `<4.1` from #8745. However, based on the conversation in #8551, this pinning of `<4.1` was only chosen because 4.1.0 wasn't yet available on conda-forge. Since the current version of mimesis is now 6.1.1, this PR updates the mimesis pinning to `>=4.1` and uses `generate_string` instead of `schoice`. I tested this locally with mimesis 6.1.1 and mimesis 4.1.0 and both passed tests.
Merge this PR concurrently with https://github.com/rapidsai/integration/pull/547.

Pin mimesis version in setup.py.

---

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md

This PR adds a section to the developer documentation about various libcudf design decisions that affect users. These policies are important for us to document and communicate consistently. I am not sure what the best place for this information is, but I think the developer docs are a good place to start since until we address #11481 we don't have a great way to publish any non-API user-facing libcudf documentation. I've created this draft PR to solicit feedback from other libcudf devs about other policies that we should be documenting in a similar manner. Once everyone is happy with the contents, I would suggest that we merge this into the dev docs for now and then revisit a better place once we've tackled #11481.
Partly addresses #5505, #1781.
Resolves #4511.

Initial draft of policies and guidelines for libcudf usage.

---

java/src/main/java/ai/rapids/cudf/RmmEventHandler.java
java/src/main/native/src/RmmJni.cpp
java/src/test/java/ai/rapids/cudf/RmmTest.java

This adds the method `boolean onAllocFailure(long sizeRequested, int retryCount)` to `RmmEventHandler`, to help handling code keep track of the number of times an allocation failure has been retried.
With this code callers can perform extra logic that depends on whether the callback was due to a brand new allocation failure, or one that has failed in the past and is being retried.
This will be used here: https://github.com/NVIDIA/spark-rapids/issues/6768

[JNI] Adds retryCount to RmmEventHandler.onAllocFailure

---

cpp/cmake/Modules/JitifyPreprocessKernels.cmake

On machines with multiple CUDA Toolkits installed it is possible to have a mismatch between the version of `nvcc` used to compile code and the version of `libnvrtc` used for the JIT code. This generally occurs when `LD_LIBRARY_PATH` points to a different version of the CUDA Toolkit.
We now explicitly specify what toolkit library directory to search when JIT code during libcudf compilation.

Tell jitify_preprocess where to search for libnvrtc

---

cpp/src/io/parquet/page_enc.cu
cpp/tests/io/parquet_test.cpp

This PR fixes an error that can occur when very small page sizes are used when writing Parquet files. #11551 changed from fixed 5000 row page fragments to a scaled value based on the requested max page size. For small page sizes, the number of fragments to process can exceed 64k. The number of fragments is used as the `y` dimension when calling `gpuInitPageFragments`, and when it exceeds 64k the kernel fails to launch, ultimately leading to an invalid memory access.

Fix writing of Parquet files with many fragments

---

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
cpp/doxygen/developer_guide/DOCUMENTATION.md
python/cudf/cudf/_lib/avro.pyx
python/cudf/cudf/_lib/io/utils.pyx
python/cudf/cudf/_lib/json.pyx
python/cudf/cudf/_lib/reduce.pyx
python/cudf/cudf/core/frame.py

For consistency across our documentation, this PR renames `libcudf++` to `libcudf`.

Rename libcudf++ to libcudf.

---

cpp/benchmarks/reduction/anyall.cpp
cpp/benchmarks/reduction/dictionary.cpp
cpp/benchmarks/reduction/reduce.cpp
cpp/benchmarks/reduction/scan.cpp
cpp/include/cudf/detail/scan.hpp
cpp/include/cudf/reduction.hpp
cpp/src/reductions/reductions.cpp
cpp/src/reductions/scan/scan.cpp
cpp/src/reductions/scan/scan.cuh
cpp/src/reductions/scan/scan_exclusive.cu
cpp/src/reductions/scan/scan_inclusive.cu
cpp/tests/quantiles/percentile_approx_test.cu
cpp/tests/reductions/collect_ops_tests.cpp
cpp/tests/reductions/list_rank_test.cpp
cpp/tests/reductions/rank_tests.cpp
cpp/tests/reductions/reduction_tests.cpp
cpp/tests/reductions/scan_tests.cpp
cpp/tests/reductions/tdigest_tests.cu
java/src/main/native/src/ColumnViewJni.cpp
python/cudf/cudf/_lib/cpp/reduce.pxd
python/cudf/cudf/_lib/reduce.pyx

There is almost never a good reason to pass arguments as `unique_ptr<T> const&`. Since those arguments cannot be modified, the only use case is accessing the underlying pointer, at which point the function better communicates its intent by accepting the underlying pointer/reference as an argument instead and is also more flexible as a result.
Resolves #10393

Accept const refs instead of const unique_ptr refs in reduce and scan APIs.

---

cpp/src/io/parquet/page_enc.cu

Closes https://github.com/rapidsai/cudf/issues/11916
cuda memcheck reports an OOB write in one of the tests. The root cause is an underallocated buffer for encoded pages.
This PR fixes the computation of the maximum size of data pages (RLE encoded) when dictionary encoding is used.
Other changes:
Refactored max RLE page size computation to avoid code repetition.
Use actual dictionary index width instead of (outdated) worst case.

Fix maximum page size estimate in Parquet writer

---

cpp/include/cudf/aggregation.hpp
cpp/tests/reductions/collect_ops_tests.cpp

Partially resolves https://github.com/rapidsai/cudf/issues/11329. This helps to align our default behaviors for null and NaN equality across APIs, specifically for `make_merge_sets_aggregation` in this PR. All functions should default to treating null values as equal to one another and NaN values as equal to one another.

Default to equal NaNs in make_merge_sets_aggregation.

---

cpp/benchmarks/string/filter.cpp
cpp/src/strings/strip.cu

Simplifies the `cudf::strings::strip` function to use the `cudf::make_strings_column` that accepts an iterator of pairs. This factory has a highly tuned gather implementation for building a strings column from an vector (iterator) of strings in device memory.
This was inspired by the review and work in #11946. This also gives a small improvement in the performance of small columns of large strings and even more improvement in large columns of large-ish strings for strip.
No function has changed just the internal implementation has been simplified.

Use gather-based strings factory in cudf::strings::strip

---

cpp/src/io/comp/nvcomp_adapter.cpp

C++17's "constexpr if" provides the same functionality as `#if` directive, as used in the nvcomp adapter.
This PR replaces macros with `constexpr` variables and uses them as conditions in "constexpr if" statements.

Replace most of preprocessor usage in nvcomp adapter with `constexpr`

---

cpp/include/cudf/io/types.hpp

These functions cannot throw exceptions.
Resolved #11399

Add missing noexcepts to column_in_metadata methods

---

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
cpp/doxygen/developer_guide/DOCUMENTATION.md

Brings the docs in line with the new way of getting the default stream in libcudf.

[skip gpuci] Replace default_stream_value with get_default_stream in docs.

---

cpp/CMakeLists.txt

Cleanup  some minor issues in the root cudf CMakeLists.txt. Make the seaching for `CUDA_SANITIZER` only occur when we are building tests as that doesn't need to be done for production builds. 
Move the gdb pretty print script logic to a separate region to better document what it is for.

Minor cleanup of root CMakeLists.txt for better organization

---

cpp/CMakeLists.txt

This PR centralizes handling of google benchmark during the build process by requesting it from rapids-cmake.

Use rapids-cmake for google benchmark.

---

cpp/src/io/comp/nvcomp_adapter.cpp

Reverts rapidsai/cudf#11980
The PR was made under the assumption that `if constexpr` branches can contain invalid code, if the branch is not taken. However, this only holds for templates.

Revert "Replace most of preprocessor usage in nvcomp adapter with `constexpr`"

---

cpp/src/lists/copying/gather.cu
cpp/src/partitioning/partitioning.cu

Fixes a couple source files that were calling gather by type-dispatching directly to the internal `column_gatherer` functor instead of using the `cudf::detail::gather` function(s). This simplifies the code and improves maintenance. For example, extra code to resolve the null-mask is eliminated since the appropriate `cudf::detail::gather` call does this automatically.
No function has changed, just code cleanup.

Fix some libcudf calls to cudf::detail::gather

---

cpp/include/cudf/dictionary/encode.hpp

Fixes the example code in the doxygen comment for `cudf::dictionary::encode` to use the correct API name.
No function has change -- just code comments that generate public doxygen content.
https://docs.rapids.ai/api/libcudf/stable/group__dictionary__encode.html#ga06997026d694784d613f4590563a8b33

Fix doxygen text for cudf::dictionary::encode

---

python/dask_cudf/dask_cudf/core.py

Removes unnecessary code from `dask_cudf.core._Frame` that is already handled in the super-class (`dask.dataframe.core._Frame`). By removing the unnecessary `__init__` logic from `dask_cudf`, we can avoid breakages from upstream changes like https://github.com/dask/dask/pull/9473.

Remove unnecessary code from dask-cudf _Frame

---

cpp/benchmarks/io/text/multibyte_split.cpp
cpp/include/cudf/io/text/multibyte_split.hpp
cpp/src/io/text/multibyte_split.cu
cpp/tests/io/text/multibyte_split_test.cpp
python/cudf/cudf/_lib/cpp/io/text.pxd
python/cudf/cudf/_lib/text.pyx
python/cudf/cudf/io/text.py
python/cudf/cudf/tests/test_text.py
python/cudf/cudf/utils/ioutils.py

This adds a `strip_delimiters` post-processing option to `read_text`. I needed to implement some lightweight striping because a thread-per-row parallelization of the string gather gave pretty bad performance.
For consistency, I also removed the special-case handling of delimiters at the end (previously adding an empty row), to match the read_csv behavior.
Benchmark results:
```
benchmarks/MULTIBYTE_SPLIT_NVBENCH --axis size_approx[pow2]=30 --axis byte_range_percent=100 --axis T=device --axis delim_size=4
```
|   T    | strip_delimiters | delim_percent |    size_approx    |   CPU Time  | Noise | Peak Memory Usage | Encoded file size |
|--------|------------------|---------------|-------------------|------------|-------|-------------------|-------------------|
| device |                0 | …

Add `strip_delimiters` option to `read_text`

---

cpp/src/io/text/multibyte_split.cu
cpp/src/io/utilities/output_builder.cuh
cpp/tests/io/text/multibyte_split_test.cpp

This PR moves the `output_builder` and `split_device_span` classes out of `multibyte_split` and adds an iterator for the `split_device_span`, enabling it to be used directly in Thrust algorithms.
I also included a fix from #11875 to make the integration easier once that is merged.

Refactor multibyte_split `output_builder`

---

docs/cudf/source/api_docs/general_functions.rst

This PR resolves #12012 by adding `cudf.pivot_table` and `cudf.crosstab` to the documentation.

Add pivot_table and crosstab to docs.

---

cpp/benchmarks/io/text/multibyte_split.cpp
cpp/include/cudf/io/text/data_chunk_source_factories.hpp
cpp/src/io/text/data_chunk_source_factories.cpp
cpp/tests/io/text/data_chunk_source_test.cpp

With `datasource` being more generic in its interface than `data_chunk_source`, this PR adds a wrapper that wraps a `datasource` in a `data_chunk_source` for use in `multibyte_split`. Its host read implementation is based on the file `data_chunk_source`

Provide `data_chunk_source` wrapper for `datasource`

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_indexing.py
python/dask_cudf/dask_cudf/tests/test_core.py

Fixes #11930
I can't figure out the purpose of these lines, so let's try removing them and run CI.
I haven't followed git blame back far enough to know the full story of these lines, but they originate at least three years ago:
https://github.com/rapidsai/cudf/pull/2208/files#diff-5f58cf9dfe537ce53c6481f690ba66ff10807da04ad82df1c79c6d112d19c08b

Fix bug where `df.loc` resulting in single row could give wrong index

---

cpp/src/hash/hash_allocator.cuh

The `managed_allocator` class is not used anywhere. All uses of cuco maps or the `concurrent_unordered_map` just use the `default_allocator`.

Remove unused `managed_allocator`

---

docs/cudf/source/api_docs/dataframe.rst
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_reshape.py

This PR adds the method `DataFrame.pivot_table` to enhance pandas API compatibility. It uses the exact same arguments as `cudf.pivot_table` but automatically supplies the first argument (a DataFrame).
Related: #11314

Add DataFrame.pivot_table.

---

.github/workflows/add_to_project.yml

This PR adds a small GitHub action to automatically add new issues and PRs to the cudf GitHub project. It does not impact existing issues/PRs.

New GHA to add issues/prs to project board

---

python/cudf/cudf/utils/utils.py

Add deprecation warning for set_allocator.

---

cpp/benchmarks/synchronization/synchronization.hpp
cpp/src/hash/hash_allocator.cuh
cpp/src/hash/helper_functions.cuh
cpp/src/hash/managed.cuh
cpp/src/unary/unary_ops.cuh

This PR adapts a few files using header guards with `#ifndef… #define` to use `#pragma once` instead. This establishes a more consistent code style for the library.

Use pragma once

---

cpp/include/cudf/detail/scatter.cuh
cpp/include/cudf/dictionary/detail/concatenate.hpp
cpp/include/cudf/dictionary/detail/encode.hpp
cpp/include/cudf/dictionary/detail/replace.hpp
cpp/include/cudf/dictionary/detail/search.hpp
cpp/include/cudf/dictionary/detail/update_keys.hpp
cpp/src/copying/copy_range.cu
cpp/src/copying/scatter.cu
cpp/src/dictionary/add_keys.cu
cpp/src/dictionary/remove_keys.cu
cpp/src/dictionary/replace.cu
cpp/src/dictionary/set_keys.cu
cpp/src/filling/fill.cu
cpp/src/replace/clamp.cu
cpp/src/replace/replace.cu
cpp/src/search/contains_column.cu
cpp/src/search/contains_scalar.cu
cpp/src/search/search_ordered.cu
cpp/tests/dictionary/search_test.cpp
cpp/tests/replace/replace_nulls_tests.cpp

Removes default parameters from the `cudf::dictionary::detail` functions. Most of these were allowing for the default memory-resource which is unnecessary. One non-stream, non-mr parameter was defaulted but the default was never used.
Reference #11967

Remove default parameters for cudf::dictionary::detail functions

---

fetch_rapids.cmake
python/cudf/CMakeLists.txt
python/cudf/cudf/_lib/CMakeLists.txt
python/cudf/cudf/_lib/io/CMakeLists.txt
python/cudf/cudf/_lib/nvtext/CMakeLists.txt
python/cudf/cudf/_lib/strings/CMakeLists.txt
python/cudf/cudf/_lib/strings/convert/CMakeLists.txt
python/cudf/cudf/_lib/strings/split/CMakeLists.txt
python/strings_udf/strings_udf/_lib/CMakeLists.txt

This PR leverages a new feature of rapids-cmake to avoid needing to manually set the RPATHs for all extension modules individually, instead just pointing to a directory once and then letting rapids-cmake automatically handle the rest. This approach is a lot less error-prone since developers do not need to keep track of the relative paths in each CMakeLists.txt file.

Leverage rapids_cython for more automated RPATH handling

---

pyproject.toml

This PR fixes an issue where `black` would not respect the exclusions in `pyproject.toml` when run via `pre-commit`. When executing the hook, `pre-commit` explicitly lists all changed files and provides them as positional arguments to `black`. When `black` receives explicit filenames, it does not respect the `exclude` settings but _does_ respect the `force-exclude` settings added in `black 20.8b1`. See issue: https://github.com/psf/black/issues/438 and PR: https://github.com/psf/black/pull/1032.
cc: @csadorf for cuML

Force black exclusions for pre-commit.

---

.pre-commit-config.yaml
README.md
docs/cudf/source/user_guide/10min.ipynb
docs/cudf/source/user_guide/missing-data.ipynb
python/cudf/cudf/_lib/search.pyx
python/cudf/cudf/_lib/strings/convert/convert_urls.pyx
python/cudf/cudf/_lib/strings/padding.pyx
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/frame.py
python/cudf/cudf/core/groupby/groupby.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/reshape.py
python/cudf/cudf/core/series.py
python/cudf/cudf/testing/testing.py
python/cudf/cudf/utils/docutils.py
python/cudf/cudf/utils/ioutils.py
python/custreamz/README.md

This PR removes all "smart quotes" from the library by enforcing a pre-commit hook.
Smart quotes typically arise from copying rendered docstrings from Pandas, because Sphinx automatically transforms straight quotes into smart quotes when rendering the docs as HTML. However, the use of smart quotes is undesirable in code, and makes it difficult to do find-replace transformations if straight and smart quotes are mixed.
I have made suggestions to fix this several times before, so I am making the suggestions more permanent and automatically enforceable via a pre-commit style check:
- https://github.com/rapidsai/cudf/pull/12025#discussion_r1008536741
- https://github.com/rapidsai/cudf/pull/9817#discussion_r791988101
- https://github.com/rapidsai/cudf/pull/9571#discussion_r741309852

Remove smart quotes from all docstrings.

---

cpp/benchmarks/io/parquet/parquet_writer.cpp

Adds `statistics_freq::STATISTICS_COLUMN` to list of parquet writer options to benchmark.  This should have been included in #11302.

Add full page indexes to Parquet writer benchmarks

---

cpp/CMakeLists.txt

The current version of nvbench is not compatible with the latest changes to fmt. This PR decouples us from needing to wait on upstreaming the compatibility changes to nvbench. These changes are necessary for building libcudf benchmarks until then.

Force using old fmt in nvbench.

---

python/strings_udf/cpp/CMakeLists.txt
python/strings_udf/strings_udf/__init__.py

In the context of distributed, `strings_udf` needs to import and set itself up without creating a CUDA context, as this can interfere with up the way the network is being set up. In this situation it can't use it's normal mechanism (which requires a context) to query the compute capability of the device, and it falls back on an environment variable `STRINGS_UDF_CC` that it needs to be passed from dask instead. A user can set this and their code will work no problem, but we also need some default configuration that just works when someone builds their code. Without knowing their setup beforehand this can be problematic, as such I originally added the default value of `cc=52` when the environment variable isn't set. This was however not exactly correct for a few reasons:
- It should be 60 I …

Allow falling back to `shim_60.ptx` by default in `strings_udf`

---

python/cudf/cudf/core/column/decimal.py
python/cudf/cudf/tests/test_decimal.py

[REVIEW] Remove overflow error during decimal binops

---

cpp/src/io/json/json_column.cu
python/cudf/cudf/tests/test_json.py

Fixes List offset end last item write condition bug
If there is a list row followed by empty list in next row, the previous row's end is not written to offsets.

Fixes List offset bug in Nested JSON reader

---

python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/scalar.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_setitem.py

To mimic pandas, we must upcast a column to the numpy result_type of the column itself and the input value dtype. This previously occurred in all relevant cases except when the index provided to __setitem__ was a single integer (originally introduced in #2442). Closes #11901.

Fix type casting in Series.__setitem__

---

cpp/src/io/json/experimental/read_json.cpp
cpp/src/io/json/reader_impl.cu

Issue is that `json::experimental::ingest_raw_data` took double the time of `json::ingest_raw_data` for same data.
After replacing tertiary operator with `if` `else`, runtime for 500 MB file is same as `json::ingest_raw_data`
I suspect, RVO (copy elision) is skipped while using tertiary operator.

Fix ingest_raw_data performance issue in Nested JSON reader due to RVO

---

cpp/src/io/utilities/file_io_utilities.cpp
cpp/src/io/utilities/file_io_utilities.hpp

Currently, creating a cufile `datasource` or `data_sink` silently fails if libcudf was built without the cuFile headers. This is expected behavior when the `LIBCUDF_CUFILE_POLICY` is not set, or is set to and value other than "ALWAYS". However, with "ALWAYS", there should be no fallback from GDS.
This PR adds a check to fail loudly when `LIBCUDF_CUFILE_POLICY=="ALWAYS"` cannot be enforced because of missing dependency (cuFile).

Throw an error when libcudf is built without cuFile and `LIBCUDF_CUFILE_POLICY` is set to `"ALWAYS"`

---

ci/benchmark/build.sh
ci/gpu/build.sh

This PR updates `dask` nightly install to correctly install the packages.

[REVIEW] Move and update `dask` nigthly install in CI

---

cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
cpp/include/cudf_test/cudf_gtest.hpp
cpp/tests/copying/get_value_tests.cpp
cpp/tests/copying/segmented_gather_list_tests.cpp
cpp/tests/error/error_handling_test.cu
cpp/tests/groupby/count_scan_tests.cpp
cpp/tests/groupby/keys_tests.cpp
cpp/tests/groupby/rank_scan_tests.cpp
cpp/tests/io/json_tree.cpp
cpp/tests/io/nested_json_test.cpp
cpp/tests/lists/stream_compaction/apply_boolean_mask_tests.cpp
cpp/tests/reductions/rank_tests.cpp
cpp/tests/sort/segmented_sort_tests.cpp

We should not be encouraging users to rely specific error messages. Anywhere that is currently doing so is likely an indication that libcudf should be throwing a more specific type of exception instead of just a `cudf::logic_error`. This PR removes the testing utilities that were previously used for this purpose and reworks the relevant tests.
Related to #10200.

Remove macros that inspect the contents of exceptions

---

cpp/src/copying/concatenate.cu
cpp/src/rolling/detail/rolling.cuh
cpp/src/rolling/jit/kernel.cu
cpp/src/strings/copying/concatenate.cu
python/custreamz/README.md

This PR updates some documentation and removes some compatibility layers referencing CUDA 10, which is no longer supported by the package.

Remove CUDA 10 compatibility code.

---

docs/cudf/source/user_guide/cupy-interop.ipynb
docs/cudf/source/user_guide/guide-to-udfs.ipynb
python/cudf/cudf/core/dataframe.py

This updates links that point to the Numba documentation to use the new domain.

Update Numba docs links.

---

docs/cudf/source/api_docs/dataframe.rst
docs/cudf/source/api_docs/series.rst

In https://github.com/rapidsai/cudf/pull/11435, the `truncate` API was added but I had a review comment(to add it docs) that I forgot to publish. This PR adds `truncate` to the docs page.

[REVIEW] Add `truncate` API to python doc pages

---

python/dask_cudf/dask_cudf/backends.py
python/dask_cudf/dask_cudf/io/json.py
python/dask_cudf/dask_cudf/io/tests/test_json.py

Exposes the `engine` argument in `dask_cudf.read_json`, enabling `dask_cudf.read_json(... engine="cudf_experimental")` for nested json data.
TODO (~maybe this PR?~):

Expose engine argument in dask_cudf.read_json

---

cpp/src/io/csv/reader_impl.cu
cpp/tests/io/csv_test.cpp

There are two options to get the names of columns in a CSV file - header or the first row. In case the first row is used, names are generated, and the only part of the row that is used is the number of detected columns.
This PR fixes the corner case where a blank line after the first (non-header) row causes the reader to detect an additional column (and return an additional column of nulls). 
The fix is to break when there is a terminator character within the first row; this only happens with blank row(s) after the first data row. The reader already does this when reading column names from a header, this PR just removes this difference in behavior that was causing the bug.

Fix reading of CSV files with blank second row

---

python/cudf/cudf/core/_compat.py
python/cudf/cudf/testing/_utils.py
python/cudf/cudf/tests/test_gcs.py
python/cudf/cudf/tests/test_hdfs.py
python/cudf/cudf/tests/test_orc.py
python/cudf/cudf/tests/test_s3.py

This PR changes calls going via `pyarrow` and then `to_pandas` to directly call `pd.read_orc`. How-ever since `pd.read_orc` was added in pandas 1.0, we will need to version the call to this constructor. This PR does that.
Partially contributes to #11540

[REVIEW] First pass of `pd.read_orc` changes in tests

---

cpp/benchmarks/join/conditional_join.cu

The `CONDITIONAL_FULL_JOIN_BENCHMARK_DEFINE` benchmark category was mapping to `cudf::conditional_inner_join` instead of `cudf::conditional_full_join`

Fix conditional_full_join benchmark

---

cpp/src/strings/regex/regexec.cpp

Fixes error in `working_memory_size()` member function passing the parameters incorrectly.
This was introduce in #11927 and found in the nightly compute-sanitizer check.
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/branches/job/cudf-gpu-build-branch-22.12/19/CUDA=11.5/testReport/junit/cudamemcheck/STRINGS_TEST/StringsContainsTests_ContainsTest/

Fix regex working-memory-size refactor error

---

notebooks/10min.ipynb
notebooks/cupy-interop.ipynb
notebooks/guide-to-udfs.ipynb
notebooks/missing-data.ipynb

Adds symlinks to notebooks from the user guide as requested by @taureandyernv.
Going forward, new notebooks added to the user guide directory should also be symlinked in `/notebooks`.

Add symlinks to notebooks.

---

java/src/main/java/ai/rapids/cudf/ColumnView.java
java/src/main/native/src/ColumnViewJni.cpp

cudf `substring(column, int, int)` has its own behavior when `end` is -1 (a valid position pointing to the last char), which is different from that in JNI. So JNI should not override it.
Besides, JNI's behavior does not match its doc when `end` is "-1". According to the doc, the last char should not be included in the result substring. But currently it does. 
Signed-off-by: Liangcai Li <liangcail@nvidia.com>

[Java] Add JNI for `substring` without 'end' parameter.

---

java/src/main/java/ai/rapids/cudf/MemoryBuffer.java
java/src/test/java/ai/rapids/cudf/MemoryBufferTest.java

This PR adds an EventHandler to `MemoryBuffer` with a single method `onClosed`. This is invoked during the `close` call, but after the `refCount` has been updated.
I am also making `getRefCount` public in this PR. Spill code in the RAPIDS Accelerator for Spark could likely assert/require that refCount==1 when taking in a new buffer to be spillable. This last change is a nice to have.

[JNI] Adds an EventHandler to Java MemoryBuffer to be invoked on close

---

python/cudf/cudf/_lib/copying.pyx
python/cudf/cudf/tests/test_setitem.py

When trying to set a length-one range with a length-one array, an off-by-one error in `copying.copy_range` meant that the value was discarded. Fix that, and tidy up the semantics of `copy_range` a little while we're here. Closes #12073.

Fix singleton-range `__setitem__` edge case

---

python/dask_cudf/dask_cudf/groupby.py
python/dask_cudf/dask_cudf/tests/test_groupby.py

This PR corresponds to the Dask-cudf version of https://github.com/dask/dask/pull/9442, which was found to improve the performance of many groupby-based workflows. After this PR, 
```python
import dask_cudf
path = "/criteo-dataset/day_0.parquet"
ddf = dask_cudf.read_parquet(path, split_row_groups=10)
ddf.groupby("C1").agg({"C2": "mean"}).compute()
```

Enable automatic column projection in groupby().agg

---

cpp/cmake/Modules/JitifyPreprocessKernels.cmake
cpp/cmake/thirdparty/get_jitify.cmake

Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

---

cpp/include/cudf/column/column.hpp
cpp/include/cudf/column/column_factories.hpp
cpp/src/column/column_factories.cpp

This fixes #12116
This just adds in a few checks for negative sizes to avoid any issues with rounding errors and also helps us detect errors sooner. It will not fix small negative allocations for device buffers directly.

Add in negative size checks for columns

---

python/strings_udf/cpp/src/strings/udf/shim.cu
python/strings_udf/strings_udf/lowering.py

In `strings_udf`, functions that return strings are built around c++ methods that return a `cudf::strings::udf::udf_string` object. However due to requiring external `C` linkage, our shim functions need to work by accepting a pointer to a preallocated `udf_string` object and setting the result into the memory it points to before returning. 
This piece of memory is allocated based off our `UDFString` extension class datamodel and while it is set up to be the right size, simply allocating it does not actually call the underlying `udf_string` default constructor so the memory isn't necessarily initialized in the same way a proper `udf_string` would initialize it. 
This can lead to some unsafe behavior when we try and assign the result. This PR changes it so that whenever we need to allocate …

Safely allocate `udf_string` pointers in `strings_udf`

---

python/cudf/cudf/core/subword_tokenizer.py

In the upcoming CuPy 12 cp.clip slightly changed the function signature: https://github.com/cupy/cupy/blob/6d857add3d46368705e133121cf49153039952e9/cupy/_math/misc.py#L147
This PR is still valid for CuPy 11 but will also satisfy the upcoming release

Update cp.clip call 

---

ci/checks/headers_test.sh

`-printf` is a GNU find extension, so `headers_test.sh` fails on systems where binutils is a BSD toolchain.
To get around this, use sed to obtain the effect of `-printf`.

Don't rely on GNU find in headers_test.sh

---

cpp/cmake/thirdparty/get_dlpack.cmake
python/cudf/CMakeLists.txt
python/cudf/cudf/_lib/CMakeLists.txt

As brought up in #12081 it is possible to have python build failures due to no include paths to dlpack being provided. This fixes the issue by ensure that the DLPACK_INCLUDE_DIR is propagated down to the interop target.
We don't run into this issue with conda, since the dlpack headers are inside the conda include dir which is already being provided to the compiler.

Ensure dlpack include is provided to cudf interop lib

---

conda/environments/all_cuda-115_arch-x86_64.yaml
conda/recipes/cudf/conda_build_config.yaml
conda/recipes/cudf_kafka/meta.yaml
conda/recipes/libcudf/conda_build_config.yaml
conda/recipes/strings_udf/conda_build_config.yaml
dependencies.yaml
python/cudf/pyproject.toml

Don't use CMake 3.25.0 as it has a show stopping FindCUDAToolkit bug

Don't use CMake 3.25.0 as it has a show stopping FindCUDAToolkit bug

---

python/cudf/cudf/tests/test_binops.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/tests/test_reshape.py

To save CI running time, this PR reduce the tests marked `spilling` drastically. 
An alternative to https://github.com/rapidsai/cudf/pull/12187

Reduce number of tests marked `spilling` 

---

ci/gpu/java.sh

This PR removes some Python dependencies from the Java CI scripts. It does not appear that these dependencies are needed. As we prepare to migrate this job to GitHub Actions in #12002, this cleanup will help us validate that we aren't dropping any real testing dependencies.

Remove Python dependencies from Java CI.

---

java/src/main/java/ai/rapids/cudf/HostColumnVector.java

Adds in a few new java APIs that can speed up appending lists of bytes to host data before it goes to the GPU.

Adds in new java APIs for appending byte arrays to host columnar data

---

cpp/src/sort/segmented_sort.cu
cpp/tests/sort/segmented_sort_tests.cpp

Adds a workaround for `cudf::segmented_sort` when following the optimized path with a the key type of `bool`.
Here, the optimized path is avoided by checking the column-type.
A gtest is also included for this case.
The workaround can be removed once https://github.com/NVIDIA/cub/issues/594 is fixed and available for libcudf.
Closes #12201

Workaround for CUB segmented-sort bug with boolean keys

---

python/cudf/cudf/tests/test_spilling.py

Based on @vyasr's [review](https://github.com/rapidsai/cudf/pull/12106#pullrequestreview-1183334305), I am cleaning up the spilling tests. Hopefully making them more readable. 
Notice, I am targeting `branch-23.02` because of code freeze but maybe we should target `branch-22.12` since it implements spilling?

Clean up of `test_spilling.py`

---

cpp/include/cudf_test/column_utilities.hpp
cpp/include/cudf_test/table_utilities.hpp
cpp/tests/ast/transform_tests.cpp
cpp/tests/column/bit_cast_test.cpp
cpp/tests/column/column_test.cu
cpp/tests/copying/concatenate_tests.cu
cpp/tests/copying/gather_list_tests.cpp
cpp/tests/copying/pack_tests.cpp
cpp/tests/copying/slice_tests.cpp
cpp/tests/copying/split_tests.cpp
cpp/tests/copying/utility_tests.cpp
cpp/tests/encode/encode_tests.cpp
cpp/tests/groupby/groupby_test_util.hpp
cpp/tests/io/csv_test.cpp
cpp/tests/quantiles/percentile_approx_test.cpp
cpp/tests/rolling/lead_lag_test.cpp
cpp/tests/strings/replace_tests.cpp
cpp/tests/structs/structs_column_tests.cpp
cpp/tests/utilities/column_utilities.cu
cpp/tests/utilities/table_utilities.cu
cpp/tests/utilities_tests/column_utilities_tests.cpp
cpp/tests/utilities_tests/lists_column_wrapper_tests.cpp

w.r.t. #11007
This PR moves `cudf::test::expect_column/table*` utilities to the `detail` namespace and replace their use cases with corresponding macros when possible.

Replace column/table test utilities with macros

---

python/cudf/cudf/_lib/io/CMakeLists.txt

This PR ensures that numpy include directories are visible to the cuIO Cython TUs. #12096 changed the way that numpy was being found but did not update this line. The old variable is automatically being created by scikit-build's Python code, so as long as skbuild correctly finds the libraries the old variable still works, but we do not want to rely on that since it is not true in all environments.

Fix include line for IO Cython modules

---

python/cudf/cudf/core/buffer/spill_manager.py
python/cudf/cudf/tests/test_spilling.py

Fixing bug in `SpillManager.spill_device_memory` where it would spill more than the limit.

Fix spill to device limit

---

python/cudf/cudf/core/join/join.py
python/cudf/cudf/tests/test_joining.py

Previously, if any of the join keys were indices, we assumed that they
all were, and provided an empty set of key columns with matching names
in the left and right dataframe. This does the wrong thing for mixed
join keys (on a combination of index and normal columns), producing
more output columns than is correct. To avoid this, only skip matching
key names if they name indices.
Closes #11550.

Only exclude join keys that are indices from key columns

---

cpp/include/cudf/detail/quantiles.hpp
cpp/include/cudf/detail/sorting.hpp
cpp/src/quantiles/quantiles.cu
cpp/src/quantiles/tdigest/tdigest_aggregation.cu
cpp/src/reductions/reductions.cpp

Removes the default parameter declarations from `cudf::detail::sort`, `cudf::detail::sorted_order`, `cudf::detail::sort_by_key`,  `cudf::detail::stable_sorted_order`, and `cudf::detail::stable_sort_by_key` as well as `cudf::detail::quantile`, `cudf::detail::quantiles` and `cudf::detail::percentile_approx`
Reference comment: https://github.com/rapidsai/cudf/pull/12237#issuecomment-1329538871
Also fixes incorrect stream parameter passed within a `quantiles.cu` detail function.
No function has been added, modified, or changed.

Remove default parameters from cudf::detail::sort function declarations

---

cpp/include/cudf/detail/structs/utilities.hpp
cpp/src/groupby/sort/group_scan_util.cuh
cpp/src/reductions/scan/scan_inclusive.cu
cpp/src/scalar/scalar.cpp
cpp/src/structs/structs_column_factories.cu
cpp/src/structs/utilities.cpp
cpp/src/table/row_operators.cu
cpp/tests/io/parquet_chunked_reader_test.cpp
cpp/tests/join/join_tests.cpp
cpp/tests/structs/utilities_tests.cpp

There are several overloads of these functions which work differently. They are classified into 2 groups:
* `superimpose_parent_nulls(null_mask, null_count, column)`: Performs superimposing nulls from somewhere else into the input column,
* `superimpose_parent_nulls(column_view/table_view)`: Perform superimposing nulls of the input column(s) into their children columns-the input root column(s) are not affected.
That is confusing. They should have different names to reflect their purposes. This PR renames these groups into more meaningful names: `superimpose_nulls` and `push_down_nulls`. No implementation has been changed.
This also supports https://github.com/rapidsai/cudf/issues/12027.

Rename `cudf::structs::detail::superimpose_parent_nulls` APIs

---

cpp/tests/io/json_chunked_reader.cpp

This issue was introduced in https://github.com/rapidsai/cudf/pull/12017 merged, which triggers compiler error on some systems:
```
../tests/io/json_chunked_reader.cpp: In function 'std::vector<cudf::io::table_with_metadata> skeleton_for_parellel_chunk_reader(cudf::host_span<std::unique_ptr<cudf::io::datasource> >, const cudf::io::json_reader_options&, int32_t, rmm::cuda_stream_view, rmm::mr::device_memory_resource*)':
../tests/io/json_chunked_reader.cpp:78:19: error: loop variable '<structured bindings>' creates a copy from type 'const std::pair<int, int>' [-Werror=range-loop-construct]
78 |   for (auto const [chunk_start, chunk_end] : record_ranges) {
|                   ^~~~~~~~~~~~~~~~~~~~~~~~
../tests/io/json_chunked_reader.cpp:78:19: note: use reference type to prevent copying
78 | …
```

Fix compile issue in `json_chunked_reader.cpp`

---

python/cudf/cudf/_lib/copying.pyx
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/io/avro.py
python/cudf/cudf/io/orc.py
python/cudf/cudf/tests/test_array_ufunc.py
python/cudf/cudf/tests/test_binops.py
python/cudf/cudf/tests/test_dataframe.py
python/cudf/cudf/utils/ioutils.py
python/cudf/cudf/utils/utils.py
python/dask_cudf/dask_cudf/core.py

This PR removes various pieces of deprecated functionality.

Remove deprecated code for 23.02

---

cpp/tests/reductions/collect_ops_tests.cpp
cpp/tests/reductions/rank_tests.cpp
cpp/tests/reductions/segmented_reduction_tests.cpp
cpp/tests/reductions/tdigest_tests.cu

Fixes reduction gtests source files coded in namespace `cudf::test`
No function or test has changed just the source code reworked per namespaces.
Fixing this ahead of any changes for #10432 

Fix reduction gtests coded in namespace cudf::test

---

.github/workflows/pr.yaml

We are seeing a rate limit on the `pr-builder` workflow. Rather than using `upsidr/merge-gatekeeper` to poll for workflow completion, we just define the `needs:` for the `pr-builder` workflow to ensure all dependencies are met. @ajschmidt8 is opening a companion PR to modify the [upstream workflow](https://github.com/rapidsai/shared-action-workflows/blob/main/.github/workflows/pr-builder.yaml) to simply `exit 0` if all requirements are met.

Define needs for pr-builder workflow.

---

ci/cpu/build.sh
ci/gpu/build.sh

This PR re-adds some environment variables to the Jenkins scripts that are missing from the Jenkins CI images in order to re-enable `sccache`. These were accidentally removed in #12002.
All of these Jenkins scripts will be removed once Jenkins is disabled.

Re-enable `sccache` for Jenkins builds

---

cpp/src/io/utilities/parsing_utils.cuh
cpp/tests/io/csv_test.cpp
cpp/tests/io/json_test.cpp
python/cudf/cudf/tests/test_csv.py

This PR changes behaviour of nested json reader to return null element on parsing error of numeric types.
Breaking behaviour in read_csv, and read_json:
- old behaviour: parsing error returns quiet NAN for that type as result for that row.
- new behaviour: parsing error returns null for that row.
Moved commit 0e45d13  https://github.com/rapidsai/cudf/pull/12022#issuecomment-1314569271 to 23.02

Null element for parsing error in numeric types in JSON, CSV reader

---

cpp/include/cudf/binaryop.hpp
cpp/src/binaryop/compiled/operation.cuh
cpp/tests/binaryop/binop-compiled-test.cpp
cpp/tests/binaryop/util/operation.h
python/cudf/cudf/tests/test_binops.py

Previously (since c8b897ccd) floor division for all pairs of arguments
was implemented by promoting both arguments to double, dividing, and
then taking the floor.
This produces results when both operands are integral that sometimes
don't match the behaviour of normal floor division in any of the
target languages that cuDF supports. Specifically for int64 operands,
any time an operand is larger than $2^{53}$, the conversion to double is
not injective and so information is lost.
To address this, implement SFINAE overloads for the FloorDiv device
functor that use standard C++ type promotion semantics for division
with mixed type operands. In the case of integral types with same
sign, this is then just standard division; if the signs are mixed, we
round towards negative infinity; if either …

Floor division uses integer division for integral arguments

---

python/cudf/cudf/core/reshape.py
python/cudf/cudf/tests/test_concat.py

The sort argument to `concat` requests a sort of the non-concatenated axis.
Previously this was handled correctly except when passing only a single object
to concatenate.
Closes #12132.

Correct behaviour of sort in `concat` for singleton concatenations

---

cpp/tests/iterator/pair_iterator_test_numeric.cu

Fixes NumericPairIteratorTest for float values that started occurring randomly.
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/prb/job/cudf-gpu-test/CUDA=11.5,GPU_LABEL=driver-495,LINUX_VER=ubuntu20.04,PYTHON=3.9/12008/testReport/junit/(root)/NumericPairIteratorTest_9/mean_var_output/
The error is an accumulation of 5000 floating-point operations (addition and multiplication) and compares the result with the same operations in a single CPU thread. The error accrued over this many operations exceeded the 0.001 expected limit due to the non-deterministic behavior of floating point operations accumulated in parallel device threads.
The gtest logic was changed to only include non-fractional data values for floating point tests. This eliminates the non-deterministic …

Fix NumericPairIteratorTest for float values

---

ci/check_style.sh

It doesn't seem like this `set +e` belongs in this script. It may prevent errors from the rest of the script from being properly reported.

Fix `check_style.sh` script

---

docs/cudf/source/api_docs/dataframe.rst

The `DataFrame.eval` method was not being added to the documentation.

Add eval to docs.

---

cpp/src/io/json/experimental/read_json.cpp
cpp/src/io/json/reader_impl.cu
cpp/tests/io/json_test.cpp

`read_json` implementation cannot read multiple inputs when inputs are compressed or not in JSON lines format.
This PR adds explicit checks to return a clear error messages in unsupported cases.

Improved error reporting when reading multiple JSON files

---

cpp/src/io/csv/reader_impl.cu
cpp/src/io/json/reader_impl.cu
cpp/src/io/utilities/type_inference.cuh
cpp/tests/io/json_test.cpp
cpp/tests/io/type_inference_test.cu
python/cudf/cudf/tests/test_json.py

When there are nulls in an integer column, libcudf csv, json readers infer it as float column (similar to pandas).
Pandas uses `float nan` because default types do no have null representation. But cuDF has null representation on all types.
Integer column with nulls in CSV or JSON will be infered as nullable integer column, instead of current behaviour of inferring as float64 column.

CSV, JSON reader to infer integer column with nulls as int64 instead of float64

---

python/strings_udf/strings_udf/lowering.py

We can't build the table pointers at import time, since that creates a
cuda context. Since libcudf caches these instances internally, just
call the functions directly.
Closes #12340.

[HOTFIX] strings_udf: use libcudf caching of character tables

---

python/cudf/cudf/core/index.py
python/cudf/cudf/core/multiindex.py
python/cudf/cudf/tests/test_index.py

Fix warnings in test_index.py

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/index.py
python/cudf/cudf/core/single_column_frame.py
python/cudf/cudf/tests/test_monotonic.py

One note with these deprecations. pandas has a special value used for parameters that are defaulted, and as a result explicitly passing None will throw a warning. We don't do this, hence the difference in the warnings contexts I use for our calls vs pandas (`pytest.warns` vs `expect_warning_if`). I didn't feel like this was worth commenting on in every place, but I can if reviewers want.

Fix warnings in test_monotonic.py

---

conda/recipes/libcudf/meta.yaml
cpp/CMakeLists.txt
cpp/include/cudf/lists/detail/reverse.hpp
cpp/include/cudf/lists/reverse.hpp
cpp/src/lists/reverse.cu
cpp/src/lists/utilities.cu
cpp/src/lists/utilities.hpp
cpp/tests/CMakeLists.txt
cpp/tests/lists/reverse_tests.cpp
java/src/main/native/src/ColumnViewJni.cpp
java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

This implements `lists::reverse` that output a lists column in which each list is generated by reversing the order of the elements in the corresponding input list.
Example:
```
s = [ [1, 2, 3], [], null, [4, 5, null] ]
r = reverse(s)
r is now [ [3, 2, 1], [], null, [null, 5, 4] ]
```
This is to support https://github.com/NVIDIA/spark-rapids/issues/4375 and https://github.com/NVIDIA/spark-rapids/issues/6885.

Implement `lists::reverse`

---

ci/gpu/build.sh
conda/environments/all_cuda-115_arch-x86_64.yaml
dependencies.yaml
python/cudf/cudf/tests/test_subword_tokenizer.py
python/cudf/setup.py

This pinning is necessary because other testing dependencies require arrow (currently, transformers has a transitive dependency on it) and don't include a pinning as strict as ours, resulting in a newer arrow package (arrow 10) being installed. When we attempt to install our cudf/libcudf packages in CI, it should be able to downgrade to arrow 9, but the downgrade fails because changes in arrow's package structure in arrow 10 include the creation of a new libarrow package (arrow-cpp was renamed to libarrow) and libarrow has no equivalent in arrow 9. As a result, conda does not see a way to downgrade it, and it also does not see a way to satisfy its dependencies if the rest of the arrow packages are downgraded to arrow 9 (because libarrow is tied to arrow 10 packages), so the conda solve …

Pin arrow 9 in testing dependencies to prevent conda solve issues

---

cpp/include/cudf/reduction.hpp
cpp/src/reductions/reductions.cpp
cpp/tests/reductions/reduction_tests.cpp

Fixes error introduced in #12279 to return the correct boolean value for reductions on empty input for `any(false)` and `all(true)`.
Also fixes incorrectly coded gtest to verify the correct result.
Closes #12373

Fix reductions any/all return value for empty input

---

cpp/src/io/avro/reader_impl.cu
cpp/src/io/csv/reader_impl.cu
cpp/src/io/json/reader_impl.cu
cpp/src/io/orc/reader_impl.cu
cpp/src/io/parquet/reader_impl.cpp
cpp/src/io/utilities/column_buffer.cpp
cpp/src/io/utilities/column_buffer.hpp

When creating a column from an `io::detail::column_buffer` object there is some subtlety in what memory resource should be used. Due to the way cudf's string APIs are designed, string columns in IO initially allocate temporary memory on construction of the `column_buffer` and only later allocate the final buffer to be returned to the user, while for all other types the initial allocation can be directly moved to the output. As a result, using the user-provided memory resource in the constructor of a `column_buffer` is sufficient to guarantee correct behavior for all column types except string columns, which also need a memory resource to be provided in `make_column`. This PR fixes the issue by storing the memory resource provided upon `column_buffer` construction, converting `make_column` …

Use correct memory resource in io::make_column

---

python/cudf/cudf/core/index.py
python/cudf/cudf/tests/test_datetime.py

Fix warnings in test_datetime.py

---

.github/ops-bot.yaml

This PR updates the `ops-bot.yaml` configuration. `external_contributors` and `rerun_tests` aren't valid configuration values at this time.
The [Recently Updated](https://docs.rapids.ai/resources/recently-updated/) check is intended to be used with GitHub Actions.

[skip gpuci] Update `ops-bot.yaml`

---

cpp/src/strings/json/json_path.cu
cpp/tests/strings/json_tests.cpp

Fixes `cudf::strings::get_json_object` to return an empty column if the input column is empty.
Closes #12383

Fix get_json_object to return empty column on empty input

---

cpp/cmake/thirdparty/get_arrow.cmake

When asked to build arrow from source, state that we want a shared library version of OpenSSL instead of a static. That ensures that we use the OpenSSL provided by conda ( which only provides shared ).
Plus in general building against a static OpenSSL is a bad idea as it makes deploying SSL CVE fixes very hard.

When building Arrow shared look for a shared OpenSSL

---

cpp/tests/copying/concatenate_tests.cu
cpp/tests/copying/copy_if_else_nested_tests.cpp
cpp/tests/copying/copy_range_tests.cpp
cpp/tests/copying/copy_tests.cpp
cpp/tests/copying/gather_list_tests.cpp
cpp/tests/copying/gather_struct_tests.cpp
cpp/tests/copying/get_value_tests.cpp
cpp/tests/copying/pack_tests.cpp
cpp/tests/copying/scatter_list_scalar_tests.cpp
cpp/tests/copying/scatter_list_tests.cpp
cpp/tests/copying/scatter_struct_scalar_tests.cpp
cpp/tests/copying/scatter_tests.cpp
cpp/tests/copying/segmented_gather_list_tests.cpp
cpp/tests/copying/shift_tests.cpp
cpp/tests/copying/split_tests.cpp

Fixes gtests source files in `COPYING_TEST` coded in namespace `cudf::test`
No function or test has changed just the test source code reworked per namespaces.

Fix COPYING_TEST: gtests coded in namespace cudf::test

---

.github/workflows/pr.yaml
.github/workflows/test.yaml

This updates GitHub Actions to use the "latest" runner tags instead of tags specific to V100 and driver version. This makes the CI system more robust as we migrate runners from older drivers/hardware to newer drivers/hardware.

Use gpu-latest-1 runner tag

---

cpp/src/io/parquet/writer_impl.cu
cpp/tests/io/parquet_test.cpp

This PR fixes a bug which caused some structures to be passed to the column index encoder incorrectly when writing Parquet files in multiple batches.

Fix bug in Parquet column index encoding

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_dataframe.py

Fix warnings in dataframe.py

---

python/cudf/cudf/tests/test_dataframe.py

There are some minor violations of the new xfail_strict policy that were merged without accounting for that change.

Fix xfail incompatibilities

---

.github/ops-bot.yaml

This PR re-enables the `Recently Updated` check.
It was previously disabled because it was frequently getting stuck in the `Pending` state.
After investigating the logs, I determined that the job was getting killed prematurely due to an insufficient `timeout` value for the Lambda function that executes the code. Therefore, the Lambda function was being killed before the batch job was able to finish updating the statuses on all of the open PRs.
I increased the `timeout` value from 30 seconds to 15 minutes in the commit below which should resolve that problem.
- https://github.com/rapidsai/ops-bot/commit/4148bb03e47998d4c5b75cf0e35d676b9f7614b5

Re-enable `Recently Updated` Check

---

java/ci/Dockerfile.centos7
java/ci/README.md

Update default build image to cuda 11.8

JNI build image default as cuda11.8

---

cpp/include/cudf/detail/utilities/assert.cuh

Since 21.06 `cuff_assert` has been a no-op in release mode. This brings the docs inline with the implementation.
Fixes #12459

Update cudf_assert docs with correct NDEBUG behavior

---

cpp/include/cudf/io/datasource.hpp

Arrow has been upgraded to version 10 in https://github.com/rapidsai/cudf/pull/12327. Unfortunately the new Arrow version trigger new warnings that are treated as compile error:
```
_deps/arrow-src/cpp/src/arrow/result.h(263): error #2810-D: ignoring return value type with "nodiscard" attribute
```
This PR fixes that by temporarily disabling such warnings.

Fix compile issue with arrow 10

---

docs/cudf/source/developer_guide/contributing_guide.md
docs/cudf/source/developer_guide/testing.md
python/cudf/cudf/io/parquet.py
python/cudf/cudf/tests/pytest.ini
python/cudf/cudf/tests/test_reductions.py

This PR fixes a final few warnings introduced in PRs merged after #12406 or with changes that weren't merged into #12406. More importantly, this PR updates the testing suite to always raise uncaught warnings as errors. This is a substantial change to the testing suite that will allow us to proactively react to deprecations in our dependencies, identify areas where pandas/pyarrow/some other dependency handles input data in different ways than us, etc. I've opted for the strictest possible setting, but am open to reviewer requests to be a little more lax with certain classes of warnings.

Raise warnings as errors in the test suite

---

python/cudf/cudf/core/_base_index.py
python/cudf/cudf/core/column/categorical.py
python/cudf/cudf/core/column/column.py
python/cudf/cudf/core/column/lists.py
python/cudf/cudf/core/column/string.py
python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/core/reshape.py
python/dask_cudf/dask_cudf/backends.py

Resolves #12303
This PR removes `int32` hard-coding which are related to `size_type` in `libcudf`. Some of the hard-coding's have been left because they are un-related to `size_type`.

[REVIEW] Remove `int32` hard-coding in python

---

docs/cudf/source/user_guide/pandas-comparison.md
python/cudf/cudf/core/dataframe.py
python/cudf/cudf/utils/utils.py

Resolves: #12472 
This PR links the unsupported iteration APIs to an existing docs section that explains why iteration isn't supported on GPU and has alternative workarounds suggested there already.

[REVIEW] Link unsupported iteration API docstrings

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/core/series.py
python/cudf/cudf/tests/test_concat.py

Fixes: #12485 
This PR fixes the issue where transfer of ListColumn's metadata is not happening when `concat` is performed on two `ListColumn`'s.

[REVIEW] Fix missing metadata transfer in concat for `ListColumn`

---

python/cudf/cudf/core/dataframe.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #12489 
This PR fixes an issue in `DataFrame.transpose` where metadata of some complex types is not being transferred.

[REVIEW] Enable metadata transfer for complex types in transpose

---

cpp/src/transform/one_hot_encode.cu
cpp/tests/transform/one_hot_encode_tests.cpp

`one_hot_encode` to use experimental row comparators

---

python/cudf/cudf/testing/_utils.py
python/cudf/cudf/tests/test_feather.py
python/cudf/cudf/tests/test_hdf.py
python/cudf/cudf/tests/test_json.py
python/cudf/cudf/tests/test_parquet.py
python/cudf/cudf/tests/test_serialize.py
python/dask_cudf/dask_cudf/tests/test_core.py

The pandas testing module was deprecated ages ago and should no longer be used. In general we can simply manually construct the necessary objects to get the same effect.
Resolves #6435

Stop using pandas._testing

---

ci/release/update-version.sh

The `update-versions.sh` script was missing a line to update our rapids-cmake definitions files in the new GitHub Actions style check script. This fixes it.

Update rapids-cmake definitions version in GitHub Actions style checks.

---

cpp/src/reductions/segmented_reductions.cpp
cpp/src/reductions/simple_segmented.cuh

This removes/updates some `TODO` comments from the code after discussions on issue #10432 with @davidwendt.

Update TODOs from issue 10432.

---

cpp/tests/io/orc_test.cpp

A C++ test that requires nvCOMP ZSTD is skipped when the required nvCOMP header is not present. This check does not seem to work correctly, as the test was skipped (on a local system) with nvCOMP 2.5.
This PR modifies the condition to skip the test to use more robust `is_decompression_disabled`.

Fix erroneously skipped ORC ZSTD test

---

cpp/include/cudf/io/csv.hpp
cpp/src/io/csv/writer_impl.cu
cpp/tests/io/csv_test.cpp
java/src/main/java/ai/rapids/cudf/CSVOptions.java
java/src/main/java/ai/rapids/cudf/CSVWriterOptions.java
java/src/main/java/ai/rapids/cudf/QuoteStyle.java
java/src/main/java/ai/rapids/cudf/Table.java
java/src/main/native/src/TableJni.cpp
java/src/test/java/ai/rapids/cudf/TableTest.java

`cudf::io::write_csv()` currently adds quotes around all `STRING` rows that contain "special" characters, including:
1. `,`, or the field delimiter
2. `\n`, or the row/record delimiter
3. `"`, or double quotes
This is in congruence with Pandas conventions for CSV, and allows for strings with such special characters to be read correctly.
If `write_csv()` is used to implement writes for CSV-like formats (such as Hive delimited text files), one notices that quoting conventions would be at odds. Hive delimited text does not automatically quote problematic strings.
This commit adds the option of turning off quoting for `STRING` columns. The erstwhile behaviour is retained as the default; the user must opt into turning off quoting.
Additionally, this commit adds the following:
1. Tests for …

Make string quoting optional on CSV write

---

cpp/include/cudf/io/json.hpp
cpp/src/io/json/reader_impl.cu
cpp/tests/io/arrow_io_source_test.cpp
cpp/tests/io/json_chunked_reader.cpp
cpp/tests/io/json_test.cpp
java/src/main/native/src/TableJni.cpp
python/cudf/cudf/_lib/cpp/io/json.pxd
python/cudf/cudf/_lib/json.pyx

Changes libcudf default JSON reader to the new nested reader. 
The previous default is now called "legacy", so the API is update to match.
C++ tests that used the default reader still do, except for "values" orient tests (will be addressed in https://github.com/rapidsai/cudf/pull/12498) and few cases where tested behavior is not desired in the new reader.
Modified Python and Java call sites to keep the current behavior.

Default `cudf::io::read_json` to nested JSON parser

---

cpp/src/lists/lists_column_factories.cu
cpp/tests/copying/purge_nonempty_nulls_tests.cpp

This makes minor optimization to lists column construction after changes made in https://github.com/rapidsai/cudf/pull/12370. Instead of always calling to `cudf::purge_nonempty_nulls` if the being created column is nullable, `has_nonempty_nulls` is called first to check if there is actually any non-empty nulls to clean up.
Because the logic behind `has_nonempty_nulls` is much simpler than `purge_nonempty_nulls`, especially for deeply nested lists, this can speed up list column creation performance to some extent.
This PR also uncovers a test that should fail in https://github.com/rapidsai/cudf/pull/12370 but it didn't, because non-empty nulls were not checked recursively. On the other hand, `has_nonempty_nulls` used in this PR is called recursively thus this completely fixes the issue …

Optimize `cudf::make_lists_column`

---

cpp/benchmarks/join/join_common.hpp
cpp/benchmarks/join/mixed_join.cu

I was picking up column index `1` while constructing the AST for a table with only 1 column.

Mixed Join benchmark bug due to wrong conditional column

---

cpp/src/structs/utilities.cpp

Similar to https://github.com/rapidsai/cudf/pull/12547, this PR mitigates the performance regression in `superimpose_nulls` and `push_down_nulls` when `purge_nonempty_nulls` is called whenever there is a nullable lists or strings column. With this fix, `purge_nonempty_nulls` is called only when it is absolutely needed (i.e., there are actual non-empty nulls in the input).
Closes https://github.com/rapidsai/cudf/issues/12550.

Use `has_nonempty_nulls` instead of `may_contain_non_empty_nulls` in `superimpose_nulls` and `push_down_nulls`

---

java/src/main/java/ai/rapids/cudf/QuoteStyle.java

When `QuoteStyle` was added in #12539, it was inadvertently made package- private to `ai.rapids.cudf`. This makes it unusable from `spark-rapids` plugin.
This commit makes the enum publicly accessible.
Signed-off-by: MithunR <mythrocks@gmail.com>

Make JNI QuoteStyle accessible outside ai.rapids.cudf

---

python/cudf/cudf/core/column/lists.py
python/cudf/cudf/tests/test_list.py

As usual, for (nested) struct dtypes, libcudf doesn't preserve field names so we must fix things up in post.
Closes #12248.

lists: Transfer dtypes correctly through list.get

---

python/cudf/cudf/core/column/timedelta.py
python/cudf/cudf/tests/test_timedelta.py

Now that we implement proper floor division in libcudf, don't remap floordiv to truediv when dividing timedeltas (first introduced in 826f6267f1). 
Closes #12393.

timedelta: Don't go via float intermediates for floordiv

---

build.sh
ci/gpu/build.sh
ci/test_cpp.sh
cpp/src/io/text/data_chunk_source_factories.cpp

`datasource_chunk_reader.get_next_chunk()` called `device_read_async()` without waiting on the returned Future.
Should fix the CI fail in https://github.com/rapidsai/cudf/pull/12574
cc. @vuule

Fixing BUG, `get_next_chunk()` should use the blocking function `device_read()`

---

java/src/main/java/ai/rapids/cudf/JCudfSerialization.java
java/src/test/java/ai/rapids/cudf/TableTest.java

This fixes a long-standing problem in JCudfSerialization where sliced columns do not have the correct null counts when serialized and then deserialized.  Previously the null count of the original column was used as a "good enough"  proxy, and this was fine as long as it was only interpreted as a boolean "do I need to worry about nulls" signal.  However it can lead to bad behavior for applications that use the null count directly, such as for statistics in a file footer.
This resolves the issue by explicitly treating sliced column null counts as unknown when it cannot be determined what the true null count is without scanning the sliced validity buffer.  By using the unknown null count sentinel value in the serialized data stream, the deserialized column will compute the null count on …

Fix incorrect null counts for sliced columns in JCudfSerialization

---

cpp/src/io/parquet/page_data.cu
cpp/src/io/parquet/parquet_gpu.hpp
cpp/src/io/parquet/reader_impl_preprocess.cu

Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-23.02 to branch-23.04 [skip gpuci]

---

cpp/include/cudf/detail/aggregation/aggregation.cuh
cpp/include/cudf/detail/aggregation/aggregation.hpp
cpp/src/rolling/detail/rolling.cuh
cpp/tests/rolling/empty_input_test.cpp

Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.02 to branch-23.04

---

python/cudf/cudf/core/buffer/spillable_buffer.py
python/cudf/cudf/core/buffer/utils.py
python/cudf/cudf/tests/test_spilling.py

#12587 exposed a bug triggered when `as_buffer()` is given a pointer already owned by another spillable buffer. In this PR, we make this illegal and return a `SpillableBufferSlice` instead. 
cc. @galipremsagar

Handle when spillable buffers own each other 

---

java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java

#12548 introduced a number of GPU resource leaks in ColumnVectorTest.  This cleans them up by wrapping them in `try` blocks.

Fix leaks in ColumnVectorTest

---

java/ci/README.md
java/pom.xml

Update JNI version to 23.04.0-SNAPSHOT

Init JNI version 23.04.0-SNAPSHOT

---

python/cudf/cudf/core/indexed_frame.py

This PR fixes a mask data corruption issue encountered while working on https://github.com/rapidsai/cudf/pull/12619.
`column_empty` actually returns un-initialized values, but we would want a fully initialized mask column here. Hence it is very inconsistent to test for a failure here, which is the reason it has been passing in CI and many of the local builds.

[REVIEW] Fix a mask data corruption in UDF

---

ci/release/update-version.sh
python/cudf/setup.py
python/dask_cudf/setup.py

Now that wheel CI is enabled, the nightly index will contain next release wheels, so we need to ensure those don't get installed while still building this release.

Pin wheel dependencies to same RAPIDS release

---

.github/workflows/build.yaml

When initially created, the GitHub Actions scripts that upload conda packages would upload all packages that were built indiscriminately.
As a result, the `libcudf-example` package has been uploading to Anaconda.org. It was not previously uploaded to Anaconda.org prior to migrating to GitHub Actions.
While this isn't a huge deal, I recently added some functionality ([here](https://github.com/rapidsai/shared-action-workflows/pull/33)) that allows us to specify package names that shouldn't be uploaded to Anaconda.org in our workflows.
This PR adds the `libcudf-example` package to the list of packages that should not be uploaded to Anaconda.org

Don't upload `libcudf-example` to Anaconda.org

---

python/cudf/cudf/core/indexed_frame.py
python/cudf/cudf/tests/test_dataframe.py

Fixes: #12648 
This PR fixes an error in the `round` API when a bool column is present. The changes include cleaning up the pytest.

[REVIEW] Handle bool types in `round` API
